### DISCUSSION TITLE
No converter available for 'brightness_move' Moes dimmer MS-105Z

### DISCUSSION THREAD

**Discussion by knallhare** [Koenkk/zigbee2mqtt#10025] [Devices]
Hi,

I have a Moes MS-105Z dimmer:
https://www.zigbee2mqtt.io/devices/MS-105Z.html

In the documentation it says you can send payload:
{
  "brightness_move": -40
}

To:
zigbee2mqtt/FRIENDLY_NAME/set

But when I do this it does not work. This is what the zigbee2mqtt logs says:
error No converter available for 'brightness_move' (-40)

Here is my automation:
```
- alias: test dimmer brightness 4
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/btn1/action
    payload: hold
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/dimmer2/set
      payload: '{"brightness_move": -40}'
```
