### DISCUSSION TITLE
Can't load frontend - docker image

### DISCUSSION THREAD

**Discussion by jmceara** [Koenkk/zigbee2mqtt#10204] [General]
Hi!
I'm trying to run z2m using docker-compose. Everything seens to being loaded fine, except frontend.
I'm running on debian 11 (fresh install), firewall disabled (no rules at all), containers looks runing fine, but can't access frontend....seens that is not being loaded at container level, but I'm not sure how to check this.
This is my configuration.yaml file for this instance:
```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt-b2
  # MQTT server URL
  server: 'mqtt://172.16.2.23'
  # MQTT server authentication, uncomment if required:
  user: mqttuser
  password: HIDDEN

# Serial settings
serial:
  # I'm using ZBridge + tasmota
  port: tcp://172.16.2.48:8888
  adapter: ezsp

frontend:
  port: 8080
  host: 0.0.0.0

advanced:
  # Optional: Logging level, options: debug, info, warn, error (default: info)
  log_level: debug

```

My docker-compose file:
```
version: '3.8'
services:
  zigbee2mqtt_b2:
    container_name: zigbee2mqtt_b2
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data-b2:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=America/Sao_Paulo
    devices:
      # Make sure this matched your adapter location
      - /dev/null:/dev/ttyACM0
```

And finally, the log (that doesn't show anything related to the frontend):
```
z2m@zigbee2mqtt-b2:~$ docker-compose up zigbee2mqtt_b2
[+] Running 1/0
 ⠿ Container zigbee2mqtt_b2  Created                                                                                                                      0.0s
Attaching to zigbee2mqtt_b2
zigbee2mqtt_b2  | Using '/app/data' as data directory
zigbee2mqtt_b2  | Zigbee2MQTT:debug 2021-12-16 11:35:07: Loaded state from file /app/data/state.json
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:07: Logging to console and directory: '/app/data/log/2021-12-16.11-35-05' filename: log.txt
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:07: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:07: Starting zigbee-herdsman (0.13.176)
zigbee2mqtt_b2  | Zigbee2MQTT:debug 2021-12-16 11:35:07: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"tcp://172.16.2.48:8888"}}'
zigbee2mqtt_b2  | Assertion failed
zigbee2mqtt_b2  | Assertion failed
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:13: zigbee-herdsman started (resumed)
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:13: Coordinator firmware version: '{"meta":{"maintrel":"9 ","majorrel":"6","minorrel":"7","product":8,"revision":"6.7.9.0 build 405"},"type":"EZSP v8"}'
zigbee2mqtt_b2  | Zigbee2MQTT:debug 2021-12-16 11:35:13: Zigbee network parameters: {"channel":11,"extendedPanID":221,"panID":6754}
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:13: Currently 0 devices are joined:
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:13: Zigbee: disabling joining new devices.
zigbee2mqtt_b2  | Zigbee2MQTT:info  2021-12-16 11:35:13: Connecting to MQTT server at mqtt://172.16.2.23
zigbee2mqtt_b2  | Zigbee2MQTT:debug 2021-12-16 11:35:13: Using MQTT login with username: mqttuser
```

And docker ps:
```
root@zigbee2mqtt-b2:~# docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS              PORTS                                       NAMES
101a472bc2de   koenkk/zigbee2mqtt   "docker-entrypoint.s…"   51 minutes ago   Up About a minute   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   zigbee2mqtt_b2
```
