### DISCUSSION TITLE
mqtt.publish data issue

### DISCUSSION THREAD

**Discussion by habitoti** [Koenkk/zigbee2mqtt#10501] [General]
Hi,

I am trying to call the Homeassistant mqtt.publish service to update the network map data. So I call it with topic _zigbee2mqtt/bridge/request/networkmap_ and _type:raw_ and _routes: true_ like so:

```
service: mqtt.publish
data:
  topic: zigbee2mqtt/bridge/request/networkmap
  payload: '{type: raw, routes: true}'
```

However, it produces this error when processing the response:

``` 
2022-01-02 09:43:33 ERROR (MainThread) [homeassistant.util.logging] Exception in attributes_message_received when handling msg on 'zigbee2mqtt/bridge/response/networkmap': '{"data":{},"error":"Type '{type: raw, routes: true}' not supported, allowed are: raw,graphviz,plantuml","status":"error"}' 
```

So it seems to take the full payload as TYPE property value. So I changed payload just to “raw”, and indeed that call succeeds and produces a network map now, however as “routes” defaults to false, how can I set it to true? What am I missing?
