### DISCUSSION TITLE
Unable to setup 2nd Zigbee network

### DISCUSSION THREAD

**Discussion by aldur11** [Koenkk/zigbee2mqtt#10631] [Devices]
Hello,

I'm attempting to setup a 2nd zigbee network. The 1st and 2nd network are using LAUNCHXL-CC26X2R1 for the coordinators running on raspberry pi 4's. The first network is setup and working just fine however, when I try to setup the second network I get the following error.
`Zigbee2MQTT:error 2022-01-06 16:40:23: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby`

The error seems straight forward, so in the configuration.yaml file I changed the pan ID and extend pan ID to something that the other coordinator isn't using. But I still get the same error. I've also tried reflashing the 2nd coordinator with uniflash, but it didn't help.

Any ideas on how to get a second zigbee network working?

Below is the log and configuration.yaml outputs.

```> zigbee2mqtt@1.22.2 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2022-01-06 16:43:43: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-01-06.16-43-41' filename: log.txt
Zigbee2MQTT:info  2022-01-06 16:43:43: Starting Zigbee2MQTT version 1.22.2 (commit #301ba14b)
Zigbee2MQTT:info  2022-01-06 16:43:43: Starting zigbee-herdsman (0.13.188)
Zigbee2MQTT:error 2022-01-06 16:44:48: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-06 16:44:48: Failed to start zigbee
Zigbee2MQTT:error 2022-01-06 16:44:48: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-06 16:44:48: Exiting...
Zigbee2MQTT:error 2022-01-06 16:44:48: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:100:27)
    at start (/opt/zigbee2mqtt/index.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.22.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-06T23_44_48_620Z-debug.log
```

configuration.yaml

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt02
  server: mqtt://10.10.12.108
  user: xxxx
  password: xxxx
serial:
  port: /dev/ttyACM0
advanced:
  network_key: xxxxx
  ext_pan_id:
    - 270
    - 270
    - 270
    - 270
    - 270
    - 270
    - 270
    - 270
  pan_id: 12295
frontend:
  port: 8080
  host: 10.10.12.217
```

Note that if I use a Conbee II as the coordinator of the 2nd zigbee network, but nothing is able to join the network.

**Comment by aldur11** [comment]
I got it figured out. Just incase anyone runs into this problem I'll include the fix.

So I ended up reflashing my pi4 and reinstalling z2mqtt. However, instead of starting it up with the following config, like I did last time.

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt02
  server: mqtt://10.10.12.108
  user: xxx
  password: xxx
serial:
  port: /dev/ttyACM0
advanced:
  network_key: GENERATE

frontend:
  port: 8080
  host: 10.10.12.217
```
I ended up adding the `pan_id: GENERATE` statement before the initial startup so my config looked like this.
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt02
  server: mqtt://10.10.12.108
  user: xxx
  password: xxx
serial:
  port: /dev/ttyACM0
advanced:
  network_key: GENERATE
  pan_id: GENERATE

frontend:
  port: 8080
  host: 10.10.12.217
```
After that I started z2mqtt using the `npm start` command and it came up no problem.

The weird thing here is that I tried using the `pan_id: GENERATE` statement in my previous tries, the only difference was I didn't do it on the initial start of z2mqtt. 

So what it seems like to me is that I couldn't change the PAN ID after the initial startup of z2mqtt as no matter what it was changed it I had a PAN ID conflict with the other zigbee network.
