### DISCUSSION TITLE
Serial by port/name and Conbee II

### DISCUSSION THREAD

**Discussion by SHxKM** [Koenkk/zigbee2mqtt#10689] [General]
I see “serial port by name” and “serial port by ID” being referenced in the context of migrating to new hardware, etc…

I have never seen any advice other than:

```yaml
serial:
  port: /dev/ttyACM0
  adapter: deconz
```

for the Conbee II. Does that mean this is the only option? And that migrating to another Conbee II will require re-pairing anyway?
