### DISCUSSION TITLE
Installing with docker-compose on Debian Bullseye headless.

### DISCUSSION THREAD

**Discussion by lgLindstrom** [Koenkk/zigbee2mqtt#10692] [General]
Hi

I have a PC with Debian Bullseye installed, headless. Following your install instructions I try to find on which port the USB stick is installed. The output from dmesg don't makes me any wiser .

```
[93943.946067] docker0: port 1(vethc3edb1c) entered disabled state
[180538.242233] i915 0000:00:02.0: [drm] HPD interrupt storm detected on connector DP-1: switching from hotplug detection to polling
[180546.126342] usb 1-5: new full-speed USB device number 2 using xhci_hcd
[180546.530385] usb 1-5: device descriptor read/64, error -71
[180546.791906] usb 1-5: New USB device found, idVendor=0451, idProduct=16a8, bcdDevice= 0.09
[180546.791912] usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[180546.791915] usb 1-5: Product: TI CC2531 USB CDC
[180546.791918] usb 1-5: Manufacturer: Texas Instruments
[180546.791920] usb 1-5: SerialNumber: __0X00124B001936A495
[180546.799432] usb 1-5: USB disconnect, device number 2
[180546.812821] usbcore: registered new interface driver cdc_acm
[180546.812822] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[180548.162400] usb 1-5: new full-speed USB device number 3 using xhci_hcd
[180548.317478] usb 1-5: New USB device found, idVendor=0451, idProduct=16a8, bcdDevice= 0.09
[180548.317480] usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[180548.317481] usb 1-5: Product: TI CC2531 USB CDC
[180548.317482] usb 1-5: Manufacturer: Texas Instruments
[180548.317483] usb 1-5: SerialNumber: __0X00124B001936A495
[180548.319092] cdc_acm 1-5:1.0: ttyACM0: USB ACM device
[181494.465499] br-148faf2870ae: port 1(veth93789bb) entered blocking state
```

Is there another way to do find the port???

**Comment by lgLindstrom** [comment]
Trial and error methods have led me to believe that my USB is mounted as ttyACM0.  Using this docker-compose file : .....

```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyACM0:/dev/ttUSB0
```

..... gives me this error 

```
zigbee2mqtt      | Zigbee2MQTT:info  2022-01-12 09:56:14: Logging to console and directory: '/app/data/log/2022-01-12.09-56-14' filename: log.txt
zigbee2mqtt      | Zigbee2MQTT:info  2022-01-12 09:56:14: Starting Zigbee2MQTT version 1.22.2 (commit #414c51f)
zigbee2mqtt      | Zigbee2MQTT:info  2022-01-12 09:56:14: Starting zigbee-herdsman (0.13.188)
zigbee2mqtt      | Zigbee2MQTT:error 2022-01-12 09:56:14: Error while starting zigbee-herdsman
zigbee2mqtt      | Zigbee2MQTT:error 2022-01-12 09:56:14: Failed to start zigbee
zigbee2mqtt      | Zigbee2MQTT:error 2022-01-12 09:56:14: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
zigbee2mqtt      | Zigbee2MQTT:error 2022-01-12 09:56:14: Exiting...
zigbee2mqtt      | Zigbee2MQTT:error 2022-01-12 09:56:14: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
zigbee2mqtt      |     at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
zigbee2mqtt      |     at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee2mqtt      |     at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
zigbee2mqtt exited with code 1

```


Seems like the serial port causing the error.  Is there a problem with the docker host (Debian Bullseye ).. 

Can anyone help me out ???  PLEASE :)

**Reply by Koenkk** [reply]
Changing `- /dev/ttyACM0:/dev/ttUSB0` to `- /dev/ttyACM0:/dev/ttyACM0` should fix it IF the adapter is indeed on `/dev/ttyACM0` (see how to determine the path: https://www.zigbee2mqtt.io/guide/installation/01_linux.html#determine-location-of-the-adapter-and-checking-user-permissions)

**Comment by lgLindstrom** [comment]
One step forward ...

Now I am getting this error from zigbee2mqtt. Is my adapter broken???

```
sh_zigbee2mqtt    | Zigbee2MQTT:debug 2022-04-11 10:48:03: Can't load state from file /app/data/state.json (doesn't exist)
sh_zigbee2mqtt    | Zigbee2MQTT:info  2022-04-11 10:48:03: Logging to console only'
sh_zigbee2mqtt    | Zigbee2MQTT:info  2022-04-11 10:48:03: Starting Zigbee2MQTT version 1.25.0 (commit #6f1460e)
sh_zigbee2mqtt    | Zigbee2MQTT:info  2022-04-11 10:48:03: Starting zigbee-herdsman (0.14.20)
sh_zigbee2mqtt    | Zigbee2MQTT:debug 2022-04-11 10:48:03: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
sh_zigbee2mqtt    | Zigbee2MQTT:error 2022-04-11 10:48:23: Error while starting zigbee-herdsman
sh_zigbee2mqtt    | Zigbee2MQTT:error 2022-04-11 10:48:23: Failed to start zigbee
sh_zigbee2mqtt    | Zigbee2MQTT:error 2022-04-11 10:48:23: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
sh_zigbee2mqtt    | Zigbee2MQTT:error 2022-04-11 10:48:23: Exiting...
sh_zigbee2mqtt    | Zigbee2MQTT:error 2022-04-11 10:48:23: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
sh_zigbee2mqtt    |     at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
sh_zigbee2mqtt    |     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
sh_zigbee2mqtt    |     at Zigbee.start (/app/lib/zigbee.ts:58:27)
sh_zigbee2mqtt    |     at Controller.start (/app/lib/controller.ts:100:27)
sh_zigbee2mqtt    |     at start (/app/index.js:101:5)
```

My docker compose is:
```
  sh_zigbee2mqtt:
    container_name: sh_zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
        - ./zigbee2mqtt/data:/app/data:rw
        - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Stockholm
    devices:
       - /dev/ttyACM0:/dev/ttyACM0
```

and my config file is:

```
permit_join: false
mqtt:
  server: mqtt://sh_mqtt:1883
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
advanced:
  log_level: debug
  log_output:
    - console
```
