### DISCUSSION TITLE
Zigbee2mqtt does not work after host migration - but no error message

### DISCUSSION THREAD

**Discussion by klaute** [Koenkk/zigbee2mqtt#10751] [General]
Hello,

I'm running a zigbee2mqtt server for about one jear now. But now it's time to migrate the service to another server.
At first it looked like an easy task. But in the end the new server can not control my philips hue light bulb.
I only got one of those light bulb.

**These are the information about the working system:**

```
Zigbee2mqtt (not docker, version 1.21.0 (commit #70891eec))
zigbee-herdsman (0.13.124)
Mosquitto (not docker, version 1.5.7)
Armbian Linux on a Cubietruck with a 5V/12A power supply 
Zigbee usb Device (ID 0451:16a8 Texas Instruments, Inc.)
```

Works perfect even if I connect it using a passive (non self powered) USB hub.
Successfully paired Philips hue light bulb.
Can control everything.
The distance between the USB stick and the device is about 8 meters with a wall between them.

**New system which is not working:**

```
Latest Arch Linux on a intel based machine.
Zigbee2mqtt (latest docker, version 1.22.2 (commit #414c51f)) - Copied all of the files from the data folder to the new location
zigbee-herdsman (0.13.188))
Mosquittto (latest docker, version 2.0.14) - same configuration as before
Same zigbee stick
```

All logging set to maximum verbosity, no error occurre in the logs.

But it does not work, even with (or without) a passive usb hub and also not with an self-powered USB hub.
I can't control the light bulb.

The command I use:
	`mosquitto_pub -i grumlok -d -h localhost -t zigbee2mqtt/0x001788010b04166b/set -m "{\"brightness\":50}"`

Then I resetted the light bulb using Bluetooth and also removed the coordinator and database file from the zigbee2mqtt data-folder.
The light bulb joins the zigbee network perfect as it should.
But I can’t control it, it does not turn off/on wether can not control the brightness.
Even when I place the light bulb within a distance of 1 meter.

Next I applied a username and password zu the mosquitto server, and configured the zigbee2mqtt.
But it does not have any effect.

In the log file again no error is shown. I'm confused about what the problem is.

Maybe there is no relation to it but also the Webinterface of zigbee2mqtt does not work.

But I'm sure that the **mosquitto server itself on the new machine** works correct, because if I configure zigbee2mqtt
**on the old system** to connect to the new server's mosquitto, the light bulb works as expected.

From my point of view it's zigbee2mqtt which causes the problem?!

Maybe someone has got an hint to me what I can try out next?

Thank you!
Kai

These are my configuration files.

modquitto.conf:
```
listener 1883
allow_anonymous false
password_file /mosquitto_passwd
```

zigbee2mqtt configuration.yaml:
```
homeassistant: false
permit_join: true
advanced:
  log_level: debug
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: mqtt
  password: mqtt
frontend:
  port: 8085
experimental:
  new_api: true
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDE5839-if00
devices:
  '0x001788010b04166b':
    friendly_name: '0x001788010b04166b'
```

docker-compose.yml:
```
  version: '3'
  services:

    mqtt:
      image: eclipse-mosquitto:2.0
      restart: unless-stopped
      environment:
        - TZ=Europe/Berlin
      volumes:
        - "/opt/docker_container/mosquitto/mosquitto-data:/mosquitto"
      ports:
        - "1883:1883"
        - "9001:9001"
      command: "mosquitto -v -c /mosquitto-no-auth.conf"

    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      restart: always
      group_add:
        - dialout
      environment:
        - TZ=Europe/Berlin
      network_mode: host
      ports:
        - "8085:8085"
      volumes:
        - ../data:/app/data
        - /run/udev:/run/udev:ro
      devices:
        # CC251
        #- /dev/ttyUSB_cc2531:/dev/ttyACM0
        # CC2530 / GBAN GB2530S
        #- /dev/ttyUSB_cc2530:/dev/ttyACM0
        #the device to control zigbee devices
        - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDE5839-if00:/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDE5839-if00
```
