### DISCUSSION TITLE
Error: Failed to connect to the adapter

### DISCUSSION THREAD

**Discussion by backupandforkacc** [Koenkk/zigbee2mqtt#10808] [Devices]
zigbee2mqtt worked for several weeks until I restarted my server. I now get the error mentioned below. 

```
$ ls /dev/ttyACM*
/dev/ttyACM0  
```

```
Zigbee2MQTT:info  2022-01-15 12:32:37: Logging to console and directory: '/app/data/log/2022-01-15.12-32-36' filename: log.txt
Zigbee2MQTT:info  2022-01-15 12:32:37: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
Zigbee2MQTT:info  2022-01-15 12:32:37: Starting zigbee-herdsman (0.13.176)
Zigbee2MQTT:error 2022-01-15 12:32:58: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-15 12:32:58: Failed to start zigbee
Zigbee2MQTT:error 2022-01-15 12:32:58: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-15 12:32:58: Exiting...
Zigbee2MQTT:error 2022-01-15 12:32:58: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)


```

I had two CC2531 sticks plugged in when I configurated zigbee2mqtt, but even if I stick the second one in and change the configuration to ttyACM1, I get an error:

```
simon@simon-itx:~$ ls /dev/ttyACM*
/dev/ttyACM0  /dev/ttyACM1

Zigbee2MQTT:info  2022-01-15 12:37:06: Logging to console and directory: '/app/data/log/2022-01-15.12-37-04' filename: log.txt
Zigbee2MQTT:info  2022-01-15 12:37:06: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
Zigbee2MQTT:info  2022-01-15 12:37:06: Starting zigbee-herdsman (0.13.176)
Zigbee2MQTT:error 2022-01-15 12:37:06: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-15 12:37:06: Failed to start zigbee
Zigbee2MQTT:error 2022-01-15 12:37:06: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-15 12:37:06: Exiting...
Zigbee2MQTT:error 2022-01-15 12:37:06: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM1'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12




```

**Comment by backupandforkacc** [comment]
Could solve it by myself, but post it for others to know: 

I unplugged the USB and plugged it in again. Then restarted zigbee2mqtt.

**Comment by m0wlheld** [comment]
You should use the device path at /dev/serial/by-id, because opposite to the symlinks /dev/tty* they are stable.

**Comment by backupandforkacc** [comment]
Many thanks, but this leads to an error:


```
~/Downloads/zigbee2mqtt$ sudo docker-compose up
Starting zigbee2mqtt ... error

ERROR: for zigbee2mqtt  Cannot start service zigbee2mqtt: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory

ERROR: for zigbee2mqtt  Cannot start service zigbee2mqtt: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory
ERROR: Encountered errors while bringing up the project.

```

my configuration.yaml:
(deleted user and password)

```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.103.44
  user: 
  password: 
serial:
  port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCDF27D-if00
devices:
  '0x00158d0004470aea':
    friendly_name: '0x00158d0005570aea'
  '0x00158d00044b1488':
    friendly_name: '0x00158d00055b1488'
  '0x00158d00027864ea':
    friendly_name: '0x00158d00027564ea'
  '0x00158d000444589e':
    friendly_name: '0x00158d000455589e'
  '0x00158d0004066f44':
    friendly_name: '0x00158d1104066f44'


```
