### DISCUSSION TITLE
no frontend reachable

### DISCUSSION THREAD

**Discussion by shizen1** [Koenkk/zigbee2mqtt#10881] [General]
Hello,

I have activated the frontend, with:
`frontend:
  port: 8000
  host: 192.168.xx.xx`

But the frontend is not accessible via the browser.
Unfortunately, I did not receive an error message.

Does anyone have a tip for me?

Greetings

**Comment by lbt** [comment]
Try running: 
sudo netstat -lnp | grep node

This will tell you if it's listening on that port and address

**Reply by shizen1** [reply]
thanks, but no one listen on Port 8000.
I try nmap, but no service on this Port :-(

i think the web-service is not running. But why?

**Reply by shizen1** [reply]
i started it from the directory with:
`npm start`
And the frontend is there. :-o

**Reply by shizen1** [reply]
But why is the frontend not running if i use a daemon with systemctl?

**Reply by shizen1** [reply]
the service must run as root :-(

**Reply by lbt** [reply]
The service is started by the main (root) systemd session (as opposed to a user session) but it runs as a normal user.

See line 12 in the service file here:  https://www.zigbee2mqtt.io/guide/installation/01_linux.html#optional-running-as-a-daemon-with-systemctl

**Reply by shizen1** [reply]
sorry, i must change the User=pi to User=root.
And now, everything is running. But i don't no why? I think is not the right way.

**Reply by lbt** [reply]
That is the wrong thing to do.

The user should be "pi" (assuming you are using Raspberry Pi OS?)
You probably missed a step in the installation: https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing
This should all be done logged in as the "pi" user.

You can probably fix this by stopping the service and running:
`sudo chown -R pi:pi /opt/zigbee2mqtt`
and then restarting the service with user=pi
You may need to run `sudo systemct daemon-reload`

**Reply by shizen1** [reply]
yesssss, thanks a lot

**Reply by Roaders** [reply]
I have the same issue. I followed all the installation instructions logged in as user pi. I have `User=pi` in my systelctl config. When I do `ls -la` in `/opt/zigbee2mqtt` everything is owned by pi. My configuration.yaml:

```
homeassistant: false
permit_join: true
fontend: true
mqtt:
  base_topic: zigbee2mqtt
```

there are no logs or any mention of frontend when starting.

What can I try next to get this working?

Many Thanks

**Reply by Roaders** [reply]
I also did netstat to see if anything is running on `8080` and there wasn't.

**Reply by lux73** [reply]
try to configure the Port

`port: 8000`

**Reply by Roaders** [reply]
nope, same. I tried just adding the port and I tried adding port and host:

```
homeassistant: false
permit_join: true
fontend:
  port: 8000
  host: 192.168.86.100
```

BTW: I hate yaml and don't really get it. I assume that it would throw an exception if I had foramtted the yaml incorrectly?

Pretty sure that I am doing something stupid here but I've checked everything I can think of.
Thanks

**Reply by lux73** [reply]
pls post your whole configuration.yaml

amd yes .yaml is very case seinsitive - e.g. one incorrect space and the system is not starting

**Reply by Roaders** [reply]
config.yaml:

```
homeassistant: false
permit_join: true
fontend:
  port: 8000
  host: 192.168.86.100
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: HIDDEN
  password: HIDDEN
serial:
  port: /dev/ttyACM0
advanced:
  network_key:
    - 233
    - 217
    - 108
    - various other values [edited]
    - 161
    - 78
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_output:
    - console
devices:
  '0x00158d00070036dd':
    friendly_name: CinemaButton
    legacy: false
  '0x00158d0007104fb6':
    friendly_name: PantryDoor
  '0x00158d0006f0d280':
    friendly_name: KitchenMotion
  '0x00158d0007c45f25':
    friendly_name: 'UtilityWaterSensor'
device_options:
  legacy: false

```
