### DISCUSSION TITLE
Working kubernetes deployment?

### DISCUSSION THREAD

**Discussion by OlafKocanda** [Koenkk/zigbee2mqtt#10899] [General]
Hi there,

anyone has a working kubernetes deployment including configmaps?

Mine does not seem to work:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Berlin
            - name: ZIGBEE2MQTT_CONFIG
              value: "/config" #/config
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: "mqtt://<Service-IP>"
            - name: ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API
              value: "true"
            - name: ZIGBEEMQTT_CONFIG_HOMEASSISTANT
              value: "true"
          image: koenkk/zigbee2mqtt:latest-dev
#          image: lansible/zigbee2mqtt:master
          name: zigbee2mqtt
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /app/data
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: zigbee2mqtt-config
              mountPath: /config
              readOnly: false
              subPath: configuration.yaml
            - name: ttyacm
              mountPath: /dev/ttyACM0
              
      volumes:
        - name: zigbee2mqtt-data
          hostPath:
            path: /app
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
```
Either not loading the configmaps, or struggling at startup with errors like:
```
 Error: EROFS: read-only file system, open '/config'
```
or
```
Error: EISDIR: illegal operation on a directory, read
```

playing around with the configmap and its deployment.
Looking forward for some help here!

**Comment by OlafKocanda** [comment]
I figured it out, the above was pretty bad...
If someone is interested for a working Kubernetes zigbee2mqtt (without helm), here is the deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER # optional - can also be configured in the configuration.yaml in the configmap
              value: "mqtt://mosquitto"
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /data
            - name: zigbee2mqtt-config
              mountPath: /app/configuration.yaml
              subPath: configuration.yaml
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: ttyacm
              mountPath: /dev/ttyACM0
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
```

Here is the pvc:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

```

and here is the service:
```
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  ports:
    - name: zigbee2mqtt
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: zigbee2mqtt
status:
  loadBalancer: {}
```
And here the configmap 
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: homeassistant
  labels:
    app: zigbee2mqtt
data:
  configuration.yaml: |-

    # Let new devices join our zigbee network
    permit_join: true
    # Home Assistant integration (MQTT discovery)
    homeassistant: true
    # Docker-Compose makes the MQTT-Server available using "mqtt" hostname
    # MQTT server URL
    mqtt:
      base_topic: zigbee2mqtt
      server: "mqtt://mosquitto.homeassistant" # mqtt://<name_of_pod>.<name_of_namespace> (mosquitto)
    # Zigbee Adapter path
    serial:
      port: /dev/ttyACM0
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8080
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      #network_key: GENERATE
      #log_output: ["console"]
      log_level: debug
      log_output:
      - console
      - file

    ## Map devices to persistent /data directory
    devices: /data/devices.yaml
    groups: /data/groups.yaml
```

of course you need an MQTT broker like mosquitto. If you need any help, feel free to write / ping me!

**Reply by MaximUltimatum** [reply]
[Given config map file isn't used by z2m, see also](https://github.com/Koenkk/zigbee2mqtt/discussions/10899#discussioncomment-9136585)

**Comment by Slyke** [comment]
I get the following error:
```
Using '/app/data' as data directory
Creating configuration file...
Zigbee2MQTT:debug 2022-10-18 09:45:58: Can't load state from file /app/data/state.json (doesn't exist)
Zigbee2MQTT:info  2022-10-18 09:45:58: Logging to console and directory: '/app/data/log/2022-10-18.09-45-58' filename: log.txt
Zigbee2MQTT:info  2022-10-18 09:45:58: Starting Zigbee2MQTT version 1.28.0 (commit #03ba647)
Zigbee2MQTT:info  2022-10-18 09:45:58: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:debug 2022-10-18 09:45:58: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:error 2022-10-18 09:45:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-18 09:45:59: Failed to start zigbee
Zigbee2MQTT:error 2022-10-18 09:45:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-18 09:45:59: Exiting...
Zigbee2MQTT:error 2022-10-18 09:45:59: Error: Error while opening serialport 'Error: Error: Operation not permitted, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
```

I have setup affinities to only run on nodes that have a label indicating that they have a Zigbee USB stick, and I can see it in when `ls`ing `/dev/`: `crw-rw---- 1 root dialout 188,  0 Oct 18 03:40 /dev/ttyUSB0`

I also tried setting permissions to `666`:
```
sudo chmod 666 /dev/ttyACM0
```

How did you get it working? I'm using containerd btw.

Edit:

Nevermind! I forgot to include security context in the deployment config:
```
securityContext:
      privileged: true
```

**Comment by OlafKocanda** [comment]
@Slyke Have you ever managed to run an ingress / ingressroute on it? I am trying to reach the zigbee2mqtt from outside the cluster and deployed the following configmap:
`---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt-ingress-route
  namespace: homeassistant
  labels:
    app: zigbee2mqtt
spec:
  entryPoints:
    - web #later websecure and tls on (https)
  routes:
  - match: PathPrefix(`/zigbee`)
    kind: Rule
    services:
    - name: zigbee2mqtt
      port: 8080
      kind: Service
  tls: {}
`

However, entering the address http://<IP_ADDRESS>:8080/zigbee is not working.

**Comment by plinford** [comment]
I have this working.  I defined the service as a loadbalancer.   I use metallb.

I had an issue were the usb dongle would be created as a directory that would prevent the container from starting.  This might be Rancher related, but solved it by moving to a ethernet zigbee coordinator.

**Reply by R-Nabil** [reply]
Could you share your working setup ? I'm struggling to get mine to work with an ethernet adapter

**Comment by JimKlapwijk** [comment]
Does anyone have a working solution without having a privileged container?

**Comment by craigcabrey** [comment]
Here is mine, though occasionally its MQTT hangs? Haven't figured that out yet.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app.kubernetes.io/name: zigbee2mqtt
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: '@monthly'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: docker.io/koenkk/zigbee2mqtt:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Chicago
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt
```
