### DISCUSSION TITLE
Configuring Docker for ethernet coordinator

### DISCUSSION THREAD

**Discussion by Josov** [Koenkk/zigbee2mqtt#10937] [Devices]
I have got a Raspberry Pi with Docker installed and would like to run z2m in a container using docker-compose (or eventually docker). The coordinator is a SmartLight Zigbee LAN adapter, the SLZB-05 on port: 6638.  How should I configure the docker compose file for the ethernet Zigbee LAN adapter?

**Comment by JackTalisker** [comment]
This is my zigbee2mqtt docker compose section for a sonoff wifi coordinator with tasmota fw:
 
```
zigbee2mqtt:
   container_name: zigbee2mqtt
   image: koenkk/zigbee2mqtt
   volumes:
   - "/home/pi/zigbee2mqtt:/app/data"
   devices:
   - /dev/null:/dev/ttyACM0
   environment:
   - "TZ=Europe/Rome"
   network_mode: host
   restart: always

```

**Reply by rafvhoof** [reply]
Trying to setup Z2M docker with a ZigStar LAN gateway. Using the following docker compose file
```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080 # Frontend port
    environment:
      - "TZ=Europe/Berlin"
    network_mode: host
    devices:
      - /dev/null:/dev/ttyACM0 # Make sure this matched your adapter location
```

I get the following error
```
Zigbee2MQTT:info  2023-02-13 13:54:58: Starting Zigbee2MQTT version 1.30.1 (commit #eb878d3)
Zigbee2MQTT:info  2023-02-13 13:54:58: Starting zigbee-herdsman (0.14.89)
Zigbee2MQTT:error 2023-02-13 13:54:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-02-13 13:54:59: Failed to start zigbee
Zigbee2MQTT:error 2023-02-13 13:54:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-02-13 13:54:59: Exiting...
Zigbee2MQTT:error 2023-02-13 13:54:59: Error: Error while opening serialport 'Error: Error: Not a tty setting custom baud rate of 115200'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18
```

Can anyone help me with the configuration?

**Reply by JackTalisker** [reply]
what's yor z2m configuration.yaml ?

**Reply by rafvhoof** [reply]
configuration.yaml
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.24
serial:
  port: 'tcp://192.168.1.108:6638'
```

No problems with connection when trying directly on my Windows system.

**Comment by TurboCoder13** [comment]
@rafvhoof Same here. Did you manage to sort it out?

This config is right for Z2M `configuration.yaml`:

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.24
serial:
  port: 'tcp://192.168.1.108:6638'
```

But for the `docker-compose.yaml` file, I have no clue what to use for `devices`:

```
zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /opt/zigbee2mqtt/data:/app/data
      - /opt/zigbee2mqtt/udev:/run/udev:ro
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Berlin
    devices:
      - # what to put here?
```

**Comment by junosuarez** [comment]
@eitel13 No need to put anything in `devices` in `docker-compose.yaml` - since you're connecting over the network instead of a local USB device, the docker `devices` config doesn't apply. You do need to make sure the container can communicate to the IP address, however. You can check this by running a command from inside the zigbee2mqtt container:

1. make sure your container is running (eq `docker container list --filter name=zigbee2mqtt`
2. start a shell inside the container: `docker exec -it zigbee2mqtt sh`. it should show a minimal prompt: `/app # `
3. try to connect to your network coordinator, using the IP and port, using netcat: `nc 192.168.1.108 6638; echo $?`
  - make sure you use a space between the IP address and the port number
  - the `; echo $?` at the end will print the exit code, so we can see if there is an error
  - if it connects successfully, you might see no message or a blank screen. this is good, it means you were able to open a connection to the coordinator. 
  - if it exits immediately or after a few seconds, the connection was closed (or never established in the first place), and you should see a `1` for the exit code. 
4. `ctrl`+`c` will close the running process. run `exit` to get out of the container and back to your system command prompt.

The `network_mode: host` means the docker container should be able to reach all the same routes as your host machine. Docker networking can be tricky, though - feel free to share the results and if you got it working or need to debug further.

**Reply by TurboCoder13** [reply]
Thank you @junosuarez for the detailed reply! 🙂 

I had managed to resolve this after posting here, but nevertheless, it's good to know and reference for the future.

Thank you again 🦾

**Reply by d3zit** [reply]
How can you test if the container sees the device if the error itself is preventing the container from starting?

**Reply by TurboCoder13** [reply]
Hey @d3zit ! 🙂 

Sorry, I don't have enough in depth knowledge to be able to help, but please see my response below to see if there's something that be of help to you. 🙇

**Comment by Sandermand** [comment]
> Thank you @junosuarez for the detailed reply! 🙂
> 
> I had managed to resolve this after posting here, but nevertheless, it's good to know and reference for the future.
> 
> Thank you again 🦾

What did you do to fix it ? I have the same issue :)

**Reply by WaarlandIT** [reply]
always nice that someone solves the problem but doesn't share the details :(

**Reply by TurboCoder13** [reply]
My apologies! 🙈 

I completely intended to reply to you @Sandermand but I forgot 😅 

To be completely honest, I had help from the developer / creator of the PoE device I was using and it's been so long, I don't recall what the exact fix was, but IIRC, it was a firmware update I was struggling with.

What I _can_ share is what my config looks like, so I hope that will help 🙇 

This is my `docker-compose.yml`

```yaml
---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    privileged: true
    depends_on:
      mosquitto:
        condition: service_healthy
    labels: 
      autoheal: "true"
    healthcheck:
      test: curl -fSs http://127.0.0.1:${PORT_HA} || exit 1
      start_period: 90s
      timeout: 10s
      interval: 5s
      retries: 3

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /opt/mosquitto:/mosquitto
    ports:
      - "${PORT_MQTT_ONE}:${PORT_MQTT_ONE}"
      - "${PORT_MQTT_TWO}:${PORT_MQTT_TWO}"
    command:
      - mosquitto
      - -c
      - /mosquitto-no-auth.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      start_period: 90s
      timeout: 10s
      interval: 5s
      retries: 3

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /opt/zigbee2mqtt/data:/app/data
      - /opt/zigbee2mqtt/udev:/run/udev:ro
    network_mode: host
    environment:
      - TZ=${TZ}
      - ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=false
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://${HA_IP}:${PORT_MQTT_ONE}
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${USER_MQTT}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${PWD_MQTT}
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=tcp://${ZIGBEE_POE_DONGLE}:${PORT_ZIGBEE_DONGLE} # POE Coordinator
    privileged: true
    depends_on:
      mosquitto:
        condition: service_healthy
    labels:
      autoheal: "true"
```

This is in `zigbee2mqtt > data > configuration.yaml`:

```yaml
---
homeassistant: true
advanced:
  rtscts: false
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  last_seen: ISO_8601_local
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  log_level: debug
device_options:
  legacy: false
devices:
  - devices.yaml
groups:
  - groups.yaml
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://<your-ip-here>:<your-port-here>
  user: <your-user-here>
  password: <your-password-here>
frontend:
  port: <z2m-frontend-port>
  host: <host-ip-address>
```

All the variables `${}` (like `${ZIGBEE_POE_DONGLE}` for example) are stored in a `.env` file which is in the same dir as the `docker-compose.yml`.

@WaarlandIT I hope this can help you too!

**Comment by CannyGent** [comment]
Hello - has anybody else managed to get this working. I am trying to migrate to my SMLight SLZB-06P7 and having accepted that I need to repair all my zigbee devices, decided to try and bring up a new instance of zigbee2mqtt in docker separate from Home Assistant so that I can gradually migrate to the new coordinator. I am stumped because if I don't map a device to /dev/ttyACM0 then zigbee2mqtt complains

```
error:      z2m: Error: Error: No such file or directory, cannot open /dev/ttyACM0
```

And if I map /dev/null then I get
```
error:     z2m: Error: Error: Not a tty setting custom baud rate of 115200
```

Any ideas?

For reference, my ```docker-compose.yml```:
```
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    privileged: true
    network_mode: host
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/null:/dev/ttyACM0
```
and my ```configuration.yaml``` serial section
```
serial:
  #adapter: zstack
  port: tcp://10.0.0.108:6638
  #baudrate: 115200
```
