### DISCUSSION TITLE
npm start fails and I cannot figure the issue from logs

### DISCUSSION THREAD

**Discussion by foice** [Koenkk/zigbee2mqtt#11005] [General]
```
$ npm start

> zigbee2mqtt@1.22.1 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2022-01-25 13:23:39: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-01-25.13-23-36' filename: log.txt
Zigbee2MQTT:info  2022-01-25 13:23:39: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229f)
Zigbee2MQTT:info  2022-01-25 13:23:39: Starting zigbee-herdsman (0.13.176)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-01-25 13:23:50: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-25 13:23:50: Failed to start zigbee
Zigbee2MQTT:error 2022-01-25 13:23:50: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-25 13:23:50: Exiting...
Zigbee2MQTT:error 2022-01-25 13:23:50: undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.22.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-25T12_23_50_710Z-debug.log
```

The log is rather unhelpful to me, it follows if you want to have a look, any clue?

```
9 verbose lifecycle zigbee2mqtt@1.22.1~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.22.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.22.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.22.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.22.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zigbee2mqtt@1.22.1
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.10.63-v7+
17 verbose argv "/opt/zigbee2mqtt/bin/node" "/opt/zigbee2mqtt/bin/npm" "start"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.22.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.22.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I have tried to even hijack the config file to see if it complained about it, but it always gives the same  error. Here is the config anyways.

```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  #server: 'mqtt://localhost'
  server: 'mqtt://192.168.1.146:1883'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
```

As a chekc I tested I can write to the serial
`test -w /dev/ttyACM0 && echo success || echo failure`
