### DISCUSSION TITLE
Cant start Zigbee2mqtt as service

### DISCUSSION THREAD

**Discussion by stain3565** [Koenkk/zigbee2mqtt#11318] [General]
I realise this has been asked many times and have read many posts.  However, not found anything for my failure.

Homebridge on Raspberry PI4 and have installed Zigbee2MQTT, following the standard instructions.

The service fails to start and creates the following failure message:

` Process: 2563 ExecStart=npm start (code=exited, status=200/CHDIR)`

I have tried many variations of the npm location.

`npm root -g` returns /usr/local/lib/node_modules/npm so I have attempted that, as well as usr/local/bin/npm and usr/bin/npm. No success. I wondered if it was permissions for my userid pi so have attempted to give permissions to the usb, using [Give your user permissions on every reboot](https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#method-1-give-your-user-permissions-on-every-reboot) although that seems to be a separate permission. I think my problem is to do with execstart folders and not the usb.

The service is defined below:

```
[Unit]
Description=zigbee2mqtt
After=network.target

[Service]
#Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/opt/zigbee2mqtt/node_8.11.2/bin
#ExecStart=/opt/zigbee2mqtt/node_8.11.2/bin/node index.js
ExecStart=npm start
WorkingDirectory=/opt/zigbee2mqtt/zigbee2mqtt
StandardOutput=null
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target

```

Configuration yaml:

```
homeassistant: false

permit_join: true

mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.yyy:1883'
  user: zzzzz
  password: ppppp

serial:
  #port: /dev/ttyUSB0
  port: /dev/ttyUSB.CC2531-01
frontend:
  port: 8080
  host: 192.168.1.xxx
advanced:
  network_key: GENERATE
```
