### DISCUSSION TITLE
Automations support

### DISCUSSION THREAD

**Discussion by Anonym-tsk** [Koenkk/zigbee2mqtt#11790] [General]
I use Z2M with Home Assistant.
Most of my devices are zigbee and I have quite a few automations in HA.
At the moment automations depend on two services - HA and Z2M. If I update or restart HA, automations don't work.
It would be great to be able to create simple automations directly in Z2M.

I've made Z2M extension to create automations directly in Z2M.
Automations syntax in the `configuration.yaml` is quite similar to the HA syntax.
Please check it out and give feedback

https://github.com/Anonym-tsk/zigbee2mqtt-extensions

It would be great to merge external extension to Z2M core and create UI for making automations.

#### Configuration example

```yaml
automations:

  # Toggle plug and light by button click
  automation_one:
    trigger:
      # On button click
      platform: action
      entity:
      - Switch
      - Button
      action:
      - single
      - double
      - hold
    condition:
      # If temperature above 25 and below 35
      platform: numeric_state
      entity: My Sensor
      attribute: temperature
      above: 25
      below: 35
    action:
    # Turn on light
    - entity: Light
      service: turn_on
    # And turn off plug
    - entity: Plug
      service: turn_off

  # Turn on night light by motion
  automation_two:
    trigger:
      # On motion
      platform: state
      entity: Motion Sensor
      attribute: occupancy
      state: true
    condition:
      # If light is off
      platform: state
      entity: Light
      state: 'OFF'
    action:
      # Turn on night light
      entity: Night Light
      service: turn_on

  # Turn off night light if no motion for 5 minutes
  automation_three:
    trigger:
      # If no motion for 5 minutes
      platform: state
      entity: Motion Sensor
      attribute: occupancy
      state: false
      for: 300
    condition:
      # If light is off
      platform: state
      entity: Light
      state: 'OFF'
    action:
      # Turn off night light
      entity: Night Light
      service: turn_off
```

**Comment by Cytrian** [comment]
I would love to see this in Zigbee2Mqtt. Then at least some basic things can be done autonomous, e.g. switching lights, even when the Homeassistant or the MQTT server is down.

**Comment by steff75** [comment]
I would also like it if something like this extension was already included in zigbee2mqtt. In Phoscon/deConz there is also a possibility to create simple rules via the GUI.

For some reason unknown to me I can't get this extension to work anymore. When saving it, I get an error:
![Screenshot 2023-03-05 103740](https://user-images.githubusercontent.com/19283026/222953766-a264e6fa-bad2-43b7-8ef6-f4c25b75a8b8.jpg)
`error 2023-03-03 13:51:55: Request 'zigbee2mqtt/bridge/request/extension/save' failed with error: 'Cannot read properties of undefined (reading 'platform')'
info  2023-03-03 13:51:55: MQTT publish: topic 'zigbee2mqtt/bridge/response/extension/save', payload '{"data":{},"error":"Cannot read properties of undefined (reading 'platform')","status":"error","transaction":"heeb9-3"}'`
Restarting doesn't help.

Zigbee2mqtt runs as HA-Addon on an Odroid-C2.
Does anyone know how I can fix this?

**Reply by Anonym-tsk** [reply]
Please describe what do you do.

**Comment by steff75** [comment]
In the web interface of Z2M I create a new extension under extensions with the '+' button. I name it 'automations-extension.js'.

As content I insert the raw text from your extension and press the 'Save' button.
![Screenshot 2023-03-05 113645](https://user-images.githubusercontent.com/19283026/222955492-ba0ddc69-d2ee-4ebd-a417-29f9c8b9c7ab.jpg)

Then the error occurs and it is not saved.

Thanks for your help!

**Reply by Anonym-tsk** [reply]
What z2m version do you use?

**Reply by steff75** [reply]
Latest HA addon.

Zigbee2MQTT Version1.30.2 commit: unknown
Coordinator-TypzStack3x0
Coordinator-Version20221226
Coordinator IEEE Adresse0x00124b0024c834e9
Frontend Version0.6.125

**Reply by Anonym-tsk** [reply]
Please provide your configuration.yaml file too

**Reply by Anonym-tsk** [reply]
Remove automations: section from config. Add and save automations extension. Then add automations back to config.

**Reply by steff75** [reply]
Ok, I stopped the Z2M addon so I can edit the 'configurations.yaml' and deleted 'automations: automations.yaml'.
Then saved the file and started Z2M.
Now I could add the extension without error message.
Now I stopped Z2M again so I could add the 'automations: automations.yaml' to the config file again.
When I then start the Z2M addon, I get into a reboot loop. Another error from me?
[automations_and_log.zip](https://github.com/Koenkk/zigbee2mqtt/files/10891694/automations_and_log.zip)

**Reply by Anonym-tsk** [reply]
Try to remove automations one by one to find the problem

**Reply by steff75** [reply]
Sorry. I can't get it to work.
Even if I remove all automations from 'automations.yaml', I still get into the reboot loop.

The funny thing is that I already had the extension running with the same automations. Then I saw that there is a new version with an outsourced 'automations.yaml' and wanted to switch to it. Then came the mentioned error. When I then wanted to go back to the last working version, I got this error there too.

Thanks for your help anyway!

**Reply by steff75** [reply]
Hey Nikolay,
I took my time again and then also found my really stupid mistake. :innocent:

I had one 'automations:' too much in the top hierarchy of the yaml code of the outsourced file.

![Screenshot 2023-03-05 182707](https://user-images.githubusercontent.com/19283026/222976344-7dd15620-7a59-4ba1-8a40-a576ed769d25.jpg)

Now it works without error.

![Screenshot 2023-03-05 182737](https://user-images.githubusercontent.com/19283026/222976359-05efc16b-f962-4210-8da7-ab6f30a5d85a.jpg)

Thanks :)

**Comment by DieterKoblenz** [comment]
Looks like a great feature to z2m, it's for example a way to link switches to lights when binding is unavailable for those devices. @Koenkk you converted the issue into this discussion. Is this something you'd see fit for z2m, or would you like to keep it separate?

**Reply by Koenkk** [reply]
The user extension in the OP is good enough ATM.

**Comment by LeoeLeoeL** [comment]
I wanted to open a thread about simple automations (pseudo binding between switches and bulbs) in Z2M but I found this discussion. :-)
Any intention to implement something "graphical" instead extensions?

**Reply by Anonym-tsk** [reply]
Z2M extensions don't support UI.
There are 2 ways for future:
1. Add this extension into z2m core and make some GUI for this
2. Make some external application to create/update automations

**Comment by LeoeLeoeL** [comment]
I'm trying to activate more actions by one trigger:

automation_by_state_9:
    trigger:
      platform: state
      entity: Virtual Bagno -1
      attribute: state_l1
      state: ON
    action:
      entity: Luce Bagno D-1
      service: turn_on
      entity: Luce Posto Auto
      service: turn_on

but it doesn'work.
I can see this error:
Request 'zigbee2mqtt/bridge/request/extension/save' failed with error: 'duplicated mapping key (88:7) 85 | action: 86 | entity: Luce Bagno D-1 87 | service: turn_on 88 | entity: Luce Posto Auto ------------^ 89 | service: turn_on 90 | '
Where do I fail?

**Reply by Burki24** [reply]
You have to respect the spaces inside, like this:

```
automation_Beschattung_Aussen_Markise_Einfahren:
  trigger:
    platform: action
    entity: Wohnbereich/Beschattung/Markise/Taster
    action: 1_single
  action:
    entity: Aussen/Beschattung/Markise
    service: custom
    data:
      state: 'CLOSE'
automation_Beschattung_Aussen_Markise_Ausfahren:
  trigger:
    platform: action
    entity: Wohnbereich/Beschattung/Markise/Taster
    action: 3_single
  action:
    entity: Aussen/Beschattung/Markise
    service: custom
    data:
      state: 'OPEN'
automation_Beschattung_Aussen_Markise_Stop:
  trigger:
    platform: action
    entity: Wohnbereich/Beschattung/Markise/Taster
    action: 2_single
  action:
    entity: Aussen/Beschattung/Markise
    service: custom
    data:
      state: 'STOP'
automation_Licht_Aussen_Hausnummer_an:
  trigger:
    platform: numeric_state
    entity: Aussen/Klima/Helligkeit/Weg_Nord_West
    attribute: illuminance
    above: 1
    below: 26000
    for: 10
  action:
    entity: Aussen/Beleuchtung/Eingang/Hausnummer
    service: custom
    data:
      state: 'ON'
automation_Licht_Aussen_Hausnummer_aus:
  trigger:
    platform: numeric_state
    entity: Aussen/Klima/Helligkeit/Weg_Nord_West
    attribute: illuminance
    above: 26000
    below: 999999
    for: 10
  action:
    entity: Aussen/Beleuchtung/Eingang/Hausnummer
    service: custom
    data:
      state: 'OFF'
automation_Licht_Badezimmer_Bewegung_an:
  trigger:
    platform: state
    entity: Bad/Sicherheit/Radar
    attribute: presence
    state: true
  action:
    entity: Bad/Beleuchtung/Deckenlicht/Licht1
    service: custom
    data:
      state: 'ON'
      brightness: 254
      transition: 1
```
