### DISCUSSION TITLE
Google IoT Core

### DISCUSSION THREAD

**Discussion by arinconc** [Koenkk/zigbee2mqtt#11948] [General]
Hello!
I am trying to connect zigbee2mqtt to Google Cloud IoT Core. I've tried many configurations but I can't get it to connect. Can anybody help me?
This is my configuration file
```
mqtt:
   base_topic: projects/<MyProject>/topics/gateway-state
   server: mqtt.googleapis.com:8883
   client_id: >-
     projects/<MyProject>/locations/europe-west1/registries/my-registry/devices/my-gateway
   ca: /config/roots.pem
   user: ''
   password: >-
     <MY_JWT>
```

Thank you very much for any information that can guide me!
Antonio
