### DISCUSSION TITLE
with a group for a lidl HG06338 sometimes state is lost

### DISCUSSION THREAD

**Discussion by Nardol** [Koenkk/zigbee2mqtt#12536] [Devices]
Hello,

I have installed Zigbee2MQTT on Raspbian Bullseye, without Docker and use Home Assistant Core and Mosquitto on the same Odroid N2+.

Using the dashboard, I created a group to be able to control all switch of a Lidl HG06338 in the same times if desired.

But I notice sometimes, if asking Google Assistant if the group is on, the answer is no even if it is not the case.
And in Home Assistant, instead of a classic switch I have one with buttons On and Off, as a non assumed-state switch.
If I click "On" button then the switch return to the desired state, I haven't the two button but a classic switch as expected.

To create the group, I put the three endpoints of the HG06338 in the group.

The generated YAML:

```yaml
  '2':
    friendly_name: Prises Chambre
    devices:
      - 0xbc33acfffe3632f2/1
      - 0xbc33acfffe3632f2/2
      - 0xbc33acfffe3632f2/3
```

What could cause this strange behavior, in fact why the state does not stay as it is?
I prefer creating a discussion before an issue.
