### DISCUSSION TITLE
Danfoss Ally questions

### DISCUSSION THREAD

**Discussion by deapstack** [Koenkk/zigbee2mqtt#12606] [Devices]
Hi,

I have a lot of experience with Zwave valves, mainly from Fibaro and Eurotronic. The one from Fibaro is catastrophic, and the one from Eurotronic is a little bit better but it suffer from big issues which can lead to catastrophic temperatures overruns and loss of calibration.

I have decided to go with Zigbee valves, and I bought one Danfoss Ally in order to test it.

I would like to have advices from users of this valve, before making an investment for all my radiators...

Is this valve fully compatible with z2m? Are there any firmware issue or valve issue that I should know? Is the thermal regulation operating correclty? What is the average battery life?

Thanks for your advices !

**Comment by zartmann** [comment]
I'm new to HA, but just got z2m up and running and tried to add one of my Danfoss Ally thermostats. Got it paired, but couldn't make sense of how to automate (or even just control) the device
https://www.zigbee2mqtt.io/devices/014G2461.html

If you got it up and running I'd be very happy to hear what you did. Basically I just wanted to get rid of the bridge Danfoss has and be able to use them with a schedule and control when I'm home/away. Like you can in their app.

Thanks.

/JZ

**Comment by rsporsche** [comment]
I've been using two POPP 701721 thermostats which are the same as the Danfoss Ally for the last few weeks with z2m and HA. Overall pretty happy with it but I think it's too early to say for sure.
Battery has dropped faster than expected but it may be because I have been changing settings quite frequently while trying to figure things out so again, I think too early to draw any conclusion.

Firmware is 1.18, it took about two hours to update each thermostat!

I am using external temperature sensors with this HA blueprint: https://community.home-assistant.io/t/danfoss-ally-1-18-set-external-temperature-to-radiator-covered-trv/380219 modified slightly with 'mode: single' instead of 'mode: restart' and replaced this:
```
- service: deconz.configure
  data:
    entity: !input danfoss_trv
    field: /config
    data: >-
      { "externalsensortemp": {{ (states(temperature_sensor)|float *100)|int }} }
```
with this:
```
- service: number.set_value
  target:
    entity_id: !input danfoss_trv
  data:
    value: '{{ (states(temperature_sensor)|float *100)|int }}'
```

I also added this to my z2m config for each thermostat so that it reports the external temperature instead of internal temperature since that's what I'm using to regulate, and to use the 'scheduled' mode for setpoint changes because I find the default too aggressive

example for my "Living room Thermostat":
```
homeassistant:
        climate:
            current_temperature_template: '{{ value_json.external_measured_room_sensor|float/100 }}'
            temperature_command_topic: 'zigbee2mqtt/Living room Thermostat/set/occupied_heating_setpoint_scheduled'
            temperature_state_template: '{{ value_json.occupied_heating_setpoint_scheduled }}'
```

I'm also using this automation for scheduled setpoint changes, it's triggered by a 'Times of the day' helper with on = night time.
```
alias: Reduce temperature at night
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.heating_off
condition: []
action:
  - if:
      - condition: state
        entity_id: binary_sensor.heating_off
        state: "on"
    then:
      - device_id: 9df09b80d5b80bd0ff5ced14aed1353c
        domain: number
        entity_id: number.living_room_thermostat_occupied_heating_setpoint_scheduled
        type: set_value
        value: 13
    else:
      - device_id: 9df09b80d5b80bd0ff5ced14aed1353c
        domain: number
        entity_id: number.living_room_thermostat_occupied_heating_setpoint_scheduled
        type: set_value
        value: 20
mode: single
```

It's pretty basic but it works. Could also use a schedule helper for more complex schedules.. I'd like to see a schedule helper in HA that could be associated with a number so you could encode the temperatures into the schedule but I don't think that's possible (yet?). You could set value to whatever you want night/day, there doesn't seem to be a way to switch them off entirely although maybe window_open_external could be misused for that? Anyway, setting setpoint to 5C should effectively turn them off.
