### DISCUSSION TITLE
Home Assistant legacy entity attributes

### DISCUSSION THREAD

**Discussion by michal-bartak** [Koenkk/zigbee2mqtt#12609] [General]
I have this setting disabled (not checked). Regardless of that entities created by Z2M contain attributes with values of other entities representing the device (see screenshot below). Is it expected? I understand the message for this feature that there should be no redundant attributes

![image](https://user-images.githubusercontent.com/7868445/170519682-bc888af6-f934-46de-a1b4-9cee14958ed4.png)

**Comment by Koenkk** [comment]
Can you provide me your `configuration.yaml`?

**Reply by michal-bartak** [reply]
See my z2m `configuration.yaml` below with a few sensitive values masked.

Just note, today I've added another device (Aqara door window sensor) and can confirm that entities created for this device don't contain unneeded attributes. However, the same type of device registered in the past has those attributes.
So it seems that legacy entity attributes remain regardless of the change in Z2M configuration (incl Z2M restarts). 

```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: ****
  password: ****
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
  - ****
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  legacy_api: false
  legacy_availability_payload: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true
zigbee_herdsman_debug: true
```
