### DISCUSSION TITLE
z2m on docker - empty device list after migrating

### DISCUSSION THREAD

**Discussion by Mamfred8000** [Koenkk/zigbee2mqtt#12620] [General]
Hello everyone,

I use docker to run mosquitto, zigbee2mqtt and home assistant. I had to reinstall ubuntu minimal and backed up my config folder to restore the existing zigbee network. After setting everythin up, unfortunately, the device list in the frontend of zigbee2mqtt is empty., allthough, all my devices are specified in the configuration.yml.

When I bring the devices to paring mode (hardware), the devices appear in the list with their predefined name. But just one at a time.
Also my defined groups are visible in the frontend.

Is there a way to restore all my devices from the configuration.yml file?

Thank you!

configuration.yml
```
homeassistant: true
permit_join: false
frontend:
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
  user: ***
  password: ***
serial:
  port: /dev/ttyACM0
devices:
  '***address1':
    friendly_name: Fenstersensor Wohnzimmer
  '***address2':
    friendly_name: Nachtleuchte Schaltdose Flur
advanced:
  log_level: info
  ikea_ota_use_test_url: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
```
