### DISCUSSION TITLE
BTicino K4411C dimmer issue.

### DISCUSSION THREAD

**Discussion by PaoloVittori** [Koenkk/zigbee2mqtt#12714] [Devices]
I am trying to migrate some devices from deconz to zigbee2mqtt. One of the problems I'm having concerns the BTICINO K4411C dimmer. 
With deconz I could use the deconz.configure service.

**I could start bright with:**
```
- service: deconz.configure
  data:
     entity: light.xxxxxxx
     field: "/state"
     data: {"bri_inc":254, "transitiontime":50}
```
**dim:**
```
- service: deconz.configure
  data:
     entity: light.xxxxxxx
     field: "/state"
     data: {"bri_inc":-230, "transitiontime":50}
```
**and stop dimming/brighting with:**
```
- service: deconz.configure
  data:
    entity: light.xxxxxxx
    field: "/state"
    data: {"bri_inc":0}
```

With zigbee2mqtt the only thing I can do is set a brightness value and define a transition time but I can't stop the dimming / brightness.
For example: {"brightness":156,"transition":3}

This could be done with the "brightness_move" or "brightness_step" payloads which however still seems unsupported for the K4411C device even if the documentation suggests otherwise (see:https://www.zigbee2mqtt.io/devices/L441C_N4411C_NT4411C.html#bticino-l441c-n4411c-nt4411c).
If I try to send the payload {"brightness_move": 40} to the topic "zigbee2mqtt/MyDevice/set" I get the error "No converter available for 'brightness_move '(40) ". 

I also tried "brightness_move_onoff" or "brightness_step_onoff" but none of them work.

What I'm missing?
