### DISCUSSION TITLE
adding external convertors prevents z2m to start

### DISCUSSION THREAD

**Discussion by rgrs83** [Koenkk/zigbee2mqtt#12994] [General]
Hi all,

I am trying to install an unknown (tuya) device using an external converter. I followed these guides:
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_1-pairing-the-device-with-zigbee2mqtt

and  this one 
https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#instructions

My main issue at the moment is, that when I add this:
```
external_converters:
  - mydevice.js
```
to the configuration.yaml, z2m fails to start.
Z2M version: 1.25.2 commit: 9b2a9210

Configuration.yaml:
```
homeassistant: true
permit_join: true
external_converters:
 - mydevice.js
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.188.3:1883
  user: XXX
  password: XXXX
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8181
  host: 192.168.188.3
devices:
  '0x000d6ffffedaee12':
    friendly_name: '0x000d6ffffedaee12'
    retain: false
  '0x000d6ffffed94e26':
    friendly_name: '0x000d6ffffed94e26'
    retain: false
  '0x14b457fffe747795':
    friendly_name: '0x14b457fffe747795'
    retain: false
  '0x000b3cfffef2be26':
    friendly_name: '0x000b3cfffef2be26'
    retain: false
  '0x14b457fffe77706e':
    friendly_name: '0x14b457fffe77706e'
    retain: false
  '0x14b457fffe746bf4':
    friendly_name: '0x14b457fffe746bf4'
    retain: false
  '0xbc33acfffe61a430':
    friendly_name: '0xbc33acfffe61a430'
  '0x00158d00054450da':
    friendly_name: '0x00158d00054450da'
  '0x7cb03eaa0a0c2072':
    friendly_name: '0x7cb03eaa0a0c2072'
  '0x7cb03eaa0a0adce3':
    friendly_name: '0x7cb03eaa0a0adce3'
  '0x7cb03eaa0a0c1b45':
    friendly_name: '0x7cb03eaa0a0c1b45'
  '0x7cb03eaa0a0c53e3':
    friendly_name: '0x7cb03eaa0a0c53e3'
  '0x842e14fffedfa0d2':
    friendly_name: '0x842e14fffedfa0d2'
  '0xb4e3f9fffe0e4dc1':
    friendly_name: '0xb4e3f9fffe0e4dc1'
  '0xb4e3f9fffe0e4de0':
    friendly_name: '0xb4e3f9fffe0e4de0'
  '0x00158d0006264d76':
    friendly_name: '0x00158d0006264d76'
  '0x00158d00052b8916':
    friendly_name: '0x00158d00052b8916'
  '0x00158d00052b88d4':
    friendly_name: '0x00158d00052b88d4'
  '0xa4c1384009464bda':
    friendly_name: '0xa4c1384009464bda'
  '0xa4c1383076cd079e':
    friendly_name: '0xa4c1383076cd079e'
advanced:
  log_level: info
  ikea_ota_use_test_url: true
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
```

Logging:

opt/zigbee2mqtt/data $ sudo journalctl -u zigbee2mqtt.service -f
-- Journal begins at Tue 2022-04-19 09:20:01 CEST. --
Jun 30 10:55:06 autohome systemd[1]: Stopping zigbee2mqtt...
Jun 30 10:55:06 autohome npm[20462]: Zigbee2MQTT:info  2022-06-30 10:55:06: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
Jun 30 10:55:06 autohome npm[20462]: Zigbee2MQTT:info  2022-06-30 10:55:06: Disconnecting from MQTT server
Jun 30 10:55:06 autohome npm[20462]: Zigbee2MQTT:info  2022-06-30 10:55:06: Stopping zigbee-herdsman...
Jun 30 10:55:16 autohome npm[20462]: Zigbee2MQTT:info  2022-06-30 10:55:16: Stopped zigbee-herdsman
Jun 30 10:55:16 autohome npm[20462]: Zigbee2MQTT:info  2022-06-30 10:55:16: Stopped Zigbee2MQTT
Jun 30 10:55:17 autohome systemd[1]: zigbee2mqtt.service: Succeeded.
Jun 30 10:55:17 autohome systemd[1]: Stopped zigbee2mqtt.
Jun 30 10:55:17 autohome systemd[1]: zigbee2mqtt.service: Consumed 2min 18.166s CPU time.
Jun 30 10:55:17 autohome systemd[1]: Started zigbee2mqtt.
Jun 30 10:55:20 autohome npm[593]: > zigbee2mqtt@1.25.2 start /opt/zigbee2mqtt
Jun 30 10:55:20 autohome npm[593]: > node index.js
Jun 30 10:55:29 autohome npm[607]: (node:607) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected identifier
Jun 30 10:55:29 autohome npm[607]: (Use `node --trace-warnings ...` to show where the warning was created)
Jun 30 10:55:29 autohome npm[607]: (node:607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jun 30 10:55:29 autohome npm[607]: (node:607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun 30 10:55:29 autohome systemd[1]: zigbee2mqtt.service: Succeeded.
Jun 30 10:55:29 autohome systemd[1]: zigbee2mqtt.service: Consumed 10.778s CPU time.
Jun 30 10:55:30 autohome systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 1.
Jun 30 10:55:30 autohome systemd[1]: Stopped zigbee2mqtt.
Jun 30 10:55:30 autohome systemd[1]: zigbee2mqtt.service: Consumed 10.778s CPU time.
Jun 30 10:55:30 autohome systemd[1]: Started zigbee2mqtt.
Jun 30 10:55:32 autohome npm[622]: > zigbee2mqtt@1.25.2 start /opt/zigbee2mqtt
Jun 30 10:55:32 autohome npm[622]: > node index.js
Jun 30 10:55:39 autohome npm[634]: (node:634) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected identifier
Jun 30 10:55:39 autohome npm[634]: (Use `node --trace-warnings ...` to show where the warning was created)
Jun 30 10:55:39 autohome npm[634]: (node:634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jun 30 10:55:39 autohome npm[634]: (node:634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun 30 10:55:39 autohome systemd[1]: zigbee2mqtt.service: Succeeded.
Jun 30 10:55:39 autohome systemd[1]: zigbee2mqtt.service: Consumed 10.329s CPU time.
Jun 30 10:55:40 autohome systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 2.
Jun 30 10:55:40 autohome systemd[1]: Stopped zigbee2mqtt.
Jun 30 10:55:40 autohome systemd[1]: zigbee2mqtt.service: Consumed 10.329s CPU time.
Jun 30 10:55:40 autohome systemd[1]: Started zigbee2mqtt.
