### DISCUSSION TITLE
502: Bad Gateway *SOLVED*

### DISCUSSION THREAD

**Discussion by Roel-D** [Koenkk/zigbee2mqtt#13428] [Devices]
Hello all

I having a problem with the integration of my Sonoff dongle
Zigbee2MQTT keeps indicating 502: Bad Gateway

**Hardware:**
Unraid server 6.9.2
Sonoff Zigbee 3.0 Dongle Plus (ZBDongle-P)
Conbee II

**Software**
Home Assistant 2022.8.1 (as VM in Unraid)
Supervisor 2022.07.0 
Operating System 8.4 
Mosquitto broker 6.1.2
Zigbee2MQTT 1.27.0-1

**Mosquitto broker LOG**
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[11:36:51] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[11:36:51] INFO: Starting NGINX for authentication handling...
[services.d] done.
[11:36:52] INFO: Starting mosquitto MQTT broker...
1659778612: Warning: Mosquitto should not be run as root/administrator.
[11:36:53] INFO: Successfully send discovery information to Home Assistant.
[11:36:53] INFO: Successfully send service information to the Supervisor.

**Zigbee2MQTT SETTINGS**
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: mqtt-user
  password: ***
serial:
  port: /dev/ttyUSB0
zigbee_herdsman_debug: false

**Zigbee2MQTT LOG**
> [12:12:03] INFO: Handing over control to Zigbee2MQTT Core ...
zigbee2mqtt@1.27.0 start
node index.js
Zigbee2MQTT:info  2022-08-06 12:12:04: Logging to console and directory: '/config/zigbee2mqtt/log/2022-08-06.12-12-04' filename: log.txt
Zigbee2MQTT:info  2022-08-06 12:12:04: Starting Zigbee2MQTT version 1.27.0 (commit #unknown)
Zigbee2MQTT:info  2022-08-06 12:12:04: Starting zigbee-herdsman (0.14.46)
Zigbee2MQTT:error 2022-08-06 12:12:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-08-06 12:12:04: Failed to start zigbee
Zigbee2MQTT:error 2022-08-06 12:12:04: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-08-06 12:12:04: Exiting...
Zigbee2MQTT:error 2022-08-06 12:12:04: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyUSB0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12

**Things I've already tried:**
- Sonoff dongle re-flashed with Z-Stack firmware
(https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20220219.zip)
Using this tutorial (https://www.youtube.com/watch?v=4jqQCxjlRDU)

- Trying to apply integration to my existing Home Assistant environment

- Trying to apply integration to a complete new installation of Home Assistant

- Put the Sonoff dongle into various USB ports (Dongle is always visible under the hardware tab in Home Assistant)

- Used with an USB extension cable

- Used without an USB extension cable

It looks like there is an issue with the Sonoff dongle.
When I replace the Sonoff dongle for my ConBee II (and adjust the port settings) Zigbee2MQTT starts up immediately without any error.

Probably I'm going to overlook something simple, but don't get anywhere with it after 2 days....

**Comment by Roel-D** [comment]
It works!

What I do, step-by-step

- Disconnect all zigbee routers from the main power
- Stop the Zigbee2MQTT plugin in Home Assistant
- Manually add a new **pan_id** and **network_key** to the configuration.yaml of Zigbee2MQTT
- Delete **coordinator_backup.json**
- Delete **database.db.backup**
- Starting the Zigbee2MQTT plugin
- Reboot the system after a few minutes
- Reconnect the Zigbee routers to the mains
- All devices now need to be manually paired again. I knew this because the pan_id has changed

Do some work tonight, but i'm happy :slight_smile:

**Comment by frequent-nomad** [comment]
Great that you got this to work, I also had the same problem with the Sonoff dongle. In the documentation it says that if you want to use the web UI  you need to edit the `configuration.yaml` file, and add in: 

`frontend: true`

Did you attempt this? Just curious to see if I need to think about the other steps you've mentioned above.

**Comment by Roel-D** [comment]
I did not add `frontend: true` to the `configuration.yaml`

Copy of my Zigbee2MQTT `configuration.yaml`

```
homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: ***
  password: ***
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ac231e4f5345ec118e5b98fd6f14af06-if00-port0
frontend:
  port: 8099
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: ***
  pan_id: ***
  ext_pan_id:
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
  network_key:
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  timestamp_format: DD-MM-YYYY HH:mm:ss
  transmit_power: 20
device_options:
  legacy: false
devices:
  'X':
    friendly_name: X
  'XX':
    friendly_name: XX
  'XXX':
    friendly_name: XXX
  'XXXX':
    friendly_name: XXXX
```

What I do notice, is that the Sonoff dongle spreads a much weaker signal compared to the Conbee II. 
(even when I set the Sonoff 20dbm)

The reason I switched anyway is because I have lost connection to different devices in Home Assistant for already 3 times.

I have around 45 devices, 18 of these act as a zigbee routers. The rest are end devices.
