### DISCUSSION TITLE
zigbee2mqtt + mosquitto MQTT failed to connect: connect ECONNREFUSED 127.0.0.1:1883

### DISCUSSION THREAD

**Discussion by Baptiste-Jolaine** [Koenkk/zigbee2mqtt#13584] [General]
Hi,
I try to configure zigbee2mqtt to work with a mosquitto brocker. Final goal is to control the whole with home assistant but the issue is not related to home assistant. I use xubuntu 22.04 computer as a nas and everything is installed on it.
zigbee2mqtt is installed with docker.
mosquitto is installed with apt, classic install.
(home assistant is installed with docker, we don't care but it means I can't use addons)
(I use a Z-Dongle-P)
I'm working to configure zigbee2mqtt since 2 days without better results.
I think mosquitto is working well because mqtt integration for home assistant can connect to it without visible problem. I disabled the integration as I don't want it to interfere.

Here is my problem :
```
nas@nas-Think:~/.zigbee2mqtt$ cat data/log/2022-08-17.17-34-06/log.txt 
info  2022-08-17 17:34:06: Logging to console and directory: '/app/data/log/2022-08-17.17-34-06' filename: log.txt
info  2022-08-17 17:34:06: Starting Zigbee2MQTT version 1.27.0 (commit #a9b8808)
info  2022-08-17 17:34:06: Starting zigbee-herdsman (0.14.46)
info  2022-08-17 17:34:06: zigbee-herdsman started (resumed)
info  2022-08-17 17:34:06: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
info  2022-08-17 17:34:06: Currently 0 devices are joined:
warn  2022-08-17 17:34:06: `permit_join` set to  `true` in configuration.yaml.
warn  2022-08-17 17:34:06: Allowing new devices to join.
warn  2022-08-17 17:34:06: Set `permit_join` to `false` once you joined all devices.
info  2022-08-17 17:34:06: Zigbee: allowing new devices to join.
info  2022-08-17 17:34:07: Connecting to MQTT server at mqtt://localhost:1883
error 2022-08-17 17:34:07: MQTT failed to connect: connect ECONNREFUSED 127.0.0.1:1883
error 2022-08-17 17:34:07: Exiting...
info  2022-08-17 17:34:07: Stopping zigbee-herdsman...
info  2022-08-17 17:34:16: Stopped zigbee-herdsman
```

Here is my zigbee2mqtt configuration file. (Note: I disabled the login with the credentials to try to get less problems.)
```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost:1883'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyUSB0

device_options:
  log_file: log.txt
```
Here are my mosquitto configuration files (default and local)
```
nas@nas-Think:~$ cat /etc/mosquitto/mosquitto.conf
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /run/mosquitto/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```

```
nas@nas-Think:~$ cat /etc/mosquitto/conf.d/local.conf 
allow_anonymous true
listener 1883
```

Multiple reboots and restart of docker / service didn't make that work. I made this clean install with few changes without better results. Here follow mosquitto logs, it detect connection of home assistant but never detect zigbee2mqtt (once I disabled home assistant it never showed anything new).
```
nas@nas-Think:~$ sudo cat /var/log/mosquitto/mosquitto.log 
[sudo] Mot de passe de nas : 
1660740402: mosquitto version 2.0.11 starting
1660740402: Config loaded from /etc/mosquitto/mosquitto.conf.
1660740402: Starting in local only mode. Connections will only be possible from clients running on this machine.
1660740402: Create a configuration file which defines a listener to allow remote access.
1660740402: For more details see https://mosquitto.org/documentation/authentication-methods/
1660740402: Opening ipv4 listen socket on port 1883.
1660740402: Opening ipv6 listen socket on port 1883.
1660740402: mosquitto version 2.0.11 running
1660740453: New connection from 127.0.0.1:54687 on port 1883.
1660740453: New client connected from 127.0.0.1:54687 as 3XuqJmCbZQLcMBuuoBopvQ (p2, c1, k60, u'nas').
1660741353: mosquitto version 2.0.11 terminating
1660741353: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660741353: mosquitto version 2.0.11 starting
1660741353: Config loaded from /etc/mosquitto/mosquitto.conf.
1660741353: Starting in local only mode. Connections will only be possible from clients running on this machine.
1660741353: Create a configuration file which defines a listener to allow remote access.
1660741353: For more details see https://mosquitto.org/documentation/authentication-methods/
1660741353: Opening ipv4 listen socket on port 1883.
1660741353: Opening ipv6 listen socket on port 1883.
1660741353: mosquitto version 2.0.11 running
1660741354: New connection from 127.0.0.1:38301 on port 1883.
1660741354: New client connected from 127.0.0.1:38301 as 3XuqJmCbZQLcMBuuoBopvQ (p2, c1, k60, u'nas').
1660741944: mosquitto version 2.0.11 terminating
1660741944: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660741944: mosquitto version 2.0.11 starting
1660741944: Config loaded from /etc/mosquitto/mosquitto.conf.
1660741944: Opening ipv4 listen socket on port 1883.
1660741944: Opening ipv6 listen socket on port 1883.
1660741944: mosquitto version 2.0.11 running
1660741945: New connection from 127.0.0.1:39413 on port 1883.
1660741945: New client connected from 127.0.0.1:39413 as 3XuqJmCbZQLcMBuuoBopvQ (p2, c1, k60, u'nas').
1660742011: mosquitto version 2.0.11 terminating
1660742011: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660747375: mosquitto version 2.0.11 starting
1660747375: Config loaded from /etc/mosquitto/mosquitto.conf.
1660747375: Opening ipv4 listen socket on port 1883.
1660747375: Opening ipv6 listen socket on port 1883.
1660747375: mosquitto version 2.0.11 running
1660749176: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660750071: mosquitto version 2.0.11 terminating
1660750071: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660750102: mosquitto version 2.0.11 starting
1660750102: Config loaded from /etc/mosquitto/mosquitto.conf.
1660750102: Opening ipv4 listen socket on port 1883.
1660750102: Opening ipv6 listen socket on port 1883.
1660750102: mosquitto version 2.0.11 running
1660751903: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1660753704: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
```

I made a lot of google research and can't find anything... Any help would be much appreciated, even link to actual configurations that work for you.

Thank you for your help.

**Comment by hughb8on** [comment]
This has similarities to a problem I had recently because of a mosquitto upgrade as part of an upgrade to ubuntu 22.04.

It may or not be the cause of your problem, but mosquitto now, by default, rejects connections from anywhere other than localhost. It used to accept them, so simply upgrading mosquitto can break things which previously worked.

In your case the broker may actuslly be running on the same machine as zigbee2mqtt, but I see you are using docker, and that complicates things and may be causing mosquitto to think it isn't.

Getting mosquitto to once again accept connections coming from outside localhost just requires an edit to its config file.

Something to think about perhaps.

**Reply by Baptiste-Jolaine** [reply]
Thanks, it's something like that. It only works if I set the local ip address of the nas (192.168.1.x) as the address listened by mosquitto and the brocker address in zigbee2mqtt. The hell is that mosquitto doesn't seem to listen to all addresses when I configure it with 0.0.0.0. Can you explain me more in detail how it works ? I can't believe it's impossible to listen to all addresses or even just several.

**Reply by Baptiste-Jolaine** [reply]
It seems that mosquitto listen on all adresses by default but zigbee2mqtt in a docker can't use it. If I use 192.168.1.x it work, if I use localhost / 127.0.0.1 it never work. It's strange that no one describe how to work around the problem. I saw someone saying that the zigbee2mqtt docker should be in host mode instead of bridge, but I never used docker before so I don't understand.

**Reply by abstractionmage** [reply]
> Getting mosquitto to once again accept connections coming from outside localhost just requires an edit to its config file.

Would you mind sharing what edit this might be? I have the same problem and am currently looking for an easy fix.

**Comment by hughb8on** [comment]
I may not be able to help you much with docker because I now avoid containerisation. 

I see the MQTT Server URL definition in your configuration.yaml points to localhost:1883

However the TIP in the zigbee2mqtt docker documentation [here](https://www.zigbee2mqtt.io/guide/installation/02_docker.html#running-the-container) suggests the following : -

 "If you run the MQTT-Server on the same host (localhost) you could use the IP of the docker0 bridge to establish the connection: server: mqtt://172.17.0.1"

Have you tried that?

**Reply by Baptiste-Jolaine** [reply]
Thanks, it seems to work.
I understand why you avoid containerisation XD

**Reply by Pavel-Demidyuk** [reply]
Works fine for me as well, thanks @hughb8on

**Comment by trackhacs** [comment]
just had the same - with a non docker install. 

I had to change the address from *localhost* to the actual address of the host *192.168.2.99* to get it working. This version/install also had lot of trouble with ZDB V3 (Dongle-E).

z2m ->  1.28.4-1
mos ->  2.0.15-2

it works normal on an other computer (arm7) wiht:

z2m -> 1.28.2-2
mos -> 2.0.15-2

**Comment by alexmi256** [comment]
I just ran into this using Docker Compose via Portainer's stack feature and it seems the best way to handle that is to set the zigbee2mqtt config to the [hostname that will be given in docker](https://docs.docker.com/compose/networking/). 

It didn't help that there are two config guides/docs, [one without mosquitto mqtt](https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose) in the Docker guide and [one with it](https://www.zigbee2mqtt.io/guide/getting-started/#installation) in the Gettings Started guide.

My `docker-compose.yml ` file ended up being:
```
version: '3.8'
services:
  mosquitto:
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /flashcache/zigbee2mqtt/mosquitto-data:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on: 
    - mosquitto
    volumes:
      - /flashcache/zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8081:8080
    environment:
      - TZ=America/New_York
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyACM0:/dev/ttyACM0
```
And the `configuration.yaml` something like:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
  adapter: ezsp
advanced:
  network_key: GENERATE
frontend: true
```
