### DISCUSSION TITLE
Two gang TuYa TS0002_switch_module as light in home assistant

### DISCUSSION THREAD

**Discussion by ascheucher** [Koenkk/zigbee2mqtt#13855] [Devices]
I have successfully set up 1 gang TuYa TS0001_switch_module as lights like this:
```
"0xa4c138b5d21d492d":
  friendly_name: switch_module.uf_hallway_light
  homeassistant:
    switch:
      type: light
      object_id: light
    light:
      name: UF Hallway Light Switch
      value_template: null
      state_value_template: "{{ value_json.state }}"
```

I try to [set up my TuYa TS0002_switch_module](https://www.zigbee2mqtt.io/devices/TS0002_switch_module.html) as [light in Zigbee2MQTT](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light), but obviously I get a detail wrong.

This was my take in the zigbee2mqtt/devices.yaml config file:
```

"0xa4c13877abfb27f2":
  friendly_name: switch_module.uf_living-room_lights
  # two gang light switch
  homeassistant:
    switch_left:
      type: light
      object_id: light_left
    light_left:
      name: UF Living Room Light Switch - Left
      value_template: null
      state_value_template: '{{ value_json.state_l1 }}'
    switch_right:
      type: light
      object_id: light_right
    light_right:
      name: UF Living Room Light Switch - Right
      value_template: null
      state_value_template: '{{ value_json.state_l2 }}'
```

I also tried:
```
"0xa4c13877abfb27f2":
  friendly_name: switch_module.uf_living-room_lights
  homeassistant:
    switch_left:
      type: light
      object_id: l1
    l1:
      name: switch_module.uf_living-room_lights_l1
      value_template: null
      state_value_template: "{{ value_json.state_l1 }}"
    switch_right:
      type: light
      object_id: l2
    l2:
      name: switch_module.uf_living-room_lights_l2
      value_template: null
      state_value_template: "{{ value_json.state_l2 }}"
```

But they do not show up in the Overview Dashboard in the light sections.

In comparison the one gang switch_module works like a charm:
```
"0xa4c138b5d21d492d":
  friendly_name: switch_module.uf_hallway_light
  homeassistant:
    switch:
      type: light
      object_id: light
    light:
      name: UF Hallway Light Switch
      value_template: null
      state_value_template: "{{ value_json.state }}"
```
To figure out how to configure it, I even checked out the [Home Assistent ZigBee2MQTT Project](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt). Dug through it, till I realized I have to take a look in the zigbee-herdsman-converters project.

Then finally [the code (search for "TS0002_switch_module ")](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js) would suggest I can't be that far off...

I am thankful for every pointer where I am wrong here.
Thanks! :slight_smile:

**Comment by Daniel76145** [comment]
With TS001 I used documentation:
https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light

I don't know how to expose TS002 as light. @ascheucher Did you find solution? Can you share it please?
<img width="252" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/132905585/775170e1-fc74-4f23-b828-5e31b8f64232">

**Reply by ascheucher** [reply]
Oh, sorry. Missed the question in the flood of updates. It’s a while I did this, but I am sure it was done through the HA GUI somehow.

**Comment by francisp2** [comment]
This I have for a TS0004

```
  '0xa4c138c1c78671cf':
    friendly_name: boven
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        name: null
        value_template: null
        state_value_template: '{{ value_json.state }}'
      switch_l1:
        type: light
        object_id: light_l1
      light_l1:
        name: slaapkamervooraan
        value_template: null
        state_value_template: '{{ value_json.state_l1 }}'
      switch_l2:
        type: light
        object_id: light_l2
      light_l2:
        name: slaapkamervooraan2
        value_template: null
        state_value_template: '{{ value_json.state_l2 }}'
      switch_l3:
        type: light
        object_id: light_l3
      light_l3:
        name: voorboventrap
        value_template: null
        state_value_template: '{{ value_json.state_l3 }}'
      switch_l4:
        type: light
        object_id: light_l4
      light_l4:
        name: bovenwc
        value_template: null
        state_value_template: '{{ value_json.state_l4 }}'
```
