### DISCUSSION TITLE
Are all those duplicated PAN id entries normal?

### DISCUSSION THREAD

**Discussion by SergioRius** [Koenkk/zigbee2mqtt#14110] [General]
![imagen](https://user-images.githubusercontent.com/1693727/191352569-6e2a63c0-94df-435c-ba39-e9482da7fc7d.png)

EDIT: Ok, by looking at the documentation I see that it may be normal:
```yaml
advanced:
  # Optional: ZigBee pan ID (default: shown below)
  # Setting pan_id: GENERATE will make Zigbee2MQTT generate a new panID on next startup
  pan_id: 0x1a62
  # Optional: Zigbee extended pan ID (default: shown below)
  ext_pan_id: [0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
```
