### DISCUSSION TITLE
Frontend is not working for me

### DISCUSSION THREAD

**Discussion by amdjml** [Koenkk/zigbee2mqtt#14237] [General]
Hi,

I have followed the instructions found [here](https://www.zigbee2mqtt.io/guide/getting-started/#installation). I am not installing this on RPi. This is on a headless Ubuntu Server using docker-compose.

Here is my `docker-compose.yml` file:

```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8083:8080
    environment:
      - TZ=America/New_York
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
and here is my `configuration.yaml` file:

```
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  network_key:
    - 143
    - REDACTED
    - 161
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
```
When I go to `http://<SERVER-IP>:8099`, nothing loads for me and I get "The site can't be reached". Here is the result of the `netstat` command:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      3677/docker-proxy   
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      85095/docker-proxy  
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1196/docker-proxy   
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      4229/docker-proxy   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      27356/systemd-resol 
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      85115/docker-proxy  
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      85076/docker-proxy  
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1094/docker-proxy   
tcp        0      0 127.0.0.1:33541         0.0.0.0:*               LISTEN      21331/homebridge    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1180/docker-proxy   
tcp        0      0 0.0.0.0:81              0.0.0.0:*               LISTEN      1139/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      38178/sshd: /usr/sb 
tcp6       0      0 :::8082                 :::*                    LISTEN      3685/docker-proxy   
tcp6       0      0 :::8083                 :::*                    LISTEN      85102/docker-proxy  
tcp6       0      0 :::8080                 :::*                    LISTEN      1211/docker-proxy   
tcp6       0      0 :::8081                 :::*                    LISTEN      4237/docker-proxy   
tcp6       0      0 :::51918                :::*                    LISTEN      21331/homebridge    
tcp6       0      0 :::1883                 :::*                    LISTEN      85121/docker-proxy  
tcp6       0      0 :::9001                 :::*                    LISTEN      85082/docker-proxy  
tcp6       0      0 :::8581                 :::*                    LISTEN      21318/hb-service    
tcp6       0      0 :::443                  :::*                    LISTEN      1103/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      1194/docker-proxy   
tcp6       0      0 :::81                   :::*                    LISTEN      1151/docker-proxy   
tcp6       0      0 :::22                   :::*                    LISTEN      38178/sshd: /usr/sb
```
