### DISCUSSION TITLE
Conbee 2 issue with initial install/running

### DISCUSSION THREAD

**Discussion by Tuttle13** [Koenkk/zigbee2mqtt#14340] [Devices]
Hi, been absolutely pulling my hair out with this one.
Been trying to get zigbee2mqtt running, but I can't work out why its failing.

I'm following the instructions, made sure I uninstalled both my old deconz addon, as well as removed the ZHA integration.
Already have MQTT broker installed, and discoverable turned on.

I install z2m, and then in config tab, I leave mqtt blank and enter under serial "port:  /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2651440-if00"
(I have also tried adding a second line "adapter: deconz" after it failed the first 50 times.

But when I start, it loads., and then I get in Log:
[15:11:42] INFO: Preparing to start...
[15:11:42] INFO: Socat not enabled
[15:11:44] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-10-05 15:11:49: Logging to console and directory: '/config/zigbee2mqtt/log/2022-10-05.15-11-49' filename: log.txt
Zigbee2MQTT:info  2022-10-05 15:11:49: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-05 15:11:49: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:error 2022-10-05 15:12:00: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-05 15:12:00: Failed to start zigbee
Zigbee2MQTT:error 2022-10-05 15:12:00: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-05 15:12:00: Exiting...
Zigbee2MQTT:error 2022-10-05 15:12:00: undefined

When I go to the newly created zigbee2mqtt folder, it shows a config file, which when opened ONLY has:
`homeassistant: true`

Doesn't matter how many times I try and run it, nothing else is added. I have tried adding my MQTT details, username and pw, no change.

I have also tried copy pasting someones successful config file into there, but it still wont run correctly (here's the modded file I tried):
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
base_topic: zigbee2mqtt
user: homeassistant
password: #######
serial:
port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2651440-if00
adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
  - 1
  - 3
  - 5
  - 7
  - 9
  - 11
  - 13
  - 15
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 13
  availability_blocklist: []
  availability_passlist: []
  device_options: {}
  blocklist: []
  passlist: []
  queue: {}
  frontend:
  #port: 8099
  experimental: {}
  availability: false
socat:
enabled: false
master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
options: '-d -d'
log: false
```

when I run this version, I still get:
[15:17:14] INFO: Preparing to start...
[15:17:14] INFO: Socat not enabled
[15:17:16] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:error 2022-10-05 15:17:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-05 15:17:32: Failed to start zigbee
Zigbee2MQTT:error 2022-10-05 15:17:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-05 15:17:32: Exiting...
Zigbee2MQTT:error 2022-10-05 15:17:32: undefined

No matter what I try, I can't get beyond this step. I have a conbee 2, and had successfully been using it initially with ZHA and then DeConz. Both are "uninstalled" as best I can tell, but I do notice that in Devices and Services, without anything installed, it does tell me "Discovered: Conbee II - /dev/..." and below that, it says "Zigbee Home Automation". But this isnt configured or installed, so I'm not sure if I can do anything to avoid it doing this.

Is anyone able to help me work out why I can't get it to run?
Thank you for any help, as mentioned, been losing my mind over this today!
