### DISCUSSION TITLE
Multiple serial port on zigbee2mqtt config?

### DISCUSSION THREAD

**Discussion by rcxrbt** [Koenkk/zigbee2mqtt#14423] [General]
Hi all,
 it's possible to configure multiple serial port on Zigbee2MQTT?
Like to connect to one or more remote adapter by Ser2Net.

```
serial:
    port: /dev/ttyACM0
    port: 'tcp://192.168.2.13:20108
    port: 'tcp://192.168.5.30:24348
```
Other solution, like make more Zigbee2MQTT instance?

Tnx
