### DISCUSSION TITLE
Frontend works, but "dashboard" always blank

### DISCUSSION THREAD

**Discussion by bwims** [Koenkk/zigbee2mqtt#14505] [Devices]
Hi,

I've been using the Frontend for some time, and it was only reading a blog article today that the "dashboard" button was actually supposed to do something!

I use the simple configuration option

`frontend: true`

and the device list shows all my devices which are 4 button switches and a sonoff zbbridge converted into a router (see screen grab below).

However, none of these devices appear in the "dashboard" list.   Is this normal?

Here is my configuration file

```
homeassistant: true
permit_join: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt.local:1883
serial:
  port: /dev/ttyACM0
availability: true
devices:
  '0x00124b0025164b66':
    friendly_name: '0x00124b0025164b66'
  '0x04cd15fffe83f75c':
    friendly_name: '0x04cd15fffe83f75c'
  '0x04cd15fffe2e263c':
    friendly_name: '0x04cd15fffe2e263c'
  '0xb4e3f9fffeb69afb':
    friendly_name: '0xb4e3f9fffeb69afb'
  '0x60a423fffe1db1a3':
    friendly_name: '0x60a423fffe1db1a3'
external_converters:
  - silabs.js
  
```

Here is my "devices" list
![image](https://user-images.githubusercontent.com/18516073/196032581-7d70ce25-de44-4145-a977-685d2588c64c.png)

and here is my "dashboard list"

![image](https://user-images.githubusercontent.com/18516073/196032623-ac862b29-9040-4b50-a5fc-90a1ec92250c.png)

I'm grateful for any suggestions!

B.
