### DISCUSSION TITLE
Configure Docker container on Synology

### DISCUSSION THREAD

**Discussion by ZonPV** [Koenkk/zigbee2mqtt#14720] [General]
I have a ITead Sonoff Zigbee 3.0 USB Dongle Plus model ZBDongle-E (based on EFR32MG21)

Downloaded yesterday the latest-dev version and configured to read the configuration.yaml from the host. 

```
# Home Assistant integration (MQTT discovery)
homeassistant: false
# allow new devices to join
permit_join: true
# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.1.18'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password
# Serial settings
serial:
  adapter: ezsp
  port: /dev/ttyACM0
frontend:
  port: 8080
```
The container starts and create a log but seems to have problems to contact the broker of the host. So no entry of zigbee in MQTT Explorer and no frontend available...

This is the log:
```
info  2022-10-30 10:14:47: Logging to console and directory: '/app/data/log/2022-10-30.10-14-47' filename: log.txt
info  2022-10-30 10:14:47: Starting Zigbee2MQTT version 1.28.0-dev (commit #6c0430b)
info  2022-10-30 10:14:47: Starting zigbee-herdsman (0.14.66)
```
There seems to be no conflicts with usbdevices or ports. The adapter is recognized in the Syno on Bus 003 Device 002 with the correct ID..

```
root@DS-718:~# lsusb
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 003: ID f400:f400
Bus 003 Device 002: ID 1a86:55d4 QinHeng Electronics
Bus 003 Device 003: ID 0658:0200 Sigma Designs, Inc.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
```
These are the settings when running the container. It is in BRIDGED mode.
[<a href="https://ibb.co/SRrjWwr"><img src="https://i.ibb.co/SRrjWwr/Portainer.jpg" alt="Portainer" border="0"></a>](url)

Any suggestion is appreciated.

**Comment by ZonPV** [comment]
**Problem solved.**  The container is running in Docker on the Synology. The 'experimental' adapter is doing okay.

In CLI with the command:  
`dmesg | grep tty `
There were 2 devices connected as ttyACM.
As there is one known device; the other should be my Zigbee-device... 

So now the configuration.yaml for Zigbee2mqtt is:

```
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.18
serial:
  adapter: ezsp
  port: /dev/ttyACM1
frontend:
  port: 8081
devices:
  '0x9035eafffef0xxxxxx':
    friendly_name: Dimmer werkkamer
homeassistant:
  discovery_topic: zigbee2mqtt
  legacy_entity_attributes: true
  legacy_triggers: true
  status_topic: homeassistant/status
```
