### DISCUSSION TITLE
Arduino Portenta X8

### DISCUSSION THREAD

**Discussion by TawhiriMaetea** [Koenkk/zigbee2mqtt#15115] [Devices]
I am trying to use zigbee2mqtt on a Portenta X8.

I edited the docker-compose.yml:
```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_feb92d6c2f86ec118770601719c2d21c-if00-port0:/dev/ttyUSB0
```
The data/config:uration.yaml:
```
homeassistant: false
permit_join: true
mqtt:
    base_topic: zigbee2mqtt
    server: 'mqtt://localhost'
    user: ****
    password: ****
serial:
    port: /dev/ttyUSB0
```
Compose works:
`docker-compose up -d zigbee2mqtt`
Start:
`docker exec -it zigbee2mqtt npm start`
This makes the container to enter a restart loop.

Any ideas would be greatly appreciated
