### DISCUSSION TITLE
Sonoff ZBDongle-P stopped working?

### DISCUSSION THREAD

**Discussion by kolaf** [Koenkk/zigbee2mqtt#15332] [General]
Hi,

I have successfully been running ZHA with my Sonoff dongle and a small network of five devices for some time. I needed to set up a second network in another building, so I purchased a SMLIGHT SLZB-06 which I successfully connected to zigbee2mqtt and made available in the same home assistant installation. Never known for leaving well enough alone I decided to change my initial zigbee installation with the Sonoff from ZHA to another Z2M instance as well. At first try this seemed to go quite well, all the devices were paired, and after a time I could see that they had built a mesh network. The day after everything fell to pieces.

I was no longer able to reach any of the devices. I tried resetting and re-pairing them, and Z2M seem to be able to pick up the reset event and the initial pairing, but the interview process almost always fail. In a few cases where the interview process is successful further communication usually times out.

I've tried a couple of things to mitigate the issue:
- I have connected the dongle to a 1.8 m USB extension cable and directly to my Intel NUC
- Updated the firmware of the Sonoff to the latest CC2652P version, 20221102
- Tried different power settings, 5 and 20 dBm 
- Moved the entire installation from one end of the house to the other
- Switched my Wi-Fi network to channel 12 in order to be as far away from Zigbee channel 11 as possible
- Switched back to ZHA but this also seems to have the same problems.

I've attached a log from today's trials where I first remove and re-add the device "Lys kontoret" which initially fails interviewing, but then succeeds, thereafter I remove and re-add "Lys Sirius" which also eventually is successful. however, any attempt to command the devices or retrieve the status fails.

Since the initial removal and adding of devices works it seems that Zigbee reception is okay, but the stick is having trouble transmitting. I am at my wits end and any suggestions are welcome.

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10146109/log.txt)
[configuration.txt](https://github.com/Koenkk/zigbee2mqtt/files/10146110/configuration.txt)

My docker-compose for Z2M:
```yaml
zigbee2mqtthome:
    network_mode: host
    container_name: zigbee2mqtthome
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_5ca2322b5286ec118c29e13719c2d21c-if00-port0:/dev/tty-sonoff
    volumes:
      - ./z2mhome:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8081:8080
    environment:
      - TZ=Europe/Oslo
```
