### DISCUSSION TITLE
Error: SRSP - SYS - ping after 6000ms

### DISCUSSION THREAD

**Discussion by swinster** [Koenkk/zigbee2mqtt#15344] [General]
Hey all,

In the troubleshooting guide (https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-srsp-sys-ping-after-6000ms), there are four common issues. listed for this error. Assuming I have checked them all (plus the rest of the guide) and none of these seem to apply, is there anything else I can look at? 

FWIW, the adapter is a SONOFF Zigbee 3.0 USB Dongle Plus (ZBDongle-P) connected to an old Raspberry Pi v1 B+. For a while back, everything was working, and I could see and pair devices, however, things have been off for a while, and now I only see this error. I'm not sure if the adapter has simply stopped working (although it is listed in `ls /dev/serial/by-id` . 

Any other thoughts on how I might test things? 

e.g.

```
pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.28.4 start
> node index.js

Zigbee2MQTT:info  2022-12-04 00:24:27: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-12-04.00-24-26' filename: log.txt
Zigbee2MQTT:info  2022-12-04 00:24:30: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f9)
Zigbee2MQTT:info  2022-12-04 00:24:30: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:error 2022-12-04 00:25:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-04 00:25:04: Failed to start zigbee
Zigbee2MQTT:error 2022-12-04 00:25:04: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-04 00:25:04: Exiting...
Zigbee2MQTT:error 2022-12-04 00:25:07: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

**Comment by swinster** [comment]
Making sure I'm not doing anything odd:

```
pi@raspberrypi:/opt/zigbee2mqtt $ ls /dev/serial/by-id -l
total 0
lrwxrwxrwx 1 root root 13 Dec  4 00:53 usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ba99a547aa12ec11b15820c7bd930c07-if00-port0 -> ../../ttyUSB0
```

and the configuration.yaml file is:

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:

  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
frontend: true
devices:
  '0x001788010bd14b59':
    friendly_name: Lodge - Philips Hue Outdoor Sensor
```
