### DISCUSSION TITLE
How to map a remote adapter into a zigbee2mqtt docker container

### DISCUSSION THREAD

**Discussion by swinster** [Koenkk/zigbee2mqtt#15360] [General]
Hey,

I thinking about setting up a remote adapter and running zigbee2mqtt as a docker elsewhere. However, I wonder about mapping the device into the container, for example:

```
docker run \
   --name zigbee2mqtt \
   --restart=unless-stopped \
   --device=/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ba99a547aa12ec11b15820c7bd930c07-if00-port0:/dev/ttyUSB0 \
   -p 8080:8080 \
   -v $(pwd)/data:/app/data \
   -v /run/udev:/run/udev:ro \
   -e TZ=Europe/London \
   koenkk/zigbee2mqtt
```

so the line:

```
   --device=/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ba99a547aa12ec11b15820c7bd930c07-if00-port0:/dev/ttyUSB0 \
```

would map the physical adapter on the host to the `/dev/ttyUSB0` device. But how is this achieved if the device is a TCP connection?

The instructions at https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_adapter.html#_2-b-configure-ser2net-4-0 show how to set up the port within the `configuration.yaml` file, but it doesn't discuss how to pass this into a container.

Is this possible? Maybe it doesn't even need to be done?

**Comment by swinster** [comment]
To answer my own question - it DOESN'T need to be specified in the docker mapping (only in the `configuration.yaml` file, e.g.:

```
docker run \
   --name zigbee2mqtt \
   --restart=unless-stopped \
   -p 8080:8080 \
   -v $(pwd)/data:/app/data \
   -v /run/udev:/run/udev:ro \
   -e TZ=Europe/London \
   koenkk/zigbee2mqtt
```

or as a `docker-compose.yaml` file:

```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /opt/zibgee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/London
```

I had some other issues getting things working, but it seems to be up now (well, nearly...).
