### DISCUSSION TITLE
No Frontend after migration

### DISCUSSION THREAD

**Discussion by chefschaffner** [Koenkk/zigbee2mqtt#15759] [General]
Good evening,

I know, this item comes up frequently, but after searching some hours, I hope to find a helping hand here...

I am running z2m on raspberry pi together with fhem. 
Now I migrated the plain z2m installation from pi to a docker container on a different machine;  I'm using portainer to manage my stacks.
The migration worked so far - I can use the devices as before and also the access in fhem works well.

The only thing, which does not work, is the frontend. I tried several configurations. but nothing worked.

In the logs (level: info) I see, that the connection to the mqqt-server is made, but there is no  line "frontend started"

Can anyone help? I do not have any further idea....

**configuration.yaml**

```
homeassistant: false
permit_join: false
mqtt:homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://westfhem.fritz.box
  client_id: zigbee_pi
serial:
  port: /dev/ttyACM0
advanced:
  report: true
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /app/data/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  log_symlink_current: false
frontend: true
device_options:
  legacy: false
devices:
  base_topic: zigbee2mqtt
  server: mqtt://westfhem.fritz.box
  client_id: zigbee_pi
serial:
  port: /dev/ttyACM0
advanced:
  report: true
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /app/data/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  log_symlink_current: false
frontend: true
device_options:
  legacy: false
devices:
...
```

I also tried:
```
...
frontend: 
  port: 8080
....
```
-> no luck....

**docker-compose.yml**

```
version: '3.7'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    build: .
    container_name: zigbee2mqtt
    restart: always
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.z2m.entrypoints=http"
#      - "traefik.http.routers.z2m.rule=Host(`westprimo`) && PathPrefix(`/z2m`)"
#      - "traefik.http.routers.z2m.middlewares=strip-z2m"
#      - "traefik.http.middlewares.strip-z2m.stripprefix.prefixes=/z2m"
#      - "traefik.http.services.z2m.loadbalancer.server.port=8080"
#      - "traefik.docker.network=proxy"
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_3A_7A-if00-port0:/dev/ttyACM0
networks:
  proxy:
    external: true

```
