### DISCUSSION TITLE
group has no members

### DISCUSSION THREAD

**Discussion by osre77** [Koenkk/zigbee2mqtt#15981] [General]
I just set up my system with currently 1 thermostat (more will come soon)
In preparation I created a group for them.
But in MQTT it always tells me the there are no group members.
The device is actually in the network.
```
devices:
  '0x50325ffffe401da8':
    friendly_name: 'temp/office'
    description: 'Office thermostat'
    debounce: 1
    retain: true
    qos: 1
groups:
  '1':
    friendly_name: 'thermostats'
    retain: true
    devices:
      - 'temp/office'
```
I tried to use the friendly_name and the id, but there is no difference.
here is what the groups look like in MQTT
```
zigbee2mqtt/bridge/groups
[
  {
    "friendly_name": "thermostats",
    "id": 1,
    "members": [],
    "scenes": []
  }
]
```

The logs seem to suggest that everything is file:
```
info  2023-01-06 13:08:24: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-01-06 13:08:24: Adding 'temp/office' to group 'thermostats'
info  2023-01-06 13:08:24: MQTT publish: topic 'zigbee2mqtt/thermostats/availability', payload 'online'
```

Any idea whats wrong here?

Thank you, Reinhard.
