### DISCUSSION TITLE
Disable Item if not plugged in. If "Offline" dont ping or contact

### DISCUSSION THREAD

**Discussion by Airmr** [Koenkk/zigbee2mqtt#16031] [Devices]
Hi,
i have several items, mostly Powerplugs that are not used all the time. I simply joined them to the zigbee2mqtt installation and took them from power.
Now i see in Z2M that it still gives a lot of error messages like "Failed to Ping", etc. 
Is there any way to just disable an item that it is not checked while disabled?

Thnx in advance

**Comment by Danit2** [comment]
https://github.com/Koenkk/zigbee2mqtt/discussions/15851

Read the first point of this release note.

**Comment by OrbitingOcelot** [comment]
I hope you do not mind if I piggyback on this with a related question:
I have lights and lightstrips that also get triggered by physical switches (meaning they may be without power for several hours a day until the switch is flipped). However, they do get used often, so a "disable" option is not helpful in this case.

Is there any way to disable the "Failed to ping XXX messages", or supress them for specific devices?
In my setup its perfectly fine for some devices to disappear from the network for hours/days and rejoin when needed.

**Reply by Danit2** [reply]
You can disable the availability feauture for some devices. 

https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#device-availability

```
devices:
  '0x12345678':
    friendly_name: 'my_bulb'
    # Set availablility: false to disable the availability feature for a specific device
    availability: false
```
