### DISCUSSION TITLE
Zigbee2MQTT: Running Edge and Stable with different adapters/coordinators on same HA instance

### DISCUSSION THREAD

**Discussion by buhito81** [Koenkk/zigbee2mqtt#16051] [General]
For some reason I figured it would be nice to replace my ConbeeII stick with a Sonoff Zigbee 3.0 USB Dongle Plus.  Since that involves repairing all my devices; I figured I'd keep my "production" Zigbee on the ConbeeII stick with Zigbee2MQTT stable, whilst I'd also install Zigbee2MQTT edge with the Sonoff stick. In this way I could gradually move to the Sonoff Coordinator, and when everything is repaired, I'd just create a backup in Zigbee2MQTT edge, and restore it in Zigbee2MQTT stable.

However I keep on running into the same type of errors all the time:

```
[11:13:55] INFO: Preparing to start...
[11:13:56] INFO: Socat not enabled
[11:13:57] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-04 11:14:01: Logging to console and directory: '/config/zigbee2mqtt4/log/2023-01-04.11-14-01' filename: log.txt
Zigbee2MQTT:info  2023-01-04 11:14:01: Starting Zigbee2MQTT version 1.29.0-dev (commit #826f032)
Zigbee2MQTT:info  2023-01-04 11:14:01: Starting zigbee-herdsman (0.14.83)
Zigbee2MQTT:error 2023-01-04 11:15:06: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-04 11:15:06: Failed to start zigbee
Zigbee2MQTT:error 2023-01-04 11:15:06: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-04 11:15:06: Exiting...
Zigbee2MQTT:error 2023-01-04 11:15:06: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```

Now, this is for the Zigbee2MQTT **Edge** AddOn that is configured to run with the SonOff Zigbee 3.0 Dongle Plus. My `configuration.yaml` is as follows:

```
data_path: /config/zigbee2mqtt5
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8486,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
mqtt:
  server: mqtt://core-mosquitto
  user: user
  password: password
  base_topic: zigbee2mqqt5
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
advanced:
  pan_id: 11123
  ext_pan_id:
    - 238
    - 238
    - 238
    - 238
    - 238
    - 238
    - 238
    - 238
  channel: 25
```

I keep on getting the following error:

```
[11:35:51] INFO: Preparing to start...
[11:35:52] INFO: Socat not enabled
[11:35:53] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-04 11:35:56: Logging to console and directory: '/config/zigbee2mqtt5/log/2023-01-04.11-35-56' filename: log.txt
Zigbee2MQTT:info  2023-01-04 11:35:56: Starting Zigbee2MQTT version 1.29.0-dev (commit #826f032)
Zigbee2MQTT:info  2023-01-04 11:35:56: Starting zigbee-herdsman (0.14.83)
Zigbee2MQTT:error 2023-01-04 11:37:01: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-04 11:37:01: Failed to start zigbee
Zigbee2MQTT:error 2023-01-04 11:37:01: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-04 11:37:01: Exiting...
Zigbee2MQTT:error 2023-01-04 11:37:01: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```
 My Zigbee2MQTT **Stable** works fine in the meanwhile with this configuration:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto
  user: user
  password: password
serial:
  port: /dev/ttyACM0
  adapter: deconz
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
```
Logging shows that my Zigbee2MQTT **stable** runs with the following network setup:

```
debug 2023-01-04 09:52:55: Loaded state from file /config/zigbee2mqtt/state.json
info  2023-01-04 09:52:55: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-04.09-52-55' filename: log.txt
debug 2023-01-04 09:52:55: Removing old log directory '/config/zigbee2mqtt/log/2022-12-22.08-14-33'
info  2023-01-04 09:52:56: Starting Zigbee2MQTT version 1.29.0 (commit #unknown)
info  2023-01-04 09:52:56: Starting zigbee-herdsman (0.14.83)
debug 2023-01-04 09:52:56: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/ttyACM0"}}'
info  2023-01-04 09:52:56: zigbee-herdsman started (resumed)
info  2023-01-04 09:52:56: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
debug 2023-01-04 09:52:56: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
```
That means the networks can't be conflicting, right?
*Am I being plain stupid here?* I've asked the same question in the HA forum, but to no avail: https://community.home-assistant.io/t/zigbee2mqtt-running-edge-and-stable-with-different-adapters-coordinators-on-same-ha-instance/
