### DISCUSSION TITLE
Ikea ICPSHC24-30EU-IL-1 discovery incomplete

### DISCUSSION THREAD

**Discussion by enboig** [Koenkk/zigbee2mqtt#16238] [Devices]
When adding ICPSHC24-30EU-IL-1 in openhab using discovery, it misses some parts (most importantly the switch). I get:
```
    - sensor/0x0c4314fffe0f8ab6/update_state
    - sensor/0x0c4314fffe0f8ab6/power_on_behavior
    - select/0x0c4314fffe0f8ab6/power_on_behavior
    - binary_sensor/0x0c4314fffe0f8ab6/update_available
    - update/0x0c4314fffe0f8ab6/update
    - light/0x0c4314fffe0f8ab6/light
    - sensor/0x0c4314fffe0f8ab6/linkquality
    - select/0x0c4314fffe0f8ab6/effect
```
So I think it misses
```
    - switch/0x0c4314fffe0f8ab6/switch
```
and some way to modify brightness.

How could this be fixed?

Thanks

**Comment by malaakso** [comment]
That is a light, it doesn't expose a switch. Brightness is modified via "light".

See
https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html

**Reply by enboig** [reply]
You are right, openhab sees `light`:
```
UID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6:mqtt-broker:encimeraCuina
label: encimeraCuina
thingTypeUID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6
configuration:
  topics:
    - sensor/0x0c4314fffe0f8ab6/update_state
    - sensor/0x0c4314fffe0f8ab6/power_on_behavior
    - binary_sensor/0x0c4314fffe0f8ab6/update_available
    - select/0x0c4314fffe0f8ab6/power_on_behavior
    - update/0x0c4314fffe0f8ab6/update
    - sensor/0x0c4314fffe0f8ab6/linkquality
    - light/0x0c4314fffe0f8ab6/light
    - select/0x0c4314fffe0f8ab6/effect
  basetopic: homeassistant
bridgeUID: mqtt:broker:mqtt-broker
```
But don't offer me a "channel" to use it:
![Screenshot_20230118_235440](https://user-images.githubusercontent.com/1155203/213313274-8fb8c95c-d597-457b-b5e4-452fbd833d83.png)

I will ask again in their forum.

Thanks
