### DISCUSSION TITLE
SLZB-06 not working as expected over network

### DISCUSSION THREAD

**Discussion by wimmme** [Koenkk/zigbee2mqtt#16247] [Devices]
Hi,
recently bought myself a SLZB-06 as an upgrade from a CC2531. An out of the box working experience is what i wanted, but not what i got :-/
Cannot get Z2M working with it. Latest stable (1.29.2) version installed, both on Windows and in Docker. My working setup before with the CC2531 was under docker, with the CC2531 connected to a RasPi and served via ser2net over tcp.
If I connect the SLZB--06 via USB, it works immediately. Both when trying via ethernet/WiFi, it doesn't. It does say 1 client connected on the SLZB-06 web interface, but it either times out or goes in error. 
I do realize this is probably the fault of the SLZB-06, and not Z2M's, but i get no response from their support.
Anyone an idea ? 
This is my config:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.12:1883
serial:
  #port: \\.\COM3
  port: tcp://192.168.0.81:6639
  adapter: auto
  baudrate: 115200
advanced:
  log_level: debug
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
frontend:
  port: 1881

```
