### DISCUSSION TITLE
Zigbee2Mqtt randomly not working and needs restart

### DISCUSSION THREAD

**Discussion by Piero87** [Koenkk/zigbee2mqtt#16447] [General]
Hi,
I have Home Assistant OS installted via Virtual Machine inside my Synology NAS 218+, I have installed Zigbee2Mqtt and I use the Sonoff ZBDongle-E with a usb 2.0 extension connected to a 3.0 port inside the NAS, I notice that sometime Zigbee2Mqtt doesn't respond well, and all devices appear offline also if they are not and for example when I enter in this "state" if I press the Permit Join button I get this error:

Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Connection not initialized'

If I go in the Add-ons page of HA and I enter in zigbee2mqtt page I see this:

<img width="1419" alt="Screenshot 2023-01-31 alle 23 34 38" src="https://user-images.githubusercontent.com/768952/215900989-b982f84e-f43e-46f0-bb60-6553a3e16784.png">

Like if the plugin is not running, instead if I refresh the Web UI of zigee2mqtt I can refresh and use it but I can't do anything because seems all offline like the error above, the only way to fix this is restart zigbee2mqtt and all start again.

This is my configuration.yaml

```
homeassistant:
  legacy_entity_attributes: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-user
  password: ****
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220812184127-if00
  adapter: ezsp
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: error
device_options:
  legacy: false
devices:
  '0x000b57fffe2614bd':
    friendly_name: Luce Penisola 1
  '0xf4ce367ea4c6f5a9':
    friendly_name: Luce Corridoio
  '0x70ac08fffe92067b':
    friendly_name: Luce Tavolo
  '0x000b57fffe272232':
    friendly_name: Luce Penisola 2
  '0x000b57fffe2d7d89':
    friendly_name: Luce Grande
availability: true
```

Anyone can help me?
