### DISCUSSION TITLE
zigbee2mqtt starts failed in HA addon

### DISCUSSION THREAD

**Discussion by Leo2442926161** [Koenkk/zigbee2mqtt#17269] [Devices]
Hi Z2M team and @Koenkk 

I installed z2m in my computor and HA in Raspberry pi4, the z2m can running on my computor and paring devices. but I added the z2m addon in HA (z2m and HA is not in same mechine but same local network), it can't starts z2m in HA addon, could anyone help me? thanks.

The zigbee adopter is pluged with my computor, do I need to configurate proxy or something?

the configuration in zigbee2mqtt addon below,
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: 
  base_topic: zigbee2mqtt
  server: mqtt:mqtt://192.168.2.105
  user: heiman
  password: heiman43613
  
serial: {}
```

![db63fda2eb2885e0a37066589d8dd21](https://user-images.githubusercontent.com/30258768/230514079-fb19a13f-c060-4a78-b9aa-cdc079b06469.png)
