### DISCUSSION TITLE
zigbee2mqtt docker "Error: Error while opening serial port 'Error: Error: No such file or directory, cannot open /dev/ttyACM0"

### DISCUSSION THREAD

**Discussion by MetaStack-Exchange** [Koenkk/zigbee2mqtt#17276] [General]
Hello everybody,
I tried to move my existing (and working) home assistant from a ubuntu-laptop to ubuntu server 22.04. Therefore, I installed docker and docker-compose but the zigbee2mqtt-container can't connect to a Texas Instruments CC2531-USB-Stick. While running the container I just get the error message "Error: Error while opening serial port 'Error: Error: No such file or directory, cannot open /dev/ttyACM0"

my docker-compose.yaml looks like this:

```
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /etc/zigbee2mqtt/data:/app/data
      - /etc/zigbee2mqtt/run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD48546-if00:/dev/ttyACM0
```

```
~# ls -l /dev/serial/by-id/
insgesamt 0
lrwxrwxrwx 1 root root 13 Apr  5 02:11 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD48546-if00 -> ../../ttyACM0

```

```
/app #  -w /dev/ttyACM0 && echo success || echo failure
success
```

and my zigbee2mqtt-config file looks like this

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.x.x:1883'
  user: username
  password: password
  client_id: Zigbee
  reject_unauthorized: true
  include_device_information: true
serial:
  port: /dev/ttyACM0
  disable_led: true
devices:
  '0x842e14fffef8d447':
    friendly_name: Steckdose-01
  '0x842e14fffedb8741':
    friendly_name: Steckdose-02
  '0x60a423fffe00487e':
    friendly_name: Steckdose-03
```

I don't know what to do and where to look ... please help me!
