### DISCUSSION TITLE
TS0203 door sensors report 2500mV and 1% battery even with brand new battery

### DISCUSSION THREAD

**Discussion by obones** [Koenkk/zigbee2mqtt#17337] [Devices]
Hello,

I have quite a few TS0203 door sensors around the house, and for some reason that I don't understand they report that their battery voltage is at 2500mV and level is at 1% despite putting a brand new battery 10 days ago. And I measured the battery again, the multimeter says 3V
Here is the state of things:

2 AAA powered -> OK
1 CR2032 powered -> OK
4 CR2032 powered -> 1%

All CR2032 sensors received a new battery 10 days ago

Is that an issue with zigbee2mqtt (I doubt it) or a malfunction in the device themselves?

**Comment by danielszilagyi** [comment]
I have similar issue with maybe only one batch of the same looking cheap window sensors. 

The devices report 1% with brand new battery, but `battery_low` is false. 

```yaml
device_class: window
friendly_name: Nappali_WindowSensor_Right Door
battery: 1
battery_low: false
contact: true
device:
  applicationVersion: 67
  dateCode: ""
  friendlyName: Nappali_WindowSensor_Right
  hardwareVersion: 1
  ieeeAddr: "0xa4c1380d9a59bea6"
  manufacturerID: 4417
  manufacturerName: _TZ3000_mq9f17dw
  model: TS0203
  networkAddress: 48256
  powerSource: Battery
  stackVersion: 0
  type: EndDevice
  zclVersion: 3
last_seen: "2024-01-14T16:50:08+01:00"
linkquality: 207
tamper: false
voltage: 2500
```
