### DISCUSSION TITLE
MQTT error: connect ECONNREFUSED 127.0.0.1:1883

### DISCUSSION THREAD

**Discussion by PeerHamood** [Koenkk/zigbee2mqtt#17348] [General]
Hi, I am seeing this issue and I am out of ideas. 
When I start the docker, zigbee2mqtt gives me this error
```
Using '/app/data' as data directory
Zigbee2MQTT:info  2023-04-15 16:23:47: Logging to console and directory: '/app/data/log/2023-04-15.16-23-47' filename: log.txt
Zigbee2MQTT:info  2023-04-15 16:23:47: Starting Zigbee2MQTT version 1.30.1 (commit #eb878d3)
Zigbee2MQTT:info  2023-04-15 16:23:47: Starting zigbee-herdsman (0.14.89)
Zigbee2MQTT:info  2023-04-15 16:23:47: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-04-15 16:23:47: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2023-04-15 16:23:47: Currently 0 devices are joined:
Zigbee2MQTT:warn  2023-04-15 16:23:47: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2023-04-15 16:23:47: Allowing new devices to join.
Zigbee2MQTT:warn  2023-04-15 16:23:47: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2023-04-15 16:23:47: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-04-15 16:23:48: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:error 2023-04-15 16:23:48: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:48: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2023-04-15 16:23:48: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2023-04-15 16:23:49: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:50: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:51: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:52: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:53: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-04-15 16:23:54: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:info  2023-04-15 16:23:55: Stopped zigbee-herdsman
``` 

**Docker-compose file:**
```
version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /opt/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Helsinki
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0

``` 

**MQTT:**
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883

## Authentication ##
allow_anonymous false
password_file /mosquitto/config/password.txt

``` 

**Zigbee2mqtt:**
```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.1.24'
  # MQTT server authentication, uncomment if required:
  user: hass
  password: asdf

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyUSB0

``` 

Any kind of help is much appreciated.
