### DISCUSSION TITLE
Aqara E1 TRV schedule syntax

### DISCUSSION THREAD

**Discussion by Mikaka27** [Koenkk/zigbee2mqtt#17481] [Devices]
Hi,
I seem to have a problem understanding what the schedule settings syntax means for Aqara E1 TRV.
Default value is here: https://www.zigbee2mqtt.io/devices/SRTS-A01.html#schedule-settings-text

As you can see it is:
mon,tue,wed,thu,fri|8:00,24.0|18:00,17.0|23:00,22.0|8:00,22.0

It seems strange for me because I would understand it as the following:
 - at 8:00 in the morning set temp to 24.0
 - at 18:00 set temp to 17.0
 - at 23:00 set temp to 22.0
 - and again at 8:00 set to 22???? (how could it be that it is set to both 24.0 and 22.0 at 8:00???)

I would be grateful if someone could clarify.
Best regards.

**Comment by RomchikL** [comment]
Has anyone tried to change the default value?
e.g. add more than 4 time periods or add different arrays (time/temp) for different days (mon,fri|....|,sat,sun|...|)
What is the syntax for such a schedule?

**Comment by HolgerAusB** [comment]
I am interested in this, too. Additionally I need to ask how to set and check the current date (day of week) and time on the device. Or is z2mqtt doing this in the background?

Because, if we can't set the time (daylight saving time) it does not make any sense to have schedule set directly on the device. I think that is only for use with Aqara/Xiaomi app.

Is someone using this schedule and can confirm, that it is working without a connection to the app?

It would be nice to use this as a fallback, if smart home components broke or disconnect

**Reply by Ra72xx** [reply]
You can find something in some closed issue thread which I don't find right now:

- Only four switches per day possible
- Time is in UTC and not synced, so it will drift

Recommendation in this thread: Use another scheduler

Does anybody know how to manually start a valve calibration? My thermostats now all show the valve error message, but as they still work, I don't really know what that means.

**Reply by HolgerAusB** [reply]
not really. Today it was the first time this year to heat and I got that error too. I took the batteries out for 10 minutes and put them back. Calibration started right away.

**Reply by Ra72xx** [reply]
As I've just installed the thermostats and they lost their calibration after a few days, I'm afraid that this will be a recurring problem. Unfortunately, you also get only this error message and it can mean everything, from stuck valve to thermometer problems.
It seems to be possible to calibrate the device with the original app.

**Reply by KF2806** [reply]
You could calibrate with mqtt.

**Reply by Ra72xx** [reply]
Yes, that's what I'm looking for, but how?!

**Reply by KF2806** [reply]
You could use the service mqtt publish. Sorry the screenshot is in german, but i think you know how to do. Please use the name from your TRV in topic.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/130925381/b84cef29-f2d4-48bc-970a-ed2971fad49e)

**Reply by Ra72xx** [reply]
Thanks for the hint. How do you find the documentation for this thermostat? I have the feeling that you have to dig through dozens of Github issue threads to collect the necessary information :-/ .

**Reply by HolgerAusB** [reply]
confirmed here too with Aqara E1. Made a [PullRequest](https://github.com/Koenkk/zigbee2mqtt.io/pull/2274) to the documentation. Thank you for that hint.

**Reply by RomchikL** [reply]
@Ra72xx I think [this ](https://github.com/Koenkk/zigbee2mqtt/issues/13993#issuecomment-1744262357)post (and the thread) are related to the discussion.
But I note that in the original Aqara app there is a possibility to set up a smart schedule for different days (different schedules on different days of the week), see the screenshot. So this is a limitation of z2m, not a physical device.

Also, this app allows you to manually start a valve calibration, which confirms PullRequest.

<details>
  <summary>Screenshot</summary>
  
<img width="1605" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/81814142/fcddeb55-0969-4fbc-816c-605145af75cf">

</details>

Here is a snippet of automation for a smart schedule (different schedules on workdays and weekends).

```
      - alias: lr_aqara_e1_temp_schedule
        id: lr_aqara_e1_temp_schedule
        description: Smart schedule Aqara E1
        initial_state: true
        trigger:
         - platform: time
           at: "06:00:00"
           id: "06"
         - platform: time
           at: "07:00:00"
           id: "07"
        action:
          - if:
             - "{{ is_state('binary_sensor.workday_sensor', 'off')  }}" 
            then: 
              - choose:
                - conditions:
                    - condition: trigger
                      id: "06"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        entity_id: climate.0xXXXXXXXXXXXXX
                        temperature: 23
                - conditions:
                    - condition: trigger
                      id: "07"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        entity_id: climate.0xXXXXXXXXXXXXX
                        temperature: 22 
                 ...
            else:                                       
              - choose:
                - conditions:
                    - condition: trigger
                      id: "06"
                  sequence:
                    - service: climate.set_temperature
                      data:
                        entity_id: climate.0xXXXXXXXXXXXXX
                        temperature: 23
               ...
```
