### DISCUSSION TITLE
use by-path for devices ?

### DISCUSSION THREAD

**Discussion by glennpierce** [Koenkk/zigbee2mqtt#17517] [Devices]
I have recently had to update my openmediavault server. I use to run zigbee2mqtt with docker with the following compose file

```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    group_add:
      - dialout
    user: 1000:1000
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_4a482f22fa93eb11a804a75b3d98b6d1-
    volumes:
      - /opt/docker-settings/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8081:8080
    environment:
      - TZ=Europe/London
```

Everything was fine until the update where I think systemd broke the udev serial/by-id links. they are no longer there

So I tried to use by-path links instead with
ie

```
    devices:
       - /dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0:/dev/ttyUSB0
```

but this always fails with

```
docker compose command failed | error="exit status 1" error_output=" Network zigbee2mqtt_default  Creating\n Network zigbee2mqtt_default  Created\n Container zigbee2mqtt  Creating\n Container zigbee2mqtt  Created\n Container zigbee2mqtt  Starting\nError response from daemon: error gathering device information while adding custom device \"\": no such file or directory\n" output=
```

PS I have got it working with the following but want to change it as its fragile.

```
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
