### DISCUSSION TITLE
Z2M in QNAP Container Station with Sonoff USB dongle

### DISCUSSION THREAD

**Discussion by PePe2KC** [Koenkk/zigbee2mqtt#17591] [Devices]
Hi,

I run Z2M in QNAP Container Station using old CC2531
Recently I wanted to upgrade my CC2531 but can't get Z2M working with Sonoff.

**Anyone successfully connected Sonoff USB dongle and runs Z2M on QNAP?**

Z2M can't connect to adapter:

> Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

I already tried the solution desribed here (incl. installation of USC serial drivers) https://github.com/Koenkk/zigbee2mqtt/discussions/14863

Still no success..do I need any specific configuration in configuration.yaml?

Any ideas?

**Comment by 1igeza** [comment]
I was using z2m in QNAP. 
In qnap ssh:
```
sudo insmod /lib/modules/5.10.60-qnap/cp210x.ko
sudo vi /sys/bus/usb-serial/drivers/cp210x/new_id
10c4 ea60
```
And save file. After this I was able to run Z2M in container station

```
version: "3.9"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt-dev
    image: koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    volumes:
      - /share/Container/z2m/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8888:80
    environment:
      - TZ=Europe/Warsaw
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
 - /share/Container/z2m/data:/app/data  - My z2m data was in  /share/Container/z2m/data
