### DISCUSSION TITLE
Support for Home Assistant Event Entities

### DISCUSSION THREAD

**Discussion by bdr99** [Koenkk/zigbee2mqtt#18389] [General]
Home Assistant has added a new entity type called event entities. It was merged in https://github.com/home-assistant/core/pull/96797 and was released in HA 2023.8. This entity type makes it easier for users to discover the events available on a device and create automations involving them.

On [this documentation page](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#responding-to-button-clicks), Zigbee2MQTT currently suggests using device triggers as the recommended way to listen to events from a Zigbee device. It would be awesome if Zigbee2MQTT could support event entities as a new way to accomplish this. The event entity could replace the legacy sensor entity (`legacy_triggers: true`), and potentially the device triggers as well, since I assume that HA will automatically generate device triggers for the event entities on a device.

HA has added support for event entities in the MQTT integration in this PR: https://github.com/home-assistant/core/pull/96876

![image](https://user-images.githubusercontent.com/195327/254939018-9b4d0667-7620-4ccc-95af-dce4e1c02be3.gif)

**Comment by stadros83** [comment]
Does Z2M send events entities now ?

**Reply by bdr99** [reply]
I don't think so.

**Comment by Mincka** [comment]
Great suggestion. I'm new to Z2M and I was looking for something similar of what's done with Deconz integration: a button press sends an event on the event bus on HA. It's so easy to use in automations...

```
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      unique_id: 00:17:88:01:06:06:81:5c # Stable ID that does not change like the HA device ID
      event: 1002 # Click (xxx2) on left button (1xxx)
```

As HA users, we know that the device trigger is sadly the worst method in the long term and it should not be recommended.
The MQTT trigger is not user friendly, needs a little bit of templating, and it's quite verbose.
Finally, the state method seems like a workaround, that seems to work great, but feels also like a hack to handle button events with the "sensor" domain.

Current method with states (the state value is cleared immediately after the value is set):
```
automation:
  - alias: Respond to button click
    trigger:
      platform: state
      entity_id: sensor.my_switch_click
      to: 'single'
    action:
      entity_id: light.my_bulb_light
      service: light.toggle
```

The shortest equivalent (mono button device, any click type trigger), with the support of the Event entity, would be:
```
automation:
  - alias: Respond to button click
    trigger:
      platform: state
      entity_id: event.my_switch_button
    action:
      entity_id: light.my_bulb_light
      service: light.toggle
```

The state of an Event entity is always the timestamp of the last event for a button.

Sample for Fibaro (Z-Wave JS) that now creates event entities:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/6184289/54faa623-3d09-4d2d-83ab-588836c8bd72)

It's possible to support multiple buttons with trigger IDs and multiple types of button press with a conditional switch.

```
automation:
  - alias: Respond to button click
    trigger:
      platform: state
      entity_id: event.my_switch_button
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: event.my_switch_button
                attribute: "event_type"
                state: "short_release"
            sequence:
               - entity_id: light.my_bulb_light
                  service: light.toggle
```

Detailed examples and documentation:
https://www.home-assistant.io/integrations/event/
https://developers.home-assistant.io/docs/core/entity/event
