### DISCUSSION TITLE
Exposing switch as a light (Tuya switches TS0001 and TS0002)

### DISCUSSION THREAD

**Discussion by Daniel76145** [Koenkk/zigbee2mqtt#19171] [Devices]
For the following devices:
TS0001 and TS0002 I have followed "Exposing switch as a light" section in the instruction:
https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#changing-supported-color-modes 

I have the following in the zigbee2mqtt/configuration.yaml
```
homeassistant: true
device_options:
  legacy: false
devices:
  '0xa4c13833a9893ea5':
    friendly_name: light.garaz
    homeassistant:
      name: light.garaz
    switch:
      type: light
      icon: light
      object_id: light
      state_value_template: '{{ value_json.state }}'
    icon: light
    legacy: false
    optimistic: false
```
What is the reason why home assistant (MQTT) see the light as a switch? For _IKEA TRADFRI bulb_ I do not need to add anything to configuration.yaml and the IKEA bulb is shown as light. I don;t want to use helpers within HA rather to have lights enteties. Any suggestions?

**Comment by francisp2** [comment]
Syntax is not correct

```
homeassistant: true
device_options:
  legacy: false
devices:
  '0xa4c13833a9893ea5':
    friendly_name: light.garaz
    switch:
      type: light
      icon: light
      object_id: light
    light:
      name: garaz
      value_template: null
      state_value_template: '{{ value_json.state }}'
    icon: light
    legacy: false
    optimistic: false
```

**Reply by francisp2** [reply]
Under controls I really see light.garaz ?

**Reply by Daniel76145** [reply]
**Solution:** complete code has to be copied into configuration.yaml, inluding after line
` # OR if your devices has multiple endpoints (e.g. left/right)`


```
devices:
  "0x12345678":
    friendly_name: my_switch
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        name: null
        value_template: null
        state_value_template: '{{ value_json.state }}'
      # OR if your devices has multiple endpoints (e.g. left/right)
      switch_left:
        type: light
        object_id: light_left
      light_left:
        name: my_switch_left
        value_template: null
        state_value_template: '{{ value_json.state_left }}'
      switch_right:
        type: light
        object_id: light_right
      light_right:
        name: my_switch_right
        value_template: null
        state_value_template: '{{ value_json.state_right }}']
```
