### DISCUSSION TITLE
Monitor network health and automation to restart Zigbee2MQTT

### DISCUSSION THREAD

**Discussion by simenopsahl** [Koenkk/zigbee2mqtt#19300] [General]
So I have made two sensors in HA
First i enabled the last_seen sensor for all my mains powered devices (routers)
one sensor is for the timestamp of the last_seen device
```yaml
sensor:
  - name: "zigbee_devices_last_seen"
    device_class: timestamp
    icon: mdi:zigbee
    availability: |
      {{ states('sensor.zigbee2mqtt_bridge_state') == 'online' }}
    state: |
# timestamp of latest last_seen device
      {% set result = namespace(sensors=[]) %}
        {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
          {% if 'last_seen' in state.entity_id %}
            {% if 'unavailable' not in state.state %}
              {% set result.sensors = result.sensors + [state.state ] %}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% set result.sensors = result.sensors | sort(reverse=true) %}
      {{ result.sensors[0] }}
    attributes:
 # shows the full array
      array: |
        {% set result = namespace(sensors=[]) %}
          {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
            {% if 'last_seen' in state.entity_id %}
              {% if 'unavailable' not in state.state %}
                {% set result.sensors = result.sensors + [state.state ] %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% set result.sensors = result.sensors | sort(reverse=true) %}
        {{ result.sensors }}
```
the second sensor uses the same parameters to monitor the health of the network
```yaml
binary_sensor:
 - name: "zigbee_devices_online"
    device_class: connectivity
    icon: |
      {% if this.state == 'on' %}
        mdi:check-network
      {% else %}
        mdi:close-network
      {% endif %}
    availability: |
      {{ states('sensor.portainer_local_zigbee2mqtt') == 'running' }}
    state: |
# if a third of the mains powered devices are unavailable, reports false
      {{ (this.attributes.count_offline <= this.attributes.threshold)
          or (not is_state('sensor.zigbee2mqtt_bridge_state', 'offline')) }}
    attributes:
      count: |
# number of devices
        {% set result = namespace(sensors=[]) %}
          {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
            {% if 'last_seen' in state.entity_id %}
              {% set result.sensors = result.sensors + [state.state ] %}
            {% endif %}
          {% endfor %}
        {% set zigbee_devices = result.sensors | count %}
        {{ zigbee_devices | int }}
      threshold: |
# threshold to consider network unhealthy
        {% set result = namespace(sensors=[]) %}
          {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
            {% if 'last_seen' in state.entity_id %}
              {% set result.sensors = result.sensors + [state.state ] %}
            {% endif %}
          {% endfor %}
        {% set zigbee_devices = result.sensors | count %}
        {% set threshold = zigbee_devices / 3 %}
        {{ threshold | int }}
      count_offline: |
# number of devices offline
        {% set result = namespace(sensors=[]) %}
          {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
            {% if 'last_seen' in state.entity_id %}
              {% if 'unavailable' in state.state %}
                {% set result.sensors = result.sensors + [state.state ] %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% set zigbee_offline = result.sensors | count %}
        {{ zigbee_offline | int }}
```

Now I am about to make an automation to restart z2m if the binary_sensor is off, if offline devices is steadily increasing, or if the last seen device is some time ago. I would limit this automation to not run again within the hour or some more time
Just checking if I could use the mqtt.publish service to restart z2m
```yaml
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/bridge/request/restart
```

**Comment by keithr59** [comment]
Alternatively you could use the hassio.addon_restart service

```
 - service: hassio.addon_restart
    data:
      addon: 45df7312_zigbee2mqtt
```

**Comment by simenopsahl** [comment]
I am running the Zigbee2MQTT proxy version, so I couldn't restart that way. But the way I did it works well. I have issues with the network failing. I have moved to all Philips Hue bulbs, but I still have some other devices which I guess won't play nice. Instead of fixing the root problem and going through ~150 devices, or rebuilding using a different coordinator I decided to work around the problem, and it works well so far.

I changed the state of the zigbee_devices_last_seen sensor to display seconds since last communication
```
{% set result = namespace(sensors=[]) %}
  {% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
    {% if 'last_seen' in state.entity_id %}
      {% if 'unavailable' not in state.state %}
      {% set result.sensors = result.sensors + [state.state ] %}
      {% endif %}
    {% endif %}
  {% endfor %}
{% set result.sensors = result.sensors | sort(reverse=true) %}
{{ (as_timestamp(now()) - as_timestamp(as_datetime(result.sensors[0]))) | round(0) }}
```
and I separated out a sensor to show the count of offline routers
```yaml
name: "zigbee_devices_offline"
icon: mdi:zigbee
availability: |
  {{ states('sensor.zigbee2mqtt_bridge_state') == 'online' }}
state: |
  {{ state_attr('binary_sensor.zigbee_devices_online', 'count_offline') | int }}
```
then I made a sensor to show the change in offfline routers
```yaml
platform: statistics
name: "zigbee_devices_offline_change"
entity_id: sensor.zigbee_devices_offline
state_characteristic: change
max_age:
  minutes: 20
sampling_size: 50
```

Finally I made an automation to restart the zigbee2mqtt server
```yaml
alias: zigbee_network_restart
# whichever triggers first
trigger:
# statistics sensor showing change in offline routers
  - platform: state
    entity_id:
      - sensor.zigbee_devices_offline_change

# sensor shows as offline if more than a third is offline
  - platform: state
    entity_id:
      - binary_sensor.zigbee_devices_online
    from: "on"
    to: "off"
condition:
# confirm that the server is not already offline or restarting
  - condition: state
    entity_id: sensor.zigbee2mqtt_bridge_state
    state: online

# devices dropping out are increasing
  - condition: numeric_state
    entity_id: sensor.zigbee_devices_offline_change
    above: 1

# last message received more than 120s ago
  - condition: numeric_state
    entity_id: sensor.zigbee_devices_last_seen
    above: 120

# just an additional check
  - condition: numeric_state
    entity_id: sensor.zigbee_devices_offline
    above: 15
action:
# script to run either addon restart or mqtt message restart
  - service: script.zigbee2mqtt_restart
    data: {}

# notify my devices
  - service: notify.simen_all
    data:
      title: Warning - ZigBee network
      message: |
        <b>ZigBee</b> network is restarting
      data:
        notification_icon: mdi:zigbee
        channel: Warn
        group: Warn-LAN
        tag: Warn-LAN

# make sure it doesn't run again too soon
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
mode: single
```
Here's a screenshot of my lovelace zigbee card, it show's three restarts over the past two days, much better than finding out that the network died overnight and I have to restart manually.
![Screenshot 2023-10-20 203940](https://github.com/Koenkk/zigbee2mqtt/assets/2676016/973e6110-7fee-4dac-8f05-7a1f6b5669e0)
