### DISCUSSION TITLE
Problem with Zigstar UZG-01

### DISCUSSION THREAD

**Discussion by shawwellpete** [Koenkk/zigbee2mqtt#19391] [Devices]
I am currently running Z2M on docker using docker compose and managed with Portainer on a NUC. I use a Sonoff Zigbee 3.0P and generally it works well. 

I have had some issues where the stick occasionally loses connection with all devices and I have to unplug it and plug it back in 20 secs later. On advice elsewhere I put the stick on a USB extender but the issue still happens and is difficult to fix remotely.

Someone suggested that the Zigstar USG-01 may be better so I ordered one. I can see the device on my network and have changed the configuration.yaml file to this as recommended by the zigstar documentation

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.11
  user: blandfordp
  password: PASSWORD
# Serial settings
serial:
  # Location of UZG-01
  port: tcp://192.168.1.113:6638
  baudrate: 115200
  # Disable green led?
  disable_led: false

frontend: true

advanced:

  transmit_power: 20
  channel: 20


```
Z2M does not run and I get the following error in the logs 

```
Zigbee2MQTT:error 2023-10-22 11:30:35: Exiting...
Zigbee2MQTT:error 2023-10-22 11:30:35: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
```

Any suggestions? I  have asked on the zigstar support but so far no help...
