### DISCUSSION TITLE
Bosch controlling all Thermostats BTH-RA with one Room Thermostat BTH-RM

### DISCUSSION THREAD

**Discussion by DSRocker** [Koenkk/zigbee2mqtt#19505] [Devices]
Is it possible to controll all Bosch thermostats II with one Room Thermostat II?

**Comment by Mag11c** [comment]
Hi, i have 1x BTH-RM and 2x BTH-RA since last week. I'm still experimenting but i think it will work.
I'm currently using better thermostat (BT) to combine both BTH-RA to one thermostat. Changes of setpoint temperature on BTH-RM are handled by automation to set temperature on thermostat (the BT device in my case)
I can't say anything about longterm stability ... i hope, it will do fine :)

br
Michael

**Reply by DSRocker** [reply]
Can you share your automation please!?  :-)

**Comment by Mag11c** [comment]
sure ... i'm using Home Assistant. The automation is still very simple:

```
trigger:
  - platform: state
    entity_id:
      - climate.bosch_bthrm_01
    attribute: occupied_heating_setpoint
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: "{{ trigger.to_state.attributes.occupied_heating_setpoint }}"
    target:
      device_id: 5da53d69014ea6d7a852f0fcfccdc0dc
mode: single
```

The target device is better thermostat ... but controlling the BTH-RA directly should work too.
I will add another automation, which updates the BTH-RM after manual change at one of the BTH-RA.

Important: you should ensure, that all devices remain in manual mode (shown as "hand" symbol).
I guess at least the BTH-RM has an internal time schedule, which isn't supported by Z2M (yet?)

-Michael
