### DISCUSSION TITLE
migrating coordinator from Conbee 2 to Conbee 3

### DISCUSSION THREAD

**Discussion by DAVIZINH0** [Koenkk/zigbee2mqtt#19785] [General]
Hello,
With the release of Conbee III and the hability tu support more devices directly, some people (like me) will be migrate from the older conbee II to the newest conbee III

It will be interesting if exist some procedure to migrate and not need to re-pair all the devices (more than 100, will be a big issue).

Someone have the conbee 3?

**Comment by Hedda** [comment]
Not officially, see related feature request here asking for deconz adapter backup and restore support -> https://github.com/Koenkk/zigbee-herdsman/issues/665

Tip; There is a possible unofficial workaround using zigpy as a third-party command tool for backup and restore parts -> https://github.com/Koenkk/zigbee2mqtt/discussions/16478

Summery; Migration from one ConBee/RaspBee adapter to another is currently not possible inside Zigbee2MQTT. For that to be possible Zigbee2MQTT would first need to add support for [deconz adapter](https://github.com/Koenkk/zigbee-herdsman/tree/master/src/adapter/deconz) backup and restore features, as the [deconz adapter code in the zigbee-herdsman library](https://github.com/Koenkk/zigbee-herdsman/tree/master/src/adapter/deconz) which Zigbee2MQTT depends on does not yet support Zigbee network backup and restore from ConBee/RaspBee Zigbee Coordinator adapters, as such you can not simply backup your old ConBee II adapter to a file from inside Zigbee2MQTT and then just restore such backups from file to your new ConBee III adapter (as you can with Texas Instruments based [z-stack adapter](https://github.com/Koenkk/zigbee-herdsman/tree/master/src/adapter/z-stack) in Z2M because that already supports the backup and restore feature inside the zigbee-herdsman library).

https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another

Hopefully, the deconz adapter developers will priotiríze this feature in zigbee-herdsman now that new ConBee III adapter being available(?).

PS: Note that before creating a backup for migration you will always first need to upgrade the firmware on your old ConBee/RaspBee adapter before doing a backup! (That is however not needed if backing up an old Silicon Labs or Texas Instruments based Zigbee Coordinator). It is generally also recommended to upgrade the firmware on the new ConBee/RaspBee adapter before migrating to it.

https://flemmingss.com/how-to-update-conbee-conbee-ii-firmware-in-windows-10/

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Reply by Hedda** [reply]
> Tip; There is a possible unofficial workaround using zigpy as a third-party command tool for backup and restore parts -> https://github.com/Koenkk/zigbee2mqtt/discussions/16478

Posted a specific question about using zigpy-cli with ConBee III (ConBee 3) for backup and restore parts here -> https://github.com/zigpy/zigpy-cli/discussions/41

**Comment by Hedda** [comment]
Tip; should be easy to migrate (backup + restore) adapter via TubesZB's and ZigStar's addons add-on if using Z2M with Home Assistant:

https://github.com/tube0013/tubeszb_addons

https://github.com/mercenaruss/zigstar_addons

For more information see:

https://github.com/tube0013/tubeszb_addons/blob/main/tzb-zigpy-cli-tools/DOCS.md

Discussions:

https://community.home-assistant.io/t/new-add-on-for-running-zigpy-cli-commands-like-energy-scans/669727/

PS: Note however that TubesZB and ZigStar does not officially support ConBee/RaspBee based adapters as they do not sell those.

**Reply by DAVIZINH0** [reply]
thanks for the work, i will test it.
Its compabile with conbee 3?

**Reply by Hedda** [reply]
> Its compabile with conbee 3?

Yes it should be, (it is based on zigpy-cli and zigpy-deconz which are compatible with ConBee III), see the references:

https://github.com/Koenkk/zigbee2mqtt/discussions/19785

https://community.home-assistant.io/t/migration-from-conbee-ii-to-conbee-iii/643550

https://community.home-assistant.io/t/conbee-iii-conbee-3-from-dresden-elektronik-based-on-silicon-labs-efr32mg21-20dbm-radio-soc-mcu/649835

**Reply by DAVIZINH0** [reply]
ok thanks. i will try again. 
I try this morning with my conbee2 for testing and got a error when i push "save button" in configuration tab

**Reply by Hedda** [reply]
If Zigbee2MQTT is used in a Docker container then you might need to install and configure Docker-Compose, see example here (that probably needs to be adapted) -> https://www.home-assistant.io/integrations/zha#docker-compose

Suggest that you intsead of here post to that thread inte Home Assistant community forum is having problems with that add-on.

**Reply by Hedda** [reply]
You of course also need to change both the serial port as well as the baud rate speed in Zigbee2MQTT configuration file.

Believe ConBee II uses 57600 baudrate + hardware flow control and the new ConBee III uses 115200 baudrate and no flow control.

Example from:


```
serial:
  port: /dev/ttyACM0
  adapter: deconz
  baudrate: 57600
  rtscts: true

advanced:
  # Optional: Set the adapter delay, only used for Conbee/Raspbee adapters (default 0).
  # In case you are having issues try `200`.
  # For more information see https://github.com/Koenkk/zigbee2mqtt/issues/4884
  adapter_delay: 0
```

to

```
serial:
  port: /dev/ttyUSB0
  adapter: deconz
  baudrate: 115200
  rtscts: false

advanced:
  # Optional: Set the adapter delay, only used for Conbee/Raspbee adapters (default 0).
  # In case you are having issues try `200`.
  # For more information see https://github.com/Koenkk/zigbee2mqtt/issues/4884
  adapter_delay: 0
```
