### DISCUSSION TITLE
Zigbee2MQTT UI in Portainer not reachable

### DISCUSSION THREAD

**Discussion by treckertom** [Koenkk/zigbee2mqtt#19786] [General]
Hi Folks.

I am trying to set up a Stack enseble consisting of Home assistant, Mosquitto an zigbee2mqtt.
I've got some problems with this common zigbee2mqtt stack:

```
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
      # network_mode: host
    volumes:
      - /srv/dev-disk-by-uuid-6efe48fd-6077-46b3-8d88-ed1eef9349f2/appdata/zigbee2mqtt-data:/app/data
      #- ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 83:8080
    environment:
      - PUID=1006
      - PGID=100
      - TZ=Europe/Berlin
    devices:
      # Make sure path right to : matched your adapter location
      - /dev/ttyACM0:/dev/ttyACM0
```

The USB Stick type receiver is a ConBee II and is detected but will not be recognized by Zigbee2MQTT.
This ist the result of the log:

```
Using '/app/data' as data directory
Zigbee2MQTT:info  2023-11-20 13:41:20: Logging to console and directory: '/app/data/log/2023-11-20.13-41-20' filename: log.txt
Zigbee2MQTT:info  2023-11-20 13:41:20: Starting Zigbee2MQTT version 1.33.2 (commit #9996c93)
Zigbee2MQTT:info  2023-11-20 13:41:20: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:info  2023-11-20 13:41:21: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-11-20 13:41:21: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
Zigbee2MQTT:info  2023-11-20 13:41:21: Currently 0 devices are joined:
Zigbee2MQTT:info  2023-11-20 13:41:21: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-11-20 13:41:22: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:error 2023-11-20 13:41:22: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2023-11-20 13:41:22: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2023-11-20 13:41:22: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2023-11-20 13:41:23: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:info  2023-11-20 13:41:23: Stopped zigbee-herdsman
Using '/app/data' as data directory
```
(and again, again)

The Stack zigbee2mqtt is running in portainer.
However, UI via port 83 is not reachable.
After a while the published Port disappears in portainer.

Any hints?
