### DISCUSSION TITLE
Docker: Can we skip UDEV in favour of "by_ID"

### DISCUSSION THREAD

**Discussion by WJ4IoT** [Koenkk/zigbee2mqtt#19815] [General]
I am using Zigbee2MQTT in Docker for a while and because it is one of the two USB devices attached to my system (Inter NUC) sometimes the USB port will change after a reboot. I understand I can prevent this with UDEV but do not understand completely how this is done in  inside the docker compose example; I see the UDEV line but the device itself is still referred as an USB port. I completely missed that but after a system reboot (eg power failure) it became evident I did not have a solid installation yet. Inside a [HA-topic ](https://community.home-assistant.io/t/static-usb-ports-via-udev-rules-mapped-into-a-docker-container-via-compose-yaml-do-not-work-after-reboot/607020)and composed a simplified version still working after a system reboot and without the use of UDEV!

```
# https://www.zigbee2mqtt.io/guide/getting-started/#installation
# https://community.home-assistant.io/t/static-usb-ports-via-udev-rules-mapped-into-a-docker-container-via-compose-yaml-do-not-work-after-reboot/607020/6

version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data:/app/data
      #- /run/udev:/run/udev:ro (no need for this anymore)
    ports:
      - 8888:8080  
    environment:
      - TZ=Europe/Amsterdam
    devices:
      # Use for USB device its ID and not the assigned USB port because when there are more than 1 USB devices attched on a
      # systemreboot assigned USB ports can (and will) change. UDEV can be used also but requires extra work outside the container.
      # Command to show USB devices by ID: sudo ls -la /dev/serial/by-id
      # for your docker-container use a logical USB name. Allign this name in configuration.yaml.
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyUSB_ZIGBEE
```

If this is a correct and simplified solution?
