### DISCUSSION TITLE
Restarting Z2M kills the 'database.db' file - every time!

### DISCUSSION THREAD

**Discussion by oywino** [Koenkk/zigbee2mqtt#19924] [General]
I have Z2M v1.33.2 commit: 9996c93 installed in a docker container.
There are three different ways to restart Z2M:

-  Using 'restart'  from the UI in Settings --> Tools --> Restart ZigBee2MQTT
-  By adding `restart: unless-stopped` to the docker compose (or docker run)
-  By issuing a docker restart command from CLI

All of the above methods result consistently in the `database.db` file being wiped empty - hence all devices configs are lost!  So in effect, restart is destructive!  This cannot be by design. There must be some config mistake I have made? Please help.

Having said that, there is a fourth way to "restart" the container, and that is to use `docker stop`, then `docker start`. This does not kill the `database.db` file, but it's not very useful as it is completely manual. (of course `docker run` also works).

**Comment by DubhAd** [comment]
What does your compose file/run command look like?

What are you running Zigbee2MQTT on (eg _Debian Bookworm_) and what version of Docker? Also, are you running a normal or rootless Docker install?

**Reply by oywino** [reply]
Here's my compose file:

```
version: '3'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    restart: "no"
    network_mode: host
    ports:
      - 9080:8080
    environment:
      TZ: Europe/Oslo
    volumes:
      - /share/Public/Z2M:/app/data
```
I'm running it on a QNAP NAS which has a customized Linux OS.
Docker version 20.10.22-qnap7, build 57ed8b8
My Docker installation is part of what QNAP calls "Container Station Version 3.0.5.623"
I have about 20 other container based systems installed on a number of different QNAP NAS servers, including Mosquitto MQTT and I have never had any issues with any of them.
