### DISCUSSION TITLE
JY-GZ-01AQ aqara smoke detector

### DISCUSSION THREAD

**Discussion by Yakie996** [Koenkk/zigbee2mqtt#20537] [Devices]
in the settings of HA the buzzer and selftest are in a drop down menu.
![Screenshot_20240103_160253_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/19747119/eee0b009-1a23-4ab2-aa8b-31c6d9980859)

would it be possible to change it to a switch and button as in ZHA?
![Screenshot 2023-10-01 175237](https://github.com/Koenkk/zigbee2mqtt/assets/19747119/9606d93a-867d-41c4-a1ca-a33df5ac8de5)

**Comment by BetaHydri** [comment]
### Sample [Aqara JY-GZ-01AQ](https://www.zigbee2mqtt.io/devices/JY-GZ-01AQ.html#aqara-jy-gz-01aq) OpenHAB MQTT Channel configuration:

```
UID: mqtt:topic:mosquitto:7a6a13c653
label: Rauchmelder1AQThing
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: offline
  payloadAvailable: online
  transformationPattern: JSONPATH:$.state
  availabilityTopic: zigbee2mqtt/Rauchmelder1AQ/availability
bridgeUID: mqtt:broker:mosquitto
location: Kinderzimmer
channels:
  - id: Rauchmelder1AQ_Voltage
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Spannung
    description: Voltage of the battery in millivolts. Value can be found in the
      published state on the voltage property.  The unit of this value is mV
    configuration:
      unit: mV
      qos: 1
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ/voltage
  - id: Rauchmelder1AQ_linkquality
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Signal
    description: Link quality (signal strength). Value can be found in the published
      state on the linkquality property.
    configuration:
      min: 0
      qos: 0
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.linkquality
      max: 255
  - id: Rauchmelder1AQ_smoke_density
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Rauchdichte
    description: Value of smoke concentration. Value can be found in the published
      state on the smoke_density property.
    configuration:
      qos: 1
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.smoke_density
  - id: Rauchmelder1AQ_smoke_density_dbm
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Rauchdichte dB/m
    description: Value of smoke concentration in dB/m. Value can be found in the
      published state on the smoke_density_dbm property.
    configuration:
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.smoke_density_dbm
  - id: Rauchmelder1AQ_smoke
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Rauch
    description: Indicates whether the device detected smoke. Value can be found in
      the published state on the smoke property.
    configuration:
      qos: 0
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.smoke
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_buzzer_manual_alarm
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Alarm manuell ausgelöst
    description: It's not possible to write (/set) this value. If value equals true
      buzzer manual alarm is ON, if false OFF.
    configuration:
      qos: 1
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.buzzer_manual_alarm
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_buzzer_manual_mute
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Alarm manuell stummschalten
    description: "Buzzer muted (manually). Value can be found in the published state
      on the buzzer_manual_mute property. "
    configuration:
      qos: 0
      formatBeforePublish: "%s"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.buzzer_manual_alarm
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_linkage_alarm
    channelTypeUID: mqtt:switch
    label: "Rauchmelder1AQ Link Alarm "
    description: When this option is enabled and a smoke alarm has occurred, then
      "linkage_alarm_state"=true, and when the smoke alarm has ended or the
      buzzer has been manually muted, then "linkage_alarm_state"=false.
    configuration:
      postCommand: true
      qos: 1
      formatBeforePublish: "%s"
      commandTopic: zigbee2mqtt/Rauchmelder1AQ/set/linkage_alarm
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.linkage_alarm
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_heartbeat_indicator
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Status Blinken
    description: When this option is enabled then in the normal monitoring state,
      the green indicator light flashes every 60 seconds. Value can be found in
      the published state on the heartbeat_indicator property.
    configuration:
      postCommand: true
      qos: 1
      formatBeforePublish: "%s"
      commandTopic: zigbee2mqtt/Rauchmelder1AQ/set/heartbeat_indicator
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.heartbeat_indicator
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_Battery
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Batterie Status
    description: Remaining battery in %, can take up to 24 hours before reported.
      Value can be found in the published state on the battery property.
    configuration:
      unit: "%"
      min: 0
      qos: 1
      formatBeforePublish: "%d"
      max: 100
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.battery
  - id: Rauchmelder1AQ_linkage_alarm_state
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Link Alarm Status
    description: "When linkage_alarm is triggered. Value can be found in the
      published state on the linkage_alarm_state property. "
    configuration:
      qos: 1
      formatBeforePublish: "%s"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.linkage_alarm_state
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_buzzer
    channelTypeUID: mqtt:string
    label: Rauchmelder1AQ Alarm manuell auslösen
    description: The buzzer can be muted and alarmed manually. During a smoke alarm,
      the buzzer can be manually muted for 80 seconds ("mute") and unmuted
      ("alarm"). The buzzer cannot be pre-muted, as this function only works
      during a smoke alarm. During the absence of a smoke alarm, the buzzer can
      be manually alarmed ("alarm") and disalarmed ("mute"), but for this
      "linkage_alarm" option must be enabled.
    configuration:
      commandTopic: zigbee2mqtt/Rauchmelder1AQ/set/buzzer
      allowedStates: mute,alarm
      postCommand: true
      qos: 1
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.buzzer
  - id: Rauchmelder1AQ_Selftest
    channelTypeUID: mqtt:string
    label: Rauchmelder1AQ Selbstest
    description: Starts the self-test process (checking the indicator light and
      buzzer work properly). Value will not be published in the state.
    configuration:
      allowedStates: selftest
      commandTopic: zigbee2mqtt/Rauchmelder1AQ/set/selftest
      postCommand: true
      qos: 1
  - id: Rauchmelder1AQ_test
    channelTypeUID: mqtt:switch
    label: Rauchmelder1AQ Selbsttest Status
    description: Self-test in progress. Value can be found in the published state on
      the test property.
    configuration:
      qos: 0
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.test
      off: "false"
      on: "true"
  - id: Rauchmelder1AQ_power_outage_count
    channelTypeUID: mqtt:number
    label: Rauchmelder1AQ Anzahl Stromausfälle
    description: "Number of power outages. Value can be found in the published state
      on the power_outage_count property. "
    configuration:
      qos: 0
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/Rauchmelder1AQ
      transformationPattern: JSONPATH:$.power_outage_count
```
