### DISCUSSION TITLE
Z2M frontend won't load when using Docker [Solved]

### DISCUSSION THREAD

**Discussion by techsurrusr** [Koenkk/zigbee2mqtt#20800] [General]
Trying to get z2m up and running in a container and just don't have any luck with getting the frontend to show. I've recommended settings nad been playing around for a while but can't get it to run. Similar discussion have suggested to add the parameter `frontend: true` which have done but still no luck..

Here is the ./data/configuration.yaml:

```
homeassistant: true
  discovery_topic: zigbeeauto

frontend: true
  port: 8090
  host: 0.0.0.0

permit_join: true

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.23

serial:
  port: /dev/ttyACM0
  adapter: ezsp

advanced:
  network_key: GENERATE

advanced:
  log_level: error

```
and this the docker-compose.yml:

```
version: 3.8

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8090:8090
    environment:
      - TZ=Europe/Stockholm
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230221093826-if00:/dev/ttyACM0
```
