### DISCUSSION TITLE
Sinopé TH1300ZB appears to act as if unoccupied is not set for thermostat_occupancy after some time

### DISCUSSION THREAD

**Discussion by neel-m** [Koenkk/zigbee2mqtt#20935] [Devices]
I appreciate the work that went into Z2M and am generally liking it.  It is not what I would call easy to set up, but once set up, it does seem to work well.

I recently configured a TH1300ZB and added it to my Home Assistant instance.  Since it doesn't have its own scheduler I needed to add something for it to HA.  After considering a few options I noticed that the TH1300ZB (or at least when used with Z2M) supports occupied and unoccupied.  This seemed great, since it allows me to use my presence sensor to say occupied and unoccupied.  I can then control the unoccupied temperature at different times of the day to make the floor warm when needed but cool down when not in use.

Looking at the power usage, I could see that my first attempt was not working as I expected.  When I looked at the occupancy sensor, it matched my expectations (unoccupied when it should have been).  But still the floor was heating when it should not have been.  It was as if the thermostat was using the occupied set point.  Looking at pi_heating_demand confirmed that sure enough it was not respecting the non-occupied set point (and using the occupied one).

Since there is a timeout for outdoor_temperature, I wondered if perhaps there was the same thing for thermostat_occupancy.  I created an automation in HA that resets thermostat_occupancy to unoccupied every 10 minutes.  This worked, but every hour the floor still came on.  I then changed the automation to run every 1 min.  Again at a little past the hour (seconds past the time the automation that sets the outdoor temperature) the floor started heating.  The automation that sets thermostat_occupancy ran 30+ seconds later and the floor turned off.  So, I have a workaround.  Not sure if this is a Z2M issue or a TH1300ZB issue or something else.

I also notice that the voltage it reports is always 120V (I have an energy meter and know the number to be different by a volt or more) and power_apparent is rarely correct.  It was always stuck at 0, but is now reporting 984 constantly (and the floor is off, so it is should be saying 0).

I saw a few discussions on the ZB1300ZB, so I suspect there are other users.  Anyone else noticed something similar?

**Comment by neel-m** [comment]
Well, I have more data and it appears to be an issue with the TH1300ZB firmware.  I increased the logging on the underlying library to see what was happening at the Zigbee level.  There was nothing unusual (no real activity) around the time the TH1300ZB decides that it needs to turn on the heater.  I can now see that it happens every ~3606 seconds.  So, I added a new automation:

```yaml
alias: Kick Sinope
description: "Remind it that it should be in unoccupied mode, because it seems to have forgotten"
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.sinope_pi_heating_demand
    for:
      hours: 0
      minutes: 0
      seconds: 2
    above: 90
condition:
  - condition: device
    device_id: e61a8edb3abd68cacbfd9de928199ff2
    domain: select
    entity_id: 4a791e6a5d0ea2ea758b0a6ec45054d3
    type: selected_option
    option: unoccupied
    for:
      hours: 0
      minutes: 1
      seconds: 0
action:
  - device_id: e61a8edb3abd68cacbfd9de928199ff2
    domain: select
    entity_id: 4a791e6a5d0ea2ea758b0a6ec45054d3
    type: select_option
    option: unoccupied

```
This waits for the thermostat to say it is heating and if it is set for unoccupied it commands the thermostat to go back to unoccupied.  Note that the thermostat never said its state had changed.  Perhaps it is only a little bit confused.  Confused enough to forget which setpoint to use, but not enough to know that it has decided to use the other setpoint.

I will probably drop the trigger time down to 1 second, but I am not sure I want to make it zero.  Either way this is going to cause more cycles on the relay, which will wear it out sooner.  So, I don't think this one will last the 17+ years my previous thermostat lasted.
