### DISCUSSION TITLE
Z2M group remembers old state?

### DISCUSSION THREAD

**Discussion by fbloemhof** [Koenkk/zigbee2mqtt#21081] [General]
When I call light.turn_on from HA with a certain brightness_pct and kelvin to an in Z2M configured light group, the group first turns on in the previous state and then transitions to the requested state. When I do this on an individual light from this group, it doesn't. How can I change this behavior?

The group is configured via the Z2M frontend and has no extra properties configured.

My Z2M configuration.yaml is:

```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: xxx
  password: xxx
  server: mqtt://core-mosquitto:1883
  force_disable_retain: false
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_22_98_98_50-if00-port0
advanced:
  log_level: info
  pan_id: xxx
  channel: 11
  network_key:
xxx
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  elapsed: false
  cache_state_send_on_startup: false
  legacy_api: false
  cache_state: true
  cache_state_persistent: false
  report: false
device_options:
  disabled: false
  homeassistant: true
  optimistic: true
  filtered_cache:
    - brightness
    - rgb_color
    - hs_color
    - xy_color
    - color_temp_kelvin
    - color_temp
    - color
    - color_mode
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false

```

**Comment by fbloemhof** [comment]
I did some more extensive testing but I am still not sure what the cause of this behavior is. I created a script in HA to demonstrate the issue.

```
alias: _dev - Light transition demo
sequence:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: "{{ entity_id }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      kelvin: 6500
      brightness: 255
    target:
      entity_id: "{{ entity_id }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: "{{ entity_id }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      kelvin: 2000
      brightness: 128
    target:
      entity_id: "{{ entity_id }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: "{{ entity_id }}"
mode: single
fields:
  entity_id:
    selector:
      entity:
        multiple: true
    name: entity_id
    description: The entity_id of the light (group) to repro the issue on
    required: true
```

If you call this with a Z2M light group as entity_id, it is probably the best visible. But also on single lights I see the same behavior (but a little less).

Also ported the script to directly MQTT commands, behavior persists:

```
alias: _dev - Light transition demo MQTT
sequence:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      retain: false
      topic: zigbee2mqtt/{{ z2m_name }}/set
      payload_template: "{ \"state\": \"OFF\" }"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      retain: false
      topic: zigbee2mqtt/{{ z2m_name }}/set
      payload_template: "{ \"state\": \"ON\", \"brightness\": 254, \"color_temp\": 291 }"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      retain: false
      topic: zigbee2mqtt/{{ z2m_name }}/set
      payload_template: "{ \"state\": \"OFF\" }"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      retain: false
      topic: zigbee2mqtt/{{ z2m_name }}/set
      payload_template: "{ \"state\": \"ON\", \"brightness\": 128, \"color_temp\": 454 }"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      retain: false
      topic: zigbee2mqtt/{{ z2m_name }}/set
      payload_template: "{ \"state\": \"OFF\" }"
mode: single
fields:
  z2m_name:
    name: Z2M name
    description: The Zigbee 2 MQTT name of the light (group) to repro the issue on
    required: true
```
