### DISCUSSION TITLE
Seeking for relay that support "On With Timed Off" command

### DISCUSSION THREAD

**Discussion by g-chevalier** [Koenkk/zigbee2mqtt#21395] [Devices]
Hi,

I'm desperately searching for a smart switch module that works with "On With Timed Off" command.
This is the command 0x42 of the OnOff Cluster.

I would like to install such switch in my home and benefit of this capacity to automatically switch off after a given delay, so that in case of Zigbee network issue or break down I'm sure that lamps connected to those switches are turned off.

I tried several switches without success up to now.

I'm sure that I'm sending the correct command as I could make it working with an IKEA TRADFRI Bulb (zigbee model LED1842G3).

Each time I test using two different methods:

- MQTT (zigbee2mqtt/friendly_name/set with Payload = {"state": "on", "on_time":5, "off_wait_time":0})
- And direct command in the device Dev Console (Cluster 6, Command 0x42, payload = {"ctrlbits":0,"offwaittime":0,"ontime":5})

The devices I tested are:

- Tuya TS0001
- Tuya TS0002
- TuYa QS-Zigbee-SEC02-U
- Moes MS-104BZ
- Avatto ZWSM16-2-Zigbee
- Not a switch module, but tested and not working: Xiaomi ZNCZ02LM

Anyone could point me to a 2 Gang switch module that support this command?
Someone having some experience on updating firmware on above devices?

**Comment by chris-1243** [comment]
I just had a try with an Ubisys S2 (two outputs) and the "on time" works.

Could you try via MQTT but with this payload : {"state" : "ON", "on_time": 5}. According to documentation :

> Support depend on the switch firmware. Some devices might require both on_time and off_wait_time to work

**Comment by g-chevalier** [comment]
Thank you for your answer.

Unfortunately, this switch costs 8 to 10 times the prices of others common switches. It's a pity to pay so much for such a device just because the software of the others is bad. But it is probably a far better quality product, with also power consumption measurement (which I don't need).

For the MQTT payload, with the IKEA bulb, I also have to specify only "on_time", if I include "offwaittime" it doesn't work. I did not write this detail on the initial post to simplify.

**Reply by chris-1243** [reply]
Well, I do agree those switch are quite expensive. The way you may configure them is just incredible...

I remember I have a [Sunricher SR-ZG9101SAC-HP-SWITCH-2CH](https://www.zigbee2mqtt.io/devices/SR-ZG9101SAC-HP-SWITCH-2CH.html) which I do not use anymore. The "on time" command works on both channel. There is one thing which has to be reported, when sending the command to the second channel (l2), Z2M throws an error but the command works...

@Koenkk Would it be possible to check why I get this error when sending this command:
```
{"state_l2": "ON", "on_time": 5}

Zigbee2MQTT:error 2024-02-15 10:25:14: Publish 'set' 'on_time' to '0x943469fffef2f700' failed: 'Error: 'null' not allowed, choose between: toggle,off,on'
``` 
When sending exactly the same command on l1 endpoint, there is no error message. Only on l2 endpoint and the command is well executed by zigbee2mqtt.

**Comment by g-chevalier** [comment]
The Sunricher SR-ZG9101SAC switch seems to be a good candidate. I'll wait a little bit more in case there are other answers in this discussion.
I'm also wondering if I'll investigate into programming my own firmware into an existing switch…

**Comment by AkLim94** [comment]
The SB-SW02 should support Timed_Off
https://www.zigbee2mqtt.io/devices/ZB-SW02.html#ewelink-zb-sw02
but I don't know how to test it....

**Reply by g-chevalier** [reply]
Hi @AkLim94 

Thank you for this suggestion. "Should support" is a bit vague.
However, this relay will not suit my needs as it doesn't have inputs for local command with existent wall switch. At the best, it has HW buttons, but I guess they use low voltage and cannot be controlled by mains voltage.

**Reply by Edmondena** [reply]
Dear HA Community,
heartly thank you all for starting this topic which becomes more and more important for me! After about three days of research for me as a newbee to HA, this research provided only few solution and could have been likely a killer for my idea of controlling an IR heating by ZHA in a house, where no reliable monitoring is present. Without this ensuring a IR Heating "switch off" command as is 100% reliably executed is a safety must have for me. Not only that the cost of a long time running heating is a real problem, but the fire hazards are the highly critical risks that could be simply initiated by a high probable single point of failure in a long chain of a high complex embedded systems and high unreliability of the zigbee/wifi controlled home automation system. 

I write you because I feel to be maybe very close to a solution and maybe provide you with more tested HW, Relais & Plugs that could fulfill our requirements.

This LEDVANCE Smart+ Plug EU I have successfully tested to provide this required safety feature "on_with_timed_off"
https://www.amazon.de/dp/B0D9M8M99C?ref=ppx_yo2ov_dt_b_fed_asin_title
Approval (similar like): ZHA->Smart+PlugEU->"3Dots"->Manage Device->...OnOffCluster->Commands->Select "on_with_timed_off"->Fill in both!: ->on_time:10 + off_wait_time "0"->Write Command->Et Voilà: The Switch goes On and 10s later back to Off (by HW countdown. 
Compare (same as above): https://community.home-assistant.io/t/getting-a-tuya-ts0001-relay-to-be-in-inching-or-auto-off-mode/753675/3

My so far my partly successful approaches are as follows:
>>Step By Step and as far as I remember....
0. This switch/plug is available today at cost of far below 20€ if you buy at least 4 pcs.
1. Write this blueprint (Problem: zha.send is not working) and put this blueprint in configuration/.homeassistant/configuration.yaml/blueprints/automation/myprints/ledvance_plug_on_with_timed_off_5.yaml
2. Don't forget zu adapt the script to fit to your exact "ieee id" at the end (not sure if correct?!)
3. Execute the below blueprint to import it as automation
4. Add your "LEDVANCE Smart+ PLug EU", change name e.g."....plug_#1"
5. Use the blueprinted automation for my TUYA TS0041 switchbutton and add the action for "LEDVANCE Smart+ Plug EU" with linked 'Switch with Timed Off Plug No1' automation
6. Maybe restart your Home Assistant
7. Try to fire your script directly from your configuration->automation & scenes folder to 1st rule out the problems come from the button automation

Please give us feedback because like me I can't accept to rely on HA<->Zigbee Network in disturbed city environments to safety switch my IR heating (and may others) back to off. Only the Plug HW is an acceptable safety instance if I'm not at home and rely that unintended "switch on" or failed "switch off" cause critical, cost intensive or even catastrophic fire hazards.

Thank you all for your great support and for hopefully helping me for this urgent, unsolved HA problem! This is driven for me by
my understanding that the safe state "Off" for any HA automated high power device attached to any smart plug must be provided by the Plug/Relais HW itself and neither zigbee, nor any other smart hub will ever be qualified to do this safety job.

I'll buy some more Relais/Plugs and start collecting it for a good/bad list as follows.....

Thank you again for your good help on highlighting this topic or point us to where we can understand to solve it!

Best regards, thanks in advance and happy public holidays! 

My blueprint draft, not succeeded so far but maybe a good starting point for more experienced users?
```
blueprint:
  name: Switch with Timed Off
  description: Turns on a switch for a specified time, then turns it off.
  domain: automation
  input:
    switch_entity:
      name: Switch Entity
      description: The switch to turn on.
      selector:
        entity:
          domain: switch
    on_time:
      name: On Time
      description: Time in seconds to keep the switch on.
      default: 10
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    off_wait_time:
      name: Off Wait Time
      description: Time in seconds to wait before turning off.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    
trigger:
  - platform: state
    entity_id: !input switch_entity
    to: 'on'

action:
  - service: zha.send
    data:
      ieee: "{{ state_attr(states('!input switch_entity'), 'PLUG EU EM T') }}"
      command: "on_with_timed_off"
      args:
        - "{{ on_time }}"  # Correctly refer to input
        - "{{ off_wait_time }}"  # Correctly refer to input

```
