### DISCUSSION TITLE
Pairing problem

### DISCUSSION THREAD

**Discussion by alexblav** [Koenkk/zigbee2mqtt#21627] [Devices]
Hello,

I'm starting with Z2M on HA. For the moment, despite my tests, I can't integrate my peripherals. My key flashes but no detection

ZIGATE key on RPI4
Would you have an idea?

Thanks

Log:
```
[07:11:34] INFO: Preparing to start...
[07:11:35] INFO: Socat not enabled
[07:11:39] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2024-03-01 07:11:51: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2024-03-01 07:11:51: Logging to console and directory: '/config/zigbee2mqtt/log/2024-03-01.07-11-51' filename: log.txt
Zigbee2MQTT:debug 2024-03-01 07:11:51: Removing old log directory '/config/zigbee2mqtt/log/2024-02-25.17-23-13'
Zigbee2MQTT:info  2024-03-01 07:11:52: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-03-01 07:11:52: Starting zigbee-herdsman (0.33.8)
Zigbee2MQTT:debug 2024-03-01 07:11:52: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[196,166,49,116,184,150,31,85],"networkKey":"HIDDEN","panID":33513},"serialPort":{"adapter":"zigate","path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:info  2024-03-01 07:11:52: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2024-03-01 07:11:52: Coordinator firmware version: '{"meta":{"maintrel":"2303","majorrel":"0","minorrel":"4","product":0,"revision":"2303","transportrev":0},"type":"zigate"}'
Zigbee2MQTT:debug 2024-03-01 07:11:52: Zigbee network parameters: {"channel":11,"extendedPanID":"0xc4a63174b8961f55","panID":8113}
Zigbee2MQTT:info  2024-03-01 07:11:52: Currently 0 devices are joined:
Zigbee2MQTT:info  2024-03-01 07:11:52: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2024-03-01 07:11:52: Connecting to MQTT server at mqtt://core-mosquitto
Zigbee2MQTT:debug 2024-03-01 07:11:52: Using MQTT login with username: mqtt
Zigbee2MQTT:info  2024-03-01 07:11:53: Connected to MQTT server
Zigbee2MQTT:info  2024-03-01 07:11:53: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:debug 2024-03-01 07:11:53: Received MQTT message on 'zigbee2mqtt/bridge/info' with data '{"commit":"unknown","config":{"advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":
```

Config:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: xxxxxxxxxxxx
serial:
  port: /dev/ttyUSB0
  adapter: zigate
```
