### DISCUSSION TITLE
TuYa PJ-ZGD01 and push button

### DISCUSSION THREAD

**Discussion by tdm-fr** [Koenkk/zigbee2mqtt#21897] [Devices]
Hello,

I've got 3 TuYa PJ-ZGD01 that I have integrated in HA thanks to Z2M.
It's working fine for the sensor letting me know if the door is closed or not.
It's also working for the trigger to open the door, but not the expected way. The trigger is a classic switch. I have to click on it to turn it to "true", then click on it again to turn it to "false". At this point the door will move.
I'd expect a push button, to click on it once and then the door will move.

This is what I have : 
<img src="https://github.com/Koenkk/zigbee2mqtt/assets/3950014/91d76065-66d3-4ac9-9993-9dee8e5c8711" width="600" />

From what I read, a push button in Z2M is a switch with a "momentary" parameter, like in this configuration : 
<img src="https://github.com/Koenkk/zigbee2mqtt/assets/3950014/4f655419-326b-49fa-97d0-d0adf8ddf731" width="600" />

How can I achieve this change ?

Franck

**Comment by fabianoarruda** [comment]
I have the same question.

**Comment by gonzasmts** [comment]
Does any one found a solution for this? I have the same device and the same problem..

**Comment by tdm-fr** [comment]
Yes.

I have created automations allowing me to open/close my garage door depending on the state of the door sensor.
I took into account that I have to switch on then switch off the exposed functionnality to activate the door.

For the user the garage door is controlled through cards
![image](https://github.com/Koenkk/zigbee2mqtt/assets/3950014/139ac68a-3f97-4e5a-a8df-2bee87673f54)

**Reply by fabianoarruda** [reply]
Can you share more details on how you did it, please?

**Reply by tdm-fr** [reply]
Yes sure !

Just some information first :
- My automations may seem complicated but it's because I have 3 TuYa PJ-ZGD01, so I created a generic code working with triggers to catch which door is triggered with the user card.
- To be able to do so, I respected a certain way of naming my modules and there exposed functionnalities.
   for example "garage_garage_door_left" have :
      - switch.garage_garage_door_left_trigger
      - binary_sensor.garage_garage_door_left_garage_door_contact
- I correct myself regarding to have to switch the trigger on/off to have the door moving. I did that in the beggining but found a better way after.
The switch of the module, so in the above example "switch.garage_garage_door_left_trigger" allow to make the door move, but it depends on the state of the sensor. So you have to open the switch if the door is closed, and close the switch if the door is opened. I don't know why but it works like this.
- We have to compose with one information only : the door sensor.
   - If the sensor is closed then the door is closed, and by deduction not moving.
   - If the sensor is opened then the door is opened and could be :
       - stopped and opened somewhere a centimeter of the ground or fully opened
       - moving, in the opening direction
       - moving, in the closing direction
- That's why I have 2 automations 
    - close the door : not knowing the state of the door, I will make it move. if after a certain amount of time the door sensor doesn't show me that the door is closed, I make the door move again.
    - open/move/stop the door : a single action of swipping the switch.
- I have 2 helpers for each module :
    - garage_garage_door_left_close ; garage_garage_door_right_close ; portal_garage_door_close
    - garage_garage_door_left_stop_go ; garage_garage_door_right_stop_go ; portal_garage_door_stop_go

``` yaml
alias: Garage Door - Move
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.garage_garage_door_right_stop_go
    id: trig_garage_door_right_stop_go
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.garage_garage_door_left_stop_go
    id: trig_garage_door_left_stop_go
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.portal_garage_door_stop_go
    id: trig_portal_door_stop_go
    from: "off"
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - trig_garage_door_right_stop_go
              - trig_garage_door_left_stop_go
              - trig_portal_door_stop_go
        sequence:
          - alias: >-
              If the automation is launched by a human (so not another automation) ;
              then deactivate the helper close
            if:
              - condition: template
                value_template: |
                  {{trigger.to_state.context.user_id is not none}}
            then:
              - service: input_boolean.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: "{{trigger.entity_id|replace('_stop_go','')}}_close"
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{is_state('binary_sensor.'~trigger.entity_id|replace('input_boolean.','')|replace('_stop_go','')~'_garage_door_contact','off')}}
                sequence:
                  - service: switch.turn_on
                    metadata: {}
                    data: {}
                    target:
                      entity_id: >-
                        switch.{{trigger.entity_id|replace('input_boolean.','')|replace('_stop_go','')}}_trigger
              - conditions:
                  - condition: template
                    value_template: >-
                      {{is_state('binary_sensor.'~trigger.entity_id|replace('input_boolean.','')|replace('_stop_go','')~'_garage_door_contact','on')}}
                sequence:
                  - service: switch.turn_off
                    metadata: {}
                    data: {}
                    target:
                      entity_id: >-
                        switch.{{trigger.entity_id|replace('input_boolean.','')|replace('_stop_go','')}}_trigger
            alias: >-
              Check the door sensor ; if the sensor is closed, then open the switch ;
              if the sensor is opened then close the switch
          - service: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: "{{trigger.entity_id}}"
            alias: set to off the helper that launched the automation
mode: single
```

``` yaml
alias: Garage Door - Close
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.garage_garage_door_left_close
    id: trig_garage_door_left_close
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.garage_garage_door_right_close
    id: trig_garage_door_right_close
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.portal_garage_door_close
    id: trig_portal_door_close
    from: "off"
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - trig_garage_door_left_close
              - trig_garage_door_right_close
              - trig_portal_door_close
        sequence:
          - repeat:
              sequence:
                - service: input_boolean.turn_on
                  target:
                    entity_id: "{{trigger.entity_id|replace('_close','')}}_stop_go"
                  data: {}
                  alias: >-
                    set the stop_go helper to on to launch
                    the automation to activate the door
                    automation pour activer la porte
                - wait_for_trigger:
                    - platform: template
                      value_template: >-
                        {{is_state('binary_sensor.'~trigger.entity_id|replace('input_boolean.','')|replace('_close','')~'_garage_door_contact','off')}}
                  timeout:
                    hours: 0
                    minutes: 0
                    seconds: 22
                    milliseconds: 0
                  alias: >-
                    Wait 22s if the sensor is closed. 22s because in the worst case the door
                    is just slightly opened and will take this amount of time to fully open and stop.
                - if:
                    - condition: template
                      value_template: >-
                        {{is_state('binary_sensor.'~trigger.entity_id|replace('input_boolean.','')|replace('_close','')~'_garage_door_contact','off')}}
                  then:
                    - service: input_boolean.turn_off
                      metadata: {}
                      data: {}
                      target:
                        entity_id: "{{trigger.entity_id}}"
                  alias: >-
                    If the sensor is closed then se the helper_close to off
                    to stop the automation
              until:
                - condition: template
                  value_template: >-
                    {{is_state('binary_sensor.'~trigger.entity_id|replace('input_boolean.','')|replace('_close','')~'_garage_door_contact','off')}}
                  alias: Until the door sensor is not closed
mode: parallel
max: 3
```

in configuration.yaml
``` yaml
cover:
  - platform: template
    covers:

      portal_door:
        unique_id: xxx
        friendly_name: "Portal Door"
        value_template: "{{ is_state('binary_sensor.portal_garage_door_garage_door_contact', 'on') }}"
        open_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.portal_garage_door_stop_go
        stop_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.portal_garage_door_stop_go
        close_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.portal_garage_door_close
        icon_template: >-
          {% if is_state('binary_sensor.portal_garage_door_garage_door_contact', 'off') %}
            mdi:garage
          {% elif is_state('input_boolean.portal_garage_door_close', 'on') %}
            mdi:transfer-down          
          {% elif is_state('binary_sensor.portal_garage_door_garage_door_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage-alert
          {% endif %}
    
      garage_door_left:
        unique_id: yyy
        friendly_name: "Garage Door Left"
        value_template: "{{ is_state('binary_sensor.garage_garage_door_left_garage_door_contact', 'on') }}"
        open_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_left_stop_go
        stop_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_left_stop_go
        close_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_left_close
        icon_template: >-
          {% if is_state('binary_sensor.garage_garage_door_left_garage_door_contact', 'off') %}
            mdi:garage
          {% elif is_state('input_boolean.garage_garage_door_left_close', 'on') %}
            mdi:transfer-down          
          {% elif is_state('binary_sensor.garage_garage_door_left_garage_door_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage-alert
          {% endif %}
          
      garage_door_right:
        unique_id: zzz
        friendly_name: "Garage Door Right"
        value_template: "{{ is_state('binary_sensor.garage_garage_door_right_garage_door_contact', 'on') }}"
        open_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_right_stop_go
        stop_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_right_stop_go
        close_cover:
          service: input_boolean.turn_on
          entity_id: input_boolean.garage_garage_door_right_close
        icon_template: >-
          {% if is_state('binary_sensor.garage_garage_door_right_garage_door_contact', 'off') %}
            mdi:garage
          {% elif is_state('input_boolean.garage_garage_door_right_close', 'on') %}
            mdi:transfer-down          
          {% elif is_state('binary_sensor.garage_garage_door_right_garage_door_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage-alert
          {% endif %}
```

On the dashboard
``` yaml
square: false
type: grid
cards:
  - type: custom:mushroom-cover-card
    entity: cover.portal_door
    name: Portail
    show_buttons_control: true
    secondary_info: last-updated
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-cover-card
        entity: cover.garage_door_left
        name: Garage gauche
        show_buttons_control: true
        secondary_info: last-updated
      - type: custom:mushroom-cover-card
        entity: cover.garage_door_right
        name: Garage droit
        show_buttons_control: true
        secondary_info: last-updated
columns: 1
```

Example of what to expect on the dashboard
![image](https://github.com/Koenkk/zigbee2mqtt/assets/3950014/3e196091-68ce-4922-9e46-1f3e2685ea58)

**Reply by fabianoarruda** [reply]
Thank you @tdm-fr. Very useful info, I'll test this. 

A quick tip regarding github markdown: for multi-line code snippets, you can use 3 backticks followed by the language name, like this: ` ``` yaml ` at the beginning, and then ` ``` ` at the end. This will give a nice formatting :)

**Comment by tdm-fr** [comment]
Thanks for the tip on how to format the code on github, much better now !

I also took the time to translate the comments in english, it will be way more helpful than the french comments 😅
And doing this translation I noticed that I forgot to talk about the helpers, so I added a last section in the information part where I list them all.

**Comment by muller-h** [comment]
entiendo que el PJ-ZGD01 funciona dando ventajas de temporización yo requiero que el al activar el pulso la puerta se abra y trascurrido el desplazamiento y el sensor marque que la puerta se ha cerrado el botón regrese a estar listo para nuevamente abrir la puerta sin tener que pulsarlo dos veces he intentado con configuration.yaml creando un interruptor virtua 

input_boolean:
  control_puerta:
    name: Control Puerta
    icon: mdi:garage

para luego crear un Automatización.

alias: Control Puerta - Modo Timbre
description: Activa el relé de contacto seco solo si la puerta está cerrada
trigger:
  - platform: state
    entity_id: input_boolean.control_puerta
    to: "off"
condition:
  - condition: state
    entity_id: binary_sensor.porton_automatico_garage_door_contact
    state: "on"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.porton_automatico_trigger
  - delay: "00:00:03"
  - service: switch.turn_off
    target:
      entity_id: switch.porton_automatico_trigger
  - delay: "00:00:01"
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.control_puerta
mode: single


sin lograrlo si alguien puede ayudar lo agradezco.

**Comment by attila-lendvai** [comment]
any simpler solutions to this? i don't want to add such an enormouns complexity instead of simply changing a switch into a momentary one... there must be a simpler solution!

unfortunately the PJ-ZGD01 related issues explaining this behavior were all closed without a fix.

my garage door switch in HA must be pressed twice...

**Comment by attila-lendvai** [comment]
i have zero knowledge of the internals, but i looked at the code.

as a comparison i looked at WHD02, which supposed to have some settings to change the button's behavior (as per https://github.com/Koenkk/zigbee2mqtt/discussions/12197).

```
        model: 'WHD02',
        vendor: 'TuYa',
        whiteLabel: [{vendor: 'TuYa', model: 'iHSW02'}, {vendor: 'Aubess', model: 'TMZ02'}],
        description: 'Wall switch module',
        extend: tuya.extend.switch({switchType: true}),
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint);
        },
```

```
        model: 'PJ-ZGD01',
        vendor: 'TuYa',
        description: 'Garage door opener',
        fromZigbee: [fz.matsee_garage_door_opener, fz.ignore_basic_report],
        toZigbee: [tz.matsee_garage_door_opener, tz.tuya_data_point_test],
        whiteLabel: [{vendor: 'MatSee Plus', model: 'PJ-ZGD01'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
        exposes: [exposes.binary('trigger', ea.STATE_SET, true, false).withDescription('Trigger the door movement'),
            exposes.binary('garage_door_contact', ea.STATE, true, false)],
```

i think the key difference is that the PJ-ZGD01 cannot simply do the `extend: tuya.extend.switch({switchType: true})` part because it's not just a simple switch. because of that it does not inherit the configuration to select the switch behavior, which would solve our problems.

maybe it's possible to use the extend and only list the `garage_door_contact` sensor in the `exposes:` array? 

i'm running z2m from a git checkout, so i tried to test this, but then i realized that i'm running a rather old version (1.36.0), so i've updated to the current latest (2.1.3) and the settings page became more complex, so i'll experiment with the new version before i delve into testing any change to the code.

**Comment by paulpeeters** [comment]
I added a simple automation that is triggered when the switch goes from off to on, waits some milliseconds and turns the switch to off again. Something like this (note that I use Zigbee2MQTT and the device was named garage_door):

```yaml
alias: Garage door - fix pushbutton
description: ""
triggers:
  - entity_id:
      - switch.garage_door_trigger
    from: "off"
    to: "on"
    trigger: state
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.garage_door_trigger
mode: single

```
