### DISCUSSION TITLE
"Error: Failure to connect" - SONOFF ZBDongle-E - RPi5

### DISCUSSION THREAD

**Discussion by KevinBalkoski** [Koenkk/zigbee2mqtt#21911] [Devices]
What happened?

I recently moved my HA from a Raspberry Pi4 to a Pi5 and I am now unable to get zigbee2mqtt to connect. Error log:
```
Zigbee2MQTT:error 2024-03-22 10:58:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-22 10:58:31: Failed to start zigbee
Zigbee2MQTT:error 2024-03-22 10:58:31: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-22 10:58:31: Exiting...
Zigbee2MQTT:error 2024-03-22 10:58:31: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:364:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:158:13)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```

From a fresh install on a new SD card, I got Home Assistant up and running. I loaded from a full backup file. Virtually everything is working aside from Z2M. It was initially setup mainly using this video: https://www.youtube.com/watch?v=4y_dDgo0i2g&t=203s

I have:

- Mosquito broker addon installed.
- Silabs Multiprotocol Addon installed
  - Points to the correct device `/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525164005-if00`
- The Z2M config:
```yaml
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-user
  password: somedumbpassword
serial:
  port: tcp://core-silabs-multiprotocol:9999
  adapter: ezsp
```
- I have a user in HA named `mqtt-user` with the password shown above
- ZHA should not be running

These symptoms look similar to this https://github.com/Koenkk/zigbee2mqtt/discussions/21593 but it looks like that was resolved from a typo in the user name (which isn't the case for me).

Zigbee2MQTT version:
1.35.3-1

Adapter firmware version
don't know

Adapter
SONOFF ZBDongle-E

Setup
Addon

Debug log
```
[10:57:58] INFO: Preparing to start...
[10:57:59] INFO: Socat not enabled
[10:57:59] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-03-22 10:58:01: Logging to console and directory: '/config/zigbee2mqtt/log/2024-03-22.10-58-01' filename: log.txt
Zigbee2MQTT:info  2024-03-22 10:58:01: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-03-22 10:58:01: Starting zigbee-herdsman (0.33.8)
Zigbee2MQTT:error 2024-03-22 10:58:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-22 10:58:31: Failed to start zigbee
Zigbee2MQTT:error 2024-03-22 10:58:31: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-22 10:58:31: Exiting...
Zigbee2MQTT:error 2024-03-22 10:58:31: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:364:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:158:13)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```
