### DISCUSSION TITLE
Invert (Aqara) binary sensor state

### DISCUSSION THREAD

**Discussion by sebastianlorenzen** [Koenkk/zigbee2mqtt#22056] [Devices]
I'm tryting to invert an Aqara door sensor to show open when it is closed and vice versa. (MCCGQ11LM)
I followed this: [](https://github.com/Koenkk/zigbee2mqtt/issues/5009) but cant get it work.
Other than in the above post I have everything in the configuration.yaml (Seems to be default)
This is the sensor definition:
``` '0x00158d0006f926d8':
    friendly_name: EG_WC_TK
    description: Door Contact EG WC
    payload_on: true
    payload_off: false
```
I have deleted the device under "Devices and Services" -> MQTT and restarted Zigbee2MQTT.
It was recreated, but still shows open when open.

Anything I have missed?

**Comment by sebastianlorenzen** [comment]
Even this is not working:
```
  '0x00158d0006f926d8':
    friendly_name: EG_WC_TK
    description: Door Contact EG WC
    homeassistant:
      contact:
        payload_on: true
        payload_off: false
```
Maybe I did something wrong with the spaces / indentiation?
