### DISCUSSION TITLE
Z2M not working in Docker any more, after big crash

### DISCUSSION THREAD

**Discussion by Dylantje** [Koenkk/zigbee2mqtt#22857] [General]
Hello, since yesterday after a crash with mqtt while pairing a lot of trouble...

 I have been running stable with docker domoticz and mqtt, influx and grafana for months. 
But since yesterday there has been a lot of misery.  

Whatever I try to get z2m in Docker running again with mqtt, it doesn't work.  I see the error, usb is wrong...

  With an error that the USB was not found:
[2024-05-31 19:09:35] info: z2m: Logging to console, file (filename: log.log)
[2024-05-31 19:09:35] info: z2m: Starting Zigbee2MQTT version 1.37.1 (commit #ea39d86)
[2024-05-31 19:09:35] info: z2m: Starting zigbee-herdsman (0.46.6)
[2024-05-31 19:09:35] error: zh:zstack:znp: Failed to determine if path is valid: 'Error: ENOENT: no such file or directory, lstat '/dev/ttyACM0''
[2024-05-31 19:09:36] info: zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen" :false}
[2024-05-31 19:09:36] error: z2m: Error while starting zigbee-herdsman
[2024-05-31 19:09:36] error: z2m: Failed to start zigbee
[2024-05-31 19:09:36] error: z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-05-31 19:09:36] error: z2m: Exiting...
[2024-05-31 19:09:36] error: z2m: Error: Error: No such file or directory, cannot open /dev/ttyACM0

And that's right because my USB is on USB 2: and not on ACM0.

Docker out all containers, images, etc. Even reinstalled Docker and turned all images back on, but couldn't get it to work right away.

It looks like there is a file or somewhere that holds that one old config. I cannot set the sonof dongel to usb2

My docker compose file: 
`services:
  zigbee2mqtt:
    container_name: zigbee2mqtt2
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8888:8888
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
      - /dev/ttyUSB2:/dev/ttyUSB2

What I've been working with for a long time.
Where I know for sure that the sonof zigbee stick is on USB2.
` ls -l /dev/serial/by-id
lrwxrwxrwx 1 root root 13 31 mei 19:46 usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0 -> ../../ttyUSB2

And I also have that in my compose file.

Is there a folder somewhere where I can throw away something from z2m so that I really have a clean start. Since installing and trying a few times, no log message appears in the OPT folder anymore. So it seems like there's still a lot wrong. And after a fresh install with docker, all the other images are running only z2m.......

So actually a big help... please.. windows noob here [ And a whole house running on Domoticz with 60 Mqtt device :-( ]

And a WAF who is very angry :-)

Edit:
Found dis strange volume:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5214969/cb7a755c-2020-43d8-aab6-353bc7b53b49)
Perhaps this something wrong?

Edit. Portainer says running:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5214969/9502339c-438c-45a6-964c-a5841a93dcd2)

Only no ip:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5214969/10d3e226-df2d-4db9-baa3-b2c01d0dcd23)
And no webui..

**Comment by chris-1243** [comment]
In your `docker-compose.yaml`, I would use this path:

```
devices:
 - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyUSB2
``` 
and in `configuration.yaml`, I would check 

```
serial:
  port: /dev/ttyUSB2
```

**Reply by Dylantje** [reply]
> serial:
>   port: /dev/ttyUSB2

Done, maar geeft nu een error::
validating /opt/z2m/docker-compose.yml: services.zigbee2mqtt Additional property serial is not allowed

**Reply by chris-1243** [reply]
This line has to be removed from your `docker-compose.yaml`. It is normal to get an error

**Comment by chris-1243** [comment]
There was a misunderstanding. To run your zigbee2mqtt container, you should have two separate files.
1. Your `docker-compose.yaml` ;
```
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt2
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
    # Frontend port
      - 8888:8888
    environment:
      - TZ=Europe/Berlin
    devices:
    # Make sure this matched your adapter location
      #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
      #- /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyUSB2
``` 

2. A specific file to run your zigbee2mqtt network `configuration.yaml` which should be outside your container. According to your first post, it should be in /data. Open and check this file. There should be a section called:
```
...
homeassistant:
  legacy_entity_attributes: true
  legacy_triggers: true
permit_join: false
mqtt:
  server: ip address and port of your mqtt server
  user: your user
  password: your password
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB2 (or sth else and it should match what you filled in docker-compose.yaml)
advanced:
  channel: xx
.....
```
