### DISCUSSION TITLE
[Needs feedback] Gladys Assistant integration

### DISCUSSION THREAD

**Discussion by Pierre-Gilles** [Koenkk/zigbee2mqtt#23186] [Show and tell]
Hi everyone! 

First, thanks for building Zigbee2mqtt, it's really an incredible software 🙌 

I'm the core maintainer of [Gladys Assistant](https://github.com/GladysAssistant/Gladys), an open-source smart home software.

We've recently worked to improve our Zigbee2mqtt integration, and users are now able to connect Gladys to an existing Zigbee2mqtt setup: 

![choose-zigbee-mode-8990adabf39a324a8cf8c4a7cce30e05](https://github.com/Koenkk/zigbee2mqtt/assets/7365207/32d8db4d-9e68-4a90-bba6-978a68159156)

If you have 2 minutes, would you mind trying our integration and tell us if you find any incompatibilities? You can start Gladys in parallel of any other software (Node-RED/HA/...), it's not an issue.

You can start a Gladys container in one line: 
```
docker run -d \
--log-driver json-file \
--log-opt max-size=10m \
--cgroupns=host \
--restart=always \
--privileged \
--network=host \
--name gladys \
-e NODE_ENV=production \
-e SERVER_PORT=80 \
-e TZ=Europe/Paris \
-e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/lib/gladysassistant:/var/lib/gladysassistant \
-v /dev:/dev \
-v /run/udev:/run/udev:ro \
gladysassistant/gladys:v4
```

Or with Docker-compose:

```
version: '3'

services:
  gladys:
    image: gladysassistant/gladys:v4
    container_name: gladys
    restart: always
    privileged: true
    network_mode: host
    cgroup: host
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/gladysassistant/gladys-production.db
      SERVER_PORT: 80
      TZ: Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/gladysassistant:/var/lib/gladysassistant
      - /dev:/dev
      - /run/udev:/run/udev:ro
```
