### DISCUSSION TITLE
Two or more instances of Z2M one machine?!

### DISCUSSION THREAD

**Discussion by M-ax-G** [Koenkk/zigbee2mqtt#23231] [General]
Looking for answers points often to HomeAssistant; however, I cannot apply these recommendations to my set-up as I do not run HASS.
I have installed one instance on a rPi4 which works nicely.

How can I install a second, third or more instances on the same machine, if possible, without docker or Proxmox?

I understand changing the port and base topic in the respective instance, but wonder how to install a program that exists a second time.

Any hints appreciated.

As for why more instances; I have three buildings, well shielded and apart, and just installed three POE SMlight coordinators... but now what?! :)

[edit1] I found on the web: _For multiple configs, what you can do for traditional binaries is to create a new user. When you want to run a second config of a given program, execute it from terminal as that user. Do an su <user> in a terminal and then launch the program from there. All the config files for that program will be grabbed from that user's home directory._
The question is then how to `su` to start multiple instances of z2m? ... in case this is the proper approach?!

**Comment by francisp2** [comment]
Is it not simply to create
* /opt/zigbee2mqtt   and install first one here
* /opt/zigbee2mqtt2 and install second one 
* /opt/zigbee2mqtt3 and install third one ?

Or am I thinking to simply ?

**Reply by DubhAd** [reply]
That's exactly the way. I've run Z2M (in Docker) using that approach:
```yaml
services:
  zigbee2mqtt_new:
    container_name: zigbee2mqtt_new
    image: koenkk/zigbee2mqtt
    volumes:
      - /data/z2m_new:/app/data
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_5cb79dca8a93eb1194cb194f3d98b6d1-if00-port0:/dev/ttyUSB0
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - TZ=Etc/UTC
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "-O -", "http://127.0.0.1:8080"]
      interval: 60s
      timeout: 5s
      retries: 3

  zigbee2mqtt_test:
    container_name: zigbee2mqtt_test
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
      - /data/z2m_test:/app/data
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E1F2ED-if00:/dev/ttyUSB0
    restart: unless-stopped
    ports:
      - 8088:8080
    environment:
      - TZ=Etc/UTC

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /data/zigbee2mqtt:/app/data
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Etc/UTC
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "-O -", "http://127.0.0.1:8080"]
      interval: 60s
      timeout: 5s
      retries: 3
```

**Reply by M-ax-G** [reply]
I don't know docker that well... is this script setting up one docker instance or three?

**Comment by M-ax-G** [comment]
OK, the query was "without docker or LXCs" ...

I need z2m to run in the garage and the shed (used as example here).

The solution (where a standard install was used for the first instance) is:

Copy the `zigbee2mqtt.service` file to (whatever name you like, here) `z2m_shed.service` and `z2m_garage.service` in `/etc/systemd/system`
Modify both new files and change the *Description*, *ExecStart*, and *WorkingDirectory*.
After a service files have been modified, run `sudo systemctl daemon-reload`

Copy the directory `zigbee2mqtt` to `z2m_shed` and `z2m_garage` in `/opt/`
Modify the file `configuration.yaml` in `data/` and change *channel*, *log_directory*, *frontend: port*, *serial: port*.

Start the services:
`sudo systemctl status z2m_garage.service` and for the shed too.

Check if it running:
`sudo systemctl status z2m_garage.service` (same for shed)

Set the services to auto start:
`sudo systemctl enable z2t_garage.service` (and for the shed too).

This worked perfect for me.

Thank you for putting me in the right direction.

**Comment by Aison0** [comment]
For multiple instances of zigbee2mqtt on the same machine I recommend asystemd service template like below:

**The files are located at this positions:**
- systemd service file: `/etc/systemd/system/zigbee2mqtt@.service`
- zigbee2mqtt data/config folder: `/var/lib/zigbee2mqtt/{instance}/`
- zigbee2mqtt source: `/opt/zigbee2mqtt`
- log directory: `/var/log/zigbee2mqtt`
- pnpm: `/usr/local/bin/pnpm`

**Create the instance "my-instance"**
1. create an instance: `systemctl enable zigbee2mqtt@my-instance.service`
2. create the `configuration.yaml` at `/var/lib/zigbee2mqtt/my-instance/configuration.yaml`
3. start the instance: `systemctl start zigbee2mqtt@my-instance.service`
4. check the log files `/var/log/zigbee2mqt/my-instance-%TIMESTAMP%.log`


**/etc/systemd/system/zigbee2mqtt@.service**
```
[Unit]
Description=zigbee2mqtt %i
After=network.target

[Service]
Environment=NODE_ENV=production
Environment=ZIGBEE2MQTT_DATA="/var/lib/zigbee2mqtt/%i"
Environment=ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC="z2m-%i"
Environment=ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_DIRECTORY="/var/log/zigbee2mqtt"
Environment=ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_FILE="%i-%%TIMESTAMP%%.log"
Environment=ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_SYMLINK_CURRENT=false
Type=exec
ExecStart=/usr/local/bin/pnpm start
WorkingDirectory=/opt/zigbee2mqtt
StandardOutput=inherit
# Or use StandardOutput=null if you don't want Zigbee2MQTT messages filling syslog, for more options see systemd.exec(5)
StandardError=inherit
Restart=always
RestartSec=10s
User=root

[Install]
WantedBy=multi-user.target
```

**/var/lib/zigbee2mqtt/my-instance/configuration.yaml example**
```
version: 4
mqtt:
  server: mqtt://localhost:1883
  user: admin
  password: admin
serial:
  port: tcp://a.b.c.d:6638
  baudrate: 115200
  adapter: ember
advanced:
  last_seen: ISO_8601
frontend:
  enabled: true
  port: 8080
```
