### DISCUSSION TITLE
Hue Signe with gradient effect auto turn on

### DISCUSSION THREAD

**Discussion by MaJerle** [Koenkk/zigbee2mqtt#23371] [Devices]
**Executive question**: Is it possible to automatically turn the light on whenever there is a *gradient scene* command?

I have Hue Signe lights and would like to use them in a HA scene (not Z2M scene). They expose light entity and *Gradient scene* entities.
For the light, aim is to set the gradient scene, that I would expect will turn the light on to this state when gradient scene is applied.

Unfortunately, the light does not turn on, and has to be manually turned on before with `light.turn_on` service. You can do this by adding the light entity to the HA scene, but once you turn it on, HA will also apply default color, and gradient scene setup won't apply.

This is how scene yaml is generated from the UI:
```yaml
- id: '1721327385865'
  name: 'Office: Test'
  entities:
    select.hue_light_office_gradient_left_gradient_scene:
      options:
      - blossom
      - .... all other options go here
      - crystalline
      assumed_state: true
      friendly_name: Hue Light - office gradient left Gradient scene
      state: spring_blossom
    light.hue_light_office_gradient_left:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - ... other effects go here
      - stop_hue_effect
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode: color_temp
      brightness: 166
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      friendly_name: Hue Light - office gradient left
      supported_features: 44
      state: 'on'
  metadata:
    select.hue_light_office_gradient_left_gradient_scene:
      entity_only: true
    light.hue_light_office_gradient_left:
      entity_only: true
```

The only solution is to manually edit the scene in yaml file and add 2 entities:

```yaml
- id: scene_id
  name: scene_name
  entities:
    light.light_name
      state: on
    select.light_name_gradient_scene:
      state: name_of_scene
```

If I use just the option below:
```yaml
- id: scene_id
  name: scene_name
  entities:
    select.light_name_gradient_scene:
      state: name_of_scene
```

The light won't turn on.

This is OK up to the extent when you have more lights and want to update them from the UI later. HA will re-populate all the options again, making your gradient scene non-functional since light entity will put the color settings, too. Like in the very first example.

Tested in Z2M, if I apply gradient scene while light is off, nothing happens:
![image](https://github.com/user-attachments/assets/632ca8dd-c134-478f-aff5-4928ecf892d5)

light will go automatically on, if I change the state manually, or if I modify the brightness:
![image](https://github.com/user-attachments/assets/c9e9d681-d8a3-4faa-ad5b-fb71f7a8a509)

Light used:
![image](https://github.com/user-attachments/assets/113a9598-df95-41c8-88d7-f8b6f40aa6cd)
