### DISCUSSION TITLE
Help to debug

### DISCUSSION THREAD

**Discussion by eerison** [Koenkk/zigbee2mqtt#23438] [Devices]
Hello

I am trying to debug a device, But I couldn't make this work :/
it is the defintion that I am testing: https://github.com/Koenkk/zigbee2mqtt/issues/22813#issuecomment-2244492861

I saw that it was possible via `console.log`, But I don't see the result anywhere

e.g:

```js
                [103, 'flow_switch', {
                        from: (v) => {
                                console.log(`debug: [from] flow switch original value ${v}`)
                                return v;
                        },
                        to: (v) => {
                                console.log(`debug: [to] flow switch original value ${v}`)
                                return v;
                        }
                }],
```

my config file

```yaml
advanced:
  log_level: debug
  log_debug_to_mqtt_frontend: true
  log_output:
    - console
    - file
```
