### DISCUSSION TITLE
Niko 552-720X1 device binding state not in sync

### DISCUSSION THREAD

**Discussion by stefanrenne** [Koenkk/zigbee2mqtt#23487] [Devices]
I am able to bind a https://www.zigbee2mqtt.io/devices/552-720X1.html#niko-552-720x1 to a Philips hue light in Z2M, but because the Niko button toggles between the actions "on" and "off" on button press and they are not always in sync with the actual state of the light you sometimes have to press the button again to (for example) turn the light on. 
Is there a way to fix this behaviour? like for example create a binding from the light back to the button?
Thanks in advance!
Stefan

**Comment by martijndhondt** [comment]
I have the same question

**Comment by martijndhondt** [comment]
Any news on this?

**Comment by martijndhondt** [comment]
@stefanrenne 
I have made a group of lights to bind the wall switch to. This works flawless. I read somewhere it's best to put the light in a group (even when you only have 1 light) and then bind the switch to that group.

But the moment i have 2 wall switches to control the same light. I have the same issue. I solved this (but i'm not happy how) by unbinding the on/off to the light group and by creating an automation in HASS to toggle the light when the event_type is on_right or off_right. ( i have the event features enabled in Z2M).

Example code:
```
alias: Z2M_SlaapkamerNachtlampenToggle
description: ""
triggers:
  - trigger: state
    entity_id:
      - event.schakelaar_slaapkamer_l_action
      - event.schakelaar_slaapkamer_r_action
    to: null
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'off_right'}}"
            enabled: true
        sequence:
          - action: light.toggle
            data: {}
            target:
              entity_id: light.slaapkamer_nachtl
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'on_right'}}"
        sequence:
          - action: light.toggle
            data: {}
            target:
              entity_id: light.slaapkamer_nachtl
mode: queued
initial_state: "on"
max_exceeded: silent
``` 
It's not how i really wanted it, but the WAF is better now. Maybe it can help someone...
