### DISCUSSION TITLE
SOLVED: Zigbee2MQTT works but Device list in HomeAssistant GUI is empty

### DISCUSSION THREAD

**Discussion by michaelsidenius** [Koenkk/zigbee2mqtt#23525] [General]
Z2M ver. 1.39.1
HA ver. 2024.7.4
HA OS ver 12.4
HW: Generic x86-64 (16GB RAM, 400 GB SSD)

Running Z2M as add-on to HA on HAOS. 

My Z2M works and automations in HA works and I can follow the MQTT messages from Z2M on the Mosquitto broker (via a 3rd party client).

However, the Z2m Web GUI in HA is showing absolutely **NO devices** (even though they are there) and **NO setup**. So somehow the connection between the HA Frontend and the Z2M is lost (I guess).

Any ideas about how to get the connection back? Have tried all kinds of restart (Z2M, HA, HAOS, HW reboot).

Thanks!

**Comment by francisp2** [comment]
Did you set

```
homeassistant: true
```
in Zigbee2MQTT's configuration.yaml

**Reply by michaelsidenius** [reply]
Yes, thank you, (see configuration.yaml below, password obfuscated)

```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
device_options:
  legacy: false
  homeassistant:
    last_seen:
      enabled_by_default: true
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
zigbee_herdsman_debug: false
ota:
  ikea_ota_use_test_url: false
```
