### DISCUSSION TITLE
Creation of docker z2m container + SLZB-06

### DISCUSSION THREAD

**Discussion by Snake40** [Koenkk/zigbee2mqtt#23682] [General]
Bojour.
I want to test a HA (Docker) + z2m (Docker) + MQTT (Docker) + SLZB-06 POE ethernet dongle configuration.
The MQTT container has been installed and working for a long time.
The installation of HA in a container is done correctly. I cannot install z2m with the POE dongle.
I use
- the following docker-compose:

version: '3.8'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        restart: unless-stopped
        network_mode: bridge
        volumes:
            - /volume1/docker/zigbee2mqtt/data:/app/data
        ports:
            - 8085:8080
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Paris

- the following "configuration.yaml" configuration file:

homeassistant: false
mqtt:
    base_topic: zigbee2mqtt
    #Serveur MQTT
    server: mqtt://192.168.1.100:1883
    #Identification pour accès au serveur
    user: xxx
    password: yyy
serial:
# Localisation du dongle POE SLZB-06 (ethernet)
    port: tcp://192.168.1.43:6638
    baudrate: 115200
    adapter: zstack
# Configuration led verte du dongle
    disable_led: false
advanced:
    # Initialise la puissance de sortie pour le dongle (max = 20)
    transmit_power: 20

For the record, all POE dongle settings are given by the web page associated with the dongle.
The container installs, then indefinitely starts, stops with the following log file:

2024/08/20 18:53:55 stderr at start (/app/index.js:130:14)
2024/08/20 18:53:55 stderr at Object.reRead (/app/lib/util/settings.ts:749:5)
2024/08/20 18:53:55 stderr at getInternalSettings (/app/lib/util/settings.ts:466:21)
2024/08/20 18:53:55 stderr at read (/app/lib/util/settings.ts:380:27)
2024/08/20 18:53:55 stderr at interpretValue (/app/lib/util/settings.ts:369:25)
2024/08/20 18:53:55 stderr at Object.read (/app/lib/util/yaml.ts:7:37)
2024/08/20 18:53:55 stderr at Object.readFileSync (node:fs:464:35)
2024/08/20 18:53:55 stderr at Object.openSync (node:fs:596:3)
2024/08/20 18:53:54 stderr Error: ENOENT: no such file or directory, open ‘/app/data/… 3.yaml’
2024/08/20 18:53:53 stdout Starting Zigbee2MQTT without watchdog.
2024/08/20 18:53:51 stdout Using ‘/app/data’ as data directory

For the record, the "configuration.yaml" file is found and processed when the container is created (WinSCP tells me that the file has been modified).

If someone with this type of installation can tell me the error I'm making, that would be a help.
THANKS.

**Comment by chris-1243** [comment]
```

2024/08/20 18:53:54 stderr Error: ENOENT: no such file or directory, open ‘/app/data/… 3.yaml’
```

From your log... Z2M is trying to open this file which is not present

**Reply by Snake40** [reply]
Thank you for your response.
This is indeed the first idea that comes to mind... Except that '/… 3.yaml' I don't know what it is... Assuming that it is the 'configuration. yaml' which is the file that must be present in the '/data' directory, the file is present and the system sees it because
1) if it did not see it it would try to create it (I did the test) ,
2) WinSCP tells me that the file has been modified (modification of dating parameters)...
So I'm thinking that something in this file is wrong... but I can't find it...

**Reply by chris-1243** [reply]
I saw you configured `network_mode: bridge` in your `docker-compose.yaml`. Maybe there is something to investigate there. I am not at all an expert of docker. The default bridge network is not the best to use. Are you sure your container is able to ping your network ?

https://docs.docker.com/engine/network/drivers/bridge/

Could you provide your full `docker-compose.yaml` and `configuration.yaml` to check if everything is ok there ?

**Reply by Snake40** [reply]
I currently have 4 Docker containers running:
- domoticz is on its own network (this is the first container I created and, at the time, my notion of "Docker network" was nonexistent but ... since it works, I didn't change anything)
- syncthing (file sync) is in bridge,
- portainer is in bridge,
- mqtt (eclipse mosquitto) is in bridge.
For z2m I tried bridge and host without difference in results.
Since our last exchange I did the following test: creation of the z2m container without a "configuration.yaml" file. z2m created the "configuration.yaml" file with standard data. I modified this file with my elements then I restarted the container with the same result as I specified in my first message. After this test, I am sure that the problem does not come from the existence of the configuration file and I think more and more that it comes from the instruction "adapter: zstack" which appears in this file.
Here is my "docker-compose.yaml":

version: "3.8"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /volume1/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8085:8080
    environment:
      - TZ=Europe/Paris

Here is my "configuration.yaml":

homeassistant: false
frontend: true
mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://192.168.1.100:1883
    user: xxx
    password: yyy
serial:
    port: tcp://192.168.1.43:6638
    baudrate: 115200
    adapter: zstack
    disable_led: false
advanced:
    transmit_power: 20
    network_key:
        - 248
        - 111
        - 127
        - 162
        - 222
        - 146
        - 105
        - 150
        - 234
        - 73
        - 8
        - 18
        - 35
        - 127
        - 148
        - 5
    pan_id: 53807
    ext_pan_id:
        - 254
        - 238
        - 57
        - 196
        - 28
        - 9
        - 243
        - 206

**Reply by chris-1243** [reply]
Z2M is able to log in file. Check this [link](https://www.zigbee2mqtt.io/guide/configuration/logging.html). Could you be able to add this to your `configuration.yaml` ? Without log it is hard to know what is going wrong. You should see your log file in /app/data so inside the volume you mapped in your container😉

By the way, which version of SLZB-06 do you have ? 

 - SLZB-06: `zstack`, based on TI chip;
 - SLZB-06M: `ember`, based on Silicon Labs chip.

There is a lot of confusion...

**Reply by Snake40** [reply]
My POE dongle is a SLZB-06. All the configuration concerning it which is found in the "configuration.yaml" file is given by the tool (web page) available when the dongle is connected to the network.
I tried to obtain a more detailed log by setting certain levels to "Debug" but I don't get anything more detailed than the log I put in my initial message. I recognize, however, that I am at the limits of my understanding when I read the URL that you gave me in the link...

**Reply by chris-1243** [reply]
Your `configuration.yaml` should look this after adding the log part. I added as well `channel` in it as you should really assign a channel which is free of wifi interference. Remove `#` and a numeric value.
```
homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.100:1883
  user: xxx
  password: yyy
serial:
  port: tcp://192.168.1.43:6638
  baudrate: 115200
  adapter: zstack
  disable_led: false
advanced:
  log_level: debug
  timestamp_format: YYYY-MM-DD HH:mm:ss
  log_directory: /app/data
  log_file: log.txt
  log_rotation: true
  log_output:
    - console
    - file
  # Optional: Zigbee channel, changing might require re-pairing of some devices (see docs below). (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid problems)
  # (default: 11)
  #channel:
  transmit_power: 20
  network_key:
    - 248
    - 111
    - 127
    - 162
    - 222
    - 146
    - 105
    - 150
    - 234
    - 73
    - 8
    - 18
    - 35
    - 127
    - 148
    - 5
  pan_id: 53807
  ext_pan_id:
    - 254
    - 238
    - 57
    - 196
    - 28
    - 9
    - 243
    - 206
``` 

Restart your container and check in /app/data what you have in log.txt. Share it if any errors

**Reply by Snake40** [reply]
I really thank you for your help and for the time you devote to me...

Modifying the "configuration.yaml" file as you advised me does not change anything whatsoever for the operation of the container or for the log. For the latter, I do not retrieve a log file in the "/data" directory.

This irritates me even more because when I start from 0, when I voluntarily launch docker-compose without having a "configuration.yaml" file, in addition to the fact that the system creates a standard "configuration.yaml" file for me, im also creates a directory "/data/log" in which I find subdirectories "data/log/%TIMESTAMP%" each with a file "log.log" (text file) whose detail is more important than that of the "log" file that I retrieve when my "configuration.yaml" file exists.

Here is the example:

Using '/app/data' as data directory
Creating configuration file...
Starting Zigbee2MQTT without watchdog.
[2024-08-24 11:07:25] info: 	z2m: Logging to console, file (filename: log.log)
[2024-08-24 11:07:25] info: 	z2m: Starting Zigbee2MQTT version 1.39.1 (commit #e132316)
[2024-08-24 11:07:25] info: 	z2m: Starting zigbee-herdsman (0.55.3)
[2024-08-24 11:07:25] error: 	zh:zstack:znp: Failed to determine if path is valid: 'Error: ENOENT: no such file or directory, lstat '/dev/ttyACM0''
[2024-08-24 11:07:25] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-08-24 11:07:25] error: 	z2m: Error while starting zigbee-herdsman
[2024-08-24 11:07:25] error: 	z2m: Failed to start zigbee
[2024-08-24 11:07:25] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-08-24 11:07:25] error: 	z2m: Exiting...
[2024-08-24 11:07:25] error: 	z2m: Error: Error: No such file or directory, cannot open /dev/ttyACM0

After a good night's sleep, I reread the zigbee2mqtt documentation that you advised me to read and apply... this time I understood perfectly, especially since your proposed "configuration.yaml" file has finished enlightening me.
I don't understand why our debug settings are not taken into account.

**Reply by Snake40** [reply]
I'm starting to suspect that the "adapter:zstack" line in the "configuration.yaml" file is the source of my woes. As a test, I commented this line to see the nature of the "insults" that the system was going to send me... To my great surprise, the log file is exactly the same as the one I've been talking to you about since some time!...

**Reply by chris-1243** [reply]
> I'm starting to suspect that the "adapter:zstack" line in the "configuration.yaml" file is the source of my woes.

As I told you in a previous comment, there are two version of the slzb-06... I would comment the `adapter: zstack` and `baudrate: 115200` in your `configuration.yaml` then start your container with `sudo docker compose up`. Paste the output. Your container should be then stoped with `ctrl+c`.

> This irritates me even more because when I start from 0, when I voluntarily launch docker-compose without having a "configuration.yaml" file, in addition to the fact that the system creates a standard "configuration.yaml" file for me, im also creates a directory "/data/log" in which I find subdirectories "data/log/%TIMESTAMP%" each with a file "log.log" (text file) whose detail is more important than that of the "log" file that I retrieve when my "configuration.yaml" file exists.

Why don't you use this basic and auto-generated `configuration.yaml` ? You just need to add the lines required in it and restart your container.

**Reply by Snake40** [reply]
I actually used the standard "configuration.yaml" file by modifying it.
For the rest, as the container obviously cannot reach the coordinator, I think there may be a problem with the Synology NAS firewall. I will look into this in detail ...

**Reply by chris-1243** [reply]
As you said mosquitto is running via docker, I would try this command:
`docker compose exec mosquitto ping -c4 ip.address.slzb.06`

If successful, docker is able to ping your coordinator. I have read in a post docker might be tricky on Synology NAS.

**Reply by Snake40** [reply]
I pinged the "mqtt" container to the Dongle IP. Obviously the dongle responded...
Assuming that when I launch the "zigbee2mqtt" container it starts then stops and this indefinitely, I tried the same operation between this container and the dongle IP and visibly, the dongle responded...
So it seems that the problem is not a connectivity problem between the container and the dongle.
It's less and less clear to me.

**Reply by chris-1243** [reply]
Without log, it is then hard to provide help.

I just saw in your `docker-compose.yaml` you are setting PUID/PGID as an environment variable. If you want to run Z2M rootless as [documented](https://www.zigbee2mqtt.io/guide/installation/02_docker.html), you change your config like:

```
version: '3.8' # This is not needed anymore in latest version of Docker
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /volume1/docker/zigbee2mqtt/data:/app/data
    ports:
      - 8085:8080
    environment:
      - TZ=Europe/Paris
    user: uid:gid
    # Not needed as you are using a network device
#    group_add:
#      - dialout
``` 
Be sure the permissions are set correctly.
