### DISCUSSION TITLE
How to remove front end notifications?

### DISCUSSION THREAD

**Discussion by nixilb** [Koenkk/zigbee2mqtt#23728] [General]
![image](https://github.com/user-attachments/assets/e58227f6-9854-49a3-ba28-f1d49ae93326)
Does someone know how to remove these pescy useless notications that prevent me to see the right part of the frontend?
Didnt find the setting...
Most are bulbs that are offline which is normal. Or sensors I don't use for the moment.

**Comment by chris-1243** [comment]
Have you tried this as you do not use those devices for the moment ?

```
devices:
  '0x00158d0001d82999':
     ...
     disabled: true
```

https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html

**Comment by nixilb** [comment]
The pb mostly occurs with bulbs that goes power off at any time for any delay. They are not "disabled". This is not an error as it will go on line as soon as anyone switch them on. Ils god to have a MQTT message for that but not a notification. a LOT of notifications.

**Reply by chris-1243** [reply]
Disable then the availability check... those errors come from this feature. You are asking Z2M to check if your devices are online/offline.

This may be done for some devices only

```
devices:
    '0x12345678':
        friendly_name: 'my_bulb'
        # Set availability: false to disable the availability feature for a specific device
        availability: false
```

https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration

Be aware, disconnecting lamps (routers) from your network all the time may cause stability problems
