### DISCUSSION TITLE
Groups for TuYa TS0001 (BSEED) switches work incorrectly

### DISCUSSION THREAD

**Discussion by Piscator74** [Koenkk/zigbee2mqtt#23957] [Devices]
I have created a group for 2 TuYa TS0001 (BSEED) switches so that they can work as 2way switches (currently, that behavior is customized in openHAB). I used the instructions on https://www.zigbee2mqtt.io/guide/usage/groups.html#configuration
```
groups:
  '1':
    friendly_name: groupSwitch_gf_garage
    off_state: 'last_member_state'
    devices:
      - bseedSwitch_gf_garage_front2WL/1
      - bseedSwitch_gf_garage_back2W/1
```

When I send the payload to the group (`zigbee2mqtt/groupSwitch_gf_garage/set`), it works as expected.
However, when I send a payload to a single switch or manually use the switch, the group is not updated (as I would expect). What am I doing wrong?
