### DISCUSSION TITLE
Disable a lights color temp ?

### DISCUSSION THREAD

**Discussion by didster** [Koenkk/zigbee2mqtt#24023] [General]
New to all this, sorry... Is it possible to disable Z2MQTTs exposure of color temp feature/attribute for a given light?  The device itself is a tuya ts0502b but I only have cold LEDs connected (which is fine for my needs).  I'd like to disable the ability to change color temp from Z2MQTT if this is possible?  Because as it stands if someone changes the light to warm via HA they go off as nothing is connected to the warm power output.

I've found various examples which say they should do this from `configuration.yaml`:

```
0xaXXXXXXXXXXXXXX':
    friendly_name: My Light
    color_mode: false
```

And 

```
0xaXXXXXXXXXXXXXX':
    friendly_name: My Light
  - type: light
        features:
          - property: state
            access: 3
          - property: brightness
            access: 3
```

But neither do anything, or seem to be documented so guess are for older versions?

Thanks
