### DISCUSSION TITLE
configuration for Conbee3 docker solution

### DISCUSSION THREAD

**Discussion by nsk** [Koenkk/zigbee2mqtt#24126] [General]
Hi, I'm making this post for those who are struggling with conbee3 and docker, I think it can help, maybe it should be put in the documentation, I searched for myself before finding the solution and by trial and error

**_configuration.yaml_**
```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://"ip":1883'
  # MQTT server authentication, uncomment if required:
  user: your login
  password: your password

# Serial settings
serial:
  port: /dev/ttyUSB0
  adapter: deconz
  baudrate: 115200

advanced:
log_directory: /var/log
experimental: {}
frontend:
 webGUI
  port: 8089
ota:
  update_check_interval: 10
disable_automatic_update_check: false
```

**_script to detect usb port:_**

```
sudo vim ports.sh

#!/bin/bash

for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
    (
        syspath="${sysdevpath%/dev}"
        devname="$(udevadm info -q name -p $syspath)"
        [[ "$devname" == "bus/"* ]]
        eval "$(udevadm info -q property --export -p $syspath)"
        [[ -z "$ID_SERIAL" ]]
        echo "/dev/$devname - $ID_SERIAL"
    )
done
```

```
sudo chmod 777 ports.sh 
./ports.sh
```

 **_docker start :_** 

`sudo docker run    --name=zigbee2mqtt    --restart=unless-stopped    -p 8089:8089    -v $(pwd)/data:/app/data    -v /run/udev:/run/udev:ro    --device=/dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03186404-if00-port0:/dev/ttyUSB0    --user 1001:1001    --group-add dialout    -e TZ=Europe/Zurich    koenkk/zigbee2mqtt`
