### DISCUSSION TITLE
[Paulmann 500.45] Disable RGB color-control

### DISCUSSION THREAD

**Discussion by AliveDevil** [Koenkk/zigbee2mqtt#24383] [Devices]
I have one Paulmann 500.45 LED controller, which is attached to a dimmable LED light strip (fixed temperature, no RGB)

Is there any way of configuring Zigbee2MQTT that only state, brightness and power-on behavior are exported to HomeAssistant?

**Comment by AliveDevil** [comment]
Was already documented - though not easily discoverable.

<details>
<summary>configuration.yaml</summary>

```
devices:
  0xID:
    homeassistant:
      light:
        supported_color_modes: [brightness]
```
</details>
