### DISCUSSION TITLE
cannot getmSLZB-06M to start, gives errors connecting

### DISCUSSION THREAD

**Discussion by asantaga** [Koenkk/zigbee2mqtt#24410] [Devices]
Hi trying to start the a docker container connecting to a slzb-06m stick and it just fails to start. It appears to connect but then says it cant.. The stick is visible on the network, ZHA in Homeassistant has no issues but I wanted to move to z2m

this is the error I get
```
zigbee2mqtt         | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt         | [2024-10-20 00:51:57] info:       z2m: Logging to console, file (filename: log.log)
zigbee2mqtt         | [2024-10-20 00:51:57] info:       z2m: Starting Zigbee2MQTT version 1.40.2 (commit #e06848d)
zigbee2mqtt         | [2024-10-20 00:51:57] info:       z2m: Starting zigbee-herdsman (2.1.3)
zigbee2mqtt         | [2024-10-20 00:51:58] info:       zh:zstack:znp: Opening TCP socket with 192.168.1.130:6638
zigbee2mqtt         | [2024-10-20 00:51:58] info:       zh:zstack:znp: Socket connected
zigbee2mqtt         | [2024-10-20 00:51:58] info:       zh:zstack:znp: Socket ready
zigbee2mqtt         | [2024-10-20 00:51:58] info:       zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
zigbee2mqtt         | [2024-10-20 00:51:59] info:       zh:zstack:znp: Skip bootloader for CC2652/CC1352
zigbee2mqtt         | [2024-10-20 00:52:17] error:      z2m: Error while starting zigbee-herdsman
zigbee2mqtt         | [2024-10-20 00:52:17] error:      z2m: Failed to start zigbee
zigbee2mqtt         | [2024-10-20 00:52:17] error:      z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
zigbee2mqtt         | [2024-10-20 00:52:17] error:      z2m: Exiting...
zigbee2mqtt         | [2024-10-20 00:52:17] error:      z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee2mqtt         |     at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:113:27)
zigbee2mqtt         |     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
zigbee2mqtt         |     at Zigbee.start (/app/lib/zigbee.ts:69:27)
zigbee2mqtt         |     at Controller.start (/app/lib/controller.ts:161:27)
zigbee2mqtt         |     at start (/app/index.js:154:5)
zigbee2mqtt exited with code 1
zigbee2mqtt         | Starting Zigbee2MQTT without watchdog.

``` 

and my configuration.xml looks like

```
homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.204
serial:
  port: tcp://192.168.1.130:6638
```

Any ideas?
Thank you

**Comment by mrebbert** [comment]
Could you connect the zigbee port of your slzb-06?
For example with nc -v 192.168.1.130 6638

**Reply by mrebbert** [reply]
add:
and you may should add
```
  baudrate: 115200
  adapter: zstack
```
to the serial section.

**Comment by asantaga** [comment]
Alas didnt work :-(

but in the adaptor admin UI, I noticed it was using the ezsp driver, so this worked
```
homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: tcp://192.168.1.130:6638
  baudrate: 115200
  adapter: ezsp
  disable_led: false
  transmit_power: 20
```

I now have mqtt errors, but thats a different issue

thank you
