### DISCUSSION TITLE
SONOFF Zigbee 3.0 USB Dongle Plus  Not supportd

### DISCUSSION THREAD

**Discussion by OZoneGuy** [Koenkk/zigbee2mqtt#24896] [Devices]
Hi,

I am trying to get Z2M to work for a specific device. I am running HAS on an unraid server, docker, and want to run Z2M there as well.

When I try to start Z2M it fails with this error:

```
2024-11-23 22:05:21] error:    z2m: Error while starting zigbee-herdsman
[2024-11-23 22:05:21] error:    z2m: Failed to start zigbee
[2024-11-23 22:05:21] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-11-23 22:05:21] error:    z2m: Exiting...
[2024-11-23 22:05:21] error:    z2m: Error: Error: Not supported, cannot set
```

According to the docs this device is supported but needs flashing (?). I did try to flash it using this [firmware](https://github.com/itead/Sonoff_Zigbee_Dongle_Firmware/tree/master/Dongle-E/Router), but HAS fails to recognize it and Z2M still doesn't work.

I couldn't find anyone facing the same issue online.

Is this dongle not supported? Or am I missing a step?

Let me k

**Comment by chris-1243** [comment]
Which Sonoff Dongle do you try to use ? Dongle-P or Dongle-E ?
They do not use the same chip.

When posting log, try the paste a full log as they might have usefull information before or after your error in order to help

Also, would you share `configuration.yaml` (without sensitive information).

**Reply by OZoneGuy** [reply]
How do I know what version of the dongle do I have?

and here is the configuration:

```yaml
homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyACM0
  adaptor : ember
advanced:
  network_key:
    - 31
    - 252
    - 158
    - 139
    - 91
    - 194
    - 137
    - 33
    - 78
    - 34
    - 254
    - 201
    - 60
    - 10
    - 233
    - 240
  pan_id: 4769
  ext_pan_id:
    - 213
    - 244
    - 38
    - 8
    - 119
    - 135
    - 60
    - 7
```
