### DISCUSSION TITLE
Question about the homeassistant part in Z2M's configuration.yaml

### DISCUSSION THREAD

**Discussion by ovizii** [Koenkk/zigbee2mqtt#25001] [General]
With the latest update, I read the breaking changes news and went to investigate my conf file.
I found two different parts which seem to do the same thing, so I am wondering if anyone can explain the difference and the right way to go forward.

On one hand I have:

```
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: false
  experimental_event_entities: true
```

on the other one: 

```
advanced:
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: homeassistant/status
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
```

so this left me wondering about two things:

**1. Which setting goes whereas it seems to work with either?
2. The Z2M GUI seems to cover all this too so should I configure Z2M via cconf fiel or GUI?**
