### DISCUSSION TITLE
docker-compose not working after upgrade

### DISCUSSION THREAD

**Discussion by aifrog** [Koenkk/zigbee2mqtt#25483] [General]
My docker compose file looks like this and works like a charm until updated to 2.0. Now the container refuses to be started:

```
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=false"
    image: koenkk/zigbee2mqt
    restart: always
    ports:
      - 9443:9442
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /run/udev:/run/udev:ro
      - /volume1/docker/zigbee2mqtt/data:/app/data
 ```
      
  I found a further line in the documentation, which is missing in my docker-compose file:
      
```
      devices:
            # Make sure this matched your adapter location
            - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
 ```

1.  How would the syntax be if I use a SLZB-06 on a certain IP adress and port?
2. Would this fix the problem and the container would start again?

Thx for your help,

H-C
