### DISCUSSION TITLE
Frient smoke detector SMSZB-120 -  How to add to group

### DISCUSSION THREAD

**Discussion by HiFiJ** [Koenkk/zigbee2mqtt#25487] [Devices]
Hi everyone,
thanks for this great project!
I am using several Frient smoke detectors (SMSZB-120). Of course I am trying to set up a connection which triggers all alarms if one detector has signalled smoke.

The devices themselves work great in Z2M. Smoke detection is working, manual alarm triggering is working, battery reports/temperature etc. all working fine.

As far as I understand, those detectors can not interconnect independently without a coordinator. So I am looking to at least  set off the alarm of all detectors via Z2M/coordinator.
I tried to activate all detectors/alarms by using a Wildcard topic, but found that this is unfortunately not supported ( https://github.com/Koenkk/zigbee2mqtt/issues/589 ).

I believe in this situation this would best be done by setting up a group in Z2M.

Unfortunately I am hitting a roadblock there as well, as I am not able to add the smoke detectors to a group.  Log says: 
`info 2025-01-04 13:52:24z2m: Adding 'Rauchmelder/Waschküche' to 'AlleRauchmelder'`
No further log entries show up, and I do not find any evidence of the device being added to the group. Group member count stays "0".

Anyone able to help with further insights into this?
Thanks very much,

Joost

**Comment by HiFiJ** [comment]
Btw. I tried to "wake" a device/smoke detector by triggering the alarm manually (via Z2M, working fine) immediately before trying to add the device to a group.

**Reply by andrei-lazarov** [reply]
I believe it's a Zigbee limitation. You can't use end_devices in Zigbee groups.
Tried with multiple devices (relays). Even if adding to the group works, it won't respond to any group commands.

**Comment by martijn1985** [comment]
I'm having the same issue with this device, I did not found a solution yet, but I have found a technical manual here: https://smarthome-store.de/media/documents/smszb-120-technical-manual-smoke-alarm.pdf

It does not mention anything about group functionality, though.

**Comment by HiFiJ** [comment]
Thanks for chiming in.

In the end I got an error message at last:

![Screenshot from 2025-01-12 10-48-18](https://github.com/user-attachments/assets/9c8b0d5a-da8f-4ccc-bfe4-822bf4778dd3)

**Comment by HiFiJ** [comment]
Still looking for a way to signal an alarm without going the manual route of instructing Node Red to set off the alarm with each smoke detector after manually adding the device in the flow :-(

**Comment by malaakso** [comment]
Autonomous (i.e. not handled by coordinator) Zigbee communication can be done by binding a client cluster of one device to a server cluster of another device or group. Unfortunately IAS warning device and zone device clusters are both server clusters, so they can't be bound to each other. The only way to achieve this is by having logic in coordinator side (Home assistant, Node-RED, or something like that).

**Comment by HiFiJ** [comment]
Thanks. 
I wonder if there is a way to have a recursion in Node Red to activate available detecors without specifically knowing each one's name. I have named them with this scheme "detector/livingroom" or "detector/basement", so the first part before the "/" is always the same.
I would like to set this up in a way that I can add further detectors in Zigbee2MQTT without  editing the NodeRed flow everytime.

**Comment by Ofenhed** [comment]
For anyone finding this in the future, let me share my Home Assistant alarm propagation automation:
```yaml
alias: Sync Fire Alarms
description: ""
trigger_variables:
  maybe_sensor_entities: >
    {{ integration_entities('mqtt')
       | select("match", "^binary_sensor\..*_(smoke|test)$")
       | list }}
# If the model name of the devices were to change, this automation breaks.
# Network propagation tests needs to be part of your regular smoke detector
# tests.
triggers:
  - trigger: template
    value_template: >-
      {%- set active = maybe_sensor_entities
                     | select("is_state", "on")
                     | list %}
      {%- set active_smoke = active
                           | select("is_device_attr", "model", "Smoke detector with siren") %}
      {%- set active_heat = active
                          | select("is_device_attr", "model", "Fire detector with siren") %}
      {{- ((active_smoke | first | default(None))
           or (active_heat | first | default(None))) != None }}
    id: activated
  - trigger: template
    value_template: >-
      {%- set active = maybe_sensor_entities
                     | select("is_state", "on")
                     | list %}
      {%- set active_smoke = active
                           | select("is_device_attr", "model", "Smoke detector with siren") %}
      {%- set active_heat = active
                          | select("is_device_attr", "model", "Fire detector with siren") %}
      {{- ((active_smoke | first | default(None))
           or (active_heat | first | default(None))) == None }}
    for:
      hours: 0
      minutes: 0
      seconds: 8
    id: deactivated
conditions: []
actions:
  - variables:
      fire_sensors: >
        {%- set smoke_sensors = maybe_sensor_entities
                              | select("is_device_attr", "model", "Smoke detector with siren") %}
        {%- set heat_sensors = maybe_sensor_entities
                             | select("is_device_attr", "model", "Fire detector with siren") %}

        {{- smoke_sensors | list + heat_sensors | list }}
      activated_sirens: >
        {%- set fire_sensor_devices = fire_sensors
                                    | map("device_id")
                                    | unique
                                    | list %}

        {{- fire_sensor_devices
            | map("device_entities")
            | map("select", "match", "^switch\..*_alarm$")
            | map("first")
            | list }}
  # Note that this will be aborted if alarm state changes, as this automation has `mode: restart`.
  - repeat:
      # When it comes to fire safety, there is no "excessive".
      # Packages may become lost, especially if routing Zigbee nodes are destroyed by fire.
      count: 20
      sequence:
        - target:
            entity_id: "{{ activated_sirens | shuffle }}"
          action: |-
            {{'switch.turn_on' if trigger.id == 'activated' else 'switch.turn_off' }}
        - delay:
            hours: 0
            minutes: 0
            seconds: 3
            milliseconds: 0
mode: restart
```
While not directly applicable to Node Red, I would assume that similar information would be available to Node Red as what I use from Home Assistant.
