### DISCUSSION TITLE
Need help finding out why zigbee2mqtt no longer starts after upgrading

### DISCUSSION THREAD

**Discussion by pullbox** [Koenkk/zigbee2mqtt#25577] [General]
zigbee2mqtt was set to auto update and when 2.0 came out it automatically updated it and since then it was no longer running.
I tried to follow the guide available for the breaking changes but could not resolve that. 
Tried to roll back to the previous version, but that version then also showed the same error as below. 

At this point, I am running 2.0 and getting the following error in my log:

[11:06:23] INFO: Preparing to start...
[11:06:23] INFO: Socat not enabled
[11:06:23] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2025-01-05 11:06:31] error: 	z2m: Error while starting zigbee-herdsman
[2025-01-05 11:06:31] error: 	z2m: Failed to start zigbee-herdsman
[2025-01-05 11:06:31] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-01-05 11:06:31] error: 	z2m: Exiting...
[2025-01-05 11:06:31] error: 	z2m: Error: Error: Not supported, cannot set

How can I figure out what device / configuration is causing the "Not supported, cannot set" error.

Complication is that it is running within a docker container in HA which restarts every time the system stops because of the above.

Sorry, fairly a noob here.  My system was running stable for years before this update.
Any help is appreciated.

**Comment by djurny** [comment]
Hi there,
Can you share some more details, like which adapter you are using and post your `configuration.yaml` files before and after the upgrade to 2.0.0 ?
Grt,

**Reply by pullbox** [reply]
HI Djurny,
I am using a Texa Instrument TI CC2531

socat
```
enabled: false
master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
options: "-d -d"
log: false
``` 

mqtt
```
ase_topic: zigbee2mqtt
server: mqtt://192.168.83.34:1883
user: mqtt
password: xxxxxxxxxxx!
advanced:
  log_level: debug
```

serial (before)
```
port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E22285-if00
```

serial (new)
```
port: /dev/ttyACM0
adapter: zstack
```

**Comment by djurny** [comment]
Hi there,
Seems you are sharing the add-on configuration? Can you also share the actual `configuration.yaml` from before and after the upgrade?

In the meantime, what happens if you change the `port` value back to what is was before?

Grt,

**Reply by pullbox** [reply]
Hi
Changing back to the original port resolves the following by adding the Adapter.

```
[2025-01-05 13:50:54] error: 	z2m: Error: Adapter 'auto' does not exists, possible options: deconz, ember, ezsp, zstack, zboss, zigate
    at Function.create (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/adapter.ts:80:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/controller/controller.ts:132:24)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:142:13)
    at start (/app/index.js:161:5)
```

But then the "not supported" shows up again.

Here is the configuration.yaml
Current:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

default_config:
ios:
cloud: !include cloud.yaml

frontend:

panel_custom: !include panel_custom.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

wemo:
  discovery: false
  static:
    - !secret wemo_smart_switch
    - !secret wemo_mini_1_switch

# Text to speech
tts:
  - platform: google_translate

# Includes
group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#light: !include lights.yaml
#camera: !include cameras.yaml

recorder:
  db_url: !secret recorder_db_url
  auto_purge: true
  purge_keep_days: 5
```

I don't believe anything was changed in the yaml before the update as I did not make any changes.

**Reply by pullbox** [reply]
Do you need the imported yaml files as well like lights.yaml etc.?

**Reply by pullbox** [reply]
Here is the scripts.yaml as example:

```
"1576310844380":
  alias: Blink snap pictures
  sequence:
    - data:
        name: My Camera
      service: blink.trigger_camera
    - delay: 00:00:05
    - service: blink.blink_update
    - data:
        filename: /config/www/blink_entrance.jpg
      entity_id: camera.blink_entrance
      service: camera.snapshot

firstfloor_lights_toggle:
  sequence:
    - service: homeassistant.toggle
      entity_id:
        - light.entryway
        - light.hue_living_room
        - light.hue_living_room_2
        - switch.kasa_1
        - switch.kasa_2
        - switch.kasa_3
        - switch.kasa_4
        - switch.kasa_11
        - switch.kasa_8
        - switch.mini_1
        - light.stand_light_2
        - switch.nodeid_4_switch

firstfloor_lights_turn_off:
  sequence:
    - service: homeassistant.turn_off
      entity_id:
        - light.entryway
        - light.hue_living_room
        - light.hue_living_room_2
        - switch.kasa_1
        - switch.kasa_2
        - switch.kasa_3
        - switch.kasa_4
        - switch.kasa_11
        - switch.kasa_8
        - switch.mini_1
        - light.stand_light_2
        - switch.nodeid_4_switch

secondfloor_lights_turn_off:
  sequence:
    - service: homeassistant.turn_off
      entity_id:
        - light.c44f33ab5155_192_168_1_66
        - light.hue_white_lamp_1

livingroom_lights_toggle:
  sequence:
    - service: homeassistant.toggle
      entity_id:
        - light.hue_living_room
        - light.hue_living_room_2
        - light.stand_light_2
```

**Reply by pullbox** [reply]
Here is the Zigbee conf from the packages import:

```
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "true"
      - service: timer.start
        data:
          entity_id: timer.zigbee_permit_join
  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
      - entity_id: input_boolean.zigbee_permit_join
        platform: state
        to: "off"
    action:
      - data:
          payload: "false"
          topic: zigbee2mqtt/bridge/config/permit_join
        service: mqtt.publish
      - data:
          entity_id: timer.zigbee_permit_join
        service: timer.cancel
  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "false"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.zigbee_permit_join

## Zigbee Map
mqtt:
  sensor:
    - name: Zigbee2mqtt Networkmap
      # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      state_topic: zigbee2mqtt/bridge/networkmap/raw
      value_template: ">- {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

    - name: Bridge state
      state_topic: zigbee2mqtt/bridge/state
      icon: mdi:router-wireless

```
