### DISCUSSION TITLE
Best method to use buttons with Home Assistant after .action removal ?

### DISCUSSION THREAD

**Discussion by silkyclouds** [Koenkk/zigbee2mqtt#25677] [General]
First of all, thank you for the amazing work on Zigbee2MQTT and the recent 2.0.0 release! 
Now, I have one little issue since the removal of sensor.*_action entities, which directly impacts the use of buttons with Home Assistant.

Before the update, I used blueprints for my automations, particularly this one: https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1743/

This blueprint relied on the .action sensor to trigger different automations (e.g., turning lights on/off, switching between modes, etc.). However, since the .action entity is no longer exposed by default, my automations have stopped working, and I’m unsure how to adapt to the new system.

I’ve read the documentation and understand that using MQTT Device Triggers is now the recommended method.

Could you please provide guidance on how to best set up buttons like the IKEA E1743 (and eventually how to make use of buttons that needs to use HA automation to turn of devices) with the new system? Do you have any examples or recommended blueprints that work well with the MQTT Device Trigger approach?

Most of my buttons are simply paired directly with my bulbs, but two of my rooms has shit zigbee devices (ZBMINI-L...) that do not support pairing, therefore, I really do rely on HA to trigger these. 

So for now, I decided to rewrite something from scratch, that actually checked the mqtt topic for one of these buttons : 

```
alias: Salle de bain - Bouton MQTT
description: Gestion du bouton de la salle de bain avec MQTT triggers
triggers:
  - topic: zigbee2mqtt/Salle de bain - interrupteur/action
    trigger: mqtt
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'on' }}"
        sequence:
          - target:
              entity_id:
                - switch.salle_de_bain_petite_lampe
                - >-
                  switch.cave_module_relais_1_utilise_pour_luminaires_salle_de_bain_l11
                - >-
                  switch.cave_module_relais_1_utilise_pour_luminaires_salle_de_bain_l12
            action: switch.turn_on
            data: {}
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'off' }}"
        sequence:
          - target:
              entity_id:
                - switch.salle_de_bain_petite_lampe
                - >-
                  switch.cave_module_relais_1_utilise_pour_luminaires_salle_de_bain_l11
                - >-
                  switch.cave_module_relais_1_utilise_pour_luminaires_salle_de_bain_l12
            action: switch.turn_off
            data: {}
    default: []
mode: single
````
not sure tyhis is best way to achieve things, though. 
thanks ! :)

**Comment by Koenkk** [comment]
Personally I do everything via the UI and this works really well, example:

**When**

<img width="1070" alt="Screenshot 2025-01-08 at 21 57 00" src="https://github.com/user-attachments/assets/834901a1-be0d-4c51-b681-23adab8591e8" />

**Then do**

<img width="1020" alt="Screenshot 2025-01-08 at 21 57 11" src="https://github.com/user-attachments/assets/29e66a03-12d3-46a1-ab11-e8f70a5244f9" />

**Reply by huperaisan** [reply]
Thanks for this. How would you do something similar in Node Red? I'm trying to fix my NR flow that used an "events: state" node with a button `_action`.

**Reply by Koenkk** [reply]
@huperaisan I dont know node-RED, so cannot recommend anything there

**Comment by DubhAd** [comment]
Personally I've enabled the new event entity and I'm using that. It's a really trivial change:
```yaml
triggers:
  - platform: state
    entity_id: sensor.office_dial_moes_action
    to: 'toggle'
        # move this value to a new template condition, replacing the value with null (no quotes)
```
becomes:
```yaml
triggers:
  - trigger: state
    entity_id: event.office_dial_moes_action
    to: ~
        # null and ~ (and NULL) are functionally identical - I just happen to prefer ~
conditions:
  - condition: template
    value_template: >-
      {{ trigger.to_state.attributes.event_type == 'toggle' }}
```
