### DISCUSSION TITLE
QS-Zigbee-CP03 curtain module problem

### DISCUSSION THREAD

**Discussion by NikolamViser** [Koenkk/zigbee2mqtt#25863] [Devices]
Hello,

I have 4 QS-Zigbee-CP03 in my setup. Two of them seem to be different version. Two are identified Zigbee Model: TS130F, Zigbee Manufacturer:
**_TZ3000_zirycpws**, and the other two Zigbee Model: TS130F, Zigbee Manufacturer: **_TZ3210_ol1uhvza**

I have Sonoff dongle P as a coordinator, and one Sonoff dongle E as a router. I have 40 devices, 22 of which are routers. My system is RPi 5 with HAOS and Z2M addon, which I recently updated to 2.0, but the issue started even before the update. All updated to the latest versions after issues started appearing, but no change.

Firstly I had only two of the devices installed (one of each version), and worked flawlessly for months. I decided it is time to add two more, and the issues appeared. When the devices are inactive for some time, and when I want to change the position of the blinds with the slider, doesn't matter up or down, they ignore the command and go to 0% (fully open). It happens only on **_Z3210_ol1uhvza** devices. Also the automation set to close the blind at sunset gets it to fully open. 

Most of the time the switch won't take the stop command until it is fully opened, and even 10 more seconds after that seems to be non responsive.
After that, it starts working normally for some time, but the issue reappears after next inactivity period. If I use up or down command, it works normally every time.

> [2025-01-16 23:24:58] debug: 	z2m: Received Zigbee message from 'dining room blinds', type 'attributeReport', cluster 'closuresWindowCovering', data '{"tuyaMovingState":0}' from endpoint 1 with groupID 0
> [2025-01-16 23:24:58] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/dining room blinds', payload '{"calibration":"OFF","calibration_time":29,"linkquality":40,"motor_reversal":"ON","moving":"UP","position":38,"state":"OPEN"}'
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
> [2025-01-16 23:24:58] debug: 	zh:zstack:znp: <-- SRSP: AF - dataRequest - {"status":0}
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --- parseNext []
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,107,173]
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,107,173]
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,107] - 173
> [2025-01-16 23:24:58] debug: 	zh:zstack:znp: <-- AREQ: AF - dataConfirm - {"status":0,"endpoint":1,"transid":107}
> [2025-01-16 23:24:58] debug: 	zh:zstack:unpi:parser: --- parseNext []
> [2025-01-16 23:24:59] debug: 	zh:zstack:unpi:parser: <-- [254,27,68,129,0,0,2,1,100,112,1,1,0,40,0,156,53,29,0,0,7,8,250,10,8,0,32,53,100,112,29,190]
> [2025-01-16 23:24:59] debug: 	zh:zstack:unpi:parser: --- parseNext [254,27,68,129,0,0,2,1,100,112,1,1,0,40,0,156,53,29,0,0,7,8,250,10,8,0,32,53,100,112,29,190]
> [2025-01-16 23:24:59] debug: 	zh:zstack:unpi:parser: --> parsed 27 - 2 - 4 - 129 - [0,0,2,1,100,112,1,1,0,40,0,156,53,29,0,0,7,8,250,10,8,0,32,53,100,112,29] - 190
> [2025-01-16 23:24:59] debug: 	zh:zstack:znp: <-- AREQ: AF - incomingMsg - {"groupid":0,"clusterid":258,"srcaddr":28772,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":40,"securityuse":0,"timestamp":1914268,"transseqnumber":0,"len":7,"data":{"type":"Buffer","data":[8,250,10,8,0,32,53]}}

There are no errors in logs both of z2m or HA. Log shows as if I sent the Open command even if sent the Close command. Coincidentally, it started happening when I passed number of 40 devices, which I believe shouldn't be the issue. I have since removed some of the devices, to go back to 39, and removed one of the **_Z3210_ol1uhvza** entirely, but the first one that worked for months continued to malfunction.

Anyone has an idea what is going on here? I'm lost.

**Comment by NikolamViser** [comment]
I have been a slave of this module for the past 7 days. I have removed and repaired it God knows how many times.
The second malfunctioning devices I moved away to the far away room, paired to the router (dongle E) and I managed to get it to work. 
It works for 5 days straight without any problems. It survived several restarts of Z2M, HA, and power losses. 

The remaining problematic module is in the same room with other 2 modules, which are _TZ3000_zirycpws. Those two work without problems, but the _Z3210_ol1uhvza that previously worked for months, is still problematic.

What I managed to conclude is that it is some kind of routing problem. I don't have enough knowledge of Z2M to be able to figure it out, but I made following observations:

When I turn off all the other QS modules (pull down the circuit breaker on them), and take the problematic module next to the coordinator, power it on without any load, and pair it, it works. I tested it for hours, giving it random positions via slider, and it made no issue at all. I could hear the relay clicking each time and the front-end reported correct position.
Once I installed it in a box, and brought back all the other modules online, it worked for some time, and than malfunctioned.

Any help on this appreciated. 

Thanks

**Comment by KipK** [comment]
I've experienced problem with TS130F modules for few monthes. Worked flawlessy for a year, then around September/October I think it started to behave strangely.

- need to send the open / close / set position 2 or 3 time to make it start. Not if it just has been controlled, it needs a few sec / mn to happend.
- sometime the position is stopped at 1% instead of 0 and then it's still reported as opened.
- can be reported as Open in HA, but Closed in z2m

I have crawled the git history and haven't found any visible reason for this. But it was definitively working 100% before last summer. 

Since, I have set up an HA automation that counter a bit this problem, but it brings new issues ( like sometime randomly opening or closing the curtain as it probably because it receives a state change for now reason  ) . Still better though.

```
alias: Store Entrée update state
description: ""
triggers:
  - trigger: state
    entity_id:
      - cover.store_entree
    attribute: current_position
conditions: []
actions:
  - variables:
      position: "{{ state_attr('cover.store_entree', 'current_position') }}"
  - delay:
      seconds: 5
  - repeat:
      while:
        - condition: template
          value_template: >-
            {{ state_attr('cover.store_entree', 'current_position') }} !=
            position
      sequence:
        - variables:
            position: "{{ state_attr('cover.store_entree', 'current_position') }}"
        - delay:
            seconds: 5
  - if:
      - condition: device
        device_id: 54a211f4b91140681f22284de3e9077b
        domain: cover
        entity_id: 385aa6ca6441b68973ca55742caa5083
        type: is_opening
      - condition: device
        device_id: 54a211f4b91140681f22284de3e9077b
        domain: cover
        entity_id: 385aa6ca6441b68973ca55742caa5083
        type: is_closing
    then: []
    else:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: |
            {{ position }}
        target:
          entity_id: cover.store_entree
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
  - if:
      - condition: device
        device_id: 54a211f4b91140681f22284de3e9077b
        domain: cover
        entity_id: 385aa6ca6441b68973ca55742caa5083
        type: is_opening
      - condition: device
        device_id: 54a211f4b91140681f22284de3e9077b
        domain: cover
        entity_id: 385aa6ca6441b68973ca55742caa5083
        type: is_closing
    then: []
    else:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: |
            {{ position }}
        target:
          entity_id: cover.store_entree
mode: restart

```
