### DISCUSSION TITLE
Issue with ConBee II and Zigbee2MQTT 2.0.0

### DISCUSSION THREAD

**Discussion by Pedro19891** [Koenkk/zigbee2mqtt#25934] [Devices]
Hello guys,

Last weekend I updated to new Zigbee2MQTT 2.0.0 and ran into problems.

Before it ran very smooth, but after the update, Zigbee2MQTT started, but seems not to recognize my Conbee II stick.

I see the following error in the logs:
[2025-01-21 21:05:27] debug:    zh:deconz:driver: send read device state from queue. seqNr: 21
[2025-01-21 21:05:27] debug:    zh:deconz:frameparser: device state: 10000000
[2025-01-21 21:05:27] debug:    zh:deconz:driver: networkstate: 0 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 0

I can run the WebUI, but cannot click on 'Permit Join'.

I don't know what goes wrong. There are no other Docker containers or services using the stick.

I already updated the firmware to the newest version, but without any result.
Also already removed the full directory with all config files in the zigbee2mqtt configuration folder.

What to do to solve this?

Running it in a Docker container on an Unraid (v7.0.0) server.
Also running Mosquitto and Home Assistant. Didn't change anything in these two, because it worked before the Z2M update.

See below the configuration file:

```
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.30.2:1883
  user: user_mqtt
  password: *******
serial:
  adapter: deconz
  port: /dev/ttyACM0
frontend:
  enabled: true
  port: 8080
advanced:
  permit_join: false
  channel: 25
  home-assistant_legacy_entity_attributes: false
  home_assistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
  last_seen: ISO_8601_local
``` 

UPDATE:
After removing the ConBee II stick, rebooting the server, a new issue appears:

Only these error lines ....
[2025-01-21 21:38:30] debug:    zh:deconz:driver: no free slots. Delay sending of APS Request

And today I got these errors when starting Z2M:
[2025-01-22 20:33:55] error:    z2m: Failed to call 'Bridge' 'start' (TypeError: Cannot read properties of undefined (reading 'getDevice')
    at Bridge.publishInfo (/app/lib/extension/bridge.ts:692:69)
    at Bridge.start (/app/lib/extension/bridge.ts:179:9)
    at Controller.callExtensions (/app/lib/controller.ts:368:17)
    at Controller.start (/app/lib/controller.ts:186:9)
    at start (/app/index.js:161:5))
[2025-01-22 20:33:55] info:     z2m: Started frontend on port 8080
[2025-01-22 20:33:55] error:    z2m: Failed to call 'HomeAssistant' 'start' (TypeError: Cannot read properties of undefined (reading 'deviceIeeeAddress')
    at HomeAssistant.getBridgeEntity (/app/lib/extension/homeassistant.ts:1918:78)
    at HomeAssistant.start (/app/lib/extension/homeassistant.ts:439:28)
    at Controller.callExtensions (/app/lib/controller.ts:368:17)
    at Controller.start (/app/lib/controller.ts:186:9)
    at start (/app/index.js:161:5))

Greetings Pedro
