### DISCUSSION TITLE
Z2M LXC Proxmox doesn't start

### DISCUSSION THREAD

**Discussion by Christophe64990** [Koenkk/zigbee2mqtt#26024] [General]
Hello, I am trying to install Z2M on LXC Proxmox and I cannot start it. I have the following error message and despite my searches, I cannot find it.
Could anyone help me?
Here is my configuration
Thanking you in advance

version: 4
homeassistant:
  enabled: false
frontend:
  port: 8081
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://'192.168.7.85:1883'
  user: user
  password: pw
  keepalive: 60
  reject_unauthorized: true

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
#   Specify valid 'adapter' and 'port' in your configuration.
#serial:
  #port: /dev/ttyACM0 #Uncomment for USB Port Method
  port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220813094657-if00
  adapter: ezsp
  rtscts: true

advanced:
  network_key:
    - 190
    - 134
    - 163
    - 31
    - 11
    - 120
    - 22
    - 102
    - 123
    - 255
    - 205
    - 55
    - 102
    - 115
    - 181
    - 75
  pan_id: 29884
  ext_pan_id:
    - 86
    - 13
    - 107
    - 217
    - 251
    - 134
    - 94
    - 46

**Comment by manuelkue** [comment]
Have you forwarded the Sonoff Zigbee stick correctly to the LXC? Have you followed the post install guide? See here: https://github.com/community-scripts/ProxmoxVE/discussions/410

Have you installed the LXC `privileged`?

---

As a sidenote: Please paste code samples as code so it can be read better (e.g. for detecting syntax errors)
You may even edit your description at the top and change the configuration sample to the code syntax. 
Use the three backticks notation

~~~
```
put your codesample here between the backticks
```
~~~

**Reply by Christophe64990** [reply]
Hi, Thank you for your answer
Yes i've LXC privileged installed and also the Sonoff Zigbee stick is correctly forwarded to the LXC. I've followed the post install guide.
I've done this twice 
I don't understand why i've this message : Refusing to start because configuration is not valid, found the following errors:
- mqtt/password must be string
Has you got another idea ?

**Comment by Christophe64990** [comment]
`version: 4
homeassistant:
  enabled: false
frontend:
  port: 8081
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://'192.168.7.85:1883'
  user: usr
  password: pw
  keepalive: 60
  reject_unauthorized: true

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
#   Specify valid 'adapter' and 'port' in your configuration.
#serial:
 # port: /dev/ttyACM0 #Uncomment for USB Port Method
  port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220813094657-if00
  adapter: ezsp
  rtscts: true

advanced:
  network_key:
    - 190
    - 134
    - 163
    - 31
    - 11
    - 120
    - 22
    - 102
    - 123
    - 255
    - 205
    - 55
    - 102
    - 115
    - 181
    - 75
  pan_id: 29884
  ext_pan_id:
    - 86
    - 13
    - 107
    - 217
    - 251
    - 134
    - 94
    - 46

`

**Reply by manuelkue** [reply]
Please use code formatting for this kind of text, as I've already mentioned in my last comment above ;-)

**Reply by Christophe64990** [reply]
Hi, sorry, i do it

**Comment by Christophe64990** [comment]
```
``version: 4
homeassistant:
  enabled: false
frontend:
  port: 8081
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.7.85:1883'
  user: usr
  password: pw
  keepalive: 60
  reject_unauthorized: true

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
#   Specify valid 'adapter' and 'port' in your configuration.
#serial:
 # port: /dev/ttyACM0 #Uncomment for USB Port Method
  port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220813094657-if00
  adapter: ezsp
  rtscts: true

advanced:
  network_key:
    - 190
    - 134
    - 163
    - 31
    - 11
    - 120
    - 22
    - 102
    - 123
    - 255
    - 205
    - 55
    - 102
    - 115
    - 181
    - 75
  pan_id: 29884
  ext_pan_id:
    - 86
    - 13
    - 107
    - 217
    - 251
    - 134
    - 94
    - 46

```
