### DISCUSSION TITLE
Can someone help me with the configuration?

### DISCUSSION THREAD

**Discussion by HAPSagan** [Koenkk/zigbee2mqtt#26151] [General]
Hi
I have been using zigbee2mqtt for a while and it has worked without any major problems. However, after updating to 2.0 I had to pair all the devices again. I thought I had done the necessary settings but apparently not. When I looked in my configuration.yaml for zigbee2mqtt I saw something strange but I don't know what I did wrong or how to fix it. I have a channel setting both under "advanced" and "device_options" I tried removing it under "device_options" but it comes back by itself. What did I do wrong and how do I fix it? Is there anything else I should change?
Thanks for the help! And apologies for my lack of knowledge. /Peter

```
homeassistant:
  enabled: true
advanced:
  channel: 25
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
  network_key:
    - 233
    - 104
    - 10
    - 96
    - 4
    - 123
    - 127
    - 235
    - 163
    - 165
    - 201
    - 39
    - 69
    - 185
    - 30
    - 86
  pan_id: 55021
  ext_pan_id:
    - 70
    - 162
    - 19
    - 156
    - 227
    - 224
    - 128
    - 173
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 20
mqtt:
  server: mqtt://core-mosquitto:1883
  user: xxxxxx
  password: xxxxxxxx
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2401728-if00
  adapter: deconz
devices:
  '0x54ef44100018c499':
    friendly_name: Sovrum taklampa Z2M
    state_action: true
```
