### DISCUSSION TITLE
pci-Silicon_Labs Adaptor from slae.sh

### DISCUSSION THREAD

**Discussion by jobabi** [Koenkk/zigbee2mqtt#26279] [Devices]
Hi,
just did an update to resolve a minor issue and nothing is working....
According what I found so far there was a major change in Adaptor setting.

Now what do I have to write in configuration.yaml for my adaptor ?
```

ls -l /dev/serial/by-id
lrwxrwxrwx 1 root root 13  9. Feb 13:10 pci-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_36_7C-if00-port0
lrwxrwxrwx 1 root root 13  9. Feb 13:10 usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_36_7C-if00-port0
```

currently I have:
```
serial:
  adapter: ember
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_36_7C-if00-port0
```

Thank you for support

**Comment by jobabi** [comment]
here is the error message:

Starting Zigbee2MQTT without watchdog.
[2025-02-09 15:05:26] error: 	z2m: Error while starting zigbee-herdsman
[2025-02-09 15:05:26] error: 	z2m: Failed to start zigbee-herdsman
[2025-02-09 15:05:26] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-02-09 15:05:26] error: 	z2m: Exiting...
[2025-02-09 15:05:26] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:670:19)
    at EmberAdapter.start (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1533:24)
    at Controller.start (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/controller/controller.ts:136:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:69:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:142:13)
    at start (/opt/zigbee2mqtt/index.js:161:5)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by chris-1243** [comment]
> slae.sh_cc2652rb_stick

You have a TI chip. 
```
serial:
  adapter: zstack
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_36_7C-if00-port0
```
