### DISCUSSION TITLE
z2m: MQTT failed to connect, exiting... (read ECONNRESET)

### DISCUSSION THREAD

**Discussion by palzkillm** [Koenkk/zigbee2mqtt#26369] [General]
Hello,

I guess I need help: I can not get Z2M to connect to Mosquitto, error Msg is "zigbee2mqtt  | [2025-02-14 22:21:19] error: 	z2m: MQTT failed to connect, exiting... (read ECONNRESET)". 

Mosquitto and Z2M are running from Docker Compose from OMV on a Raspi in a Network based on a FritzBox as DNS, individual port setting is enabled. 

Various Logs and Configs below. I am not experienced using Linux, so assume simple noob errors! 

Grateful for any suggestions,
Marco

### Z2M
 **Z2M Docker Compose Config:**
```
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ./data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            # Frontend port
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            # Make sure this matched your adapter location
            - /dev/ttyUSB0:/dev/ttyUSB0
```

**Z2M Docker Compose Log:**
```
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | [2025-02-14 22:21:15] info: 	z2m: Logging to console, file (filename: log.log)
zigbee2mqtt  | [2025-02-14 22:21:15] info: 	z2m: Starting Zigbee2MQTT version 2.1.1 (commit #1accb8b66b95b99658c50e4c0209edcb946a5fe2)
zigbee2mqtt  | [2025-02-14 22:21:15] info: 	z2m: Starting zigbee-herdsman (3.2.5)
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	zh:adapter:discovery: Matched adapter: {"path":"/dev/ttyUSB0","manufacturer":"ITead","serialNumber":"c2efe622ed6aef1181a499adc169b110","pnpId":"usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_c2efe622ed6aef1181a499adc169b110-if00-port0","vendorId":"10c4","productId":"ea60"} => zstack: path=/dev/ttyUSB0, score=4
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	zh:zstack:znp: Serialport opened
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	z2m: zigbee-herdsman started (resumed)
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	z2m: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	z2m: Currently 0 devices are joined.
zigbee2mqtt  | [2025-02-14 22:21:16] info: 	z2m: Connecting to MQTT server at mqtt://192.168.178.66:1883
zigbee2mqtt  | [2025-02-14 22:21:19] error: 	z2m: MQTT failed to connect, exiting... (read ECONNRESET)
zigbee2mqtt  | [2025-02-14 22:21:19] info: 	z2m: Stopping zigbee-herdsman...
```

**root@raspberrypi:/dockercompose/zigbee2mqtt/data# nano configuration.yaml**
```
  GNU nano 7.2                                                             configuration.yaml
version: 4
homeassistant:
  enabled: false
frontend:
  enabled: true
  host: 192.168.178.66
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.66:1883
  keepalive: 20
```

I have also tried:

**server: mqtt://localhost**
```
zigbee2mqtt  | [2025-02-14 22:27:19] info: 	z2m: Connecting to MQTT server at mqtt://localhost
zigbee2mqtt  | [2025-02-14 22:27:19] error: 	z2m: MQTT failed to connect, exiting... ()
```

 **server: mqtt://localhost:1883**
```
zigbee2mqtt  | [2025-02-14 22:26:13] info: 	z2m: Connecting to MQTT server at mqtt://localhost:1883
zigbee2mqtt  | [2025-02-14 22:26:13] error: 	z2m: MQTT failed to connect, exiting... ()
```

### Mosquitto
**Mosquitto Docker Compose file:**
```
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped

networks:
  default:
    name: mqtt5-network
```

**Mosquitto Docker Compose Log:**
```
mqtt5  | 1739561535: mosquitto version 2.0.20 starting
mqtt5  | 1739561535: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt5  | 1739561535: Starting in local only mode. Connections will only be possible from clients running on this machine.
mqtt5  | 1739561535: Create a configuration file which defines a listener to allow remote access.
mqtt5  | 1739561535: For more details see https://mosquitto.org/documentation/authentication-methods/
mqtt5  | 1739561535: Opening ipv4 listen socket on port 1883.
mqtt5  | 1739561535: Opening ipv6 listen socket on port 1883.
mqtt5  | 1739561535: mosquitto version 2.0.20 running
```

### Various Info
**root@raspberrypi:/dockercompose/zigbee2mqtt/data# netstat -tuplen**
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      0          505814     170690/docker-proxy
```
