### DISCUSSION TITLE
configuration.yaml and devices: devices.yaml

### DISCUSSION THREAD

**Discussion by Mark-Muc** [Koenkk/zigbee2mqtt#26540] [General]
Hello .. i'd like to outsource my devises to an own file like `devices.yaml`
It is decriped like: 
![image](https://github.com/user-attachments/assets/62c2d6f7-7fb6-4ecc-9419-d88bd737654b)
and I know it worked bevor version 2.xx.yy
I did the same in > ver 2.xx.yy i got an error looking like that:

```
[09:08:47] INFO: Socat not enabled
[09:08:47] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, node_assert_1.default)(result instanceof Object)
    at read (/app/lib/util/yaml.ts:24:15)
    at Object.readIfExists (/app/lib/util/yaml.ts:36:34)
    at readDevicesOrGroups (/app/lib/util/settings.ts:318:38)
    at read (/app/lib/util/settings.ts:326:5)
    at getPersistedSettings (/app/lib/util/settings.ts:394:21)
    at Object.reRead (/app/lib/util/settings.ts:641:5)
    at start (/app/index.js:130:14)

```
even i don't have any device added and try to build the construction in config.yaml with an empty devices.yaml
the error occurred. 
the files are Unix(LF) formatted.
Doesn't it work anymore?
Anyone have a clue, why it doesn't work anymore?
Thx for help!!

Mark-Muc

**Comment by chris-1243** [comment]
It is perfectly working on version 2.x

This what I use since my first start with this software

```
devices: devices.yaml
```

Your file must be in the same folder as your `configuration.yaml`

**Reply by Mark-Muc** [reply]
Thank u chris .. 
I tried again .. really 100% correct: `devices.yaml` in the same dir like `configuration.yaml`
in devices: `configuration.yaml` 
`devices: devices.yaml`
Still get:
```
[11:46:06] INFO: Preparing to start...
[11:46:06] INFO: Socat not enabled
[11:46:07] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, node_assert_1.default)(result instanceof Object)
    at read (/app/lib/util/yaml.ts:24:15)
    at Object.readIfExists (/app/lib/util/yaml.ts:36:34)
    at readDevicesOrGroups (/app/lib/util/settings.ts:318:38)
    at read (/app/lib/util/settings.ts:325:5)
    at getPersistedSettings (/app/lib/util/settings.ts:394:21)
    at Object.reRead (/app/lib/util/settings.ts:641:5)
    at start (/app/index.js:130:14)
```
I had it work befor 2.xx but now .. can't get it to work

Mark-Muc

**Reply by chris-1243** [reply]
Would you mind sharing your `configuration.yaml` ?

It might have a small error in it I guess. I'm running 2.1.3 and my devices list is in a separate file without issue

**Reply by Mark-Muc** [reply]
sure .. here it is:
Working:
```
version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 72
    - 247
    - 38
    - 197
    - 96
    - 19
    - 207
    - 187
    - 118
    - 31
    - 114
    - 60
    - 123
    - 112
    - 111
    - 137
  pan_id: 42138
  ext_pan_id:
    - 9
    - 237
    - 184
    - 153
    - 208
    - 236
    - 30
    - 7
  last_seen: ISO_8601_local
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aiphuu2Fe9ongahmai3airooTiem3ang5egheet1OoJ4que0qual0moojuj4ash5
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06Mg24_06bae9171c8bef11bc872bccef8776e9-if00-port0
  adapter: ember
  baudrate: 115200
  rtscts: false
devices:
  '0xa4c138e57a1c84e9':
    friendly_name: Test-Thermometer
  '0xa4c138ab99cd5b4a':
    friendly_name: Test-Thermostat

```
not working:
```
version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 72
    - 247
    - 38
    - 197
    - 96
    - 19
    - 207
    - 187
    - 118
    - 31
    - 114
    - 60
    - 123
    - 112
    - 111
    - 137
  pan_id: 42138
  ext_pan_id:
    - 9
    - 237
    - 184
    - 153
    - 208
    - 236
    - 30
    - 7
  last_seen: ISO_8601_local
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aiphuu2Fe9ongahmai3airooTiem3ang5egheet1OoJ4que0qual0moojuj4ash5
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06Mg24_06bae9171c8bef11bc872bccef8776e9-if00-port0
  adapter: ember
  baudrate: 115200
  rtscts: false

devices: devices.yaml
```
so nothing special ... that's my testinvironment

Thx
Mark-Muc
My config:
![image](https://github.com/user-attachments/assets/fc3653b3-33aa-4364-abde-839fe6921d8a)

**Comment by chris-1243** [comment]
And how does your `devices.yaml` look ?

**Reply by Mark-Muc** [reply]
it's simpy empty!!
sure i deleted all devices and stopped z2m .. then edit configuration.yaml (add devices: devices.yaml) and deleted the devices: []    line before starting z2m again
Mark-Muc

**Comment by chris-1243** [comment]
It should not be. The devices already paired should be in `devices.yaml`

```
'0xa4c138e57a1c84e9':
  friendly_name: Test-Thermometer
'0xa4c138ab99cd5b4a':
  friendly_name: Test-Thermostat
``` 

and your `configuration.yaml` should look

```
version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - 72
    - 247
    - 38
    - 197
    - 96
    - 19
    - 207
    - 187
    - 118
    - 31
    - 114
    - 60
    - 123
    - 112
    - 111
    - 137
  pan_id: 42138
  ext_pan_id:
    - 9
    - 237
    - 184
    - 153
    - 208
    - 236
    - 30
    - 7
  last_seen: ISO_8601_local
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aiphuu2Fe9ongahmai3airooTiem3ang5egheet1OoJ4que0qual0moojuj4ash5
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06Mg24_06bae9171c8bef11bc872bccef8776e9-if00-port0
  adapter: ember
  baudrate: 115200
  rtscts: false
devices: devices.yaml
``` 

I was able to reproduce your error on my test network. It happens as your `devices.yaml` is empty and you have paired devices
