### DISCUSSION TITLE
Interview fails for all IKEA E1746 repeaters after major version upgrade

### DISCUSSION THREAD

**Discussion by dhcgn** [Koenkk/zigbee2mqtt#26665] [Devices]
After upgrading Zigbee2MQTT from version 1.x to 2.1.3, all IKEA Zigbee repeaters (E1746) stopped functioning.

**Environment:**
- Zigbee2MQTT version: `2.1.3` (running via Docker)
- Host OS: Freshly installed Ubuntu machine
- Zigbee Coordinator Stick: `usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_4A_79-if00-port0`
- Coordinator Firmware: `CC2652RB_coordinator_20240710`

**Issue:**
- IKEA Zigbee repeaters (E1746) cannot be recognized or paired.
- The issue occurs with both previously paired devices and completely new ones.
- The IKEA E1746 repeater remains listed as supported: [[IKEA E1746 compatibility](https://www.zigbee2mqtt.io/devices/E1746.html)](https://www.zigbee2mqtt.io/devices/E1746.html).

**Error Log:**
```
z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of 'kueche_usb' (0x5c0272fffe71efcc) failed: Error: Interview failed because can not get node descriptor ('0x5c0272fffe71efcc')'
```

**Database Entry:**
```json
{"id":6,"type":"Unknown","ieeeAddr":"0x5c0272fffe71efcc","nwkAddr":6225,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1741454905293}
```

**Additional context:**
- Other Zigbee devices from different manufacturers operate normally after the upgrade.
- Screenshot shows:
  - 3 working devices
  - 2 IKEA E1746 repeaters showing identical states ("interview failed")

**Configuration:**
```yaml
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.3.10:1883
  advanced:
    output: attribute_and_json
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
  adapter: zstack
frontend:
  enabled: true
  port: 8080
  host: 0.0.0.0
advanced:
  pan_id: 44209
  ext_pan_id:
    - 20
    - 175
    - 162
    - 84
    - 61
    - 152
    - 94
    - 100
  channel: 11
  network_key:
    - ...
  output: attribute_and_json
device_options: {}
devices:
  '0xbc33acfffe7c32d4':
    friendly_name: dach_usb_technik
  '0x804b50fffe0a60a0':
    friendly_name: schlaf_sonnenblende_rechts
  '0xbc33acfffe59661b':
    friendly_name: schlaf_sonnenblende_links
  '0x00158d0004640c1d':
    friendly_name: '0x00158d0004640c1d'
  '0x5c0272fffe71efcc':
    friendly_name: kueche_usb
version: 4
```

Please let me know if further information or debugging steps are needed.
