### DISCUSSION TITLE
_TZE200_uiyqstza used to work with converter, but doesn't anymore (after an upgrade, I assume, but it's complicated - see below)

### DISCUSSION THREAD

**Discussion by louisnichols** [Koenkk/zigbee2mqtt#26963] [Devices]
Hi!

I have a few pieces of the model _TZE200_uiyqstza.

I had added them to z2m a few years ago with a custom js file and they worked.

Then I had some issues with my setup and had to leave it unmaintained for a year or more.

Now, I brought it back up and it has a new version of z2m, and this device is not recognized anymore. The `Exposes` tabs are empty. I've searched the forum and can't completely figure out how to solve this. I think it has something to do with the switch in config file versions, but I still can't solve it.

My configuration looked like this:
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyACM0
frontend: true
advanced:
  log_symlink_current: true
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00124b0024c83d2b':
    friendly_name: Sonoff_Router
  '0xec1bbdfffee4c479':
    friendly_name: Thermostat_Office_Zigbee
  '0xa4c1387c01ec0a60':
    friendly_name: Thermostat_Kitchen_Zigbee
  '0xa4c1383ffd4e597a':
    friendly_name: Thermostat_Living_Side_Zigbee
  '0xa4c138f2269496c6':
    friendly_name: Thermostat_Living_Front_Zigbee
external_converters:
  - lidl_radiator_valve.js
```
Where `lidl_radiator_valve.js` was under the `data` folder.

Now, after the most recent re-generation of configuration.yaml, the `external_converters` block is no longer there. I tried adding it, but still doesn't work. I tried placing the js file both under the `data` folder and under `data/external_converters/` but still nothing.

I will appreciate your help.
