### DISCUSSION TITLE
All devices offline, after they used to work

### DISCUSSION THREAD

**Discussion by louisnichols** [Koenkk/zigbee2mqtt#26971] [Devices]
Hi!

I was trying to solve an issue I have, and I created a bigger one.

My initial issue is here: https://github.com/Koenkk/zigbee2mqtt/discussions/26963 and I still don't know how to solve that.

However, while trying to fix it, I tried several things and one seems to have made things worse.

My initial docker-compose configuration looked like this (as made by IOTstack):
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    environment:
      - TZ=${TZ:-Etc/UTC}
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=zstack
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto:1883
      # only enable the next line for Zigbee2MQTT v1
      # - ZIGBEE2MQTT_CONFIG_FRONTEND=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_SYMLINK_CURRENT=true
      # - DEBUG=zigbee-herdsman*
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
    devices:
      - "${ZIGBEE2MQTT_DEVICE_PATH:?eg echo ZIGBEE2MQTT_DEVICE_PATH=/dev/ttyUSB0 >>~/IOTstack/.env}:/dev/ttyUSB0"
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
    - homestack_nw
```
But then I noticed the instructions here: https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose and I noticed that the repo is different and the devices section is... well, not really different, but I thought I should try.

So I changed my docker-compose to this:
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    environment:
      - TZ=${TZ:-Etc/UTC}
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=zstack
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto:1883
      # only enable the next line for Zigbee2MQTT v1
      # - ZIGBEE2MQTT_CONFIG_FRONTEND=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_SYMLINK_CURRENT=true
      # - DEBUG=zigbee-herdsman*
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
    devices:
      - "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_608950e5e75fec11a3ff365f25bfaa52-if00-port0:/dev/ttyUSB0"
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
    - homestack_nw
```

And after I did this and restarted z2m, all devices now appear offline, including the router.
(I ran `docker-compose down` and `docker-compose up -d` in each case, after modifying `docker-compose.yaml`)

Stranger thing is, I reverted `docker-compose.yaml` but the situation is still the same. I tried to unplug and replug the USB router, and I tried a reboot, but still the same.

The only thing that hasn't reverted is the z2m image.

So, with my initial config, I had version 2.1.3. After the change, I did a `docker pull` and it updated to 2.2. After the revert of config, the image is still 2.2. But I don't think that is the reason of the problem.

Any ideas?
