### DISCUSSION TITLE
SMLight not startin zin HA Z2M addon

### DISCUSSION THREAD

**Discussion by tonsemail** [Koenkk/zigbee2mqtt#27072] [Devices]
I have SLZB-06Mg24 and Z2M addon in HA. At the moment i have a sonoff dongle P running with z2m on another machine. Thats why you see zigbee2mqtt2 in the configuration. What is wrong?. I am running HA with a generic x86 installation
```
data_path: /config/zigbee2mqtt2
socat:
  enabled: true
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://192.168.123.31:1883
  user: xxxxxx
  password: xxxxxxx
  base_topic: zigbee2mqtt2
serial:
  serial:
    port: tcp://192.168.123.35:6638
    baudrate: 115200
    adapter: ember
    disable_led: false
    rtscts: false
  advanced:
    transmit_power: 20

The Log returns:
```
[18:10:04] INFO: Preparing to start...
[18:10:04] INFO: Socat enabled
[18:10:04] INFO: Starting socat
Socat startup parameters:
Options:     -d -d
Master:      pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
Slave:       tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
[18:10:04] INFO: Starting socat process ...
2025/04/10 18:10:04 socat[46] N PTY is /dev/pts/0
2025/04/10 18:10:04 socat[46] N listening on AF=2 0.0.0.0:8485
[18:10:05] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2025-04-10 18:10:07] info: 	z2m: Logging to console, file (filename: log.log)
[2025-04-10 18:10:08] info: 	z2m: Starting Zigbee2MQTT version 2.2.1 (commit #unknown)
[2025-04-10 18:10:08] info: 	z2m: Starting zigbee-herdsman (3.4.11)
[2025-04-10 18:10:08] info: 	zh:ember: Using default stack config.
[2025-04-10 18:10:08] info: 	zh:ember: ======== Ember Adapter Starting ========
[2025-04-10 18:10:08] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash: ASH COUNTERS since last clear:
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Total frames: RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Cancelled   : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   DATA frames : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   DATA bytes  : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Retry frames: RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   ACK frames  : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   NAK frames  : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   nRdy frames : RX=0, TX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   CRC errors      : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Comm errors     : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Length < minimum: RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Length > maximum: RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Bad controls    : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Bad lengths     : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Bad ACK numbers : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Out of buffers  : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Retry dupes     : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   Out of sequence : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash:   ACK timeouts    : RX=0
[2025-04-10 18:10:08] info: 	zh:ember:uart:ash: ======== ASH stopped ========
[2025-04-10 18:10:08] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: No such file or directory, cannot open port: tcp://192.168.123.35:6638
[2025-04-10 18:10:08] error: 	z2m: Error while starting zigbee-herdsman
[2025-04-10 18:10:08] error: 	z2m: Failed to start zigbee-herdsman
[2025-04-10 18:10:08] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-04-10 18:10:08] error: 	z2m: Exiting...
[2025-04-10 18:10:08] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/.pnpm/zigbee-herdsman@3.4.11/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:672:19)
    at EmberAdapter.start (/app/node_modules/.pnpm/zigbee-herdsman@3.4.11/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1538:24)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@3.4.11/node_modules/zigbee-herdsman/src/controller/controller.ts:136:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:104:13)
    at start (/app/index.js:149:5)
```
```
