### DISCUSSION TITLE
cc2530+cc2591 Not Joining

### DISCUSSION THREAD

**Discussion by FilipDem** [Koenkk/zigbee2mqtt#27134] [Devices]
I am already some days running in circles...
I have a Sonoff Zigbee 3.0 USB Plus Coordinator... As many of my devices are battery power, I want to add a router device (esp. to have coverage in the garden for a Sonoff Smart Valve. I use a cc2530+cc2591 and the [Create cc2530 router](https://www.zigbee2mqtt.io/advanced/zigbee/05_create_a_cc2530_router.html#flashing) procedure. As firmware I am using the [cc2530_cc2591_router_2020_09_29](https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_Home_1.2/bin/CC2530_CC2591_router_2020_09_29.zip), converted to a binary.
Flashing using a CCLoader with ESP8266 works perfectly from the first trial... 512 blocks and ended with "Programmed successfully"
"Permit Join (All)" is enabled in Zigbee3Mqtt.
However after flashing, the router does not join the network... Debug logs doesn't gave any indication.
I also used the "rejoined" procedure (on - 2s - off, 3 times and then on)... Not joining...
Reflashing... Same (negative) result.
Anyone with interesting insight?
Filip

**Comment by francisp2** [comment]
Should work. I have one on my network. Try pairing closer to the coordinator.  Or try a script
```
sequence:
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_on
  - delay:
      seconds: 2
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_off
  - delay:
      seconds: 2
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_on
  - delay:
      seconds: 1
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_off
  - delay:
      seconds: 2
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_on
  - delay:
      seconds: 1
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_off
  - delay:
      seconds: 2
  - data:
      entity_id: switch.ikeaoutlet1
    action: switch.turn_on

```
