### DISCUSSION TITLE
SLZB-06: SRSP - SYS - ping after 6000ms

### DISCUSSION THREAD

**Discussion by UltraBlackLinux** [Koenkk/zigbee2mqtt#27497] [Devices]
Hey there,
I just got my this SLZB-06 (with the CC2652P chip) because the wiki told me that it would work. I hooked it up over usb and set up a basic config, but all I'm getting is the error mentioned in the title.
This is my config:
```yaml
version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.63:8124
serial:
    port: /dev/ttyUSB0
    adapter: zstack
    disable_led: false
advanced:
  log_level: info
  transmit_power: 20

frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: false
```
I've tried every possible adapter option with no luck. The troubleshooting steps also didn't help me so far, although I didn't try an alternative firmware because I don't know if I can just flash any old non-smlight firmware on this thing.

any idea what I'm doing wrong?
Thanks!
