### DISCUSSION TITLE
First Configuration of Sonoff ZBDongle-E and ZigBee2MQTT goes wrong

### DISCUSSION THREAD

**Discussion by fraflora** [Koenkk/zigbee2mqtt#27597] [Devices]
Hi everyone,

I am totslly new to this word, and trying to set up my first ha configuration for new house. I want to base it on zigbee devices, so started from raspberry pi config based on docker and now trying to configurate the Sonoff ZBDongle-E (ZigBee 3.0 USB Dongle Plus) on it.
First I have installed the mosquitto container, and so far so good.
Next I have updated the dongle firmware, using darkxst (https://indomus.it/link/zbdongle-e-firmware-ncp-sw-flow-115200/) NCP coordinator version.
Finally, I have created the configuration.yaml:
```
serial:
  port: /dev/ttyUSB0
  adapter: ember
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://172.18.0.2:1883'
  user: francesco
  password: ***
  version: 5
  reject_unauthorized: true
  include_device_information: true
permit_join: false
frontend:
  port: 8080
homeassistant:
  legacy_triggers: false
  legacy_entity_attributes: false
ota:
  update_check_interval: 1440
  disable_automatic_update_check: false
availability:
  enabled: true
advanced:
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  channel: 19
  transmit_power: 20
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  log_namespaced_levels:
    z2m:mqtt: warning
```

and added the container to docker-compose yaml:
```
services:
  home_assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/pi/homeassistant_hub/homeassistant/config:/config
    - /home/pi/homeassistant_hub/homeassistant/media:/media
    - /run/dbus:/run/dbus:ro
    environment:
    - TZ=Europe/Rome
    - DISABLE_JEMALLOC=true
    network_mode: host
    restart: always
    privileged: true
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/srv/mosquitto/config:/mosquitto/config"
    - "/srv/mosquitto/log:/mosquitto/log"
    - "/srv/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "~/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyUSB0"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always
```

but, after compose it, in the log files I continue to recevie this errors:
```
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2025-06-02 17:47:59] info:     z2m: Logging to console, file (filename: log.log)
[2025-06-02 17:47:59] info:     z2m: Starting Zigbee2MQTT version 2.4.0 (commit #bdb94da46e0461337f4a61b4f2a6bfa5172f608f
)
[2025-06-02 17:47:59] info:     z2m: Starting zigbee-herdsman (4.1.0)
[2025-06-02 17:47:59] error:    z2m: Error while starting zigbee-herdsman
[2025-06-02 17:47:59] error:    z2m: Failed to start zigbee-herdsman
[2025-06-02 17:47:59] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-06-02 17:47:59] error:    z2m: Exiting...
[2025-06-02 17:47:59] error:    z2m: Error: USB adapter discovery error (No valid USB adapter found). Specify valid 'adapter' and 'port' in your configuration.
    at discoverAdapter (/app/node_modules/.pnpm/zigbee-herdsman@4.1.0/node_modules/zigbee-herdsman/src/adapter/adapterDiscovery.ts:589:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Function.create (/app/node_modules/.pnpm/zigbee-herdsman@4.1.0/node_modules/zigbee-herdsman/src/adapter/adapter.ts:53:33)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@4.1.0/node_modules/zigbee-herdsman/src/controller/controller.ts:129:24)
    at Zigbee.start (/app/lib/zigbee.ts:71:27)
    at Controller.start (/app/lib/controller.ts:102:13)
    at start (/app/index.js:149:5)
[2025-06-02 17:47:59] error:    z2m: If this happens after updating to Zigbee2MQTT 2.0.0, see https://github.com/Koenkk/zigbee2mqtt/discussions/24364
```

any suggestions?

**Comment by chris-1243** [comment]
What is the output of `ls -l /dev/serial/by-id` ?

**Reply by fraflora** [reply]
` total 0
lrwxrwxrwx 1 root root 13 Jun  2 18:15 usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_acc5b098094fef11916d51b3174bec31-if00-port0 -> ../../ttyUSB0`

**Comment by chris-1243** [comment]
In your compose.yaml I would go like this

```yaml
services:
  zigbee2mqtt: 
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - "~/zigbee2mqtt:/app/data"
    devices:
      - "/dev/serial/by-id/Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_acc5b098094fef11916d51b3174bec31-if00-port0:/dev/ttyUSB0"
    environment:
      - "TZ=Europe/Rome"
    network_mode: host
    restart: always
```
and your configuration.yaml

```yaml
serial:
  port: /dev/ttyUSB0
  adapter: ember
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://172.18.0.2:1883'
  user: francesco
  password: ***
  version: 5
  reject_unauthorized: true
  include_device_information: true
frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: true
ota:
  update_check_interval: 1440
  disable_automatic_update_check: false
availability:
  enabled: true
device_options:
  legacy: false
advanced:
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  channel: 19
  pan_id: GENERATE
  ext_pan_id: GENERATE
  network_key: GENERATE
  transmit_power: 20
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  #log_namespaced_levels: z2m:mqtt: warning # You will use this when everything is running
```

Please, use code blocks... much easier to read

**Comment by fraflora** [comment]
it seems like doesn't love devices provided in that form:
`Error response from daemon: error gathering device information while adding custom device "/dev/serial/by-id/Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_acc5b098094fef11916d51b3174bec31-if00-port0": no such file or directory`

**Comment by chris-1243** [comment]
My apologies... I found my mistake. It should not complain with this compose.yaml

```yaml
services:
  zigbee2mqtt: 
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - "~/zigbee2mqtt:/app/data"
    devices:
      - "/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_acc5b098094fef11916d51b3174bec31-if00-port0:/dev/ttyUSB0"
    environment:
      - "TZ=Europe/Rome"
    network_mode: host
    restart: always
```
