### DISCUSSION TITLE
Struggling with Zigbee2MQTT Upgrade

### DISCUSSION THREAD

**Discussion by Grizz952** [Koenkk/zigbee2mqtt#27807] [General]
Home Assistant (Cove 2025.2.5) running in Docker (27.5.1)/Ubuntu (24.04).  Also loaded; Portainer and Zigbee2mqtt (Z2M; 2.1.1).  Originally added Z2M (version 2.1.1) to my Home Assistant system in Feb.  Seeking now to upgrade to latest version (2.4?).  Upgrade attempted using docker-compose.yaml by following general instructions from several internet sources.

- Stop the existing container (docker stop zigbee2mqtt),
- Pull the latest image (docker pull koenkk/zigbee2mqtt:latest),
- Edit/update docker-compose.yaml file ( image: koenkk/zigbee2mqtt:latest), and
- Recreate the container with the updated image (docker-compose up -d).

This process (in my hands) failed to produce the upgrade.  Examination of zigbee2mqtt (in HA as well as in Portainer) shows version 2.1.1.  In addition, attempted to add lines to docker-compose.yaml to include frontend: (enabled: true; package: zigbee2mqtt-windfront).  This threw an immediate error indicating that 'frontend:' was not recognized.  I believe the process aborted before installing the upgrade, leaving me with 2.1.1.  Still very much a 'noob' to this technology.  What is the best way to upgrade Z2M?

**Comment by francisp2** [comment]
>attempted to add lines to docker-compose.yaml to include frontend: (enabled: true; package: zigbee2mqtt-windfront)

This does not go into your docker-compose.yaml, but in Zigbee2MQTt's configuration.yaml

Maybe show the contents of your docker-compose.yaml and Zigbee2MQTt's configuration.yaml

**Comment by Tee86** [comment]
~~> * Stop the existing container (docker stop zigbee2mqtt),~~
~~> * Pull the latest image (docker pull koenkk/zigbee2mqtt:latest),~~
~~> * Edit/update docker-compose.yaml file ( image: koenkk/zigbee2mqtt:latest), and~~
~~> * Recreate the container with the updated image (docker-compose up -d).~~

* Stop the existing container (docker stop zigbee2mqtt),
* Remove old container (docker rm zigbee2mqtt)
* Pull the latest image (docker pull koenkk/zigbee2mqtt:latest),
* ~~Edit/update docker-compose.yaml file ( image: koenkk/zigbee2mqtt:latest), and~~ I don't think this is needed. You need to update configuration.yaml in z2m data folder, not compose
* Recreate the container with the updated image (docker-compose up -d).

example compose:
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    volumes:
      - /home/t/zigbee2mqtt/data/configuration.yaml:/app/configuration.yaml
      - /home/t/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/London
      - DISABLE_TUYA_DEFAULT_RESPONSE=true
```
