### DISCUSSION TITLE
TERNCY-SD01

### DISCUSSION THREAD

**Discussion by bartplessers** [Koenkk/zigbee2mqtt#5682] [Devices]
Hi

I’m looking for a nice rotary controller. 

Till now, I only found TERNCY-SD01.
Can anybody point me to some simular devices?

Another question: the TERNCY-SD01 supports also double, tripple,... click actions. That seems nice, but on the other hand: this induces some latency: the sensor has to wait some fractions of a second before sending the message, otherwise it can not detect the double click. Altough that’s my experience with my Aqara wall switches...

Anybody experience with this kind of behavior on this device?

Are there somewhere some rotary dimmers with only following actions:
- turn left
- Turn right
- Single click

any feedback is appreciated

kind regards,
Bart

**Comment by 70MM13** [comment]
IKEA [Symfonisk sound controller](https://www.zigbee2mqtt.io/devices/E1744.html) comes to mind.
I don't have one yet... Also interested in the one you mentioned

regards

**Reply by bartplessers** [reply]
Nice! Thanx for the tip. Affordable and nice design. I will give it a try next time I'm IKEA.

**Reply by bartplessers** [reply]
Finally got an opportunity to go to IKEA.
The E1744 TRADFRI Symfonisk rocks!

Here is my automation
```
# =================================================
# CONTROLLER: 0x680ae2fffe3d52fb
# YOURLIGHT: my_n91_test_light_l08_testlamp
# =================================================

automation:
  ###########################################
  ## Toggle the light
  ###########################################
  - id: 0x680ae2fffe3d52fb_toggle
    alias: 0x680ae2fffe3d52fb_toggle
    trigger:
      - platform: state
        entity_id: sensor.0x680ae2fffe3d52fb_action
        to: "play_pause"
    condition:
    action:
      - data:
          entity_id: light.my_n91_test_light_l08_testlamp
        service: light.toggle

  ###########################################
  ## Dim up/down with rotation
  ###########################################
  - id: 0x680ae2fffe3d52fb_dim_up
    alias: 0x680ae2fffe3d52fb_dim_up
    trigger:
      platform: state
      entity_id: sensor.0x680ae2fffe3d52fb_action
      to: "rotate_right"
    action:
      data_template:
        entity_id: light.my_n91_test_light_l08_testlamp
        brightness: >
          {{ state_attr('sensor.0x680ae2fffe3d52fb_action','brightness')|int}}
      service: light.turn_on

  - id: 0x680ae2fffe3d52fb_dim_down
    alias: 0x680ae2fffe3d52fb_dim_down
    trigger:
      platform: state
      entity_id: sensor.0x680ae2fffe3d52fb_action
      to: rotate_left
    action:
      data_template:
        entity_id: light.my_n91_test_light_l08_testlamp
        brightness: >
          {{ state_attr('sensor.0x680ae2fffe3d52fb_action','brightness')|int }}
      service: light.turn_on

```

Nice hardware/software combination with great WAF (Wife Acceptance Factore).

grtz
B
