### DISCUSSION TITLE
zigbee2mqtt removing devices registered by other integrations

### DISCUSSION THREAD

**Discussion by peter-dolkens** [Koenkk/zigbee2mqtt#5783] [General]
I've attempted to manually register some devices in mqtt by publishing to `homeassistant/sensor/bedroom/iphone/config`

If zigbee2mqtt is running, it immediately removes the integration.

If I rename the topic to `homeassistant/sensor/bedroom_iphone/config` zigbee2mqtt leaves it alone.

Should this integration be touching config that isn't owned by itself?

**Comment by peter-dolkens** [comment]
If it helps - this config is to configure some `monitor.sh` sensors, and looks like this:

# homeassistant/sensor/bedroom/echoes/config

```
{
  "availability": [
    {
      "topic": "home/bedroom/status"
    }
  ],
  "device": {
    "identifiers": [
      "phone_apple_58e6ba3abad3"
    ],
    "manufacturer": "Apple",
    "model": "iPhone10,6",
    "name": "echoes",
    "sw_version": "14.3"
  },
  "device_class": "signal_strength",
  "name": "Signal Strength (Bedroom)",
  "state_topic": "home/bedroom/iphone_peter/rssi",
  "unique_id": "home_bedroom_iphone_peter_rssi",
  "unit_of_measurement": "dB"
}
```

and the culprit log line from zigbee2mqtt:

```
Jan 17 03:53:44 hallway-pi npm[28482]: Zigbee2MQTT:info  2021-01-17 03:53:44: MQTT publish: topic 'homeassistant/sensor/bedroom/echoes/config', payload 'null'
```

**Comment by Koenkk** [comment]
Can you provide your Zigbee2MQTT configuration.yaml?

**Reply by peter-dolkens** [reply]
I removed `network_key`, but otherwise:

```yaml
homeassistant: true
permit_join: false

mqtt:
  base_topic: home
  server: 'mqtt://mqtt-server.com'
  user: AzureDiamond
  password: Hunter2
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_49_B6-if00-port0
advanced:
  network_key: GENERATED

devices:
  '0x001788010801fe28':
    friendly_name: Kitchen Button
  '0x00178801080284e2':
    friendly_name: Front Hallway Button
  '0x001788010801be2f':
    friendly_name: Rear Hallway Button
  '0x001788010802abc2':
    friendly_name: Master Button
  '0x001788010802857a':
    friendly_name: Spare Room Button
  '0x0017880108663440':
    friendly_name: Front Hallway Sensor
  '0x00178801086636f7':
    friendly_name: Rear Hallway Sensor
  '0x0017880108664630':
    friendly_name: Kitchen Sensor
  '0x00178801091605f4':
    friendly_name: Lounge Sensor
  '0x0017880109162760':
    friendly_name: Bedroom Sensor
  '0x00178801091627d5':
    friendly_name: Spare Room Sensor
  '0x001788010872a1b4':
    friendly_name: Lounge Dimmer
  '0x001788010872a1c8':
    friendly_name: Bedroom Dimmer
  '0x0017880108db2551':
    friendly_name: Rear Hallway Light
  '0x0017880108c1a712':
    friendly_name: Front Hallway Light
  '0x0017880108daf33e':
    friendly_name: Kitchen Light
  '0x0017880108d97d51':
    friendly_name: Lounge Light
  '0x0017880108db2590':
    friendly_name: Bedroom Light
  '0x0017880108c1717a':
    friendly_name: Spare Room Light
```
