### DISCUSSION TITLE
Hue_Correction Issues

### DISCUSSION THREAD

**Discussion by RynoL37** [Koenkk/zigbee2mqtt#5994] [General]
I'm trying to get hue_correction setup properly and I finally got Z2M to load with my config changes, but when making changes I don't see the published color temp changing. I have 2 Gledopto GL-CL-008P that I am trying to get to match some other bulbs.

Here is what is now in my devices.yaml and the log snippet of botting up Z2M. I tried playing with different amounts of points to map across, but I can't seem to get it to work. The mired value I select in HA is sent as color_temp in the published mqtt. Any thoughts?

Devices.yaml:

```
'0xbc33acfffe8b7be7':
  friendly_name: 'oven_cabinet_lights_z2m'
  hue_correction:
        - in: 170
          out: 153
        - in: 200
          out: 200
        - in: 333
          out: 400
        - in: 370
          out: 460
        - in: 400
          out: 500
'0xbc33acfffe8b80e0':
  friendly_name: 'fridge_cabinet_lights_z2m'
  hue_correction:
        - in: 333
          out: 400
        - in: 370
          out: 460
        - in: 400
          out: 500
```

Z2M Log boot up, the last lines are valid, but I kept the device_options part for reference where it is on boot up.
`"device_options":{},"devices":{"0x00124b001f320764":{"friendly_name":"0x00124b001f320764"},"0x00158d0002904e05":{"friendly_name":"0x00158d0002904e05"},"0x00158d00040aa59f":{"friendly_name":"0x00158d00040aa59f"},"0x00158d00040be340":{"friendly_name":"0x00158d00040be340"},"0x00158d0004200b6d":{"friendly_name":"0x00158d0004200b6d"},"0x00158d000424a3be":{"friendly_name":"0x00158d000424a3be"},"0x00158d00042a111d":{"friendly_name":"0x00158d00042a111d"},"0x00158d00042ad90d":{"friendly_name":"0x00158d00042ad90d"},"0x00158d0004517f1f":{"friendly_name":"0x00158d0004517f1f"},"0x00158d0004518137":{"friendly_name":"0x00158d0004518137"},"0x14b457fffed781af":{"friendly_name":"0x14b457fffed781af"},"0xbc33acfffe8b7be7":{"friendly_name":"oven_cabinet_lights_z2m","hue_correction":[{"in":170,"out":153},{"in":200,"out":200},{"in":333,"out":400},{"in":370,"out":460},{"in":400,"out":500}]},"0xbc33acfffe8b80e0":{"friendly_name":"fridge_cabinet_lights_z2m","hue_correction":[{"in":333,"out":400},{"in":370,"out":460},{"in":400,"out":500}]},"`
