### DISCUSSION TITLE
more then two lights don't update state

### DISCUSSION THREAD

**Discussion by smulle48** [Koenkk/zigbee2mqtt#5998] [General]
Hi

I don't know if I'm the only one got this problem. I'm using an Conbee2 stick with z2m. If I create a group with more then 2 lights and bind a switch to the group, the state of the lights don't always update, unless I press the update button in the web frontend.

If I remove bulbs, so there are only 2 in the group, 99% of the time, the state is updated, but still not good enough. I don't know if the code request the state of the bulb/group too fast. At least I noticed with the IKEA LED1837R5 they take a bit longer to turn on then the IKEA LED1650R5.

All the lights, even more then two are turning on and off in the group, even if z2m are offline, so they all get the command. Do they automatically return an response? If so, why not listen to those responses and update the state when the response are returned?

It could also simply be my conbee2 that are crap :-D

**Comment by pavax** [comment]
I've got the exact same setup (Conbee2, z2m) . I've got several zigbee groups that consist of several ikea based lights. (in the same group are always the same kind of lights). I've also got different remotes (5Btn / 2Btn). The very same problem can be found in various constellations.  I also played around with the `retrieve_state` attribute (set to true) on the devices and/or the groups - without luck though.... 



Remotes: E1524/E1810, E1743
Lights:  LED1537R6/LED1739R5, L1529, LED1837R5 

**Z2M Groups:**
```
'4':
  friendly_name: Esstisch
  devices:
    - 0x5c0272fffe9d957d/1
    - 0x5c0272fffe9f261e/1
    - 0x5c0272fffea29e52/1
```

**Z2M Binding for the Remote:**

Source Ep | Destination |  Clusters
------------ | ------------- | -------------
1 | Coordinator | PowerCfg 
1 | Esstisch | OnOff/LevelCtrl


**Current Workaround/Hack**
several seconds after I press the toggle button (on the 5-Btn-Remote) or the on-off button (on the 2-Btn-Remote) I'm going to fetch the current value of every light associated with that group.  Eventually the state of the group also changes in z2m after some seconds... I guess that it works like the `retrieve_state` on z2m but with a longer delay (3sec) in my case

**Home-Assitant Automation:**
```
alias: '[zigbee] sync  esstisch '
description: ''
use_blueprint:
  path: custom/z2m-ikea-remote-controls.yaml
  input:
    remote: sensor.esstisch_remote_action
    toggle:
      - delay: '00:00:03'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 01/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 02/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 03/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
```

 Blueprint: https://gist.github.com/pavax/32581f0d4ed860264159df1d79d8c849
