### DISCUSSION TITLE
HomeAssistant: recommended trigger handling

### DISCUSSION THREAD

**Discussion by lazyoldbear** [Koenkk/zigbee2mqtt#6013] [General]
The documentation [recommends MQTT device triggers](https://www.zigbee2mqtt.io/integration/home_assistant.html#via-mqtt-device-trigger-recommended) above all. 
This works fine, but creates a number of [inconveniences in Home Assistant](https://community.home-assistant.io/t/device-triggers-from-zigbee2mqtt-vs-mqtt-listen-and-sometimes-a-bit-about-blueprints/270023/14). States are much easier in integrations, and are more consistent with other devices (ZWaveJS2MQTT and other things). 

The question is: why are MQTT device triggers actually recommended and what bad would there be with using states (e.g. added delays or formidable performance impact)?

**Comment by silvanverschuur** [comment]
The only advantage I can think of is that with MQTT device triggers you don't have to worry about state changes. Suppose you have a Zigbee device (button?) that sends a 'click' command. The first time you press the button, the state attribute changes to 'click'. A second click won't change the state. Z2M has a workaround for this problem, it sends a message to 'clear' the state after the first click. This workaround causes some delay and issues when pressing the button multiple times during a short period of time.

The biggest problem with using MQTT devices triggers in HA is that you cannot use the new Blueprint feature for these events. All Blueprints out there are based on a state changes of an attribute.

Another big issue with MQTT device triggers is that you cannot add them manually to a YAML automation file (because you don't know the device / discovery id's). You have to set it up using the UI and copy/paste the generated YAML code into your own file.

**Reply by ristomatti** [reply]
> The biggest problem with using MQTT devices triggers in HA is that you cannot use the new Blueprint feature for these events. All Blueprints out there are based on a state changes of an attribute.

@silvanverschuur I've used Z2M for quite a while with Node-RED and I have recently been experimenting with HA. I've already painfully figured out what you say here. Do you know if the Blueprints feature inherently does not support triggers or is the problem just the currently existing Blueprints?

They seem handy but if they're also buggy with the legacy triggers, I'd rather look into creating my own Blueprints using device triggers. So I'd appreciate to know if I'd be just wasting my time trying to make them work before I dig into the topic. There clearly seems to be a learning curve involved. 🙂

**Comment by silvanverschuur** [comment]
@ristomatti 
I've never seen anyone using MQTT device triggers in blueprints so I'm not sure if it's possible. I have tried it some time ago but did not manage to get it working. 

But maybe you can give it a try and post an example if you succeed :-)

**Reply by ristomatti** [reply]
@silvanverschuur Hold my beer! (...for a couple of months)

**Comment by timdonovanuk** [comment]
I'd love to know how to handle the new [MQTT device trigger](https://www.home-assistant.io/integrations/device_trigger.mqtt/) in node-red. A google search returns zero on this topic. I've tried multiple ways but ended up reverting to legacy triggers because they actually make sense.

**Reply by Daniel15** [reply]
For Node-RED, you don't need it. Just use the standard "mqtt in" node.

**Reply by ristomatti** [reply]
If you're looking for automatic discovery of of the Zigbee2MQTT connected devices similarly as from Home Assistant nodes give you, check if https://flows.nodered.org/node/node-red-contrib-zigbee2mqtt can do this. IIRC it can.

**Reply by timdonovanuk** [reply]
Hmm thank you! In my opinion however the correct paradigm is to always use Home Assistant as the state machine. It should be the central place to track and react to state changes. I get from a technical point of view I'm just being picky, but the slippery slope from what you're suggesting is: lets ditch HA integration entirely in place of NR with mqtt triggers. 

So for now....legacy triggers!

**Reply by Daniel15** [reply]
@timdonovanuk 

> use Home Assistant as the state machine. It should be the central place to track and react to state changes.

Triggers aren't state though, and it doesn't really make sense to refer to them as such. State is something that makes sense to persist and read at any time (eg "is the light currently on?") whereas events occur at a single point in time (eg clicking a button) and don't make sense to persist beyond that. Events modify the state of the state machine, but they're not part of the state contained within.

**Reply by timdonovanuk** [reply]
But a change of state is what causes something to trigger...anyway I'm not looking to get too academic about it I guess :)

I have a second more compelling reason: HA effectively acts as an API gateway. Hardware changes quite frequently and who knows if the next device will support MQTT. Adding MQTT triggers to NR introduces yet more complexity (subjective whether it's small or big). It's far more elegant and cleaner to use HA as the central place for monitoring state changes and interacting with hardware. 

Using MQTT directly feels like a shortcut to some degree. 

An besides, the slippery slope is still there. Why bother using HA at all - rather than calling light services in HA we could just interact directly with our zigbee bulbs via NR MQTT calls.

**Reply by ristomatti** [reply]
I've spent so much time trying to get this to work the HA way. MQTT is just way more reliable then the legacy trigger nonsense. Sluggy to react and button pressed get missed. I highly recommend using the Zigbee2QMTT Node-RED node for now.

It's not really linked to Node-RED but you might still want to check [Home Assistant Switch Manager](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager). It can handle device triggers quite nicely and supports blueprints of it's own.

**Reply by WizBangCrash** [reply]
I recently (last week) moved to Z2M after loosing faith in ZHA. I was blissfully unaware of the MQTT device triggers and after spending the day switching all my devices over to Z2M I found that my blueprints would no longer work because I couldn't trigger them :-(

I came up with the following workaround and thought I'd share as I did not want to use legacy triggers.

My blueprints are now triggered from custom events that are sent from automations linked to the Z2M devices. I think it is easier to show by example, so see below.
I have a single blueprint for light control that used to be triggered from ZHA events, but I have now changed it to be triggered from custom events.
I create an automation that is linked to the Z2M device and send custom events based on what triggered the Z2M device.
I set the `automation_entity_id` in the blueprint to the Z2M device automation.
Bingo! Now I can have the bulk of my automation stored in a Blueprint and use a device specific automation to trigger the blueprint.
It's not ideal, but it was the cleanest way I could think of to overcome the HA/Z2M shortcoming.

Here is an example blueprint:
```yaml
#
# In order to overcome the fact that it is impossible to determine the
# discovery_id from a mqtt device_id to use MQTT device triggers
# This Blueprint that can be triggered by a custom trigger fired
# in a MQTT device trigger
#
# The custom trigger uses the following format:
#
# - event: blueprint_trigger
#   event_data:
#     automation_entity_id: "{{ this.entity_id }}"
#     button_press: single | double | single_on | single_off | double_on | double_off | up | down
#
# The custom event is fired from within an automation linked to the MQTT device,
# or anything else e.g. ZHA device, script etc.

blueprint:
  name: MQTT device triggers test
  domain: automation
  input:
    automation_entity_id:
      name: Triggering Automation
      description: Select the automation defining the remote button(s) that will trigger this automation
      selector:
        entity:
          domain: automation
    light_entity_id:
      name: Light
      description: The light to be controlled
      selector:
        entity:
          domain: light
#
# The automation
#

# Trigger mode
mode: queued

# Traces to store
trace:
  stored_traces: 20

trigger:
# Remote
  - platform: event
    id: button_press
    event_type: blueprint_trigger
    event_data:
      automation_entity_id: !input automation_entity_id

# Actions
action:
  - choose:
      - alias: "Light on request"
        conditions:
          - "{{ trigger.id == 'button_press' and trigger.event.data.button_press.endswith('_on') }}"
        sequence:
          - if:
              - alias: "single_on or double_on"
                condition: template
                value_template: "{{ trigger.event.data.button_press == 'single_on' }}"
            then:
              - alias: "single press to turn on lights specified brightness"
                service: light.turn_on
                entity_id: !input light_entity_id
            else:
              - alias: "double press to turn on lights full brightness"
                service: light.turn_on
                entity_id: !input light_entity_id
                data:
                  brightness_pct: 100
                  color_temp_kelvin: 3950

      - alias: "Light off request"
        conditions:
          - "{{ trigger.id == 'button_press' and trigger.event.data.button_press.endswith('_off') }}"
        sequence:
          - alias: "Turn off light(s)"
            service: light.turn_off
            entity_id: !input light_entity_id

      - alias: "Light toggle request from {{trigger.id}}"
        conditions:
          - "{{ trigger.id == 'button_press' and trigger.event.data.button_press == 'single' }}"
        sequence:
          - alias: Toggle light & killswitch state
            if:
              - condition: state
                entity_id: !input light_entity_id
                state: 'off'
            then:
              - service: light.turn_on
                entity_id: !input light_entity_id
                data:
                  brightness_pct: 100
            else:
              - service: light.turn_off
                entity_id: !input light_entity_id

    default: []
```


and here is an automation linked to the device:
```yaml
alias: Office Light Switch
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 91e6ed6d0c09b46c9798202b55617a00
    type: action
    subtype: button_1_single
    discovery_id: 0x04cf8cdf3c7c3278 action_button_1_single
    id: turn_on
  - platform: device
    domain: mqtt
    device_id: 91e6ed6d0c09b46c9798202b55617a00
    type: action
    subtype: button_2_single
    discovery_id: 0x04cf8cdf3c7c3278 action_button_2_single
    id: turn_off
  - platform: device
    domain: mqtt
    device_id: 91e6ed6d0c09b46c9798202b55617a00
    type: action
    subtype: button_1_double
    discovery_id: 0x04cf8cdf3c7c3278 action_button_1_double
    id: double_on
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - event: blueprint_trigger
            event_data:
              automation_entity_id: "{{ this.entity_id }}"
              button_press: single_on
      - conditions:
          - condition: trigger
            id: double_on
        sequence:
          - event: blueprint_trigger
            event_data:
              automation_entity_id: "{{ this.entity_id }}"
              button_press: double_on
      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - event: blueprint_trigger
            event_data:
              automation_entity_id: "{{ this.entity_id }}"
              button_press: single_off
mode: single
```

**Reply by qraynaud** [reply]
@WizBangCrash that’s an awesome take there.

I found that even though MQTT device trigger is the recommended way, it’s not good enough. Duplicating your first automation for each switch is a bother.
Using states is a bad idea. I succeeded in making blueprints with those, but multiple clicks can be mistaken as one. Sometimes state changes are too quick and don’t trigger the associated automation for an unknow reason. So it’s not a reliable way to automate anything.
MQTT topics are fine though. They are not very different from MQTT device triggers. They work as intended. And it’s possible to automate them using blueprints from start to finish.

If you match the HA name and the zigbee2mqtt name, I made this easy to use blueprint to bind in a similar way you did an aqara switch to a « normal » event:
```yaml
blueprint:
  name: Bind MQTT Aqara Switch
  domain: automation
  input:
    device:
      name: Switch to bind
      selector:
        device:
          entity:
            domain: switch
    name:
      name: Copier et coller le nom du switch ici

mode: single

trigger_variables:
  name: !input name

trigger:
- platform: mqtt
  topic: "zigbee2mqtt/{{name}}/action"

condition: []

variables:
  device: !input device

action:
- event: mqtt-bind
  event_data:
    device_id: "{{ device }}"
    action: "{{ trigger.payload }}"
```

Here is a sample blueprint I use to match the events coming from my aqara switches to switch on/off other switches:
```yaml
blueprint:
  name: Allume/éteint un (des) switch(s) avec un interrupteur MQTT bindé
  domain: automation
  input:
    device:
      name: Interrupteur
      selector:
        device:
          entity:
            domain: switch
    action:
      name: Évènement à binder
      selector:
        select:
          options:
          - label: Clic simple
            value: single
          - label: Clic double
            value: double
          - label: Clic simple à gauche
            value: single_left
          - label: Clic double à gauche
            value: double_left
          - label: Clic simple à droite
            value: single_right
          - label: Clic double à droite
            value: double_right
    target:
      name: Cible
      selector:
        target:
          entity:
            domain: switch

trigger_variables:
  action: !input action

trigger:
- platform: event
  event_type: mqtt-bind
  event_data:
    device_id: !input device
    action: "{{ action }}"

condition: []

action:
- service: switch.toggle
  target: !input target
```

Those are similar to yours. Pretty straightforward.
