### DISCUSSION TITLE
How do the 'delta' and 'interval' variable of 'simulated brightness' work?

### DISCUSSION THREAD

**Discussion by flatsiedatsie** [Koenkk/zigbee2mqtt#6091] [Devices]
I'm trying to understand how to fine-tune the `simulated_brightness` feature.

On device pages it says there are two things that can be changed:

- delta: 20 # delta per interval, default = 20
- interval: 200 # interval in milliseconds, default = 200

I've tried changing these with the goal of getting the simulated brightness to change less quickly. I've tried setting delta to 1, or interval to 2000. But I'm not really noticing any significant changes. Could someone explain exactly how these values should be changes to get the value to change much more slowly?

**Comment by flatsiedatsie** [comment]
Answered my own question:

This gave good slow results:

```
device_options:
  simulated_brightness:
    delta: 2
    interval: 100
```

**Reply by miguelalfayate** [reply]
Wow I am still trying to wrap my mind around this. I have an [Ikea light switch](https://www.zigbee2mqtt.io/devices/E1743.html) with this functionality and I can't make it work for the life of me.
As I understand I need to add this lines to the configuration.yaml file:

```
device_options:
  simulated_brightness:
    delta: 2
    interval: 100
```

In my case looks something like this:

```
'0x5c0272fffexxxxxxx':
  friendly_name: light_dimmer
    legacy: false
    device_options:
      simulated_brightness:
        delta: 2
        interval: 100
```
Then what happens? How does these changes affect the functioning of the dimmer?

**Reply by knallhare** [reply]
Not sure if you are still struggeling with this issue Miguel, but for info to all of you guys trying to wrap your head around this, here is what I have figured out.

So I basically added this to the devices.yaml file under the zigbee2mqtt folder (not the Home Assistant devices.yaml one):
```
'0x000d6f000fd85946':
  friendly_name: dim1
  simulated_brightness:
    delta: 2
    interval: 100
```
After a reboot, your dimmer should have a brightness value which you can use to send in a payload. Here is my json string which shows the brightness of the dimmer:
```
{{ states.sensor.dim1_action.attributes.brightness }}
```

**Reply by miguelalfayate** [reply]
Hi, Thank you for your reply. I haven't got time to tinker with my IOT setup up until now. As you very well point out in your message those values added in the yaml file do just as expected and I have already integrated it my own setup.

Best wishes.

**Reply by rrakso** [reply]
[Remember](https://github.com/Koenkk/zigbee2mqtt/issues/13981#issuecomment-2160822953) to set [`legacy_entity_attributes`](https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html#advanced-configuration) to `true` (I had it set to `false` and did not see the brightness attribute).

![image](https://github.com/user-attachments/assets/abe6e864-23b0-4464-b783-7781ac7bc252)

**Comment by simondid** [comment]
any one that can post a full yaml for the button setup that works getting error when using the sates attribues 

`expected int for dictionary value @ data['brightness']. Got None`

**Comment by flatsiedatsie** [comment]
No problem

```
homeassistant: false
permit_join: false
devices: devices.yaml
groups: groups.yaml
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyUSB0
availability:
  active:
    timeout: 3
  passive:
    timeout: 1500
ota:
  update_check_interval: 2880
advanced:
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  last_seen: 'epoch'
  pan_id: REDACTED
  network_key: [REDACTED]
  legacy_api: false
device_options:
  debounce: .1
  legacy: false
  measurement_poll_interval: 10
  filtered_attributes: ['Action group', 'Action rate', 'xy']
  simulated_brightness:
    delta: 2
    interval: 100
```

(the rest is in a separate groups.yaml and devices.yaml)
