### DISCUSSION TITLE
Lock Capabilities - reason for lock/unlock?

### DISCUSSION THREAD

**Discussion by wixoff** [Koenkk/zigbee2mqtt#6181] [Devices]
I have a Kwikset 914 SmartCode deadbolt - it's a Z-Wave Plus unit that works - usually - pretty well with the Home Assistant built-in OZW integration.  It can be locked or unlocked, it shows status, and it provides information about **HOW** it was locked (manually/key, or remotely, or via keypad), or unlocked (manually/key, or remotely, or which "user code" was entered into the keypad).

While the Z-Wave integration has these capabilities, the reliability leaves much to be desired.

This is a supported lock in Z2M, so I gave it a brain transplant - swapped out the Z-Wave board and installed the compatible Zigbee board.  This works fine - it joined easily, and it shows up as a Weiser SmartCode 10, which I gather is basically the same lock.  Lock and Unlock operations work great - quickly and reliably, and the status appears accurate.

But unfortunately I lose the ancillary attributes: specifically, the reason for a lock/unlock doesn't seem to be available.  I can't tell which user code was used, or whether it was locked/unlocked manually.  This would be nice to have!

Is there any prospect to get this data?  I don't see any lock in Z2M that publishes it.

**Comment by wixoff** [comment]
Answering my own question - the data is there!  With a caveat.

There are four values that can be turned into sensors - `action`, `action_source`, `action_source_name`, and `action_user`.  An MQTT sensor in Home Assistant like this works:

```
  - platform: mqtt
    availability:
      - topic: zigbee2mqtt/bridge/state
    device:
      identifiers:
        - zigbee2mqtt_0x002XXXXXXXXXXXXX
      manufacturer: Weiser
      model: SmartCode 10 (9GED18000-009)
      name: '0x002XXXXXXXXXXXXX'
    name: 0x002XXXXXXXXXXXXX action
    state_topic: zigbee2mqtt/0x002XXXXXXXXXXXXX
    unique_id: 0x002XXXXXXXXXXXXX_action_zigbee2mqtt
    value_template: '{{ value_json.action }}'
```

BUT it gets overwritten practically instantly.  The MQTT message with a valid `action` in it is followed, in a short fraction of a second, with another message with '' (i.e. blank) as the `action`.  Here is a sample message sequence (from the HA MQTT integration's device debugger):

```

Received 12:43:04 PM

    QoS: 0
    Payload:

    action: manual_unlock
    action_source: 2
    action_source_name: manual
    action_user: 65535
    battery: 100
    linkquality: 165
    lock_state: locked
    state: LOCK

Received 12:43:04 PM

    QoS: 0
    Payload:

    action: ''
    battery: 100
    linkquality: 165
    lock_state: locked
    state: LOCK

Received 12:43:09 PM

    QoS: 0
    Payload:

    battery: 100
    linkquality: 165
    lock_state: unlocked
    state: UNLOCK

Received 12:43:21 PM

    QoS: 0
    Payload:

    action: manual_lock
    action_source: 2
    action_source_name: manual
    action_user: 65535
    battery: 100
    linkquality: 165
    lock_state: locked
    state: LOCK

Received 12:43:21 PM

    QoS: 0
    Payload:

    action: ''
    battery: 100
    linkquality: 165
    lock_state: locked
    state: LOCK

```

The `action`, `action_source`, `action_source_name`, and `action_user` vanish practically instantly, and debounce doesn't seem to help.  So to get these sensor values into the UI to show the most recent action, I need to use automations to grab them and put them into an input_text.  Not optimal!

Does anyone have a better solution?

**Comment by charettepa** [comment]
Have you found a solution
I have the same concers
I am Also new to zigbee2mqtt coming from zwavejs
I am keeping ZJS but as you stated the reliability of the lock is not great

I too am used to being able to extract all the messages
there is a big difference between locked, locked manually, locked by keypad
in this case action source seems to handle it but is not consistantly exposed

seems strange that in the documented exposed values it only lists lock state, battery, linkquality
have you found a solution to this, is the data now exposed?
I have not yet bought a zigbee lock as the lack of avilable data concerns me

**Comment by wixoff** [comment]
A year later and I'm still using the same solution.  It looks like this, for one of my locks.

First, the sensors:

```yaml
  - platform: mqtt
    availability:
      - topic: zigbee2mqtt/bridge/state
    device:
      identifiers:
        - zigbee2mqtt_0x002446xxxxxxxxxx
      manufacturer: Weiser
      model: SmartCode 10 (9GED18000-009)
      name: '0x002446xxxxxxxxxx'
    name: Front Door Lock Action
    state_topic: zigbee2mqtt/0x002446xxxxxxxxxx
    unique_id: 0x002446xxxxxxxxxx_action_zigbee2mqtt
    value_template: '{{ value_json.action }}'

  - platform: mqtt
    availability:
      - topic: zigbee2mqtt/bridge/state
    device:
      identifiers:
        - zigbee2mqtt_0x002446xxxxxxxxxx
      manufacturer: Weiser
      model: SmartCode 10 (9GED18000-009)
      name: '0x002446xxxxxxxxxx'
    name: Front Door Lock Action Source Name
    state_topic: zigbee2mqtt/0x002446xxxxxxxxxx
    unique_id: 0x002446xxxxxxxxxx_action_source_name_zigbee2mqtt
    value_template: '{{ value_json.action_source_name }}'

  - platform: mqtt
    availability:
      - topic: zigbee2mqtt/bridge/state
    device:
      identifiers:
        - zigbee2mqtt_0x002446xxxxxxxxxx
      manufacturer: Weiser
      model: SmartCode 10 (9GED18000-009)
      name: '0x002446xxxxxxxxxx'
    name: Front Door Lock Action User
    state_topic: zigbee2mqtt/0x002446xxxxxxxxxx
    unique_id: 0x002446xxxxxxxxxx_action_user_zigbee2mqtt
    value_template: '{{ value_json.action_user }}'
```

Then the corresponding automations to set input_text values:

```yaml
  - alias: Front Door Action Update
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_action
    condition: "{{ trigger.to_state.state != '' }}"
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.front_door_action
          value: "{{ trigger.to_state.state }}"

  - alias: Front Door Source Update
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_action_source_name
    condition: "{{ trigger.to_state.state != '' }}"
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.front_door_action_source_name
          value: "{{ trigger.to_state.state }}"

  - alias: Front Door User Update
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_action_user
    condition: "{{ trigger.to_state.state != '' }}"
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.front_door_action_user
          value: "{{ trigger.to_state.state }}"
```

The automations take those transient MQTT values (which get wiped out immediately) and turn them into something persistent that can be used for display in Lovelace or for subsequent automation conditions, that kind of thing.

This all still works great - very reliable, and I'm entirely happy with how it works compared to my old Z-wave setup.
