### DISCUSSION TITLE
z2m crash!

### DISCUSSION THREAD

**Discussion by bartve66** [Koenkk/zigbee2mqtt#6362] [General]
I run zigbee2mqtt as an add on  in home assistant (rpi / docker), all recent updates applied.
Everything was working fine, but because I added/paired some Tradfri light bulbs, and z2m did not pick up the friendly name I entered in HA I rebooted the rpi.
After that z2m did not start up correctly, this is the part of the log that keeps repeating:
```
[10:35:34] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
Zigbee2MQTT:info  2021-02-19 10:35:40: Logging to console and directory: '/share/zigbee2mqtt/log/2021-02-19.10-35-38' filename: log.txt
Zigbee2MQTT:info  2021-02-19 10:35:40: Starting Zigbee2MQTT version 1.17.1 (commit #1.17.1)
Zigbee2MQTT:info  2021-02-19 10:35:40: Starting zigbee-herdsman (0.13.59)
Zigbee2MQTT:error 2021-02-19 10:36:00: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-19 10:36:00: Failed to start zigbee
Zigbee2MQTT:error 2021-02-19 10:36:00: Exiting...
Zigbee2MQTT:error 2021-02-19 10:36:00: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-19T09_36_00_373Z-debug.log
```
As it says 'Error: Failed to connect to the adapter' I disconnected and connected the adapter (ZZH) and I logged in on the rpi with ssh and 'lsusb' shows the adapter just fine. Then I restarted z2m (no result) and rebooted the system again (no result). That's about as far as my expertise reaches, any thoughts?

This is my z2m config file:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: [...]
  password: [...]
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
