### DISCUSSION TITLE
Plan to support Lidl/Silvercrest HG06339 gateway

### DISCUSSION THREAD

**Discussion by snakesrules94** [Koenkk/zigbee2mqtt#6414] [Devices]
Hi there , is there some plan to support this gateway in zigbee2mqtt ? Now that a hack is exposed for this gateway and integration in HA is working , could be interresting to have it directly in Zigbee2mqtt.

Regards,

**Comment by gipnokote** [comment]
It actually works well with zigbee2mqtt.
Here is my docker compose file:

```version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
```

Please note that in the case of this gateway the `devices:` part is not needed, because we are not mapping any hardware ports.
Also note that the `network_mode: host` is important to have. The actual network serial port will be referenced directly in the zigbee2mqtt configuration file. Here it is:

```homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: username
  password: strongpassword
  include_device_information: true
frontend:
  port: 8080
serial:
  adapter: ezsp
  port: tcp://192.168.1.100:8888
```

The `port:` has the IP of the SilverCrest gateway. `adapter: ezsp` is very important too. MQTT `server:` in my case is `localhost` because mosquitto runs in another container within same host machine. `network_mode: host` in the docker compose file above directly affects what localhost is in this configuration file.

Please also make sure you update the EZSP version on the gateway as described [on this page](https://zigbee.blakadder.com/Lidl_TYGWZ-01.html). With the version that my gateway was bought, zigbee2mqtt starts and adds new devices, but it cannot properly interview them, resulting in listing a bunch of "unsupported" devices which don't even get paiered. After EZSP firmware update (in my case to 6.7.8.0) everything works like a charm.

I hope this is useful for someone :)

**Reply by VladaWaas** [reply]
I trying your method, but the configuration has Error:
_ERROR: for zigbee2mqtt  "host" network_mode is incompatible with port_bindings i                                                                             Traceback (most recent call last):ist-packages/compose/service.py", line 579, in
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.9/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/local/lib/python3.9/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/local/lib/python3.9/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.9/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/local/lib/python3.9/dist-packages/compose/project.py", line 679, in do_

My knowlidges is not  on high level about it. Could you tell me, where is err_ERROR: 
In the docker compose:
```
 zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Prague 
     In the configuration:
# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  adapter: ezsp
  port: tcp://192.168.0.110:8888
```
-----------------
MQTT is live and active in the docker, HAss too.
