### DISCUSSION TITLE
New outdoor siren supported

### DISCUSSION THREAD

**Discussion by samuprofe** [Koenkk/zigbee2mqtt#6456] [Devices]
SMaBiT (Bitron) AV2010/29A
Up to now only EDGE version
Documentation: https://github.com/samuprofe/zigbee2mqtt.io/blob/master/docs/devices/AV2010_29A.md

**Comment by lesensei** [comment]
Hey there @samuprofe !
I'd like to thank you for this work. I just received my AV2010/29A siren and got it to work. I just thought I'd chime in to let you know that with mine, I need to set the "strobe" parameter to `true` in order for the siren to make a sound when sending a "warning". Whenever I set it to false, the siren stays silent. Since the documentation says the contrary, I thought it might be important to let you know.
By the way, have you found a way to disable the "tamper" alarm in order to change batteries ? or, more generally, to stop the siren once it has been triggered ?
Thanks again !

**Reply by samuprofe** [reply]
Thanks for the comment.

In my case to activate the alarm I send this message and it works:
```
service: mqtt.publish
data:
   topic: zigbee2mqtt / 0x00124b00207f60d6 / set
   payload: '{"warning": {"duration": 30, "strobe": false}}'

```
However, I am still using the EDGE version, maybe with the standard version it has changed. I will write it down in the documentation.

To deactivate the alarm, just send any other beep. I send a short beep like this:

```
service: mqtt.publish
data:
   topic: zigbee2mqtt / 0x00124b00207f60d6 / set
   payload: '{"warning": {"level": "very_high"}}'
```

The "Tamper" function worked for me when I manually adopted the device but it stopped working when I put the EDGE version. I have to investigate it but I think that right now it probably won't work for you. If I am wrong please let me know.

Thanks and greetings.
