### DISCUSSION TITLE
Why has a link quality sensor a brightness attribute?

### DISCUSSION THREAD

**Discussion by darootler** [Koenkk/zigbee2mqtt#7249] [General]
Hi!

I am using Zigbee2MQTT for a few weeks now and my HA database started growing. The cause are many state changes for new entities from Zigbee2MQTT. So i reviewed those a bit and found out that all of those sensors do report multiple attributes, here is an example:

![image](https://user-images.githubusercontent.com/11849583/116570110-48bc5000-a90a-11eb-8eac-74b0d5138c47.png)

This is a link quality sensor from a light and it has attributes like brightness, color mode and so on. Is this intended or just a configuration issue?

Regards
Richard

**Comment by Koenkk** [comment]
This due to the `json_attributes_topic` being set. But this is indeed a bad practice, instead separate sensors should be created. I've removed this now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Reply by ssiergl** [reply]
@Koenkk should be marked in release notes. This will break HA automations which are using state attribute trigger

like:

```
trigger:
  platform: state
  entity_id: !input remote
  attribute: action
```

Which sadly a lot blueprints are using.

**Reply by darootler** [reply]
@ssiergl Based on my example above:

If lqi changes an automation will sill trigger because the state changes. If color_temp changes the automation will not trigger. So i think this is just a "bug fix" and fixes wrongly triggered automations.

Or am i wrong here?

Regards
Richard

**Reply by ssiergl** [reply]
yeah of course this fix is valid! Absolutely. As @Koenkk mentioned this was a bad practice and each attribute should get an own entity.

Well I think a lot user are using it like above due of the click deprecation in favour of action and/or to reduce automation triggers for every change even if they filter the command out in the action

Just wanted to say that this change should be explicity mentioned so that user can interact. Otherwise you will get a lot of open issues here :D

**Reply by Koenkk** [reply]
@ssiergl thanks for pointing this out. This is indeed a breaking change and therefore not something we want to address now, but rather in Z2M 2.0.0). I've reverted this change now however you can still remove the attributes relatively easy by adding the following to your `configuration.yaml`.

```yaml
device_options:
  homeassistant:
    json_attributes_topic: null
```

**Reply by darootler** [reply]
Hmm, i just tried that and the attributes are still there. Am i missing something here?

EDIT: Seems like the HA Addon is not passing the configuration correctly or i am just unable to do that correctly. However, i'll just wait for the new release.

Regards
Richard

**Reply by Koenkk** [reply]
I believe you need to restart HA also after this. Note that no change will be included in the next release, this should already be possible

**Reply by darootler** [reply]
Hmm, here is the add on config:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee
  password: '!secret zigbee_password'
  server: 'mqtt://core-mosquitto:1883'
  user: '!secret zigbee_username'
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  availability_timeout: 600
  channel: 25
  last_seen: ISO_8601_local
  log_level: warn
  network_key: []
  network_key_string: '!secret zigbee_network_key'
  pan_id: '!secret zigbee_pan_id'
  report: true
device_options:
  homeassistant:
    json_attributes_topic: null
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
```
and here is the configuration.yaml written by the add on:

```
{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee",
    "password": "xxx",
    "server": "mqtt://core-mosquitto:1883",
    "user": "xxx"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
  },
  "advanced": {
    "availability_timeout": 600,
    "channel": 25,
    "last_seen": "ISO_8601_local",
    "log_level": "warn",
    "network_key": [
      xx,
      xx,
      xx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xx
    ],
    "pan_id": xxxx,
    "report": true
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}
```

Is it possible that "device_options" isn't taken into account from the add on yet?

Regards
Richard
