### DISCUSSION TITLE
Graylog / external syslog

### DISCUSSION THREAD

**Discussion by Giewarro** [Koenkk/zigbee2mqtt#7404] [General]
Hello,
I have been using it for more then one year with joy & without any issues. Because it is on Pi Zero I thought to move log to different place. Graylog seemed to be the perfect option after changing succefully all tasmota devices to it. Playing variety of options finnaly I changed configuration.yaml to the following but without any success. 
As mentioned before Graylog register all tasmotas but no single line from zigbee2mqtt.
Log.txt is filled properly but without any hints.
Any suggestion appritiated.

```
advanced:
  log_level: info
  log_output:
    - file
    - syslog
  log_syslog:
    host: 192.168.1.15
    port: 5141
    protocol: udp4
    type: bsd
    facility: local1
    app_name: Zigbee2MQTT
  rtscts: false


```
EDIT: I don't know how to force it to send log directly to graylog but I was able to send it syslog and then redirect to graylog. The only thing still bodering me is _facility_ option (e.g here local1), which is not overtaken into log. Somebody something?   
EDIT: Solved. Facility working fine.
