### DISCUSSION TITLE
Component error: devices - Integration 'devices' not found.

### DISCUSSION THREAD

**Discussion by wizvvs** [Koenkk/zigbee2mqtt#8001] [General]
I need to calibrate and change temperature precision for my Aqara door & window contact sensor (Xiaomi MCCGQ11LM). When I added according to device type specific configurationin in configuration.yaml these lines:

 ```
devices:
   '0x00158d0006c4d217':
     temperature_precision: 0
     temperature_calibration: -4
```
I have this error in Home Assistant logs: "Component error: devices - Integration 'devices' not found".

What did I miss?
