### DISCUSSION TITLE
ERROR Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'

### DISCUSSION THREAD

**Discussion by fioriniald** [Koenkk/zigbee2mqtt#8186] [General]
Hello,
in log I have this error:

**Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'**

My configuration is:

```
sensor:
   - platform: "mqtt"
     state_topic: "zigbee2mqtt/0x00258e009654d7bn"
     name: "door_signal"
     availability_topic: "zigbee2mqtt/bridge/state"
     unit_of_measurement: "lqi"
     value_template: "{{ value_json.linkquality }}"
     icon: "mdi:signal"
```
Can help me?
