### DISCUSSION TITLE
why doesn't work "sensor.zigbee2mqtt_version"

### DISCUSSION THREAD

**Discussion by bartplessers** [Koenkk/zigbee2mqtt#8612] [General]
Hi,

I have zigbee2mqtt connected to my homeassistant instance.

in MQTT explorer, I see the following JSON under `zigbee2mqtt/bridge/config`
```
{
    "commit": "unknown",
    "coordinator": {
        "meta": {
            "maintrel": 1,
            "majorrel": 2,
            "minorrel": 7,
            "product": 1,
            "revision": 20210430,
            "transportrev": 2
        },
        "type": "zStack3x0"
    },
    "log_level": "warn",
    "network": {
        "channel": 11,
        "extendedPanID": "0xdddddddddddddddd",
        "panID": 6758
    },
    "permit_join": false,
    "version": "1.21.0"
}
```

In home assistant, I configured following yaml in packages:

```
sensor:
# -------------------------------------------
  # Sensor for Showing the Zigbee2mqtt Version
  - platform: mqtt
    name: Zigbee2mqtt Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee
  # Sensor for Showing the Coordinator Version
  - platform: mqtt
    name: Coordinator Version
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator }}"
    icon: mdi:chip

group:
# -------------------------------------------
  Zigbee2mqtt:
    name: Zigbee2mqtt
    entities:
    - sensor.zigbee2mqtt_bridge_state
    - sensor.zigbee2mqtt_version
    - sensor.coordinator_version

```

However, in the interface I see that "Coordinator Version" is recognized, but "Zigbee2mqtt Version" isn't...
![2021-09-02_17-31-44](https://user-images.githubusercontent.com/10470708/131873128-ca8eb1b0-ad22-4de9-8af8-fb8653bce778.png)

Question
How can I configure my sensor in a way that I can show the running version of Zigbee2mqtt on hass?

thanx in advance!

Grtz
B
