### DISCUSSION TITLE
Custom Color Temperature Ranges for zigbee cct dimmers, is it possible?

### DISCUSSION THREAD

**Discussion by fluffymadness** [Koenkk/zigbee2mqtt#8649] [Devices]
I'm generally have issues with Miboxer zigbee devices atm.
The bulb FUT105z for example  (still working on support https://github.com/Koenkk/zigbee2mqtt/issues/8599) has the problem of reporting a physical
colorTempRange: [153, 500].
The thing is however that range maps to 6500k-2700k(370mired) in reality.
This brings all kind of issues if things like adaptive lighting are used in homeassistant, since
it assumes it is a fullrange light with 500mired max, so the colour temperature is always off.

The same thing ofc happens with the dual white ledstrip controller (cct), if some other strips than the reported color range are connected
```
 fingerprint: [{modelID: 'TS0502B', manufacturerName: '_TZ3210_frm6149r'}],
        model: 'FUT035Z',
        description: 'Dual white LED controller',
        vendor: 'Miboxer',
        extend: extend.light_onoff_brightness_colortemp({disableColorTempStartup: true, colorTempRange: [153, 500]}),

```
Is there any possibility via custom converters or anything to do some kind of range mapping???
eg mapping a intervall of e.g 153-500 mired to 153-370 mired?
This one should be a general issue that appears on cct ledstrip controllers, since you can basically connect anything to it. In esphome it is solved in a way that you can specify the max color temperature of each channel

```
light:
  - platform: cwww
    id: light1
    default_transition_length: 0s
    constant_brightness: true
    name: "${name} Light"
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500K
    warm_white_color_temperature: 2700K
    gamma_correct: 0

```
Does anyone have a solution or maybe a suggestion how this one could be solved ?
I did some digging in the herdsman converter repo by looking at other converters, read the documentation of adding new devices etc, but so far I haven't found anything.

**Comment by fluffymadness** [comment]
@sjorge Do you have an idea how this could maybe be fixed. My bulb FUT105z https://github.com/Koenkk/zigbee2mqtt/issues/8599 is reporting a wrong color temperature than it has in real life.
The reported color temp range of my bulb is [153, 500], however in reality it maps to 6500k-2700k, which brings color issues in home assistant when trying to set a target color temperature.
I did some digging in the herdsman repo the last few days, but haven't found anything I could solve this with.
I've found one old issue post https://github.com/Koenkk/zigbee2mqtt/issues/6123#issuecomment-774509448 where one user was also complaining about a bulb that was supposedly lying with its color temperature, where you suggested that some meta value could probably be added to work around this

**Reply by sjorge** [reply]
No idea how to do such mapping, the only thing change around color temperature handling is what we limit it to the range the bulb reports as supported.

Removing that restriction is not magically gonna fix your problem, as the mapping is still going to be wrong. Although it looks like it is already set to `colorTempRange: [153, 500]` which is basically un restricted.

**Reply by fluffymadness** [reply]
If I move the restriction, and set it to 370. It basically clamps and I can't reach the real max value (2700k=370mired) anymore.
Atm to get my 370 Mired I have to set 500 Mired in homeassistant.

I think to fix this, we would basically need a conversion like this, which should also work for dimmers.
This way we should be able to connect any kind of strips with different mired values and we would still get the correct color mapping
```
long map(long x, long in_min, long in_max, long out_min, long out_max) {
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
```
For example (homeassistant side)
in_min = 153
in_max = 370
Bulb side
out_min = 153
out_max = 500

for x ( home assistant side) for example we set the target temperature value = 370 mired (2700k), which then would result in 500 mired on the bulb side

(370-153)*(500-153)/(370-153) + 153
(217)*(347)/(217)  +153
          (75299  /217) +153 = 500 mired

**Reply by fluffymadness** [reply]
And then on the converter /device specific config side maybe something like
 extend: extend.light_onoff_brightness_colortemp({disableColorTempStartup: true, colorTempReportRange[153,370], colorTempRange: [153, 500]}),
 That way we could map one interval to the other.

This would enable us to do e.g colorTempReportRange[165,370]
if the cold white strip connected to the cw/ww dimmer for example only has 165mired

**Reply by fluffymadness** [reply]
@Koenkk Would something like this be feasible to implement?

**Reply by intrinseca** [reply]
I just replaced the LED strip on one of my GL-C-008 RGBCCT controllers and have run into this same issue.

I struggle to know where to start to change the behaviour (and TypeScript is pretty far down my list of fluent languages).

It looks like you could change https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/converters/toZigbee.ts#L156 to do a mapping? And I'm not sure where you would add the 'true color temp' settings. Is there an easy way to prototype with an external converter?

Would love to try and progress this, but would welcome a starting direction from an existing contributor!

**Comment by fluffymadness** [comment]
For anyone being in the same situation.
This is the setup i use for my milight dimmer atm where a 2700k and a 6500k strip is connected to it for cct.
Here is a color converter example on the homeassistant side mapping 370-153mired to 500-153 mired on the zigbee2mqtt side.
It works with a light template entity.
You have to enable seperate turn on commands in the adaptive lighting settings page.
Simultaneous commands don't work on light templates.
Anyways here is the code, maybe it is useful to someone.

```
light:
  - platform: template
    lights:
      azdimmer_dummy:
        friendly_name: "AzDimmerTemplate"
        level_template: "{{ state_attr('light.dimmerazroom', 'brightness') | int }}"
        value_template: "{{ states('light.dimmerazroom') }}"
        temperature_template: >-
         {% set color_temperature = state_attr('light.dimmerazroom', 'color_temp') | int %}
         {{ (color_temperature - 153)*(500-153)/(370-153) + 153 }}
        max_mireds_template: 370 
        min_mireds_template: 153
        turn_on:
          - service: light.turn_on
            entity_id: light.dimmerazroom
        turn_off:
          - service: light.turn_off
            entity_id: light.dimmerazroom
        set_level:
          - service: light.turn_on
            data_template:
              entity_id: light.dimmerazroom
              brightness: "{{ brightness }}"
        set_temperature:
          - service: light.turn_on
            data_template:
              entity_id: light.dimmerazroom
              color_temp: "{{ (color_temp - 153)*(500-153)/(370-153) + 153 }}"

```
