### DISCUSSION TITLE
Eurotronic Spirit zigbee thermostat - missing entity?

### DISCUSSION THREAD

**Discussion by bence111** [Koenkk/zigbee2mqtt#9195] [Devices]
Hello,

I'm using an Eurotronic Spirit thermostat integrated into (dev type SPZB0001, zigbee_manufacturer is Eurotronic).
Some parameters (battery, eurotronic_valve_position, eurotronic_trv_mode and climate (including current temp, heating setpoing etc) are published to Mosquitto MQTT server and appearing in the Home assistant enity list.
There is one parameter (what I really need): pi_heating_demand (the current position of the valve), which is not appearing in the entity list therefore I can not check/display it in HA.
When browsing with MQTT explorer, it seems that is listed in homeassistant/sensor/DEVNAME topic, but no entity is created for it.
Mosquitto discovering is enabled.
Mosquitto version 6.0.1
Zigbee2MQtt version 1.21.2-1
HA version 2021.10.5
I already tried couple of things, e.g.:
-remove the device, add it again
-remove, then stop mosquitto, restart HA, delete old entities and join the device again

Is this pi_heating_demand is working for someone as entity?

How can I add MQTT value manually to entities?

Or what can be the problem with this eurotronic device in zigbee2mqtt?

**Comment by Morphy99** [comment]
pi_heating_demand is available as a state attribute of the main TRV entity. You can create a sensor in HA like this:

```
- platform: template
  sensors:
    bedroom_trv_pi_demand:
      friendly_name: "Bedroom Radiator Pi Demand"
      value_template: "{{ state_attr('climate.trv_bedroom', 'pi_heating_demand') }}"
```
