### DISCUSSION TITLE
Connecting to MQTT maqiatto.com fail

### DISCUSSION THREAD

**Discussion by rudolf992** [Koenkk/zigbee2mqtt#9405] [General]
Hello,

I am testing out zigbee2mqtt which works perfectly, but can't get it connect to maqiatto.com mqtt service. It is stuck at connecting to mqtt server. Others like, local or test.mosquitto.org works.

this is whay my configuration.yaml looks like:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://maqiatto.com:1883
user: myusername
password: mypass
serial:
  port: /dev/ttyACM0
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
device_options:
  legacy: false
devices:
  '0x847127fffe11dbfe':
    friendly_name: 'radiator1'
```

Do you have any experience connecting to maqiatto service?

Thank you!
