### DISCUSSION TITLE
Tuya Zigbee SC500ZB support?

### DISCUSSION THREAD

**Discussion by AndreMassa997** [Koenkk/zigbee2mqtt#9514] [Devices]
Hi, Is Tuya Zigbee SC500ZB roller shutter module supported? I see in aliexpress site that is supported in zigbee2mqtt but I don't see it in the supported devices list on website.
Someone use this device?
Thank you.

**Comment by Wilboc85** [comment]
hi, 
I bought these switches.
I ordered them on aliexpress from the same seller.
Although the switches are visually identical. They don't have the same components inside.
Despite everything, they are well recognized in Zigbee2MQTT. They are recognized as a TS130F.

See you

**Reply by AndreMassa997** [reply]
Thank you!

**Reply by hardwareadictos** [reply]
Thanks for the answer. I am also interested on them, are they still functioning correctly?

**Reply by AndreMassa997** [reply]
@hardwareadictos Yes, I have 7 or these modules and they work all properly. I suggest to calibrate the mechanical limit switch with physical buttons without this module. After this procedure, you can attach the module to the motor and physical buttons, then add these to zigbee2mqtt and calibrate it.

**Reply by hardwareadictos** [reply]
> @hardwareadictos Yes, I have 7 or these modules and they work all properly. I suggest to calibrate the mechanical limit switch with physical buttons without this module. After this procedure, you can attach the module to the motor and physical buttons, then add these to zigbee2mqtt and calibrate it.

That's the idea, firstly to calibrate limits with the motor, and then add those switches, which have to be totally transparent to that proces 🙂

Let's add some of them to the basket!

Thanks for the rapid response.

**Comment by Wilboc85** [comment]
Hello, 
They are working properly.
Calibration remains a concern because it is established according to a time of ascent descent and not ascent. the difference between its two phases can be significant.
I would prefer an intensity feedback which makes it possible to maintain the ascent or descent phase until the end of the motor run.
Cordially,

**Reply by Kuirak** [reply]
Did you happen to find a solution for ascent and descent being different. After some usages they don't fully open anymore and I need to recalibrate it.

**Reply by Wilboc85** [reply]
Hello, I have to do the same as you.
Unfortunately.

**Reply by FeikoJoosten** [reply]
Out of curiosity, did either of you every manage to resolve this? I can reproduce this rather quickly by simply opening the blinds to 10%, en closing again and it's already out of sync as it no longer fully closes, sometimes it still needs 1% and other times it still needs 3%.

**Reply by Kuirak** [reply]
@FeikoJoosten I solved it with software and wrote an automation in my home assistant that when the blinds reach 0%/ stop I reverse the motor direction and open it back to 2% (physically it is closing). This ensures the blinds are always fully opened and the out of sync  doesn't happen. This solution was good enough for my purpose
```yaml
alias: Reset Blinds
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.blinds_north_moving
    from: UP
    to: STOP
condition:
  - condition: device
    device_id: <device-id>
    domain: cover
    entity_id: cover.blinds_north
    type: is_position
    below: 1
action:
  - type: turn_on
    device_id: <device-id>
    entity_id: switch.blinds_north_motor_reversal
    domain: switch
  - device_id: <device-id>
    domain: cover
    entity_id: cover.blinds_north
    type: set_position
    position: 2
  - wait_for_trigger:
      - platform: state
        entity_id:
          - sensor.blinds_north_moving
        to: STOP
  - type: turn_off
    device_id: <device-id>
    entity_id: switch.blinds_north_motor_reversal
    domain: switch
mode: single
```
