### DISCUSSION TITLE
Device-Availability --> "availability: true" does not work?

### DISCUSSION THREAD

**Discussion by bartplessers** [Koenkk/zigbee2mqtt#9699] [General]
Hi,

I'm testing with the availability feature.

My zigbee2mqtt config:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.5.85
  user: xxxxxxxx
  password: xxxxxxxx
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6758
  channel: 11
  network_key:
    - xxx
    - xxx
    - xxx
  availability_blocklist: []
  availability_passlist: []
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
availability: true

```

I deliberately disabled a lamp (no powersupply) and rebooted zigbee2mqtt (and also hass)
However, I do NOT see a topic 
`zigbee2mqtt/[FRIENDLY_NAME]/availability`

What am I doing wrong?

grtz
B
