### DISCUSSION TITLE
Last seen N/A for all devices

### DISCUSSION THREAD

**Discussion by hugalafutro** [Koenkk/zigbee2mqtt#9703] [General]
Hi,
I noticed N/A  in lower left of each device of z2m web ui dashboard, and found out this is supposed to show the last_seen attribute, however all my devices show this as N/A. I didn't want to open an issue in case I'm just blind and miss some obvious toggle to enable this, but was wondering if there are some specific steps to make this work?

**Comment by sjorge** [comment]
This is correct unless you enable the last seen tracking.

https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#mqtt-behaviour

```yaml
advanced:
  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
  last_seen: 'disable'
```

So setting this to either `ISO_8601`, `ISO_8601_local` or `epoch` will enable it.
