### DISCUSSION TITLE
GE 45852GE Dimmer Doesn't Work When `state` and `brightness` Are Set at the Same Time

### DISCUSSION THREAD

**Discussion by scolby33** [Koenkk/zigbee2mqtt#9902] [Devices]
I have a GE 45852GE dimmer and when I configure it in a Home Assistant scene, it sometimes doesn't work.

Starting with the device in this state:
```
{
    "brightness": 127,
    "linkquality": 90,
    "state": "ON"
}
```

I can activate a scene that has the desired brightness at 79:
```
Zigbee2MQTT:debug 2021-11-29 22:35:30: Received MQTT message on 'zigbee2mqtt/dimmer/set' with data '{"state": "ON", "brightness": 79}'
Zigbee2MQTT:debug 2021-11-29 22:35:30: Publishing 'set' 'brightness' to 'dimmer'
Zigbee2MQTT:info  2021-11-29 22:35:30: MQTT publish: topic 'zigbee2mqtt/dimmer', payload '{"brightness":79,"linkquality":90,"state":"ON"}'
```

If I now turn the dimmer off:
```
{
    "brightness": 79,
    "linkquality": 90,
    "state": "OFF"
}
```

And activate the same scene:
```
Zigbee2MQTT:debug 2021-11-29 22:37:38: Received MQTT message on 'zigbee2mqtt/dimmer/set' with data '{"state": "ON", "brightness": 79}'
Zigbee2MQTT:debug 2021-11-29 22:37:38: Publishing 'set' 'brightness' to 'dimmer'
Zigbee2MQTT:info  2021-11-29 22:37:38: MQTT publish: topic 'zigbee2mqtt/dimmer', payload '{"brightness":79,"linkquality":90,"state":"ON"}'
```
But the light doesn't come on, even though the state in Zigbee2MQTT says it is:
```
{
    "brightness": 79,
    "linkquality": 90,
    "state": "ON"
}
```

Manually turning it off results in the proper state, and then turning it back on again works:
```
Zigbee2MQTT:debug 2021-11-29 22:40:52: Received MQTT message on 'zigbee2mqtt/dimmer/set' with data '{"state": "ON"}'
Zigbee2MQTT:debug 2021-11-29 22:40:52: Publishing 'set' 'state' to 'dimmer'
Zigbee2MQTT:info  2021-11-29 22:40:52: MQTT publish: topic 'zigbee2mqtt/dimmer', payload '{"brightness":79,"linkquality":90,"state":"ON"}'
Zigbee2MQTT:debug 2021-11-29 22:40:52: Received Zigbee message from 'dimmer', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-11-29 22:40:52: MQTT publish: topic 'zigbee2mqtt/dimmer', payload '{"brightness":79,"linkquality":90,"state":"ON"}'
```

Notice how the incoming MQTT message was just `{"state": "ON"}` and didn't contain a brightness key.

This seems like a bug in the GE 45852GE dimmer itself. Is there a way to work around this problem in Zigbee2MQTT, perhaps some way to split up incoming messages? If not, is there some way to convince Home Assistant to not coalesce the state and brightness messages? (I can of course ask in a Home Assistant forum for this as well, but thought I'd throw in the question here as well.)

**Comment by onixx** [comment]
Same issue here with homebridge and the z2m plugin.

**Comment by old-beans** [comment]
Any action on this? Just migrated from ZHA to z2m and I have the same issue.

**Comment by scolby33** [comment]
I worked around this with this automation:
```yaml
alias: Dimmer Fix
trigger:
  - platform: state
    entity_id:
      - light.zigbee_dimmer
    to: "on"
action:
  - service: light.turn_on
    data:
      brightness_step_pct: -5
    target:
      entity_id: light.zigbee_dimmer
  - service: light.turn_on
    data:
      brightness_step_pct: 5
    target:
      entity_id: light.zigbee_dimmer
mode: single
```

(I'm not using this dimmer any more though, since it suddenly stopped working a few weeks ago, suspiciously just a month after the warranty ran out 😢)
