### ISSUE TITLE
Error: network commissioning timed out

### ISSUE THREAD

**Issue by Koli96** [Koenkk/zigbee2mqtt#10209]
## What happened
Hi.
I'm trying to run `zigbee2mtqq` with SONOFF Zigbee 3.0 USB Dongle Plus on Raspberry Pi4 with Raspberry Pi Os x86. I'm newbie with zigbee and it's my first contact either with mosqutto and zigbee itself. I have set up `mosquitto` broker and now I'm trying to run `zigbee2mtqq` in docker.
I have my dongle mounted at `/dev/ttyUSB0`.
After running container I'm still getting in logs:
```
 Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
```
I tried to change `panId` and `extendedPanId` in `configuration.yaml`, but didn't help.

## Debug info
Zigbee2MQTT version: latest docker image
Adapter hardware: SONOFF Zigbee 3.0 USB Dongle Plus
Adapter firmware version: preflashed from itead.cc

Full logs:
```
Using '/app/data' as data directory
Zigbee2MQTT:debug 2021-12-17 18:58:04: Loaded state from file /app/data/state.json
Zigbee2MQTT:info  2021-12-17 18:58:04: Logging to console and directory: '/app/data/log/2021-12-17.18-58-02' filename: log.txt
Zigbee2MQTT:debug 2021-12-17 18:58:04: Removing old log directory '/app/data/log/2021-12-17.18-46-11'
Zigbee2MQTT:info  2021-12-17 18:58:04: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
Zigbee2MQTT:info  2021-12-17 18:58:04: Starting zigbee-herdsman (0.13.176)
Zigbee2MQTT:debug 2021-12-17 18:58:04: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,13,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6452},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:error 2021-12-17 18:59:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-12-17 18:59:09: Failed to start zigbee
Zigbee2MQTT:error 2021-12-17 18:59:09: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2021-12-17 18:59:09: Exiting...
Zigbee2MQTT:error 2021-12-17 18:59:09: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
```

`docker-compose.yaml`:
```
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0
```

`configuration.yaml`:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: XXX
  password: XXX
serial:
  port: /dev/ttyACM0
advanced:
  ext_pan_id:
    - 221
    - 13
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  pan_id: 6452
  network_key: xxx
  log_level: debug
```

Thank you for your time!
