### ISSUE TITLE
Zigbee network does not recovers after coordinator/server power off

### ISSUE THREAD

**Issue by voed** [Koenkk/zigbee2mqtt#10325]
I have 3 Zigbee devices in my network:
Moes switch MS-104Z
Moes temp/hum/lux sensor with display ZSS-ZK-THL
Moes tem/hum sensor without display TT001ZAV20

After power loss for ~30 minutes all devices stopped to update their states. I've waited for few hours, but nothing changed. ZSS-ZK-THL had "!" symbol on its display. For switch i used "update" button in z2m frontend. The sensors started to work only after pressing pair button on sensor itself. Not exactly sure when it started, but looks like after "availability" feature even if its disabled. 

## Debug info
Zigbee2MQTT version:
1.22.1
Adapter firmware version:
20210708

My z2m config:
``` yaml
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  username: user
  password: pass
serial:
  port: /dev/ttyS1
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601_local
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```
