### ISSUE TITLE
[Feature request]: Add/change ser2net documentation for Conbee II

### ISSUE THREAD

**Issue by Jeroen-Priester** [Koenkk/zigbee2mqtt#10533]
### Is your feature request related to a problem? Please describe

Conbee II via ser2net doesn't work when using examples from connect_to_a_remote_adapter.html
It does work when adding "nobreak" to ser2net config.

- Ubuntu 21.10
- ser2net 4.3.3 from from default Ubuntu repo
- Z2M addon 1.22.2-1 in Home Assistant Hassio in VM

### Describe the solution you'd like

Add "**nobreak**" to ser2net example for Conbee II users:

Like:

```
connection: &con01
  accepter: tcp,20108
  connector: serialdev,/dev/ttyACM0,115200n81,nobreak,local
  options:
    kickolduser: true
```

### Describe alternatives you've considered

no alternative

### Additional context

see solution
