### ISSUE TITLE
Groups on SSM-U02  device

### ISSUE THREAD

**Issue by Jacuo** [Koenkk/zigbee2mqtt#11020]
### What happened?

I tried to configure group for two SSM-U02  devivec
But it doesn`t work

### What did you expect to happen?

When I send command to group topic both switches will execute it

### How to reproduce it (minimal and precise)

My configuration.yaml
```
devices:
  '0x54ef4410001a996d':
    friendly_name: schody_dol/wylacznik_gora
  '0x54ef4410001a8949':
    friendly_name: schody_dol/wylacznik_dol
groups:
  '1':
    friendly_name: wylaczniki
    devices:
      - 0x54ef4410001a8949/1
      - 0x54ef4410001a996d/1
```

When I publish to topic zigbee2mqtt/wylaczniki/set
message 
`{"state":"ON"}`

state in UI changes, but switches don`t execute it 
Sending the same message to both topics schody_dol/wylacznik_gora and  schody_dol/wylacznik_dol works as expected

### Zigbee2MQTT version

 1.22.2 commit: 414c51f

### Adapter firmware version

 20190619

### Adapter

 zStack12
