### ISSUE TITLE
zigbee-herdsman stuck at startup

### ISSUE THREAD

**Issue by conorhub** [Koenkk/zigbee2mqtt#11079]
### What happened?

When starting zigbee2mqtt (via docker with a flashed sonoff zigbee bridge) the log never goes beyond "Starting zigbee-herdsman". It doesn't appear frozen, per-se, but I've left it for hours, restarted, and it never moves beyond this message.

```
Zigbee2MQTT:info  2022-01-28 16:00:17: Logging to console and directory: '/app/data/log/2022-01-28.16-00-15' filename: log.txt
Zigbee2MQTT:info  2022-01-28 16:00:17: Starting Zigbee2MQTT version 1.22.2 (commit #414c51f)
Zigbee2MQTT:info  2022-01-28 16:00:17: Starting zigbee-herdsman (0.13.188)
```

### What did you expect to happen?

I expected it to output something similar to: https://1.bp.blogspot.com/-QOHM_8w_FlI/YE6y15g7qaI/AAAAAAAEoQA/ZPsHZpSc-assud52cNaZfg66cVOPje1zwCLcBGAsYHQ/s982/zigbee_log.PNG

Particularly confirming that zigbee-herdsman was succesfully started, as the next line or, if there was an issue, to state there was a failure or error. Neither happen.

### How to reproduce it (minimal and precise)

**docker-compose.yml**

```

version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "/home/pi/docker/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
       - /home/pi/docker/zigbee2mqtt/data:/app/data
       - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin

  zigbee2mqttAssistant:
    image: carldebilly/zigbee2mqttassistant
    container_name: zigbee2mqttAssistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=192.168.88.220
      - TZ=Europe/Berlin
    ports:
      - 8880:80
    restart: unless-stopped
```

**configuration.yml**

```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.88.220:1883'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # sonoff bridge
  adapter: ezsp
  port: 'tcp://192.168.88.200:8888'
frontend:
  port: 8080
# Optional: advanced settings
advanced:
  # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
  # (default: 11)
  channel: 15
```

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

Can't access frontend

### Adapter

Sonoff Zigbee Bridge flashed to Tasmota

### Debug log

I wasn't able to successfully generate debug logs via docker-compose
