### ISSUE TITLE
Problem with Xiaomi Aqara double key wired wall switch (QBKG12LM)

### ISSUE THREAD

**Issue by rado0786** [Koenkk/zigbee2mqtt#1115]
Hi,
I installed the Zigbee2mqtt and when I paired the "Xiaomi", it only detects that it is a sensor. I can not use the 2 buttons. (or I do not know how to use them)
![455222213_260083](https://user-images.githubusercontent.com/46976316/52939474-90c3ad80-3364-11e9-8fad-24d5f17c76ec.jpg)
any solution?
Thank you

**Comment by Bojan023** [comment]
The wall switch is connected correctly. It actually is a sensor since it 'measures' what button is pressed. If any button is pressed (left, right, long, twice) it will broadcast a message over Zigbee accordingly. For instance: left single click will broadcast "left" and the HA sensor value will be updated to 'left'. Twice right: broadcast "right_double", HA sensor "right_double". Good luck!

**Comment by dudel** [comment]
You can use the mqtt trigger and template conditions for automations like this:

```
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/0x001234567890
  condition:
  - condition: template
    value_template: '{{ "left" == trigger.payload_json.click }}'
```
