### ISSUE TITLE
Xiaomi Aqara SSM-U01 not show specific settings

### ISSUE THREAD

**Issue by dtalens** [Koenkk/zigbee2mqtt#11353]
### What happened?

The documentation for Xiaomi Aqara SSM-U01 device shows that  temperature can be calibrated, but then nothing is shown in the Settings (specific) section.
![image](https://user-images.githubusercontent.com/6631832/153565126-4c3ddf11-f9b1-429a-9925-4b042ebc3156.png)
I added this directly to the `device.yaml` file but it has no effect.: 
```
'0x54ef44xxxxxxxxxx':
  friendly_name: Estufa tovalloles
  temperature_calibration: -4
```
This doesn't work either:
```
'0x54ef44xxxxxxxxxx':
  friendly_name: Estufa tovalloles
  device_options:
    temperature_calibration: -4
```
Documentation is confusing, I'm not sure if "device_options" should be set or not.

### Zigbee2MQTT version

1.23.0-dev commit: 7fe803a

### Adapter firmware version

20220103

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus
