### ISSUE TITLE
Split up user and automatic configuration

### ISSUE THREAD

**Issue by deisi** [Koenkk/zigbee2mqtt#1148]
I'm trying to improve the configuration of the z2m addon for hassio https://github.com/danielwelch/hassio-zigbee2mqtt/pull/115

However, because there is mixing between user input (add something to `configuration.yaml`) and automatic input up on pairing (also adds something to `configuration.yaml`), this is more complicated then it should be.
Would it be possible, to split up `configuration.yaml` into seperate files. I think of something like:
- `configuration.yaml`
  All user configuration goes here
- `devices.yaml`
  Gets updated during runtime if new devices are added.
- `groups.yaml` same as devices.

One could also combine `groups.yaml` and `devices.yaml` into a common file, but I have no good name suggestion maybe something like `network.yaml`

The reason for this is, that the current system forces the hassio addon to somehow merge two sources of configuration. 
- 1. The user configures the addon within the hassio frontend > writes to some `options.json` and gets passed into `configuration.yaml`
- 2. The network writes something to `configuration.yaml` and now there is an outch, because we have to telling hassio that the addon changed its own configuration file by itself.

By splitting of these rather dynamic parts of the configuration into separate files. Things could be simplified, because we could then just say that these parts of z2m must be configured from within the configuration files itself and z2m takes care of the user input within these files (as it does already)

**Comment by Koenkk** [comment]
What if we could do something like this:

```yaml
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
  user: my_user

devices: devices.yaml

OR

devices:
  '0x00158d0001d82999':
    friendly_name: 'my_occupancy_sensor'
    retain: true

# same for groups.
```

In zigbeem2qtt we can easily check if devices is a string or an object.
