### ISSUE TITLE
Container keeps restarting with version 1.23

### ISSUE THREAD

**Issue by avakarev** [Koenkk/zigbee2mqtt#11545]
### What happened?

Docker container of image `koenkk/zigbee2mqtt:latest-dev` constantly restarts.
Same configurations works just fine with latest release `koenkk/zigbee2mqtt:1.23.0`

### What did you expect to happen?

I expect container to keep running, connects to mqtt server and publishes / consumes messages.

### How to reproduce it (minimal and precise)

Pull and run latest `koenkk/zigbee2mqtt:latest-dev` image (I found the following version in logs: `1.23.0-dev (commit #a345181)`

### Zigbee2MQTT version

1.23.0-dev (commit #a345181)

### Adapter firmware version

20211217

### Adapter

Electrolama zzh! CC2652R

### Debug log

zigbee2mqtt    | Using '/app/data' as data directory
zigbee2mqtt    | Zigbee2MQTT:debug 2022-02-21 17:22:14: Loaded state from file /app/data/state.json
zigbee2mqtt    | Zigbee2MQTT:info  2022-02-21 17:22:14: Logging to console only'
zigbee2mqtt    | Zigbee2MQTT:info  2022-02-21 17:22:14: Starting Zigbee2MQTT version 1.23.0-dev (commit #a345181)
zigbee2mqtt    | Zigbee2MQTT:info  2022-02-21 17:22:14: Starting zigbee-herdsman (0.14.17)
zigbee2mqtt    | Zigbee2MQTT:debug 2022-02-21 17:22:14: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":true},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"path":"/dev/ttyUSB0"}}'

**Comment by avakarev** [comment]
Here is content of `configuration.yaml`:

```yaml
serial:
  port: /dev/ttyUSB0
  disable_led: true

mqtt:
  server: mqtt://my-server:1883
  base_topic: zigbee2mqtt-home
  user: '!secret user'
  password: '!secret password'
  client_id: zigbee2mqtt-home
  include_device_information: true

permit_join: false

frontend:
  port: 8080
  host: 0.0.0.0

devices: devices.yaml
groups: groups.yaml

ota:
  ikea_ota_use_test_url: false
  update_check_interval: 3600
  disable_automatic_update_check: true

availability:
  active:
    timeout: 20
  passive:
    timeout: 720

homeassistant: false

advanced:
  log_level: debug
  log_output: ['console']
  pan_id: 6755
  channel: 25
  last_seen: ISO_8601_local
  legacy_api: false
```

Here is content of `devices.yaml`:
```yaml
'0x000d6ffffe4b4615':
  friendly_name: hallway-wall-light
  availability: true
'0x847127fffebea049':
  friendly_name: mailbox-motion
'0x14b457fffe693ef6':
  friendly_name: storeroom-motion
'0xa4c138a63ca36dd1':
  friendly_name: '0xa4c138a63ca36dd1'
```

Here is content of `groups.yaml`:
```yaml
{}
```
