### ISSUE TITLE
Use click and action for aqara button state in home assistant

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#1157]
@Koenkk currently only "click" is reportet to the aqara button sensor state in home assistant.
So only "single", "double" can be reportet to the state.

I use (because of the issue, only works after 1-2 seconds after triggered, you know what I mean)

```
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/ZigbeeButton'   
  condition:
    - condition: template
      value_template: '{{ "hold" == trigger.payload_json.**action** }}' 
```

For click is looks like this

```
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/ZigbeeButton'   
  condition:
    - condition: template
      value_template: '{{ "single" == trigger.payload_json.**click** }}' 
```
So I don't need this, but I noticed it and might be necessary for other users, that want to use the "hold" feature that is reportet in "action" not in "click".
