### ISSUE TITLE
Action: null after long time of inactivity from Legrand Netatmo 

### ISSUE THREAD

**Issue by michalg-** [Koenkk/zigbee2mqtt#11657]
### What happened?

Hi,
I have a few Legrand Netatmo remote wall switches and basically, they all behave in similar way. After a long period of inactivity first event after pushing the button is sent with missing action: 
```
zigbee2mqtt    | Zigbee2MQTT:info  2022-03-01 08:10:46: MQTT publish: topic 'zigbee2mqtt/Włącznik światła przedpokój przy drzwiach', payload '{"action":null,"battery":80,"device":{"applicationVersion":0,"dateCode":" \u000020210325\u0000\u0000\u0000\u0000\u0000","friendlyName":"Włącznik światła przedpokój przy drzwiach","hardwareVersion":7,"ieeeAddr":"0x0004740000c24e1e","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067773","networkAddress":65202,"powerSource":"Battery","softwareBuildID":"002a","stackVersion":66,"type":"EndDevice","zclVersion":2},"last_seen":"2022-03-01T08:10:46+01:00","linkquality":134,"voltage":2900}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-03-01 08:10:47: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Włącznik światła przedpokój przy drzwiach","ieee_address":"0x0004740000c24e1e"},"type":"device_announce"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-03-01 08:10:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Włącznik światła przedpokój przy drzwiach"},"type":"device_announced"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-03-01 08:10:47: MQTT publish: topic 'zigbee2mqtt/Włącznik światła przedpokój przy drzwiach', payload '{"action":null,"battery":80,"device":{"applicationVersion":0,"dateCode":" \u000020210325\u0000\u0000\u0000\u0000\u0000","friendlyName":"Włącznik światła przedpokój przy drzwiach","hardwareVersion":7,"ieeeAddr":"0x0004740000c24e1e","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067773","networkAddress":65202,"powerSource":"Battery","softwareBuildID":"002a","stackVersion":66,"type":"EndDevice","zclVersion":2},"last_seen":"2022-03-01T08:10:47+01:00","linkquality":131,"voltage":2900}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-03-01 08:10:54: MQTT publish: topic 'zigbee2mqtt/Włącznik światła przedpokój przy drzwiach', payload '{"action":"toggle","battery":80,"device":{"applicationVersion":0,"dateCode":" \u000020210325\u0000\u0000\u0000\u0000\u0000","friendlyName":"Włącznik światła przedpokój przy drzwiach","hardwareVersion":7,"ieeeAddr":"0x0004740000c24e1e","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067773","networkAddress":65202,"powerSource":"Battery","softwareBuildID":"002a","stackVersion":66,"type":"EndDevice","zclVersion":2},"last_seen":"2022-03-01T08:10:54+01:00","linkquality":109,"voltage":2900}'
```

```
# configuration.yaml

homeassistant: true
permit_join: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://127.0.0.1
  keepalive: 60
  reject_unauthorized: true
  version: 4
  include_device_information: true
serial:
  port: /dev/ttyACM0
ota:
  ikea_ota_use_test_url: false
  disable_automatic_update_check: true
advanced:
  adapter_delay: 10
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601_local
queue:
  delay: 40
  simultaneously: 25
devices:
  '0x04cd15fffe37a54a':
    friendly_name: Włącznik ścienny
  '0x001788010815ec14':
    friendly_name: Lampa kuchnia 1
    transition: 0
  '0x001788010815f1bb':
    friendly_name: Lampa kuchnia 2
  '0x001788010814c77f':
    friendly_name: Lampa kuchnia 3
  '0x00158d0001d76586':
    friendly_name: Czujnik temperatury zewnętrznej
  '0x0017880104f54211':
    friendly_name: Pilot Philips HUE
    legacy: true
  '0x8cf681fffe2fd14e':
    friendly_name: Włącznik na łóżku
  '0x00124b0024c2077d':
    friendly_name: Lampka przy łózku
  '0x8cf681fffe223035':
    friendly_name: Termostat łazienka
  '0x00047400007a881d':
    friendly_name: Włącznik słupek prawy
    legacy: false
  '0x00047400009a1adc':
    friendly_name: Światło kuchnia
  '0x00124b0024c17944':
    friendly_name: Światło przedpokój
  '0x0004740000c2f55c':
    friendly_name: Włącznik słupek środek
  '0x0004740000c24e1e':
    friendly_name: Włącznik światła przedpokój przy drzwiach
  '0x00158d0006445211':
    friendly_name: Guzik
groups: {}
```

As you can see after that every next message has proper `toggle` action in the payload.
There is any way to debounce those two `action: null` messages and handle them as a regular on/off events? Or maybe there is something with the adapter script and I could debug this issue somehow?

### What did you expect to happen?

Handle this event in some way.

### How to reproduce it (minimal and precise)

After a night of inactivity first message sent from the wall switch contains
```
"action": null
```
in the payload.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20211217

### Adapter

Sonoff zigbee 3.0 usb dongle plus
