### ISSUE TITLE
Availability disabled with plain switches

### ISSUE THREAD

**Issue by 21stce** [Koenkk/zigbee2mqtt#11704]
### What happened?

I am seeing that Availability is "Disabled" for two devices, but my configuration file specifies that it should be available. 

Relevant documentation: https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration

![image](https://user-images.githubusercontent.com/100212538/156781241-cbd84c20-c1ca-4665-bce7-74deb9b42c3e.png)

Relevant configuration:

```
advanced:
  legacy_availability_payload: false

devices:
  '<device id1>':
    availability: true
    friendly_name: FOO BAR BAZ
  '<device id2>':
    availability: true
    friendly_name: QUUX BAZ
```

### What did you expect to happen?

I expected to see it was not "Disabled". So, I presume that's called "Enabled". 

### How to reproduce it (minimal and precise)

```
advanced:
  legacy_availability_payload: false
devices:
  '<device id1>':
    availability: true
    friendly_name: FOO BAR BAZ
  '<device id2>':
    availability: true
    friendly_name: QUUX BAZ

frontend:
  host: 127.0.0.1
  port: 8082
homeassistant:
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
permit_join: true
serial:
  adapter: ezsp
  port: tcp://192.168.188.113:8888

```

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

Coordinator type EZSP v8 Coordinator revision 6.7.8.0 build 373

### Adapter

Hacked Silvercrest 

### Debug log

I don't think this is relevant. I will add it when it turns out that it is relevant.
