### ISSUE TITLE
"forgetting" configuration 

### ISSUE THREAD

**Issue by MoonshineSG** [Koenkk/zigbee2mqtt#11700]
### What happened?

the following are setup in configuration (via the Add-Ons-> Z2M -> Configuration) but after reboot, in the WebUI Settings are shown as 'true'

```
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: false
advanced:
  legacy_availability_payload: false

```

### What did you expect to happen?

expected to follow the configuration setup. If setup via WebUI, same thing happens. 

### How to reproduce it (minimal and precise)

Change in Add-Ons
Restart Z2M
Check in Settings

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2
