### ISSUE TITLE
climate.0x<rest of address> shown in home assistant instead of the renamed climate.foo

### ISSUE THREAD

**Issue by 21stce** [Koenkk/zigbee2mqtt#11752]
### What happened?

The address `0x2c1165fffec62727 ` is displayed/leaked in Home Assistant.

### What did you expect to happen?

The desired semantics is that climate.0x2c1165fffec62727 does not exist in Home Assistant, but only climate.office_space_center is available. 

I expected that the `friendly_name` could also be used as an entity_id, which is *not* the case. 

The documentation also discusses a construct of the form:
```
switch:
        type: light
        object_id: light
```

How do I force something to be of type `climate`? The documentation does not specify this. 

### How to reproduce it (minimal and precise)

```
advanced:
  legacy_availability_payload: false
  log_level: debug
availability: true
devices:
  '0x2c1165fffec62727':
    availability: true
    friendly_name: office_space_center
frontend:
  host: 192.168.1.67
  port: 8082
homeassistant:
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
permit_join: true
serial:
  adapter: ezsp
  port: tcp://192.168.1.113:8888
```

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

Coordinator type EZSP v8 Coordinator revision 6.7.8.0 build 373

### Adapter

Hacked Silvercrest 

### Debug log

Unlikely to be relevant here.
