### ISSUE TITLE
[Feature request]: Automations support

### ISSUE THREAD

**Issue by Anonym-tsk** [Koenkk/zigbee2mqtt#11779]
### Is your feature request related to a problem? Please describe

I use Z2M with Home Assistant.
Most of my devices are zigbee and I have quite a few automations in HA.
At the moment automations depend on two services - HA and Z2M. If I update or restart HA, automations don't work.
It would be great to be able to create simple automations directly in Z2M.

### Describe the solution you'd like

I made Z2M extension to create automations directly in Z2M.
Automations syntax in the `configuration.yaml` is quite similar to the HA syntax.

https://github.com/Anonym-tsk/zigbee2mqtt-extensions

### Describe alternatives you've considered

It would be great to merge external extension to Z2M core and create UI for making automations.

### Additional context

```
automations:
  automation_one:
    trigger:
      platform: action
      entity:
      - Switch
      - Button
      action:
      - single
      - double
      - hold
    condition:
      platform: numeric_state
      entity: My Sensor
      attribute: temperature
      above: 25
      below: 35
    action:
    - entity: Light
      service: turn_on
    - entity: Plug
      service: turn_off

  automation_two:
    trigger:
      platform: state
      entity: Motion Sensor
      attribute: occupancy
      state: true
    condition:
      platform: state
      entity: Light
      state: 'OFF'
    action:
      entity: Plug
      service: turn_on
```
