### ISSUE TITLE
ZLinky lower frequency of sensors update

### ISSUE THREAD

**Issue by capi92** [Koenkk/zigbee2mqtt#11805]
### What happened?

Lixee Linky running firmware date 20220217 version 4000-0005
Linky in standard mode, single phase, no production.

Despite measurement_poll_interval set to 300s, pooling remains every 60s.

<img width="1365" alt="Capture d’écran 2022-03-11 à 20 10 29" src="https://user-images.githubusercontent.com/6361326/157935579-8c64ad9a-49bc-4db1-81b9-eb106bbf3ff9.png">

### What did you expect to happen?

Setting 300s pooling interval, I expect sensor value update very 5 minutes.

### How to reproduce it (minimal and precise)

Set anything else than 60s default value, pooling remains every 60s.

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20210120

### Adapter

SonOff ZIGBEE 3.0 USB DONGLE PLUS

**Comment by Koenkk** [comment]
@vk496 could you check this?

**Comment by vk496** [comment]
@capi92 the attributes that are not reportable, use the time you set. Since the device is very aggressive (as you can see), I forced to all reportable attributes use 60s minimum too. You can check that under reporting tab and adjust your needs

**Comment by capi92** [comment]
<img width="1367" alt="Capture d’écran 2022-03-12 à 10 26 06" src="https://user-images.githubusercontent.com/6361326/158012372-a0462944-709a-4226-b09f-a556b998bdef.png">
 @vk496 I guess you are referring to this ?
I just changed everything to 300 except ActiveEnerfyOutDP1 that does not support 300.

BTW, I guess there is a typo, should be Activer Ener**g**youtDP1...

Will let you know in 1 hour or so.

**Comment by Pofilo** [comment]
@renaiku I tag you as asked in #11674 :)

**Comment by capi92** [comment]
Workaround for the time being:

sensor.yaml
```
- platform: filter
  entity_id: sensor.linky_easd02
  name: Filtered hchp
  filters:
    - filter: time_throttle
      window_size: 00:05

- platform: filter
  entity_id: sensor.linky_easd01
  name: Filtered hchc
  filters:
    - filter: time_throttle
      window_size: 00:05
```
