### ISSUE TITLE
Xiaomi DJT11LM "vibration_timeout" does not work

### ISSUE THREAD

**Issue by lux73** [Koenkk/zigbee2mqtt#11835]
### What happened?

Setting `vibration_timeout` in devices.yaml does not work. There's no reset. I had to do via OpenHAB expire command

https://www.zigbee2mqtt.io/devices/DJT11LM.html#options

snip from my devices.yaml:

```
'0x00xxxxxxxxxxxxxx':
  friendly_name: sensor-vibration
  debounce: 1
  vibration_timeout: 60
  filtered_attributes:
    - angle_x_absolute
    - angle_y_absolute
```

### What did you expect to happen?

after setting `vibration_timeout` in devices.yaml that the Sensor is resetting after my specified 60s from z2m

### How to reproduce it (minimal and precise)

set `vibration_timeout` & confirm it does not work

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

Slaesh CC2652RB
