### ISSUE TITLE
Feature request: ICTC-G-1(round Ikea dimmer) Add Action to the MQTT message 

### ISSUE THREAD

**Issue by WagnerBeccard** [Koenkk/zigbee2mqtt#1191]
For better integrating into HomeAssistant i would realy appriciate a `action` in the payload. 
like ` rotate_left ` ,` rotate_right ` ,` quick_rotate_left ` ,` quick_rotate_right `  that we can better work with templates and set lights more dynamic.

**Comment by JLFN** [comment]
I use like this and it works perfect.
```yaml
automation:

- alias: Ikea dimmer
  initial_state: 'off'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt_4/0x000b57fffe2f8d88'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bed_1
    - service: light.turn_on
      data_template:
        entity_id: light.bed_1
        brightness: '{{ states.sensor.ikea_dimmer.state }}'
    - condition: template
      value_template: "{{ states.sensor.ikea_dimmer.state == '0' }}"
    - service: light.turn_off
      data:
        entity_id: light.bed_1
```
