### ISSUE TITLE
Tuya TS0601_thermostat - Window Open entity status Unknown in HA

### ISSUE THREAD

**Issue by Plawasan** [Koenkk/zigbee2mqtt#12130]
### What happened?

After the upgrade to Z2M 1.25.0 I can now see the "Window Open" entity under the Thermostat device in HA however it doesn't get updated with the actual status of the valve while Z2M dashboard (and mqtt messages) show the correct status.

![image](https://user-images.githubusercontent.com/73796046/162605435-d3a901fc-719e-4600-9f58-f4ce0cb4db7f.png)

### What did you expect to happen?

Window open entity updated to reflect the state of the device

### How to reproduce it (minimal and precise)

Enable Wiindow detection on the device
Check status of the Window Open parameter in Z2M
Check status of the corresponding entity  in HA

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210120

### Adapter

zzh!

### Debug log

```
z2m device state:
{
    "auto_lock": "MANUAL",
    "away_mode": "OFF",
    "away_preset_days": 1,
    "away_preset_temperature": 15,
    "battery_low": false,
    "boost_time": 300,
    "child_lock": "UNLOCK",
    "comfort_temperature": 20,
    "current_heating_setpoint": 23.5,
    "eco_temperature": 17,
    "force": "normal",
    "holidays": [
        {
            "hour": 5,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ],
    "holidays_schedule": "05:00/20°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/20°C 22:00/15°C",
    "linkquality": 78,
    "local_temperature": 21.5,
    "local_temperature_calibration": -1,
    "max_temperature": 34,
    "min_temperature": 5,
    "position": 20,
    "preset": "manual",
    "running_state": "heat",
    "system_mode": "auto",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "week": "5+2",
    "window_detection": "ON",
    "window_detection_params": {
        "minutes": 0,
        "temperature": 64
    },
    "window_open": false,
    "workdays": [
        {
            "hour": 6,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ],
    "workdays_schedule": "06:00/20°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/20°C 22:00/15°C",
    "valve_detection": null
}
```

Last MQTT Message shown in HA:
```
Received 08:18:42
QoS: 0
Payload: auto_lock: MANUAL
away_mode: 'OFF'
away_preset_days: 1
away_preset_temperature: 15
battery_low: false
boost_time: 300
child_lock: UNLOCK
comfort_temperature: 20
current_heating_setpoint: 23.5
eco_temperature: 17
force: normal
holidays_schedule: 05:00/20°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/20°C 22:00/15°C
linkquality: 78
local_temperature: 21.5
local_temperature_calibration: -1
max_temperature: 34
min_temperature: 5
position: 20
preset: manual
running_state: heat
system_mode: auto
update:
  state: idle
update_available: false
valve_detection: null
week: 5+2
window_detection: 'ON'
window_detection_params:
  minutes: 0
  temperature: 64
window_open: false
workdays_schedule: 06:00/20°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/20°C 22:00/15°C
```
