### ISSUE TITLE
[Feature request]: Option to enable sensor.<device>_last_seen entity within HA from Z2M configuration settings

### ISSUE THREAD

**Issue by jarrah31** [Koenkk/zigbee2mqtt#12235]
### Is your feature request related to a problem? Please describe

Based on the latest update to the following HA Blueprint, I need to enable the last_seen entity on my devices so that I can be notified when they go offline. 
https://community.home-assistant.io/t/offline-detection-for-z2m-devices-with-last-seen/310138
<img width="581" alt="image" src="https://user-images.githubusercontent.com/3072303/164315039-08d71fbd-6f5e-440b-9c7c-5c6383b0e806.png">

The problem is I have 125 devices, so manually enabling last_seen for each one will take far too long!

### Describe the solution you'd like

Related to this comment https://github.com/Koenkk/zigbee2mqtt/issues/8287#issuecomment-939254755, would it be possible to have an option that enables last_seen entities by default please? Perhaps called something like `last_seen_entity'
```
advanced:
  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
  last_seen: 'ISO_8601_local'
  last_seen_entity: 'true'
```

### Describe alternatives you've considered

Other than manually enabling last_seen for all 125 devices, I'm not aware of an alternative method.

### Additional context

Another user described the same problem in a similar closed thread:
https://github.com/Koenkk/zigbee2mqtt/issues/9398#issuecomment-1003752055

**Comment by jarrah31** [comment]
Thanks to the Blueprint author, he suggested the following, but unfortunately this didn't work for me, even after restarting Z2M and HA.
```
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
```
Just in case anything is clashing, here is my config:
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbeepi2
  server: mqtt://192.168.0.10
  user: user
  password: pass
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
device_options:
  legacy: false
  homeassistant:
    last_seen:
      enabled_by_default: true
experimental:
  new_api: true
advanced:
  network_key:
    - removed
  pan_id: removed
  channel: 23
  last_seen: ISO_8601_local
  elapsed: true
devices:
```

**Comment by Koenkk** [comment]
> I need to enable the last_seen entity on my devices so that I can be notified when they go offline.

You should use the availability feature for this instead: https://www.zigbee2mqtt.io/guide/configuration/device-availability.html

**Comment by jarrah31** [comment]
Hey @Koenkk, thank you for the suggestion. Would we then monitor the device's online/offline status within Home Assistant?

**Comment by Koenkk** [comment]
Yes, since offline devices will be marked as unavailable in HA.

**Comment by jarrah31** [comment]
Thanks Koenkk!

**Comment by jarrah31** [comment]
Sorry, one more question @Koenkk, what is the best way to identify all devices from Z2M within Home Assistant please?

I see that historically, the following has been used, but my devices don't appear to have this attribute anymore.
```
{% for state in states.sensor | selectattr('attributes.unit_of_measurement', '==', 'lqi') %}
```
If I could enable all my _last_seen entities, the following may be a possibility, but this also retrieves entities unrelated to Z2M such as my Alexa devices
```
{% for state in states.sensor | selectattr('attributes.device_class', '==', 'timestamp') %}
```
So is there a reliable way to search all Z2M devices so that I can report on any that are unavailable please?

**Comment by Koenkk** [comment]
You can use something like https://community.home-assistant.io/t/unavailable-entity-detection-notification/337272

**Comment by jarrah31** [comment]
Thank you for the suggestion, but unfortunately this picks up all my unavailable entities (around 40) whereas I only have one unavailable Z2M entity.

If possible I'd like to figure out why the following doesn't enable all my last_seen entities in HA please because this would give me a useful set of Z2M entities to monitor.
```
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
```
Within MQTT Explorer I can see that the sensor reported by HA has `enabled_by_default` set to true:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/3072303/164775682-48956f71-d410-4096-b360-e4b9b0514588.png">

However, the entity remains disabled within HA:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3072303/164775920-bea7d460-e407-4c72-9b95-72153fc4181e.png">

I'll be happy to run any further tests to help troubleshoot this issue.
