### ISSUE TITLE
Docker compose , fresh install conbee II adapter not connecting

### ISSUE THREAD

**Issue by h0mesmart** [Koenkk/zigbee2mqtt#12333]
### What happened?

Hi there, 

Hardware : Raspberry pi 3B+ Buster 64bit, Conbee II latest firmware, write access to serial checked -> success 

Docker compose : 
```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9002:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyAMA0:/dev/ttyACM0

```

configuration, in order to use the livolo TI0001-cover, extra config added as mentioned here [TI0001-cover](https://www.zigbee2mqtt.io/devices/TI0001-cover.html)

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8080
advanced:
  network_key:
       [HIDDEN]
  ext_pan_id:
    - 33
    - 117
    - 141
    - 25
    - 0
    - 75
    - 18
    - 0
  channel: 26

```

Log 

```
igbee2MQTT:info  2022-05-01 15:33:50: Starting Zigbee2MQTT version 1.25.0 (commit #6f1460e)
Zigbee2MQTT:info  2022-05-01 15:33:50: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:debug 2022-05-01 15:33:50: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[26],"extendedPanID":[33,117,141,25,0,75,18,0],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/ttyACM0"}}'
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-05-01 15:34:02: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-05-01 15:34:02: Failed to start zigbee
Zigbee2MQTT:error 2022-05-01 15:34:02: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-05-01 15:34:02: Exiting...
Zigbee2MQTT:error 2022-05-01 15:34:02: undefined

```

As you can see , not much helping information in the log. Even with log level to debug, I was unable to get more that  **undefined** 

Thanks for any help. 

### What did you expect to happen?

Zigbee2Mqtt start and fronted accessible

### Zigbee2MQTT version

I was unable to get this far

### Adapter firmware version

I was unable to get this far

### Adapter

Conbee II
