### ISSUE TITLE
include_device_information seems to be ignored

### ISSUE THREAD

**Issue by xiduzo** [Koenkk/zigbee2mqtt#12487]
### What happened?

When setting the `mqtt -> include_device_information` to `false` in the configuration.yaml the mqtt  message to home assistants still contains the device information.

Getting the following error in home assistant:

`Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'device': {'configuration_url': 'http://192.168.2.4/#/device/0x00124b002344990b/info', 'identifiers': ['zigbee2mqtt_0x00124b002344990b'], 'manufacturer': 'SONOFF', 'model': 'Motion sensor (SNZB-03)', 'name': '1028305567'}, 'device_class': 'battery', 'entity_category': 'diagnostic', 'json_attributes_topic': 'zigbee2mqtt/1028305567', 'name': '1028305567 battery low', 'payload_off': False, 'payload_on': True, 'state_topic': 'zigbee2mqtt/1028305567', 'unique_id': '0x00124b002344990b_battery_low_zigbee2mqtt', 'value_template': '{{ value_json.battery_low }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['device']['configuration_url']`

MQTT message in `homeassistant/sensor/0x00124b002344990b/battery/config`:

`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/1028305567/availability"}],"availability_mode":"all","device":{"configuration_url":"http://192.168.2.4/#/device/0x00124b002344990b/info","identifiers":["zigbee2mqtt_0x00124b002344990b"],"manufacturer":"SONOFF","model":"Motion sensor (SNZB-03)","name":"1028305567"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/1028305567","name":"1028305567 battery","state_class":"measurement","state_topic":"zigbee2mqtt/1028305567","unique_id":"0x00124b002344990b_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}`

### What did you expect to happen?

MQTT message on `homeassistant/sensor/*/*/config` not to contain `device` in the JSON message.

### How to reproduce it (minimal and precise)

Run home assistant, mqtt and zigbee2mqtt in docker

```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    network_mode: host #:8123
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /volume1/video:/media
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto
    network_mode: host # 1883 / 8883
    volumes:
      - ./mosquitto/mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto-logs:/mosquitto/logs
      - ./mosquitto/mosquitto-conf:/mosquitto/config
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    network_mode: host # 8080 / 8080
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
```

Zigbee2mqtt config:

```
homeassistant:
  status_topic: homeassistant/status
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: mosquitto
  server: mqtt://192.168.2.4:1883
  include_device_information: false
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  url: http://192.168.2.4
devices:
  '0x00124b00251e6bd1':
    friendly_name: 1094703D74
  '0x00124b00251f6cc5':
    friendly_name: 10947044C8
  '0x00124b002344990b':
    friendly_name: '1028305567'
    filtered_optimistic: []
    homeassistant: {}
    legacy: false
    optimistic: true
  '0x00124b002342fd37':
    friendly_name: 1028304A22
```

### Zigbee2MQTT version

1.25.1 commit: 3f6a137

### Adapter firmware version

20210708

### Adapter

Zigbee 3.0 USB dongle Plus
