### ISSUE TITLE
Neo NAS-AB02B2: Intermittent ignored commands

### ISSUE THREAD

**Issue by IAmTheMilkManMyMilkIsDelicious** [Koenkk/zigbee2mqtt#12542]
### What happened?

Due to the way [NAS-AB02B2](https://www.zigbee2mqtt.io/devices/NAS-AB02B2.html#neo-nas-ab02b2) is setup in z2m (or firmware) only one command can be sent at a time. When using the siren for multiple purposes (door bell, house alarm, notification beeps) you have to send each command (duration, melody, volume, alarm) one after another.

For example a door bell script:

1. payload: '{ "duration": 4 }'
    topic: zigbee2mqtt/Siren/set
2. payload: '{ "melody": 18 }'
    topic: zigbee2mqtt/Siren/set
3. payload: '{ "volume": "medium" }'
    topic: zigbee2mqtt/Siren/set
4. payload: '{ "alarm": true }'
    topic: zigbee2mqtt/Siren/set

The issue the device has is it will randomly ignore commands. There seems to be no specific command it will or won't ignore. Sometimes I will run this script and it won't set the duration, causing the alarm bell to play forever. Other times it doesn't set the volume and it's too quiet. Many times it just won't play a sound at all.
I figured this was to do with sending multiple commands in succession at the same time, so I added a 5 second delay between each command, and the random failures still happen.

### What did you expect to happen?

When running the script I mentioned, it should always play the correct melody for the correct duration

### How to reproduce it (minimal and precise)

I used homeassistant so my script looks like this:

```
alias: Set Door Bell
sequence:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Siren/set
      payload: '{ "duration": 4 }'
  - service: mqtt.publish
    data:
      payload: '{ "melody": 18 }'
      topic: zigbee2mqtt/Siren/set
  - service: mqtt.publish
    data:
      payload: '{ "volume": "medium" }'
      topic: zigbee2mqtt/Siren/set
  - service: mqtt.publish
    data:
      payload: '{ "alarm": true }'
      topic: zigbee2mqtt/Siren/set
mode: single
icon: mdi:bell
```

But I would also have another script such as:
```
alias: Set Siren House Alarm Mode
sequence:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Siren/set
      payload: '{ "duration": 900 }'
  - service: mqtt.publish
    data:
      payload: '{ "melody": 7 }'
      topic: zigbee2mqtt/Siren/set
  - service: mqtt.publish
    data:
      payload: '{ "volume": "high" }'
      topic: zigbee2mqtt/Siren/set
  - service: mqtt.publish
    data:
      payload: '{ "alarm": true }'
      topic: zigbee2mqtt/Siren/set

mode: single
icon: mdi:volume-vibrate
```

To reproduce, I simply run one script then the other a few times. I will always run into random issues where the device ignores certain commands.

### Zigbee2MQTT version

1.25.0 commit: 6f1460e4

### Adapter firmware version

20210120

### Adapter

zzh (CC2652R Stick)

### Debug log

The debug log doesn't show any warnings or errors and based on my scripts actually does successfully send every command to the device:

```
Publishing 'set' 'alarm' to 'Siren'
Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{ "alarm": true }'
Publishing 'set' 'alarm' to 'Siren'
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":13}],"seq":52992}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":13}],"seq":53248}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":13}],"seq":53504}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[15],"type":"Buffer"},"datatype":4,"dp":21}],"seq":53760}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[15],"type":"Buffer"},"datatype":4,"dp":21}],"seq":54016}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":5}],"seq":54528}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":13}],"seq":54784}' from endpoint 1 with groupID 0
Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{ "melody": 16 }'
Publishing 'set' 'melody' to 'Siren'
Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{ "volume": "high" }'
Publishing 'set' 'volume' to 'Siren'
Received MQTT message on 'zigbee2mqtt/Siren/set' with data '{ "alarm": true }'
Publishing 'set' 'alarm' to 'Siren'
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[16],"type":"Buffer"},"datatype":4,"dp":21}],"seq":55040}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":5}],"seq":55296}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":13}],"seq":55552}' from endpoint 1 with groupID 0
Received Zigbee message from 'Siren', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":13}],"seq":55808}' from endpoint 1 with groupID 0
```
