### ISSUE TITLE
Discrepance between home assistant configuration tab and configuration.yaml

### ISSUE THREAD

**Issue by jlo88** [Koenkk/zigbee2mqtt#12711]
### What happened?

I'm trying to understand the connection between configuration.yaml and the home assistant addon configuration tab. When I make changes in the home assistant configuration tab and save it I don't see the updates in the yaml file and vise versa. Which one is leading?

### What did you expect to happen?

home assistant addon configuration tab to have the same content as configuration.yaml

### How to reproduce it (minimal and precise)

Configuration.yaml:
```
{
  "external_converters": [],
  "devices": ["devices.yaml"],
  "groups": ["groups.yaml"],
  "homeassistant": true,
  "permit_join": false,
  "mqtt":
    {
      "base_topic": "zigbee2mqtt",
      "server": "mqtt://core-mosquitto",
      "user": "XXX",
      "password": "XXX",
    },
  "serial": { "port": "/dev/ttyACM0" },
  "advanced":
    {
      "log_level": "info",
      "pan_id": 6753,
      "channel": 11,
      "network_key": [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13],
      "availability_blocklist": [],
      "availability_passlist": [],
    },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": { "port": 8099 },
  "experimental": {},
}
```

home assistant addon in yaml: 

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: XXX
  password: XXX
serial:
  port: /dev/ttyACM0
```

Many options from the configuration.yaml are not visible in the addon. When I make a change in the addon the file on the disk is not updated and the other way around. Removing configuration.yaml results in an error after restarting and recreating the file. So I know I'm looking at the correct file. 

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20191106

### Adapter

20191106

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8837509/log.txt)
