### ISSUE TITLE
First start does not Work on RPi 3 running Ubuntu 20.04 with node 16

### ISSUE THREAD

**Issue by loewexy** [Koenkk/zigbee2mqtt#12798]
### What happened?

I ran `npm ci` and had to repeat this multiple times due to crashes and timeouts. I used a fresh checkout for every try. After this succeeded I tried to start zigbee2mqtt, but this hangs at Building Zigbee2MQTT. After a while to complete Raspberry Pi becomes unavailable the SSH connection breaks and only a hard Power Reset brings it back to life.

```bash
zigbee2mqtt@mirabel:~/zigbee2mqtt$ npm start

> zigbee2mqtt@1.25.2 start
> node index.js

Building Zigbee2MQTT... (initial build)Timeout, server mirabel not responding.
```

### What did you expect to happen?

The start should run without Problems.

### How to reproduce it (minimal and precise)

Install Ubuntu 20.04 for Raspberry PI on a Raspberry Pi 3
Run `curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -`
Run `sudo apt install -y nodejs git make g++ gcc build-essential`

Run `git clone --depth 1 https://github.com/Koenkk/zigbee2mqtt.git`
Change to directory and run `npm ci` for me I had to retry this and the step before multiple times til it worked.

Set config as:
```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mirabel.frdev.iot.intranet'

# Serial settings
serial:
  port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D95A62-if00

# Advanced Settings
advanced:
  network_key: GENERATE
```

Now run `npm start` the result is as described above.

### Zigbee2MQTT version

a252914 The current Master Yesterday

### Adapter firmware version

I do not get there

### Adapter

CC2531
