### ISSUE TITLE
Separate config files from app data

### ISSUE THREAD

**Issue by lukepighetti** [Koenkk/zigbee2mqtt#12822]
### What happened?

Went to bed, everything was working, woke up, none of my zigbee devices were functioning.

Checked logs, z2m container was restarting after error that it couldn't connect to `/dev/ttyUSB0` because the path didn't exist.

I am explicitly providing an alternative in my configuration

```yaml
serial:
  port: tcp://192.168.10.10:6638
```

### What did you expect to happen?

I expected it to use the configuration setting in all failure modes

### How to reproduce it (minimal and precise)

Unfortunately I do not have a MCVE for this issue

### Were you able to unblock yourself? How?

Yes. Restarting the container did not work, but recreating it (with docker-compose down/up) allowed it to work.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Configuration

```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.10.5
serial:
  port: tcp://192.168.10.10:6638
frontend:
  port: 8080
devices:
  "0x00158d0008027368":
    friendly_name: "0x00158d0008027368"
    description: main
  "0x00158d000804a462":
    friendly_name: "0x00158d000804a462"
```

#### When it first starts, working as expected

```
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-06-14 21:36:23: Logging to console and directory: '/app/data/log/2022-06-14.21-36-23' filename: log.txt
Zigbee2MQTT:info  2022-06-14 21:36:23: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)
Zigbee2MQTT:info  2022-06-14 21:36:23: Starting zigbee-herdsman (0.14.34)
Zigbee2MQTT:info  2022-06-14 21:36:25: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-06-14 21:36:25: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-06-14 21:36:25: Currently 2 devices are joined:
Zigbee2MQTT:info  2022-06-14 21:36:25: 0x00158d0008027368 (0x00158d0008027368): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2022-06-14 21:36:25: 0x00158d000804a462 (0x00158d000804a462): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2022-06-14 21:36:25: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-14 21:36:25: Connecting to MQTT server at mqtt://mqtt
Zigbee2MQTT:info  2022-06-14 21:36:25: Connected to MQTT server
Zigbee2MQTT:info  2022-06-14 21:36:25: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-06-14 21:36:25: Started frontend on port 0.0.0.0:8080
```

#### When the adapter is disconnected, and it erroneously uses `/dev/ttyUSB0` on restart

```
Zigbee2MQTT:error 2022-06-15 02:33:05: Adapter disconnected, stopping
Zigbee2MQTT:info  2022-06-15 02:33:05: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
Zigbee2MQTT:info  2022-06-15 02:33:05: Disconnecting from MQTT server
Zigbee2MQTT:info  2022-06-15 02:33:05: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2022-06-15 02:33:05: Failed to stop Zigbee2MQTT
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-06-15 02:33:07: Logging to console and directory: '/app/data/log/2022-06-15.02-33-07' filename: log.txt
Zigbee2MQTT:info  2022-06-15 02:33:07: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)
Zigbee2MQTT:info  2022-06-15 02:33:07: Starting zigbee-herdsman (0.14.34)
Zigbee2MQTT:error 2022-06-15 02:33:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-06-15 02:33:07: Failed to start zigbee
Zigbee2MQTT:error 2022-06-15 02:33:07: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-06-15 02:33:07: Exiting...
Zigbee2MQTT:error 2022-06-15 02:33:07: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
```

Then repeats

```
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-06-15 02:33:09: Logging to console and directory: '/app/data/log/2022-06-15.02-33-09' filename: log.txt
Zigbee2MQTT:info  2022-06-15 02:33:09: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)
Zigbee2MQTT:info  2022-06-15 02:33:09: Starting zigbee-herdsman (0.14.34)
Zigbee2MQTT:error 2022-06-15 02:33:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-06-15 02:33:09: Failed to start zigbee
Zigbee2MQTT:error 2022-06-15 02:33:09: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-06-15 02:33:09: Exiting...
Zigbee2MQTT:error 2022-06-15 02:33:09: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
```

#### When the container is manually recreated, and it correctly uses the network coordinator

```
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-06-15 06:46:40: Logging to console and directory: '/app/data/log/2022-06-15.06-46-40' filename: log.txt
Zigbee2MQTT:info  2022-06-15 06:46:40: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)
Zigbee2MQTT:info  2022-06-15 06:46:40: Starting zigbee-herdsman (0.14.34)
Zigbee2MQTT:info  2022-06-15 06:46:43: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-06-15 06:46:43: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-06-15 06:46:43: Currently 2 devices are joined:
Zigbee2MQTT:info  2022-06-15 06:46:43: 0x00158d0008027368 (0x00158d0008027368): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2022-06-15 06:46:43: 0x00158d000804a462 (0x00158d000804a462): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2022-06-15 06:46:43: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-15 06:46:43: Connecting to MQTT server at mqtt://mqtt
Zigbee2MQTT:info  2022-06-15 06:46:43: Connected to MQTT server
Zigbee2MQTT:info  2022-06-15 06:46:43: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-06-15 06:46:43: Started frontend on port 0.0.0.0:8080
```

**Comment by lukepighetti** [comment]
Just happened again. No known stimulus on my part.

**Comment by lukepighetti** [comment]
Just happened again, after adding an Aqara door/window sensor. Not sure if it was that or random like the others.

```
Using '/app/data' as data directory

Zigbee2MQTT:info  2022-06-28 19:51:53: Logging to console and directory: '/app/data/log/2022-06-28.19-51-53' filename: log.txt

Zigbee2MQTT:info  2022-06-28 19:51:53: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)

Zigbee2MQTT:info  2022-06-28 19:51:53: Starting zigbee-herdsman (0.14.34)

Zigbee2MQTT:error 2022-06-28 19:51:53: Error while starting zigbee-herdsman

Zigbee2MQTT:error 2022-06-28 19:51:53: Failed to start zigbee

Zigbee2MQTT:error 2022-06-28 19:51:53: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions

Zigbee2MQTT:error 2022-06-28 19:51:53: Exiting...

Zigbee2MQTT:error 2022-06-28 19:51:53: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'

    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)

    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)

    at /app/node_modules/@serialport/stream/lib/index.js:242:12

Using '/app/data' as data directory
```

**Comment by lukepighetti** [comment]
@Koenkk is there anything I can do to make triage easier?

**Comment by lukepighetti** [comment]
I am running it on macOS Docker, and I have no USB devices connected. My coordinator is a network coordinator.

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when the start fails?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by lukepighetti** [comment]
Last logs while working
```
Zigbee2MQTT:debug 2022-07-05 08:36:44: lumi.plug.maus01: Processed data into payload {"device_temperature":35,"state":"ON","energy":3.6,"consumption":3.6,"power":0}

Zigbee2MQTT:debug 2022-07-05 08:36:44: lumi.plug.maus01: Processed data into payload {"device_temperature":35,"state":"ON","energy":3.6,"consumption":3.6,"power":0}

Zigbee2MQTT:info  2022-07-05 08:36:44: MQTT publish: topic 'zigbee2mqtt/0x00158d0008069966', payload '{"consumption":3.6,"device_temperature":35,"energy":3.6,"linkquality":72,"power":0,"state":"ON","voltage":null}'

Zigbee2MQTT:debug 2022-07-05 08:38:49: Saving state to file /app/data/state.json
```

Container was restarted, fail loop begins (this loops over and over)
```
Using '/app/data' as data directory

Zigbee2MQTT:info  2022-07-05 08:46:21: Logging to console and directory: '/app/data/log/2022-07-05.08-46-21' filename: log.txt

Zigbee2MQTT:info  2022-07-05 08:46:21: Starting Zigbee2MQTT version 1.25.2 (commit #3c5854f)

Zigbee2MQTT:info  2022-07-05 08:46:21: Starting zigbee-herdsman (0.14.34)

Zigbee2MQTT:error 2022-07-05 08:46:22: Error while starting zigbee-herdsman

Zigbee2MQTT:error 2022-07-05 08:46:22: Failed to start zigbee

Zigbee2MQTT:error 2022-07-05 08:46:22: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions

Zigbee2MQTT:error 2022-07-05 08:46:22: Exiting...

Zigbee2MQTT:error 2022-07-05 08:46:22: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'

    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)

    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)

    at /app/node_modules/@serialport/stream/lib/index.js:242:12
```

Here's my data folder dump... however, the configuration is overridden with a local config file, and it is known to work

[zigbee2mqtt-data.zip](https://github.com/Koenkk/zigbee2mqtt/files/9046479/zigbee2mqtt-data.zip)



```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: tcp://192.168.4.40:6638
frontend:
  port: 8080
advanced:
  log_level: debug
devices:
  '0x00158d0008027368':
    friendly_name: '0x00158d0008027368'
    description: main
  '0x00158d000804a462':
    friendly_name: '0x00158d000804a462'
  '0x00158d00086516ea':
    friendly_name: '0x00158d00086516ea'
  '0x00158d0008068b1d':
    friendly_name: '0x00158d0008068b1d'
  '0x00158d0007e59d24':
    friendly_name: '0x00158d0007e59d24'
  '0x00158d0008069966':
    friendly_name: '0x00158d0008069966'
  '0x00158d00080689c5':
    friendly_name: '0x00158d00080689c5'
  '0x00158d000804995a':
    friendly_name: '0x00158d000804995a'
```

```yaml
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ~/.dockerfs/zigbee2mqtt-data:/app/data
      - ./zigbee2mqtt-configuration.yaml:/app/data/configuration.yaml <<<<<<<<<<
    depends_on:
      - mqtt
    ports:
      - 8080:8080
    environment:
      - TZ=America/New_York
    extra_hosts:
      coordinator: 192.168.4.40
```

**Comment by Koenkk** [comment]
I need the herdsman debug logging (this is not logged to a file but only to STDOUT).

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by lukepighetti** [comment]
OK, it looks like this is an issue with Docker. I'll summarize

```yaml
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ~/.dockerfs/zigbee2mqtt-data:/app/data
      - ./zigbee2mqtt-configuration.yaml:/app/data/configuration.yaml
```

As you can see, we have z2m `/app/data` being stored in my home folder, but we have `/app/data/configuration.yaml` checked into my repository.

For some reason, on a fresh start, docker-compose will happily handle these nested volumes. However, on a restart it appears that these volume maps degrade, and the second entry is ignored.

As far as I know, it is a strong best practice to have `/app/data` separate from configuration files, which typically live in `/config` or `/app/config`. (You can see ESPHome for an example of this, but I have seen it elsewhere).

This allows the consumer of the Docker image to specify a place for things like database files to be saved on disk, while checking configuration files into source control, without having these odd nested volumes.
