### ISSUE TITLE
Zigbee2MQTT not starting with “Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)”

### ISSUE THREAD

**Issue by enzodesena** [Koenkk/zigbee2mqtt#12887]
### What happened?

Hi everyone. This has been discussed elsewhere, but it looks like most discussions appear to be stale, so here goes. 

I am running HA on Raspberry Pi 3, with a Sonoff Universal Zigbee 3.0 USB Dongle Plus. The dongle works well with ZHA. However, I need Zigbee2MQTT. I follow the instructions but get the dreaded  "Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)". The full log is here: https://pastebin.com/gEwq17K2

I have tried the following, without success:
- Added the following lines to the mqtt section: "user: mqtt-user and password: my-password"
- Connected the dongle through a USB-extension cable
- Updated the Sonoff Dongle with the latest firmware
- Installed the Zigbee2MQTT Edge (i.e. developer branch) instead of Zigbee2MQTT
- Used as port /dev/serial/by-id/.... instead of /dev/ttyUSB0
- Tried two different power supplies. 
- Followed the instructions on ttps://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html , including: (a) checking that the port is correct; (b) Verifying that the user running Zigbee2MQTT as has write access to the port (I am assuming here that the user would be root. 
- All the usual stuff: restarting HA, restarting raspberry pi, reinstalling add-on. 

My full configuration is here: https://pastebin.com/52mTVPmg

Anything else I could try? Thanks in advance.

### How to reproduce it (minimal and precise)

Here is the configuration file:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-user
  password: my-password
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_3e2fe9a18412ec119a4b20c7bd930c07-if00-port0
```

### Zigbee2MQTT version

1.25.2-1

### Adapter firmware version

Latest

### Adapter

Sonoff Universal Zigbee 3.0 USB Dongle Plus

### Debug log

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
[21:31:51] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun socat (no readiness notification)
services-up: info: copying legacy longrun zigbee2mqtt (no readiness notification)
[21:32:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.2 start
> node index.js
Zigbee2MQTT:info  2022-06-20 21:32:32: Logging to console and directory: '/config/zigbee2mqtt/log/2022-06-20.21-32-31' filename: log.txt
Zigbee2MQTT:info  2022-06-20 21:32:32: Starting Zigbee2MQTT version 1.25.2 (commit #unknown)
Zigbee2MQTT:info  2022-06-20 21:32:32: Starting zigbee-herdsman (0.14.34)
Zigbee2MQTT:error 2022-06-20 21:32:53: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-06-20 21:32:54: Failed to start zigbee
Zigbee2MQTT:error 2022-06-20 21:32:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-06-20 21:32:54: Exiting...
Zigbee2MQTT:error 2022-06-20 21:32:55: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)
[21:33:06] INFO: Handing over control to Zigbee2mqtt Core ...
