### ISSUE TITLE
Frontend URL environment variable not working?

### ISSUE THREAD

**Issue by RoboMagus** [Koenkk/zigbee2mqtt#12911]
### What happened?

Trying to set the frontend URL through environment variable injected through docker compose, but setting `ZIGBEE2MQTT_CONFIG_FRONTEND_URL` does not seem to affect the Z2M configuration in any way. (Url remains unset when looking at the settings through the frontend).

### What did you expect to happen?

Correct configuration.

After browsing through the code related to ENV setting handling I _think_ this might be related to the parsing of the `oneOf` bit in settings.schema.json, not being translated as expected by `const envPart = path.reduce((acc, val) => `${acc}${val}_`, '');`.

Or I could be completely mistaken and my config is faulty...

### How to reproduce it (minimal and precise)

Compose snippet for Z2M
```yaml
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    hostname: zigbee2mqtt
    stop_grace_period: 1m30s
    restart: always
    depends_on:
      - mosquitto
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Volumes/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyAMA4:/dev/ttyACM0
    environment:
      - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=https://zigbee.${DOMAIN}
```

### Zigbee2MQTT version

1.25.2 commit: 3c5854fa

### Adapter firmware version

N/a

### Adapter

cc2652
