### ISSUE TITLE
Simplify sensor setup

### ISSUE THREAD

**Issue by PetricaM** [Koenkk/zigbee2mqtt#1303]
Current wiki suggests setting switches & buttons that only send a single payload as sensors however binary_sensor would simplify usage (only on/off state and simpler usage in automation trigger). The off_delay introduced in HA 0.81 will set the binary_sensor back to off without additional settings.

For buttons that send multiple type events (single/double/long/etc click) setting as binary_sensor is still possible but increases the number of entities HA will have to deal with.

Thus regular buttons could be set as:

```
binary_sensor:
  - platform: "mqtt"
    name: "binary_sensor_x"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: 'left' # or right or both case of a dual button switch (for double/long press it would be easier with sensor)
    payload_off: 'off' # it can be actually anything
    value_template: "{{ value_json.click }}"
    force_update: true
    off_delay: 1 # it will turn to off state without additional automation
```
instead of

```
sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
    expire_after: 1

```

Also, automation would be simpler:

```
automation:
  - alias: Respond to button clicks
    trigger:
      platform: state
      entity_id: binary_sensor.binary_sensor_x
      to: 'on'
    action:
      entity_id: light.bedroom
      service: light.toggle
```

instead of

```
automation:
  - alias: Respond to button clicks
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/<FRIENDLY_NAME'
    condition:
      condition: template
      value_template: '{{ "single" == trigger.payload_json.click }}'
    action:
      entity_id: light.bedroom
      service: light.toggle
```
or

```
automation:
  - alias: Respond to button click
    trigger:
      platform: state
      entity_id: sensor.my_switch_click
      to: 'single'
    action:
      entity_id: light.my_bulb_light
      service: light.toggle
```
