### ISSUE TITLE
HA reports MQTT deprecation errors on startup because of z2m config

### ISSUE THREAD

**Issue by derekoharrow** [Koenkk/zigbee2mqtt#13194]
### What happened?

Home Assistant complains on startup:

```
2022-07-17 20:20:28 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Manually configured MQTT switch(s) found under platform key 'switch', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/switch.mqtt/#new_format
2022-07-17 20:20:32 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
```

This seems to be caused by the zigbee2mqtt.yaml file I created by following the instructions at https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/guide/usage/integrations/home_assistant.md

These instructions need to be updated to reflect the deprecation of defining mqtt entities under switches and sensors as documented at https://www.home-assistant.io/integrations/sensor.mqtt/#new_format

### What did you expect to happen?

No HA errors on startup

### How to reproduce it (minimal and precise)

See above - use zigbee2mqtt.yaml example from https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/guide/usage/integrations/home_assistant.md

### Zigbee2MQTT version

1.26.0-dev commit: 4ef9ea7

### Adapter firmware version

20220219

### Adapter

zzh

**Comment by Koenkk** [comment]
Isn't it in the new format already?  e.g.

```yaml
mqtt:
  sensor:
    # Sensor for monitoring the bridge state
    - name: Zigbee2MQTT Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless
```
