### ISSUE TITLE
HA Status topic defaults to "hass/status" vs. "homeassistant/status"

### ISSUE THREAD

**Issue by ptr727** [Koenkk/zigbee2mqtt#13629]
### What happened?

Birth and will messages for HA did not seem to work.

Code:  
https://github.com/Koenkk/zigbee2mqtt/blob/a9b8808237554316c5c97e9d9c990048733779e8/lib/util/settings.ts#L121

Docs:  
https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html#advanced-configuration

Config defaults to "hass/status" per code.  
Docs say default should be "homeassistant/status".

HA [docs](https://www.home-assistant.io/docs/mqtt/birth_will/) say to use the MQTT GUI config, and default is "homeassistant/status".

Must manually change config else HA reports entities offline when restarting.

### How to reproduce it (minimal and precise)

Use simple HA integration:

```
homeassistant: true
```

Open advanced settings UI, UI reports the HA status topic is "hass/status".

Change HA config to advanced:

```
homeassistant:
  discovery_topic: "homeassistant"
  status_topic: "homeassistant/status"
  legacy_entity_attributes: false
  legacy_triggers: false
```

Settings UI now matches documentation.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20220219

### Adapter

tubez
