### ISSUE TITLE
[Feature request]: Add Conditionals to filtered_attributes and the ability to "bounce"

### ISSUE THREAD

**Issue by TrueCyberAxe** [Koenkk/zigbee2mqtt#13709]
### Is your feature request related to a problem? Please describe

I have bulbs that fail to turn off if sent a transition with the 0 brightness value

It would be nice to be able to specify matched values to filter certain attributes

Also in a similar vein there are also other things that dont get set correctly if you send the values as a single packet, just as there's a debonce would be nice if you could do a bounce aswell to split a packet if two values are together

### Describe the solution you'd like

For filtered_attributes:
to remove transition when brightness is 0 or state is off
```
filtered_attributes:
  - filter: 
      - "^transition$"
    brightness: 0
  - filter: 
      - "^transition$"
    state: "$[Oo][Oo][Ff]^"
```

For bounce: (Split may be a better name? just went with bounce as it was related to existing terminology)
```
bounce: [ "^xy_color$", "^color_temp$" ] 
```

ability to specify specific values when splitting
so if xy_colour and colour_temp were in the same packet
split into 2 payloads and set colourmode and transition for the same one that contains xy_color (and override any existing)
and the same for color_temp
```
bounce:
  - filter: [ "^xy_color$", "^color_temp$" ]
    group_values:
      xy_color:
        color_mode: xy
        transition: 0
     color_temp:
       color_mode: color_temp
```

and split order should match the bounce array so colour temp would get sent first then immediatly followed by rgb colour, all other attributes sent in the last packet or duplicated

### Describe alternatives you've considered

No existing solution other than a blanked block of the attribute

### Additional context

These have potential to add more dynamic behaviour through splitting and including transitions and such, especially with the attribute matching though the features is probably most useful for working around firmware bugs such as my initial use case.
