### ISSUE TITLE
IKEA LED2005R5 remain on, while Z2M reports state off

### ISSUE THREAD

**Issue by tivoo** [Koenkk/zigbee2mqtt#13902]
### What happened?

I have a fairly simple automation for my entryway where there are 3 IKEA LED2005R5 (https://www.zigbee2mqtt.io/devices/LED2005R5.html#ikea-led2005r5) lamps in one fixture that turn on when motion is detected and turn off after motion is not detected anymore. It's setup as a group in Z2M and HA only deals with the one 'Entryway Lights' entity that consists of the 3 seperate lamps registered in Z2M.

The Aqara  RTCGQ11LM (https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html#xiaomi-rtcgq11lm) is set to occupancy_timeout of 90 seconds and is the trigger for the automation.

### What did you expect to happen?

I expected that the three lights turn off after no occupancy is detected anymore. And although HA and Z2M report that the 3 lamps are off, they are actually still on. I have to manually turn the group on in HA and off again to actually switch them off. 

### How to reproduce it (minimal and precise)

The automation:
```
alias: Lights - On when Motion in Entryway
description: Light on for 90 seconds when motion detected in entryway
trigger:
  - platform: state
    entity_id:
      - binary_sensor.entryway_motion_sensor_occupancy
    to: "on"
condition:
  - condition: numeric_state
    entity_id: sensor.entryway_motion_sensor_illuminance_lux
    below: "40"
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.entryway_lights
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.entryway_motion_sensor_occupancy
        from: "on"
        to: "off"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: light.turn_off
    data:
      transition: 1
    target:
      entity_id:
        - light.entryway_lights
mode: restart
max_exceeded: silent
```

### Zigbee2MQTT version

1.27.2 

### Adapter firmware version

20220219

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

[entrway_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9506739/entrway_log.txt)
