### ISSUE TITLE
[Feature request]: Add support for scenes to Home Assistant extension

### ISSUE THREAD

**Issue by Kars-de-Jong** [Koenkk/zigbee2mqtt#13937]
### Is your feature request related to a problem? Please describe

Scenes created with Zigbee2MQTT are not available in Home Assistant.
You have to create them manually, they are not linked to devices.

### Describe the solution you'd like

I'd like scenes that are created in Zigbee2MQTT to be automatically added to Home Assistant through MQTT discovery.
Home Assistant has support for this (through the MQTT Scene integration).

### Describe alternatives you've considered

The alternative is manually adding MQTT scenes, which is not very user friendly.

### Additional context

I think this is a must-have feature ;-)

**Comment by Kars-de-Jong** [comment]
It may be stale, but I still think this would be a good feature.

**Comment by nakedible** [comment]
I think this is an important feature - in my set up, it doesn't make sense to ever configure any lights without setting a scene. All my lights are color temperature lights, so simply turning a light on is pointless (brightness is likely to be 1%) and also adjusting only brightness causes nasty results (really bright yellow lights or really dim blue lights) and also single light control is pointless as most rooms have more than one light source and just controlling one just creates a weird scene with one side of the room lit. And for me, evening dim lighting might mean ceiling spots fully off, and only the indirect light strips on, so not every light in a group is going to have the same settings for a scene.

So the only thing I want to call from the Home Assistant side is activating a scene for a certain group.

As I understand it, implementing this would mean extending [[lib/extension/homeassistant.ts](lib/extension/homeassistant.ts)](https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.ts) to somehow also represent active scenes for a group in the discovery topics. I don't know enough of Home Assistant to know what's the best way to do that, since Home Assistant scene support is also kind of non-existent - but at least some workarounds are definitely possible, like exposing each scene for a group as a separate "light" with just the "turn_on" action.

No promises I have time to actually conclude this, but @Koenkk do you think I should take a stab at implementing this? Would it likely get merged?

**Comment by Koenkk** [comment]
@nakedible I'm fine with that. Some tips:

- For the HA part https://www.home-assistant.io/integrations/scene.mqtt/ seems to fit well.
- You can access all scenes of a device in `homeassistant.ts` via `endpoint.getDevice().meta.scenes`

**Comment by nakedible** [comment]
For @Kars-de-Jong and others who stumble upon this... indeed manually configuring MQTT scenes does make them behave somewhat decently:

```
mqtt:
  scene:
    - name: Kaikki Päivä
      command_topic: zigbee2mqtt/Kaikki/set
      payload_on: '{ "scene_recall": 1 }'
      unique_id: 666_1_scene_zigbee2mqtt
      availability:
        - topic: zigbee2mqtt/bridge/state
    - name: Kaikki Ilta
      command_topic: zigbee2mqtt/Kaikki/set
      payload_on: '{ "scene_recall": 0 }'
      unique_id: 666_0_scene_zigbee2mqtt
      availability:
        - topic: zigbee2mqtt/bridge/state
    - name: Kaikki Yö
      command_topic: zigbee2mqtt/Kaikki/set
      payload_on: '{ "scene_recall": 5 }'
      unique_id: 666_5_scene_zigbee2mqtt
      availability:
        - topic: zigbee2mqtt/bridge/state
    - name: Kaikki Pois
      command_topic: zigbee2mqtt/Kaikki/set
      payload_on: '{ "scene_recall": 4 }'
      unique_id: 666_4_scene_zigbee2mqtt
      availability:
        - topic: zigbee2mqtt/bridge/state
```

I'll play around a bit with these, or possibly templated lights as well, to figure out what's the best way for these to be represented on the HA side.
