### ISSUE TITLE
Simulated brightness entity doesn't appear in Home Assistant

### ISSUE THREAD

**Issue by YodaDaCoda** [Koenkk/zigbee2mqtt#13981]
### What happened?

I set up `simulated_brightness` on my [E1744](https://www.zigbee2mqtt.io/devices/E1744.html) & observed the brightness attribute changing via the State tab in the webui as I turned the remote. I went to Home Assistant to use the new brightness on an automation and couldn't find it.

### What did you expect to happen?

I expected to find a brightness entity attached to the device in Home Assistant.

### How to reproduce it (minimal and precise)

Pair E1744 device. Observe it is added to Home assistant. Configure `simulated_brightness` in z2m. Observe the brightness changes within the state as the remote is rotated. Note the brightness does not appear in Home Assistant.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

zzh!

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9547854/log.txt)

**Comment by ModuCZ** [comment]
I have experienced the same issue.  Brightness value is visible in MQTT Info inside HA.

**Comment by YodaDaCoda** [comment]
Issue persists.

**Comment by AndreKR** [comment]
The issue is still valid.

**Comment by thefelixno** [comment]
had to activate legacy entity attributes for the ha-integrations, now works for me

```yml
homeassistant:
  # Optional: Home Assistant legacy entity attributes, (default: shown below), when enabled:
  # Zigbee2MQTT will send additional states as attributes with each entity. For example,
  # A temperature & humidity sensor will have 2 entities for the temperature and
  # humidity, with this setting enabled both entities will also have
  # an temperature and humidity attribute.
  # Note: Disabling this option, requires a Home Assistant restart
  legacy_entity_attributes: true
```
