### ISSUE TITLE
Efficient way to do auto response?

### ISSUE THREAD

**Issue by he902** [Koenkk/zigbee2mqtt#1402]
My Yunmi Door Lock reports 'genPollCtrl' message every 20mins to the coordinator, and the coordinator needs to write attrId 16653 with attrData 0x0 when 'genPollCtrl' received.
Currently I'm doing it via HA Automation with MQTT to trigger the write action.
But I think it is not efficient and reliable by going through outside system (HA & MQTT). Any way inside zigbee2mqtt can do such task?

Here is the HA Automation I used:
```
- alias: 'Yunmi Lock Poll'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/yunmi_lock
  condition:
    condition: template
    value_template: "{{ 'poll' in trigger.payload_json }}"
  action:
    - service: mqtt.publish
      data:
        payload: "Active"
        topic: "zigbee2mqtt/yunmi_lock/set"
        retain: false
```
Here is the zigbee2mqtt debug log:
```
  zigbee2mqtt:debug 4/10/2019, 5:08:08 PM Received zigbee message of type 'attReport' with data '{"cid":"genPollCtrl","data":{"20480":0}}' of device 'FNB56-DOR23FB1.3' (0x00158d0002ac2222)
  zigbee2mqtt:info 4/10/2019, 5:08:08 PM MQTT publish: topic 'zigbee2mqtt/yunmi_lock', payload '{"date_poll":"4/10/2019, 5:08:08 PM","poll":0,"linkquality":68}'
  zigbee2mqtt:debug 4/10/2019, 5:08:08 PM Received MQTT message on 'zigbee2mqtt/yunmi_lock/set' with data 'Active'
  zigbee2mqtt:info 4/10/2019, 5:08:08 PM Zigbee publish to device '0x00158d0002ac2222', closuresDoorLock - write - [{"attrId":16653,"dataType":32,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - null
```
