### ISSUE TITLE
[Feature request]: Option to expose frontend throught HTTPS

### ISSUE THREAD

**Issue by PheelTi** [Koenkk/zigbee2mqtt#14136]
### Is your feature request related to a problem? Please describe

It would be great to make the frontend exposed through HTTPS.

### Describe the solution you'd like

in configuration.yaml, add :
```yaml
frontend:
  secure:
    ssl_cert: [path to cert file]
    ssl_key: [path to key file]
```

then adapt code in the `start()` function in [lib/extension/frontend.ts](https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/frontend.ts) 

### Describe alternatives you've considered

It can be handled with a proxy like Traefik... I do use one for my websites exposed on the internet.
but I do not want to use such proxy for LAN access.

### Additional context

I may try to code this by myself as it is not really complicated (I suppose), and submit a pull request.
