### ISSUE TITLE
Network stuck at ping to Xiaomi Wall Switch

### ISSUE THREAD

**Issue by lenisko** [Koenkk/zigbee2mqtt#1424]
# Bug Report
## What happened
Whole network got blocked/stuck after unsuccessful ping to one of devices (Xiaomi Wall Switch - which is working just fine manually).
It's `QBKG04LM / office_light` on graph.
It has happened after few hours of non-problematic work.

## What did you expect to happen
Not block whole network? :-)

## How to reproduce it (minimal and precise)
No idea.

But `zigbee2mqtt` restart **and** module re-plug is solving problem for few hours, after that it's still hanging.

## Debug Info
zigbee2mqtt version: 1.3.0 / 00ebd441a0f804e1bbcae4c2a03cbe9698b58010
CC2530 firmware version: 20190223 default
log: https://hastebin.com/ginogokupa.log (starting at `4/13/2019, 9:58:53 PM`)
device: cc2530
configuration:
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.1'
serial:
  port: /dev/zigbee
advanced:
  report: false
  rtscts: false
  channel: 11
  baudrate: 115200
  log_level: debug
  log_directory: data/log/
  cache_state: true
  soft_reset_timeout: 0
  network_key: ...
devices: devices.yaml
groups: groups.yaml
```

network graph:
![4bebc011-a566-4ef1-93d0-e2b604560aa7](https://user-images.githubusercontent.com/10072920/56096504-69fba080-5ee9-11e9-9ffa-59b3c43eda4a.png)
