### ISSUE TITLE
Startup hangs on Starting zigbee-herdsman

### ISSUE THREAD

**Issue by Lovasz-Akos** [Koenkk/zigbee2mqtt#14325]
### What happened?

Trying to start zigbee2mqtt 1.28 it hangs on Starting zigbee-herdsman (0.14.62), no error just stops there.

### What did you expect to happen?

Startup continues and zigbee2mqtt launches

### How to reproduce it (minimal and precise)

followed install instructions all the way even npm ci returned with expected message.
then went to npm start and it's hanging, with barely and CPU or RAM usage, so probably not even doing anything

### Zigbee2MQTT version

1.28

### Adapter firmware version

v8

### Adapter

ezsp

### Debug log

```bash
Zigbee2MQTT:info  2022-10-04 12:42:24: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-04 12:42:24: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:debug 2022-10-04 12:42:24: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/home/admin/zigbee2mqtt-1.28.0/data/coordinator_backup.json","databaseBackupPath":"/home/admin/zigbee2mqtt-1.28.0/data/database.db.backup","databasePath":"/home/admin/zigbee2mqtt-1.28.0/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:debug 2022-10-04 12:47:24: Saving state to file /home/admin/zigbee2mqtt-1.28.0/data/state.json
```

**Comment by Lovasz-Akos** [comment]
Additional info:
` ls -l /dev/serial/by-id` returns `usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB0`

`test -w /dev/ttyUSB0 && echo success || echo failure` returns `success`

my config is:
```yaml
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  port: /dev/ttyUSB0
  adapter: ezsp

frontend: true
advanced:
  log_level: debug

```
