### ISSUE TITLE
[Feature Request] Send powerusage (Watt) values to MQTT by period (e.g. every 60 seconds)

### ISSUE THREAD

**Issue by tunip** [Koenkk/zigbee2mqtt#1433]
If you have automations based on powerusage and time (e.g. washer finished, when...), we could integrate period based output.

Example:
washer < 5 watt within 3 minutes (e.g. check every minute) means:
 If the washer consumes under 5 Watt within 3 minutes its finished.
 
As the values are send now by its changed state on value you are not able to create automation (in Home Assistant) like above.

A device specific config could look like this:
```
devices:
  '0x001532d0003f82999':
    friendly_name: 'power_plug'
    period_time: 60
```
period_time would be seconds and Zigbee2mqtt would send every "fixed" 60 seconds the last/avg value of the poweusage (Power, Voltage, Current) to the MQTT broker.
