### ISSUE TITLE
Zigbee2MQTT doesn't retain HA Discovery Payloads

### ISSUE THREAD

**Issue by droans** [Koenkk/zigbee2mqtt#14381]
### What happened?

This has been occurring since I started using Z2M a couple years back and took me a long time to track down.

Zigbee2MQTT does not set the retain flag for any messages under `homeassistant/status`. This issue causes Home Assistant to mark all devices as unavailable, even when they are running appropriately.  

The only similar issues I can find are with people using the built-in HA MQTT broker. However, I am running mine as a separate container. I even have Z2M set as relying on HA to start up first, but it still fails maybe 1/3 of the time. I'm guessing that Z2M starts up quicker than HA in those instances. 

Environment:

* Docker
* HA, Z2M, and Mosquitto Broker all in separate containers

Relevant Configuration:

```
homeassistant:
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://XX.XX.XX.XX
  user: zigbee2mqtt
  password: XXXXX
  keepalive: 60
  reject_unauthorized: false
  version: 4
  include_device_information: true
advanced:
  legacy_availability_payload: false
availability: false
```

### What did you expect to happen?

Zigbee2MQTT should be setting the retain flag on discovery payloads so that HA will find the device upon a restart.

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20220219

### Adapter

LaunchXL
