### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/dev/serial/by-id/package.json'

### ISSUE THREAD

**Issue by jandechent** [Koenkk/zigbee2mqtt#14457]
### What happened?

feshly installed today, configured and I get 
`verbose stack Error: ENOENT: no such file or directory, open '/dev/serial/by-id/package.json'`

### What did you expect to happen?

I tried both by-id and USB directly using this config file

```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_34b306362b45ec11998b96fd6f14af06-if00-port
  #port: /dev/ttyUSB0
```
So I had not expected to see any error with package.json in it. How does this come there?
### How to reproduce it (minimal and precise)

happend very time. 

### Zigbee2MQTT version

todays git 

### Adapter firmware version

I dont get ot that

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.15.0
2 info using node@v16.17.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 10ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/dev/serial/by-id/.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 30ms
19 timing npm:load:configload Completed in 31ms
20 timing npm:load:mkdirpcache Completed in 3ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm start
23 verbose argv "start"
24 timing npm:load:setTitle Completed in 3ms
25 timing config:load:flatten Completed in 9ms
26 timing npm:load:display Completed in 14ms
27 verbose logfile logs-max:10 dir:/root/.npm/_logs
28 verbose logfile /root/.npm/_logs/2022-10-12T18_12_43_502Z-debug-0.log
29 timing npm:load:logFile Completed in 14ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 70ms
33 silly logfile start cleaning logs, removing 3 files
34 timing command:run-script Completed in 8ms
35 timing command:start Completed in 17ms
36 verbose stack Error: ENOENT: no such file or directory, open '/dev/serial/by-id/package.json'

```
