### ISSUE TITLE
Xiaomi WSDCGQ01LM device send data, but not visible on HA devices / entities

### ISSUE THREAD

**Issue by thrasheri** [Koenkk/zigbee2mqtt#1460]
I set up Zigbee2Mqtt and home assistant internal mqtt server to connect all my zigbee devices to HA. The setup went fine and log state that Zigbee2Mqtt is connected to the mqtt server. I paired one Xiaomi WSDCGQ01LM and Zigbee2Mqtt is receiving the values from the sensor. Unfortunately the is no sign of the sensor in HA entities / devices. Did I miss something? 

**Home assistant configuration.yaml :**

```
mqtt:
  password: mqttpassword
  discovery: true
```

**zigbee2mqtt configuration.yaml:**

```
devices:
  '0x00158d000255927f':
    friendly_name: lampo_elmerinhuone
    homeassistant:
      device:
        identifiers: '0x00158d000255927f'
        name: elmerinhuone
      temperature:
        name: elmerinhuone
        unique_id: lampo_elmerinhuone'
    retain: false
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: mypassword
  server: mqtt://homeassistant
  user: homeassistant
permit_join: true
serial:
  port: /dev/ttyACM0
```

**Zigbee2Mqtt Logs:** 

` zigbee2mqtt:info 4/22/2019, 11:25:00 AM Zigbee: allowing new devices to join.
  zigbee2mqtt:info 4/22/2019, 11:25:00 AM Connecting to MQTT server at mqtt://homeassistant
  zigbee2mqtt:info 4/22/2019, 11:25:00 AM zigbee-shepherd ready
  zigbee2mqtt:info 4/22/2019, 11:25:02 AM Connected to MQTT server
  zigbee2mqtt:info 4/22/2019, 11:25:02 AM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
  zigbee2mqtt:info 4/22/2019, 11:25:02 AM MQTT publish: topic 'zigbee2mqtt/lampo_elmerinhuone', payload '{"temperature":22.42,"linkquality":52,"humidity":29.93,"battery":91,"voltage":2985}'
  zigbee2mqtt:info 4/22/2019, 11:25:02 AM MQTT publish: topic 'homeassistant/sensor/0x00158d000255927f/temperature/config', payload '{"unit_of_measurement":"°C","device_class":"temperature","value_template":"{{ value_json.temperature }}","state_topic":"zigbee2mqtt/lampo_elmerinhuone","json_attributes_topic":"zigbee2mqtt/lampo_elmerinhuone","name":"elmerinhuone","unique_id":"lampo_elmerinhuone'","device":{"identifiers":"0x00158d000255927f","name":"elmerinhuone","sw_version":"Zigbee2mqtt 1.3.1","model":"MiJia temperature & humidity sensor  (WSDCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'`
