### ISSUE TITLE
Crash loop on MacOS

### ISSUE THREAD

**Issue by Kautenja** [Koenkk/zigbee2mqtt#14795]
### What happened?

`docker-compose up -d` is stuck in a crash loop. It can't find the device `/dev/cu.usbserial-1440`, which exists, can be flashed, and is detectable through other means.

### What did you expect to happen?

I expect the service to launch and find the adapter

### How to reproduce it (minimal and precise)

_out of the box boilerplate for running in docker_

I had to add the `priveleged` flags to the services; the image to come up at all without it.

docker compose file

```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    privileged: true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/cu.usbserial-1440:/dev/cu.usbserial-1440
    privileged: true

```

config file

```
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/cu.usbserial-1440
frontend:
  port: 8080
advanced:
  network_key:
    - 230
    - 235
    - 181
    - 84
    - 188
    - 173
    - 45
    - 37
    - 177
    - 3
    - 121
    - 18
    - 177
    - 91
    - 95
    - 212
```

### Zigbee2MQTT version

latest

### Adapter firmware version

NA

### Adapter

Sonoff

### Debug log

```
zigbee2mqtt    | Zigbee2MQTT:info  2022-11-03 21:30:04: Logging to console and directory: '/app/data/log/2022-11-03.21-30-04' filename: log.txt
zigbee2mqtt    | Zigbee2MQTT:info  2022-11-03 21:30:04: Starting Zigbee2MQTT version 1.23.0 (commit #6ea61ba)
zigbee2mqtt    | Zigbee2MQTT:info  2022-11-03 21:30:04: Starting zigbee-herdsman (0.14.10)
zigbee2mqtt    | Zigbee2MQTT:error 2022-11-03 21:30:04: Error while starting zigbee-herdsman
zigbee2mqtt    | Zigbee2MQTT:error 2022-11-03 21:30:04: Failed to start zigbee
zigbee2mqtt    | Zigbee2MQTT:error 2022-11-03 21:30:04: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
zigbee2mqtt    | Zigbee2MQTT:error 2022-11-03 21:30:04: Exiting...
zigbee2mqtt    | Zigbee2MQTT:error 2022-11-03 21:30:04: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/cu.usbserial-1440'
zigbee2mqtt    |     at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
zigbee2mqtt    |     at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee2mqtt    |     at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12

```
