### ISSUE TITLE
Cannot set properties of undefined (setting 'installed_version')

### ISSUE THREAD

**Issue by vladyspavlov** [Koenkk/zigbee2mqtt#14917]
### What happened?

When attempting to launch the latest zigbee2mqtt edge, an error occurred. It seems like an error appeared after this PR https://github.com/Koenkk/zigbee2mqtt/pull/14905

### How to reproduce it (minimal and precise)

Start zigbee2mqtt edge

### Zigbee2MQTT version

1.28.2-dev (commit #98a6a2d)

### Adapter firmware version

20220219

### Adapter

Sonoff CC2652P

### Debug log

```
TypeError: Cannot set properties of undefined (setting 'installed_version')
    at HomeAssistant.adjustMessageBeforePublish (/app/lib/extension/homeassistant.ts:1465:51)
    at Controller.publishEntityState (/app/lib/controller.ts:266:49)
    at Object.publishLastSeen (/app/lib/util/utils.ts:348:9)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:157:19)
```

**Comment by Koenkk** [comment]
Can you provide your z2m `configuration.yaml`? The update property should always be mocked.

**Comment by vladyspavlov** [comment]
<details>
<summary>configuration.yaml</summary>

```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: mqttpass
  server: mqtt://core-mosquitto:1883
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_eae9d457011aec11a0bf77e5f01c6278-if00-port0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
device_options:
  retain: true
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  transmit_power: 15
availability: true
```
</details>
