### ISSUE TITLE
Can't control Groups via MQTT:  TypeError: Cannot read properties of null (reading 'endpoints')'

### ISSUE THREAD

**Issue by TobiasMuellerES** [Koenkk/zigbee2mqtt#15397]
### What happened?

I added 2 [Busch Jaeger Light Switch](https://www.zigbee2mqtt.io/devices/6735_6736_6737.html#busch-jaeger-6735%252F6736%252F6737) and one [Phlipps Hue Lightstrip ](https://www.zigbee2mqtt.io/devices/915005106701.html#philips-915005106701) to a zigbee2mqtt group. 

I can switch all devices by themself without any problem. When i try to switch them on/off as group i get the error: Publish 'set' 'state' to 'z2m_eingangsbereich' failed: 'TypeError: Cannot read properties of null (reading 'endpoints')'

Could the Home Assistant Configuration be a problem? For the busch jaeger light switches i add the home assistant configuration to expose the switches as light.
```
  '0xd85def11a100007f':
    friendly_name: diele_lichtschalter
    homeassistant:
      name: Diele Lichtschalter
      switch:
        type: light
        object_id: light
      light:
        name: Diele
        value_template: null
        state_value_template: '{{ value_json.state }}'
```

### What did you expect to happen?

The group will go on and off when i send the appropriate command via mqtt.

### How to reproduce it (minimal and precise)

Some groups with lights are working and other not. i don't know why. 
I have other groups with busch jaeger light switches and bulbs and they're working without problem.

### Zigbee2MQTT version

1.28.4 commit: 52e545f

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

Info 2022-12-06 17:50:25MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
Info 2022-12-06 17:50:25MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
Info 2022-12-06 17:50:30MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
Info 2022-12-06 17:50:30MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
Debug 2022-12-06 17:50:32Received MQTT message on 'zigbee2mqtt/z2m_eingangsbereich/set' with data 'ON'
Debug 2022-12-06 17:50:32Publishing 'set' 'state' to 'z2m_eingangsbereich'
Error 2022-12-06 17:50:32Publish 'set' 'state' to 'z2m_eingangsbereich' failed: 'TypeError: Cannot read properties of null (reading 'endpoints')'
Info 2022-12-06 17:50:35MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
Info 2022-12-06 17:50:35MQTT publish: topic 'zigbee2mqtt/z2m_eingangsbereich', payload '{"brightness":254,"state":"OFF"}'
