### ISSUE TITLE
Network commissioning timed out - issue with 2 networks

### ISSUE THREAD

**Issue by CaliLuke** [Koenkk/zigbee2mqtt#15403]
### What happened?

I'm trying to run zigbee2mqtt and ZHA at the same time using 2 sonoff usb dongles.

The ZHA network is configured as follows:

```
PAN ID: 1A62
Extended PAN ID: 00:12:4b:00:1c:d6:ed:01
Channel: 11
Coordinator IEEE: 00:12:4b:00:1c:d6:ed:01
Network key: 01:03:05:07:09:0b:0d:0f:00:02:04:06:08:0a:0c:0d
Radio type: znp
```
the device I'm using with this integration is located at /dev/ttyUSB0 and works fine.

My Zigbee2mqtt configuration is:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB1
advanced:
  pan_id: 2400
  ext_pan_id:
    - 14
    - 33
    - 98
    - 13
    - 76
    - 36
    - 44
    - 22
  channel: 25
  network_key: GENERATE
zigbee_herdsman_debug: true
```

when I try starting zigbee2mqtt, after a while I get this log:

```
[12:40:40] INFO: Preparing to start...
[12:40:41] INFO: Socat not enabled
[12:40:43] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-12-06 12:40:48: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-06.12-40-48' filename: log.txt
Zigbee2MQTT:info  2022-12-06 12:40:48: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-06 12:40:48: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:error 2022-12-06 12:41:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-06 12:41:54: Failed to start zigbee
Zigbee2MQTT:error 2022-12-06 12:41:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-06 12:41:54: Exiting...
Zigbee2MQTT:error 2022-12-06 12:41:54: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```

I did read the possible solutions at https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html and googled a bunch but I can't figure out what's happening.

Am I triggering a bug or is there anything else I can do to debug the situation?

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

unsure - can't start UI

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus Gateway

### Debug log

debug 2022-12-06 12:53:52: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
info  2022-12-06 12:53:52: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-06.12-53-52' filename: log.txt
debug 2022-12-06 12:53:52: Removing old log directory '/config/zigbee2mqtt/log/2022-10-18.23-40-59'
info  2022-12-06 12:53:52: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
info  2022-12-06 12:53:52: Starting zigbee-herdsman (0.14.76)
debug 2022-12-06 12:53:52: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB1"}}'
error 2022-12-06 12:54:57: Error while starting zigbee-herdsman
error 2022-12-06 12:54:57: Failed to start zigbee
error 2022-12-06 12:54:57: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-12-06 12:54:57: Exiting...
error 2022-12-06 12:54:57: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
