### ISSUE TITLE
[Feature request]: Full blown `configuration.yaml` (with descriptions)

### ISSUE THREAD

**Issue by milkpirate** [Koenkk/zigbee2mqtt#15594]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I once found a `configuration.yaml` with all options and description, my version looks like so:

```yaml
# Required: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: false

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: false

frontend:
  # Optional, default 8080
  port: 8881
  # Optional, default 0.0.0.0
  host: 0.0.0.0
  # Optional, enables authentication, disabled by default
#  auth_token: your-secret-token

devices: devices.yaml
# groups: groups.yaml

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtts://mosquitto:8884'
  # Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
  ca: /usr/local/share/ca-certificates/root_ca.crt
#  # Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
#  key: '/etc/ssl/server.pem'
#  cert: '/etc/ssl/server.crt'
#  # Optional: MQTT server authentication user (default: nothing)
  user: "{{ mosquitto.users.zigbee2mqtt.name }}"
#  # Optional: MQTT server authentication password (default: nothing)
  password: "{{ mosquitto.users.zigbee2mqtt.pass }}"
#  # Optional: MQTT client ID (default: nothing)
#  client_id: 'zigbee2mqtt'
#  # Optional: disable self-signed SSL certificates (default: true)
#  reject_unauthorized: true
#  # Optional: Include device information to mqtt messages (default: false)
  include_device_information: true
#  # Optional: MQTT keepalive in seconds (default: 60)
#  keepalive: 60
#  # Optional: MQTT protocol version (default: 4), set this to 5 if you
#  # use the 'retention' device specific configuration
  version: 5

# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/ttyZigBee
#  # Optional: disable LED of the adapter if supported (default: false)
#  disable_led: false
#  # Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz)
#  adapter: null

# Optional: Block devices from the network (by ieeeAddr) (default: empty)
# Previously called `ban` (which is deprecated)
#blocklist:
#  - '0x000b57fffec6a5b2'

# Optional: Allow only certain devices to join the network (by ieeeAddr)
# Note that all devices not on the passlist will be removed from the network!
# (default: empty)
# Previously called `whitelist` (which is deprecated)
#passlist:
#  - '0x000b57fffec6a5b3'

# Optional: advanced settings
#advanced:
#  # Optional: ZigBee pan ID (default: shown below)
#  pan_id: 0x1a62
#  # Optional: Zigbee extended pan ID (default: shown below)
#  ext_pan_id: [0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
#  # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
#  # (default: 11)
#  channel: 11
#  # Optional: state caching, MQTT message payload will contain all attributes, not only changed ones.
#  # Has to be true when integrating via Home Assistant (default: true)
#  cache_state: true
#  # Optional: persist cached state, only used when cache_state: true (default: true)
#  cache_state_persistent: true
#  # Optional: send cached state on startup, only used when cache_state_persistent: true (default: true)
#  cache_state_send_on_startup: true
#  # Optional: Logging level, options: debug, info, warn, error (default: info)
  log_level: info
#  # Optional: Location of log directory (default: shown below)
#  log_directory: data/log/%TIMESTAMP%
#  # Optional: Log file name, can also contain timestamp, e.g.: zigbee2mqtt_%TIMESTAMP%.log (default: shown below)
#  log_file: log.txt
#  # Optional: Log rotation (default: shown below)
#  log_rotation: true
#  # Optional: Output location of the log (default: shown below), leave empty to supress logging (log_output: [])
#  # possible options: 'console', 'file', 'syslog'
#  log_output:
#    - console
#    - file
#  # Optional: syslog configuration, skip values or entirely to use defaults. Only use when 'syslog' in 'log_output' (see above)
#  log_syslog:
#    host: localhost # The host running syslogd, defaults to localhost.
#    port: 123 # The port on the host that syslog is running on, defaults to syslogd's default port.
#    protocol: tcp4 # The network protocol to log over (e.g. tcp4, udp4, tls4, unix, unix-connect, etc).
#    path:  /dev/log # The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).
#    pid: process.pid # PID of the process that log messages are coming from (Default process.pid).
#    facility: local0 # Syslog facility to use (Default: local0).
#    localhost: localhost # Host to indicate that log messages are coming from (Default: localhost).
#    type: 5424 # The type of the syslog protocol to use (Default: BSD, also valid: 5424).
#    app_name: Zigbee2MQTT # The name of the application (Default: Zigbee2MQTT).
#    eol: '\n' # The end of line character to be added to the end of the message (Default: Message without modifications).
#  # Optional: Baudrate for serial port (default: 115200 for Z-Stack, 38400 for Deconz)
#  baudrate: 115200
#  # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
#  rtscts: false
#  # Optional: soft reset ZNP after timeout (in seconds); 0 is disabled (default: 0)
#  soft_reset_timeout: 0
  # Optional: network encryption key, will improve security (Note: changing requires repairing of all devices) (default: shown below)
  network_key: {{ zigbee2mqtt.network_key }}
#  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
#  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
#  last_seen: 'disable'
#  # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
#  elapsed: false
#  # Optional: Availability timeout in seconds, disabled by default (0).
#  # When enabled, devices will be checked if they are still online.
#  # Only AC powered routers are checked for availability. (default: 0)
  availability_timeout: 60
#  # Optional: Prevent devices from being checked for availability (default: empty)
#  # Previously called `availability_blacklist` (which is deprecated)
#  availability_blocklist:
#    - DEVICE_FRIENDLY_NAME or DEVICE_IEEE_ADDRESS
#  # Optional: Only enable availability check for certain devices (default: empty)
#  # Previously called `availability_whitelist` (which is deprecated)
#  availability_passlist:
#    - DEVICE_FRIENDLY_NAME or DEVICE_IEEE_ADDRESS
#  # Optional: Enables report feature (see information -> report for more details) (default: false)
#  report: true
#  # Optional: Home Assistant discovery topic (default: shown below)
#  homeassistant_discovery_topic: 'homeassistant'
#  # Optional: Home Assistant status topic (default: shown below)
#  homeassistant_status_topic: 'homeassistant/status'
#  # Optional: Home Assistant legacy triggers (default: shown below), when enabled:
#  # - Zigbee2mqt will send an empty 'action' or 'click' after one has been send
#  # - A 'sensor_action' and 'sensor_click' will be discoverd
#  homeassistant_legacy_triggers: true
#  # Optional: log timestamp format (default: shown below)
#  timestamp_format: 'YYYY-MM-DD HH:mm:ss'
#  # Optional: configure adapter concurrency (e.g. 2 for CC2531 or 16 for CC26X2R1) (default: null, uses recommended value)
#  adapter_concurrent: null

# Optional: experimental options
experimental:
#  # Optional: MQTT output type: json, attribute or attribute_and_json (default: shown below)
#  # Examples when 'state' of a device is published
#  # json: topic: 'zigbee2mqtt/my_bulb' payload '{"state": "ON"}'
#  # attribute: topic 'zigbee2mqtt/my_bulb/state' payload 'ON"
#  # attribute_and_json: both json and attribute (see above)
#  output: 'json'
  new_api: true

## Optional: networkmap options
#map_options:
#  graphviz:
#    # Optional: Colors to be used in the graphviz network map (default: shown below)
#    colors:
#      fill:
#        enddevice: '#fff8ce'
#        coordinator: '#e04e5d'
#        router: '#4ea3e0'
#      font:
#        coordinator: '#ffffff'
#        router: '#ffffff'
#        enddevice: '#000000'
#      line:
#        active: '#009900'
#        inactive: '#994444'

## Optional: see 'Device specific configuration' below
#device_options: {}
## Optional, see 'External converters configuration' below
#external_converters: []
```

I updated to 1.28.4 lately and was wondering if there are other/new options. I tired to find full blown and documented one for the new version but I only found partials or minimal configs. Could you supply one?

### Describe alternatives you've considered

N/A

### Additional context

N/A
