### ISSUE TITLE
SOFTWARE_FAILURE while configuring

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#15627]
### What happened?

I saw an error popup, so I went into the log. This showed up:

```
error 2022-12-18 18:38:49Failed to configure 'CO-Melder R's Zimmer ', attempt 1 (Error: ConfigureReporting 0x[redacted]/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.batteryAlarmState (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:71:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/feibit.js:92:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))
```

Device is a Feibit SCA01ZB.

Other details:

```
Zigbee Model
    FNB56-COS06FB1.7
Zigbee Manufacturer
    feibit
Firmware build date
    20171215
Firmware version
    
```

The state currently is:

```yaml
{
    "battery": 100,
    "battery_low": false,
    "carbon_monoxide": false,
    "last_seen": "2022-12-18T18:38:49+01:00",
    "linkquality": 105,
    "tamper": false,
    "voltage": 3500,
    "device": {
        "applicationVersion": 1,
        "dateCode": "20171215",
        "friendlyName": "CO-Melder R's Zimmer ",
        "hardwareVersion": 1,
        "ieeeAddr": "0x[redacted]",
        "manufacturerID": 4478,
        "manufacturerName": "feibit",
        "model": "SCA01ZB",
        "networkAddress": 3400,
        "powerSource": "Battery",
        "softwareBuildID": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
        "stackVersion": 2,
        "type": "EndDevice",
        "zclVersion": 2
    }
}
```

### What did you expect to happen?

no error

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB stick
