### ISSUE TITLE
Hue transition speeds 

### ISSUE THREAD

**Issue by brettyj** [Koenkk/zigbee2mqtt#1567]
Hey,

Just a couple of questions if that's okay? 

Just got zigbee2mqtt setup and controlling some hue bulbs to test with. Couple of things I've noticed,  changing brightness / white temperature via Home Assistant is instant with no transition time. Exposing the lights via a zigbee group through nova casa cloud to alexa, works well, but changing brightness takes a long time, feels like a good 15-20 seconds.

Anyway to make switching on/off via HA have a transition like built in hue, and anyway to make the brightness change via alexa faster to match the hue transition speed?

I've also noticed if I use define a transition speed in an automation, Home Assistant will show the incorrect status of the bulb, showing it as being dimmer than it is - almost as if it's checking the value of the bulb before the transition has finished - any way to fix this?

Thanks, love what you're doing with this project.

**Comment by Koenkk** [comment]
You should be able to to this by modifying the zigbee2mqtt `configuration.yaml` for this device like

```yaml
devices:
  '0x00158d0001d82999':
    friendly_name: 'my_light'
    homeassistant:
      # Transition in seconds
      light:
        transition: 2
```
