### ISSUE TITLE
[Feature request]: Add additional events for Phillips Hue Tap Dial (e.g. number of steps you rotate the dial by)

### ISSUE THREAD

**Issue by victorhooi** [Koenkk/zigbee2mqtt#15761]
### Is your feature request related to a problem? Please describe

I'm trying to port this blueprint from ZHA to zigbee2mqtt.

[https://community.home-assistant.io/t/philips-hue-tap-dial-switch-zha/446636/](https://community.home-assistant.io/t/philips-hue-tap-dial-switch-zha/446636/)
https://github.com/apollo1220/blueprints/blob/main/philips_zigbee_dial.yaml

The blueprint allows you to use the Phillips Hue Tap Dial with the following functionality:
* Pressing buttons 1 through to 4 lets you toggle 4 different lights/devices on/off
* Turning the tap dial lets you dim the last toggled light (and there's a configurable scaling factor).

However, it seems like certain events are not exposed in zigbee2mqtt (or possibly I'm missing something very obvious), which is hampering my ability to port it.

### Describe the solution you'd like

The ZHA blueprint seems to pull things like `scene_id`, as well as `step_mode` (which I believe is either slow or fast) and `step_size`. This is the variables stanza:

```
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args }}"
      params: "{{ trigger.event.data.params }}"
      scene: "{{ trigger.event.data.params.scene_id }}"
      step_mode: "{{ trigger.event.data.params.step_mode }}"
      step_size: "{{ trigger.event.data.params.step_size }}"
```

For zigbee2mqtt, it creates an entity for the tap dial called for example `sensor.hue_tap_dial_1_action` - and when you press buttons, it does things like `state: button_1_press` and `state: button_1_press_release`.

For turning the dial, it just does `state: dial_rotate_left_slow` or `state: dial_rotate_right_fast` when you turn it.

However, there doesn't seem to be any way to pull the number of steps you click on the dial.

### Describe alternatives you've considered

Use ZHA instead of zigbee2mqtt (but I'm already setup with zigbee2mqtt, and I like it, lol).

### Additional context

My Phillips Hue Tap DIal is on the latest firmware (2.59.25), if that helps. Updated by zigbee2mqtt, which was pretty neat.a
