### ISSUE TITLE
[Feature request]: Network Key and Pan ID / Extended Pan ID auto generated during install to minimize insecure installs

### ISSUE THREAD

**Issue by bharvey88** [Koenkk/zigbee2mqtt#16188]
### Is your feature request related to a problem? Please describe

While learning more about zigbee and z2m in the home assistant discord server I have been made aware that my install is far from secure. Per: https://www.zigbee2mqtt.io/advanced/zigbee/03_secure_network.html#change-zigbee-network-encryption-key it says the install uses a default encryption key and pan ID and extended pan ID. It also states we are unable to generate the key ourselves when using the addon inside home assistant OS. I find this default install behavior to be very worrying and I request that there be a way to automatically generate both a random network key and pan ID to make this a noob-friendly installation experience.

### Describe the solution you'd like

Automatically generate randomized network key and pan ID and extended pan ID during installation process.

### Describe alternatives you've considered

Alternatively, a required set of options for both network key and pan ID and extended pan ID in the configuration tab with accompanying documentation in the documentation tab of the addon.

### Additional context

No additional context to give, let me know if you want any added information.

Stale bot closed this issue and I was unable to reopen so I made a new one: https://github.com/Koenkk/zigbee2mqtt/issues/14868

**Comment by eikowagenknecht** [comment]
I found that while the docs say it can't be done when using the HA addon, it's not that hard (or I'm missing something).

Warning: You need to repair all devices after you do that!!

- Shutdown zigbee2mqtt addon
- Open \\<homeassistant_ip>\config\zigbee2mqtt\configuration.yaml
- set network_key and ext_pan_id like so:
  ```
  advanced:
      network_key:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 220
    ext_pan_id:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 221
  ```
  Obviously use other values for each entry (betweed 1 and 221 should be safe).
- Remove coordinator_backup.json
- Restart and repair all your devices
