### ISSUE TITLE
Override of min_mireds and max_mireds for HomeAssistant

### ISSUE THREAD

**Issue by chriss-de** [Koenkk/zigbee2mqtt#16266]
### What happened?

My Paulmann Zigbee Light dont report their max/min_mireds.

When I change the color_temp in the Zigbee2mqtt frontend with the predefined buttons warmest (or coolest) it selects values which seems to be the max/min mireds. I can change to a higher mired but the color_temp does not change so I assume zigbee2mqtt knows the max_mired. Same goes for min_mireds.

But since it is not reported to HomeAssistent my selector for color_temp is way larger in range than what is available.

I tried to override it in my devices.yml but it does not change the payload
configuration.yaml:
```yaml
---
devices:
  - devices.yml
```

devices.yml
```yaml
---
'0x00158d00057fcc99':
  friendly_name: OG - Bad - Licht
  homeassistant:
    light:
      min_mireds: 153
      max_mireds: 370
```

I'm not sure if it really an issue or just a classic case of PEBKAC.

### What did you expect to happen?

Would be nice to let HomeAssistant know about max_mireds and min_mireds

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2
