### ISSUE TITLE
Schneider Electric CCTFR6700 pi_heating_demand

### ISSUE THREAD

**Issue by krair** [Koenkk/zigbee2mqtt#16315]
### What happened?

According to the documentation [for the device](https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/CCTFR6700.md), I should be able to not only control the desired temperature, but also the level of heating by setting the pi_heating_demand endpoint. I have no issues with publishing payloads to the other 3 endpoints in the documentation, but everything published to pi_heating_demand gives the error "No converter available for 'pi_heating_demand'".

I see that we can publish to {"temperature_measured_value": VALUE}, but returns on {"local_temperature": ""}. Is the pi_heating_demand the incorrect endpoint? 

I see the "interview" produces the following from the config endpoint:
```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
current_temperature_template: '{{ value_json.local_temperature }}'
current_temperature_topic: zigbee2mqtt/0xe0798dfffe7e2923
device:
  identifiers:
    - zigbee2mqtt_0xe0798dfffe7e2923
  manufacturer: Schneider Electric
  model: Heating thermostat (CCTFR6700)
  name: '0xe0798dfffe7e2923'
max_temp: '30'
min_temp: '4'
mode_command_topic: zigbee2mqtt/0xe0798dfffe7e2923/set/system_mode
mode_state_template: '{{ value_json.system_mode }}'
mode_state_topic: zigbee2mqtt/0xe0798dfffe7e2923
modes:
  - 'off'
  - auto
  - heat
name: '0xe0798dfffe7e2923'
temp_step: 0.5
temperature_command_topic: zigbee2mqtt/0xe0798dfffe7e2923/set/occupied_heating_setpoint
temperature_state_template: '{{ value_json.occupied_heating_setpoint }}'
temperature_state_topic: zigbee2mqtt/0xe0798dfffe7e2923
temperature_unit: C
unique_id: 0xe0798dfffe7e2923_climate_zigbee2mqtt
platform: mqtt
```

If you'd like I can find the initial raw interview from the zigbee2mqtt logs.

### What did you expect to happen?

I can set a pi_heating_demand while in either "heat" or "auto" mode to create faux "eco" and "boost" modes.

### How to reproduce it (minimal and precise)

publish to `zigbee2mqtt/device_name/set` with payload of `{"pi_heating_demand": 10}` OR publish to `zigbee2mqtt/device_name/set/pi_heating_demand` with a payload of `10`.

### Zigbee2MQTT version

1.29.2 commit: bb3e8f6

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

debug 2023-01-23 11:51:26 Received MQTT message on 'zigbee2mqtt/0xe0798dfffe7e2923/set/pi_heating_demand' with data '10'
error 2023-01-23 11:51:26 No converter available for 'pi_heating_demand' (10)

AND

debug 2023-01-23 12:00:54 Received MQTT message on 'zigbee2mqtt/0xe0798dfffe7e2923/set' with data '{"pi_heating_demand": 20}'
error 2023-01-23 12:00:54 No converter available for 'pi_heating_demand' (20)
