### ISSUE TITLE
Power On Behaviour Packet Sniff - TS0505B / _TZB210_tmi0rihb "Zigbee 3.0 5 in 1 LED Strip Controller Model LM052"

### ISSUE THREAD

**Issue by jarrah31** [Koenkk/zigbee2mqtt#16325]
### What happened?

Hi Koenkk,

Would you be able to help me add power_on_behavior for the Laimi / Tuya TS0505B, _TZB210_tmi0rihb device  please? (originally added as a new device here: https://github.com/Koenkk/zigbee2mqtt/issues/12168)

I contacted the Laimi manufacturer to ask if the device supported power_on_behavior, and they replied with the following:

> You can buy a Tuya Zigbee gateway connect with our controller, use the Tuya Smart Life APP to set "Do Not disturb function“”. Our controller has memory, after you set "Do Not disturb function", the controller will save it automatically.
> Kind Regards,
> Sky Liu
> Shenzhen You Lai Mi Technology Co.,Ltd

Unfortunately I don't have a Tuya hub to sniff the packets when this option is set, but I'm ready and willing to run any test commands or external_converters on a dev zigbee2mqtt that I have this device paired to. If this isn't possible, I'm willing to buy the Tuya hub to help get this working.

Thanks in advance!

![IMG_0691](https://user-images.githubusercontent.com/3072303/214150890-bb6d1c19-d52f-49de-8000-0554f8d28025.png)

<img width="485" alt="image" src="https://user-images.githubusercontent.com/3072303/214152455-1f39616d-2b88-450a-be5f-ca5bcac01ec6.png">

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20221102

### Adapter

zzh

**Comment by jarrah31** [comment]
I now have a Tuya Zigbee Gateway and I have been able to set the "Do Not Disturb" feature for this LED controller. I will attempt the sniff the traffic over the next few days to see if this helps you figure out the required setting.

One thing worth noting is that Do Not Disturb is an on or off setting, there's no option to define the previous state. It also work different to what I expected - when the feature is enabled and you turn power back on, the LED strip briefly lights up for around 5-7 seconds and then turns off. It does this no matter what state the light was previously in.

![IMG_0700](https://user-images.githubusercontent.com/3072303/215158822-53871d0b-2d93-4bed-92a3-8d17d432289e.jpeg)

**Comment by jarrah31** [comment]
Packet has now been sniffed! Hopefully the attached packet trace will help you figure out the required setting @Koenkk 

[tuya_TZB210_tmi0rihb_PwOnSetting.pcapng.zip](https://github.com/Koenkk/zigbee2mqtt/files/10522707/tuya_TZB210_tmi0rihb_PwOnSetting.pcapng.zip)

Decryption key is: 5be76546b74e7add78c0dc72dd0a56e4

Packets 46 and 158 is the off message sent when I press save in the above screenshot.

Packet 106 and 192 is the on message.

Good luck and thanks in advance!

**Comment by Koenkk** [comment]
@jarrah31 could you find out the data point of `do_not_disturb` using https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html

**Comment by jarrah31** [comment]
Hi @Koenkk, thanks for your help!

The data point for `do_not_disturb` is 34!

<img width="264" alt="image" src="https://user-images.githubusercontent.com/3072303/215568991-4642afa9-4355-4fef-a67c-9e3a16bdab5f.png">

**Comment by jarrah31** [comment]
Thanks @Koenkk, I can confirm that `do_not_disturb` now works as intended for this device!

One more question if I may - I set the `availability` option on this device with a `timeout` of 1, expecting Z2M to detect that my light state was off after returning from power (it was on before turning power off/on), but even though the light is off, several minutes later I find Z2M still thinks the device is on.

The same is true if I set `do_not_distrub` to `false`, turn the light off from within Z2m, power off and then on the device, the light resumes on and stays on, but Z2M still shows it as off 5 mins later.

Is it perhaps because the device is running as an external converter and all will be ok once it's properly integrated?

This is my config just in case it helps:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: testzigbee
  server: mqtt://192.168.1.10
  user: mqttuser
  password: password
serial:
  port: /dev/ttyUSB0
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c1389473a50933':
    friendly_name: '0xa4c1389473a50933'
    availability:
      timeout: 1
frontend:
  port: 8080
external_converters:
  - ext_converter.js
```
