### ISSUE TITLE
[New device support]: Wireless switch with 4 buttons - _TZ3000_dziaict4 - TS0044

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#16595]
### Link

https://zigbee.blakadder.com/Tuya_4key.html

### Database entry

info  2023-02-09 15:29:20: MQTT publish: topic 'homeassistant/sensor/0xa4c13877de566574/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/4 Button Remote/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xa4c13877de566574"],"manufacturer":"TuYa","model":"Wireless switch with 4 buttons (TS0044)","name":"4 Button Remote"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"4 Button Remote action","state_topic":"zigbee2mqtt/4 Button Remote","unique_id":"0xa4c13877de566574_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'

### Comments

```
Friendly name
4 Button Remote
Description
Last seen
8 minutes ago
Availability
Online
Device type
EndDevice
Zigbee Model
TS0044
Zigbee Manufacturer
_TZ3000_dziaict4
Description
Wireless switch with 4 buttons
Support status
Supported

IEEE Address
0xa4c13877de566574
Network address
0x1393
Manufacturer
[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model
[TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html#tuya-ts0044)
Power
Battery 
Interview completed
True

```
info  2023-02-09 15:29:20: MQTT publish: topic 'homeassistant/sensor/0xa4c13877de566574/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/4 Button Remote/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xa4c13877de566574"],"manufacturer":"TuYa","model":"Wireless switch with 4 buttons (TS0044)","name":"4 Button Remote"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"4 Button Remote action","state_topic":"zigbee2mqtt/4 Button Remote","unique_id":"0xa4c13877de566574_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
```




























### External converter

```shell
No Converters
```

**Comment by cloudbr34k84** [comment]
@Koenkk can wer get this added to the converter as it seems its already supported just not this model?

![image](https://user-images.githubusercontent.com/58960644/217988395-2c74c803-331e-4b23-b584-73babe80e5e6.png)

**Comment by Koenkk** [comment]
```
Support status
Supported`
```

It is already detected as supported?

**Comment by cloudbr34k84** [comment]
> ```
> Support status
> Supported`
> ```
> 
> It is already detected as supported?

I don't get any of the actions available in HA?

**Comment by cloudbr34k84** [comment]
> ```
> Support status
> Supported`
> ```
> 
> It is already detected as supported?

![Screenshot_20230211-020200.png](https://user-images.githubusercontent.com/58960644/218138090-613edd5e-40f0-4b5c-923e-e7bd69442cd4.png)

![Screenshot_20230211-020131.png](https://user-images.githubusercontent.com/58960644/218138091-5d7fda76-a587-4929-b279-82510f29aa07.png)

Nothing is available

**Comment by Koenkk** [comment]
Can you provide the debug log when pressing buttons on the device?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by cloudbr34k84** [comment]
> Can you provide the debug log when pressing buttons on the device?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
[log (1).txt](https://github.com/Koenkk/zigbee2mqtt/files/10711998/log.1.txt)

0xa4c13877de566574
TS0044
0x13A7

**Comment by cloudbr34k84** [comment]
> > Can you provide the debug log when pressing buttons on the device?
> > See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
> > [log (1).txt](https://github.com/Koenkk/zigbee2mqtt/files/10711998/log.1.txt)
> 
> 0xa4c13877de566574 TS0044 0x13A7

@Koenkk any updates mate?

**Comment by Koenkk** [comment]
> > Can you provide the debug log when pressing buttons on the device?
> > See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
> > [log (1).txt](https://github.com/Koenkk/zigbee2mqtt/files/10711998/log.1.txt)
> 
> 0xa4c13877de566574 TS0044 0x13A7

These are not the debug logs, see https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by cloudbr34k84** [comment]
@Koenkk ahh ok, i have no idea when imn reading the instructions what or how to do that?? DO you have a better step by step guide for noobs? sorry

**Comment by Koenkk** [comment]
You can find them in the `data/log` folder.

**Comment by cloudbr34k84** [comment]
@Koenkk i dont see that. what am i missing here??
![image](https://user-images.githubusercontent.com/58960644/219360495-02c2e1a5-7378-4863-a453-ccb1cc3db911.png)

This is my config
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
  zigbee_herdsman_debug: true
mqtt:
  base_topic: zigbee2mqtt
  user: mqtt-user
  password: XXXXXXXXXXXXX
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyUSB0
availability: true
advanced:
  log_level: debug
  pan_id: GENERATE
  ext_pan_id:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  network_key: GENERATE
  channel: 25
homeassistant: true
discovery_topic: homeassistant
status_topic: hass/status
```
