### ISSUE TITLE
Update from 1.22.2 to latest Version - Error starting z2mqtt

### ISSUE THREAD

**Issue by chrismast** [Koenkk/zigbee2mqtt#16689]
### What happened?

Hi all,
I do run z2mqtt since a long time, missed though to update since early last year.
I am still on version 1.22.2.
Wanted to update today to the latest version and followed the update instructions (as I did also before always) but somehow z2mqtt does not start anymore and I am not really getting any error message telling me why (or I cannot find the correct log).
I also looked through all releases and did not see any breaking changes.

**Below is my config:**

Running z2mqtt inside an LXC on Proxmox
npm --version: 6.14.15
node --version: v12.22.7

configuration.yaml:

```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt.USER.com:1883'
  user: USER
  password: 'PW'
  #key: /home/christian/ssl/mqtt.key
  #cert: /home/christian/ssl/mqtt.crt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  last_seen: ISO_8601_local
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  ikea_ota_use_test_url: true
  rtscts: false
experimental:
  output: attribute
frontend:
  port: 8080
  host: 0.0.0.0
devices: devices.yaml

```

Any hint on what could go wrong or where I could dig further on the error I am getting?
Luckily I can easily rollback with Proxmox so that I do not break the PROD environment.

Thanks

### What did you expect to happen?

Update as usual

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210708

### Adapter

zzh!
