### ISSUE TITLE
Dual device description in response

### ISSUE THREAD

**Issue by directman66** [Koenkk/zigbee2mqtt#1685]
I request a device map in the PAB format, some devices are contained in the response twice

Answer:

```
[{"ieeeAddr":"0x000d6ffffe20387e","nwkAddr":54281,"lqi":98,"parent":"0x00124b001938dc6d","status":"online"},{"ieeeAddr":"0x00158d0001a24770","nwkAddr":34881,"lqi":63,"parent":"0x00124b001938dc6d","status":"online"},{"ieeeAddr":"0x00158d00017394dd","nwkAddr":24509,"lqi":77,"parent":"0x00124b001938dc6d","status":"offline"},{"ieeeAddr":"0x00158d0002c65d56","nwkAddr":13384,"lqi":49,"parent":"0x00124b001938dc6d","status":"online"},{"ieeeAddr":"0x000b57fffed4f6d4","nwkAddr":17528,"lqi":28,"parent":"0x00124b001938dc6d","status":"offline"},{"ieeeAddr":"0x01124b001baea534","nwkAddr":9078,"lqi":12,"parent":"0x00124b001938dc6d","status":"offline"},{"ieeeAddr":"0x00124b001938dc6d","nwkAddr":0,"lqi":156,"parent":"0x000d6ffffe20387e","status":"online"},{"ieeeAddr":"0x01124b001baea534","nwkAddr":9078,"lqi":77,"parent":"0x000d6ffffe20387e","status":"offline"},{"ieeeAddr":"0x00158d0002c65d56","nwkAddr":13384,"lqi":255,"parent":"0x000d6ffffe20387e","status":"online"},{"ieeeAddr":"0x000b57fffed4f6d4","nwkAddr":17528,"lqi":255,"parent":"0x000d6ffffe20387e","status":"offline"},{"ieeeAddr":"0x00158d00017394dd","nwkAddr":24509,"lqi":255,"parent":"0x000d6ffffe20387e","status":"offline"},{"ieeeAddr":"0x00158d0001a24770","nwkAddr":34881,"lqi":255,"parent":"0x000d6ffffe20387e","status":"online"},{"ieeeAddr":"0x00158d00029b4352","nwkAddr":921,"lqi":255,"parent":"0x000d6ffffe20387e","status":"online"},{"ieeeAddr":"0x00158d0001a24770","nwkAddr":34881,"lqi":1,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d0001a2e891","nwkAddr":13072,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d00022bc3ab","nwkAddr":4114,"lqi":96,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d0002b76411","nwkAddr":59051,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d0001150114","nwkAddr":52621,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x000b57fffeb86106","nwkAddr":30223,"lqi":170,"parent":"0x01124b001baea534","status":"offline"},{"ieeeAddr":"0x00158d0001269d5f","nwkAddr":39672,"lqi":170,"parent":"0x01124b001baea534","status":"offline"},{"ieeeAddr":"0x00158d0002afd713","nwkAddr":14093,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d00026ea90d","nwkAddr":47867,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d0001bb383a","nwkAddr":47572,"lqi":170,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x000b57fffed4f6d4","nwkAddr":17528,"lqi":1,"parent":"0x01124b001baea534","status":"offline"},{"ieeeAddr":"0x00158d0002c65d56","nwkAddr":13384,"lqi":17,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x00158d00017394dd","nwkAddr":24509,"lqi":1,"parent":"0x01124b001baea534","status":"offline"},{"ieeeAddr":"0x00124b001938dc6d","nwkAddr":0,"lqi":1,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x000d6ffffe20387e","nwkAddr":54281,"lqi":8,"parent":"0x01124b001baea534","status":"online"},{"ieeeAddr":"0x01124b001baea534","nwkAddr":9078,"lqi":39,"parent":"0x00158d0001a24770","status":"offline"},{"ieeeAddr":"0x00158d0001269d5f","nwkAddr":39672,"lqi":100,"parent":"0x00158d0001a24770","status":"offline"},{"ieeeAddr":"0x00158d0001a044d8","nwkAddr":62930,"lqi":169,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x00158d0002afd713","nwkAddr":14093,"lqi":112,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x00158d0001150114","nwkAddr":52621,"lqi":150,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x00124b001938dc6d","nwkAddr":0,"lqi":69,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x000b57fffed4f6d4","nwkAddr":17528,"lqi":159,"parent":"0x00158d0001a24770","status":"offline"},{"ieeeAddr":"0x000d6ffffe20387e","nwkAddr":54281,"lqi":191,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x00158d0002c65d56","nwkAddr":13384,"lqi":199,"parent":"0x00158d0001a24770","status":"online"},{"ieeeAddr":"0x00158d00017394dd","nwkAddr":24509,"lqi":157,"parent":"0x00158d0001a24770","status":"offline"},{"ieeeAddr":"0x00124b001938dc6d","nwkAddr":0,"lqi":60,"parent":"0x000b57fffed4f6d4","status":"online"},{"ieeeAddr":"0x01124b001baea534","nwkAddr":9078,"lqi":42,"parent":"0x000b57fffed4f6d4","status":"offline"},{"ieeeAddr":"0x00158d0002c65d56","nwkAddr":13384,"lqi":255,"parent":"0x000b57fffed4f6d4","status":"online"},{"ieeeAddr":"0x00158d00017394dd","nwkAddr":24509,"lqi":248,"parent":"0x000b57fffed4f6d4","status":"offline"},{"ieeeAddr":"0x00158d0001a24770","nwkAddr":34881,"lqi":236,"parent":"0x000b57fffed4f6d4","status":"online"},{"ieeeAddr":"0x000d6ffffe20387e","nwkAddr":54281,"lqi":255,"parent":"0x000b57fffed4f6d4","status":"online"}]
```

at least the device with the address 0x01124b001baea534 is presented more than once

configuration.yaml
```
homeassistant: true
permit_join: true
advanced:
  channel: 26
  soft_reset_timeout: 3000
  log_level: debug
  report: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.39:1883'
serial:
  port: /dev/ttyACM1
experimental:
  livolo: true
devices:
  '0x01124b001baea534':
    friendly_name: '0x01124b001baea534'
    retain: false
  '0x00158d0001a24770':
    friendly_name: '0x00158d0001a24770'
    retain: false
  '0x00158d0002c65d56':
    friendly_name: '0x00158d0002c65d56'
    retain: false
  '0x00158d0001a2e891':
    friendly_name: '0x00158d0001a2e891'
    retain: false
  '0x00158d0001150114':
    friendly_name: '0x00158d0001150114'
    retain: false
  '0x00158d0002afd713':
    friendly_name: '0x00158d0002afd713'
    retain: false
  '0x00158d0002b76411':
    friendly_name: '0x00158d0002b76411'
    retain: false
  '0x00158d00026ea90d':
    friendly_name: '0x00158d00026ea90d'
    retain: false
  '0x00158d0001560da8':
    friendly_name: '0x00158d0001560da8'
    retain: false
  '0x000b57fffed4f6d4':
    friendly_name: '0x000b57fffed4f6d4'
    retain: false
  '0x000b57fffeb86106':
    friendly_name: '0x000b57fffeb86106'
    retain: false
  '0x000d6ffffe20387e':
    friendly_name: '0x000d6ffffe20387e'
    retain: false
  '0x00158d00017394dd':
    friendly_name: '0x00158d00017394dd'
    retain: false
  '0x00158d0001a044d8':
    friendly_name: '0x00158d0001a044d8'
    retain: false
  '0x00158d0001a9e374':
    friendly_name: '0x00158d0001a9e374'
    retain: false
  '0x00158d0001bb383a':
    friendly_name: '0x00158d0001bb383a'
    retain: false
  '0x00124b000bf07241':
    friendly_name: '0x00124b000bf07241'
    retain: false
  '0x0017880104f2abb5':
    friendly_name: '0x0017880104f2abb5'
    retain: false
  '0x00158d00022bc3ab':
    friendly_name: '0x00158d00022bc3ab'
    retain: false
  '0x00158d00029b4352':
    friendly_name: '0x00158d00029b4352'
    retain: false
groups:
  '1':
    friendly_name: group1
    devices:
      - '0x000d6ffffe20387e'
  '2':
    friendly_name: group1
    devices: []
  '3':
    friendly_name: group1
    devices: []
  '4':
    friendly_name: group1
    devices: []
  '5':
    friendly_name: group1
    devices: []
  '6':
    friendly_name: group1
    devices: []
  '7':
    friendly_name: group1
    devices: []
  '8':
    friendly_name: group1
    devices: []
  '9':
    friendly_name: group1
    devices: []
  '10':
    friendly_name: gledopto
    devices:
      - '0x00124b001ba6e3c0'
  '11':
    friendly_name: xiaomi
    devices:
      - '0x00158d0001a24770'
  '12':
    friendly_name: ikea
    devices:
      - '0x000d6ffffe20387e'
  '13':
    friendly_name: group1
    devices: []

```
