### ISSUE TITLE
Xiaomi Aqara WXKG02LM

### ISSUE THREAD

**Issue by sander2506** [Koenkk/zigbee2mqtt#1695]
I've pairde the switch and this shows up when i press the left button:

>   zigbee2mqtt:info 7/6/2019, 1:41:50 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0001e06761', payload '{"linkquality":47,"battery":100,"voltage":3055,"click":"left"}'
>   zigbee2mqtt:info 7/6/2019, 1:41:50 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0001e06761', payload '{"linkquality":47,"battery":100,"voltage":3055,"click":""}'

i've tried both automations but the light won't light up:

```
- alias: Respond to button clicks
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/sensor.0x00158d0001e06761_click'
  condition:
    condition: template
    value_template: '{{ "left" == trigger.payload_json.click }}'
  action:
    entity_id: light.sonoff2
    service: light.toggle   
```

```
automation:
  - alias: Respond to button clicks
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d0001e06761'
    condition:
      condition: template
      value_template: '{{ "left" == trigger.payload_json.click }}'
  action:
    entity_id: light.sonoff2
    service: light.toggle   
```
