### ISSUE TITLE
TS0601_dimmer (Moes) not responding to on/off after a while

### ISSUE THREAD

**Issue by giejay** [Koenkk/zigbee2mqtt#17092]
### What happened?

I bought one of these dimmers: https://nl.aliexpress.com/item/1005001567846491.html and it was working perfectly for a while. I'm not exactly sure when, but somewhere along the road it starting becoming unresponsive after a while (a day or so) to on/off (including brightness) commands.

When I hit the reconfigure button in the frontend or when I repair, it works again for about 1 day. The strange thing is, that the state gets reported instantly, when I manually turn on/off the dimmer so I don't think its a range issue. Also, the LQI is good, about 140. 

I suspected a faulty unit so I ordered another one last week. Exactly the same thing is happening. I tried 3 different routers (SonOff, ZZH and Slaesh) and all are experiencing the same issue.

The only thing I can think of is simply making an automation in HA which will reconfigure the device every hour, but I would rather get to the rootcause. This is the only device (of 52 zigbee devices) acting like this.

Zigbee Model
TS0601
Zigbee Manufacturer
_TZE200_w4cryh2i
https://www.zigbee2mqtt.io/devices/TS0601_dimmer.html#tuya-ts0601_dimmer

### What did you expect to happen?

I expect the dimmer to be controllable from z2mqtt, also after 1 day. 

### How to reproduce it (minimal and precise)

1. Pair/reconfigure
2. Wait about 1 day, sometimes sooner
3. Device wont respond anymore to on/off or brightness commands

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20221226

### Adapter

SonOff/Slaesh

### Debug log

```
Debug 2023-03-20 19:23:07Received MQTT message on 'zigbee2mqtt-meter-pi/kitchen/set' with data '{"state":"ON"}'
Debug 2023-03-20 19:23:07Publishing 'set' 'state' to 'kitchen'
```

Nothing else happens after this.

**Comment by giejay** [comment]
Update, I removed 2 of my Tuya zigbee sockets all together from my z2m installation because i was seeing some lqi errors when I did a network scan. 

That seems to fix it, almost 1 week of being able to control the dimmer. 

Yesterday, I added another dimmer to my installation, the TS110E, and immediately, the same problem started occuring again, the new device worked fine, but the dimmer of the OP is again failing to turn on/off.

I now removed the new dimmer again and will be monitoring the behaviour.

**Comment by giejay** [comment]
A valid flow:

```
Debug 2023-03-27 13:57:49Received Zigbee message from 'kitchen', type 'attributeReport', cluster 'genBasic', data '{"65506":31,"65508":0,"appVersion":68}' from endpoint 1 with groupID 0
Debug 2023-03-27 13:57:50Received MQTT message on 'zigbee2mqtt-meter-pi/kitchen/set' with data '{"state":"ON"}'
Debug 2023-03-27 13:57:50Publishing 'set' 'state' to 'kitchen'
Debug 2023-03-27 13:57:50Received Zigbee message from 'kitchen', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":1}],"seq":256}' from endpoint 1 with groupID 0
Info 2023-03-27 13:57:50MQTT publish: topic 'zigbee2mqtt-meter-pi/kitchen', payload '{"brightness":74,"linkquality":127,"min_brightness":4,"state":"ON"}'
```

Unhappy:

```
Debug 2023-03-20 19:23:07Received MQTT message on 'zigbee2mqtt-meter-pi/kitchen/set' with data '{"state":"ON"}'
Debug 2023-03-20 19:23:07Publishing 'set' 'state' to 'kitchen'
```

It seems like "something" is not receiving a "commandDataResponse".

After a restart of Z2M, everything works again for a while.

**Comment by giejay** [comment]
Currently, I have a workaround in place to automatically call reconfigure whenever it happens:

```
mqtt:
  button:
    - name: Kitchen Light Reconfigure
      command_topic: "zigbee2mqtt-meter-pi/bridge/request/device/configure"
      payload_press: '{"id":"kitchen","transaction":"psoe5-1"}'
      json_attributes_topic: zigbee2mqtt-meter-pi/bridge/response/device/configure
```

```
                  - alias: "Reconfigure the kitchen light"
                    service: button.press
                    target:
                      entity_id: button.kitchen_light_reconfigure
```
