### ISSUE TITLE
[Feature request]: Add option to not send duplicate mqtt messages

### ISSUE THREAD

**Issue by vandalon** [Koenkk/zigbee2mqtt#17134]
### Is your feature request related to a problem? Please describe

The "problem" this would solve is to prevent flooding of mqtt messages. 

### Describe the solution you'd like

When a mqtt message for a device is the same is the previously sent message, don't sent it out. 

### Describe alternatives you've considered

I've considered using debouncing but this brings the disadvantage that messages are delayed.

### Additional context

When using the "Filtered publish attributes" option on my tuya mmWave sensors z2m still sends out a message when one of the filtered attributes is changed. The above solution would prevent sending out "unnecessary" mqtt messages

**Comment by danieledwardgeorgehitchcock** [comment]
As far as I am aware, the debounce logic should not add any additional time to the processing of the message.

Z2M uses the `hasAlreadyProcessedMessage` function to debounce - this effectively lets through the first message as it comes into the stack, but no subsequent messages within the given debounce period.

**Comment by junosuarez** [comment]
Can you provide an example from the logs of repeated published messages?

**Comment by vandalon** [comment]
Sure:

The first column is the unix timestamp with nanoseconds

```
1680076451.739552450 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076451.792046669 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076451.851917373 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076451.903376464 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076451.955591047 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076452.009332653 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076452.062816790 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076452.113896740 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
1680076452.166795268 zigbee2mqtt/Eetkamer mmWave {"illuminance_lux":290,"presence":false}
```

with the following config:
```
  '0xe0798dfffeb1fab4':
    friendly_name: Eetkamer mmWave
    filtered_attributes:
      - target_distance
      - last_seen
      - linkquality
      - elapsed
      - self_test
      - radar_sensitivity
      - maximum_range
      - minimum_range
      - fading_time
      - detection_delay
      - cli
    legacy: false
    optimistic: true
```
