### ISSUE TITLE
Availability not working - failed to ping all devices in network

### ISSUE THREAD

**Issue by jonatrey** [Koenkk/zigbee2mqtt#17152]
### What happened?

The device availability feature is not working as intended for devices that are powered off. There is no ping happening to the devices. 

- Last seen metadata is correct,
- After rebooting zigbee2mqtt, the correct availability is published,
- When powering on a device, the new correct availability is published (from unavailable to online)
- After powering off the device, the availability is not published - the device is not pinged
- This is happening with all devices

Hardware
- My network has about 60 devices, some permanently powered, some on battery and some on traditional switches. I disabled the availability feature for the permanently powered devices.
- Adapter Conbee II with the recommended firmware version (0x26580700)

Log entries:
- Log level is in Debug, no single entries (no ping happening of failing) from https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/availability.ts file
- Can see periodic OTA requests in the debug logs

```
Config:
advanced:
  log_level: debug
  ..
  adapter_delay: 100
  cache_state: true
  last_seen: ISO_8601
  adapter_concurrent: 2
  legacy_availability_payload: false
availability:
  active:
    timeout: 5
  passive:
    timeout: 1500
```

### What did you expect to happen?

I expect to have my powered on devices pinged at 5 min intervals.

### How to reproduce it (minimal and precise)

Power cycle a bulb, 

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2

### Debug log

[zigbee_debug_log.log](https://github.com/Koenkk/zigbee2mqtt/files/11072749/zigbee_debug_log.log)
[Startup log](https://pastebin.com/hGRycFcW) (zigbee2mqtt_0x001788010491ffbd is unplugged)
