### ISSUE TITLE
Not connected to MQTT server

### ISSUE THREAD

**Issue by pzystorm** [Koenkk/zigbee2mqtt#1730]
**Sorry guys, of course I have seen the other topics here regarding the same issue "Not connected to MQTT server"... but this seems different.**

## What happened
The connection to the mqtt cannot be established

## What did you expect to happen
The connection to the mqtt can be established

## How to reproduce it (minimal and precise)
apt-get install mosquitto
Mosquitto default config has not been changed.

Ensure the service is running:
```
# netstat -pltn | grep mosq
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      18272/mosquitto
```

Test message arrives:
`mosquitto_pub -h localhost -t test -m "hello world"`

```
$ mosquitto_sub -h localhost -t test
hello world
```

zigbee2mqtt config:
```
# cat data/configuration.yaml
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d*****':
    friendly_name: '0x00158d*****'
    retain: false
advanced:
  log_level: debug
```

Output of zigbee2mqtt:
```
  zigbee2mqtt:info 2019-7-13 22:23:06 Currently 1 devices are joined:
  zigbee2mqtt:info 2019-7-13 22:23:06 0x00158d***** (0x00158d*****): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
  zigbee2mqtt:info 2019-7-13 22:23:06 Zigbee: disabling joining new devices.
  zigbee2mqtt:info 2019-7-13 22:23:06 Connecting to MQTT server at mqtt://localhost:1883
  zigbee2mqtt:info 2019-7-13 22:23:06 zigbee-shepherd ready
  zigbee2mqtt:error 2019-7-13 22:23:16 Not connected to MQTT server!
  zigbee2mqtt:error 2019-7-13 22:23:26 Not connected to MQTT server!
  zigbee2mqtt:error 2019-7-13 22:23:36 Not connected to MQTT server!
  zigbee2mqtt:error 2019-7-13 22:23:38 Not connected to MQTT server!
  zigbee2mqtt:error 2019-7-13 22:23:38 Cannot send message: topic: 'zigbee2mqtt/0x00158d*****', payload: '{"temperature":26.29,"linkquality":39,"humidity":65.46,"pressure":954}
  zigbee2mqtt:error 2019-7-13 22:23:38 Not connected to MQTT server!
```

## Debug Info
zigbee2mqtt version: latest (git clone on 13th July, 10pm)
CC253X firmware version: latest (June 2019)
mosquitto: https://www.ubuntuupdates.org/package/core/trusty/universe/updates/mosquitto
npm version: 6.10.1
node version: v10.14.0
OS: Ubuntu 14.04.5 LTS (Trusty)
