### ISSUE TITLE
Device option retain via configuration environment variable

### ISSUE THREAD

**Issue by OlafKocanda** [Koenkk/zigbee2mqtt#17373]
### What happened?

According to the [configuration documentation](https://www.zigbee2mqtt.io/guide/configuration/) it should be possible to set an environment variable. This worked for variables like "ZIGBEE2MQTT_CONFIG_MQTT_SERVER" or "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN". However, it does not seem to work for the retain option:

```
            - name: ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN
              value: "true"
```

When adding this, it simply does not show in the configuration.yaml

As a sitenote: I am able to edit / copy the configuration.yaml in / to the pod while running, but this is not a good solution for me.

### What did you expect to happen?

```
            - name: ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN
              value: "true"
```

should add the following to the configuration.yaml:

```
device_options:
  retain: true
```

### How to reproduce it (minimal and precise)

This is my zigbee2mqtt deployment.yaml on kubernetes:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.30.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: "mqtt://mosquitto"
            - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN
              value: "true"
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /data
            - name: zigbee2mqtt-config
              mountPath: /app/configuration.yaml
              subPath: configuration.yaml
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: ttyacm
              mountPath: /dev/ttyACM0
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: "hostname"
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
```

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2
