### ISSUE TITLE
Zigbee2Mqtt fails with Exit Code 1 Connection not initialized after running for hours

### ISSUE THREAD

**Issue by artem-zinnatullin** [Koenkk/zigbee2mqtt#17466]
### What happened?

I'm noticing Zigbee2Mqtt `1.30.3` fails after hours of trouble-free run-time with `exit code 1` and this error in log:

```js
Zigbee2MQTT:info  2023-04-26 09:13:15: MQTT publish: topic 'zigbee2mqtt/Washing Machine', payload '{"ac_frequency":60,"current":0.04,"energy":1.78,"linkquality":148,"power":0.3,"power_factor":null,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":123.6}'
Zigbee2MQTT:info  2023-04-26 09:13:15: MQTT publish: topic 'zigbee2mqtt/Washing Machine', payload '{"ac_frequency":60,"current":0.04,"energy":1.78,"linkquality":152,"power":0.3,"power_factor":null,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":123.6}'
Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:540:19)
    at Driver.addTransientLinkKey (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:679:26)
    at Driver.preJoining (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:611:35)
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:237:29)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:42)
    at /app/node_modules/zigbee-herdsman/src/utils/queue.ts:21:18
    at new Promise (<anonymous>)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:19:16)
    at EZSPAdapter.permitJoin (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:234:34)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:251:36)
```

On previous release `1.30.2` I was seeing crashes with exit code 255 and no useful log, but now it has stacktrace.

I'm running Zigbee2Mqtt in container with following key details:

```yaml
          resources:
            requests:
              cpu: "0.25"
              memory: "768Mi"
            limits:
              cpu: "4"
              memory: "768Mi"
              # Exposed through https://github.com/squat/generic-device-plugin
              squat.ai/zigbee: 1

            - --device
            - '{"name": "zigbee", "groups": [{"paths": [{"path": "/dev/ttyACM0"}]}]}'
```

### What did you expect to happen?

No crashes

### How to reproduce it (minimal and precise)

Just have it running in my case and it will fail eventually.

Happy to provide more info if I can!

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Stick (ZBDongle-E)
