### ISSUE TITLE
Xiaomi/Aqara QBKG26LM doesn't report action state in `operation_mode: decoupled`

### ISSUE THREAD

**Issue by oliverholliday** [Koenkk/zigbee2mqtt#17477]
### What happened?

I have the following [wall switch](https://www.zigbee2mqtt.io/devices/QBKG26LM.html) and I've configured the right hand button to use `operation_mode: decoupled`. When in this mode no zigbee messages are received in HA for that button. 

When in `operation_mode: control_relay` state changes are visible. I believe this is also the case for other models of the same switch (neutral or no neutral, and the 1/2/3 gang variants).

I have configured `state_action: true` in the hassio UI for "Settings (specific)".

After pressing buttons a few times the 'State' tab for the device shows:
```
{
    "flip_indicator_light": "ON",
    "linkquality": 81,
    "operation_mode_center": "control_relay",
    "operation_mode_left": "control_relay",
    "operation_mode_right": "decoupled",
    "state_center": "ON",
    "state_left": "ON",
    "state_right": "OFF",
    "update": {
        "installed_version": 33,
        "latest_version": 33,
        "state": "idle"
    },
    "update_available": false
}
```

There are other issues referencing this problem but no working solutions:
#12365
#17306

### What did you expect to happen?

When in decoupled mode the switch should report an action state change, for the right hand switch the payload should include `action: single_right`.

### How to reproduce it (minimal and precise)

Connect the switch, set `operation_mode: decoupled` for one of the buttons. Press the button.

### Zigbee2MQTT version

1.30.3 commit: unknown

### Adapter firmware version

20190608

### Adapter

zStack12

**Comment by oliverholliday** [comment]
Another thread of the same problem reported:

https://community.home-assistant.io/t/aqara-wall-switch-not-working-in-decoupled-mode/537582/6

**Comment by oliverholliday** [comment]
To make sure I wasn't reading the logs wrong I created an automation. The automation triggers if I press any of the buttons except the one that I've configured to be decoupled. The decoupled button does nothing.

```
alias: decoupled test
description: ""
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/0x54ef4410005e9c74/action
condition: []
action:
  - type: toggle
    device_id: 998c02f71788427093c43b5fb1dc741e
    entity_id: light.dining_standing
    domain: light
mode: single

```
