### ISSUE TITLE
No Connection to Conbee with Docker

### ISSUE THREAD

**Issue by boscho87** [Koenkk/zigbee2mqtt#17535]
### What happened?

I Updated my Raspberry PI and restartet the docker instance

### What did you expect to happen?

Should Connect Like before the Update

### How to reproduce it (minimal and precise)

Its Possible that i have the Same Problem with my zigbee2mqtt docker configuraiton?

```shell
zigbee2mqtt  | Zigbee2MQTT:error 2023-05-02 08:34:59: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee2mqtt  |     at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
zigbee2mqtt  |     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
zigbee2mqtt  |     at Zigbee.start (/app/lib/zigbee.ts:58:27)
zigbee2mqtt  |     at Controller.start (/app/lib/controller.ts:101:27)
zigbee2mqtt  |     at start (/app/index.js:107:5)
```

```yaml
 zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt:1.28.4
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Zurich
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
```

```shell
[ 1078.028698] usb 1-1.3: USB disconnect, device number 18
[ 1078.254314] usb 1-1.3: new full-speed USB device number 19 using xhci_hcd
[ 1078.363336] usb 1-1.3: New USB device found, idVendor=1cf1, idProduct=0030, bcdDevice= 1.00
[ 1078.363350] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1078.363356] usb 1-1.3: Product: ConBee II
[ 1078.363361] usb 1-1.3: Manufacturer: dresden elektronik ingenieurtechnik GmbH
[ 1078.363366] usb 1-1.3: SerialNumber: DE2662453
[ 1078.368759] cdc_acm 1-1.3:1.0: ttyACM0: USB ACM device
```

my devices info:
```shell
docker@dockerpi:~ $ ls -lah /dev/ttyACM0 
crw-rw---- 1 root dialout 166, 0 May  2 10:18 /dev/ttyACM0

docker@dockerpi:~ $ ls -la /dev/serial/by-path/
total 0
drwxr-xr-x 2 root root 60 May  2 10:18 .
drwxr-xr-x 3 root root 60 May  2 10:18 ..
lrwxrwxrwx 1 root root 13 May  2 10:18 platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0 -> ../../ttyACM0
```

anyone knows why i dont have an `/dev/serial/by-id` path?

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

-

### Adapter

-
