### ISSUE TITLE
[New device support]: LTECH TY-20-250-1000-W2Z2

### ISSUE THREAD

**Issue by lychee512** [Koenkk/zigbee2mqtt#17953]
### Link

http://www.ltechonline.com/html/en/products/Intelligence/zigbee/SE-20-250-1000-W2Z2.html

### Database entry

{"id":11,"type":"Router","ieeeAddr":"0x9035eafffed56882","nwkAddr":35277,"manufId":4098,"manufName":"_TZE200_2gtsuokt","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_2gtsuokt","powerSource":1,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":"","appVersion":72}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1676534437},"lastSeen":1686202816998,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to write my own converter for these TuYa-based LED drivers. Everything works fine from the zigbee2mqtt front end:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/11145407/22d4ccee-a33c-4143-ab34-9a935941aea3)

However I am having trouble getting the Home Assistant auto discovery to work completely. It seems that only the on-off status of the switch gets exposed: 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/11145407/671ef3c1-f68b-48be-972a-ccd71ce9a866)
Turning this light on and off from Home Assistant does work, but I can't figure out how to get the brightness and color temperature to show up.

From the debug window of the Home Assistant Device, I got the following payload for the mqtt discovery data, but I don't know if something is missing or misconfigured from this. 
```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
brightness: true
brightness_scale: 254
color_mode: true
command_topic: zigbee2mqtt/living_window_left/set
device:
  identifiers:
    - zigbee2mqtt_0x9035eafffed55e95
  manufacturer: LTECH
  model: Tuya LED for Vortex by Verde Lights (TY-20-250-1000-W2Z2)
  name: living_window_left
max_mireds: 454
min_mireds: 250
name: living_window_left
schema: json
state_topic: zigbee2mqtt/living_window_left
supported_color_modes:
  - color_temp
unique_id: 0x9035eafffed55e95_light_zigbee2mqtt
platform: mqtt
```
Any assistance would be appreciated!
zigbee2mqtt version: [1.30.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.30.2) commit: [cdf62ea](https://github.com/Koenkk/zigbee2mqtt/commit/cdf62ea)
homeassistant version: Home Assistant 2023.3.3, Frontend 20230309.0 - latest

Jingyee

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
  fingerprint: [
      {modelID: 'TS0601', manufacturerName: '_TZE200_2gtsuokt'},
  ],
  model: 'TY-20-250-1000-W2Z2',
  vendor: 'LTECH',
  description: 'Tuya LED for Vortex by Verde Lights',
  fromZigbee: [fz.tuya_light_wz5],
  toZigbee: [tz.tuya_dimmer_state, tz.tuya_light_wz5],
  exposes: [
      exposes.light().withBrightness().setAccess('state', ea.STATE_SET).setAccess('brightness',
          ea.STATE_SET).withColorTemp([250, 454]).setAccess('color_temp',
          ea.STATE_SET),
      //exposes.numeric('white_brightness', ea.STATE_SET).withValueMin(0).withValueMax(254).withDescription(
      //    'White brightness of this light'),
  ],
  //meta: {separateWhite: true},
};

module.exports = definition;
```

### Supported color modes

color temperature
