### ISSUE TITLE
Unable to run container as non-root

### ISSUE THREAD

**Issue by MrManor** [Koenkk/zigbee2mqtt#17999]
### What happened?

Hi, I am new to containers so I might have overlooked something.

I would like to use the NFS on my NAS for my containers, but retain the root_squash setting for security. Unfortunately I can not get  zigbee2mqtt to run as non-root.  If I insert the following lines into docker-compose, the container fails to connect to my SONOFF dongle. 
```    user: 1004:1004
    group_add:
      - dialout
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811153002-if00:/dev/ttyACM0
```

### What did you expect to happen?

I was hoping to start zigbee2mqtt as non-root

I previously used the same spec in a homeassistant container and homeassistant had no problem in connecting to the Sonos dongle.

Also, if I disable the root_squash flag from my NFS server and remove the user line from the compose file, then Zigbee2MQTT starts without problems.

### How to reproduce it (minimal and precise)

setup a NFS share with a directory owned uid 1004 and ensure that the USB dongle is accessible by the dialup group
(or adjust the compose file accordingly)

Modify the original docker-compose file like this:
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: no
    user: 1004:1004
    group_add:
     - dialout
    volumes:
      - Zigbee2MQTT-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Copenhagen
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811153002-if00:/dev/ttyACM0
      # - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - smarthome
      
volumes:
  Zigbee2MQTT-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=nfs.atmy-server.dk,rw
      device: ":/dockdat/zb2mqtt"

networks:
  smarthome:
    external: true
```

### Zigbee2MQTT version

1.30.4 commit: b2dd21e

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

### Debug log

```info  2023-06-11 20:02:18: Logging to console and directory: '/app/data/log/2023-06-11.20-02-17' filename: log.txt
info  2023-06-11 20:02:18: Starting Zigbee2MQTT version 1.30.4 (commit #b2dd21e)
info  2023-06-11 20:02:18: Starting zigbee-herdsman (0.14.111)
error 2023-06-11 20:02:38: Error while starting zigbee-herdsman
error 2023-06-11 20:02:38: Failed to start zigbee
error 2023-06-11 20:02:38: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-06-11 20:02:38: Exiting...
error 2023-06-11 20:02:38: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:141:25)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:165:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
