### ISSUE TITLE
HEIMAN HS2SS-E_V03 button : No action

### ISSUE THREAD

**Issue by Hankey71** [Koenkk/zigbee2mqtt#18071]
### What happened?

Hi !
I have a [Heiman HS2SS-E_V03](https://www.zigbee2mqtt.io/devices/HS2SS-E_V03.html) doorbell
After connecting it to Z2M, I don't see any payload in "action" when I press the switch.
Only a general message from the device.
Here is my log:
`debug 2023-06-20 11:07:05Received Zigbee message from 'Sonnette Entrée', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32772}' from endpoint 1 with groupID null`
`info 2023-06-20 11:07:05MQTT publish: topic 'zigbee2mqtt/Sonnette Entrée', payload '{"battery":null,"battery_low":false,"last_seen":"2023-06-20T09:07:05.027Z","linkquality":255,"tamper":true}'`

So I can't launch automations from Home Assistant with "action".
For now I have a very simple trigger to try, but it might go off anytime (battery level change)

```
- id: '1687250930064'
  alias: Sonnette Entrée
  description: Gestion de la sonnette à l'Entrée.
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Sonnette Entrée
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.lumiere_entree
  mode: single
```

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2
