### ISSUE TITLE
Osram lamp stopped working

### ISSUE THREAD

**Issue by Th3M1k3y** [Koenkk/zigbee2mqtt#18176]
### What happened?

After updating to 1.32.0-2 one of my lamps stopped working, now I get this error when I try to change anything on it

`Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}`

and the lamp does not change anything.

The lamp is this one https://www.zigbee2mqtt.io/devices/4058075816794.html#osram-4058075816794

### How to reproduce it (minimal and precise)

Any change to the exposed options makes it return the error

### Zigbee2MQTT version

1.32.0-2

### Adapter firmware version

20211217

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

Zigbee2MQTT:error 2023-07-02 06:35:00: Publish 'set' 'state' to 'workroom_ceiling_lamp' failed: 'Error: 'transition' is not a number, got string (2)'
Zigbee2MQTT:error 2023-07-02 06:35:23: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:35:26: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:35:27: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:35:30: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:35:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:35:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:23: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:26: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:27: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:30: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:36:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:23: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:26: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:27: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:30: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:37:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:38:23: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:38:26: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:38:27: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:38:30: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}
Zigbee2MQTT:error 2023-07-02 06:38:31: Exception while calling fromZigbee converter: Cannot read properties of null (reading 'from')}

**Comment by Koenkk** [comment]
Please provide the debug log

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by Th3M1k3y** [comment]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11928898/log.txt)

**Comment by Koenkk** [comment]
The `transition` in your `configuration.yaml` seems to be a string and should be a number (change `'2'` to `2`)

**Comment by Th3M1k3y** [comment]
Which configuration.yaml should that be in?

**Comment by Koenkk** [comment]
Your zigbee2mqtt `configuration.yaml`

**Comment by Th3M1k3y** [comment]
I don't follow... There is no transition in there, should it be added in?

```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  legacy_entity_attributes: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: x
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: 6704
  channel: 15
  network_key:
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true
```
