### ISSUE TITLE
[Feature request]: New property NodOn SIN-4-RS-20, SIN-4-RS-20_LEX and SIN-4-RS-20_PRO

### ISSUE THREAD

**Issue by rty3108** [Koenkk/zigbee2mqtt#18414]
### Is your feature request related to a problem? Please describe

Please, can you add the Calibration property for the NodOn devices SIN-4-RS-20, SIN-4-RS-20_LEX and SIN-4-RS-20_PRO?
These devices support the option to calibrate through zigbee commands.

The attribute to be used for module calibration is 'Mode' is code 0x0017 from 'Window Covering Settings Attribute Set' (7.4.2.1.3).
The bit for its activation is the 'bit1' table (7.4.2.1.3.8)

### Describe the solution you'd like

New property for devices SIN-4-RS-20, SIN-4-RS-20_LEX and SIN-4-RS-20_PRO

### Describe alternatives you've considered

I don't know any other way to get this information

### Additional context

.

**Comment by rty3108** [comment]
Please can implement this features?
Thancks

**Comment by Sraoune** [comment]
Yeah, would be nice to have

**Comment by Sraoune** [comment]
Still needed :)

**Comment by rty3108** [comment]
Please can implement this features?
Thancks

**Comment by eherranzr** [comment]
Hi guys,
I just bought the device and position only shows 0% or 100%. Is the same for you?
I would say calibrating would solve this issue.
If we can support somehow, please let us know

**Comment by josejn** [comment]
> Hi guys, I just bought the device and position only shows 0% or 100%. Is the same for you? I would say calibrating would solve this issue. If I can support somehow, please let me know

Hi, I have bought some of them and they work like a charm (lex / leroy merlin version)
You have to calibrate them by pushing 5 times the phisical switch at the module. The blind will go full up, then full down and them up again.

The only issue I have is at the first pairing. I have to reboot mosquito brocker in order to get they publishing the state and follow the commands properly.

Having this feature would be great since they are ver inconvinient to disassemble because they barely fit under the wall buttons.

Regards.

**Comment by amanfromfrance** [comment]
I also would like this feature to be implemented as the auto-calibration does not work with my Bubendorff motors.

**Comment by lippertmarkus** [comment]
did one of you were able to start the manual calibration?

**Comment by amanfromfrance** [comment]
If you mean sending commands using this panel:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/58064665/458192a2-7112-4f7d-b625-053a9a9df4fe)

Then no it never worked.

**Comment by lippertmarkus** [comment]
I just were able to manually set the calibration bit:
<img width="769" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/1463140/4a8b1d8e-2597-4c41-9ad4-5745af7f9595">


but setting this just starts the automatic calibration (just like pressing the button on the module 5 times) and afterwards disables the automatic calibration again (bit1 = 0)

**Comment by amanfromfrance** [comment]
So you are sending something like 0x0010?

**Comment by lippertmarkus** [comment]
yes writing the attribute, but as a decimal (2)

**Comment by amanfromfrance** [comment]
I was able to get the complete list of attributes from the module using **zha_toolkit.scan_device** command:

```yaml
zha_toolkit_version: v1.1.10
zigpy_version: 0.64.1
zigpy_rf_version: 0.39.1
ieee_org:
  - 165
  - 93
  - 25
  - 254
  - 255
  - 177
  - 179
  - 244
ieee: f4:b3:b1:ff:fe:19:5d:a5
command: scan_device
command_data: null
start_time: "2024-06-20T16:18:26.653801+00:00"
errors: []
params:
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
scan:
  ieee: f4:b3:b1:ff:fe:19:5d:a5
  nwk: "0x5447"
  model: SIN-4-RS-20
  manufacturer: NodOn
  manufacturer_id: "0x4747"
  endpoints:
    - id: 1
      device_type: "0x0202"
      profile: "0x0104"
      in_clusters:
        "0x0000":
          cluster_id: "0x0000"
          title: Basic
          name: basic
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: zcl_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 8
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: app_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: stack_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 103
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: hw_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 50
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: manufacturer
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: NodOn
            "0x0005":
              attribute_id: "0x0005"
              attribute_name: model
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: SIN-4-RS-20
            "0x0006":
              attribute_id: "0x0006"
              attribute_name: date_code
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: "2020"
            "0x0007":
              attribute_id: "0x0007"
              attribute_name: power_source
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 1
            "0x0014":
              attribute_id: "0x0014"
              attribute_name: disable_local_config
              value_type:
                - "0x18"
                - bitmap8
                - Discrete
              access: READ|WRITE|REPORT
              access_acl: 7
              attribute_value: 0
            "0x4000":
              attribute_id: "0x4000"
              attribute_name: sw_build_id
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3.0.0-1.1.2
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: reset_fact_default
              command_arguments: <class 'zigpy.zcl.foundation.reset_fact_default'>
          commands_generated: {}
        "0x0003":
          cluster_id: "0x0003"
          title: Identify
          name: identify
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: identify_time
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE|REPORT
              access_acl: 7
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 2
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: identify
              command_arguments: <class 'zigpy.zcl.foundation.identify'>
            "0x01":
              command_id: "0x01"
              command_name: identify_query
              command_arguments: <class 'zigpy.zcl.foundation.identify_query'>
          commands_generated:
            "0x00":
              command_id: "0x00"
              command_name: identify_query_response
              command_args: <class 'zigpy.zcl.foundation.identify_query_response'>
        "0x0004":
          cluster_id: "0x0004"
          title: Groups
          name: groups
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: name_support
              value_type:
                - "0x18"
                - bitmap8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: add
              command_arguments: <class 'zigpy.zcl.foundation.add'>
            "0x01":
              command_id: "0x01"
              command_name: view
              command_arguments: <class 'zigpy.zcl.foundation.view'>
            "0x02":
              command_id: "0x02"
              command_name: get_membership
              command_arguments: <class 'zigpy.zcl.foundation.get_membership'>
            "0x03":
              command_id: "0x03"
              command_name: remove
              command_arguments: <class 'zigpy.zcl.foundation.remove'>
            "0x04":
              command_id: "0x04"
              command_name: remove_all
              command_arguments: <class 'zigpy.zcl.foundation.remove_all'>
            "0x05":
              command_id: "0x05"
              command_name: add_if_identifying
              command_arguments: <class 'zigpy.zcl.foundation.add_if_identifying'>
          commands_generated:
            "0x00":
              command_id: "0x00"
              command_name: add_response
              command_args: <class 'zigpy.zcl.foundation.add_response'>
            "0x01":
              command_id: "0x01"
              command_name: view_response
              command_args: <class 'zigpy.zcl.foundation.view_response'>
            "0x02":
              command_id: "0x02"
              command_name: get_membership_response
              command_args: <class 'zigpy.zcl.foundation.get_membership_response'>
            "0x03":
              command_id: "0x03"
              command_name: remove_response
              command_args: <class 'zigpy.zcl.foundation.remove_response'>
        "0x0005":
          cluster_id: "0x0005"
          title: Scenes
          name: scenes
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: count
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: current_scene
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: current_group
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: scene_valid
              value_type:
                - "0x10"
                - Bool
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: name_support
              value_type:
                - "0x18"
                - bitmap8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: add
              command_arguments: <class 'zigpy.zcl.foundation.add'>
            "0x01":
              command_id: "0x01"
              command_name: view
              command_arguments: <class 'zigpy.zcl.foundation.view'>
            "0x02":
              command_id: "0x02"
              command_name: remove
              command_arguments: <class 'zigpy.zcl.foundation.remove'>
            "0x03":
              command_id: "0x03"
              command_name: remove_all
              command_arguments: <class 'zigpy.zcl.foundation.remove_all'>
            "0x04":
              command_id: "0x04"
              command_name: store
              command_arguments: <class 'zigpy.zcl.foundation.store'>
            "0x05":
              command_id: "0x05"
              command_name: recall
              command_arguments: <class 'zigpy.zcl.foundation.recall'>
            "0x06":
              command_id: "0x06"
              command_name: get_scene_membership
              command_arguments: <class 'zigpy.zcl.foundation.get_scene_membership'>
          commands_generated:
            "0x00":
              command_id: "0x00"
              command_name: add_scene_response
              command_args: <class 'zigpy.zcl.foundation.add_scene_response'>
            "0x01":
              command_id: "0x01"
              command_name: view_response
              command_args: <class 'zigpy.zcl.foundation.view_response'>
            "0x02":
              command_id: "0x02"
              command_name: remove_scene_response
              command_args: <class 'zigpy.zcl.foundation.remove_scene_response'>
            "0x03":
              command_id: "0x03"
              command_name: remove_all_scenes_response
              command_args: <class 'zigpy.zcl.foundation.remove_all_scenes_response'>
            "0x04":
              command_id: "0x04"
              command_name: store_scene_response
              command_args: <class 'zigpy.zcl.foundation.store_scene_response'>
            "0x06":
              command_id: "0x06"
              command_name: get_scene_membership_response
              command_args: <class 'zigpy.zcl.foundation.get_scene_membership_response'>
        "0x0102":
          cluster_id: "0x0102"
          title: Window Covering
          name: window_covering
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: window_covering_type
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 8
            "0x0007":
              attribute_id: "0x0007"
              attribute_name: config_status
              value_type:
                - "0x18"
                - bitmap8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
            "0x0008":
              attribute_id: "0x0008"
              attribute_name: current_position_lift_percentage
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 100
            "0x0009":
              attribute_id: "0x0009"
              attribute_name: current_position_tilt_percentage
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0010":
              attribute_id: "0x0010"
              attribute_name: installed_open_limit_lift
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0011":
              attribute_id: "0x0011"
              attribute_name: installed_closed_limit_lift
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 65535
            "0x0012":
              attribute_id: "0x0012"
              attribute_name: installed_open_limit_tilt
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0x0013":
              attribute_id: "0x0013"
              attribute_name: installed_closed_limit_tilt
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 65535
            "0x0017":
              attribute_id: "0x0017"
              attribute_name: window_covering_mode
              value_type:
                - "0x18"
                - bitmap8
                - Discrete
              access: READ|WRITE|REPORT
              access_acl: 7
              attribute_value: 8
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: "65533"
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 1
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: physical_closed_limit_lift
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE|REPORT
              access_acl: 7
              manf_id: 4747
              attribute_value: 300
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: physical_closed_limit_tilt
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE|REPORT
              access_acl: 7
              manf_id: 4747
              attribute_value: 300
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: current_position_lift
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE|REPORT
              access_acl: 7
              manf_id: 4747
              attribute_value: 2000
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: current_position_tilt
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE|REPORT
              access_acl: 7
              manf_id: 4747
              attribute_value: 2000
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: up_open
              command_arguments: <class 'zigpy.zcl.foundation.up_open'>
            "0x01":
              command_id: "0x01"
              command_name: down_close
              command_arguments: <class 'zigpy.zcl.foundation.down_close'>
            "0x02":
              command_id: "0x02"
              command_name: stop
              command_arguments: <class 'zigpy.zcl.foundation.stop'>
            "0x05":
              command_id: "0x05"
              command_name: go_to_lift_percentage
              command_arguments: <class 'zigpy.zcl.foundation.go_to_lift_percentage'>
            "0x08":
              command_id: "0x08"
              command_name: go_to_tilt_percentage
              command_arguments: <class 'zigpy.zcl.foundation.go_to_tilt_percentage'>
          commands_generated: {}
        "0x1000":
          cluster_id: "0x1000"
          title: LightLink
          name: lightlink
          attributes:
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: "65533"
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 2
          commands_received:
            "0x41":
              command_id: "0x41"
              command_name: get_group_identifiers
              command_arguments: <class 'zigpy.zcl.foundation.get_group_identifiers'>
            "0x42":
              command_id: "0x42"
              command_name: get_endpoint_list
              command_arguments: <class 'zigpy.zcl.foundation.get_endpoint_list'>
          commands_generated:
            "0x01":
              command_id: "0x01"
              command_name: scan_rsp
              command_args: <class 'zigpy.zcl.foundation.scan_rsp'>
            "0x03":
              command_id: "0x03"
              command_name: device_info_rsp
              command_args: <class 'zigpy.zcl.foundation.device_info_rsp'>
            "0x11":
              command_id: "0x11"
              command_name: network_start_rsp
              command_args: <class 'zigpy.zcl.foundation.network_start_rsp'>
            "0x13":
              command_id: "0x13"
              command_name: network_join_router_rsp
              command_args: <class 'zigpy.zcl.foundation.network_join_router_rsp'>
            "0x15":
              command_id: "0x15"
              command_name: network_join_end_device_rsp
              command_args: <class 'zigpy.zcl.foundation.network_join_end_device_rsp'>
            "0x40":
              command_id: "0x40"
              command_name: endpoint_info
              command_args: <class 'zigpy.zcl.foundation.endpoint_info'>
            "0x41":
              command_id: "0x41"
              command_name: get_group_identifiers_rsp
              command_args: <class 'zigpy.zcl.foundation.get_group_identifiers_rsp'>
            "0x42":
              command_id: "0x42"
              command_name: get_endpoint_list_rsp
              command_args: <class 'zigpy.zcl.foundation.get_endpoint_list_rsp'>
      out_clusters:
        "0x0003":
          cluster_id: "0x0003"
          title: Identify
          name: identify
          attributes:
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 2
          commands_received:
            "0x00":
              command_id: "0x00"
              command_name: identify
              command_arguments: <class 'zigpy.zcl.foundation.identify'>
          commands_generated:
            "0x00":
              command_id: "0x00"
              command_name: identify_query_response
              command_args: <class 'zigpy.zcl.foundation.identify_query_response'>
            "0x01":
              command_id: "0x01"
              command_name: "1"
              command_args: not_in_zcl
        "0x0019":
          cluster_id: "0x0019"
          title: Ota
          name: ota
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: upgrade_server_id
              value_type:
                - "0xf0"
                - EUI64
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value:
                - 48
                - 178
                - 34
                - 254
                - 255
                - 39
                - 135
                - 4
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: file_offset
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 393278
            "0x0006":
              attribute_id: "0x0006"
              attribute_name: image_upgrade_status
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|REPORT
              access_acl: 5
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 4
          commands_received: {}
          commands_generated:
            "0x01":
              command_id: "0x01"
              command_name: "1"
              command_args: not_in_zcl
            "0x03":
              command_id: "0x03"
              command_name: "3"
              command_args: not_in_zcl
            "0x06":
              command_id: "0x06"
              command_name: "6"
              command_args: not_in_zcl
        "0x0102":
          cluster_id: "0x0102"
          title: Window Covering
          name: window_covering
          attributes:
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: "65533"
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              attribute_value: 3
          commands_received: {}
          commands_generated:
            "0x00":
              command_id: "0x00"
              command_name: "0"
              command_args: not_in_zcl
            "0x01":
              command_id: "0x01"
              command_name: "1"
              command_args: not_in_zcl
            "0x02":
              command_id: "0x02"
              command_name: "2"
              command_args: not_in_zcl
    - id: 242
      device_type: "0x0066"
      profile: "0xa1e0"
success: true
```
When I reached NodOn customer Support, they told me that there are **Manufacturers Specific Attributes** and that we could use the following attributes:

- **Calibration Vertical Run Time - Up**
   - **_Attribute_**: 0x0000
   - **_Type_**: uint16
   - **_Manufacturer Code_**: 0x1288
   - **_Description_**: Value of the current Up Vertical Run Time in ten of ms . By default, the value is set at OxFFFF, which means the Calibration has not been done. Once the Calibration has been done, the value changed to the Run Time calculated during the Calibration process.
- **Calibration Vertical Run Time - Down**
   - **_Attribute_**: 0x0001
   - **_Type_**: uint16
   - **_Manufacturer Code_**: 0x128B
   - **_Description_**: Value of the current Down Vertical Run Time in ten of ms By default, the value is set at OxFFFF, which means the Calibration has not been done. Once the Calibration has been done, the value changed to the Run Time calculated during the Calibration process.
- **Calibration Rotation Run Time - Up**
   - **_Attribute_**: 0x0002
   - **_Type_**: uint16
   - **_Manufacturer Code_**: 0x1288
   - **_Description_**: Value of the current Up Rotation Run Time in ten of ms By default, the value is set at 0x00C8 (= 200 => 2000 ms). The Rotation Run Time is not calculated by the Calibration process and must be set by the user using this attribute.
- **Calibration Rotation Run Time - Down**
   - **_Attribute_**: 0x0003
   - **_Type_**: uint16
   - **_Manufacturer Code_**: 0x1288
   - **_Description_**: Value of the current Down Rotation Run Time in ten of ms By default, the value is set at 0x00C8 (200 => 2000 ms). The Rotation Run Time is not calculated by the Calibration process and must be set by the user using this attribute.

But as you can see these Manufacturers attribues do not appear in the YAML... so I'm confused.

From what the customer support told me, it works perfectly using Z2M but to be honest I am reluctant to migrate...
