### ISSUE TITLE
When group has `optimistic: false`, other groups are not "notified" of change

### ISSUE THREAD

**Issue by SHxKM** [Koenkk/zigbee2mqtt#18457]
### What happened?

After the discussion [here](https://github.com/Koenkk/zigbee2mqtt/discussions/10719) and the clarifications by @Koenkk on what `optimistic: false` actually means, I believe what I'm experiencing is a bug.

If you have `big_group` with `light_a` and `light_b` as members and `optimistic: false`, and `small_group` with `light_a` as member, and you turn off `big_group`, `small_group` keeps reporting `ON`.

### What did you expect to happen?

That `small_group`, having the default `optimistic: true` setting, should change state according to its members' state.

### How to reproduce it (minimal and precise)

1. Create two groups, one, `big_group` with two lights, and one, `small_group` with a single light that is a member of `big_group`.
2. Set `big_group`'s `optimistic` flag to `false`.
3. Turn on `small_group`
4. Turn on `big_group`
5. Turn off `big_group`

I would've expected `small_group`'s state to change to `OFF` as well, but it remains `ON`.

Auxiliary YAML:

```yaml
"1000": # large ID numbers to avoid collision
  friendly_name: big_group
  optimistic: false
  devices:
    - light_1 # mutual member
    - light_2
"1001":
  friendly_name: small_group
  devices:
    - light_1 # mutual member
```

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

### Debug log

Nothing out of the ordinary.
