### ISSUE TITLE
After upgrading my RPI, my zigbee2mqtt docker not started

### ISSUE THREAD

**Issue by rafalolb** [Koenkk/zigbee2mqtt#18731]
### What happened?

I have installed zigbee2mqtt docker on my RPI.

1 years works fine, but 1 months ago I upgrade my RPI and I get the message:
Logs:
`Zigbee2MQTT:info  2023-08-25 12:25:11: Logging to console and directory: '/app/data/log/2023-08-25.12-25-11' filename: log.txt
Zigbee2MQTT:info  2023-08-25 12:25:11: Starting Zigbee2MQTT version 1.32.2 (commit #1ec1e57)
Zigbee2MQTT:info  2023-08-25 12:25:11: Starting zigbee-herdsman (0.17.2)
Zigbee2MQTT:error 2023-08-25 12:25:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-08-25 12:25:32: Failed to start zigbee
Zigbee2MQTT:error 2023-08-25 12:25:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-08-25 12:25:32: Exiting...
Zigbee2MQTT:error 2023-08-25 12:25:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:59:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)`

Then I back to my previous RPI backup and zigbee2mqtt works.

Today I ones again upgrade my RPI, and I have the same problem.

My device is available:
`rafal@raspberrypi:~ $ ls -l /dev/ttyACM0
crw-rw---- 1 root dialout 166, 0 08-25 11:42 /dev/ttyACM0
rafal@raspberrypi:~ $ ls -l /dev/serial/by-id
ls: nie ma dostępu do '/dev/serial/by-id': Nie ma takiego pliku ani katalogu
`

Configuration is good.
What can I do?

### Zigbee2MQTT version

1.32.2 (commit #1ec1e57)

### Adapter firmware version

-

### Adapter

 Sonoff ZBDongle-E

### Debug log

Zigbee2MQTT:info  2023-08-25 12:25:11: Logging to console and directory: '/app/data/log/2023-08-25.12-25-11' filename: log.txt
Zigbee2MQTT:info  2023-08-25 12:25:11: Starting Zigbee2MQTT version 1.32.2 (commit #1ec1e57)
Zigbee2MQTT:info  2023-08-25 12:25:11: Starting zigbee-herdsman (0.17.2)
Zigbee2MQTT:error 2023-08-25 12:25:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-08-25 12:25:32: Failed to start zigbee
Zigbee2MQTT:error 2023-08-25 12:25:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-08-25 12:25:32: Exiting...
Zigbee2MQTT:error 2023-08-25 12:25:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:59:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by william-sy** [comment]
`Configuration is good.`

Please provide the config :)

**Comment by y8s** [comment]
This also happened to me after a recent upgrade. Using ZBDongle-E in docker.

I can view the USB device in the docker container via 
```
pi@iot:~/docker $ docker exec -it zigbee2mqtt /bin/sh
/app # lsusb
Bus 001 Device 007: ID 1915:cafe
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 004: ID 1a86:55d4 (<--- that's the zigbee dongle)
Bus 001 Device 003: ID 1a40:0101
Bus 001 Device 002: ID 2109:3431
Bus 002 Device 002: ID 174c:55aa
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 005: ID 04d9:0007
Bus 001 Device 006: ID 051d:0002
/app #

```
Here's my compose file:
I have a udev rule to create a device called /dev/zbdongle-e, but that doesn't work either. 
I tried a few other ways of passing the USB through but they don't work either. Those are commented. The original method is uncommented.

```
     zigbee2mqtt:
       container_name: zigbee2mqtt
       restart: unless-stopped
   #    image: koenkk/zigbee2mqtt:latest-dev
       image: koenkk/zigbee2mqtt
       volumes:
         - ./zigbee2mqtt/data:/app/data
         - /run/udev:/run/udev:ro
       ports:
         - 55555:55555
       environment:
         - TZ=America/New_York
   #      - DEBUG=zigbee-herdsman*
       devices:
   #      - /dev/zbdongle-e:/dev/ttyUSB0
         - /dev/ttyACM1:/dev/ttyUSB0
   #      - /dev/bus/usb:/dev/bus/usb
   #      - /dev/bus/usb/001/004:/dev/ttyUSB0
```
z2m config relevant parts (minus devices and key):

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://10.10.10.40
frontend:
  port: 55555
  host: 0.0.0.0
serial:
  adapter: ezsp
  port: /dev/ttyUSB0
advanced:
  log_level: warn
```

with herdsman debug on I get this:

```
zigbee2mqtt  | 2023-08-25T14:14:24.186Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/zbdongle-e","baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee2mqtt  | 2023-08-25T14:14:24.268Z zigbee-herdsman:adapter:ezsp:erro Connection attempt 1 error: Error: Error while opening serialport 'Error: Error: Not a tty setting custom baud rate of 115200'
zigbee2mqtt  |     at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:94:28)
zigbee2mqtt  |     at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:75:22)
zigbee2mqtt  |     at /app/node_modules/@serialport/stream/dist/index.js:111:18
zigbee2mqtt  | 2023-08-25T14:14:29.277Z zigbee-herdsman:adapter:ezsp:ezsp Next attempt 2
```

**Comment by rafalolb** [comment]
My configuration:

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.10.17
  user: zigbee2mqtt_client
  password: zigbee2mqtt_client_olb
serial:
  port: /dev/ttyACM0
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
device_options:
  legacy: false
devices:
  '0xa4c1384138434fc0':
    friendly_name: CzujnikTemperatury1
    availability: true
    temperature_calibration: ''
frontend:
  port: 8080
  host: 0.0.0.0
  url: https://zigbee2mqtt.myhouse.org
```

docker-compose:
```
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/rafal/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
```
