### ISSUE TITLE
Successfully reenabled joining, even when permit_join: false

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#1881]
# Bug Report
## What happened
In configuration.yaml, I DISABLED joining: (permit_join:false)

```
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt.bearforce.org'
serial:
  port: /dev/ttyACM0
devices:

xxxx
```

However, in the log, I find

```
8/21/2019, 11:31:45 AM - info: Starting zigbee2mqtt version 1.5.1 (commit #ac3b924)
8/21/2019, 11:31:45 AM - info: Starting zigbee-shepherd
8/21/2019, 11:31:48 AM - info: zigbee-shepherd started
8/21/2019, 11:31:48 AM - info: Coordinator firmware version: '20190608'

(...)

8/21/2019, 11:31:48 AM - info: Zigbee: disabling joining new devices.
8/21/2019, 11:31:48 AM - info: Connecting to MQTT server at mqtt://mqtt.bearforce.org
8/21/2019, 11:31:50 AM - info: zigbee-shepherd ready
8/21/2019, 11:31:50 AM - info: Connected to MQTT server

(...)

8/21/2019, 11:31:51 AM - info: Zigbee: allowing new devices to join.
(...)
8/21/2019, 11:34:31 AM - info: Successfully reenabled joining
(...)
8/21/2019, 11:37:11 AM - info: Successfully reenabled joining
(...)
8/21/2019, 11:39:51 AM - info: Successfully reenabled joining

```

The last line is logged frequently.

What triggers this? Who is re-enabling joining?
Is joining now enabled/disabled?
Or just a bug in the logging?

kind regards
Bart

## What did you expect to happen
joining remains disabled

## Debug Info
zigbee2mqtt version: 1.5
CC2531 firmware version : CC2531_DEFAULT_20190608.zip
