### ISSUE TITLE
`MQTT device name is equal to entity name in your config` for switch as light device.

### ISSUE THREAD

**Issue by jeroen85** [Koenkk/zigbee2mqtt#18896]
### What happened?

I still experience the MQTT device vs entity name warning with the latest HA (2023.9.0) and Z2M (1.33.0) versions. It only occurs with one device. A smart plug I have set up as light in Z2M.

**HA Warning in logs.**
```
2023-09-07 14:48:34.763 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT device name is equal to entity name in your config {'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': Template<template=({{ value_json.state }}) renders=0>, 'payload_available': 'online', 'payload_not_available': 'offline'}, {'topic': 'zigbee2mqtt/Kastlicht/availability', 'value_template': Template<template=({{ value_json.state }}) renders=0>, 'payload_available': 'online', 'payload_not_available': 'offline'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/Kastlicht/set', 'device': {'identifiers': ['zigbee2mqtt_0x540f57fffe91ffb6'], 'manufacturer': 'TuYa', 'model': 'Smart plug (with power monitoring by polling) (TS011F_plug_3)', 'name': 'Kastlicht', 'connections': []}, 'name': 'Kastlicht', 'object_id': 'kastlicht', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.33.0', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Kastlicht', 'state_value_template': Template<template=({{ value_json.state }}) renders=0>, 'unique_id': '0x540f57fffe91ffb6_light_zigbee2mqtt', 'schema': 'basic', 'payload_available': 'online', 'optimistic': False, 'on_command_type': 'last', 'white_scale': 255, 'payload_not_available': 'offline', 'enabled_by_default': True, 'brightness_scale': 255, 'encoding': 'utf-8', 'qos': 0, 'retain': False}, this is not expected. Please correct your configuration. The entity name will be set to `null`
```

**Config in Z2M for specific device**
Conform [docs](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light)
```
  '0x540f57fffe91ffb6':
    friendly_name: Kastlicht
    measurement_poll_interval: 30
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        name: Kastlicht
        value_template: null
        state_value_template: '{{ value_json.state }}'
```

**MQTT info within HA**
```
Kastlicht (light.kastlicht)
MQTT discovery data:
Topic: homeassistant/light/0x540f57fffe91ffb6/light/config
Payload
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/Kastlicht/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
command_topic: zigbee2mqtt/Kastlicht/set
device:
  identifiers:
    - zigbee2mqtt_0x540f57fffe91ffb6
  manufacturer: TuYa
  model: Smart plug (with power monitoring by polling) (TS011F_plug_3)
  name: Kastlicht
name: Kastlicht
object_id: kastlicht
origin:
  name: Zigbee2MQTT
  sw_version: 1.33.0
  support_url: https://www.zigbee2mqtt.io
payload_off: 'OFF'
payload_on: 'ON'
state_topic: zigbee2mqtt/Kastlicht
state_value_template: '{{ value_json.state }}'
unique_id: 0x540f57fffe91ffb6_light_zigbee2mqtt
platform: mqtt
```

### What did you expect to happen?

No warning after this fix https://github.com/Koenkk/zigbee2mqtt/commit/f6196107a75f9257366505a3ad5ef7b29ff5bc1c

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

Not relevant

### Adapter

Not relevant

**Comment by Drafteed** [comment]
Replace light `name` to `null`:

```yaml
  '0x540f57fffe91ffb6':
    friendly_name: Kastlicht
    measurement_poll_interval: 30
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        name: null
        value_template: null
        state_value_template: '{{ value_json.state }}'
```
