### ISSUE TITLE
[Feature request]: a branch that supports new devices for Home Assistant < 2023.08

### ISSUE THREAD

**Issue by cocoabox** [Koenkk/zigbee2mqtt#18964]
### Is your feature request related to a problem? Please describe

https://github.com/Koenkk/zigbee2mqtt/issues/18445 and merges related have rendered zigbee2mqtt>=1.33.0 to be incompatible with HomeAssistant < 2023.08 ; however many users including me are still using 2023.08 as a set-and-forget setup.

### Describe the solution you'd like

Can there be a branch that continues to support new devices but is compatible with HomeAssistant < 2023.08 ?

### Describe alternatives you've considered

I have considered upgrading HomeAssistant but newer versions do not work well with mqtt+tls. MQTT Configuration done in configuration.yaml have been deprecated and all mqtt configuration needs to be done from the UI. When setting up MQTT+TLS from the UI, it gives the following error:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/7977116/a25e50e3-1423-40fb-9544-a267df3b9ab7)
 
I hence could not upgrade my HomeAssistant to a newer version

### Additional context

n/a

**Comment by Drafteed** [comment]
You can try manually override `name` for HA devices in **configuration.yaml** to match the old requirements:

```yaml
devices:
  "0x12345678":
    friendly_name: my_light
    homeassistant:
      light:
        name: "Light"
  "0x12345678":
    friendly_name: my_switch
    homeassistant:
      switch_left:
        name: "Switch Left"
  "0x1112231":
    friendly_name: my_temperature
    homeassistant:
      temperature:
        name: "Temperature"
```

See https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#overriding-discovery-properties
