### ISSUE TITLE
sending info logs to syslog but "warn" is configured

### ISSUE THREAD

**Issue by Jarod2801** [Koenkk/zigbee2mqtt#18994]
### What happened?

I have the following log configuration:

```yml
advanced:
  log_level: warn
  timestamp_format: YYYY-MM-DD HH:mm:ss
  log_directory: data/log/%TIMESTAMP%
  log_file: log.txt
  log_rotation: true
  log_output:
    - console
    - file
    - syslog
  log_symlink_current: false
  log_syslog:
    host: 1.2.3.4
    port: 514
    protocol: udp4
    path: /dev/log
    pid: process.pid
    facility: local0
    localhost: zigbee2mqtt
    type: '5424'
    app_name: Zigbee2MQTT
    eol: \n
```
The log file are looking fine, there I see only warnings or higher, but the syslog contains logs like for e.g.  the color_temp or brightness

```
2023-09-17 00:18:15 | MQTT publish: topic 'z2m/Spiegel', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"state":"OFF"}'
```

### What did you expect to happen?

Maybe I have interpreted the MQTT message wrong, but how to get rid of these messages in my syslog?

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

20230507

### Adapter

CC2652 RB
