### ISSUE TITLE
[Feature request]: TS0601 min not persist after power loss

### ISSUE THREAD

**Issue by devildant** [Koenkk/zigbee2mqtt#19097]
### Is your feature request related to a problem? Please describe

after a power cut the pre-recorded min is reset, and no entity exists for this option, so it is impossible to force a value with automation

### Describe the solution you'd like

1) add a checkbox to remember and restore the value if changed

2) add a specific entity for this value

### Describe alternatives you've considered

all solutions suit me as long as I can force this value

### Additional context

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8700106/4b9d1e26-4a6f-49ed-83c9-154dd924bfa7)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8700106/561a847c-050b-410a-b7e6-9728929bd883)

**Comment by devildant** [comment]
Revelation of the night, MQTT can be used from an automation... I'm stupid not to have thought of it before opening this subject

**Comment by iqlogic** [comment]
> Revelation of the night, MQTT can be used from an automation... I'm stupid not to have thought of it before opening this subject

Hello, please how did you solved it? Could you please share your automation? Thank you

EDIT: I've got it.
```
alias: Bedroom Main Light Min Brightness
description: >-
  Detects when the Great Hall Main Light comes online after power loss and sets Bedroom Main Light min_brightness.
triggers:
  - trigger: state
    entity_id:
      - switch.great_hall_main_light
    from: unavailable
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: "0"
      topic: zigbee2mqtt/Bedroom Main Light/set
      payload: "{\"min_brightness\": 100}"
mode: single
```
