### ISSUE TITLE
wrong entity_id generation for switch exposing as a light

### ISSUE THREAD

**Issue by Marku555** [Koenkk/zigbee2mqtt#19107]
### What happened?

When I use code from https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light to expose switch as light, I've get long entity_id in HA.
Example code:
```yaml
  '0x5900c602a0c93d15':
    friendly_name: light_switch_balcony
    debounce: 1
    homeassistant: 
      #switch_left no need to override
      switch_right:
        type: light
        object_id: balcony_switch_right
      balcony_switch_right:
        name: balcony_spots
        icon: mdi:lightbulb-spot
        value_template: null
        state_value_template: '{{ value_json.state_right }}'
```
Generated entity_id in HA looks like: `light.light_switch_balcony_balcony_switch_right`.
On previous versions of zigbee2mqtt for overridden switches the entity id lookes like `light.balcony_spots`

### What did you expect to happen?

Entity_id in HA for overridden switches looks like: `light.balcony_spots`.

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

20230507

### Adapter

zStack3x0 SONOFF Zigbee 3.0 USB Dongle
