### ISSUE TITLE
[New device support]: TS0601_TZE200_t6gq6nju Ceiling Fan Switch

### ISSUE THREAD

**Issue by mick5423** [Koenkk/zigbee2mqtt#19425]
### Link

https://www.aliexpress.com/item/1005005766866247.html

### Database entry

{"id":4,"type":"Router","ieeeAddr":"0xa4c1383a414277ba","nwkAddr":15841,"manufId":4417,"manufName":"_TZE200_t6gq6nju","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"e��,ff��,\u0012","65506":54,"65508":1,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZE200_t6gq6nju","zclVersion":3,"appVersion":70,"modelId":"TS0601","powerSource":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1698280708065,"defaultSendRequestWhen":"immediate"}

### Comments

Attached attempt at a converter appears to be working. Only points 1 and 101 are reported from physical interaction, 2, 11 and 12 were identified through Tuya IoT platform. 

A couple of firmware bugs maybe worth noting on future device page?
- Device doesn't always report on/off state correctly when physically interacting with device. (responds appropriately to all speed/state changes sent from Zigbee2MQTT though)
- Device resets backlight setting after power cycling (whether paired with Tuya gateway or Zigbee2MQTT)

If worth including on device page or for anyone who stumbles upon it, Home Assistant template presently in use:

```
fan:
  - platform: template
    fans:
      test_fan:
        friendly_name: "Ceiling Fan"
        value_template: "{{ states('switch.ceiling_fan') }}"
        turn_on:
          - service: switch.turn_on
            target:
              entity_id: switch.ceiling_fan
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.ceiling_fan
        speed_count: 3
        percentage_template: "{{ (float(states('number.ceiling_fan_fan_speed'))*33.2)|round(0) }}"
        set_percentage:
          - if:
              condition: template
              value_template: "{{ percentage > 0 }}"
            then:
              - service: number.set_value
                target:
                  entity_id: number.ceiling_fan_fan_speed
                data:
                  value: "{{ (percentage/33)|round(0) }}"
              - service: switch.turn_on
                target:
                  entity_id: switch.ceiling_fan
            else:
              - service: switch.turn_off
                target:
                  entity_id: switch.ceiling_fan
```

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_t6gq6nju',
        },
    ],
    model: 'TS0601_TZE200_t6gq6nju',
    vendor: 'TuYa',
    description: 'Ceiling Fan',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
    exposes: [
        tuya.exposes.switch(),
        tuya.exposes.countdown().withValueMin(0).withValueMax(720).withUnit('m').withDescription('Max ON time in minutes'),
        e.power_on_behavior(['off', 'on', 'previous']).withAccess(ea.STATE_SET),
        e.enum('indicator', ea.ALL, ['off', 'off/on', 'on']).withDescription('LED indicator mode').withAccess(ea.STATE_SET),
        e.numeric('fan_speed', ea.STATE_SET).withValueMin(1).withValueMax(3).withValueStep(1).withDescription('Speed of the fan'),
    ],
    meta: {
        tuyaDatapoints: [
            // Datapoints from Tuya IoT platform:
            //"1":"Fan switch",
            //"2":"Fan countdown",
            //"11":"Power-on state setting", enum. Off / On / Previous
            //"12":"Indicator status setting", enum. Off / (Off/On Status) / On
            //"101":"Fan Level" enum. 0 = Low, 1 = Medium, 2 = High
            
            [1, 'state', tuya.valueConverter.onOff],
            [2, 'countdown', tuya.valueConverter.countdown],
            [11, 'power_on_behavior', tuya.valueConverterBasic.lookup({'off': tuya.enum(0), 'on': tuya.enum(1), 'previous': tuya.enum(2)})],
            [12, 'indicator', tuya.valueConverterBasic.lookup({'off': tuya.enum(0), 'off/on': tuya.enum(1), 'on': tuya.enum(2)})],
            [101, 'fan_speed', tuya.valueConverterBasic.lookup({'1': tuya.enum(0), '2': tuya.enum(1), '3': tuya.enum(2)})],
        ],
    },
};

module.exports = definition;
```
