### ISSUE TITLE
Unable to convert switch to light

### ISSUE THREAD

**Issue by LaUr3nTiU** [Koenkk/zigbee2mqtt#19564]
### What happened?

Following the documentation,

```
devices:
  "0x30fb10fffe6e9e0d":
    friendly_name: light_bedroom
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        name: null
        value_template: null
        state_value_template: "{{ value_json.state }}"
```

I am expecting that this device shows up as a `light` in Home Assistant, but it still shows up as a `switch`.

### What did you expect to happen?

I would expect that the device shows up as a light instead.

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20210708

### Adapter

SONOFF ZigBee 3.0 USB Dongle Plus
