### ISSUE TITLE
Tuya TS0601 _TZE200_pw7mji0l Cover Motor: Open and Close state not working properly in Home Assistant

### ISSUE THREAD

**Issue by didi3r** [Koenkk/zigbee2mqtt#19665]
### What happened?

The "open" and "closed" states reported to Home Assistant are not working as expected. They seem to be based on whatever you set on the "state". 

1. If you set it to "Open" in zigbee2mqtt, and then change the position through zigbee2mqtt or the remote. The state would be "open" regarding the position.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/2e9261ea-19a8-4694-923a-fe9a9d003833)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/9c295a8e-4109-4499-9384-db63bd03111d)

1. If you set it to "Close" in zigbee2mqtt, and then change the position through zigbee2mqtt or the remote. The state would be "closed" regarding the position.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/db4e4a69-ef52-458f-894f-6ec18a5e1eb2)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/f4e4029f-8ea6-4b1c-9b17-e3740c1a9cab)

3. If you set it to "Stop" in zigbee2mqtt, and then change the position through zigbee2mqtt or the remote. The state would be "open" or "closed" **based on the position**.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/cde98def-72fa-40ec-a0c6-82e7b76b28ee)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/8c99b138-0a12-4c3f-bc35-12841cb756a5)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/9f79d9e2-4b85-40a2-891a-a585fc8fd0ce)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2186020/193052ff-4946-4445-ba9e-35f04c4c2df4)

### What did you expect to happen?

I would like the reported state of the covers to be always based on the position, not on what the user can randomly change.

### Zigbee2MQTT version

1.33.2-dev commit: c8dcd71

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongleP (CC2652P)

**Comment by GvdbW** [comment]
I have the same issue with the roller TZE200_bv1jcqqu

it all worked normally until the last update. Now all my automation are broken and work randomly. 

It seems related to this issue 
https://github.com/Koenkk/zigbee2mqtt/issues/19539

**Comment by elad-bar** [comment]
i have the same issue for all tuya homeetec covers, checked the converters (i added them almost a year ago), nothing change in them but it now throws errors as described above

**Comment by elad-bar** [comment]
adding more details, devices:
- _TZE200_p6vz3wzt
- _TZE200_jhkttplm
- _TZE200_5nldle7w

**Comment by alexeiw123** [comment]
I am seeing this behaviour as well, has anyone identified the source of the problem?

**Comment by alexeiw123** [comment]
@Koenkk how can we take an integrated device from .ts and use that to in a local .js external converter? I'd like to see if I can find a way around this but the only way I can see is starting from scratch.

The devices position updates OK so somehow just need the state to reflect the position regardless of if it is operated by ZigBee or RF remote.

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/ea7f0f705ad78880088b84ac380415f4): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, 
- in the frontend, check if the description of this device now ends with `CUSTOM` (this indicates the external converter has been loaded correctly)
- check if issue is fixed

**Comment by alexeiw123** [comment]
> Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/ea7f0f705ad78880088b84ac380415f4):
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m,
> * in the frontend, check if the description of this device now ends with `CUSTOM` (this indicates the external converter has been loaded correctly)
> * check if issue is fixed

Thanks - I have added this external converter and I get no errors in my logs, however the blind description is still `cover motor` not `cover motor CUSTOM` as I'd expect.

external converter is showing in the GUI settings, so config seems to be working OK.

**Comment by alexeiw123** [comment]
> * check if issue is fixed

OK I updated this line:
`tuya.whitelabel('Zemismart', 'ZM25EL', 'Cover motor', ['_TZE200_pw7mji0l']),`
To this:
`tuya.whitelabel('Zemismart', 'ZM25EL', 'Cover motor CUSTOM', ['_TZE200_pw7mji0l']),`

The external converter was loading but the white label line was preventing the description form updating

**Comment by alexeiw123** [comment]
> * check if issue is fixed

Unfortunately no - using the external converter, the position expose doesn't update at all anymore.

**Comment by alexeiw123** [comment]
temporary workaround:

This will create a new cover entity in HA that interacts with the Z2MQTT created cover entity, but updates state based on the reported position in Z2M. in my very short testing this seems to be working for me until the converter issue is figure out.

```
cover:
  - platform: template
    covers:
      your_blind_temp:
        device_class: shade
        friendly_name: "Your blind temp"
        unique_id: your_blind_temp
        position_template: >-
          {{ state_attr('cover.your_blind', 'current_position')}}
        value_template: >-
          {% if state_attr('cover.your_blind', 'current_position') | int(default=0) > 0 %}
            open
          {% else %}
            closed
          {% endif %}
        open_cover:
          action: cover.open_cover
          target:
            entity_id: cover.your_blind
        close_cover:
          action: cover.close_cover
          target:
            entity_id: cover.your_blind
        stop_cover:
          action: cover.stop_cover
          target:
            entity_id: cover.your_blind
        set_cover_position:
          action: cover.set_cover_position
          data:
            position: "{{position}}"
          target:
            entity_id: cover.your_blind
```
