### ISSUE TITLE
Question about advanced settings of configuration.yaml

### ISSUE THREAD

**Issue by alwashe** [Koenkk/zigbee2mqtt#1969]
with reference to: https://www.zigbee2mqtt.io/configuration/configuration.html

**1. Are these options not also optional, like the other advanced settings?**
```
  # Availability timeout in seconds, disabled by default (0).
  # When enabled, devices will be checked if they are still online.
  # Only AC powered routers are checked for availability.
  availability_timeout: 0

  # Blacklist devices from being checked for availability
  availability_blacklist:
    - DEVICE_FRIENDLY_NAME

  # Enables report feature (see information -> report for more details)
  report: true

  # Home Assistant discovery topic
  homeassistant_discovery_topic: 'homeassistant'

  # Home Assistant status topic
  homeassistant_status_topic: 'hass/status'
```

**2. What are the default options of the advanced settings?**

Huge thanks for your work.
