### ISSUE TITLE
Crash while pairing Xiaomi MiJia wireless switch (WXKG01LM)

### ISSUE THREAD

**Issue by hahrens** [Koenkk/zigbee2mqtt#198]
I'm unable to pair my first Device with zigbee2mqtt, a MiJia Switch (WXKG01LM). Once i've start the bridge in my console and allow pairing, i've started the button-pairing by pressing the config button on the switch until the led is blinking (~4sec) and continue it by pressing the button every second according to the [wiki documentation](https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices#xiaomi).

This is a repeatable error, i get it every time i try to pair the button.

```
~/zigbee2mqtt> sudo node index.js                                                                                                         master!
2018-7-16 11:49:02 DEBUG Using zigbee-shepherd with settings: '{"net":{"panId":6754,"channelList":[11]},"dbPath":"/home/pi/zigbee2mqtt/data/database.db","sp":{"baudrate":115200,"rtscts":true}}'
2018-7-16 11:49:02 INFO Starting zigbee2mqtt version 0.1.0 (commit #ae41b7b)
2018-7-16 11:49:02 INFO Starting zigbee-shepherd
2018-7-16 11:49:03 INFO zigbee-shepherd started
2018-7-16 11:49:03 INFO Currently 0 devices are joined:
2018-7-16 11:49:03 WARN `permit_join` set to  `true` in configuration.yaml.
2018-7-16 11:49:03 WARN Allowing new devices to join.
2018-7-16 11:49:03 WARN Set `permit_join` to `false` once you joined all devices.
2018-7-16 11:49:03 INFO Zigbee: allowing new devices to join.
2018-7-16 11:49:03 INFO Connecting to MQTT server at mqtt://localhost
2018-7-16 11:49:03 INFO zigbee-shepherd ready
2018-7-16 11:49:03 INFO Connected to MQTT server
2018-7-16 11:49:03 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/state', payload: 'online'
spinlock: false []
/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:297
        dataTypeStr = zclId.dataType(dataType).key;
                                              ^

TypeError: Cannot read property 'key' of undefined
    at ensureDataTypeString (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:297:47)
    at getDataType (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:307:16)
    at Dissolve.<anonymous> (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:689:28)
    at Dissolve._transform (/home/pi/zigbee2mqtt/node_modules/dissolve/index.js:80:16)
    at Dissolve.Transform._read (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Dissolve.Transform._write (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Dissolve.Writable.write (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Dissolve.Writable.end (/home/pi/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:426:10)
```

I've found the issue #107 with the same error message and already tried the commit referenced in [this comment](https://github.com/Koenkk/zigbee2mqtt/issues/107#issuecomment-395981296) - doesn't fix it for me.

Here is my configuration.yml:
```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0

advanced:
  log_level: debug
```
