### ISSUE TITLE
Conbee III fails to start

### ISSUE THREAD

**Issue by fborch** [Koenkk/zigbee2mqtt#19821]
### What happened?

Fails to start with Conbee III adapter

### What did you expect to happen?

Service would start

### How to reproduce it (minimal and precise)

Config file:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-admin
  password: Trolldalen
serial:
  port: /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03111043-if00-port0
  baudrate: 115200
  adapter: deconz
zigbee_herdsman_debug: true
```

This is in Home Assistant VM with USB passthrough

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

Unknown, adapter fails to start

### Adapter

Conbee III

### Debug log

[20:04:16] INFO: Preparing to start...
[20:04:17] INFO: Socat not enabled
[20:04:17] INFO: Zigbee Herdsman debug logging enabled
[20:04:18] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-11-22 20:04:21: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2023-11-22 20:04:21: Logging to console and directory: '/config/zigbee2mqtt/log/2023-11-22.20-04-21' filename: log.txt
Zigbee2MQTT:info  2023-11-22 20:04:21: Starting Zigbee2MQTT version 1.33.2 (commit #unknown)
Zigbee2MQTT:info  2023-11-22 20:04:21: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:debug 2023-11-22 20:04:21: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[206,203,242,104,143,173,219,98],"networkKey":"HIDDEN","panID":29510},"serialPort":{"adapter":"deconz","baudRate":115200,"path":"/dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03111043-if00-port0"}}'
2023-11-22T19:04:21.626Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-11-22T19:04:21.629Z zigbee-herdsman:deconz:driver Set delay to 0
2023-11-22T19:04:21.630Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[65,117,116,43,196,112,25,195,202,12,213,92,138,118,55,41],"panID":29510,"extendedPanID":[206,203,242,104,143,173,219,98],"channelList":[11]},"serialPort":{"baudRate":115200,"path":"/dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03111043-if00-port0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-11-22T19:04:21.630Z zigbee-herdsman:deconz:driver Opening with /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03111043-if00-port0
2023-11-22T19:04:21.641Z zigbee-herdsman:deconz:driver Serialport opened
2023-11-22T19:04:21.641Z zigbee-herdsman:controller:log Started with result 'resumed'
2023-11-22T19:04:21.642Z zigbee-herdsman:controller:log Injected database: true, adapter: true
2023-11-22T19:04:21.643Z zigbee-herdsman:controller:database:log Writing database to '/config/zigbee2mqtt/database.db'
2023-11-22T19:04:21.652Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
2023-11-22T19:04:24.631Z zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
2023-11-22T19:04:24.636Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 2 request id: 1
2023-11-22T19:04:31.656Z zigbee-herdsman:deconz:driver Timeout for request - CMD: 0xa seqNr: 1
Zigbee2MQTT:error 2023-11-22 20:04:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-11-22 20:04:31: Failed to start zigbee
Zigbee2MQTT:error 2023-11-22 20:04:31: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-11-22 20:04:31: Exiting...
Zigbee2MQTT:error 2023-11-22 20:04:31: undefined
