### ISSUE TITLE
IKEA Spotlights not working with initial brightness

### ISSUE THREAD

**Issue by Sku1ly** [Koenkk/zigbee2mqtt#19892]
### What happened?

Light not turning on at full brightness, even within Z2M control panel itself. Light shows full brightness in control panel and MQTT message but it isn't. Manually adjusting slider to 100% works. MQTT message shows exact same in both messages.
I can't recall what version this started to happen in but it's a very recent problem.

TRADFRI bulb GU10 WS 400lm on 2.3.087

### What did you expect to happen?

Light to turn on at full brightness

### How to reproduce it (minimal and precise)

Turn light on via Z2M dashboard

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20211217

### Adapter

Sonoff 3.0 Dongle Plus

### Debug log

```
Zigbee2MQTT:debug 2023-11-27 17:09:45: Publishing 'set' 'state' to 'Group - Kitchen Lights'
Zigbee2MQTT:info  2023-11-27 17:09:45: MQTT publish: topic 'zigbee2mqtt/Light - Kitchen 1', payload '{"brightness":254,"color_mode":"color_temp","color_options":null,"color_temp":359,"level_config":{"on_level":"previous"},"linkquality":112,"power_on_behavior":null,"state":"ON","update":{"installed_version":587757105,"latest_version":587757105,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-11-27 17:09:45: MQTT publish: topic 'zigbee2mqtt/Group - Kitchen Lights', payload '{"brightness":254,"color_mode":"color_temp","color_temp":359,"state":"ON"}'
Zigbee2MQTT:info  2023-11-27 17:09:45: MQTT publish: topic 'zigbee2mqtt/Light - Kitchen 2', payload '{"brightness":254,"color_mode":"color_temp","color_options":null,"color_temp":359,"level_config":{"on_level":"previous"},"linkquality":98,"power_on_behavior":null,"state":"ON","update":{"installed_version":587757105,"latest_version":587757105,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-11-27 17:09:45: MQTT publish: topic 'zigbee2mqtt/Light - Kitchen 3', payload '{"brightness":254,"color_mode":"color_temp","color_options":null,"color_temp":359,"level_config":{"on_level":"previous"},"linkquality":83,"power_on_behavior":null,"state":"ON","update":{"installed_version":587757105,"latest_version":587757105,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-11-27 17:09:45: MQTT publish: topic 'zigbee2mqtt/Light - Kitchen 4', payload '{"brightness":254,"color_mode":"color_temp","color_options":null,"color_temp":359,"level_config":{"on_level":"previous"},"linkquality":80,"power_on_behavior":null,"state":"ON","update":{"installed_version":587757105,"latest_version":587757105,"state":"idle"},"update_available":false}'
```

**Comment by Sku1ly** [comment]
This is now happening with two more IKEA devices. I've rolled back Z2M version but no change.

**Comment by bartplessers** [comment]
Same problem here

Current version: 1.33.2-1 
CC2652 (Electrolama zig-a-zig-ah! (zzh!))
CC2652R_coordinator_20221226

Very annoying, it happens with ALL my IKEA bulbs (+/- 25 bulbs, all kinds)

B

**Comment by Sku1ly** [comment]
@bartplessers I've actually just fixed it. Even though transition is by default set to 0 I've had to set it again in the config.yaml file, now all my bulbs are working fine. 

Give it a try

**Comment by bartplessers** [comment]
> I've had to set it again in the config.yaml file

I can set this in an automation, i.e.
```
- id: '0x14b457fffe4fa583_action_on'
  alias: '(R07) action on'
  initial_state: true
  trigger:
  - entity_id: sensor.my_n00_p00_switch_r07_achterzijde_action
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.group_n00_p00_plafond_bijkeuken
      transition: 0
    service: light.turn_on
```

But where can I set "transition: 0" as default value for all (IKEA) lights?

**Comment by bartplessers** [comment]
> I noticed that you also work with lightgroups. Is this related?

nope, just tested this. Indeed same problem when adressing bulb directly

**Comment by Sku1ly** [comment]
Hi @bartplessers this is my zigbee2mqtt config.yaml example, it's still working after about 15 hours

<img width="149" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/45756272/9405aebe-dbd1-4814-b9f7-520409cfb91a">

```
    friendly_name: Group - Kitchen Lights
    devices:
      - 0x000b57fffec1ec80/1
      - 0x000b57fffebad38d/1
      - 0x000b57fffec01ba2/1
      - 0x000b57fffebb92c6/1
    transition: 0
```
