### ISSUE TITLE
Disabled device unexpectedly pinged

### ISSUE THREAD

**Issue by protyposis** [Koenkk/zigbee2mqtt#20021]
### What happened?

I have `availability` enabled and multiple (active) devices disabled. Some of them are still pinged by Z2M, resulting in an error (because they are disconnected from the network / from power). Re-enabling/disabling and restarting Z2M does not fix this.

```
Failed to ping '<devicename>' (attempt 1/1, Read 0x<address>/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)))
```

I think this was happening at least since 1.33.2, it just became apparent in 1.34.0 due to https://github.com/nurikk/zigbee2mqtt-frontend/issues/1847. 

### What did you expect to happen?

I expect disabled devices not to be pinged (as is the case for most of my disabled devices).

### How to reproduce it (minimal and precise)

1. Remove active device from network (by unplugging / cutting power)
2. Disable device in Z2M UI
3. Restart Z2M
4. (observe device still pinged)

This is not a reliable repro, since, as explained above, it doesn't happen with all devices.
Example device: Lidl HG06337 power plug (_TZ3000_kdi2o9m6)

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20221226

### Adapter

Sonoff ZBDongle-P

**Comment by Koenkk** [comment]
Could you provide your `configuration.yaml`? (without the sensitive details of course)

**Comment by protyposis** [comment]
Sure, here it is:

```
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  legacy_entity_attributes: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: <snipped>
  password: <snipped>
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
  adapter: zstack
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key: <snipped>
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
  legacy_availability_payload: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500

```
