### ISSUE TITLE
Entity category `config` is invalid for sensors, stops working from HA Core 2024.2.0

### ISSUE THREAD

**Issue by seblu** [Koenkk/zigbee2mqtt#20252]
### What happened?

When a device export a "[numeric](https://github.com/Koenkk/zigbee2mqtt/blob/03ba647dc6b5f299f8f3ab441712999fcb3a253e/lib/extension/homeassistant.ts#L597C48-L597C48)" type,  z2m may creates 2 entities, one with domain `sensor` and one with domain `number`. When `number` is allowed, `sensor` is disabled by default.

This numeric entity may represent a configuration property and  you may want to customize it like this:
```yaml
  '0x0123456789abcdef':
    homeassistant:
      temperature_threshold:
        entity_category: config
```

In this case, entity_ids are `sensor.0x0123456789abcdef_temperature_threshold` and `number.0x0123456789abcdef_temperature_threshold`. The both entities share a lot, like `object_id` or `unique_id`.

It causes the following warning message:
```
WARNING (MainThread) [homeassistant.components.mqtt.mixins] Entity category `config` is invalid for sensors, ignoring. This stops working from HA Core 2024.2.0
```
I guess than HA devs, do not recognize read-only entities like sensors as configuration entities and that makes sense.

### What did you expect to happen?

Be able to override each `entity_category` attribute for each entities created by z2m.

```yaml
  '0x0123456789abcdef':
    homeassistant:
      temperature_threshold:
        entity_category: diagnostic
      number_temperature_threshold:
        entity_category: config
```

### How to reproduce it (minimal and precise)

Find a device which export a modifiable numeric value and set it `entity_category` to "config".

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20230507

### Adapter

zStack3x0
