### ISSUE TITLE
When Ethernet ZigBee coordinator goes away, docker stops, and cannot be restarted.

### ISSUE THREAD

**Issue by Carlosmsithios01** [Koenkk/zigbee2mqtt#20279]
### What happened?

If my POE ZigBee coordinator goes offline: zigbee2mqtt (in docker) does this:
```
zigbee2mqtt  | Zigbee2MQTT:error 2023-12-18 15:40:20: Adapter disconnected, stopping
zigbee2mqtt  | Zigbee2MQTT:info  2023-12-18 15:40:20: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
zigbee2mqtt  | Zigbee2MQTT:info  2023-12-18 15:40:20: Disconnecting from MQTT server
zigbee2mqtt  | Zigbee2MQTT:info  2023-12-18 15:40:20: Stopping zigbee-herdsman...
zigbee2mqtt  | Zigbee2MQTT:error 2023-12-18 15:40:20: Failed to stop Zigbee2MQTT
pi@lys:~ $ 
pi@lys:~ $ 
pi@lys:~ $ 
pi@lys:~ $ docker compose top
mqtt
UID    PID    PPID   C    STIME    TTY   TIME       CMD
1883   1060   997    0    des.12   ?     00:03:19   mosquitto -c /mosquitto-no-auth.conf   

node-red
UID   PID    PPID   C    STIME    TTY   TIME       CMD
pi    1646   1626   0    des.12   ?     00:00:00   /bin/bash ./entrypoint.sh   
pi    1709   1646   0    des.12   ?     00:23:38   node-red                    

pi@lys:~ $ docker compose start zigbee2mqtt 
[+] Running 0/1
 ⠴ Container zigbee2mqtt  Starting                                                                                                   0.5s 
pi@lys:~ $ 
```

Once this happens, I am unable to start this container again until rebooting the Rpi.

### What did you expect to happen?

I expect it to continue running, trying to reconnect.
or - at least allow the docker to start again

### How to reproduce it (minimal and precise)

run zigbee2mqtt in docker - for example with this compose file:
```
pi@lys:~ $ cat docker-compose.yml 
version: '3.8'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "/home/pi/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    depends_on:
      - mqtt
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      #- ./data:/app/data
      - /home/pi/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    #devices:
      # Make sure this matched your adapter location
      #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
      #- /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0

  node-red:
    image: "nodered/node-red:latest"
    restart: unless-stopped
    container_name: node-red
    ports:
      - "161:161/udp"
      - "162:162/udp"
      - "1880:1880/tcp"
    volumes:
      - /home/pi/node-red-data:/data

```

disconnect the ethernet POE adapter (cause this docker image lose connection to coordinator)

### Zigbee2MQTT version

 1.33.2 commit: 9996c93

### Adapter firmware version

20230507

### Adapter

POE ethernet from HamGeek
