### ISSUE TITLE
Zigbee.herdsman connection error to SONOFF Dongle Plus

### ISSUE THREAD

**Issue by VinvarLaLece** [Koenkk/zigbee2mqtt#20472]
### What happened?

Hi all,

I have troubles getting my SONOFF ZIGBEE 3.0 USB DONGLE PLUS to work. I tried using the containerized version (preferred solution) and by installing it in Linux. For both I followed the [official installation guide](https://www.zigbee2mqtt.io/guide/installation/). I both cases Zigbee.herdsman errors out while starting due to a failure to connect.

### What did you expect to happen?

The installation to succeed. I wonder what I am doing wrong. Would you be able to help, please?

### How to reproduce it (minimal and precise)

The Dongle is connected via a 1,5m extension cord to an INTEL NUC running proxmox 8 (kernel Linux 6.5.11-4-pve). Proxmox is running a Debian 12 LXC in which I tried installing Z2M via Docker and directly on the 'container bare' metal. I tried both installing while plugged into an USB 3 and an USB 2 port. Both give me the same errors (see debug log below).
Eclipse Mosquitto and Docker are the only other applications running in the LXC.

**Preparing the Dongle**
- Flashed it with ncp-uart-sw_6.10.3_115200.gbl & nvm3_initfile.gbl [download here](https://github.com/xsp1989/zigbeeFirmware/tree/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP) and following this [YouTube video](https://www.youtube.com/watch?v=BU9ha0Uaduc).

**Preparing the host (Proxmox)**
- I created a group to pass permissions: `groupadd -g 100000 lxc-root`
- I created a user to pass permissions: `useradd -u 100000 lxc-root -g lxc-root`
- I added a udev file `SUBSYSTEMS=="usb", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d4", OWNER="lxc-root", GROUP="lxc-root", SYMLINK="ttyACM0"`. I verified the attributes via lsusb.
- I added to the lxc/100.conf: _(USB3=0 as the Dongle is plugged into a USB 2 port currently.)_
```
usb0: host=1a86:55d4,usb3=0
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/ttyACM0  dev/ttyACM0  none bind,optional,create=file

```
- Rebooted the system.

**In the LXC (Debian 12/bookworm)**
- Verified `/dev/ttyACM0` was connected (`ls -l /dev` -> `crw-rw---- root root 189, 4 Jan 1 15:12 ttyACM01`)
- (Tried both with and without) Made sure current user with which I ran the installation was the owner: `sudo chown lxc-admin:lxc-admin /dev/ttyACM0`
- `test -w /dev/ttyACM0 && echo success || echo failure` resulted in 'success'
- Created the configuration: _Below is the Linux install. For Docker attempt I used the same config. Pan_id and network_key are generated by Z2M._
```
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://retracted_as_is_secret:8883
  user: retracted_as_is_secret
  password: retracted_as_is_secret
  ca: '/etc/ssl/ca.crt'
  key: '/etc/ssl/mqtt-client.key'
  cert: '/etc/ssl/mqtt-client.crt'
serial:
  port: /dev/ttyACM0
  adapter: ezsp
advanced:
  log_level: debug
  pan_id: 13020
  network_key:
    - 15
    - 108
    - 96
    - 197
    - 163
    - 66
    - 253
    - 64
    - 158
    - 233
    - 147
    - 102
    - 85
    - 77
    - 49
    - 154
  channel: 20
```

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

sw_6.10.3_115200

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

```
debug 2024-01-01 14:52:54: Loaded state from file /opt/zigbee2mqtt/data/state.json
info  2024-01-01 14:52:54: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-01-01.14-52-54' filename: log.txt
info  2024-01-01 14:52:54: Starting Zigbee2MQTT version 1.35.0 (commit #3d8f0fc)
info  2024-01-01 14:52:54: Starting zigbee-herdsman (0.30.0)
debug 2024-01-01 14:52:54: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/dat>
error 2024-01-01 14:53:14: Error while starting zigbee-herdsman
error 2024-01-01 14:53:14: Failed to start zigbee
error 2024-01-01 14:53:14: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-01-01 14:53:14: Exiting...
error 2024-01-01 14:53:15: Error: Failure to connect
    at Ezsp.connect (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:277:19)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:139:9)
    at EZSPAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:60:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

**Comment by VinvarLaLece** [comment]
Today I tried it on an VM so I could use the `/dev/serial/by-id`. Same result unfortunately.

Config: _disable_led & rtscts: I tried them without, with one and with both._ 
```
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://retracted_as_is_secret:8883
  user: retracted_as_is_secret
  password: retracted_as_is_secret
  ca: '/etc/ssl/ca.crt'
  key: '/etc/ssl/mqtt-client.key'
  cert: '/etc/ssl/mqtt-client.crt'
serial:
  port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230508165132-if00
  adapter: ezsp
  disable_led: true
  rtscts: false
advanced:
  log_level: debug
```

Error log
```
> zigbee2mqtt@1.35.0 start
> node index.js

Zigbee2MQTT:debug 2024-01-02 16:35:12: Can't load state from file /opt/zigbee2mqtt/data/state.json (doesn't exist)
Zigbee2MQTT:info  2024-01-02 16:35:12: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-01-02.16-35-12' filename: log.txt
Zigbee2MQTT:info  2024-01-02 16:35:12: Starting Zigbee2MQTT version 1.35.0 (commit #3d8f0fc)
Zigbee2MQTT:info  2024-01-02 16:35:12: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:debug 2024-01-02 16:35:12: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":true},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230508165132-if00","rtscts":false}}'
Zigbee2MQTT:error 2024-01-02 16:35:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-02 16:35:32: Failed to start zigbee
Zigbee2MQTT:error 2024-01-02 16:35:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-02 16:35:32: Exiting...
Zigbee2MQTT:error 2024-01-02 16:35:32: Error: Failure to connect
    at Ezsp.connect (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:277:19)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:139:9)
    at EZSPAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:60:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```
