### ISSUE TITLE
Error while starting zigbee-shepherd - docker version 1.6.0

### ISSUE THREAD

**Issue by hajo62** [Koenkk/zigbee2mqtt#2047]
I made an update of my docker install to **1.6.0** as described on your pages. Im running a RPi 3B+ with Raspbian GNU/Linux 9 and docker 18.09.0.
When I now start zigbee2mqtt, I see the following error message. 
I do see sensor-value in my homeassistant:

```
$ docker-compose up zigbee2mqtt
mosquitto is up-to-date
Starting zigbee2mqtt ... done
Attaching to zigbee2mqtt
zigbee2mqtt      | Using '/app/data' as data directory
zigbee2mqtt      | 
zigbee2mqtt      | > zigbee2mqtt@1.6.0 start /app
zigbee2mqtt      | > node index.js
zigbee2mqtt      | 
zigbee2mqtt      |   zigbee2mqtt:info 9/28/2019, 1:23:43 PM Logging to directory: '/app/data/log/2019-09-28.13-23-42'
zigbee2mqtt      |   zigbee2mqtt:info 9/28/2019, 1:23:43 PM Starting zigbee2mqtt version 1.6.0 (commit #e26ad2a)
zigbee2mqtt      |   zigbee2mqtt:info 9/28/2019, 1:23:43 PM Starting zigbee-shepherd
zigbee2mqtt      |   zigbee2mqtt:info 9/28/2019, 1:23:56 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: SRSP - SYS - osalNvRead after 6000ms)
zigbee2mqtt      |   zigbee2mqtt:info 9/28/2019, 1:24:56 PM Starting zigbee-shepherd
zigbee2mqtt      |   zigbee2mqtt:error 9/28/2019, 1:25:09 PM Error while starting zigbee-shepherd! (Error: SRSP - SYS - osalNvRead after 6000ms)
zigbee2mqtt      |   zigbee2mqtt:error 9/28/2019, 1:25:09 PM Press the reset button on the stick (the one closest to the USB) and start again
zigbee2mqtt      |   zigbee2mqtt:error 9/28/2019, 1:25:09 PM Failed to start
zigbee2mqtt      | 	{"message":"SRSP - SYS - osalNvRead after 6000ms","stack":"Error: SRSP - SYS - osalNvRead after 6000ms\n    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/znp/znp.js:227:24)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
zigbee2mqtt      |   zigbee2mqtt:error 9/28/2019, 1:25:09 PM Exiting...
zigbee2mqtt      | npm ERR! code ELIFECYCLE
zigbee2mqtt      | npm ERR! errno 1
zigbee2mqtt      | npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
zigbee2mqtt      | npm ERR! Exit status 1
zigbee2mqtt      | npm ERR! 
zigbee2mqtt      | npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
zigbee2mqtt      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
zigbee2mqtt      | 
zigbee2mqtt      | npm ERR! A complete log of this run can be found in:
zigbee2mqtt      | npm ERR!     /root/.npm/_logs/2019-09-28T13_25_09_917Z-debug.log
```

The container restarts every minute...
Here my docker-compose.yaml:
```
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt:arm32v6
      depends_on:
        - mqtt
      volumes:
        - ./data:/app/data
      devices:
        # CC251
        #- /dev/ttyUSB_cc2531:/dev/ttyACM0
        - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193648CA-if00
        # CC2530 / GBAN GB2530S
        #- /dev/ttyUSB_cc2530:/dev/ttyACM0
      restart: unless-stopped 
      network_mode: host
```
