### ISSUE TITLE
Can't create a group by adding it to the .yaml config

### ISSUE THREAD

**Issue by EmJay276** [Koenkk/zigbee2mqtt#20620]
### What happened?

I wanted to create a group using the groups.yaml file

```
'15':
  friendly_name: Licht Küche
  transition: 1
  devices:
    - 0x0017880108b46997/11
    - 0x00178801061c645a/11
    - 0x00178801061e8271/11
    - 0x00178801093c46e9/11
    - 0x00124b0026b6cc8f/1
```

After a restart of the plugin, the group won't show up in the UI and won't get created as entity in HA.
It also won't add the devices specified to the group.

In the UI I also can't create a group with this name, because the friendly name is already in use
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/8619525/6cbece77-db72-4f4c-829f-b5581eef2f1b)

### What did you expect to happen?

Creating groups from the yaml should create the group in the UI, add the devices and create the HA entity/device

### How to reproduce it (minimal and precise)

Add a group manually to the groups.yaml file

```
'15':
  friendly_name: Licht Küche
  transition: 1
  devices:
    - 0x0017880108b46997/11
    - 0x00178801061c645a/11
    - 0x00178801061e8271/11
    - 0x00178801093c46e9/11
    - 0x00124b0026b6cc8f/1
```

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2
