### ISSUE TITLE
Scene Support

### ISSUE THREAD

**Issue by sti0** [Koenkk/zigbee2mqtt#2069]
As mentioned in #764 it would be nice if zigbee2mqtt supports scenes like the Hue bridge.

Scene support should solve the problem that bulbs in a room won't turn on together if they are not in a group (you have to call them one-by-one). When they are in a group it's only possible to set one color for all bulbs. Scene support allows to set different colors to different bulbs and they turn on immediately together if the scene is called.

There are different ways to achieve a solution.

Some points to discuss:

- How to define a scene?

1. Define a scene within a JSON payload and call it (store the scene information outside of zigbee2mqtt)
2. Define a scene in a scenes.yaml in the config folder. (store scene information inside zigbee2mqtt and call it just by a name or id)

- Must scenes belong to a group?

- Will scenes affect lights only?

- How to change a scene?

There are many other points to clarify. This is only a starting point. Other thoughts und ideas are welcome.

**Comment by sti0** [comment]
### Some proposals:

### Defining a scene

Setting a scene via MQTT could be done by a JSON payload inspired by the z2m color setting
```
{
    "sceneName": "Some Scene",
    "devices": {
        "friendly_name1": {
            "brightness": 255,
            "color_temp": 155,
            "color": {
              "x": 0.123,
              "y": 0.123
            }
        },
        "friendly_name2": {
            "brightness": 255,
            "color_temp": 155,
            "color": {
                "r": 46,
                "g": 102,
                "b": 193
            }
        },
        "friendly_name3": {
            "brightness": 255,
            "color_temp": 155,
            "color": {
                "hex": "#547CFF"
            }
        },
        "friendly_name4": {
            "brightness": 255,
            "color_temp": 155,
            "color": {
                "hue": 360,
                "saturation": 100
            }
        }
    },
    "transition": 2
}
```
### Storing a scene
This would be stored in a scenes.yaml
```
sceneName: Some Scene
devices:
  friendly_name1:
    brightness: 255
    color_temp: 155
    color:
      x: 0.123
      y: 0.123
  friendly_name2:
    brightness: 255
    color_temp: 155
    color:
      r: 46
      g: 102
      b: 193
  friendly_name3:
    brightness: 255
    color_temp: 155
    color:
      hex: "#547CFF"
  friendly_name4:
    brightness: 255
    color_temp: 155
    color:
      hue: 360
      saturation: 100
transition: 2
```

### Topics:

- Add a Scene  zigbee2mqtt/bridge/config/add_scene
- Remove a Scene zigbee2mqtt/bridge/config/remove_scene
- Activating a Scene zigbee2mqtt/[Scene_Name]/set

### Others
- Scenes can be overwritten. If an existing scene is added again, it will be remove first and added again
- Scenes don't belong to a group (see next point)
- Scenes could can be expanded for other devices like switches later
- Maybe a STATE attribute makes sense to turn off specific lights (or later turn on/off switches). This should be discussed. On my above proposal a state setting to "ON" is implicit.
