### ISSUE TITLE
 Error: network commissioning timed out

### ISSUE THREAD

**Issue by BinaryShrub** [Koenkk/zigbee2mqtt#20804]
### What happened?

configuration.yml which has fields generate as expected:
```
homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: GENERATE
  ext_pan_id: GENERATE
  network_key: GENERATE
```

But I get this error when starting.

```
Zigbee2MQTT:error 2024-01-14 20:33:36: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```

### What did you expect to happen?

I expect the server to start

### How to reproduce it (minimal and precise)

Reflash successfully:
```
docker run --rm --device /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f4219e725586ec11bb41e33719c2d21c-if00-port0:/dev/ttyUSB0 -e \
FIRMWARE_URL=https://github.com/Koenkk/Z-Stack-firmware/raw/Z-Stack_3.x.0_coordinator_20230507/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20230507.zip \
ckware/ti-cc-tool -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb
```

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Docker
