### ISSUE TITLE
Error: 2024-01-27 07:32:36Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()

### ISSUE THREAD

**Issue by Burki24** [Koenkk/zigbee2mqtt#21037]
### What happened?

When I set 'Measurement poll interval' on device '_TZ3000_rdtixbnu' ([TS0121_plug](https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121_plug)), I get this error-log: Error 2024-01-27 07:32:36Failed to apply calibration to 'power': 'power_calibration' is not a number, got string (). But I didn't change calibration for power.

After setting 'poll interval' this error message persists and pop up every minute, until I change the parameter 'calibration for power' to '0'.

### What did you expect to happen?

Change the poll interval only, not changing anything other without getting that error message.

### How to reproduce it (minimal and precise)

On every plug-device with powermeassurement, if there were manually changes in settings(specific). Tested on tuya-devices. 

### Zigbee2MQTT version

1.35.1-dev commit: a879382c

### Adapter firmware version

EZSP V8 - 7.0.2.0 build 406

### Adapter

sonoff-zigbee-3-0-usb-dongle-plus-e

### Setup

plain on Pi

### Debug log

Error 2024-01-27 09:02:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:03:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:04:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:06:15Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:06:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:07:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:08:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:09:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:10:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:11:42Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:12:43Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:13:43Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:14:43Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Error 2024-01-27 09:15:43Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()
Info 2024-01-27 09:15:43MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"b8w1a-6"}'
Debug 2024-01-27 09:15:44Received Zigbee message from 'Wohnzimmer/Sicherheit/Wohnbereich/Radar', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,2,223],"type":"Buffer"},"datatype":2,"dp":9}],"seq":20992}' from endpoint 1 with groupID 0
Info 2024-01-27 09:15:44MQTT publish: topic 'zigbee2mqtt/Wohnzimmer/Sicherheit/Wohnbereich/Radar', payload '{"illuminance_lux":15,"last_seen":1706343343992,"linkquality":212,"target_distance":7.35}'
Debug 2024-01-27 09:15:44Received Zigbee message from 'Buero/Sicherheit/Radar', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,186],"type":"Buffer"},"datatype":2,"dp":9}],"seq":33024}' from endpoint 1 with groupID 0
Info 2024-01-27 09:15:44MQTT publish: topic 'zigbee2mqtt/Buero/Sicherheit/Radar', payload '{"cli":" ","detection_delay":0,"fading_time":20,"illuminance_lux":24,"last_seen":1706343344460,"linkquality":164,"maximum_range":3,"minimum_range":0.3,"presence":true,"radar_sensitivity":8,"self_test":"check_success","target_distance":1.86}'
Debug 2024-01-27 09:15:45Received Zigbee message from 'Wohnzimmer/Sicherheit/Wohnbereich/Radar', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,2,211],"type":"Buffer"},"datatype":2,"dp":9}],"seq":21248}' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
What is the `power_calibration` value in your `configuration.yaml`?

**Comment by Burki24** [comment]
Didn't changed it. So it is not used. the calibration I never changed. It isn't inside configuration.yaml and also not in devices.yaml.

**Comment by Burki24** [comment]
@Koenkk 
Same Issue with https://www.zigbee2mqtt.io/devices/SP_240.html.

Zigbee2MQTT V. 1.35.1-dev commit: [0b59a51c](https://github.com/Koenkk/zigbee2mqtt/commit/0b59a51c)
Coordinator-Typ EZSP v8
Coordinator-Version 7.0.2.0 build 406
Coordinator IEEE Adresse 0xe0798dfffebbe7d6
Frontend-Version 0.6.152
Zigbee-herdsman-converters version 18.25.1
Zigbee-herdsman version 0.33.5

Debug:

```
Info 2024-02-01 16:29:40MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"action":"on","current":0,"energy":0,"linkquality":248,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
Info 2024-02-01 16:29:41MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"current":0,"energy":0,"linkquality":255,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
Error 2024-02-01 16:29:41Failed to apply calibration to 'power': 'power_precision' is not a number, got string ()
Info 2024-02-01 16:29:41MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"current":0,"energy":0,"linkquality":248,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
Error 2024-02-01 16:29:42Failed to apply calibration to 'voltage': 'voltage_precision' is not a number, got string ()
Info 2024-02-01 16:29:42MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"current":0,"energy":0,"linkquality":248,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
Error 2024-02-01 16:29:43Failed to apply calibration to 'current': 'current_precision' is not a number, got string ()
Info 2024-02-01 16:29:43MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"current":0,"energy":0,"linkquality":252,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
Error 2024-02-01 16:29:44Failed to apply calibration to 'energy': 'energy_calibration' is not a number, got string ()
Info 2024-02-01 16:29:44MQTT publish: topic 'zigbee2mqtt/0xa4c138a71702a8fe', payload '{"current":0,"energy":0,"linkquality":252,"power":0,"power_on_behavior":"previous","state":"ON","voltage":227}'
```
![image](https://github.com/Koenkk/zigbee2mqtt/assets/20765982/5b5db465-5d6c-4574-a844-7a23fb3ac262)


configuration.yaml:
```

homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1024
serial:
  port: /dev/ttyACM0
advanced:
  network_key:
    - 102
    - 17
    - 175
    - 4
    - 116
    - 126
    - 187
    - 75
    - 13
    - 76
    - 110
    - 54
    - 65
    - 56
    - 49
    - 58
  pan_id: 55083
  ext_pan_id:
    - 236
    - 84
    - 200
    - 65
    - 99
    - 19
    - 48
    - 171
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c13855e2d4363a':
    friendly_name: '0xa4c13855e2d4363a'
  '0xa4c138e3ebf058b7':
    friendly_name: '0xa4c138e3ebf058b7'
  '0x38398ffffeecaf95':
    friendly_name: '0x38398ffffeecaf95'
  '0xa4c138dafc377c8f':
    friendly_name: '0xa4c138dafc377c8f'
    color_sync: true
  '0xa4c138a71702a8fe':
    friendly_name: '0xa4c138a71702a8fe'
    energy_calibration: ''
    power_precision: ''
    voltage_precision: ''
    current_precision: ''
    energy_precision: ''
    state_action: true
```
