### ISSUE TITLE
No converter available

### ISSUE THREAD

**Issue by jwillmer** [Koenkk/zigbee2mqtt#21333]
### What happened?

I get the `No converter available` error for a payload that is described in the device specs of zigbee2mqtt.

### What did you expect to happen?

I can send this payload to the device.

### How to reproduce it (minimal and precise)

I used Home Assistant to call `zigbee2mqtt/living_room/set` with payload `{"show_smiley": "HIDE"}` as described in the [zigbee2mqtt device specs](https://www.zigbee2mqtt.io/devices/LYWSD03MMC.html#show-smiley-binary). But I get the error `No converter available`.

Home assistant call:
```
service: mqtt.publish
data:
  payload: '{"show_smiley": "HIDE"}'
  topic: zigbee2mqtt/living_room/set
```

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20221226

### Adapter

SLZB-06

### Setup

Docker
