### ISSUE TITLE
Missing zigbeeModel for Philips Hue Adore lights (2 spots), model: '3417931P6'

### ISSUE THREAD

**Issue by AlexL00** [Koenkk/zigbee2mqtt#21418]
### What happened?

I have added a new Philips Hue Adore Lamp with 2 spots. This device is supported according to the [device list](https://www.zigbee2mqtt.io/devices/3417931P6.html), see also [vendors product page](https://www.philips-hue.com/de-de/p/hue-white-ambiance-adore-badezimmer-spot-weiss-+-dimmschalter/8719514340879).

I have found that the two spots are recognized as the following devices/models:
- 929003056201_01
- 929003056201_02

In the zigbee-herdsman-converter, the device is currently defined as follows:
```yaml
{
zigbeeModel: ['3417931P6', '929003056201'],
model: '3417931P6',
vendor: 'Philips',
description: 'Hue white ambiance Adore GU10 with Bluetooth (2 spots)',
extend: [philipsLight({colorTemp: {range: [153, 454]}})],
}
```
**As a result, the devices are currently not recognized as supported devices.**

### What did you expect to happen?

In my opinion, the definition needs to be adjusted as follows:
```yaml
{
    zigbeeModel: ['3417931P6', '929003056201', '929003056201_01', '929003056201_02'],
    model: '3417931P6',
    vendor: 'Philips',
    description: 'Hue white ambiance Adore GU10 with Bluetooth (2 spots)',
    extend: [philipsLight({colorTemp: {range: [153, 454]}})],
}
```

This adjustment has already been made for the 3418131P6 device (same lamp/design with 3 spots).

### How to reproduce it (minimal and precise)

You need to pair a Philips Hue Adore Lamp with 2 spots to Z2M.

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P (CC2652P)

### Setup

Z2M add-on running on Home assistant on Pi4
