### ISSUE TITLE
Cannot read properties of undefined (reading 'toZigbeeConverters')

### ISSUE THREAD

**Issue by Lovasz-Akos** [Koenkk/zigbee2mqtt#21473]
### What happened?

Freshly installed 1.35.3, zigbee2mqtt no longer starts, complains about custom converters when there are none.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55391231/5814cad4-196b-4b8e-b3ff-1ea8b2a4d795)
my config is 
```yaml
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/serial/by-path/platform-ff5c0000.usb-usb-0:1.3:1.0-port0
  adapter: ezsp
advanced:
  network_key:
    - idk if it's safe to share :)
  pan_id: idk if it's safe to share :)
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x84ba20fffe6abf42':
    friendly_name: '0x84ba20fffe6abf42'
```

### What did you expect to happen?

Zigbee2mqtt starts as usual

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

`Coordinator firmware version: '{"meta":{"maintrel":"8 ","majorrel":"6","minorrel":"7","product":8,"revision":"6.7.8.0 build 373"},"type":"EZSP v8"}'`

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E (ezsp)

### Setup

npm start, on an arm64 machine

### Debug log

$ npm start

> zigbee2mqtt@1.35.3 start
> node index.js

/home/smarthome/zigbee2mqtt/lib/extension/publish.ts:20
    zhc.toZigbee.light_onoff_brightness,
                             ^
TypeError: Cannot read properties of undefined (reading 'toZigbeeConverters')
    at Object.<anonymous> (/home/smarthome/zigbee2mqtt/lib/extension/publish.ts:20:30)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/smarthome/zigbee2mqtt/lib/controller.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
