### ISSUE TITLE
Docker latest-dev: error starting when USB device is not named /dev/ttyACM(0,1)

### ISSUE THREAD

**Issue by airdrummingfool** [Koenkk/zigbee2mqtt#2157]
I'm using Docker to run the dev version of zigbee2mqtt. I pulled the latest version a couple hours ago, and as soon as I did, z2m stopped starting, and would instead throw the following error:
```
zigbee2mqtt_1    | Using '/app/data' as data directory
zigbee2mqtt_1    |
zigbee2mqtt_1    | > zigbee2mqtt@1.6.0 start /app
zigbee2mqtt_1    | > node index.js
zigbee2mqtt_1    |
zigbee2mqtt_1    | zigbee2mqtt:info  2019-10-18T10:17:09: Logging to directory: '/app/data/log/2019-10-18.10-17-08'
zigbee2mqtt_1    | zigbee2mqtt:debug 2019-10-18T10:17:09: Removing old log directory '/app/data/log/2019-10-18.09-18-14'
zigbee2mqtt_1    | zigbee2mqtt:debug 2019-10-18T10:17:09: Loaded state from file /app/data/state.json
zigbee2mqtt_1    | zigbee2mqtt:info  2019-10-18T10:17:09: Starting zigbee2mqtt version 1.6.0 (commit #f219e5d)
zigbee2mqtt_1    | zigbee2mqtt:info  2019-10-18T10:17:09: Starting zigbee-herdsman...
zigbee2mqtt_1    | zigbee2mqtt:debug 2019-10-18T10:17:09: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extenedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/app/data/database.db","backupPath":"/app/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/zigbee"}}'
zigbee2mqtt_1    | zigbee2mqtt:error 2019-10-18T10:17:09: Error while starting zigbee-herdsman
zigbee2mqtt_1    | zigbee2mqtt:error 2019-10-18T10:17:09: Failed to start zigbee
zigbee2mqtt_1    | zigbee2mqtt:error 2019-10-18T10:17:09: Exiting...
zigbee2mqtt_1    | zigbee2mqtt:error 2019-10-18T10:17:09: Error: Path '/dev/zigbee' does not exist
zigbee2mqtt_1    |     at Object.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js:31:19)
zigbee2mqtt_1    |     at Generator.next (<anonymous>)
zigbee2mqtt_1    |     at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js:5:58)
zigbee2mqtt_1    |     at process._tickCallback (internal/process/next_tick.js:68:7)
zigbee2mqtt_1    | npm ERR! code ELIFECYCLE
zigbee2mqtt_1    | npm ERR! errno 1
zigbee2mqtt_1    | npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
zigbee2mqtt_1    | npm ERR! Exit status 1
zigbee2mqtt_1    | npm ERR!
zigbee2mqtt_1    | npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
zigbee2mqtt_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
zigbee2mqtt_1    |
zigbee2mqtt_1    | npm ERR! A complete log of this run can be found in:
zigbee2mqtt_1    | npm ERR!     /root/.npm/_logs/2019-10-18T10_17_09_288Z-debug.log
```
Note that I had not touched my `docker-compose.yaml` or `zigbee2mqtt/configuration.yaml` file since the previous version had started successfully.

Here's my original configuration (that no longer works):
docker-compose.yaml
```yaml
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00015A7695-if00:/dev/zigbee
[...]
```

zigbee2mqtt configuration.yaml:
```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt'
serial:
  port: /dev/zigbee
```

After lots of trial and error, I found that I could get zigbee2mqtt working again if I used `/dev/ttyACM0` or `/dev/ttyACM1` instead of `/dev/zigbee`. However, other similar device names do not work; so far I've tried `/dev/ttyACM2` and `/dev/ttyACM11` - neither works.

**The only thing I have to do to fix the problem is change the name of the device in both `configuration.yaml` and `docker-compose.yaml`**.

Here's my configuration that works now:
docker-compose.yaml
```yaml
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00015A7695-if00:/dev/ttyACM0
[...]
```

zigbee2mqtt configuration.yaml
```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt'
serial:
  port: /dev/ttyACM0
```
