### ISSUE TITLE
Exposing switch as a light doesn't retain the original Friendly Name

### ISSUE THREAD

**Issue by Skaronator** [Koenkk/zigbee2mqtt#22034]
### What happened?

I'm trying to expose a switch as a light according [to the official documentation](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light) but the resulting entry name looks broken:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2886913/5e64d2e7-3e40-4b10-8ede-27a71e53e9dd)

The entity name is correct, only the display name is wrong:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2886913/6147cb27-c28f-4268-8e60-b24b4cbdc948)

### What did you expect to happen?

I'd expect that the `friendly_name` would be used for this entry and not "MQTT LightEntitry"

### How to reproduce it (minimal and precise)

My config looks like this:
```yaml
  '0x54ef4410008bec76':
    friendly_name: Abstellkammer Lichtschalter
    homeassistant:
      switch:                                                                                                                                                                                         type: light
        object_id: light
      light:
        name: null
        value_template: null
        state_value_template: '{{ value_json.state }}'
```

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20231030

### Adapter

SLZB-06M

### Setup

Docker (Kubernetes)
