### ISSUE TITLE
Osram Plug unavailable in HA but responding via mqtt messages

### ISSUE THREAD

**Issue by Bruceforce** [Koenkk/zigbee2mqtt#2216]
# Bug Report
## What happened
One of my two osram plugs
```yaml
  '0x7cb03eaa0a00ed53':
    friendly_name: osram_plug_02
```

becomes unavailable in home assistant but it still receives command via mqtt directly. I'm using mosquitto as mqtt server and I'm running everyting inside docker containers.

I already tried re-pairing the device a couple of times.

## What did you expect to happen
The Osram plug shouldn't be unavailable in home assistant since it still seems to process mqtt messages.

## How to reproduce it (minimal and precise)
1. start up zigbee2mqtt docker container
1. wait until osram plug becomes unavaible in home assistant
1. send direct mqtt message `zigbee2mqtt/0x7cb03eaa0a00ed53/set` with payload `{"state": "ON"}` via MQTT.fq

## Debug Info
zigbee2mqtt version: 1.6.0 (commit #e26ad2a)
CC253X firmware version: 20190608

configuration.yaml
```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto:1883'
serial:
  port: /dev/ttyACM0
advanced:
  panid: 6754
  channel: 25
  network_key: [...]
  log_level: warn
  report: true
  availability_timeout: 300
groups:
  [...]
devices:
  [...]
```

Debug logs are here: https://gist.github.com/Bruceforce/c91af88522876fc3bd32e237062395a0
database.db https://gist.github.com/Bruceforce/947149ab2b8d7147e00ab1138ed5f7cb
