### ISSUE TITLE
[Feature request]:  Ability to change the domain of a switch to outlet and others

### ISSUE THREAD

**Issue by walberjunior** [Koenkk/zigbee2mqtt#22423]
### Is your feature request related to a problem? Please describe

I would like to be able to change the domain of an entity, for example from switch to outlet. 
Apparently this feature only works for "light". 
I know it is possible to change in HA with the "show as" option, but this option does not change the domain, it only changes the way the switch will be shown on the dashboard.

### Describe the solution you'd like

```
  '0xa4c138b930822295':
    friendly_name: 'Tomada'
    homeassistant:
      switch:
        type: outlet
        object_id: outlet
      outlet:
        name: Tomada
        value_template: null
        state_value_template: '{{ value_json.state }}'
        ```

### Describe alternatives you've considered

none

### Additional context

none
