### ISSUE TITLE
SNZB-06P Failed to configure on Z2M 1.37.0

### ISSUE THREAD

**Issue by idogrf** [Koenkk/zigbee2mqtt#22486]
### What happened?

Trying to configure the SNZB-06P presence sensor on Zigbee2MQTT version 1.37.0 fails with the following error - 
```
attempt 2 (TypeError: func is not a function at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

Reverting to Z2M 1.35.1 seems to solve the issue (haven't tried 1.36.0)

### How to reproduce it (minimal and precise)

Try to pair the device with Z2M

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

1.0.6

### Adapter

SNZB-06P

### Setup

Dockerized Z2M on a raspberry pi

**Comment by darkfuncat** [comment]
Hi, new to zigbee.
I have just one coordinator sonoff dongle-e, recently flashed (>7.4) and have the same problem than you.

**Comment by darkfuncat** [comment]
Update : just tried 1.36.1 and there is no bug.

**Comment by Koenkk** [comment]
Could it be that you are using an external converter for this device? (check your `configuration.yaml`)

**Comment by idogrf** [comment]
I don't think I'm using an external converted either.
This is my configuration.yaml - 

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.XXX:XXX
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:
    - ...
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: debug
device_options:
  legacy: false
devices:
  '0x00158d0007005864':
    friendly_name: contact_sensor_1
  '0x00158d000775300c':
    friendly_name: motion_sensor
    occupancy_timeout: 90
    no_occupancy_since: []
  '0x04cf8cdf3c7c6b7a':
    friendly_name: single_switch
  '0x0ceff6fffe3b0481':
    friendly_name: presence_sensor_1
frontend:
  port: 8011
availability: false
```

where device `0x0ceff6fffe3b0481` is the problematic one
