### ISSUE TITLE
Zigbee2Mqtt  1.37.0 & 1.37.1 : Lost of device link and Device IEE Change after reparing

### ISSUE THREAD

**Issue by jmorille** [Koenkk/zigbee2mqtt#22741]
### What happened?

After Update to version 1.37.1 with docker version, 
- all zigbee device change there Adresse IEEE
- and many error in logs appear 
1. error:  `	zh:zigate:driver: Parsing error: Error: Message '8008' not found`
2. error: 	 `source endpoint 242, not supported`	

After repairing all device for the new   Adresse IEEE the schema map become without any link anymore
![image](https://github.com/Koenkk/zigbee2mqtt/assets/538320/5fe11fe9-c150-4adb-81a0-215ab1a7f859)

I try to the latest dev version with docker tag latest-dev and the error persist

### What did you expect to happen?

No error in IHM like
1. error:  `	zh:zigate:driver: Parsing error: Error: Message '8008' not found`
2. error: 	 `source endpoint 242, not supported`	

A Map Schema with link 

### How to reproduce it (minimal and precise)

My adapter is a `Zigate+ V2 USB` with the following config
```yaml
serial:
  port: /dev/serial/by-id/usb-FTDI_ZiGate_ZIGATE+-if00-port0
  adapter: zigate
  baudrate: 115200
  disable_led: true
  rtscts: true
```

### Zigbee2MQTT version

1.37.1-dev commit: b2d3265

### Adapter firmware version

ZiGateV2 v3.A0

### Adapter

Zigate+ V2 USB

### Setup

Zigbee2MQTT in docker with x86-64 with N100 CPU

### Debug log

[_zigbee2mqtt_logs.txt](https://github.com/Koenkk/zigbee2mqtt/files/15407754/_zigbee2mqtt_logs.txt)
