### ISSUE TITLE
zh:ember: Delivery of BROADCAST failed for "65533" on fw 7.4.1, 7.4.2, and 7.43 

### ISSUE THREAD

**Issue by lennon101** [Koenkk/zigbee2mqtt#22816]
### What happened?

- Journal of steps
	- upgraded zigbee2mqtt to 1.37
	- received the `zh:ezsp: Deprecated driver 'ezsp' currently in use, 'ember' will become the officially supported EmberZNet driver in next release. If using Zigbee2MQTT see https://github.com/Koenkk/zigbee2mqtt/discussions/21462`
	- changed adapter: ezsp to adapter: ember and restarted
	- got an error that my coordinator was not on EZSP
	- upgraded my coordinator firmware to FW ncp-uart-hw-v7.4.2.0-zbdonglee-230400
		- using the steps outlined here: https://github.com/Koenkk/zigbee2mqtt/issues/22398#issuecomment-2094674395
		- link to fw files here: https://github.com/darkxst/silabs-firmware-builder/tree/4.4.3/firmware_builds/zbdonglee
	- changed config in zigbee2mqtt to `adapter: ember` + `rtscts: false`
	- restarted zigbee2mqtt and I can open the webpage but
		- now at startup I get the message `zh:ember: Delivery of BROADCAST failed for "65533" `
		- the coordinator can only find the non-router devices
		- all powered devices are missing from the network map
		- switching back to `adapter: ezsp` doesn't work either as I then get the error `zh:controller:greenpower: Received undefined command from '0'`.
	- Found this closed issue saying reporting exactly the same issue saying that 7.4.2 was the problem:
		- https://github.com/Koenkk/zigbee2mqtt/issues/22469
	- Downgraded zigbee coordinator fw to 7.4.1
		- using: `universal-silabs-flasher --device /dev/ttyACM0 flash --firmware ncp-uart-hw-v7.4.1.0-zbdonglee-115200.gbl --force`
	- got the same error as before: `zh:ember: Delivery of BROADCAST failed for "65533" `
	- upgraded zigbee coordinator fw to 7.4.3 using: `universal-silabs-flasher --device /dev/ttyACM0 flash --firmware ncp-uart-hw-v7.4.3.0-zbdonglee-115200.gbl --force`
	- got the same error as before: `zh:ember: Delivery of BROADCAST failed for "65533" `

zigbee2mqtt docker compose: 

```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.37.1
    restart: unless-stopped
    volumes:
      - /home/<usernam>/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8089:8080
    environment:
      - TZ=Australia/Brisbane
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220095219-if00:/dev/ttyACM0
    group_add:
      - dialout
    user: hidden:hidden
    privileged: 'true'

```

zigbee2mqtt configuration.yaml

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://hidden ip and port
  user: hidden
  password: hidden
serial:
  port: /dev/ttyACM0
  adapter: ember
  baudrate: 115200
  rtscts: false
frontend: true
availability: true
devices:
  <removed but you get the idea>
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
  log_level: error

```

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

ncp-uart-hw-v7.4.3.0-zbdonglee-115200

### Adapter

zbdongle-e

### Setup

docker container

### Debug log

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15477318/log.log)
