### ISSUE TITLE
HA discovery configuration dropped when value is null

### ISSUE THREAD

**Issue by ghoz** [Koenkk/zigbee2mqtt#22976]
### What happened?

I have customized some home assistant  discovery for specific entities to override the default category from diagnostic to regular sensor.
 In order to do that I'm overriding the specific ``entity_category`` for the entities in my devices.yaml file, and it works:

``` yaml
'0xieeeAddr':
  friendly_name: Smart_plug
  description: chatty Nous A1Z
  [...]
  homeassistant:
    power:
      entity_category: null
    current:
      entity_category: null
    voltage:
      entity_category: null
```

However, when making any change using the UI, all ``entity_category: null`` are removed.

``` yaml
'0xieeeAddr':
  friendly_name: Smart_plug
  description: chatty Nous A1Z
  [...]
  homeassistant:
    power: {}
    current: {}
    voltage: {}
```

This might be tied to https://github.com/Koenkk/zigbee2mqtt/pull/22674 
I haven't tested if it also occurs in the main configuration file under ``homeassistant`` key

note: It is kind of hidden as z2m no longer sends the discovery payload if already sent since https://github.com/Koenkk/zigbee2mqtt/pull/22701 ,  so home assistant won't see the change unless the retained discovery topics are cleared first (https://github.com/Koenkk/zigbee2mqtt/issues/22977).

### What did you expect to happen?

I expected that my configuration would keep my settings.

### How to reproduce it (minimal and precise)

1. add a custom home assistant entry in a device  configuration with a value of ``null``  
2. change a setting in the UI
3. see that the config was changed and the entry removed

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20230507

### Adapter

Sonoff ZBDongle-P

### Setup

container on pi3
