### ISSUE TITLE
SLZB-06

### ISSUE THREAD

**Issue by ALPF5555** [Koenkk/zigbee2mqtt#23177]
### What happened?

When I try to change the config file to allow the new coordinator to be the coordinator for the Z2M I type in tcp://192.168.1.186:6638 and then  when I try to start Z2M it fails and resets the config file back to the USB port in the default setup. I have tried many times and it always goes back to the default settings including going back to localhost.
I am using Bookworm 64 bit on a Raspberry Pi 4 with 8GB ram and a 480 GB NVME drive. 

### What did you expect to happen?

I would have expected the configuration file to stay changed after I have saved it using ctrl X then Y and enter but when Z2M fails to start everything is back to the default settings. 
I have tried changing and saving the localhost to 192.168.1.10:1883 as that is the location of my Raspberry Pi and the serial port to tcp but it always resets to the default page below.
I have tried changing the settings one at a time and then starting but upon failure to start it always defaults to the original config. 

 Home Assistant integration (MQTT discovery)
homeassistant: false

# Enable the frontend, runs on port 8080 by default
frontend: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0

# Advanced settings
advanced:
  # Let Zigbee2MQTT generate a network key on first start
  network_key: GENERATE
  # Let Zigbee2MQTT generate a pan_id on first start
  pan_id: GENERATE
  # Let Zigbee2MQTT generate a ext_pan_id on first start
  ext_pan_id: GENERATE

### How to reproduce it (minimal and precise)

all I do is go to the Z2M and look at the config file and see it is not what I had saved. I make the changes and then save it then try to start Z2M but it fails 
Then when I go back and check the config set up I find it has reverted to the default setup.
> zigbee2mqtt@1.38.0 start
> node index.js

[2024-06-27 10:10:41] info:     z2m: Logging to console, file (filename: log.log)
[2024-06-27 10:10:41] info:     z2m: Starting Zigbee2MQTT version 1.38.0 (commit #6c7d52a)
[2024-06-27 10:10:41] info:     z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-27 10:10:41] error:    zh:zstack:znp: Failed to determine if path is valid: 'Error: ENOENT: no such file or directory, lstat '/dev/ttyACM0''
[2024-06-27 10:10:41] info:     zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-06-27 10:10:41] error:    z2m: Error while starting zigbee-herdsman
[2024-06-27 10:10:41] error:    z2m: Failed to start zigbee
[2024-06-27 10:10:41] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-27 10:10:41] error:    z2m: Exiting...
[2024-06-27 10:10:41] error:    z2m: Error: Error: No such file or directory, cannot open /dev/ttyACM0

### Zigbee2MQTT version

1.38

### Adapter firmware version

	0.9.9 (Mar 3 2023)

### Adapter

slzb-06 POE 

### Setup

On Raspberry Pi plain using Bookworm.

**Comment by andyblac** [comment]
I use a `SLZB-06M` with no issues, where are you putting the serial config in the add-on config page or in Z2M confuration.yaml ?, I have then in both to be safe.

**Comment by ALPF5555** [comment]
Hello          I am just putting it into the Config.yaml file. 
Regards 
    On Thursday 27 June 2024 at 10:39:55 BST, Andrew Blackburn ***@***.***> wrote:   

 


I use a SLZB-06M with no issues, where are you putting the serial config in the add-on config page or in Z2M confuration.yaml ?, I have then in both to be safe.

**Comment by ALPF5555** [comment]
I am not using Home Assistant so there is the z2m configuration.yaml file where the changes are normally made.
    On Thursday 27 June 2024 at 10:39:55 BST, Andrew Blackburn ***@***.***> wrote:   

 


I use a SLZB-06M with no issues, where are you putting the serial config in the add-on config page or in Z2M confuration.yaml ?, I have then in both to be safe.

**Comment by andyblac** [comment]
> Hello          I am just putting it into the Config.yaml file.  Regards  On Thursday 27 June 2024 at 10:39:55 BST, Andrew Blackburn ***@***.***> wrote: I use a SLZB-06M with no issues, where are you putting the serial config in the add-on config page or in Z2M confuration.yaml ?, I have then in both to be safe. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

try adding it to the add-on config section as well.

<img width="1112" alt="Screenshot 2024-06-27 at 10 54 06" src="https://github.com/Koenkk/zigbee2mqtt/assets/77936/3f7a831f-3b9b-48d1-a0c4-0237cae196f4">

**Comment by andyblac** [comment]
looking at you log, it trying to open a serial port not a tcp port

```
[2024-06-27 10:10:41] info: zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
```
]can you post your configuration.yaml file ?

**Comment by ALPF5555** [comment]
# Home Assistant integration (MQTT discovery)
homeassistant: false

# Enable the frontend, runs on port 8080 by default
frontend: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: tcp://192.168.1.168:6638

# Advanced settings
advanced:
  # Let Zigbee2MQTT generate a network key on first start
  network_key: GENERATE
  # Let Zigbee2MQTT generate a pan_id on first start
  pan_id: GENERATE
  # Let Zigbee2MQTT generate a ext_pan_id on first start
  ext_pan_id: GENERATE


This is the configuration set up I want to save but every time I save it the changes revert back to the default setting where it is looking for a serial port not a tcp port.

**Comment by andyblac** [comment]
ok try this

```yaml
homeassistant: false
permit_join: false
advanced:
  network_key: GENERATE
  pan_id: GENERATE
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
  transmit_power: 20
  log_level: warning
  channel: 22
frontend:
  port: 8099
device_options:
  legacy: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
mqtt:
  server: mqtt://core-mosquitto:1883
  user: my_user
  password: my_pass
  base_topic: zigbee2mqtt
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: tcp://slzb-06.local:6638
  baudrate: 115200
  adapter: ember
  rtscts: false
```
