### ISSUE TITLE
syslog logging broken in v1.39.0 ("undefined" messages)

### ISSUE THREAD

**Issue by skazi0** [Koenkk/zigbee2mqtt#23241]
### What happened?

After upgrading from v1.38.0 to v1.39.0 my syslog started logging "undefined" instead of messages:
```
lip 02 16:53:50 openhab systemd[1]: Started zigbee2mqtt.service - zigbee2mqtt.
lip 02 16:53:54 openhab npm[2613725]: > zigbee2mqtt@1.39.0 start
lip 02 16:53:54 openhab npm[2613725]: > node index.js
lip 02 16:53:55 openhab npm[2613738]: Starting Zigbee2MQTT without watchdog.
lip 02 16:54:07 openhab Zigbee2MQTT[2613738]: undefined
lip 02 16:54:07 openhab Zigbee2MQTT[2613738]: undefined
lip 02 16:54:07 openhab Zigbee2MQTT[2613738]: undefined
```
in v1.38.0 it looks like this:
```
lip 02 17:05:00 openhab systemd[1]: Started zigbee2mqtt.service - zigbee2mqtt.
lip 02 17:05:04 openhab npm[2615727]: > zigbee2mqtt@1.38.0 start
lip 02 17:05:04 openhab npm[2615727]: > node index.js
lip 02 17:05:17 openhab Zigbee2MQTT[2615805]: z2m: Logging to console (silenced), syslog
lip 02 17:05:17 openhab Zigbee2MQTT[2615805]: z2m: Starting Zigbee2MQTT version 1.38.0 (commit #fe048e6e)
lip 02 17:05:17 openhab Zigbee2MQTT[2615805]: z2m: Starting zigbee-herdsman (0.49.2)
```

### What did you expect to happen?

Logging to syslog still works after upgrade.

### How to reproduce it (minimal and precise)

with following config:
```
frontend:
  port: 8081
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
devices:
(...)
advanced:
  log_output:
    - syslog
  log_syslog:
    path: /dev/log
    protocol: unix
    localhost: ''
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
```
running following commands:
```
$ cd /opt/zigbee2mqtt
$ git checkout 1.39.0 # or git checkout master
$ npm ci --no-audit --no-update-notifier
$ npm run build
$ sudo systemctl restart zigbee2mqtt
$ sudo journalctl -u zigbee2mqtt -f
```

### Zigbee2MQTT version

1.39.0 or current master

### Adapter firmware version

20230507

### Adapter

ZBDongle-P

### Setup

direct git checkout on debian12 VM with USB passthrough
