### ISSUE TITLE
HA Supervisor logs

### ISSUE THREAD

**Issue by Anto79-ops** [Koenkk/zigbee2mqtt#23446]
### What happened?

hello,

Noticed these logs in HA Supervisor (using the Z2M addon on HAOS, SMlite SLZB-06):

```
2024-07-28 23:28:38.998 WARNING (MainThread) [supervisor.addons.options] Unknown option 'disable_led' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-07-28 23:28:38.999 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
```

Core 2024.7.3
Supervisor 2024.07.0
Operating System 12.4

### Zigbee2MQTT version

1.39.0-1

### Adapter firmware version

20240710

### Adapter

SLZB-06

### Setup

Add-on HA, HAOS

**Comment by Anto79-ops** [comment]
addon config:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://192.168.1.234:1883
  user: [redacted]
  password:[redacted]
serial:
  port: tcp://slzb-06.local:6638
  baudrate: 115200
  adapter: zstack
  disable_led: false
advanced:
  transmit_power: 20
  channel: 20
```

**Comment by Anto79-ops** [comment]
it seems if move these two options from the addon-config to the Z2M configuration yaml file, and the supervisor logs stop complaining.

```
  disable_led: false
advanced:
  transmit_power: 20
  channel: 20
  ```
