### ISSUE TITLE
SLZB-06 does not work with version 1.39.1

### ISSUE THREAD

**Issue by eerison** [Koenkk/zigbee2mqtt#23635]
### What happened?

after update to version 1.39.1 the z2m does not start

### What did you expect to happen?

it starts

### How to reproduce it (minimal and precise)

update z2m image from 1.39.0 to 1.39.1 and it gonna see the message bellow

Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20240527

### Adapter

slzb-06

### Setup

docker container

### Debug log

I just can see this error 

Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory
Using '/app/data' as data directory

even if I set log_level: debug

**Comment by eerison** [comment]
and on version 1.39.0 it starts

```
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-08-16 08:30:26] info: 	z2m: Logging to console, file (filename: log.log)
[2024-08-16 08:30:26] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #0326926)
[2024-08-16 08:30:26] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-08-16 08:30:27] info: 	zh:zstack:znp: Opening TCP socket with 
[2024-08-16 08:30:27] info: 	zh:zstack:znp: Socket connected
[2024-08-16 08:30:27] info: 	zh:zstack:znp: Socket ready
[2024-08-16 08:30:27] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-08-16 08:30:28] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-08-16 08:31:09] info: 	z2m: zigbee-herdsman started (restored)
```

**Comment by Snake40** [comment]
Bonsoir.
I'm trying (in vain) to install zigbbee2mqtt in a Docker container with the SLZB-06 POE dongle. Beyond the difficulty you seem to be encountering at the moment, could you give me the docker compose (or equivalent) that you used to install your container as well as the zigbee2mqtt "configuration.yaml" file, specifying where of your container file structure did you put it?...
Thank you in advance for your help...

**Comment by Koenkk** [comment]
@eerison can you try changing your `configuration.yaml` to [this one](https://github.com/Koenkk/zigbee2mqtt/blob/master/data/configuration.example.yaml) and see if tries to start now? (of course it will fail because the port is wrong, but I want to see if it gets further). Also, with what config do you run the Docker container?

**Comment by Snake40** [comment]
Bonjour.
Thank you for your assistance.

I'm working with a Synology DS220+ NAS that already has MQTT installed in a container. I want to do some testing by creating 2 containers (HA and zigbee2mqtt) and using the SLZB-06 POE dongle.
Given your initial post on which I reacted, I am using version 1.39.0 of the z2m image to avoid complicating things...

Here is my docker compose to create the homeassistant and zigbee2mqtt containers:

version: '3.8'
services:
    #Conteneur Home Assistant
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:latest
        restart: always
        #On définit un "bind mount" pour conserver la configuration de Home-Assistant
        volumes:
            - /volume1/docker/homeassistant:/config
        ports:
        #Le port sur lequel sera accessible l'interface web PORT_EXPORTE:PORT_CONTENEUR
            - 8123:8123
        environment:
            - TZ=Europe/Paris

    #Conteneur ZigBee2MQTT
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - /volume1/docker/zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro         
        ports:
            #Port Zigbee2MQTT
            - 8085:8085
        environment:
            - TZ=Europe/Paris

Here is the "configuration.yaml" file which is located in the "/volume1/docker/zigbee2mqtt/data" directory:

homeassistant: false
permit_join: false
frontend:
    port: 8085
mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://192.168.1.100:1883
    user: xxx
    password: xxx
serial:
# Location of SLZB-06
    port: tcp://192.168.1.43:6638
    baudrate: 115200
    adapter: zstack
# Disable green led?
    disable_led: false
# Set output power to max 20
# Advanced settings
advanced:
    transmit_power: 20
    # Let Zigbee2MQTT generate a network key on first start
    network_key: GENERATE
    # Let Zigbee2MQTT generate a pan_id on first start
    pan_id: GENERATE
    # Let Zigbee2MQTT generate a ext_pan_id on first start
    ext_pan_id: GENERATE

In this file, everything related to the SLZB-06 is given to me by the web app associated with the dongle.

Whether I start creating the containers with my "configuration.yaml" file or with the example file that you gave me, the result is the same. Here is the log file associated with the zigbee2mqtt container:

2024/08/17 10:24:46	stderr	    at start (/app/index.js:130:14)
2024/08/17 10:24:46	stderr	    at Object.reRead (/app/lib/util/settings.ts:749:5)
2024/08/17 10:24:46	stderr	    at getInternalSettings (/app/lib/util/settings.ts:466:21)
2024/08/17 10:24:46	stderr	    at read (/app/lib/util/settings.ts:380:27)
2024/08/17 10:24:46	stderr	    at interpretValue (/app/lib/util/settings.ts:369:25)
2024/08/17 10:24:46	stderr	    at Object.read (/app/lib/util/yaml.ts:7:37)
2024/08/17 10:24:46	stderr	    at Object.readFileSync (node:fs:464:35)
2024/08/17 10:24:46	stderr	    at Object.openSync (node:fs:596:3)
2024/08/17 10:24:46	stderr	Error: ENOENT: no such file or directory, open '/app/data/... 3.yaml'
2024/08/17 10:24:45	stdout	Starting Zigbee2MQTT without watchdog.
2024/08/17 10:24:45	stdout	Using '/app/data' as data directory

My current understanding of Docker and z2m and my searches on the web do not allow me to understand what is happening. Currently I think my volume declarations when creating the zigbee2mqtt container are incorrect and not allowing the system to find the "configuration.yaml" file.

Have a nice day ...

**Comment by Snake40** [comment]
Sorry...I just realized I was responding to a message that wasn't intended for me.

**Comment by eerison** [comment]
> @eerison can you try changing your `configuration.yaml` to [this one](https://github.com/Koenkk/zigbee2mqtt/blob/master/data/configuration.example.yaml) and see if tries to start now? (of course it will fail because the port is wrong, but I want to see if it gets further). Also, with what config do you run the Docker container?

I changed the config file for the example that you sent, But it didn´t work too 🤔

**Comment by eerison** [comment]
@Snake40 

it is my docker file

```yaml
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.39.1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 500M 
    volumes:
      - my/local/path/data:/app/data
      - /run/udev:/run/udev:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.z2m.rule=Host(`my.domain.com`)"
      - "traefik.http.routers.z2m.entrypoints=websecure"
      - "traefik.http.services.z2m.loadbalancer.server.port=8080"
      - "traefik.http.routers.z2m.tls.certresolver=cloudflare"
    environment:
      - TZ=Your/TimeZone
    devices:
      # Make sure this matched your adapter location
      - /dev/tty0:/dev/ttyACM0
    networks:
      - proxy

networks:
    proxy:
      driver: bridge
      external: true
```
