### ISSUE TITLE
Beginner Sonoff Stick 3 in Raspberry pi

### ISSUE THREAD

**Issue by Middendorf** [Koenkk/zigbee2mqtt#23642]
### What happened?

Hello folks,

until a few days ago I was still with Conbee, but they stopped the service.

Now I wanted to try out a Sonoff USB 3 stick.

`ls` /dev/serial/by-id/`
usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_b8b49abd27a6ed11a280eba32981d5c7-if00-port0

it is also recognized.

sudo nano /opt/zigbee2mqtt/data/configuration.yaml
```
`#` home Assistant
homeassistant: false
# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://mqtt
  # MQTT server authentication, uncomment if required:
  # user: username
  # password: 123456
# Serial settings
serial:
  # Location of the adapter (see first step of this guide)
port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_b8b49abd27a6ed11a280eba32981d5c7-if00-port0

advanced:
  network_key: GENERATE
  ikea_ota_use_test_url: true
  legacy_api: false
  log_level: debug

frontend: true
frontend:
  port: 8020
  host: 0.0.0.0
  auth_token: 123456

``` 

--- this is what the start of npm looks like----

cd /opt/zigbee2mqtt                               
pi@Zuhause:/opt/zigbee2mqtt $ npm start

>zigbee2mqtt@1.39.1 start
> node index.js

Starting Zigbee2MQTT without watchdog.

/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: unexpected end of the stream within a single quoted scalar (32:1)

 29 |   host: 0.0.0.0
 30 |   auth_token: 123456
 31 |   url: http://localhost
 32 | 
------^
    at generateError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:187:9)
    at readSingleQuotedScalar (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:624:3)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1446:13)
    at readBlockMapping (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockMapping (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1688:5)
pi@Zuhause:/opt/zigbee2mqtt $

I followed this page, but only from the point where they talk about setting up Zigbee2mqtt configuration
https://nerdiy.de/de_de/howto-zigbee-installation-von-zigbee2mqtt-auf-dem-raspberry-pi/

Have I forgotten something or made a mistake?? Is there software on the stick?? Or do you have to flash it when you buy it?

I'm a beginner when it comes to this, if I have to flash it it's enough for me to know this, then I'll google it.

I would like to have the web interface, because I can certainly handle something like that better than with codes. I use Fhem as a home assistant on a Raspberry pi4

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

.

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Setup

Fhem, Raspberry Pi4

**Comment by Koenkk** [comment]
```
frontend: true # <- remove this line
frontend:
  port: 8020
  host: 0.0.0.0
  auth_token: 123456
```
