### ISSUE TITLE
zigbee2mqtt doesn't start

### ISSUE THREAD

**Issue by hdelbers** [Koenkk/zigbee2mqtt#23862]
### What happened?

I tried to run zigbee2mqtt and mosquitto in a docker container.

mosquitto runs fine, I can publish messages from another PC and subscribe + read these messages.

zigbee2mqtt does not start and ends with "z2m: Error: startup failed - configuration-adapter mismatch - see logs above for more information". I can't find any helpfull information in logfiles.

### What did you expect to happen?

I expected that it would start without errors and that I could connect to the internal website (http://192.168.2.73:8080/).

### How to reproduce it (minimal and precise)

I reboot my PC which starts docker with mosquitto and zigbee2mqtt automatically.

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20240710

### Adapter

SLZB-06

### Setup

raspberry clone with mosquitto and zigbee2mqtt in docker

### Debug log

[log.log](https://github.com/user-attachments/files/16895639/log.log)
[docker-compose.yml.gz](https://github.com/user-attachments/files/16895855/docker-compose.yml.gz)

**Comment by YoungRus** [comment]
Try this format in the composition.
 my z2m doesn't start without an adapter either, maybe that's the problem.
 
 ```
 mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "8020:8020"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    depends_on:
      - mosquitto
```
