### ISSUE TITLE
[Feature request]: Add default reporting setting per device in configuration.yaml

### ISSUE THREAD

**Issue by sdaclin** [Koenkk/zigbee2mqtt#24099]
### Is your feature request related to a problem? Please describe

I've a set of SNZB-02P and I'm not pleased by the default configuration when they are joining.
So I've to change it for each new device joining.

### Describe the solution you'd like

A new Yaml section is added in `configuration.yaml` :
```yaml
device_models:
    'SNZB-02':
        temperature:
            'min_rep_interval': 3600,
            'max_rep_interval': 7200,
            'min_rep_change': 10
```

### Describe alternatives you've considered

I don't zee any other alternative :/

### Additional context

Thanks a lot for reading me.
I searched in the backlog for "default" but didn't manage to find such kind of feature request.
Thanks for your wonderfull work.
