### ISSUE TITLE
Does not work Loginovo ZG-101ZL

### ISSUE THREAD

**Issue by codinv** [Koenkk/zigbee2mqtt#24237]
### What happened?

After update Zigbee2MQTT to 1.40.2 my button Loginovo ZG-101ZL stop working
When I press the button, Z2M returns empty string 
Maybe this is due to the changes in #24013
![IMG_0743](https://github.com/user-attachments/assets/e92b576c-0f09-4d49-8c47-611a1556977a)

### Zigbee2MQTT version

1.40.2 commit: e06848d

### Adapter firmware version

7.4.4 [GA]

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E (EFR32MG21)

### Setup

Docker

**Comment by codinv** [comment]
That's how it doesn't work
```
triggers:
  - domain: mqtt
    device_id: 11111111111111111111111111
    type: action
    subtype: single
    trigger: device
```

But that's how it works

```
triggers:
  - trigger: state
    entity_id:
      - sensor.button_one_action
    to: single
```
