### ISSUE TITLE
Osram RGB Bulbs Error - "Cannot read property 'color' of null'" when setting color via hue and saturation

### ISSUE THREAD

**Issue by odx** [Koenkk/zigbee2mqtt#2450]
# Bug Report
## What happened

I just installed a few Osram bulbs in my garden. I attempt to use hue and saturation to set the color (since this is what HomeKit requires, als all conversions I implemented to far are never 100% reversible).

When is send data to the bulbs (They identify as CLA60 RGBW Z3, PAR 16 50 RGBW - LIGHTIFY or PAR16 RGBW Z3) I don't get proper status updates.

Neither the color values, nor the color_mode property seem to update in the MQTT messages correctly although the bulb's color reflects the given values. Also I noticed that there is an error in the log, although the color of the bulb updates correctly:

```
zigbee2mqtt:error 2019-12-01T20:46:23: Publish 'set' 'color' to 'my_fancy_bulb_name' failed: 'TypeError: Cannot read property 'color' of null'
```

I can set the correct color or color temperature with MQTT messages like:
```
{"color":{"hue":360,"saturation":100}}
{"color":{"hue":180,"saturation":100}}
{"color_temp":370}
```

When the error occurs I don't get a MQTT response message.

## What did you expect to happen

When I use hue and saturation as color parameters, I expect the bulb to report hue and saturation and the color_mode to represent value 0.
When I use color_temp to set the "color", I expect the color_mode to represent value 2 but it does not change.

## How to reproduce it (minimal and precise)
Publish:
```
{"state":"ON"}
```
Response:
```
{"state":"ON","linkquality":47,"last_seen":"2019-12-01T20:36:18.826Z","brightness":127,"color":{"x":0.6223,"y":0.3656,"saturation":100,"hue":357.2},"color_temp":370,"color_mode":1,"elapsed":20808}
```

Publish:
```
{"color":{"hue":360,"saturation":100}}
```
Error in the log:
```
zigbee2mqtt:error 2019-12-01T20:46:23: Publish 'set' 'color' to 'my_fancy_bulb_name' failed: 'TypeError: Cannot read property 'color' of null'
```
No Response received but the bulbs color is red as expected. In the following response messages the hue value is not correct (but saturation is). The color mode does not change to 0.

Publish:
```
{"color_temp":370}
```
Response:
```
{"state":"ON","linkquality":47,"last_seen":"2019-12-01T20:54:05.571Z","brightness":1,"color":{"x":0.6223,"y":0.3656,"saturation":50,"hue":357.2},"color_temp":370,"color_mode":1,"elapsed":63013}
```
And the bulbs color is warm white. But color mode did not change to 2.

## Debug Info
zigbee2mqtt version: 1.7.1
CC2530 firmware version: 20190619 ZStack Home 1.2

**Comment by odx** [comment]
I captured a debug log. I am not really sure how to read it though...
```
adable" +30ms
zigbee2mqtt:debug 2019-12-02T20:15:33: Received MQTT message on 'zigbee/my_fancy_friendly_name/set' with data '{"color":{"hue":360,"saturation":100}}'
winston:file written true false
zigbee2mqtt:debug 2019-12-02T20:15:33: Publishing 'set' 'color' to 'my_fancy_friendly_name'
winston:file written true false
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":39095,"destendpoint":1,"srcendpoint":1,"clusterid":768,"transid":36,"options":0,"radius":30,"len":8,"data":{"type":"Buffer","data":[1,14,67,255,255,254,0,0]}} +4s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,18,36,1,183,152,1,1,0,3,36,0,30,8,1,14,67,255,255,254,0,0,155] +4s
  serialport/stream _write 23 bytes of data +4s
  serialport/binding-abstract write 23 bytes +4s
winston:file logged 37618 debug 2019-12-02T20:15:33: Received MQTT message on 'zigbee/my_fancy_friendly_name/set' with data '{"color":{"hue":360,"saturation":100}}'

winston:file logged 37699 debug 2019-12-02T20:15:33: Publishing 'set' 'color' to 'my_fancy_friendly_name'

  serialport/bindings/unixWrite Starting write 23 bytes offset 0 bytesToWrite 23 +4s
  serialport/bindings/unixWrite write returned: wrote 23 bytes +2ms
  serialport/bindings/unixWrite Finished writing 23 bytes +0ms
  serialport/stream binding.write write finished +5ms
  serialport/bindings/poller received "readable" +4s
  serialport/binding-abstract read +20ms
  serialport/bindings/unixRead Starting read +4s
  serialport/bindings/unixRead Finished read { bytesRead: 6,
  buffer:
   <Buffer fe 0e 61 02 02 00 02 06 03 9b 15 34 01 02 00 00 00 00 d1 fe 03 61 08 00 01 55 3e fe 03 61 08 00 01 55 3e fe 06 61 08 00 04 00 08 00 00 63 fe 03 61 08 ... > } bytes +1ms
  serialport/stream binding.read finished { bytesRead: 6 } +18ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100] +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [] - 100 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading { start: 2405, toRead: 63131 } +5ms
  serialport/binding-abstract read +7ms
  serialport/bindings/unixRead Starting read +7ms
  serialport/bindings/unixRead Finished read { bytesRead: 8,
  buffer:
   <Buffer fe 0e 61 02 02 00 02 06 03 9b 15 34 01 02 00 00 00 00 d1 fe 03 61 08 00 01 55 3e fe 03 61 08 00 01 55 3e fe 06 61 08 00 04 00 08 00 00 63 fe 03 61 08 ... > } bytes +1ms
  serialport/stream binding.read finished { bytesRead: 8 } +2ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,36,226] +4ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,36,226] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [$] - 226 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":36} +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  serialport/stream _read reading { start: 2413, toRead: 63123 } +4ms
  serialport/binding-abstract read +7ms
  serialport/bindings/unixRead Starting read +5ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +17ms
  serialport/bindings/poller received "readable" +18ms
  serialport/binding-abstract read +21ms
  serialport/bindings/unixRead Starting read +20ms
  serialport/bindings/unixRead Finished read { bytesRead: 10,
  buffer:
   <Buffer fe 0e 61 02 02 00 02 06 03 9b 15 34 01 02 00 00 00 00 d1 fe 03 61 08 00 01 55 3e fe 03 61 08 00 01 55 3e fe 06 61 08 00 04 00 08 00 00 63 fe 03 61 08 ... > } bytes +1ms
  serialport/stream binding.read finished { bytesRead: 10 } +23ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,5,69,196,183,152,1,128,141,167] +25ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,5,69,196,183,152,1,128,141,167] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 5 - 2 - 5 - 196 - [����] - 167 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":39095,"relaycount":1,"relaylist":[36224]} +27ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading { start: 2423, toRead: 63113 } +4ms
  serialport/binding-abstract read +6ms
  serialport/bindings/unixRead Starting read +5ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +9ms
  serialport/bindings/poller received "readable" +45ms
  serialport/binding-abstract read +48ms
  serialport/bindings/unixRead Starting read +49ms
  serialport/bindings/unixRead Finished read { bytesRead: 30,
  buffer:
   <Buffer fe 0e 61 02 02 00 02 06 03 9b 15 34 01 02 00 00 00 00 d1 fe 03 61 08 00 01 55 3e fe 03 61 08 00 01 55 3e fe 06 61 08 00 04 00 08 00 00 63 fe 03 61 08 ... > } bytes +1ms
  serialport/stream binding.read finished { bytesRead: 30 } +53ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,0,3,183,152,1,1,0,52,0,128,110,64,0,0,5,8,14,11,67,0,128,141,28,48] +56ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,0,3,183,152,1,1,0,52,0,128,110,64,0,0,5,8,14,11,67,0,128,141,28,48] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [��4�n@
                                                                                 C��] - 48 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":768,"srcaddr":39095,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":52,"securityuse":0,"timestamp":4222592,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[8,14,11,67,0]}} +59ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false},"transactionSequenceNumber":14,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":67,"statusCode":0},"Cluster":{"ID":768,"attributes":{"currentHue":{"ID":0,"type":32,"name":"currentHue"},"currentSaturation":{"ID":1,"type":32,"name":"currentSaturation"},"remainingTime":{"ID":2,"type":33,"name":"remainingTime"},"currentX":{"ID":3,"type":33,"name":"currentX"},"currentY":{"ID":4,"type":33,"name":"currentY"},"driftCompensation":{"ID":5,"type":48,"name":"driftCompensation"},"compensationText":{"ID":6,"type":66,"name":"compensationText"},"colorTemperature":{"ID":7,"type":33,"name":"colorTemperature"},"colorMode":{"ID":8,"type":48,"name":"colorMode"},"numPrimaries":{"ID":16,"type":32,"name":"numPrimaries"},"primary1X":{"ID":17,"type":33,"name":"primary1X"},"primary1Y":{"ID":18,"type":33,"name":"primary1Y"},"primary1Intensity":{"ID":19,"type":32,"name":"primary1Intensity"},"primary2X":{"ID":21,"type":33,"name":"primary2X"},"primary2Y":{"ID":22,"type":33,"name":"primary2Y"},"primary2Intensity":{"ID":23,"type":32,"name":"primary2Intensity"},"primary3X":{"ID":25,"type":33,"name":"primary3X"},"primary3Y":{"ID":26,"type":33,"name":"primary3Y"},"primary3Intensity":{"ID":27,"type":32,"name":"primary3Intensity"},"primary4X":{"ID":32,"type":33,"name":"primary4X"},"primary4Y":{"ID":33,"type":33,"name":"primary4Y"},"primary4Intensity":{"ID":34,"type":32,"name":"primary4Intensity"},"primary5X":{"ID":36,"type":33,"name":"primary5X"},"primary5Y":{"ID":37,"type":33,"name":"primary5Y"},"primary5Intensity":{"ID":38,"type":32,"name":"primary5Intensity"},"primary6X":{"ID":40,"type":33,"name":"primary6X"},"primary6Y":{"ID":41,"type":33,"name":"primary6Y"},"primary6Intensity":{"ID":42,"type":32,"name":"primary6Intensity"},"whitePointX":{"ID":48,"type":33,"name":"whitePointX"},"whitePointY":{"ID":49,"type":33,"name":"whitePointY"},"colorPointRX":{"ID":50,"type":33,"name":"colorPointRX"},"colorPointRY":{"ID":51,"type":33,"name":"colorPointRY"},"colorPointRIntensity":{"ID":52,"type":32,"name":"colorPointRIntensity"},"colorPointGX":{"ID":54,"type":33,"name":"colorPointGX"},"colorPointGY":{"ID":55,"type":33,"name":"colorPointGY"},"colorPointGIntensity":{"ID":56,"type":32,"name":"colorPointGIntensity"},"colorPointBX":{"ID":58,"type":33,"name":"colorPointBX"},"colorPointBY":{"ID":59,"type":33,"name":"colorPointBY"},"colorPointBIntensity":{"ID":60,"type":32,"name":"colorPointBIntensity"},"enhancedCurrentHue":{"ID":16384,"type":33,"name":"enhancedCurrentHue"},"enhancedColorMode":{"ID":16385,"type":48,"name":"enhancedColorMode"},"colorLoopActive":{"ID":16386,"type":32,"name":"colorLoopActive"},"colorLoopDirection":{"ID":16387,"type":32,"name":"colorLoopDirection"},"colorLoopTime":{"ID":16388,"type":33,"name":"colorLoopTime"},"colorLoopStartEnhancedHue":{"ID":16389,"type":33,"name":"colorLoopStartEnhancedHue"},"colorLoopStoredEnhancedHue":{"ID":16390,"type":33,"name":"colorLoopStoredEnhancedHue"},"colorCapabilities":{"ID":16394,"type":33,"name":"colorCapabilities"},"colorTempPhysicalMin":{"ID":16395,"type":33,"name":"colorTempPhysicalMin"},"colorTempPhysicalMax":{"ID":16396,"type":33,"name":"colorTempPhysicalMax"}},"name":"lightingColorCtrl","commands":{"moveToHue":{"ID":0,"parameters":[{"name":"hue","type":32},{"name":"direction","type":32},{"name":"transtime","type":33}],"name":"moveToHue"},"moveHue":{"ID":1,"parameters":[{"name":"movemode","type":32},{"name":"rate","type":32}],"name":"moveHue"},"stepHue":{"ID":2,"parameters":[{"name":"stepmode","type":32},{"name":"stepsize","type":32},{"name":"transtime","type":32}],"name":"stepHue"},"moveToSaturation":{"ID":3,"parameters":[{"name":"saturation","type":32},{"name":"transtime","type":33}],"name":"moveToSaturation"},"moveSaturation":{"ID":4,"parameters":[{"name":"movemode","type":32},{"name":"rate","type":32}],"name":"moveSaturation"},"stepSaturation":{"ID":5,"parameters":[{"name":"stepmode","type":32},{"name":"stepsize","type":32},{"name":"transtime","type":32}],"name":"stepSaturation"},"moveToHueAndSaturation":{"ID":6,"parameters":[{"name":"hue","type":32},{"name":"saturation","type":32},{"name":"transtime","type":33}],"name":"moveToHueAndSaturation"},"moveToColor":{"ID":7,"parameters":[{"name":"colorx","type":33},{"name":"colory","type":33},{"name":"transtime","type":33}],"name":"moveToColor"},"moveColor":{"ID":8,"parameters":[{"name":"ratex","type":41},{"name":"ratey","type":41}],"name":"moveColor"},"stepColor":{"ID":9,"parameters":[{"name":"stepx","type":41},{"name":"stepy","type":41},{"name":"transtime","type":33}],"name":"stepColor"},"moveToColorTemp":{"ID":10,"parameters":[{"name":"colortemp","type":33},{"name":"transtime","type":33}],"name":"moveToColorTemp"},"enhancedMoveToHue":{"ID":64,"parameters":[{"name":"enhancehue","type":33},{"name":"direction","type":32},{"name":"transtime","type":33}],"name":"enhancedMoveToHue"},"enhancedMoveHue":{"ID":65,"parameters":[{"name":"movemode","type":32},{"name":"rate","type":33}],"name":"enhancedMoveHue"},"enhancedStepHue":{"ID":66,"parameters":[{"name":"stepmode","type":32},{"name":"stepsize","type":33},{"name":"transtime","type":33}],"name":"enhancedStepHue"},"enhancedMoveToHueAndSaturation":{"ID":67,"parameters":[{"name":"enhancehue","type":33},{"name":"saturation","type":32},{"name":"transtime","type":33}],"name":"enhancedMoveToHueAndSaturation"},"colorLoopSet":{"ID":68,"parameters":[{"name":"bits","type":32},{"name":"bytee","type":32},{"name":"action","type":32},{"name":"direction","type":32},{"name":"time","type":33},{"name":"starthue","type":33}],"name":"colorLoopSet"},"stopMoveStep":{"ID":71,"parameters":[{"name":"bits","type":32},{"name":"bytee","type":32},{"name":"action","type":32},{"name":"direction","type":32},{"name":"time","type":33},{"name":"starthue","type":33}],"name":"stopMoveStep"}},"commandsResponse":{}}},"networkAddress":39095,"endpoint":1,"linkquality":52,"groupID":0}' +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +7ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":39095,"destendpoint":1,"srcendpoint":1,"clusterid":768,"transid":37,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[24,14,11,11,0]}} +129ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,15,36,1,183,152,1,1,0,3,37,0,30,5,24,14,11,11,0,46] +128ms
  serialport/stream _write 20 bytes of data +14ms
  serialport/binding-abstract write 20 bytes +19ms
  serialport/bindings/unixWrite Starting write 20 bytes offset 0 bytesToWrite 20 +125ms
zigbee2mqtt:error 2019-12-02T20:15:33: Publish 'set' 'color' to 'my_fancy_friendly_name' failed: 'TypeError: Cannot read property 'color' of null'
winston:file written true false
zigbee2mqtt:info  2019-12-02T20:15:33: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'color' to 'my_fancy_friendly_name' failed: 'TypeError: Cannot read property 'color' of null'","meta":{"friendly_name":"my_fancy_friendly_name"}}'
winston:file written true false
  serialport/stream _read reading { start: 2453, toRead: 63083 } +5ms
  serialport/binding-abstract read +5ms
winston:file logged 37835 error 2019-12-02T20:15:33: Publish 'set' 'color' to 'my_fancy_friendly_name' failed: 'TypeError: Cannot read property 'color' of null'

winston:file logged 38117 info  2019-12-02T20:15:33: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'color' to 'my_fancy_friendly_name' failed: 'TypeError: Cannot read property 'color' of null'","meta":{"friendly_name":"my_fancy_friendly_name"}}'
```

**Comment by Koenkk** [comment]
Can you provide your `configuration.yaml`? (without password/usernames and ip addresses).

**Comment by odx** [comment]
```
homeassistant: false
permit_join: false
advanced:
  network_key:
    - XXX
  last_seen: ISO_8601
  elapsed: true
  report: true
mqtt:
  base_topic: zigbee
  server: 'mqtt://localhost'
  user: XXX
  password: XXX
serial:
  port: /dev/ttyUSB0
devices:
  '0x00158d000273cfdc':
    qos: 2
    friendly_name: temp2
    retain: true
  '0x00158d000273e222':
    qos: 2
    friendly_name: door1
    retain: true
  '0x00158d0002d481c3':
    qos: 2
    friendly_name: terrassentuer_rechts
    retain: true
  '0x00158d0002d48263':
    qos: 2
    friendly_name: terrassentuer_links
    retain: true
  '0x00158d000273e216':
    qos: 2
    friendly_name: terrassentuer_kueche
    retain: true
  '0x00158d0002d489fb':
    qos: 2
    friendly_name: wohnzimmerfenster_links
    retain: true
  '0x00158d0002e20b98':
    qos: 2
    friendly_name: wohnzimmerfenster_rechts
    retain: true
  '0x00158d0002d489e2':
    qos: 2
    friendly_name: wc-fenster
    retain: true
  '0x00158d0002d48259':
    qos: 2
    friendly_name: fenster_abstellraum
    retain: true
  '0x00158d0002e25588':
    qos: 2
    friendly_name: badfenster
    retain: true
  '0x00158d0002ca2d76':
    qos: 2
    friendly_name: dachfenster_1
    retain: true
  '0x00158d0002d48174':
    qos: 2
    friendly_name: garagentor
    retain: true
  '0x00158d0002d481ed':
    qos: 2
    friendly_name: fenster_2_links
    retain: true
  '0x00158d0002d48177':
    qos: 2
    friendly_name: fenster_2_rechts
    retain: true
  '0x00158d0002e20d06':
    qos: 2
    friendly_name: dachfenster_galerie
    retain: true
  '0x00158d0002d481e9':
    qos: 2
    friendly_name: giebelfenster_links
    retain: true
  '0x00158d0002d48919':
    qos: 2
    friendly_name: giebelfenster_rechts
    retain: true
  '0x00158d000273e1a3':
    qos: 2
    friendly_name: balkontuer
    retain: true
  '0x00158d0002d481b3':
    qos: 2
    friendly_name: garage_gartentuer
    retain: true
  '0x00124b001bb8e9e9':
    qos: 2
    friendly_name: router3
    retain: true
  '0x000b57fffe900c86':
    qos: 2
    friendly_name: nachttisch_janina
    retain: true
  '0x000b57fffe976159':
    qos: 2
    friendly_name: nachttisch_ronja
    retain: true
  '0x000d6ffffe24cb50':
    qos: 2
    friendly_name: sofalampe
    retain: true
  '0xd0cf5efffef808ed':
    qos: 2
    friendly_name: RemoteSZ
    retain: true
  '0x00158d0003042554':
    qos: 2
    friendly_name: pir_wz
    retain: true
    occupancy_timeout: 300
  '0x00158d000305875c':
    qos: 2
    friendly_name: pir_bad
    retain: true
    occupancy_timeout: 300
  '0x00158d00031b315d':
    qos: 2
    friendly_name: spare_broken
    retain: true
  '0x000d6ffffe7aca4b':
    qos: 2
    friendly_name: tradfri_repeater
    retain: true
  '0x00158d0002758987':
    qos: 2
    friendly_name: smoke_broken
    retain: true
  '0x00158d0003021a63':
    qos: 2
    friendly_name: pir_abstell
    retain: true
  '0x7cb03eaa0a068a51':
    qos: 2
    friendly_name: plug1
    retain: true
  '0x00158d0002758682':
    qos: 2
    friendly_name: smoke_wz
    retain: true
  '0x00158d0002759edc':
    qos: 2
    friendly_name: smoke_flur_eg
    retain: true
  '0x00158d000275878d':
    qos: 2
    friendly_name: smoke_flur_og
    retain: true
  '0x00158d0002754836':
    qos: 2
    friendly_name: smoke_sz
    retain: true
  '0x00158d000275472a':
    qos: 2
    friendly_name: smoke_1
    retain: true
  '0x00158d0002758628':
    qos: 2
    friendly_name: smoke_galerie
    retain: true
  '0x00158d0002755923':
    qos: 2
    friendly_name: smoke_2
    retain: true
  '0x7cb03eaa0a06a960':
    qos: 2
    friendly_name: cd_player_2
    retain: true
  '0x00158d000349cb43':
    qos: 2
    friendly_name: temp_sz
    retain: true
  '0x7cb03eaa0a071b63':
    qos: 2
    friendly_name: plug2
    retain: true
  '0x00158d00031b28b5':
    qos: 2
    friendly_name: pir_sz
    retain: true
  '0x00158d00027315e8':
    qos: 2
    friendly_name: temp1
    retain: true
  '0x00158d0002a367df':
    friendly_name: lumicube2
    retain: false
  '0x00158d0002c6371f':
    friendly_name: pir_kueche
    retain: false
  '0x00158d0002b6ee13':
    friendly_name: pir_flur_og
    retain: false
  '0xf0d1b80000129fd1':
    friendly_name: garten_spot_1
    retain: true
  '0x00158d00027305c3':
    friendly_name: pir_flur_eg
    retain: false
  '0x70b3d5de0000140c':
    friendly_name: ecozy1
    retain: false
  '0xf0d1b8000010d9a1':
    friendly_name: garten_kugel_gross
    retain: true
  '0xf0d1b8000010b717':
    friendly_name: garten_kugel_klein_sandkasten
    retain: true
  '0x7cb03eaa00aed8fa':
    friendly_name: garten_spot_2
    retain: true
  '0x7cb03eaa00ab61bc':
    friendly_name: garten_spot_3
    retain: true
  '0x7cb03eaa00aee03d':
    friendly_name: garten_spot_4
    retain: true
  '0x7cb03eaa00aee1ca':
    friendly_name: garten_spot_5
    retain: true
  '0xf0d1b8000010af88':
    friendly_name: garten_kugel_klein_baum
    retain: true
```
