### ISSUE TITLE
Handling of poll check-in from <device> failed with Tuya 19JWZ Door/Window Sensor

### ISSUE THREAD

**Issue by mrebbert** [Koenkk/zigbee2mqtt#24506]
### What happened?

I got five of the Tuya 19JWZ Door/Window sensors. 
They work as expected but I get the error message below nearly every 30 minutes from each of them.
In general i got no connection issues.

`zigbee2mqtt  | [2024-10-27 15:30:40] error:     zh:controller:device: Handling of poll check-in from 0xa4c1380c6c3aa1e1 failed (ZCL command 0xa4c1380c6c3aa1e1/1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 63813 - 1 - 53 - 32 - 11 after 10000ms))`

Currently the sensor is recognized as Sonoff SNZB-04 - i already raised an issue for this: #24499 
I already tried to make device individual configuartions but it seems that they are completely ignored.

Any hints?

My configuration.yaml:

```
homeassistant: true
permit_join: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: '!secrets.yaml mqtt_server'
  user: '!secrets.yaml mqtt_user'
  password: '!secrets.yaml mqtt_password'
serial:
  port: tcp://<ip>:6638
  baudrate: 115200
  adapter: zstack
  disable_led: true
advanced:
  pan_id: <pan_id>
  ext_pan_id:
    <..>

  channel: 20
  network_key: '!secrets.yaml network_key'
  transmit_power: 20
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
  last_seen: ISO_8601_local
  log_output:
    - console
device_options:
  legacy: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
devices: devices.yaml
groups: groups.yaml
```

### Zigbee2MQTT version

1.40.2 commit: e06848d

### Adapter firmware version

20221226

### Adapter

SMLIGHT SLZB-06

### Setup

docker

### Debug log

```
zigbee2mqtt  | [2024-10-27 15:30:16] debug: 	zh:controller:device: check-in from 0xa4c1380c6c3aa1e1: declining fast-poll
zigbee2mqtt  | [2024-10-27 15:30:16] debug: 	zh:controller:endpoint: ZCL command 0xa4c1380c6c3aa1e1/1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"})
zigbee2mqtt  | [2024-10-27 15:30:16] debug: 	zh:controller:endpoint: Request Queue (0xa4c1380c6c3aa1e1/1): send checkinRsp request immediately (sendPolicy=immediate)
zigbee2mqtt  | [2024-10-27 15:30:16] debug: 	zh:zstack: sendZclFrameToEndpointInternal 0xa4c1380c6c3aa1e1:63813/1 (0,0,1)
zigbee2mqtt  | [2024-10-27 15:30:26] debug: 	zh:zstack: Response timeout (0xa4c1380c6c3aa1e1:63813,0)
zigbee2mqtt  | [2024-10-27 15:30:26] debug: 	zh:zstack:znp: --> SREQ: UTIL - assocGetWithAddress - {"extaddr":"0xa4c1380c6c3aa1e1","nwkaddr":63813}
zigbee2mqtt  | [2024-10-27 15:30:26] debug: 	zh:zstack: Response timeout recovery: Node relation 8 (0xa4c1380c6c3aa1e1 / 65534)
zigbee2mqtt  | [2024-10-27 15:30:30] debug: 	zh:zstack: sendZclFrameToEndpointInternal 0xa4c1380c6c3aa1e1:63813/1 (1,0,1)
zigbee2mqtt  | [2024-10-27 15:30:40] debug: 	zh:zstack: Response timeout (0xa4c1380c6c3aa1e1:63813,1)
zigbee2mqtt  | [2024-10-27 15:30:40] debug: 	zh:controller:endpoint: Error: ZCL command 0xa4c1380c6c3aa1e1/1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 63813 - 1 - 53 - 32 - 11 after 10000ms)
zigbee2mqtt  | [2024-10-27 15:30:40] error: 	zh:controller:device: Handling of poll check-in from 0xa4c1380c6c3aa1e1 failed (ZCL command 0xa4c1380c6c3aa1e1/1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 63813 - 1 - 53 - 32 - 11 after 10000ms))

```
