### ISSUE TITLE
[New device support]: I have tried to set this up using the guide with no luck

### ISSUE THREAD

**Issue by jamiegalbreath** [Koenkk/zigbee2mqtt#24900]
### Link

https://www.amazon.co.uk/dp/B0DG8PJC5G?ref=ppx_yo2ov_dt_b_fed_asin_title

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c138ce596d0846","nwkAddr":57126,"manufId":4417,"manufName":"_TZ3000_402vrq2i","powerSource":"Battery","modelId":"TS004F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[1,3,4,6,4096,0],"outClusterList":[3,4,5,6,8,4096,25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1732451631190}

### Zigbee2MQTT version

 1.41.0 commit: unknown

### Comments

I have tried to set this up using the guide with no luck. Help would be greatly appreciated.

### External definition

```shell
const {battery, onOff, commandsOnOff, commandsLevelCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS004F'],
    model: 'TS004F',
    vendor: '_TZ3000_402vrq2i',
    description: 'Automatically generated definition',
    extend: [battery(), onOff({"powerOnBehavior": false}), commandsOnOff(), commandsLevelCtrl()],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Does not show any triggers in setting up an automation

**Comment by codefaux** [comment]
I should add, after creating the .js file and adding it to configuration.yaml I get the following error on any action performed upon the device aka twist, push, etc:

```
[2024-11-25 14:54:33] error:    z2m: Failed to configure 'ZigDial2', attempt 1 (Error: ZCL command 0xa4c138b4b46ef09f/1 genOnOff.configReport([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:350:28)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:956:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:688:9)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:162:17)
    at /app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:546:17
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:205:21)
    at Configure.configure (/app/lib/extension/configure.ts:130:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:206:17))
```

**Comment by DaeMonSxy** [comment]
Hi gents,

just got mine also, would be good to have it integrated, isnt it?:)

**Comment by codefaux** [comment]
After fiddling around and searching more thoroughly, I've gotten mine working. The answer is in another pending issue;

https://github.com/Koenkk/zigbee2mqtt/issues/23543#issuecomment-2508257550

I'm still not sure how to get to that point with the tutorial, but it's working.

It does support three-tap to switch from Command to Event mode.

In Event mode, it supports Single tap, Double tap (don't tap too fast), Hold (4sec), Rotate Left and Rotate Right

In command mode, it supports Single, no Double, no Hold, brightness_step_up/_down and distance, color_temperature_step_up/_down and distance.

**Comment by djurny** [comment]
[1.42.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.42.0) supports the [Smart Knob Dimmer](https://www.aliexpress.com/item/3256807534367914.html).
From the release notes:

- [#8257](https://github.com/Koenkk/zigbee-herdsman-converters/issues/8257) Detect _TZ3000_402vrq2i as Tuya ERS-10TZBVK-AA (@Velomeloman)

Groetjes,

**Comment by codefaux** [comment]
As this release just pushed 14 hours ago, I'll go ahead and say they had support for our device already in the pipeline. Nice to see it released, after @jamiegalbreath verifies support they can probably close this Issue.

Can someone weigh in on best practices moving forward? Should we nuke the external definition file after moving to this version? Is the external definition from the Issue I linked essentially the same as the internal definition will be?

If it is best to remove the external definition, will this impact Home Assistant devices?

**Comment by djurny** [comment]
The external converter was made by copy/pasting parts from what is now available in [1.42.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.42.0). I would remove the external definition and just use what is in [1.42.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.42.0).
I did not see anything bork after doing so.
Groetjes,

**Comment by Velomeloman** [comment]
I also made an automatic converter. After it didn't work, I found a similar device in herdsman converters and copied the code into my js. After checking the converter's operability, I made a pull request to detect this dimmer.
[white_knob.js.txt](https://github.com/user-attachments/files/17978768/white_knob.js.txt)

**Comment by chupacabra71** [comment]
i purchased a similar device from [aliexpress](https://www.aliexpress.us/item/3256805640427007.html?spm=a2g0o.productlist.main.27.7978SbGySbGyoO&algo_pvid=686018c4-6190-4bfe-9e4d-826151656cd3&aem_p4p_detail=2024120505431615949096285037280002409988&algo_exp_id=686018c4-6190-4bfe-9e4d-826151656cd3-13&pdp_npi=4%40dis%21USD%2117.13%2111.99%21%21%2117.13%2111.99%21%402103244b17334061966973691e73ea%2112000034491954011%21sea%21US%213349649559%21X&curPageLogUid=bDe2Ai9wyDJU&utparam-url=scene%3Asearch%7Cquery_from%3A&search_p4p_id=2024120505431615949096285037280002409988_4#nav-specification) and i am on 1.42.0, but i cannot get the device to get any commands.  The device documentation shows the model as `RSH-SC20`.  when i look at what the device exposes it shows all as NULL.  the definition shows as:
```
const {battery, onOff, commandsOnOff, commandsLevelCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS004F'],
    model: 'TS004F',
    vendor: '_TZ3000_abrsvsou',
    description: 'Automatically generated definition',
    extend: [battery(), onOff({"powerOnBehavior":false}), commandsOnOff(), commandsLevelCtrl()],
    meta: {},
};

module.exports = definition;
```
and this is what the exposes shows up as:

<img width="989" alt="Screenshot 2024-12-05 at 9 50 28 AM" src="https://github.com/user-attachments/assets/05b675e4-6d33-42a7-858d-a7f63a0b8e88">

I am a bit new to Z2M, so any pointers would be greatly appreciated.

**Comment by codefaux** [comment]
> but i cannot get the device to get any commands

Your setup may be working properly here.

When these dial devices update, they send multiple, nearly-simultaneous updates.
When in Command mode, this will normally be a step size, an action, a null action state, and a null step size -- within milliseconds of each other. In the UI, you -might- get to see text flicker between N/A and brightness_step_up but most of the time it won't show at all. Plug the device into HASS or monitor your MQTT topic to see if this is the case for you. It shows updates via Device panel in HASS;
![image](https://github.com/user-attachments/assets/6c607a7c-ca27-489a-aa1a-87d7b505a56a)

But the Zigbee2MQTT dash shows N/A the whole time;
![image](https://github.com/user-attachments/assets/6c70d437-0d40-461c-b93b-beb916086e2b)

When in Event mode they drop the step_size feature and the push-and-hold-and-turn feature but gain the capacity to measure a double-click. I use Command mode, so I can capture step size.

Also worth noting, I've found that these report step size in multiples of 12.5, rounded up. AKA -- 13, 25, 38, 50, 63, etc... So, in Home Assistant, you can use an automation to capture step_size to an input_number any time its state changes from Unavailable, divide it by 12.5, and filter that to an int. You'll also need an automation to capture when the Action changes, and so on.

**Comment by chupacabra71** [comment]
> Also worth noting, I've found that these report step size in multiples of 12.5, rounded up. AKA -- 13, 25, 38, 50, 63, etc... So, in Home Assistant, you can use an automation to capture step_size to an input_number any time its state changes from Unavailable, divide it by 12.5, and filter that to an int. You'll also need an automation to capture when the Action changes, and so on.


Thank you!  just checked via MQTT Explorer and they are indeed sending messages.  very confusing, but they seem to be working as you mentioned.

**Comment by codefaux** [comment]
> Thank you!

Quite welcome! I'm glad I could help. If you need help working with this sort of event in Home Automation I'm pretty familiar and willing to help.

> very confusing, but they seem to be working as you mentioned.

It seems confusing at first, but consider -- how would a service know that an event had already been handled? How would it differentiate between the same event being sent twice in a row? By sending an event and returning to 'null' it ensures subsequent triggers will be able to fire regardless of condition. It does make catching things a bit tricky; if you try to read the value after the trigger, it's probably already gone, so you have to capture it with the state event itself.

FWIW I have two Home Assistant automations related to these dials -- one triggered by the step_size event and store it in an input_number, one to catch the action trigger (aka brightness_up or brightness_down) and apply the caught step_size to the light.

**Comment by djurny** [comment]
Hi there,
I found a great example online somewhere of a "peak-hold" type of sensor. This will allow your automation to use the  `action_step_size` properly. You can then have your automation trigger by `rotate_left`, `brightness_step_down`, `rotate_right`,`brightness_step_up`, `toggle` or `single`. (Or any of the other triggers sent by the device.)
```
# in configuration.yaml:
template:
- trigger:
    - platform: state
      entity_id: sensor.<name>_action_step_size
      not_to:
        - unknown
        - unavailable
    sensor:
    - name: "<name>'s action step size"
      state: '{{trigger.to_state.state}}'
```
Most likely you'd be able to filter out the values `unknown` or `unavailable` in z2m as well to achieve the same effect.

Hope that helps,
Groetjes,

**Comment by codefaux** [comment]
Oh - damn, sorry, I had put that into my first message but deleted it to reformat and forgot to re-add it. Good addition. However, you'll want to modify it with the division I mentioned if you want it more easily used. I also added a max() call to ensure it's not set to zero.

I notice you're using template, but I used an automation to store it in a number helper object. I'm curious what the effective difference is, and how one would reference your version.

```
alias: "Kitchen Lighting: (User) Step Size tracking from ZigDial1"
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.zigdial1_action_step_size ###EDIT FOR YOURS
    from: unknown
conditions: []
actions:
  - action: input_number.set_value
    metadata: {}
    data:
      value: "{{ max(trigger.to_state.state | float / 12.5, 1) | int }}"
    target:
      entity_id: input_number.kitchen_lighting_brightness_step_size
mode: single
```

**Comment by djurny** [comment]
Hi @codefaux,
Functionally both will do the job, but I would think the template sensor will be more compact and will not require an additional 'helper' variable.
Combined it will look as follows for your application:
```
# in configuration.yaml:
template:
- trigger:
    - platform: state
      entity_id: sensor.<name>_action_step_size
      not_to:
        - unknown
        - unavailable
    sensor:
    - name: "<name>'s action step size"
      state: '{{[1, trigger.to_state.state|float / 12.5]|max|int}}'
```
In my automation I use the templates sensor as follows:
```
alias: Smart Knob Dimmer
description: "Yes"
triggers:
  - domain: mqtt
    device_id: ***
    type: action
    subtype: rotate_left
    trigger: device
    id: left
  - domain: mqtt
    device_id:  ***
    type: action
    subtype: brightness_step_down
    trigger: device
    id: left
  - domain: mqtt
    device_id:  ***
    type: action
    subtype: rotate_right
    trigger: device
    id: right
  - domain: mqtt
    device_id:  ***
    type: action
    subtype: brightness_step_up
    trigger: device
    id: right
  - domain: mqtt
    device_id:  ***
    type: action
    subtype: toggle
    trigger: device
    id: press
  - domain: mqtt
    device_id:  ***
    type: action
    subtype: single
    trigger: device
    id: press
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - left
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.work_room
            data:
              brightness_step_pct: >-
                {%set _now=now()%}
                {%set _last_updated=states['sensor.dimmer_work_room_accel'].last_updated%}
                {%set _elapsed=_now-_last_updated%}
                {%if _elapsed.total_seconds() < 1.5%}
                  {%set _accel=states('sensor.dimmer_work_room_accel')|int%}
                  {%if _accel is number%}
                    -{{_accel|float*100/255}}
                  {%else%}
                    -10
                  {%endif%}
                {%else%}
                  -10
                {%endif%}
      - conditions:
          - condition: trigger
            id:
              - right
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.work_room
            data:
              brightness_step_pct: >-
                {%set _now=now()%}
                {%set _last_updated=states['sensor.dimmer_work_room_accel'].last_updated%}
                {%set _elapsed=_now-_last_updated%}
                {%if _elapsed.total_seconds() < 1.5%}
                  {%set _accel=states('sensor.dimmer_work_room_accel')|int%}
                  {%if _accel is number%}
                    {{_accel|float*100/255}}
                  {%else%}
                    10
                  {%endif%}
                {%else%}
                  10
                {%endif%}
      - conditions:
          - condition: trigger
            id:
              - press
        sequence:
          - action: adaptive_lighting.apply
            data:
              entity_id: switch.adaptive_lighting_work_room
              adapt_brightness: true
              adapt_color: true
            enabled: false
          - action: adaptive_lighting.set_manual_control
            data:
              entity_id: switch.adaptive_lighting_work_room
              manual_control: false
mode: single
```
Some remarks though:
- The example uses a different calculation for the `action_step_size` - the 'more' you jog the dial, the bigger the adjustment.
- The automation supports both operation modes, so if someone accidentally triple-clicks the button, it still sort-of works.
- Added a check to make sure that the template sensor value is valid. After some testing, I found that the events do not always come in in order. I prefer to have the automation ignore the `action_step_size` in case the last value was sent later on or way earlier than the rotation/click events came in.
- There is room for further improvement by moving the timestamp checking in an automation variable, so I might start reworking it at some point in time. For now it's working adequately for my usecase (dimming my work room lighting with a fancy round dimmer know on my desk). 

Groetjes,
