### ISSUE TITLE
[Feature request]: Add support for NAMRON 4512726 Brightness

### ISSUE THREAD

**Issue by niklas2233** [Koenkk/zigbee2mqtt#24911]
### Is your feature request related to a problem? Please describe

I have a Namron [4512726](https://www.zigbee2mqtt.io/devices/4512726.html) Dimmer Switch but it only sends Action "brightness_move_to_level" but never a value to Home Assistant. It includes the brightness in the payload 
`z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Namron Dimmer Switch', payload '{"action":"brightness_move_to_level","action_brightness_delta":0,"action_level":254,"action_transition_time":0,"battery":200,"brightness":254,"linkquality":212,"update":{"installed_version":22,"latest_version":22,"state":"idle"},"update_available":null,"voltage":3200}'`

### Describe the solution you'd like

A way to add the brightness level to home assistant so that you can use it to sync with a light to make the light also change brightness

### Describe alternatives you've considered

Use a button i guess. Works with ON or OFF but not with brightness. Tried to make a custom extension but didn't figure it out. If i check the Device page on Zigbee2mqtt.io every Namron dimmer has light tag but not this one.

### Additional context

If someone can make an custom extension it would be much appreciated 😊

**Comment by aridder** [comment]
I have the same dimmer. I havn't found a good way of using it for on/off and dimming before today. Before better native support, here is my two automations for on/off and dimming:

For on/off:

yaml
```
alias: Dimmer bad - on/off
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Bad - Dimer
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'on' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: light.downlights_bad
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'off' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: light.downlights_bad
mode: single
```

Dimming:

yaml
```
alias: Dimmer bad - dim
description: ""
triggers:
  - topic: zigbee2mqtt/Bad - Dimer
    trigger: mqtt
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'brightness_move_to_level' }}"
actions:
  - target:
      entity_id: light.downlights_bad
    data:
      brightness: "{{ trigger.payload_json.action_level | int }}"
    action: light.turn_on
mode: single

```
