### ISSUE TITLE
Migrated to 2.0.0, failed to start, exited with code 0 or 139

### ISSUE THREAD

**Issue by diplix** [Koenkk/zigbee2mqtt#25092]
### What happened?

after i migrated to 2.0.0 (accoring to migration log everything went fine), zigbee2bqtt faily to start:
```
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt exited with code 0
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt exited with code 0
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt exited with code 139
[…]
```

### What did you expect to happen?

error code 139 seems to indicate a serial problem, at least accoring to issue [11545](https://github.com/Koenkk/zigbee2mqtt/issues/11545).

### How to reproduce it (minimal and precise)

i run zigbee2mqtt on docker on raspberry pi 3. 
1.42.0 runs fine.

### Zigbee2MQTT version

1.42.0, 2.0.0

### Adapter firmware version

20240710

### Adapter

zStack3x0, LAUNCHXL-CC1352P-2

### Setup

i run zigbee2mqtt on docker on raspberry pi 3

**Comment by Koenkk** [comment]
139 is a SIGSEGV, could you provide your `configuration.yaml`?

**Comment by diplix** [comment]
```
homeassistant:
  experimental_event_entities: true
  discovery_topic: homeassistantconf2
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.57:21608
  user: *********
  password: *********
  client_id: zigbee2mqtt_pi
advanced:
  pan_id: ****
  log_directory: data/log
  log_level: error
  log_output:
    - console
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601
serial:
  port: /dev/ttyACM0
groups:
  '1':
    friendly_name: kammer_lichter
  '2':
    friendly_name: tint_rgb
    retain: true
    transition: 1
  '3':
    friendly_name: kronleuchter
    retain: true
    transition: 1
  '4':
    friendly_name: kinderzimmer_alles
    retain: true
    transition: 1
  '5':
    friendly_name: kinderzimmer_lichter
    retain: true
    transition: 1
  '6':
    friendly_name: group_tradfri_schalter_2
    retain: true
    transition: 1
  '7':
    friendly_name: schlafzimmer_deckenlampe
    retain: true
    transition: 1
  '8':
    friendly_name: group_lidl_1
  '9':
    friendly_name: group_tradfri_schalter_4
    retain: true
    transition: 1
  '10':
    friendly_name: stube_lichter
    retain: true
    transition: 1
  '11':
    friendly_name: kueche_lichter
    retain: true
    transition: 0
  '12':
    friendly_name: strahler_katia_g
  '13':
    friendly_name: bad_lichter
  '14':
    friendly_name: group_stube_fensterlicht
  '901':
    friendly_name: default_bind_group
    retain: true
    transition: 1
  '902':
    friendly_name: group_tradfri_schalter_5
    retain: true
    transition: 1
  '903':
    friendly_name: group_tradfri_schalter_1
    retain: true
    transition: 1
  '904':
    friendly_name: group_tradfri_dimmer_1
    retain: true
    transition: 1
  '905':
    friendly_name: group_tradfri_schalter_6
    retain: true
    transition: 1
  '906':
    friendly_name: group_tradfri_schalter_3
    retain: true
    transition: 1
  '4512':
    friendly_name: flur_lichter
    retain: true
    transition: 1
  '65289':
    friendly_name: magic_group
devices:
  '0x00124b0*********':
    friendly_name: Coordinator
  '0x000d6ff*********':
    friendly_name: signal repeater
    retain: false
  '0x0017880*********':
    friendly_name: hue_ambiance_lamp_1
    retain: true
    transition: 1
    description: Nachttisch Kinderzimmer
  '0x00158d0*********':
    friendly_name: innr_rb_265
    transition: 1
    retain: true
    description: Kammer oben
  '0x00158d0*********':
    friendly_name: innr_rgb_birne_1
    retain: true
    transition: 1
    description: Kugellampe
  '0xd0cf5ef*********':
    friendly_name: mi_nachtlicht
    retain: true
    transition: 1
    description: Flur hinten
  '0x0017880*********':
    friendly_name: hue_schalter_1
    multiple_press_timeout: 0.25
    retain: true
  '0x0017880*********':
    friendly_name: hue_schalter_2
    multiple_press_timeout: 0.25
    retain: true
    disabled: true
    homeassistant: {}
    optimistic: true
  '0x000d6ff*********':
    friendly_name: tradfri_schalter_1
    retain: true
    description: Schalter Sideboard
  '0x14b457f*********':
    friendly_name: tradfri_schalter_2
    retain: true
    description: Lidlpanel Schalter
  '0x90fd9ff*********':
    friendly_name: tradfri_schalter_3
    retain: true
    transition: 1
    description: Sofalampe
  '0x00158d0*********':
    friendly_name: xiaomi_schalter_1
    retain: true
    description: Schalter Küche (dekommisioniert?)
  '0x00158d0*********':
    friendly_name: xiaomi_schalter_3
    retain: true
    description: Kronleuchter
  '0x00158d0*********':
    friendly_name: xiaomi_schalter_4
    retain: true
    description: Kinderzimmer Balkon/Vorhang
    disabled: true
    homeassistant: {}
    optimistic: true
  '0x00158d0*********':
    friendly_name: innr_steckdose_1
    retain: false
    description: AC Schalter
    disabled: false
    homeassistant: {}
    optimistic: true
  '0x00158d0*********':
    friendly_name: innr_steckdose_2
    retain: false
    description: Schalter Leselicht Stube
  '0x000d6ff*********':
    friendly_name: tradfri_steckdose_1
    retain: true
    description: Herdlicht
  '0x00158d0*********':
    friendly_name: xiaomi_bewegungsmelder_3
    retain: true
    description: Küche Tür
    occupancy_timeout: 5
    no_occupancy_since: []
  '0x00158d0*********':
    friendly_name: xiaomi_bewegungsmelder_2
    retain: true
    description: Schlafzimmer Bewegungsmelder
  '0x00158d0*********':
    friendly_name: xiaomi_bewegungsmelder_1
    retain: true
    description: Küchentür Bewegungssensor
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_1
    retain: true
    description: Schlafzimmerfenster
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_2
    retain: true
    description: Wohnzimmerfenster
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_3
    retain: true
    description: Balkontür 1
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_4
    retain: true
    description: Küchenfenster
  '0x00158d0*********':
    friendly_name: xiaomi_vibration_1
    retain: true
    vibration_timeout: 10
  '0x00158d0*********':
    friendly_name: xiaomi_vibration_2
    retain: true
    vibration_timeout: 10
  '0x00158d0*********':
    friendly_name: xiaomi_temp_hum_1
    retain: true
  '0x000b57f*********':
    friendly_name: tradfri_schalter_4
    retain: true
    transition: 1
    description: Schreibtisch(e) Stube
  '0x000b57f*********':
    friendly_name: tradfri_ww_e27_2
    retain: true
    transition: 1
    description: Sofalampe
  '0x000d6ff*********':
    friendly_name: tradfri_steckdose_3
    retain: true
    description: Kammer oben (kammer ESP, Fensterlicht, Rollo)
    disabled: false
    homeassistant: {}
    optimistic: true
  '0x000b57f*********':
    friendly_name: decke_2
    retain: true
    transition: 1
  '0x000b57f*********':
    friendly_name: decke_3
    retain: true
    transition: 1
  '0x000b57f*********':
    friendly_name: decke_1
    retain: true
    transition: 1
  '0x00158d0*********':
    friendly_name: Innr UC 110
    retain: true
    transition: 1
    description: Kammerschrank
  '0x000b57f*********':
    friendly_name: TRADFRI LED driver, 10 w
    retain: true
    transition: 1
    description: flimmert
  '0xd0cf5ef*********':
    friendly_name: stube_kerzenlampe
    retain: true
    transition: 1
  '0x000b57f*********':
    friendly_name: serverraum
    retain: true
    transition: 1
  '0x000b57f*********':
    friendly_name: tradfri_schalter_6
    retain: true
    transition: 2
    description: Küchentisch
  '0x90fd9ff*********':
    friendly_name: kinderzimmer_decke
    retain: true
    transition: 1
  '0x04cf8cd*********':
    friendly_name: opple_sachalter_flur
    transition: 1
  '0x04cf8cd*********':
    friendly_name: opple_sachalter_kueche
    transition: 1
  '0x04cf8cd*********':
    friendly_name: opple_sachalter_kinderzimmer
    transition: 1
  '0x04cf8cd*********':
    friendly_name: opple_sachalter_schlafzimmer
    transition: 1
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_5
    retain: true
    description: Schlafzimmertür
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_7
    retain: true
    description: Stube Sofa Drucksensor
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_6
    retain: true
    description: Balkontürsensor 2
  '0x00124b0*********':
    friendly_name: sonoffz
    retain: true
    description: Wasserkamera Schalter
  '0x588e81f*********':
    friendly_name: tradfri_steckdose_4
    description: Drucker
  '0x588e81f*********':
    friendly_name: tradfri_steckdose_5
    description: Flutlicht Steckdose
  '0x00124b0*********':
    friendly_name: barschrank
    retain: true
    transition: 1
  '0x00158d0*********':
    friendly_name: tint_ww_e27_1
    retain: true
    transition: 1
    description: Theaterscheinwerfer
  '0x00158d0*********':
    friendly_name: tint_RGB_1
    retain: true
    transition: 1
    description: Fake Window Flur
    homeassistant: {}
    optimistic: true
  '0xccccccf*********':
    friendly_name: Symfonisk Dimmer
    debounce: 0.5
    debounce_ignore:
      - action
      - brightness
    description: Symfonisk Küche
    legacy: false
    simulated_brightness:
      delta: 20
      interval: 200
  '0x842e14f*********':
    friendly_name: Lidl Lichtpanel
    retain: true
    transition: 1
  '0xbc33acf*********':
    friendly_name: Lidl Fernbedienung
  '0x842e14f*********':
    friendly_name: aldi_panel
    retain: true
  '0x00124b0*********':
    friendly_name: Stube Fenster (zb)
    optimistic: true
    retain: true
  '0x00124b0*********':
    friendly_name: gledopto_3
    transition: 0
    optimistic: true
    retain: true
    description: Arbeitsplatte
    color_sync: true
    state_action: false
  '0x000b57f*********':
    friendly_name: nachttischlampe
    availability:
      timeout: 1
    optimistic: true
    retain: true
  '0x00158d0*********':
    friendly_name: tint_ww_e27_2
    description: Küchentisch
    transition: 1
  '0x00124b0*********':
    friendly_name: strahler_katia
    optimistic: true
    retain: true
  '0x000b57f*********':
    friendly_name: tradfri_schalter_5
    description: Schreibtisch Kinderzimmer
    legacy: false
  '0x00124b0*********':
    friendly_name: strahler_frida
  '0x00158d0*********':
    friendly_name: aquara_d1_schalter_1
    description: Kinderzimmer Balkon/Vorhang
  '0x00158d0*********':
    friendly_name: aquara_d1_schalter_2
    description: Schalter Küche
  '0x00158d0*********':
    friendly_name: tint_ww_e14_1
    description: DDR Lampe
    transition: 1
  '0x54ef441*********':
    friendly_name: xiaomi_bewegungsmelder_4
    description: PIR Flur vorne
  '0x00158d0*********':
    friendly_name: xi_fenstersensor_8
  '0x70b3d52*********':
    friendly_name: tuya steckdosenleiste
    description: Kinderzimmer (u.a. Sidebioard)
  '0xa4c1386*********':
    friendly_name: Tuya Presence Sensor
  '0x385cfbf*********':
    friendly_name: Vindstyrka
    homeassistant:
      voc_index:
        state_class: measurement
        icon: mdi:radiator
    temperature_precision: 0
    humidity_precision: 0
  '0xa4c1380*********':
    friendly_name: tuya steckdose 1
    disabled: false
    homeassistant: {}
    optimistic: true
  '0xa4c1381*********':
    friendly_name: Tuya Steckdose 2
    description: Roode-1 und AIQea Steckdose
  '0xf0d1b80*********':
    friendly_name: Ledvance B40 E14 Tunable white 1
    description: Schreibtischlampe Kinderzimmer 2
    transition: 0.1
  '0xf0d1b8b*********':
    friendly_name: LEDVANCE E27 RGBTW 1
    description: Tonlampe
  '0x0c4314f*********':
    friendly_name: tradfri_szenen_schalter_2
    description: stube
  '0x00158d00*********':
    friendly_name: Schreibtisch Stube
    description: Schreibtisch Stube 1 neu
    transition: 0.1
  '0xa4c138a*********':
    friendly_name: big red button
  '0x00158d0*********':
    friendly_name: xiaomi_schalter_2
    description: xi Schalter 2 (Stube)
  '0xa4c1380*********':
    friendly_name: tint_RGB_2a
    homeassistant: {}
    optimistic: true
    transition: 1
    description: Fake Window Flur
  '0x84fd27f*********':
    friendly_name: tradfri_szenen_schalter_1
    description: on air
  '0xa4c1380*********':
    friendly_name: bad_waschbecken
    transition: 1
    color_sync: false
    state_action: false
  '0xa4c1380*********':
    friendly_name: bad_decke
    color_sync: false
    transition: 1
  '0x847127f*********':
    friendly_name: tuyai_temp_hum_1
  '0xa4c1383*********':
    friendly_name: Dimmer Bad
    description: Neu, von Tuya
    simulated_brightness:
      delta: 20
      interval: 200
  '0x881a14f*********':
    friendly_name: Tretakt 1
  '0x881a14f*********':
    friendly_name: Tretakt 2
  '0x94b216f*********':
    friendly_name: billy2
blocklist:
  - '0x00124b001d033b3a'
  - '0x0000000000000000'
  - '0x00158d0003ae81d6'
availability: true
version: 2
```

**Comment by Koenkk** [comment]
Could you change the log level to debug?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by diplix** [comment]
not much more info it seems with …
```
advanced:
  log_directory: data/log
  log_level: debug
```

```
pi@olga:~/docker-configs/docker-zigbee2mqtt-v2 $ docker compose logs -f
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Logging to console
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: Loaded state from file /app/data/state.json
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Starting Zigbee2MQTT version 1.42.0-dev (commit #1dde41f7eafe2ecfc55fa1d10a7963c211294043)
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: sd-notify loaded
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Starting zigbee-herdsman (3.0.2)
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":xxxx,\"extendedPanID\":[xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx],\"channelList\":[11],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/app/data/database.db\",\"databaseBackupPath\":\"/app/data/database.db.backup\",\"backupPath\":\"/app/data/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/ttyACM0\"},\"adapter\":{\"disableLED\":false}}"'
zigbee2mqtt  | [2024-12-12 05:03:59] debug: 	zh:adapter:discovery: Connected devices: [{"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if00","vendorId":"0451","productId":"bef3"},{"path":"/dev/ttyACM1","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if03","vendorId":"0451","productId":"bef3"},{"path":"/dev/ttyAMA0"}]
zigbee2mqtt  | [2024-12-12 05:04:00] info: 	zh:adapter:discovery: Matched adapter: {"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if00","vendorId":"0451","productId":"bef3"} => zstack: path=/dev/ttyACM0, score=4
zigbee2mqtt  | [2024-12-12 05:04:00] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":xxxx,"extendedPanID":[xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"zstack"},"adapter":{"disableLED":false},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json"}'
zigbee2mqtt  | [2024-12-12 05:04:00] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee2mqtt exited with code 0
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Logging to console
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: Loaded state from file /app/data/state.json
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Starting Zigbee2MQTT version 1.42.0-dev (commit #1dde41f7eafe2ecfc55fa1d10a7963c211294043)
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: sd-notify loaded
zigbee2mqtt  | [2024-12-12 05:03:58] info: 	z2m: Starting zigbee-herdsman (3.0.2)
zigbee2mqtt  | [2024-12-12 05:03:58] debug: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":xxxx,\"extendedPanID\":[xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx],\"channelList\":[11],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/app/data/database.db\",\"databaseBackupPath\":\"/app/data/database.db.backup\",\"backupPath\":\"/app/data/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/ttyACM0\"},\"adapter\":{\"disableLED\":false}}"'
zigbee2mqtt  | [2024-12-12 05:03:59] debug: 	zh:adapter:discovery: Connected devices: [{"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if00","vendorId":"0451","productId":"bef3"},{"path":"/dev/ttyACM1","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if03","vendorId":"0451","productId":"bef3"},{"path":"/dev/ttyAMA0"}]
zigbee2mqtt  | [2024-12-12 05:04:00] info: 	zh:adapter:discovery: Matched adapter: {"path":"/dev/ttyACM0","manufacturer":"Texas Instruments","serialNumber":"L1100D19","pnpId":"usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if00","vendorId":"0451","productId":"bef3"} => zstack: path=/dev/ttyACM0, score=4
zigbee2mqtt  | [2024-12-12 05:04:00] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":xxxx,"extendedPanID":[xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"zstack"},"adapter":{"disableLED":false},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json"}'
zigbee2mqtt  | [2024-12-12 05:04:00] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
```

**Comment by diplix** [comment]
maybe my docker-compose.yaml is of any help — which works flawlessly with 1.42.0

```
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    privileged: true
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    dns:
      - 127.0.0.1 # system resolver
      - 1.1.1.1 # cloudflare
      - 8.8.8.8 # google
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.29__Embed_with_CMSIS-DAP_L1100D19-if00:/dev/ttyACM0
```
