### ISSUE TITLE
Experimental home assistant events retrigger when restarting container

### ISSUE THREAD

**Issue by abrasher** [Koenkk/zigbee2mqtt#25101]
### What happened?

When I restart the container, ~~some lights that were previously off prior to the restart suddenly turn on. ~~ event entities are retriggered

This was not happening on version 1.4.1

I also get an error about publishEntityState

### What did you expect to happen?

Events not to get retriggered

### How to reproduce it (minimal and precise)

docker compose restart zigbee2mqtt
events are triggered again, event though it is several hours since last action
![image](https://github.com/user-attachments/assets/9b36aa85-cbeb-4ab4-8936-a82e6a986489)

### Zigbee2MQTT version

1.42.0-dev commit: 639e3bb6fd50928da002d417455b5eaf3acb2ad8

### Adapter firmware version

20220219

### Adapter

zStack3x0 Sonoff Zigbee USB Stick

### Setup

Docker, linux x64, debian 12

### Debug log

The devices that trigger a new event after restart:~~turn on after restart are:~~
Hue Tap 00315 (0x000000000047a196)

[log.log](https://github.com/user-attachments/files/18042061/log.log)

**Comment by abrasher** [comment]
I guess this is intended behaviour as the official docs have it ignore if the previous state is unavailable

```
conditions:
          - condition: template
            value_template: "{{trigger.from_state.state != 'unavailable'}}"
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'single'}}"
```
