### ISSUE TITLE
[Feature request]: Please display "last seen" for offline sensors

### ISSUE THREAD

**Issue by AndKe** [Koenkk/zigbee2mqtt#25279]
### Is your feature request related to a problem? Please describe

Sometimes one see an sensor offline, some sensors have very long time between reporting, and will time out.
Please display "last seen" time or time since last seen.   This would maek it easy to see at a glance if there is an actual issue with the sensor, or if it simply timed out.

### Describe the solution you'd like

Please display "last seen" time or time since last seen.  near the red "Offline" in the Availability column.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by AndKe** [comment]
bump

**Comment by AndKe** [comment]
bump

**Comment by Nerivec** [comment]
You can configure the availability setting for specific devices to avoid this scenario:
https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#advanced-configuration
```yaml

devices:
    '0x87654321':
        friendly_name: 'my_switch'
        # Change availability timeout to 3000 minutes for this device only
        availability:
            timeout: 3000
```

Also, last_seen should be displayed in WindFront (in case you haven't tried it yet).
