### ISSUE TITLE
Node fails to bind port 443 due to missing setcap on /usr/bin/node binary

### ISSUE THREAD

**Issue by rklaren** [Koenkk/zigbee2mqtt#25385]
### What happened?

I was trying to run zigbee2mqtt via docker compose on port 443 running as a non root user. Despite adding CAP_NET_BIND_SERVICE the service failed to start with an access denied error.

### What did you expect to happen?

I expected it to started properly after properly configuring the docker compose set up.

### How to reproduce it (minimal and precise)

Environment: Synology DSM 7.2. Docker 20.10.23, docker-compose v2.9.0. Container connected to a macvlan. Zigbee2mqtt started via portainer with this stack:

```
version: "3"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.42.0
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - /volume1/docker/Zigbee2mqtt/data:/app/data
    networks:
      macvlan:
        ipv4_address: 192.168.2.195
    environment:
      - TZ=America/Chicago
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rw
    cap_add:
      - NET_BIND_SERVICE
networks:
  macvlan:
    name: 'macvlan'
    external: true
```

Zigbee2mqtt config:

```
homeassistant: true
permit_join: false
frontend:
  port: 443
  url: https://zigbee2mqtt.my.domain
  ssl_cert: /app/data/certs/fullchain.pem
  ssl_key: /app/data/certs/privkey.pem
mqtt:
  base_topic: zigbee2mqtt
  server: mqtts://mqtt.my.domain
  user: user
  password: mqtt-pass
serial:
  adapter: ember
  port: /dev/ttyUSB0
  rtscts: false
device_options:
  legacy: false
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  network_key: ...
  pan_id: ...
  ext_pan_id: ...
devices:
  ...
```

This results in the following error in the log:

```
....
[2024-12-30 12:28:24] info:     z2m: Zigbee2MQTT started!
Error: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
```

I was able to get the above stack running by executing `setcap 'cap_net_bind_service=+ep' /usr/bin/node` using a small Dockerfile like this and replacing the original container with my patched one:

```
FROM koenkk/zigbee2mqtt:1.42.0

RUN apk add --no-cache libcap
RUN setcap 'cap_net_bind_service=+ep' /usr/bin/node
```

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

NA

### Adapter

NA

### Setup

docker-compose/portainer on synology DSM 7.2

**Comment by bo0tzz** [comment]
This change breaks the container for any nonroot deployment that _doesn't_ set `CAP_NET_BIND_SERVICE`.

**Comment by onedr0p** [comment]
Yeah I run this as a non-root user on Kubernetes and now I get

```
Using '/config' as data directory
[FATAL tini (7)] exec node failed: Operation not permitted
```

Setting the `securityContext` like this helped, but I was already running zigbee2mqtt on port 80 successfully without this change.

```yaml
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
```

I think this should be reverted.
