### ISSUE TITLE
Philips 324131092621 - z2m 2.0 does not expose "action" in HASS integration

### ISSUE THREAD

**Issue by tomtom13** [Koenkk/zigbee2mqtt#25460]
### What happened?

After upgrading z2m to 2.0 via hass update process, for all philips hue dimmer switches:
Philips 324131092621
"action" have disappeared from the hass. Luckilly for me, I backup whole VM so a full restore fixed the problem. 

### Zigbee2MQTT version

2.0

### Adapter firmware version

20240710

### Adapter

SLZB06

### Setup

add-on to home assistant inside of VM.

**Comment by Drafteed** [comment]
Please always read the [release notes](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.0.0), especially the breaking changes section, before updating.

**Comment by psybernoid** [comment]
I too am having the exact same issue. Have reverted back to 1.42.0 for now and restore the configuration.yaml

Reading the release notes, I'm unsure what to do to reasolve it in version 2

I added
`advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false`

as described in the docs, but that was _after_ the upgrade happened. Should I add that before the upgrade?

**Comment by tomtom13** [comment]
Ok, so I see that “_action” got removed and triggers are supposed to be used. However I’m a bit confused here because:
Philips 8718699693985
_action still exists and acts how it’s supposed to.
Additionally if anybody would point me toward how to use triggers along with node-red it would be fantastic.
(It’s going to be long few evenings to reconfigure all automations)

**Comment by KennethLavrsen** [comment]
I actually installed previous version and moved all switches from Deconz to Zigbee2MQTT because the new action events were comming. The new way is pretty cool unlike the horrible device triggers

Here is an example of a full HA automation for a Philips dimmer controlling lights incl up and down dimming

```
alias: Bedroom Dimmer
triggers:
  - trigger: state
    entity_id: event.bedroom_switch_action
    to: null
conditions:
  - condition: template
    value_template: "{{trigger.from_state.state != 'unavailable'}}"
actions:
  - choose:
      - conditions:
          - "{{trigger.to_state.attributes.button == 'on'}}"
          - "{{trigger.to_state.attributes.event_type == 'press'}}"
        sequence:
          - data:
              entity_id:
                - light.bedroom
              brightness_pct: 50
            action: light.turn_on
      - conditions:
          - "{{trigger.to_state.attributes.button == 'on'}}"
          - "{{trigger.to_state.attributes.event_type == 'hold'}}"
        sequence:
          - data:
              entity_id:
                - light.bedroom
                - light.bedroom_desk
                - light.background
              brightness_pct: 100
            action: light.turn_on
      - conditions:
          - "{{trigger.to_state.attributes.button == 'up'}}"
          - "{{trigger.to_state.attributes.event_type == 'hold'}}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: zigbee2mqtt/Bedroom/set
              payload: "{\"brightness_move\": 50 }"
      - conditions:
          - "{{trigger.to_state.attributes.button == 'down'}}"
          - "{{trigger.to_state.attributes.event_type == 'hold'}}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: zigbee2mqtt/Bedroom/set
              payload: "{\"brightness_move\": -50 }"
      - conditions:
          - "{{trigger.to_state.attributes.button in ('up', 'down')}}"
          - "{{trigger.to_state.attributes.event_type == 'hold_release'}}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: zigbee2mqtt/Bedroom/set
              payload: "{\"brightness_move\": 0 }"
      - conditions:
          - "{{trigger.to_state.attributes.button == 'off'}}"
          - "{{trigger.to_state.attributes.event_type == 'press'}}"
        sequence:
          - data:
              entity_id:
                - light.bedroom
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.button == 'off'}}"
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'hold'}}"
        sequence:
          - data:
              entity_id:
                - light.bedroom
                - light.bedroom_desk
                - light.background
            action: light.turn_off
initial_state: "on"
mode: queued
max_exceeded: silent
```
