### ISSUE TITLE
Does not start after update 2.0.0

### ISSUE THREAD

**Issue by thueske** [Koenkk/zigbee2mqtt#25467]
### What happened?

```
Refusing to start because configuration is not valid, found the following errors:
- homeassistant must be object
- availability must be object
```

### What did you expect to happen?

Finding useful information about this problem in https://www.zigbee2mqtt.io/guide/configuration or https://github.com/Koenkk/zigbee2mqtt/discussions/24198.

### Zigbee2MQTT version

2.0.0

### Adapter firmware version

-

### Adapter

CONBEE II

### Setup

Docker

### Debug log

```
homeassistant:
  enabled: true
frontend:
  enabled: true
  port: 8080
device_options:
  legacy: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://broker:1883
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  log_level: warn
  log_output: []
  adapter_delay: 50
  last_seen: ISO_8601
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
blocklist: []
availability:
  enabled: true
version: 4
```

**Comment by thebatfink** [comment]
Add your logs like it asks, not your interpretation of them.

**Comment by Der-WU** [comment]
for test:

remove   legacy: false line

without mine z2mqtt starts

**Comment by thueske** [comment]
> Add your logs like it asks, not your interpretation of them.

<img width="823" alt="Bildschirmfoto 2025-01-04 um 10 16 02" src="https://github.com/user-attachments/assets/d85cb621-842f-4072-be82-f8ad9637173d" />

I already did in the first post ;-)

**Comment by thueske** [comment]
> for test:
> 
> remove legacy: false line
> 
> without mine z2mqtt starts

Does not work.

**Comment by z-master42** [comment]
Do you have migration logs in your Z2M directory?

**Comment by thueske** [comment]
> Do you have migration logs in your Z2M directory?

**migration-1-to-2.log**

```
[CHANGE] Log level 'warn' has been renamed to 'warning'.

[ADDITION] Migrated settings to version 2

[REMOVAL] Action and click sensors have been removed (homeassistant.legacy_triggers setting). This means all sensor.*_action and sensor.*_click entities are removed. Use the MQTT device trigger instead.

[REMOVAL] The permit_join setting has been removed, use the frontend or MQTT to permit joining.

[REMOVAL] Due to the OTA rework, the ota.ikea_ota_use_test_url option has been removed.

[REMOVAL] Removed configuring group members through configuration.yaml (groups.xyz.devices setting). This will not impact current group members; however, you will no longer be able to add or remove devices from a group through the configuration.yaml.
```

**migration-2-to-3.log**

```
[CHANGE] Migrated settings to version 3

[SPECIAL] Property 'homeassistant' is now always an object.

[SPECIAL] Property 'frontend' is now always an object.

[SPECIAL] Property 'availability' is now always an object.
```

**migration-3-to-4.log**

```
[CHANGE] Migrated settings to version 4

[SPECIAL] Device icons are now saved as images.
```

**Comment by z-master42** [comment]
> > Do you have migration logs in your Z2M directory?
> 
> **migration-1-to-2.log**
> 
> ```
> [CHANGE] Log level 'warn' has been renamed to 'warning'.
> 
> [ADDITION] Migrated settings to version 2
> 
> [REMOVAL] Action and click sensors have been removed (homeassistant.legacy_triggers setting). This means all sensor.*_action and sensor.*_click entities are removed. Use the MQTT device trigger instead.
> 
> [REMOVAL] The permit_join setting has been removed, use the frontend or MQTT to permit joining.
> 
> [REMOVAL] Due to the OTA rework, the ota.ikea_ota_use_test_url option has been removed.
> 
> [REMOVAL] Removed configuring group members through configuration.yaml (groups.xyz.devices setting). This will not impact current group members; however, you will no longer be able to add or remove devices from a group through the configuration.yaml.
> ```
> 
> **migration-2-to-3.log**
> 
> ```
> [CHANGE] Migrated settings to version 3
> 
> [SPECIAL] Property 'homeassistant' is now always an object.
> 
> [SPECIAL] Property 'frontend' is now always an object.
> 
> [SPECIAL] Property 'availability' is now always an object.
> ```
> 
> **migration-3-to-4.log**
> 
> ```
> [CHANGE] Migrated settings to version 4
> 
> [SPECIAL] Device icons are now saved as images.
> ```

Locks good so far.

**Comment by shadowpanther** [comment]
I have the same issue here.

Migration logs:
```
# more migration-1-to-2.log 
[ADDITION] Migrated settings to version 2

For more details, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

# more migration-2-to-3.log 
[CHANGE] Migrated settings to version 3

[SPECIAL] Property 'homeassistant' is now always an object.

[SPECIAL] Property 'frontend' is now always an object.

[SPECIAL] Property 'availability' is now always an object.

For more details, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

# more migration-3-to-4.log 
[CHANGE] Migrated settings to version 4

For more details, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
```

```
# cat configuration.yaml
frontend:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  user: mqtt-user
  password: password
serial:
  port: /dev/ttyACM0
advanced:
  network_key:
    - (HIDDEN)
  pan_id: 45894
  ext_pan_id:
    - (HIDDEN)
  log_level: warning
device_options: {}
availability:
  enabled: true
devices:
 (LIST OF DEVICES)
version: 4
homeassistant:
  enabled: true
```

I've added these last two lines and removed the legacy `homeassistant: true` in an effort to fix the config, but it didn't help
```
homeassistant:
  enabled: true
```

It also doesn't start without these two and without the legacy one (no `homeassistant` entries at all).
