### ISSUE TITLE
Migrating to v2 produces error during startup "Cannot create property 'discovery_topic' on boolean 'true'"

### ISSUE THREAD

**Issue by janpfischer** [Koenkk/zigbee2mqtt#25518]
### What happened?

I try to upgrade my zigbee2mqtt installation to v2. When starting the new image I will get the following log entries:

```
Using '/data' as data directory
Starting Zigbee2MQTT without watchdog.
TypeError: Cannot create property 'enabled' on boolean 'true'
    at iterate (/app/lib/util/settings.ts:360:59)
    at iterate (/app/lib/util/settings.ts:377:21)
    at iterate (/app/lib/util/settings.ts:377:21)
    at applyEnvironmentVariables (/app/lib/util/settings.ts:383:5)
    at read (/app/lib/util/settings.ts:278:5)
    at getPersistedSettings (/app/lib/util/settings.ts:393:21)
    at Object.reRead (/app/lib/util/settings.ts:640:5)
    at start (/app/index.js:130:14)
stream closed EOF for home-automation/zigbee2mqtt-0 (app)

```

Part of the configuration.yaml
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto.home-automation.svc.cluster.local
  keepalive: 60
  user: user
  password: password
  reject_unauthorized: true
  include_device_information: true
  version: 5
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
frontend:
  port: 8080
  url: ......
advanced:
  legacy_api: false
  legacy_availability_payload: false
  log_output:
    - console
  log_level: info
  homeassistant_legacy_entity_attributes: false
  homeassistant_status_topic: homeassistant/status
  homeassistant_legacy_triggers: true
  transmit_power: 20
device_options:
  legacy: false

```

A configuration_v1_backup yaml is present in the directory but I can't find any migration log file so I assume that the migration did not started. 
The configuration.yaml seems to have to old structure. I believe the creation of the configuration.yaml is failing with the error. 

I configure zigbee2mqtt through ENVs. This are my ENVs: 

Maybe I am missing something here? I've checked the migration guideline but found nothing.

```
ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_LEGACY_TRIGGERS: "true"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER: 20
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 10
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 1500
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto.home-automation.svc.cluster.local"
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              etc.
```

### Zigbee2MQTT version

2.0.0

### Adapter firmware version

-

### Adapter

Sonoff Zigbee 3

### Setup

Kubernetes
