### ISSUE TITLE
Philips RDM001 Wal Switch - action seems no longer exposed on V2.0.0

### ISSUE THREAD

**Issue by luigui2906** [Koenkk/zigbee2mqtt#25574]
### What happened?

I have been using the Philips Hue RDM001 Wall Switch for all switches in my home since about a year now. I created an automation  that listens to sensor action and if left press on switch, a light is toggled, automation below.

When :
```
entity_id:
  - sensor.smart_mate_philips_kitchen_lights_action
to: left_press_release
enabled: true
trigger: state
````

Then do:
```
metadata: {}
data:
  transition: 0
target:
  entity_id: light.bulb_e27_kitchen
action: light.toggle
````

However, this stop working since I updated to V2.0.0 as the action variable seems not to be exposed, I get error on the automation (`"Error in describing trigger: Cannot read properties of undefined (reading 'entity_id'"`). See image below.

![Screenshot 2025-01-05 143146](https://github.com/user-attachments/assets/8f38f22b-8907-44b9-96de-28cb2ae74fc0)

However; the variable is present on zigbee2mqtt and I can see the state change, see image below.

![Screenshot 2025-01-05 143042](https://github.com/user-attachments/assets/ea7bd09e-4947-49b8-bdd4-2ca572bf7879)

I decided to roll back to V1.42.0 and everything works back again.

### What did you expect to happen?

Automation continues to work on v2.0.0 on same way as it was working on V1.42.0

### How to reproduce it (minimal and precise)

Add sensor to Zigbee2MQTT and create automation on both versions and compare behavior

### Zigbee2MQTT version

2.0.0

### Adapter firmware version

20210708

### Adapter

Sonoff  ZBDongle-P

### Setup

Raspberry Pi with docker container

### Debug log

Sorry, I forgot to download the log before the rollback

**Comment by m0wlheld** [comment]
Not an issue, see #24198

**Comment by m0wlheld** [comment]
#25573

**Comment by luigui2906** [comment]
Thank you for pointing me on the right direction !! It works now with V2.0.0. For everyone that has the same issue, I changed automation from :

```
# AUTOMATION FOR V1.42.0

alias: Kitchen - Countertop Light - Toggle Switch
description: Kitchen countertop lights toggle on/off by selected switches
mode: single
triggers:
  - entity_id:
      - sensor.smart_mate_philips_kitchen_lights_action
    to: left_press_release
    enabled: true
    trigger: state
conditions: []
actions:
  - metadata: {}
    data:
      transition: 0
    target:
      entity_id: light.bulb_e27_kitchen
    action: light.toggle
```

to:

```
# AUTOMATION FOR V2.0.0

alias: Kitchen - Countertop Light - Toggle Switch
description: Kitchen countertop lights toggle on/off by selected switches
mode: single
triggers:
  - trigger: device
    domain: mqtt
    device_id: bbbfc0f589c36c02d260668bbb9b192a
    type: action
    subtype: left_press_release
actions:
  - metadata: {}
    data:
      transition: 0
    target:
      entity_id: light.bulb_e27_kitchen
    action: light.toggle
```

closing now the issue. Thanks for the quick reply and the hard work.
