### ISSUE TITLE
experimental_event_entities problem with events

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#25666]
### What happened?

Maybe it is how it is supposed to be, but..

let assume you have some button, which reports press-release states, then you can use events in automations, you pressed - it delivers "press" you released - it deliver "release", then you press again and it is "press" again. So, second event.

But if I have some another button, which delivers "single" , "double" etc, then no luck.
You click once, it delivered "single" and, obviously, stays "single". Then I press again. MQTT delivers to HA "single". But is is "single" already, so...nothing changed from HA point of view, so, no automation triggered. Unless I do something like double click etc, to change "single" state to something else. Then, after such "reset", single click will work again one time.

So, kind of sucks! :)

I'd suggest that, by default, all such buttons would follow "single" with "release" message maybe.

PS: and yes, like everyone else, I hate device triggers for obvious reasons :)

### What did you expect to happen?

some way to actually use events for a lot of devices, for which it does not work right now.

### How to reproduce it (minimal and precise)

any button, switch etc with "single", "double" etc events, but without explicit "press" event.

### Zigbee2MQTT version

2.0

### Adapter firmware version

8.1.0 [GA]

### Adapter

EmberZNet

### Setup

Supervised HA with Z2M add-on.

**Comment by ctomazini** [comment]
Hello!
I may not fully understand the issue you're facing, but in my automations, I typically set the trigger as a state trigger and use event.entity_action for the entity ID. Then, I create conditions based on each button type or press. It works for me, even if I press the same button (two times a single, for example) twice in a row. Just a note, do not add any "from" or "to" attribute for the trigger.

Let me know if this aligns with what you're looking for!
Here's an example from an automation I use for a 4 buttons moe's switch.

```
alias: Nova Automação
description: ""
triggers:
  - trigger: state
    entity_id:
      - event.moes_botoeira01_action
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 1_single
        sequence:
          - if:
              - condition: time
                after: "23:00:00"
                before: "06:00:00"
                weekday:
                  - sun
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
            then:
              - metadata: {}
                data:
                  color_name: darkgoldenrod
                  brightness_pct: 10
                target:
                  entity_id:
                    - light.abajur_charles
                action: light.toggle
            else:
              - metadata: {}
                data:
                  color_name: darkgoldenrod
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.abajur_charles
                action: light.toggle
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 1_double
        sequence:
          - if:
              - condition: time
                after: "23:00:00"
                before: "06:00:00"
                weekday:
                  - sun
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
            then:
              - metadata: {}
                data:
                  color_name: darkgoldenrod
                  brightness_pct: 10
                target:
                  entity_id: light.abajur_carine
                action: light.toggle
            else:
              - metadata: {}
                data:
                  color_name: darkgoldenrod
                  brightness_pct: 100
                target:
                  entity_id: light.abajur_carine
                action: light.toggle
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 2_single
        sequence:
          - type: toggle
            device_id: 1d9ea071ec7957d93a0e2430faa3cb98
            entity_id: 5ffd138e86157f0997ff8627bf934596
            domain: light
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 3_single
        sequence:
          - data: {}
            target:
              entity_id: light.todas_as_luzes_2
            action: homeassistant.turn_off
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 4_single
        sequence:
          - data: {}
            target:
              device_id: 7108fb98caa6d24bd4e013ae9e46ff95
            action: media_player.media_play_pause
      - conditions:
          - condition: state
            entity_id: event.moes_botoeira01_action
            attribute: event_type
            state: 4_double
        sequence:
          - data:
              entity_id: media_player.lg_webos_tv_uj6565
              button: ENTER
            action: webostv.button
mode: single

```
