### ISSUE TITLE
z2m Timeout

### ISSUE THREAD

**Issue by pinkfloydFR** [Koenkk/zigbee2mqtt#25689]
### What happened?

Hi,
After year of working, i have a lot of problem. I control my light with wireless switch to order relay. But now i need to press multiple time my switch for the order to be send

All my automation are on node red. ( node-red-contrib-home-assistant-websocket v0.63.1 not updated manually to 0.75.0 )

I currently disabled all my get state action node to replace it by mqtt reader

Note, when i publish mqtt message is well received but no action, i need to send the message multiple time for my relay toggle too.

![image](https://github.com/user-attachments/assets/6e889057-127c-4dd7-9140-65b4a2f36a62)

![image](https://github.com/user-attachments/assets/0b5b98a7-9a60-47aa-80bf-65e767ec2647)

![image](https://github.com/user-attachments/assets/5dc97473-9cad-49f0-9b35-662ce28619cc)

- Here is an example of publishing mqtt topic from nod red, I had to execute twice the ON topic for my light (so the relay) switching ON :  

![image](https://github.com/user-attachments/assets/08304c89-0287-4aca-a688-399378ec5e5e)

-Here is another example directly under HA, 5 change on the switch to be active :
 
![image](https://github.com/user-attachments/assets/d8612e79-deec-4e5a-a3d3-8924ba855507)

- My configuration.yaml : 

```
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  enabled: true
  legacy_action_sensor: true
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: ******
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
device_options: 
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  enabled: true
  port: 8099
availability:
  enabled: false
version: 4
```

### What did you expect to happen?

No timeout, action directly send

### Zigbee2MQTT version

2.0.0-2

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Setup

Add on HA OS rasp 4

### Debug log

[45df7312_zigbee2mqtt_2025-01-08T21-16-14.194Z.log](https://github.com/user-attachments/files/18353203/45df7312_zigbee2mqtt_2025-01-08T21-16-14.194Z.log)
