### ISSUE TITLE
Smart energy meter _TZE200_nslr42tt power and current (A) values ​​does not have device_class 

### ISSUE THREAD

**Issue by agalera** [Koenkk/zigbee2mqtt#25691]
### What happened?

Hi! I've noticed that the values ​​for this device that are 'power' are not all displayed as such
This device has several power:
power, power_a, power_b, power_c

The power is displayed correctly:
```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/powermeter/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
device:
  hw_version: 1
  identifiers:
    - zigbee2mqtt_0xa4c1388c743338ef
  manufacturer: Tuya
  model: 3-phase clamp power meter
  model_id: TS0601_3_phase_clamp_meter
  via_device: zigbee2mqtt_bridge_0x00124b002a2e43ae
  name: powermeter
device_class: power
enabled_by_default: true
entity_category: diagnostic
object_id: powermeter_power
origin:
  name: Zigbee2MQTT
  sw_version: 2.0.0
  support_url: https://www.zigbee2mqtt.io
state_class: measurement
state_topic: zigbee2mqtt/powermeter
unique_id: 0xa4c1388c743338ef_power_zigbee2mqtt
unit_of_measurement: W
value_template: '{{ value_json.power }}'
```

power a,b and c are displayed as a normal value, not as power:
```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/powermeter/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
device:
  hw_version: 1
  identifiers:
    - zigbee2mqtt_0xa4c1388c743338ef
  manufacturer: Tuya
  model: 3-phase clamp power meter
  model_id: TS0601_3_phase_clamp_meter
  via_device: zigbee2mqtt_bridge_0x00124b002a2e43ae
  name: powermeter
enabled_by_default: true
object_id: powermeter_power_a
origin:
  name: Zigbee2MQTT
  sw_version: 2.0.0
  support_url: https://www.zigbee2mqtt.io
state_topic: zigbee2mqtt/powermeter
unique_id: 0xa4c1388c743338ef_power_a_zigbee2mqtt
unit_of_measurement: W
value_template: '{{ value_json.power_a }}'
name: Power a
```

I assumed it was due to ```device_class: power``` but I didn't know how to test it and change it.

Thanks a lot!

### What did you expect to happen?

display the power_a, power_b and power_c in the correct data type in home assistant

### How to reproduce it (minimal and precise)

This happens with the default configuration

### Zigbee2MQTT version

2.0.0

### Adapter firmware version

20230507

### Adapter

zStack3x0

### Setup

z2m in docker,  home assistant in VM

### Debug log

availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/powermeter/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
device:
  hw_version: 1
  identifiers:
    - zigbee2mqtt_0xa4c1388c743338ef
  manufacturer: Tuya
  model: 3-phase clamp power meter
  model_id: TS0601_3_phase_clamp_meter
  via_device: zigbee2mqtt_bridge_0x00124b002a2e43ae
  name: powermeter
enabled_by_default: true
object_id: powermeter_power_a
origin:
  name: Zigbee2MQTT
  sw_version: 2.0.0
  support_url: https://www.zigbee2mqtt.io
state_topic: zigbee2mqtt/powermeter
unique_id: 0xa4c1388c743338ef_power_a_zigbee2mqtt
unit_of_measurement: W
value_template: '{{ value_json.power_a }}'
name: Power a

![Captura desde 2025-01-08 22-30-18](https://github.com/user-attachments/assets/79277bdc-7a76-490f-9593-e266427d105b)
