### ISSUE TITLE
Switch problem with 1.8.0 only

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/zigbee2mqtt#2571]
I use my custom switch, Xiaomi switch with Z2M without any issue until version 1.8.0.
The problem:
- I have use Home Assistant automation to sync state of two switches.
- I tested with 2 switches with my custom hardware DNCKATSW001 and  Xiaomi switch: QBKG03LM
- They work normal like this: when **switch.id2_switch** ON then **switch.id1_switch** ON, when **switch.id2_switch** OFF then **switch.id1_switch** OFF and the same with  **switch.id1_switch** states with the automation.
But version 1.8.0 make 2 switches change state endlessly 
- The problem never occur until version 1.8.0, i restore version 1.7.1 and problem solve
- Home Assistant version: 0.102.x, 0.103.x, I don't know if it occur with older version

So it may relate to delay of the on/off command or multi process in version 1.8.0.
Automation here so anyone can produce the bug with any switch in HA (I am guest):

```
  #automation for BR3 light button 1 sync
  - id: control_light_bedroom3
    alias: Control light bedroom 3.1
    trigger:
      platform: state
      entity_id:
        - switch.id1_switch
    condition:
      - condition: template
        value_template: '{{ states.switch["id2_switch"].state != trigger.to_state.state }}'
    action:
      - service_template:
          switch.turn_{{trigger.to_state.state}}
        data:
          entity_id:
            - switch.id2_switch
   #automation for BR3 light button 2 sync
  - id: control_light_bedroom3_2
    alias: Control light bedroom 3.2
    trigger:
      platform: state
      entity_id:
        - switch.id2_switch
    condition:
      - condition: template
        value_template: '{{ states.switch["id1_switch"].state != trigger.to_state.state }}'
    action:
      - service_template:
          switch.turn_{{trigger.to_state.state}}
        data:
          entity_id:
            - switch.id1_switch
```
Queue setting:

```
  "queue": {
    "delay": 50,
    "simultaneously": 5
  }
```
