### ISSUE TITLE
Sensors not fully pairing

### ISSUE THREAD

**Issue by BorisKamp** [Koenkk/zigbee2mqtt#25728]
### What happened?

I have bought door sensors type MCCGQ11LM and motion sensors type RTCGQ11LM trough AliExpress. I have a hard time pairing them (tried multiple to make sure it is not a device failure).
For example, this is my door sensor where battery is always `?` and `Exposes` shows `null` or `n/a` for all values except the Linkquality, that one is read.
<img width="911" alt="Screenshot 2025-01-10 at 15 29 48" src="https://github.com/user-attachments/assets/4d80963e-7855-411a
<img width="409" alt="Screenshot 2025-01-10 at 15 30 28" src="https://github.com/user-attachments/assets/735d6445-eacf-4ce2-86cd-35fe6518d9eb" />
-b123-c601bd6ecf29" />

I have HA and Z2M running in Docker on my R Pi5 and use a Sonoff zigbee dongle. 

This is my `configuration.yaml`:
```
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
  adapter: ezsp
frontend:
  enabled: true
  port: 8080
advanced:
  network_key:
    - 60
    - 224
    - 221
    - 118
    - 108
    - 58
    - 241
    - 162
    - 92
    - 131
    - 26
    - 128
    - 47
    - 19
    - 245
    - 155
device_options: {}
devices:
  '0x00158d008b335764':
    friendly_name: lumi.weather - kinderkamer
  '0x54ef441000ce5aee':
.....
```

this is my dockerfile's Z2M service:
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
       - ./zigbee2mqtt-data:/app/data
       - /run/udev:/run/udev:ro
    ports:
       - 8080:8080
    environment:
       - TZ=Europe/Amsterdam
    devices:
       - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_348acc9ef012ef11b0966db8bf9df066-if00-port0:/dev/ttyUSB0
```

Does anybody have any suggestions? I already tried the following:
1. pressed this **** out of the pair buttons during interview
2. Restarted Z2M
3. Started pair mode on the sensor and only then pressed `Permit join (all)` in Z2M
4. Regular paring process: press `Permit join (all)` and then press the button for five seconds on the device.

This all does not work.

This is my `About`:
```
Zigbee2MQTT version
2.0.0 commit: 060ae99cff715cc9ef6a0cfa7cae0cdcb17f0c8a
Coordinator type
EZSP v8
Coordinator revision
6.10.3.0 build 297
Coordinator IEEE Address
0x0ceff6fffece0bc5
Frontend version
0.9.4
zigbee-herdsman-converters version
21.12.0
zigbee-herdsman version
3.2.1
```

### What did you expect to happen?

I expect the sensors to pair and all the exposes to be read/initialized

### Zigbee2MQTT version

2.0.0 commit: 060ae99cff715cc9ef6a0cfa7cae0cdcb17f0c8a

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP

### Setup

Pi5, docker

### Debug log

I enabled this and restarted Z2M but I see no data folder:
<img width="1048" alt="Screenshot 2025-01-10 at 16 07 37" src="https://github.com/user-attachments/assets/1bb331ff-9e51-4441-9df9-05c99ba37b02" />
