### ISSUE TITLE
Philips Hue Tap dial missing event attributes

### ISSUE THREAD

**Issue by romfir** [Koenkk/zigbee2mqtt#25927]
### What happened?

I'm using [Philips Hue Tap dial switch](https://www.zigbee2mqtt.io/devices/8719514440937_8719514440999.html) and I'm trying to use its dimmer to change brightness of lights im my room. I'm using `experimental_event_entities`, but the event does not contain action time/action step size.
Event looks like this
```
event_types: press, press_release, hold, hold_release, dial_rotate, brightness_step
event_type: dial_rotate
direction: left
icon: mdi:gesture-double-tap
friendly_name: tap Action
speed: step
```
right now I'm reading state of `sensor.tap_action_time` manually, but I think `action_time` should be included in the event
<details>
  <summary>Full home assistant config:</summary>
  
  ```
id: '1737459952114'
  alias: brightness_bedroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.tap_action
  conditions:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.event_type == ''dial_rotate''
      }}'
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_step_pct: '{{ (1 if (trigger.to_state.attributes.direction == ''left'')
        else -1) * 10 * ((states(''sensor.tap_action_time'')|int) / 15) }}'
    target:
      area_id: bedroom
    enabled: true
  mode: single
  ```
</details>

### What did you expect to happen?

I expect all changed values to be added to the event entity

### How to reproduce it (minimal and precise)

1. Enable `experimental_event_entities`
2. Connect and use Philips Hue Tap dial

### Zigbee2MQTT version

2.0.0

### Adapter firmware version

7.4.3 [GA]

### Adapter

Sonoff ZBDongle-E

### Setup

as LXC on proxmox mini pc using community scripts https://github.com/community-scripts/ProxmoxVE
