### ISSUE TITLE
Z2M configuration interface in homeassistant does not reflect the settings on the configuration.yaml

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#26023]
### What happened?

Hi,

I upgraded today to Z2M 2.0.
It took me more time than expected. The main problem was that in Home Assitant, the configuration-editor in YAML-mode does NOT reflect the settings that are stored in the configuration.yaml file of zigbee.2mqtt

i.e., in my case

## configuration.yaml

```
data_path: /config/zigbee2mqtt
devices:
  - devices.yaml
groups:
  - groups.yaml
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://xxx.xxx.xxx
  user: xxxxxxxxx
  password: xxxxxxxxx
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  adapter: zstack
homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
  experimental_event_entities: false
  legacy_action_sensor: true
advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: error
  pan_id: xxxxxxxxx
  channel: 11
  network_key:
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  enabled: true
  port: 8099
availability:
  enabled: true
version: 4

```

But in the YAML-editor of homeassistant addon:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://xxx.xxx.xxx.xxx
  user: xxxxxxxxx
  password: xxxxxxxxx
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: warn
  pan_id: 6758
  channel: 11
  network_key:
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
    - xxx
  availability_blocklist: []
  availability_passlist: []
device_options:
  legacy: false
  transition: 0.7
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true

```

I also noticed that changes, made in the editor in yaml-mode are NOT saved to configuration .yaml.

### What did you expect to happen?

I can use the GUI editor on home assistant to edit my config and that this will be saved to the configuration.yaml file that is used by Z2M

### Zigbee2MQTT version

2.0

### Adapter firmware version

CC2652R_coordinator_20221226

### Adapter

CC2652 (Electrolama zig-a-zig-ah! (zzh!))

### Setup

home assistant OS + Z2M addon
