### ISSUE TITLE
[Feature request]: HT402: Missing Hilo challenge mode attribute

### ISSUE THREAD

**Issue by lit-af** [Koenkk/zigbee2mqtt#26089]
### Is your feature request related to a problem? Please describe

While the HT402 is supported, it's missing the Hilo challenge mode (icon 4) attribute in the converter.

https://www.hiloenergie.com/en-ca/products/heating/thermostat-intelligent-hilo-thermostat/

![Image](https://github.com/user-attachments/assets/44d47096-cb35-4a5c-8f9b-12b77bee2794)

### Describe the solution you'd like

I tried sniffing the Zigbee bus, but I can't find the attribute at the moment. I suspect that it might be enabled once then canceled by the thermostat itself 4 hours later.

I'd like to be able to set pictogram 4 on for four hours so that I know when there's a peak demand event occuring at the moment.

### Describe alternatives you've considered

Live without it.

### Additional context

I'll try asking Stelpro nicely by email for the engineering info.

**Comment by spookyneo** [comment]
@lit-af, did you ever reach out to Stelpro about this and found out the attribute to use ? I too am looking for this.

**Comment by lit-af** [comment]
I didn't contact them. I was able to sniff my ZigBee network while there was a peak event. I'll post them here eventually.

**Comment by spookyneo** [comment]
Awesome ! Please do post them when you get some free time.

**Comment by lit-af** [comment]
Since I don't know how to share the pcapng files without reveiling my network private key, here's some screenshots.

At 4AM when the peak event starts this is written to the thermostat:

![Image](https://github.com/user-attachments/assets/ad4045fc-6d96-4b6e-9a58-cb219c7bbdbe)

At 11AM when the peak event ends this is written to the thermostat:

![Image](https://github.com/user-attachments/assets/188d57c0-e52f-47cb-951d-b853ab6f3384)

I wonder if this is enough information to add this feature to the zigbee-herdsman-converters for HT402

**Comment by lit-af** [comment]
I figured it out! Using zha_toolbox but adding it to z2m might not be too hard, I'll look into it eventually.

To turn it on:
```yaml
action: zha_toolkit.attr_write
data:
  ieee: climate.stello_ht402
  endpoint_id: 25
  cluster: 0x0201
  attribute: 0x4105
  attr_val: 25200
  value_type: uint16
```

To turn it off:
```yaml
action: zha_toolkit.attr_write
data:
  ieee: climate.stello_ht402
  endpoint_id: 25
  cluster: 0x0201
  attribute: 0x4105
  attr_val: 0
  value_type: uint16
  ```
