### ISSUE TITLE
Boot Loop after Update

### ISSUE THREAD

**Issue by Ruko2010** [Koenkk/zigbee2mqtt#26142]
### What happened?

Hi, I user Zigbee2MQTT as a Docker Container in Unraid. Today I updated and now it is not working any more. Looking in the logs, I see this:

```
[2025-02-03 10:24:04] info:     z2m: Logging to console, file (filename: log.log)
[2025-02-03 10:24:04] info:     z2m: Starting Zigbee2MQTT version 2.1.0 (commit #unknown)
[2025-02-03 10:24:04] info:     z2m: Starting zigbee-herdsman (3.2.5)
[2025-02-03 10:24:04] info:     zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
Starting Zigbee2MQTT without watchdog. 
```

This is constantly repeating after some secounds.
I can't reach the frontend of Z2M and also Home Assistant can't discover/control any devices.

This is my Configuration:

```
homeassistant:
  enabled: true
frontend:
  enabled: true
  port: 9442
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.10.245:1883
  keepalive: 60
  reject_unauthorized: false
  version: 4
serial:
  port: /dev/ttyACM0
  adapter: zstack
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
device_options: {}
devices:
  '0x00124b002a533fab':
    friendly_name: LQM 2
  '0x00124b002a539fac':
    friendly_name: LQM 1
  '0x00124b002a53061d':
    friendly_name: LQM 3
  '0x00124b002931de01':
    friendly_name: Garagentor
  '0xf0d1b8be24091d8e':
    friendly_name: Couchlicht
  '0xa4c1383866dcf4f0':
    friendly_name: BadTV
  '0xa4c138b0b095c1c6':
    friendly_name: KücheTV
  '0xa4c13829b1c80f3f':
    friendly_name: GaragenRouter
version: 4
```

I also tryed it with the "ember" configuration, but it is also not working. Hope somebody can help me.

### Zigbee2MQTT version

2.1.0

### Adapter firmware version

Since I can't reach the frontend, I have no idea

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2 

### Setup

Docker Container on Unraid
