### ISSUE TITLE
Not able to pair any device after update

### ISSUE THREAD

**Issue by gvi70000** [Koenkk/zigbee2mqtt#26161]
Hello,
after updating zigbee2mqtt I am not able to pair my devices no matter what i try.
OS: Ubuntu server 24.04
mosquitto version 2.0.20
node --version v20.18.2
pnpm --version 9.15.5
Coordinator: Zigstar V4 running CC1352P2_CC2652P_launchpad_coordinator_20240710.hex

I have programmed the coordinator and erased NVRAM several times.

My configuration file
```yaml
version: 4
permit_join: true
homeassistant:
  enabled: false
frontend:
  enabled: true
  port: 8088
mqtt:
  base_topic: zigbee2mqtt
  server: '!secret.yaml server'
  user: '!secret.yaml user'
  password: '!secret.yaml password'
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  disable_led: false
  rtscts: false
  adapter: zstack
advanced:
  transmit_power: 20
  channel: 11
  log_level: debug
  network_key:
    - 128
    - 93
    - 208
    - 198
    - 121
    - 106
    - 96
    - 115
    - 247
    - 177
    - 234
    - 153
    - 142
    - 229
    - 103
    - 222
  pan_id: 58498
  ext_pan_id:
    - 153
    - 75
    - 239
    - 24
    - 203
    - 234
    - 51
    - 195
```
My log file
[log.log](https://github.com/user-attachments/files/18646246/log.log)

I have turned off all routers and powered devices, turn off WiFi Only the battery powered sensors are "online" and none of them are joining the network.

Any tips/advices on what to do?
