### ISSUE TITLE
Müller Licht 404006/404008/404004 no longer report color_temp to HA

### ISSUE THREAD

**Issue by waclaw66** [Koenkk/zigbee2mqtt#26623]
### What happened?

https://www.zigbee2mqtt.io/devices/404006_404008_404004.html stopped showing value of `color_temp` sensor attribute, (it's always `null`) after update HA to 2025.3.

```
min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 370
effect_list: blink, breathe, okay, channel_change, finish_effect, stop_effect
supported_color_modes: color_temp
effect: null
color_mode: color_temp
brightness: 255
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
friendly_name: Bulb
supported_features: 44
```

However MQTT message contains proper `color_temp` value. Color temperature can be set precisely via HA color temp control, but not via `color_temp` sensor attribute as I did within automations.

Z2M 2.1.3
HA 2025.3.0

light/config

```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
brightness: true
brightness_scale: 254
command_topic: zigbee2mqtt/bulb/set
device:
  hw_version: 1
  identifiers:
    - zigbee2mqtt_0x00158d0002fddfdc
  manufacturer: Müller Licht
  model: Tint LED bulb GU10/E14/E27 350/470/806 lumen, dimmable, opal white
  model_id: 404006/404008/404004
  sw_version: '2.0'
  via_device: zigbee2mqtt_bridge_0x00124b0021b7800c
  name: bulb
effect: true
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
max_mireds: 370
min_mireds: 153
object_id: bulb
origin:
  sw_version: 2.1.3
  name: Zigbee2MQTT
  support_url: https://www.zigbee2mqtt.io
schema: json
state_topic: zigbee2mqtt/bulb
supported_color_modes:
  - color_temp
unique_id: 0x00158d0002fddfdc_light_zigbee2mqtt
name: null
```

### What did you expect to happen?

Sensor `color_temp` attribute shall have current value of color temperature as for other bulb models.

### Zigbee2MQTT version

2.1.3

### Adapter firmware version

20240710

### Adapter

ZBDongle-P

### Setup

docker
