### ISSUE TITLE
State of cover QS-Zigbee-C03 remains open after closing

### ISSUE THREAD

**Issue by Andifront7** [Koenkk/zigbee2mqtt#26809]
### What happened?

When closing the cover the state remains in OPEN. The logs of Zigbee2MQTT show that the last event proclaims position = 0 and state = CLOSE.
The position attribute seems to be processed, the state not (see screenshots).

![Image](https://github.com/user-attachments/assets/cbccd1e3-66d4-4d13-b6c1-b0576abdcd46)
![Image](https://github.com/user-attachments/assets/02206556-f65f-4c1f-ad14-7545fe5827f0)
![Image](https://github.com/user-attachments/assets/2830e911-9d48-476e-8c65-4f195c184f5b)

### What did you expect to happen?

The state of the cover should change from OPEN to CLOSE after closing (position = 0).

### How to reproduce it (minimal and precise)

closing cover

### Zigbee2MQTT version

2.1.3

### Adapter firmware version

7.4.4 [GA]

### Adapter

EmberZNet

### Setup

Add-on on Home Assistant OS

**Comment by Andifront7** [comment]
This bug still exists.

**Comment by Koenkk** [comment]
Could you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by KG3RK3N** [comment]
I've the same issue and share the logs the next days.

**Comment by KG3RK3N** [comment]
Seems to be fixed in latest version

**Comment by AndiLuft** [comment]
Hi @Koenkk , I atteched my logs for a cover not updating the state to "close" after position reached zero. Thanks for your great work!

[rollladen.log](https://github.com/user-attachments/files/22081225/rollladen.log)

**Comment by Koenkk** [comment]
I checked the log but it looks to me the state is `CLOSE` when position is `0`:

```
[2025-09-01 17:28:47] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Rollladen Gästezimmer', payload '{"calibration":"OFF","calibration_time":24,"linkquality":112,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE"}'
```

**Comment by AndiLuft** [comment]
Hi @Koenkk 
here are the logs of two shutters, where one changed it's state to close (Badezimmer) and the other not (Schlafzimmer).
In the logs I see no difference between the two shutters. Maybe the timing (last two changes happen at the same time) is the problem. But it seems to be not a specific issue of QS-Zigbee-C03, since in Schlafzimmer I use TS130F_GIRIER.

<img width="1154" height="508" alt="Image" src="https://github.com/user-attachments/assets/49fea2fc-1d84-4441-ab4c-3379c51511b0" />

<img width="498" height="124" alt="Image" src="https://github.com/user-attachments/assets/3764e1b1-fedd-4655-8aa2-cff7fc176e5c" />

[Badezimmer.log](https://github.com/user-attachments/files/22406926/Badezimmer.log)
[Schlafzimmer.log](https://github.com/user-attachments/files/22406927/Schlafzimmer.log)

**Comment by Koenkk** [comment]
If the published state and position is OK (open = 100, close = 0), this is not a z2m but HA issue.

**Comment by zaubara** [comment]
I think it's a z2m issue after all, in the sense that that's expected behaviour. I have made customizations to the homeassistant entry in the config, and by configuring a closed-state and updating the value_template, this seems to work:

```
  '0xasdf':
    friendly_name: Rollladen
    icon: device_icons/826ac14885905c02268a8f6b249819c9.png
    homeassistant:
      cover:
        value_template: >-
          {% if value_json.get("moving") in ["UP", "DOWN"] %} {{
          value_json["moving"] }} {% else %} {{ value_json.get("state", "STOP")
          }} {% endif %}
        state_open: OPEN
        state_closed: CLOSE
        state_opening: UP
        state_closing: DOWN
        state_stopped: STOP
```
