### ISSUE TITLE
ZBDongle-E Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by hermannw** [Koenkk/zigbee2mqtt#26870]
### What happened?

After my previous dongle failed, I decided t upgrade Z2M to V2.1.3 and bought a new "Zigbee 3.0 USB dongle plus" (ZBDongle-E).  I upgraded the coordinator firmware to 7.4.4 but Z2M won't start. The error is " z2m: Error while starting zigbee-herdsman".
This is a plain vanilla installation on a Pine64 with latest version Armbian (this has been running for the last three+ years) No docker, no Home Assistant... 

Config.yaml:
```
homeassistant:
  enabled: true
frontend:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.120

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
#   Specify valid 'adapter' and 'port' in your configuration.
serial:
    # Location of the adapter
    # USB adapters - use format "port: /dev/serial/by-id/XXX"
    # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
    port: /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_1a22a8dd3a53ef11b2ea20e0174bec31-if00-port0
    # Adapter type, allowed values: `zstack`, `ember`, `deconz`, `zigate` or `zboss`
    adapter: ember
    rtscts: false
    baudrate: 115200
```

Any help would be greatly appreciated.

### What did you expect to happen?

Z2M starting

### How to reproduce it (minimal and precise)

Upgrade Z2M to 2.1.3, plus in upgraded dongle, start Z2M with "pnpm start"

### Zigbee2MQTT version

2.1.3

### Adapter firmware version

7.4.4

### Adapter

ZBDongle-E

### Setup

Plain vanilla Armbian on Pine64. No other programs running on this.

### Debug log

Error after starting:

pi@pine64:/opt/zigbee2mqtt$ pnpm start

> zigbee2mqtt@2.1.3 start /opt/zigbee2mqtt
> node index.js

Starting Zigbee2MQTT without watchdog.
[2025-03-26 09:44:20] info:     z2m: Logging to console, file (filename: log.log)
[2025-03-26 09:44:20] info:     z2m: Starting Zigbee2MQTT version 2.1.3 (commit #fc35ac5)
[2025-03-26 09:44:20] info:     z2m: Starting zigbee-herdsman (3.2.7)
[2025-03-26 09:44:21] info:     zh:ember: Using default stack config.
[2025-03-26 09:44:21] info:     zh:ember: ======== Ember Adapter Starting ========
[2025-03-26 09:44:21] info:     zh:ember:ezsp: ======== EZSP starting ========
[2025-03-26 09:44:21] info:     zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-03-26 09:44:21] info:     zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2025-03-26 09:44:21] info:     zh:ember:uart:ash: Serial port opened
[2025-03-26 09:44:21] info:     zh:ember:uart:ash: ======== ASH starting ========
[2025-03-26 09:44:22] info:     zh:ember:uart:ash: ======== ASH connected ========
[2025-03-26 09:44:22] info:     zh:ember:uart:ash: ======== ASH started ========
[2025-03-26 09:44:22] info:     zh:ember:ezsp: ======== EZSP started ========
[2025-03-26 09:44:22] info:     zh:ember: Adapter EZSP protocol version (13) lower than Host. Switched.
[2025-03-26 09:44:22] info:     zh:ember: Adapter version info: {"ezsp":13,"revision":"7.4.4 [GA]","build":0,"major":7,"minor":4,"patch":4,"special":0,"type":170}
[2025-03-26 09:44:22] error:    z2m: Error while starting zigbee-herdsman
[2025-03-26 09:44:22] error:    z2m: Failed to start zigbee-herdsman
[2025-03-26 09:44:22] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-03-26 09:44:22] error:    z2m: Exiting...
[2025-03-26 09:44:23] error:    z2m: Error: [BACKUP] Current backup file is not for EmberZNet stack.
    at EmberAdapter.getStoredBackup (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.7/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1152:23)
    at EmberAdapter.initTrustCenter (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.7/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:928:29)
    at EmberAdapter.initEzsp (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.7/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:712:18)
    at EmberAdapter.start (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.7/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1536:24)
    at Controller.start (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.7/node_modules/zigbee-herdsman/src/controller/controller.ts:136:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:69:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:142:13)
    at start (/opt/zigbee2mqtt/index.js:161:5)
 ELIFECYCLE  Command failed with exit code 1.

Edit:
In the mean time I did a completely new installation on a Raspberry Pi and the result is exactly the same... 
Set log level to debug. Attached the log here.

[log.log](https://github.com/user-attachments/files/19471849/log.log)
