### ISSUE TITLE
secret.yaml overwritten

### ISSUE THREAD

**Issue by Haraade** [Koenkk/zigbee2mqtt#26943]
### What happened?

latest version performs overwriting of secret.yaml 
Add-on Home Assistant.

configuration.yaml
mqtt:
    server: '!secret.yaml server'
    user: '!secret.yaml user'
    password: '!secret.yaml password'

secret.yaml
server: 'mqtt://localhost:1883'
user: mqtt_user
password: mqtt_password

After upgrade to latest version (2.2.0)
secret.yaml
server: '!secret.yaml server'
user: '!secret.yaml user'
password: '!secret.yaml password'

### Zigbee2MQTT version

2.2.0

### Adapter firmware version

8.0.2

### Adapter

Ember

### Setup

Home Assistant

**Comment by Bloodpack** [comment]
Same here

**Comment by Koenkk** [comment]
- Do you have the MQTT addon config installed?
- Could you provide a screenshot of the addon config? (including `Show unused optional configuration options`)

**Comment by Haraade** [comment]
Installed add-on Mosquitto broker 6.5.0 and with default settings.

![Image](https://github.com/user-attachments/assets/342d4b8a-5d62-4b00-b294-7d23340a3949)
![Image](https://github.com/user-attachments/assets/9ffc4014-65f6-4e56-a53e-42c19077f783)

**Comment by Nerivec** [comment]
I cannot replicate this, I've tried several ways to configure as indicated in first post:
- using carbon-copy of the first post
- using environment variables on top of yaml
- using environment variables in place of yaml

On top of what Koenkk asked, can you also post your `configuration.yaml` file (_you can hide security-related fields_)?

**Comment by ash286** [comment]
> What do you have in the settings of the Zigbee2MQTT addon?
> 
> > Could you provide a screenshot of the addon config? (including Show unused optional configuration options)
> 
> CC: [@ash286](https://github.com/ash286)

@Koenkk Please see the `configuration.yaml` file below. Previously, I was using `EZSP ` driver and now `ember`. This issue replicates with `EZSP` as well as `ember`. Due to this issue I have now reverted back to the previous version - please see the screenshot below.

@Nerivec Please refer to the issue I opened #26950 

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://homeassistant:1883
  user: "!/config/secrets.yaml zigbee-user"
  password: "!/config/secrets.yaml zigbee-password"
serial:
  port: /dev/ttyACM0
  adapter: ember
advanced:
  channel: 25
  network_key: "!/config/secrets.yaml zigbee_key"
zigbee_herdsman_debug: false
```

![Image](https://github.com/user-attachments/assets/c1d16db9-aaf0-48fa-9194-9de77e0f3cd5)
