### ISSUE TITLE
why do some devices randomly disconnect?

### ISSUE THREAD

**Issue by prankousky** [Koenkk/zigbee2mqtt#2705]
Hi everybody,

I get random disconnects from devices that had previously been paired and working just fine with `zigbee2mqtt`. How can I avoid these in the future? I use a single `Texas Instruments CC1352P-2`, but had issues like this back when using a `CC2531` coordinator with multiple `CC2530` routers as well.

## Debug Info
zigbee2mqtt version: `1.8.0`
CC253X firmware version: `{'type': 'zStack3x0', 'meta': {'transportrev': 2, 'product': 1, 'majorrel': 2, 'minorrel': 7, 'maintrel': 1, 'revision': 20191106}}`

# Bug Report
## What happened

Devices will suddenly not update their status any longer. I am using `Home Assistant` and `zigbee2mqttassistant`; example device is a `Xiaomi` door/window sensor
![image](https://user-images.githubusercontent.com/11297070/72063059-52671200-32d9-11ea-9497-451a4662617c.png)
![image](https://user-images.githubusercontent.com/11297070/72063091-64e14b80-32d9-11ea-99e6-37368d698e60.png)

It **does work** at the moment; however, it stopped worked last night. I remotely restarted the server running `zigbee2mqtt` as well as `Home Assistant` etc., but no success. This morning, I took the sensor, pressed the button 5 seconds, and it seems to have paired successfully, as it works again. 

Here is another sensor that *currently* **does not** work. However, it had worked before, and it is the same `Xiaomi` door/window sensor as the others, so it should be known by `zigbee2mqtt` (which it **usually** is; when I first paired it, it was displayed without any errors and as the kind of sensor it actually is).

![image](https://user-images.githubusercontent.com/11297070/72063300-cf928700-32d9-11ea-83f1-6122a2dc2fff.png)
![image](https://user-images.githubusercontent.com/11297070/72063317-dc16df80-32d9-11ea-9eb4-d062b03ae602.png)

This is my `configuration.yaml`; I am using the `npm` version now, but had used `docker` as well, which seems to have had a slightly worse performance than `npm`

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://url:1883'
  user: very_mqtt
  password: much_secret
  client_id: z2mbeelink
  include_device_information: true
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L430019B-if00
  disable_led: false
advanced:
  pan_id: my pan id
  network_key:
   - my network key
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: hass/status
  last_seen: ISO_8601_local
  elapsed: true
  report: true
  log_level: debug
  availability_timeout: 30
  cache_state: true
queue:
  delay: 250
  simultaneously: 15
ban:
  - '0x14b457fffe779019'
devices:
```

My current "fix" is to manually re-pair each device that randomly disconnects. While this works, it also means I have to have `permit_join: true` set **at all times**, because otherwise this will (or might) not work. Well, I could always manually set it via `mqtt`,  but unless I am wrong, I feel like leaving it `true` seems to give an overall better connectivity.

I had messed around with those `queue` parameters, but could not figure out what would give better/worse performance, or if it made a difference at all in my setup.

This is a screenshot of my current network map status
![image](https://user-images.githubusercontent.com/11297070/72063797-c9e97100-32da-11ea-9aab-f07a9843ad3b.png)

Pretty much at the top there is `Flur_Tuer`, which is a door sensor. It is pretty close to the coordinator, and it is successfully paired (and sending updates), so I am not sure why that device (and many others) just "float" there without displaying a connection - the connection **is** there. Then again, the `Haustuer_Button` button (`Xiaomi` as well) **is** connected according to network map image, but it did not work this morning when it was pressed (we use it as a doorbell). So I don't know how accurate the map is.

I do rely on my sensors (well, most of them ;)) for automation, so I cannot always have them disconnect. What did I do wrong in my setup? Thank you for your help :)
