### ISSUE TITLE
Integration for IKEA symfonisk sound controller (E1744) does not create battery sensor

### ISSUE THREAD

**Issue by dmak** [Koenkk/zigbee2mqtt#2715]
## Description

[IKEA symfonisk sound controller](https://www.zigbee2mqtt.io/devices/E1744.html) is a battery-powered device, hence it is expected that zigbee2mqtt-to-homeassistant integration creates additional sensor same way as for [E1524_E1810](https://www.zigbee2mqtt.io/devices/E1524_E1810.html) or [ICTC-G-1](https://www.zigbee2mqtt.io/devices/ICTC-G-1.html)

```
sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
```

## Info
zigbee2mqtt version: 1.8.0
