### ISSUE TITLE
[New device support]: Aqara Climate Sensor W100 X0028HPT89

### ISSUE THREAD

**Issue by on-off-on** [Koenkk/zigbee2mqtt#27262]
### Link

https://www.aqara.com/eu/product/climate-sensor-w100/

### Database entry

{"id":52,"type":"EndDevice","ieeeAddr":"0x54ef441001265aab","nwkAddr":14243,"manufId":4447,"manufName":"Aqara","powerSource":"Battery","modelId":"lumi.sensor_ht.agl001","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[18,1029,1026,1,3,0,64704],"outClusterList":[25],"clusters":{"msRelativeHumidity":{"attributes":{"measuredValue":4000}},"genBasic":{"attributes":{"61441":2,"modelId":"lumi.sensor_ht.agl001"}},"manuSpecificLumi":{"attributes":{"22":"3DC59BEA8B24719A4E92164951599C245245A9A2E505C68A9417CA0BEB6E413F","32":4,"223":{"type":"Buffer","data":[40,35,64,0,0,0,3,35,90,0,0,0,4,33,2,0,5,33,0,0,41,35,0,0,0,0,42,35,0,0,0,0,43,33,126,52,44,41,163,255]},"238":3620,"247":{"type":"Buffer","data":[3,40,24,4,33,0,0,5,33,3,0,10,33,126,52,12,32,10,13,35,36,14,0,0,19,32,0,100,41,142,9,101,33,236,15,102,32,100,103,32,0]},"252":0,"354":1000,"355":30000,"356":50,"357":1,"358":-2000,"359":6000,"360":0,"362":30000,"363":300,"364":1,"365":0,"366":9999,"367":0,"368":2,"370":0,"371":0}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2600}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":0}}},"binds":[{"cluster":1029,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b82e49","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b82e49","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b82e49","endpointID":1}],"configuredReportings":[{"cluster":1029,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100},{"cluster":1026,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10}],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[18],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[18],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":36,"stackVersion":27,"hwVersion":12,"dateCode":"20250417","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1745962646753}

### Zigbee2MQTT version

2.2.1

### Comments

Checkes actual version of zigbee2mqtt, checked supported devices on website

### External definition

```shell
import * as m from 'zigbee-herdsman-converters/lib/modernExtend';

export default {
    zigbeeModel: ['lumi.sensor_ht.agl001'],
    model: 'lumi.sensor_ht.agl001',
    vendor: 'Aqara',
    description: 'Automatically generated definition',
    extend: [m.deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3}}), m.humidity(), m.temperature(), m.battery()],
    meta: {"multiEndpoint":true},
};
```

### What does/doesn't work with the external definition?

3 switches with press, double, long are not supportet, external inputs not supported

**Comment by on-off-on** [comment]
further details:
https://csa-iot.org/csa_product/climate-sensor-w100/

**Comment by TechArea** [comment]
> However actions don't report on HA and I can't get the external sensor working from HA either.

My switches work. I can switch things via automation (see example). But what doesn't work is that the display shows values from the outdoor sensor. This interface doesn't seem to have been implemented. But i'd rather have no display than have aqara on my home assistant. Still... I miss that feature too!

`
alias: Aqara W100 - Master Schalter Aktionen
description: ""
triggers:
  - entity_id: sensor.eg_master_schalter_action
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: single_plus
        sequence:
          - target:
              area_id: wohnzimmer
            action: light.turn_on
            data: {}
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: double_plus
        sequence:
          - data:
              brightness_pct: 1
            target:
              area_id: wohnzimmer
            action: light.turn_on
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: hold_plus
        sequence:
          - data:
              brightness_pct: 100
            target:
              area_id: wohnzimmer
            action: light.turn_on
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: single_minus
        sequence:
          - target:
              area_id: wohnzimmer
            action: light.turn_off
            data: {}
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: double_minus
        sequence:
          - target:
              area_id: erdgeschoss
            action: light.turn_off
            data: {}
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: hold_minus
        sequence:
          - target:
              area_id: haus
            action: light.turn_off
            data: {}
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: single_center
        sequence:
          - data:
              brightness_pct: 100
            target:
              area_id:
                - vorgarten
                - eingang
            action: light.turn_on
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: double_center
        sequence:
          - target:
              area_id: wintergarten
            action: light.turn_on
            data: {}
      - conditions:
          - condition: state
            entity_id: sensor.eg_master_schalter_action
            state: hold_center
        sequence:
          - target:
              area_id:
                - vorgarten
                - eingang
                - wintergarten
            action: light.turn_off
            data: {}
    default: []
mode: single
`

**Comment by TechArea** [comment]
And here's a blueprint:

```
blueprint:
  name: Aqara W100 – 3 Tasten, 3 Funktionen
  description: Reagiere auf alle 9 möglichen Aktionen des Aqara W100 (TH-S04D)
  domain: automation
  input:
    schalter_sensor:
      name: Action-Sensor
      description: Sensor-Entität mit action-Attribut (z. B. sensor.eg_master_schalter_action)
      selector:
        entity:
          domain: sensor
    action_single_plus:
      name: + einfach
      default: []
      selector:
        action: {}
    action_double_plus:
      name: + doppelt
      default: []
      selector:
        action: {}
    action_hold_plus:
      name: + lang
      default: []
      selector:
        action: {}
    action_single_center:
      name: Mitte einfach
      default: []
      selector:
        action: {}
    action_double_center:
      name: Mitte doppelt
      default: []
      selector:
        action: {}
    action_hold_center:
      name: Mitte lang
      default: []
      selector:
        action: {}
    action_single_minus:
      name: – einfach
      default: []
      selector:
        action: {}
    action_double_minus:
      name: – doppelt
      default: []
      selector:
        action: {}
    action_hold_minus:
      name: – lang
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input schalter_sensor
    attribute: action

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'single_plus' }}"
        sequence: !input action_single_plus

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'double_plus' }}"
        sequence: !input action_double_plus

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'hold_plus' }}"
        sequence: !input action_hold_plus

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'single_center' }}"
        sequence: !input action_single_center

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'double_center' }}"
        sequence: !input action_double_center

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'hold_center' }}"
        sequence: !input action_hold_center

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'single_minus' }}"
        sequence: !input action_single_minus

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'double_minus' }}"
        sequence: !input action_double_minus

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.action == 'hold_minus' }}"
        sequence: !input action_hold_minus
```
