### ISSUE TITLE
WARN Soft resetted zigbee

### ISSUE THREAD

**Issue by Sjeff** [Koenkk/zigbee2mqtt#274]
I Installed Zigbee2MQTT a couple of days ago but im running in to some weird warnings.
After the warning no mqtt messages are published anymore. And im unable to find any more errors/warnings in the log files. 

I can see that the time in the docker container is 2 hours off (21:11 in log is 23:11 my time zone).
```
2018-8-10 20:36:16 WARN Soft resetted zigbee
2018-8-10 20:36:16 INFO zigbee-shepherd ready
```
I reflashed the CC2531 sniffer and redownloaded the image to recreate the docker container.
Running for a few hours and the same warning pops up.

I'm running zigbee2mqtt version 0.1.2 (commit #a3d89c0) on ubuntu 18.04 docker.
Docker version 18.06.0-ce, build 0ffa825

MD5 hash of CC2531ZNP-Prod.hex:
3e90df9326d777ab54226413ffba04b6
SHA256 hash of CC2531ZNP-Prod.hex:
08e9ee6f1af54a87f38c059a7ecb54051c20a6afb10c0a6748c362e46552939c

Current configuration.yaml :
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://example:1883'
  user: username
  password: password
  client_id: CC2531
serial:
  port: /dev/zigbee2mqtt
devices:
  '0x00158d000245f2bc':
    friendly_name: Master_Bedroom
    retain: true
    qos: 1
advanced:
  log_level: debug
```

debug log after restart no new mqtt messages are published : https://pastebin.com/Ae05d86Z
