### ISSUE TITLE
Sonoff Zigbee Smart Water Valve: Incorrect `on_time` Duration (Payload Seconds Do Not Match Valve Response)

### ISSUE THREAD

**Issue by TapioJarnfors** [Koenkk/zigbee2mqtt#27465]
### Description

When using a Sonoff Zigbee Smart Water Valve (see: https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv) with Zigbee2MQTT, sending a payload with the `on_time` key does not result in the expected valve open duration. For example, sending `on_time: 11` opens the valve for 110 seconds, and sending `on_time: 13` results in an unexpected duration with an odd value reported back.

#### Device Information

- **Device Type:** EndDevice
- **Zigbee Model:** SWV
- **Zigbee Manufacturer:** SONOFF
- **Description:** Zigbee smart water valve
- **Support status:** Supported
- **IEEE Address:** 0x7cc6b6fffe0d0509
- **Network address:** 0xC348 / 49992
- **Firmware build date:** 20240820
- **Firmware version:** 1.0.4
- **Manufacturer:** SONOFF
- **Model:** SWV
- **Power:** Battery 100%
- **Interview state:** Successful

#### Test Cases

**Case 1: 11 Seconds**

Home Assistant Button:
```yaml
- name: "Open Water Valve for testing 11seconds"
  unique_id: "open_water_valve_testing_11"
  command_topic: "zigbee2mqtt/sonoff_smart_water_valve1/set"
  payload_press: '{"state": "ON", "on_time": 11}'
  icon: mdi:water-pump
```

Zigbee2MQTT Log & Valve Status:
```json
{
  "cyclic_timed_irrigation": {
    "current_count": 1,
    "irrigation_duration": 110,
    "irrigation_interval": 0,
    "total_number": 1
  },
  ...
}
```

**Case 2: 13 Seconds**

Home Assistant Button:
```yaml
- name: "Open Water Valve for testing 13seconds"
  unique_id: "open_water_valve_testing_13"
  command_topic: "zigbee2mqtt/sonoff_smart_water_valve1/set"
  payload_press: '{"state": "ON", "on_time": 13}'
  icon: mdi:water-pump
```

Zigbee2MQTT Log & Valve Status:
```json
{
  "cyclic_timed_irrigation": {
    "current_count": 1,
    "irrigation_duration": 239,
    "irrigation_interval": -1078132736,
    "total_number": 1
  },
  ...
}
```
#### Zigbee2MQTT Configuration

- **Zigbee2MQTT version:** 2.3.0-1  
- **MQTT server:** core-mosquitto (Home Assistant add-on)  
- **Serial adapter:** Ember (`/dev/ttyUSB0`)  
- **Adapter firmware:** 2.3.0  
- **Adapter hardware:** EmberZNet 7.4.4 [GA]  
- **Channel:** 25  
- **Frontend:** enabled (port 8099)  
- **Home Assistant integration:** enabled  
- **Device:**  
  - **IEEE:** `0x7cc6b6fffe0d0509`  
  - **Friendly name:** `sonoff_smart_water_valve1`

#### Expected Behavior

- Setting `on_time` to N should keep the valve ON for N seconds.

#### Actual Behavior

- The value reported back (and the actual valve operation) does not match the payload's `on_time` value.

#### Steps to Reproduce

1. Send an MQTT payload with `{ "state": "ON", "on_time": <N> }` to the topic `zigbee2mqtt/sonoff_smart_water_valve1/set` (via Home Assistant or MQTT Explorer).
2. Observe Zigbee2MQTT logs and the status reported by the valve.
3. Note the mismatch between sent `on_time` and reported/actual operation duration.

#### Relevant Hardware/Software
- Device: Sonoff Smart Water Valve (SWV)
- Home Assistant & MQTT Explorer (version: 0.4.0-beta.6)
- Zigbee2MQTT version: 2.3.0-1

#### Additional Information
- [Device reference](https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv)
- Example logs and payloads included above.

---

If you need any additional information, please let me know

### Zigbee2MQTT version

Zigbee2MQTT version: 2.3.0-1 

### Adapter firmware version

2.3.0

### Adapter

Adapter hardware: EmberZNet 7.4.4 [GA] (Zigbee 3.0 USB Dongle Plus)

### Setup

- **How do you run Z2M:** Home Assistant add-on  
- **Machine:** Raspberry Pi 4 (replace with your hardware if different)  
- **OS:** Home Assistant OS  
- **Zigbee2MQTT version:** 4  
- **Coordinator:** Ember, port `/dev/ttyUSB0`  
- **MQTT:** Core Mosquitto add-on (`mqtt://core-mosquitto:1883`)  
- **Note:** Running as Home Assistant OS add-on, host shell access not available for `uname -a`.

### Debug log

More detailed logs are available upon request

**Comment by Marius-Romanus** [comment]
The same thing happens to me, I set it to 10 minutes and I have to turn it off manually, this is the example of my automation:

```
alias: Riego - Antes del atardecer
description: >
  Activa el riego del patio al atardecer si no ha llovido y no se espera lluvia.
  El riego dura 20 minutos y se apaga automáticamente desde la válvula.
triggers:
  - event: sunset
    trigger: sun
conditions:
  - condition: numeric_state
    entity_id: sensor.aemet_rain
    below: 0.2
  - condition: numeric_state
    entity_id: sensor.aemet_rain_probability
    below: 20
actions:
  - data:
      topic: zigbee2mqtt/Riego patio/set
      payload: "{\"state\": \"ON\", \"on_time\": 600, \"off_wait_time\": 300}"
    action: mqtt.publish
mode: single
```

Firmware Date: 20240820
Firmware Version: 1.0.4
