### ISSUE TITLE
Cannot set states on devices anymore, only read states

### ISSUE THREAD

**Issue by Gibbz** [Koenkk/zigbee2mqtt#27622]
### What happened?

I am tidying up my docker folder. After I restarted z2m today I can no longer set states on any device. I am reading the states without issue in both z2m and node red. However when i try to send any state it errors.

This is an example of me trying to toggle a light on/off
```
2025-06-05 11:14:29z2m: EventBus error 'OTAUpdate/deviceMessage': CommandResponse 0xa4c138d87ca8376f/11 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))

error 2025-06-05 11:14:47z2m: Publish 'set' 'state' to 'Garage Light' failed: 'Error: ZCL command 0x00124b001b7902cc/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 13147 - 1 - 48 - 6 - 11 after 10000ms)'
```

### What did you expect to happen?

set state should work fine

### How to reproduce it (minimal and precise)

im not sure, i just restarted my docker instance. It possibly updated z2m? Edit looks like ive updated from 2.3.0 to 2.4.0 and thats done something bad! Edit: reverted to 2.3 and its still doing the same thing, so not sure whats going on!

### Zigbee2MQTT version

2.4.0

### Adapter firmware version

20240710

### Adapter

zzh!

### Setup

docker or podman

```
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    volumes:
      - ${HOME}/Docker/zigbee2mqtt/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
```

### Debug log

[log.log](https://github.com/user-attachments/files/20601214/log.log)
