### ISSUE TITLE
Availability is OFF but ON in Setting

### ISSUE THREAD

**Issue by LeoeLeoeL** [Koenkk/zigbee2mqtt#27642]
### What happened?

I have availability OFF but:

![Image](https://github.com/user-attachments/assets/2f7d4677-e909-4423-a929-e06bc37f864f)
This is written in Configuration .yaml:
availability:
  enabled: false

When I unchecked "Enabled", Submitted and Restarted, **Z2M** **didn't** **work** **anymore.**
Something was added in configuration.yaml; Sorry but I don't have itto show.
I had to revert to a previous configuration.yaml in order to get Z2M workin again

### What did you expect to happen?

I expect to see the right configuration

### How to reproduce it (minimal and precise)

Read "What Happened" section

### Zigbee2MQTT version

2.40

### Adapter firmware version

8.02 GA (Nerivec)

### Adapter

EmberZNet

### Setup

Proxmox container

**Comment by Nerivec** [comment]
@Koenkk I think this is this line:
https://github.com/Koenkk/zigbee2mqtt/blob/bdb94da46e0461337f4a61b4f2a6bfa5172f608f/lib/util/settings.schema.json#L81
it appears as `Enabled` because of the wrong title (should be `Backoff` instead).
`Enabled` at the bottom of the screenshot is actually `availability>enabled`.
(Seems checkboxes are not showing the description.)

Though, not sure why Z2M wouldn't work after disabling it when availability is disabled (shouldn't have any effect).

**Comment by LeoeLeoeL** [comment]
I replicated the issue.
There are 2  lines in Configuration.yaml added as follows;
From:
availability:
  enabled: false

To:
availability:
  enabled: false
  active:
    backoff: false

When there are the 2 "new lines" Zigbee2MQTT doesn't work.

**Comment by Nerivec** [comment]
Did you respect the indentation?
```yaml
availability:
  enabled: false
  active:
    backoff: false
```

If yes, what error are you getting?

**Comment by LeoeLeoeL** [comment]
The only things in the log are:
[2025-06-09 00:07:21] error: 	zh:ember:uart:ash: Received frame with CRC error
[2025-06-09 00:07:21] error: 	zh:ember:uart:ash: Received ERROR from adapter while connecting, with code=ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT.

**Comment by LeoeLeoeL** [comment]
> Did you respect the indentation?
> 
> availability:
>   enabled: false
>   active:
>     backoff: false
> If yes, what error are you getting?

I didn't add anything on my own.
Z2M added those lines when I unchecked ENABLED.

**Comment by Nerivec** [comment]
> ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT

These are not related to settings though, just the adapter having issues, it's common enough on startup, it does this once, and then starts fine when it retries automatically.
Can you set `log_level` to `debug` so we can get more info about what's actually preventing the start and post the logs?

**Comment by LeoeLeoeL** [comment]
I deleted all logs and then switched to debug but no log file has been created. I rebooted the container several times but no log file.
Perhaps Z2M doesn't start because the CPU load is steady at 0%.

**Comment by Nerivec** [comment]
Can you post your entire `configuration.yaml` (can hide keys/password as needed)?

**Comment by LeoeLeoeL** [comment]
This is the configuration.yaml after i uncheck ENABLED in Availability:
```yaml
version: 4
homeassistant:
  enabled: true
advanced:
  network_key:
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - **
    - ***
    - **
    - ***
    - **
    - **
  pan_id: *****
  ext_pan_id:
    - ***
    - ***
    - ***
    - **
    - **
    - ***
    - ***
    - **
  last_seen: ISO_8601_local
  log_level: debug
  channel: 25
  transmit_power: 20
mqtt:
  server: mqtt://192.168.1.118:1883
  user: ******
  password: ******
serial:
  port: /dev/ttyACM0
  adapter: ember
  disable_led: true
frontend:
  enabled: true
  port: 8099
  base_topic: zigbee2mqtt
  force_disable_retain: false
  include_device_information: false
  keepalive: 60
  maximum_packet_size: 1048576
  notification_filter:
    - 'zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT'
  server: mqtt://192.168.1.118:1883
  user: ******
  version: 4
devices:
  '0x187a3efffeb742e7':
    friendly_name: VIND Sala Cinema
    icon: device_icons/294e3494233342633d14479f42e076af.png
  '0x3425b4fffe7b793f':
    friendly_name: VIND Taverna
    icon: device_icons/294e3494233342633d14479f42e076af.png
  '0xd44867fffe01b7c4':
    friendly_name: VIND Dispensa
    icon: device_icons/294e3494233342633d14479f42e076af.png
  '0x6cfd22fffe1a0c11':
    friendly_name: Monitor
    icon: device_icons/0b39bffc869e7c3c844e3f5d380e1d04.png
  '0x6cfd22fffe1c825f':
    friendly_name: Subwoofer
    icon: device_icons/0b39bffc869e7c3c844e3f5d380e1d04.png
    energy_precision: 2
  '0xbc33acfffe0c27b6':
    friendly_name: Ampli
    icon: device_icons/29ab6739745cd872912999ba4302d8ca.png
  '0x6cfd22fffe1c288c':
    friendly_name: Tavolo Sala Cinema
    icon: device_icons/0b39bffc869e7c3c844e3f5d380e1d04.png
  '0xa4c1384b63888a03':
    friendly_name: Virtual Bagno -1
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0xdc8e95fffe5f1fa9':
    friendly_name: Virtual Taverna/Luce Esterna Taverna
    icon: device_icons/e1b453c64a1336df56ecb3bd9e8e2671.png
  '0xa4c1387dafa4a285':
    friendly_name: Virtual Scala Sotto/Virtual Disimpegno -1
    icon: device_icons/e65d8ff46d852adc5331434b45275b6e.png
  '0x842e14fffe000d29':
    friendly_name: Luce Disimpegno C1
    icon: device_icons/9949e00d3b3848822c03486760ae68b2.png
  '0x588e81fffec9e008':
    friendly_name: Luce Disimpegno C2
    icon: device_icons/9949e00d3b3848822c03486760ae68b2.png
  '0x842e14fffe01dd0b':
    friendly_name: Luce Disimpegno C3
    icon: device_icons/9949e00d3b3848822c03486760ae68b2.png
  '0xa4c138b938783940':
    friendly_name: Luce Dispensa
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0xec1bbdfffe254631':
    friendly_name: Luce Bagno D-1
    icon: device_icons/63148c755093908371fc6d9ed592eb2f.png
  '0x588e81fffebeb9f8':
    friendly_name: Luce Sala Cinema D
    icon: device_icons/379dd18f15514afac94115eddc7f02c0.png
  '0x842e14fffe22df5e':
    friendly_name: Luce Living C
    icon: device_icons/d1783e27de8a1d46a8035fff49bbf46e.png
  '0xa4c1385c31ceac2f':
    friendly_name: Virtual Living
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0x588e81fffe71526b':
    friendly_name: Luce Living W2
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffecf8641':
    friendly_name: Luce Living W1
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffe715265':
    friendly_name: Luce Living W8
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffeca077a':
    friendly_name: Luce Living W7
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffecf8dbe':
    friendly_name: Luce Living W6
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffeef443d':
    friendly_name: Luce Living W5
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x588e81fffefb11ca':
    friendly_name: Luce Living W4
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0x842e14fffe1b7ecc':
    friendly_name: Luce Living W3
    icon: device_icons/b1f42cb6f70e5768aa29ef84bf0c7a4c.png
  '0xd44867fffe026796':
    friendly_name: VIND Cucina
    icon: device_icons/294e3494233342633d14479f42e076af.png
  '0xa4c1382374bf1230':
    friendly_name: Virtual Cucina
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0x60a423fffeff1600':
    friendly_name: Virtual Primo Piano/Virtual Scala Sopra
    icon: device_icons/e1b453c64a1336df56ecb3bd9e8e2671.png
    state_action: true
  '0xf082c0fffe214d7f':
    friendly_name: Luce Bagno D1/Luce Scale D
    icon: device_icons/92927ed3cb7ad3263b4c86b4e086f075.png
  '0xcc86ecfffef3c18e':
    friendly_name: Virtual Camera/Luce Disimpegno 0
    icon: device_icons/e1b453c64a1336df56ecb3bd9e8e2671.png
  '0xa4c1386b605048f3':
    friendly_name: Luce Esterna Living/Virtual Ulivo
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0xa4c138e59bf8fc0b':
    friendly_name: Luce Cancelletto/Luce Ulivo
    icon: device_icons/d7c2a288be053975a48d5f01984e22dd.png
  '0x00158d000704f6e7':
    friendly_name: Sensore Movimento Aqara
    icon: device_icons/2e7485d54446698ed62425812fe12303.png
    occupancy_timeout: 5
    no_occupancy_since: []
  '0x00158d0007103555':
    friendly_name: Sensore Cancelletto
    icon: device_icons/95eff091034c37f5a8e34e03c82cff29.png
  '0x00158d000895e0ae':
    friendly_name: Sensore Porta
    icon: device_icons/95eff091034c37f5a8e34e03c82cff29.png
  '0xa4c13812d1c596f1':
    friendly_name: E.M. Asciugatrice
    icon: device_icons/7f6be149e188b9d7b0fda29fb638249d.png
  '0xa4c138861ee5cd73':
    friendly_name: Luce Esterna Camera/Virtual Limone
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0x000d6ffffebb2b25':
    friendly_name: RPT Camera
    icon: device_icons/24db05d65ad54835a329d5d5b3452222.png
  '0x385cfbfffeaf9519':
    friendly_name: VIND Cameretta
    icon: device_icons/294e3494233342633d14479f42e076af.png
  '0xbc33acfffe5937b5':
    friendly_name: Moge Cam
    icon: device_icons/29ab6739745cd872912999ba4302d8ca.png
  '0x6cfd22fffe1c1395':
    friendly_name: Purificatore Daikin
    icon: device_icons/0b39bffc869e7c3c844e3f5d380e1d04.png
  '0xec1bbdfffeb06619':
    friendly_name: Multipresa Cameretta
    icon: device_icons/3325ca52ebbb299809aa3a85ceef5298.png
  '0xa4c138465b3ffa8e':
    friendly_name: Luce Mansarda
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0xec1bbdfffeb617ee':
    friendly_name: Ferro da Stiro
    icon: device_icons/29ab6739745cd872912999ba4302d8ca.png
  '0xa4c13828bec539b4':
    friendly_name: Luce Esterna Mansarda
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0xa4c1380d613093be':
    friendly_name: Luce Esterna Cameretta
    icon: device_icons/bfe925ac777f6ae1ee876492feb5e044.png
  '0x842e14fffe209a70':
    friendly_name: Luce Moge C
    icon: device_icons/661a781efb60aa9fe95ea9e3f057e4e8.png
  '0xf4ce36993b907389':
    friendly_name: Luce Limone
    icon: device_icons/752427e1ff0512e2f5ce68ed9e8885a2.png
  '0xa4c1382ec0e289b7':
    friendly_name: E.M. Lavastoviglie
    icon: device_icons/7f6be149e188b9d7b0fda29fb638249d.png
  '0x000d6ffffe7ab7a7':
    friendly_name: RPT L.T.
    icon: device_icons/24db05d65ad54835a329d5d5b3452222.png
  '0x003c84fffe8ca53f':
    friendly_name: Luce Posto Auto
    icon: device_icons/d2983fba8d258cc39bb7d3898fadbd33.png
  '0x842e14fffe62635a':
    friendly_name: Irrigazione Maurys
    icon: device_icons/29ab6739745cd872912999ba4302d8ca.png
  '0x7cb03eaa0a009f21':
    friendly_name: Presa Esterna Maurys
    icon: device_icons/1421cda56f9bab7f8ab6e504e036e3e0.png
  '0xa4c1388c6114e3d7':
    friendly_name: E.M Frigo Cucina
    icon: device_icons/7f6be149e188b9d7b0fda29fb638249d.png
  '0xa4c138d888779e91':
    friendly_name: E.M. Lavatrice
    icon: device_icons/7f6be149e188b9d7b0fda29fb638249d.png
  '0x00158d000839ee04':
    friendly_name: Sensore Disimpegno 1
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x00158d00047b57e9':
    friendly_name: Sensore Cameretta
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0xf4ce36467562d893':
    friendly_name: Finestra Centrale
    icon: device_icons/ce8697597a426c7e15105220ba5c455d.png
  '0xf4ce36d8666fac48':
    friendly_name: Finestra Cucina -1
    icon: device_icons/ce8697597a426c7e15105220ba5c455d.png
  '0xf4ce366bab1b414f':
    friendly_name: Finestra Camino
    icon: device_icons/ce8697597a426c7e15105220ba5c455d.png
  '0xf4ce36f9bfeeb1f8':
    friendly_name: Finestra Bagno -1
    icon: device_icons/ce8697597a426c7e15105220ba5c455d.png
  '0xf4ce3683b7ae660b':
    friendly_name: Finestra Dispensa
    icon: device_icons/ce8697597a426c7e15105220ba5c455d.png
  '0xa4c1380e4693d656':
    friendly_name: E.M. Frigo Taverna
    icon: device_icons/7f6be149e188b9d7b0fda29fb638249d.png
  '0x00124b002a9a73a2':
    friendly_name: RPT Dongle P
    icon: device_icons/3246337b3393ab837a1d83be05685c19.png
  '0xec1bbdfffea21998':
    friendly_name: Irrigazione Strada
    icon: device_icons/29ab6739745cd872912999ba4302d8ca.png
  '0x7cb03eaa0a07754c':
    friendly_name: Presa Esterna Strada
    icon: device_icons/1421cda56f9bab7f8ab6e504e036e3e0.png
  '0xa4c1388d42e0bd5f':
    friendly_name: Cancello
    icon: device_icons/ca7c84cdf297aaf8066adb7bd52b403d.png
  '0x00124b00226b528e':
    friendly_name: Cancelletto
    icon: device_icons/879e82a63045555a205e2e473785d39c.png
  '0x086bd7fffe5b723b':
    friendly_name: Luce Portico/Luce Esterna Est
    icon: device_icons/0f15f4d112b0ff96498f61e8ccce52a5.png
  '0xb43522fffe0adbf3':
    friendly_name: Dimmer Living
    icon: device_icons/36c972f318c6801ebb07c8b1dde874df.png
  '0x8c6fb9fffe1f1529':
    friendly_name: Sensore VALLHORN
    icon: device_icons/27dc30501ab148ff5b7c68982359344c.png
  '0x3c2ef5fffe4216d1':
    friendly_name: Sensore PARASOLL
    icon: device_icons/25e2fecb1c072822172bb0d30e24911a.png
  '0xec1bbdfffe3f9bf4':
    friendly_name: Dimmer Bagno D0
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0x00158d0008384979':
    friendly_name: Sensore Taverna
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0xf4ce36b9c30898ed':
    friendly_name: Luce Bagno D0
    icon: device_icons/2e7d2bcffe8472b4c41fbdc03d1da4cb.png
  '0xf4ce36dc388048a4':
    friendly_name: Luce Esterna Cucina
    icon: device_icons/752427e1ff0512e2f5ce68ed9e8885a2.png
  '0xf0d1b8000014acf0':
    friendly_name: Eket Bars W
    icon: device_icons/be80222ec606d2733b5db19ba8af2a24.png
  '0x7cb03eaa0a01beee':
    friendly_name: Albero di Natale
    icon: device_icons/1421cda56f9bab7f8ab6e504e036e3e0.png
  '0x8c6fb9fffe9e678f':
    friendly_name: Dimmer Sala Cinema
  '0x7cb03eaa0a025a09':
    friendly_name: Luci Oktoberfest
availability:
  enabled: false
  active:
    backoff: false
groups:
  '1':
    friendly_name: G. Disimpegno -1
  '2':
    friendly_name: G. Living
```
