### ISSUE TITLE
SONOFF TRVZB - climate.set_temperature also sets thermostat HVAC mode to heat

### ISSUE THREAD

**Issue by nocin** [Koenkk/zigbee2mqtt#27657]
### What happened?

Hi,

I noticed that the SONOFF TRV's are the only TRV's I have, that are turned on (HVAC mode heat) when setting the temperature by using `climate.set_temperature.`

Example: I have manually turned off my TRV's and I want them to stay off.
First thermostat is a TRV601, second the SONOFF TRVZB.

![Image](https://github.com/user-attachments/assets/fc6c3f4e-0018-4b36-b639-1ca94bf1567a)

Now, some automations are changing the target temperatures for my thermostats like this:

```YAML
action: climate.set_temperature
metadata: {}
data:
  temperature: 21
target:
  entity_id:
    - climate.0xa4c13832ba136190
    - climate.0xa4c138d8b8094f89
```
The temperatures are set successfully, but it also changes the HVAC mode to heat for the SONOFF TRV.

### What did you expect to happen?

I'm expecting that the thermostat stays off (HVAC mode off), when changing the temperature. But instead the SONOFF TRV's thermostats are turned on. This does not happen with other brands.

![Image](https://github.com/user-attachments/assets/a377155d-0cf8-47f3-b5d6-0e9202820ee7)

### How to reproduce it (minimal and precise)

Turn off the thermostat of your SONOFF TRV. Change the temperature via action `climate.set_temperature`. The corresponding thermostat will be set to heat, instead of staying off. 

### Zigbee2MQTT version

2.4.0

### Adapter firmware version

20240710

### Adapter

ZStack3x0

### Setup

Add-on on Home Assistant OS as Proxmox VM
