### ISSUE TITLE
unit_of_measurement for linkquality missing in HA

### ISSUE THREAD

**Issue by HA-TB303** [Koenkk/zigbee2mqtt#2806]
Improvement:

On all my sensors (hue, Ikea and Xiaomi) the unit_of_measurement value for linkquality (dB or % whatever is appropriate) is missing.

## Debug Info
zigbee2mqtt version: 1.9.0

![image](https://user-images.githubusercontent.com/9609805/72969544-f6ff4e80-3dc5-11ea-99ae-168134d180af.png)

It would be nice of you could add this.

**Comment by nanobra1n** [comment]
Link Quality Indicator (LQI) is the quality of the real data received in a signal.It ranges from 0 to 255, with 255 being the best quality. Therefore, there is no unit_of_measurement, as shown by the "-"

**Comment by HA-TB303** [comment]
Would it not still be perfectly possible to translate those values to a more consumer friendly 0-100 and make the unit of measurement ”%”

**Comment by nanobra1n** [comment]
Including this functionality into zigbee2mqtt is a philosophical question and beyond my pay grade. But if you really want this now, it's as easy as creating your own template sensor

```
sensor
  - platform: template
    sensors:
      linkqual:
        entity_id: sensor.yoursensor_linkquality
        unit_of_measurement: '%'
        friendly_name: 'My sensor link'
        value_template: '{{states.sensor.yoursensor_linkquality.state| float / 255 * 100}}'
        icon_template: mdi:wifi
```
Voila

**Comment by HA-TB303** [comment]
I know i could do that for my 18 sensors, but that's not what I’m asking 😏

**Comment by groenmarsmannetje** [comment]
Maybe just use “lqi” as unit. Besides that I would recommend to use device_class “signal_strength” as default class for all these Linkquality sensors. Currently I have to manually customize that each time.

**Comment by Koenkk** [comment]
@groenmarsmannetje done, unit will be `lqi` now and icon will be set to a signal icon now. Device class `signal_strength` cannot be used as according to the docs the unit has to be `dB` for this (https://www.home-assistant.io/integrations/sensor/#device-class)

**Comment by PedroLamas** [comment]
@Koenkk the dev build got broken after these changes, I assume the tests have failed?

**Comment by PedroLamas** [comment]
On a side note, I've asked on Home Assistant discord if there would be an interest in having a "lqi" device class of sorts!

**Comment by Koenkk** [comment]
@PedroLamas thanks, fixed the tests.

**Comment by PedroLamas** [comment]
This feels a bit unnecessary and kind of "hacky" to me...

All these sensors end on "_linkquality", so it was quite easy to configure them globally anyway with the `customize_glob.yaml` file:

```yaml
"*_linkquality":
  unit_of_measurement: 'lqi'
  icon: mdi:signal
```

You can check [here](https://github.com/PedroLamas/home-assistant-config/blob/011da3185cd3d475e43ccafec299fd18608cb91a/config/customize_glob.yaml) an example in my own configuration.
