### ISSUE TITLE
lag / delay, NOT related to mqtt (see post)

### ISSUE THREAD

**Issue by prankousky** [Koenkk/zigbee2mqtt#2814]
Hi everybody,

I am running `1.9.0` `
{'type': 'zStack3x0', 'meta': {'transportrev': 2, 'product': 1, 'majorrel': 2, 'minorrel': 7, 'maintrel': 1, 'revision': 20191106}}` on a `Texas Instruments CC1352P-2`.

Recently, **all** my light entities, and **most of** my climate entities have either *a lot* of delay, or *will not work at all*.

I use the `Eurotronic SPZB0001` zigbee thermostat as climate entities; my lights are some `innr` bulbs, some `philips hue`, a `philips aurora`, and some `aqara smart bulbs`. All of these devices are supported by `zigbee2mqtt` according to the official website.

zigbee2mqtt is connected to `Home Assistant` (version `0.104.3`) via `mqtt`. What really goes over my head is the fact that most sensors work immediately; let's say I open the office door... the entity in Home Assistant will turn to `open` right away! However, when I try to switch on my office light, nothing will happen. Home Assistant will display it as `on` after I switched it on, but then, after a few seconds, display it as `off` again. It ***might*** turn on eventually, or it might now. If it does, Home Assistant will display its state accordingly once this happened. 

However, below is my mqtt output. Unfortunately there is no timestamp, so I manually inserted estimated time values.

```
❯ msub zigbee2mqtt/Philips_Hue_01/#

zigbee2mqtt/Philips_Hue_01/availability online
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"} --- 16:42:10
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"} --- 16:42:50 (tried again)
zigbee2mqtt/Philips_Hue_01/set {"state": "OFF"} --- 16:42:52 (manually turned it back off)
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"} --- 16:43:10
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"} --- 16:45:00
zigbee2mqtt/Philips_Hue_01/availability online --- 16:49:30 (first time this came up since I subscribed to the lamp's topic)
```

The light is currently still off. This is usually the light that responds the fastest, so I used that one as an example. Of course now that I want to demo, it does not work at all. Even after it showing its availability as `online`, I am not able to control it!!

However, I can say that most lights work like this. The will eventually react to commands (not just on/off,  but also color/brightness changes), but this might happen between 20 seconds and 10 minutes (just to name a value; it can be multiple minutes...).

What could be the cause of this? Until recently, I did not have this issue. I recently updated both `zigbee2mqtt` as well as `Home Assistant`, but I am not sure this has anything to do with it... when I change anything in Home Assistant, it will display **right away** in the mqtt log, so it is being transmitted *to* zigbee2mqtt immediately. Why does it take zigbee2mqtt so long for the lights and climate entities to work? Sensor values will *usually* be transmitted as soon as they change. I am not sure for all sensors atm, but I am positive for door/window sensors, as I often test them when something is wrong. 

So communication between z2m and hass seems to be immediate. But still, lights and climate entities work very inconsistently. 

This is my configuration. I changed the values for `queue` as well as completely commented them out for testing (and always restarted afterwards)

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://url:1883'
  user: very_mqtt
  password: much_secret
  client_id: z2mbeelink
  include_device_information: true
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L430019B-if00
  disable_led: false
advanced:
  pan_id: my pan id
  network_key:
   - my network key
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: hass/status
  last_seen: ISO_8601_local
  elapsed: true
  report: true
  log_level: debug
  availability_timeout: 30
  cache_state: true
queue:
  delay: 350 #previously 250
  simultaneously: 100 # previously 15
ban:
  - '0x14b457fffe779019'
devices:
```
That did not make a difference at all.

# Really weird

When I restart the entire server running zigbee2mqtt, everything will work fine for a couple of minutes. When I switch a climate entity or light entity, it will work as expected: change to the newly set state right away. But after a few minutes, the lag is there again.

I have completely deactivated the `Home Assistant zigbee2mqtt map` addon, as I have read that it causes a lot of traffic. I have also connected my coordinator via USB extender cable to my server; it sits **outside** of my mini-rack, not inside. The antenna is around 2 meters away from the controller itself, as it's cable offered this much range. It has also worked like this just fine until recently.

As I have many automations that work with these light entities, I would like to get back to the state where there is no lag. It had worked fine previously, I did not (knowingly) change anything, yet suddenly this problem occurred and was there to stay.

Of course I can provide additional log files, information, etc.; please just let me know what helps to fix this and I'll post it :)

Here is another log for the same bulb from just now. As you can see, I have turned it on multiple times, but it reported its status as off. Then suddenly it turned on...

```
❯ msub zigbee2mqtt/Philips_Hue_01/#
zigbee2mqtt/Philips_Hue_01/availability online
zigbee2mqtt/Philips_Hue_01/set {"state": "OFF"}
zigbee2mqtt/Philips_Hue_01 {"state":"OFF","linkquality":54,"last_seen":"2020-01-24T17:01:26+01:00","brightness":189,"device":{"friendlyName":"Philips_Hue_01","model":"8718696449691","ieeeAddr":"0x0017880102a2d83f","networkAddress":53354,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":1,"hardwareVersion":1,"dateCode":"20170311","softwareBuildID":"1.23.0_r20156"}}
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"}
zigbee2mqtt/Philips_Hue_01 {"state":"OFF","linkquality":54,"last_seen":"2020-01-24T17:01:38+01:00","brightness":189,"device":{"friendlyName":"Philips_Hue_01","model":"8718696449691","ieeeAddr":"0x0017880102a2d83f","networkAddress":53354,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":1,"hardwareVersion":1,"dateCode":"20170311","softwareBuildID":"1.23.0_r20156"}}
zigbee2mqtt/Philips_Hue_01/set {"state": "ON"}
zigbee2mqtt/Philips_Hue_01 {"state":"ON","linkquality":54,"last_seen":"2020-01-24T17:02:04+01:00","brightness":189,"device":{"friendlyName":"Philips_Hue_01","model":"8718696449691","ieeeAddr":"0x0017880102a2d83f","networkAddress":53354,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":1,"hardwareVersion":1,"dateCode":"20170311","softwareBuildID":"1.23.0_r20156"}}
zigbee2mqtt/Philips_Hue_01 {"state":"ON","linkquality":54,"last_seen":"2020-01-24T17:02:15+01:00","brightness":189,"device":{"friendlyName":"Philips_Hue_01","model":"8718696449691","ieeeAddr":"0x0017880102a2d83f","networkAddress":53354,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":1,"hardwareVersion":1,"dateCode":"20170311","softwareBuildID":"1.23.0_r20156"}}

```

Thank you for your help

**Comment by dzungpv** [comment]
@prankousky try these setting for queue:
queue: 
delay: 40
simultaneously: 25

**Comment by prankousky** [comment]
Thank you @dzungpv 

This kinda works: when I toggle the lamp now, it will take about 25 seconds for it to react to the command. This is a big improvement, but still too slow. I will try playing around with those values more... but is there a general rule I can work with? 

For example, is simultaneously best set to a certain percentage of total devices? I have ~85 total, so is 25 good or should it be a higher/lower value? Same for delay, do either of those values have to do with the amount of devices, or is there another way to tweak it more without (what I will do now) trial and error?

**Comment by dzungpv** [comment]
@prankousky younhave 85 devices but rarely you turn it all on or off, so not the problem, the above setting work fine for me. Or you can change delay like 40 and simulate 85, it take only 3.4 seconds to process all.

**Comment by prankousky** [comment]
Thank you. Unfortunately, changing those options does not help. The lights now take between 15 - 25 seconds to change. Could something else in my configuration cause this? I have tried commenting differenting things out already, but nothing made a noticable difference as far as I can tell.

**Comment by dzungpv** [comment]
@prankousky so it relate to other problem of yours, i reply in difference issue, please check that.

**Comment by prankousky** [comment]
@dzungpv I replied in that thread (https://github.com/Koenkk/zigbee2mqtt/issues/2705#issuecomment-578389345). Just a quick summary if somebody found this one via search: the 15-25 seconds delay *was* gone yesterday; however, this was **merely** due to restarting zigbee2mqtt. A few hours after the last restart, the lag was incredibly high again.

So this likely does not have anything to do with the `queue` section in the configuration.yaml.

**Comment by Koenkk** [comment]
The queue settings are not used anymore.

Try removing availability_timeout from your configuration.yaml, as the bigger the networks gets, the more stress it will put on it.

**Comment by prankousky** [comment]
Thank you @Koenkk 

This is my updated `configuration.yaml`. After I just now restarted, the lights took about 30 seconds to react to any command (switch on/off, color change). Do you know what could cause this delay to grow according to the amount of time zigbee2mqtt is running? It always works best after a restart, then lag expands. And since just a few weeks ago there was **almost no lag at all**, I know that both hardware and software a capable of working faster than they do at the moment.

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://ip:1883'
  user: my_user
  password: actual_password
  client_id: z2mbeelink
  include_device_information: true
serial:
    port: null # changed to this to auto-detect the correct port, as the CC1352P-2 will show up as two different devices (according to official documentation)
  disable_led: false
advanced:
  pan_id: #
  network_key: #
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: hass/status
  last_seen: ISO_8601_local
  elapsed: true
  report: true
  log_level: debug
  cache_state: true
```
