### ISSUE TITLE
Eurotronic Spirit Zigbee SPZB0001 manual config

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#2823]
# Bug Report
## What happened
home assistant + zigbee2mqtt + Eurotronic Spirit Zigbee SPZB0001
I tried to configure the SPZB0001 manual according to documentation
https://www.zigbee2mqtt.io/devices/SPZB0001.html#manual-home-assistant-configuration

I created a file "thermostat_eurotronic_spirit_zigbee_r01.yaml" in "hassio/homeassistant/packages":

```
# ===============================================
# Manual Home Assistant configuration #
# ===============================================
climate:
  - platform: "mqtt"
    name: "R01"
    availability_topic: "zigbee2mqtt/bridge/state"
    min_temp: "10"
    max_temp: "26"
    modes: 
      - "off"
      - "auto"
      - "heat"
    mode_state_topic: true
    mode_state_template: "{{ value_json.system_mode }}"
    mode_command_topic: true
    current_temperature_topic: true
    current_temperature_template: "{{ value_json.local_temperature }}"
    temperature_state_topic: true
    temperature_state_template: "{{ value_json.current_heating_setpoint }}"
    temperature_command_topic: "current_heating_setpoint"
    temp_step: 0.5
    action_topic: true
    action_template: "{{ value_json.operation }}"

sensor:
  - platform: "mqtt"
    name: "R01 battery"
    state_topic: "zigbee2mqtt/0x00158d0001ff8bca"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

sensor:
  - platform: "mqtt"
    name: "R01 linkquality"
    state_topic: "zigbee2mqtt/0x00158d0001ff8bca"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"


# ===============================================
# GROUPS
# ===============================================
group:
# -------------------------------------------
  group_hvac_eurotronic_r01:
    name: "R01 Eurotronic"
    control: hidden
    entities:
    - climate.r01_climate
    - sensor.r01_battery
    - sensor.r01_linkquality

```

## What did you expect to happen
...fully working lovelace card(s)

But in lovelace automode, I get
![2020-01-25_21-27-00](https://user-images.githubusercontent.com/10470708/73126956-9cc6df00-3fb9-11ea-9bc8-7abde49018e1.png)

where
1. manual config
2. automatic config (discovery)

## Question:
How can I configure my TRV manual with all functionality?
Can this be done with multiple TRV's?
In the "climate" tag in the yaml file, I can't find a reference to the zigbee-topic of the device... (in my case: zigbee2mqtt/0x00158d0001ff8bca)

## Debug Info
home assistant: hassio in docker on RPI3
zigbee2mqtt version: 1.8.0-dev
CC253X firmware version: 20190608
