### ISSUE TITLE
Log filename

### ISSUE THREAD

**Issue by svh1985** [Koenkk/zigbee2mqtt#2889]
Hi there,

I want to request an enhancement for the log settings. It is to allow to set the name of the log file.

Something like:
```
  log_level: info
  log_directory: /var/log/
  log_filename: zigbee2mqtt.log # also allowes zigbee2mqtt_%TIMESTAMP%.log
  log_output:
    - console
    - file
```

This gives some extra flexibility for the log file. Especially handy for external log rotate scrips.

I looked at the code and I think I'll be able to create a PR. Love to hear your feedback and suggestions.
