### ISSUE TITLE
Can't pair anything

### ISSUE THREAD

**Issue by Jeoffreybauvin** [Koenkk/zigbee2mqtt#2914]
Hi there,

I have a major issue with Zigbee2mqtt. 

This was my Zigbee map last night :

![unknown](https://user-images.githubusercontent.com/701928/74083370-9f1e4400-4a63-11ea-93bd-707675e3f39b.png)

And my configuration file  : 

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://broker:8883'
  ca: /opt/zigbee2mqtt_ssl/ca.crt
  key: /opt/zigbee2mqtt_ssl/zigbee2mqtt.key
  cert: /opt/zigbee2mqtt_ssl/zigbee2mqtt.crt
advanced:
  log_level: debug
  network_key:
...
serial:
  port: /dev/ttyACM0
```

All my sensors worked fine. I tried to plug new devices : 

- Ikea Bulb (LED1623G12)
- Ikea plug wall (E1603/E1702)
- Xiaomi Motion Sensor (RTCGQ11LM)

I was not able to pair any of these devices. Nothing in z2mqtt's logs :(. 

The coordinator is a ready2use CC2531 with antenna from h4nc. 

So I took an old CC2531, and flashed it as a router (CC2531_router_2019_02).  Again, nothing in log file.
 
I decided to start from scratch : 

- Stop z2mqtt
- Delete state.json, database.db,  all devices in configuration file
- Start zigbee2mqtt

Now,  I only have my coordinator. I'm trying to pair my CC2531 router : nothing in log file, again. 

My router is blinking red, but I don't see it in z2mqtt...

I'm not sure what to do now...  I though I'll pair all my routers before pairing any  end device...

Any ideas ?

Regards,
