### ISSUE TITLE
`debounce` in default `device_options` doesn't seem to be honnered

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3004]
# Bug Report
## What happened
To cleanup my `configuration.yaml` a bit I moved my default `retain` and `debounce` value to the default `device_options` block.

Those settings are no longer applied!
```
zigbee2mqtt:info  2020-02-26 15:37:45: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.06,"linkquality":47,"humidity":56.98,"pressure":1002,"battery":91,"voltage":2985}'
zigbee2mqtt:info  2020-02-26 15:37:45: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.06,"linkquality":47,"humidity":58.22,"pressure":1002,"battery":91,"voltage":2985}'
zigbee2mqtt:info  2020-02-26 15:37:45: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.06,"linkquality":49,"humidity":58.22,"pressure":1002.3,"battery":91,"voltage":2985}'
zigbee2mqtt:info  2020-02-26 15:40:57: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.58,"linkquality":47,"humidity":58.22,"pressure":1002.3,"battery":91,"voltage":2985}'
zigbee2mqtt:info  2020-02-26 15:40:57: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.58,"linkquality":47,"humidity":56.74,"pressure":1002.3,"battery":91,"voltage":2985}'
zigbee2mqtt:info  2020-02-26 15:40:57: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor', payload '{"temperature":19.58,"linkquality":47,"humidity":56.74,"pressure":1002.3,"battery":91,"voltage":2985}'
```

## What did you expect to happen
`retain` and `debounce` to still be applied.

## How to reproduce it (minimal and precise)
```yaml
device_options:
  debounce: 1
  retain: true
devices:
  '0x000d6ffffe8e8d4f':
    friendly_name: masterbedroom/repeater
    debounce: 0
    retain: false
  '0x90fd9ffffee77fcf':
    friendly_name: bedroom/night_light/bulb
  '0x0017880104259333':
    friendly_name: bedroom/desk_lamp/bulb
  '0x14b457fffecc1315':
    friendly_name: bedroom/night_light/remote
    debounce: 0
    retain: false
  '0x14b457fffeca351b':
    friendly_name: bedroom/desk_lamp/remote
    debounce: 0
    retain: false
  '0x00158d0004148f89':
    friendly_name: bedroom/motion
  '0x00158d00033ddfaa':
    friendly_name: bedroom/sensor
  '0x00158d0003f115c5':
    friendly_name: serverroom/sensor
  '0x00158d0001ffaffc':
    friendly_name: bedroom/radiator
    debounce: 2.5
  '0x04cf8cdf3c771820':
    friendly_name: bedroom/light_sensor
```

I would expect my aqara sensors to have a default debounce of 1 second, they do not. Setting `debounce: 1` for both '/sensor' devices directly works as expected.

## Debug Info
zigbee2mqtt version: 1.10+dev
CC253X firmware version: n/a
