### ISSUE TITLE
Error Starting Zigbee2mqtt on Docker (Synology).

### ISSUE THREAD

**Issue by aptonline** [Koenkk/zigbee2mqtt#305]
I have a newly flashed CC253X (unsure of firmware as was suppled to me) and initially the device did pickup a Tradfri bulb using the latest docker on my Synology but now I am seeing the following error:

```
Using '/app/data' as data directory
zigbee2mqtt@0.1.3 start /app
node index.js
zigbee2mqtt:info 2018-8-24 16:04:34 Logging to directory: '/app/data/log/2018-08-24.16:04:33'
zigbee2mqtt:info 2018-8-24 16:04:43 Starting zigbee2mqtt version 0.1.3 (commit #c8c8417)
zigbee2mqtt:info 2018-8-24 16:04:43 Starting zigbee-shepherd
zigbee2mqtt:info 2018-8-24 16:04:46 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
zigbee2mqtt:info 2018-8-24 16:05:46 Starting zigbee-shepherd
zigbee2mqtt:error 2018-8-24 16:05:49 Error while starting zigbee-shepherd!
zigbee2mqtt:error 2018-8-24 16:05:49 Press the reset button on the stick (the one closest to the USB) and start again
zigbee2mqtt:error 2018-8-24 16:05:49 Failed to start
{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/cc
```

I've been led to believe this is a firmware issue on the stick and it needs updating.  Can some one confirm this is the case? as I don't have the debugger and cables I need to look at getting this updated from my source or purchased the relevant hardware but would like to know before hand.

This is my config my Zigbee2mqtt:

```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: homeassistant
  # MQTT server URL
  server: 'mqtt://192.168.1.12'
  # MQTT server authentication, uncomment if required:
  user: *********
  password: *********

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
```
