### ISSUE TITLE
How do I get the devices to show up in Homeassistant?

### ISSUE THREAD

**Issue by burton666** [Koenkk/zigbee2mqtt#3153]
I just recieved my zigbee2mqtt hardware and managed to flash the software to it. I am running unraid and have installed the zigbee2mqtt, mosquitto and homeassistant dockers. 

I started all with default configurations just adding "homeassistant:true" in the zigbee2mqtt configuration. If I look at the mosquitto log I see "client connected..." and when I try to add zigbee devices they all show up in the log of the zigbee2mqtt-docker.
But I have never used used mqtt before so I am a little confused of how it should work. I added: 
"mqtt:
  discovery: true
  discovery_prefix: homeassistant
"
to the home assistant configuration, but I can't see any devices show up. I guess that I have missed something but I don't understand what to do.

**Comment by dfsx1** [comment]
See documentation here:
https://www.zigbee2mqtt.io/integration/home_assistant.html

In your Zigbee2mqtt configuration.yaml set homeassistant: true
In your Home Assistant configuration.yaml:
```
mqtt:
  discovery: true
  broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
