### ISSUE TITLE
error in documentation?

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#3237]
On 
https://www.zigbee2mqtt.io/devices/SPZB0001.html

I found
```
climate:
  - platform: "mqtt"
    availability_topic: "zigbee2mqtt/bridge/state"
    min_temp: "5"
    max_temp: "30"
    modes: 
      - "off"
      - "auto"
      - "heat"
    mode_state_topic: true
    mode_state_template: "{{ value_json.system_mode }}"
    mode_command_topic: true
    current_temperature_topic: true
    current_temperature_template: "{{ value_json.local_temperature }}"
    temperature_state_topic: true
    temperature_state_template: "{{ value_json.current_heating_setpoint }}"
    temperature_command_topic: "current_heating_setpoint"
    temp_step: 0.5
    action_topic: true
    action_template: "{{ value_json.operation }}"

```

Hower, that didn't work for me.
I had to modify
```
    mode_state_topic: true
    mode_command_topic: true
    current_temperature_topic: true
    temperature_state_topic: true
    temperature_command_topic: "current_heating_setpoint"
```

to address explicitly the device topics, i.e.:

```
climate:
  - platform: "mqtt"
    unique_id: "0x00158d00053d404d"
    name: "0x00158d00053d404d"
    availability_topic: "zigbee2mqtt/bridge/state"
    min_temp: "5"
    max_temp: "30"
    modes:
      - "off"
      - "auto"
      - "heat"

    # modus (uit/auto/aan)
    mode_state_topic: "zigbee2mqtt/0x00158d00053d404d"
    mode_state_template: "{{ value_json.system_mode }}"
    mode_command_topic: "zigbee2mqtt/0x00158d00053d404d/set/system_mode"

    # huidige temperatuur
    current_temperature_topic: "zigbee2mqtt/0x00158d00053d404d"
    current_temperature_template: "{{ value_json.local_temperature }}"

    # gewenste temperatuur
    temperature_state_topic: "zigbee2mqtt/0x00158d00053d404d"
    temperature_state_template: "{{ value_json.current_heating_setpoint }}"
    temperature_command_topic: "zigbee2mqtt/0x00158d00053d404d/set/current_heating_setpoint"

    temp_step: 0.5

    action_topic: "zigbee2mqtt/0x00158d00053d404d/set"
    action_template: "{{ value_json.operation }}"

```
