### ISSUE TITLE
Docker-compose does not recognize device

### ISSUE THREAD

**Issue by MartijndeHeus** [Koenkk/zigbee2mqtt#3268]
# Bug Report
## What happened
When I run the service as part of a docker-compose it does not recognize my device. I can run Zigbee2mqtt when I clone the repo using npm start. I get the following error when using docker-compose: 
```
zigbee2mqtt:error 2020-04-01 18:27:16: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/tty.usbmodem14501
```

## What did you expect to happen
Zigbee2mqtt start normally, similar to when I run it using the original project.

## How to reproduce it (minimal and precise)
Flash the CC2531, plug it in a USB-C adaptor, run docker-compose:

```
zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        volumes: 
            - ./zigbee2mqtt-data/:/app/data/
        devices:
            - /dev/tty.usbmodem14501
        privileged: true
```

I do also have ```/dev/tty.usbmodem14501``` in my ```configuration.yaml```.

## Debug Info
zigbee2mqtt version: 1.12.0
CC253X firmware version: CC2531_DEFAULT_20190608
