### ISSUE TITLE
adding orvibo T11W1LZ single switch

### ISSUE THREAD

**Issue by ARoozitalab** [Koenkk/zigbee2mqtt#3325]
hi i want to add orvibo t11w1lz single switch to zigbee2mqtt

in debug mode i can see :
```
zigbee2mqtt:debug 2020-04-10 11:55:04: Received Zigbee message from '0x00124b000adca903', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0
zigbee2mqtt:warn  2020-04-10 11:55:04: Received message from unsupported device with Zigbee model '374b2e283a7147609956d4412615afc0'
zigbee2mqtt:warn  2020-04-10 11:55:04: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-04-10 11:55:23: Device '0x00124b000adca903' announced itself
zigbee2mqtt:info  2020-04-10 11:55:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b000adca903"}}'
zigbee2mqtt:debug 2020-04-10 11:55:29: Received Zigbee message from '0x00124b000adca903', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0
zigbee2mqtt:warn  2020-04-10 11:55:29: Received message from unsupported device with Zigbee model '374b2e283a7147609956d4412615afc0'
zigbee2mqtt:warn  2020-04-10 11:55:29: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

i added follow codes to device.js

```
{
    zigbeeModel: ['374b2e283a7147609956d4412615afc0'],
    model: 'T11W1LZ',
    vendor: 'Orvibo',
    description: 'swith 1 state', 
    supports: 'on/off', 
    fromZigbee: [], 
    toZigbee: [tz.on_off],
        ep: (device) => {
            return {'1': 1};
        }
},

```
and added follow command to hassio configuration.yaml

```
switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/0x00124b000adca903"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/0x00124b000adca903/1/set"



sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/0x00124b000adca903"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
```

but I have this error in my logs
`zigbee2mqtt:error 2020-04-10 13:34:36: Publish 'set' 'state' to '0x00124b000adca903' failed: 'TypeError: Cannot read property 'command' of undefined'`

I am new with zigbee2mqtt and I read this page 
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
but I can't understand how should I solve my problem

thanks
