### ISSUE TITLE
Can not create group for IKEA switch (and light bulb)

### ISSUE THREAD

**Issue by brean** [Koenkk/zigbee2mqtt#3326]
# Bug Report
I wanted to setup a group of my IKEA light switch and bulb, but it fails at startup.
I can however see and control light bulb and switch in home assistant using zigbee2mqtt

## What happened
When starting I see this error message:
`zigbee2mqtt:error 2020-04-10 16:49:04: Failed to call 'Groups' 'onZigbeeStarted' (Error: Command 0xd0c.../1 genGroups.add({"groupid":1,"groupname":""}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)`

## What did you expect to happen
Both devices should end up in a group, so when I press the switch the light should toggle.

## How to reproduce it (minimal and precise)
My configuration.yaml:
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt'
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
devices:
  '0xd0c...':
    friendly_name: 'living_room_switch'
  '0x90...':
    friendly_name: 'living_room_light_back'
    
groups:
  # ID, each group should have a different numerical ID
  '1':
    # Required: Name which will be used to control the group
    friendly_name: group_1
    # Required: Retain messages (true/false) (default: false)
    devices:
      - '0xd0c...'
      - '0x90...'
```

Docker-compose file and additional config at https://github.com/brean/docker-compose-hass

## Debug Info
zigbee2mqtt version: 1.12.2 (commit #7d27a54) (using docker)
CC253X firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
