### ISSUE TITLE
Centralite 3157100 doesnt create climate entity

### ISSUE THREAD

**Issue by YamiFrankc** [Koenkk/zigbee2mqtt#3478]
Hello, I just installed this Centralite Pearl thermostat to my house. It controls my AC ok and is paired to my zigbee network. But it is not interfacing well with zigbee. It creates a battery and link quality sensor, but does not create the temperature sensor, and climate and fan entities that ( I think) it is supposed to create so I can control it from HA. 

# Bug Report

Centralite Pearl thermostat does not create all entities needed to work.
## What happened
I paired the thermostat and only the battery and link quality sensors where automatically created(auto discover) I tried to manually add the device as explained [here](https://www.zigbee2mqtt.io/devices/3157100.html), but it does not work either.

## What did you expect to happen
For it to automatically create the climate and fan control entities, and also a temperature sensor.

## How to reproduce it (minimal and precise)
Join device to zigbee network.

## Debug Info
Zigbee2mqtt version:  1.13.0
Adapter hardware: CC2531
Adapter firmware version: 20190608 

[Log ](https://hastebin.com/dupeguyive.sql)

**Comment by YamiFrankc** [comment]
Hello, based on issue #3237 , I modified the climate entity in my config.yaml a little bit.
Now I have a climate entity that reports the state of the thermostat (temperature, operation mode), but I still cant control the device from HA. What other change do I need to make?

```
climate:
  - platform: "mqtt"
    unique_id: "0x000d6f000b4cbce7"
    name: "TEST"
    availability_topic: "zigbee/bridge/state"
    min_temp: "10"
    max_temp: "30"
    modes: 
      - "off"
      - "auto"
      - "heat"
      - "cool"
    mode_state_topic: "zigbee/0x000d6f000b4cbce7"
    mode_state_template: "{{ value_json.system_mode }}"
    mode_command_topic: "zigbee/0x000d6f000b4cbce7"
    current_temperature_topic: "zigbee/0x000d6f000b4cbce7"
    current_temperature_template: "{{ value_json.local_temperature }}"
    temperature_low_state_topic: "zigbee/0x000d6f000b4cbce7"
    temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
    temperature_high_state_topic: "zigbee/0x000d6f000b4cbce7"
    temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
    temperature_low_command_topic: "occupied_heating_setpoint"
    temperature_high_command_topic: "occupied_cooling_setpoint"
    temp_step: 1
    action_topic: "zigbee/0x000d6f000b4cbce7"
    action_template: "{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}"
    fan_modes: 
      - "auto"
      - "on"
    fan_mode_command_topic: "zigbee/0x000d6f000b4cbce7"
    fan_mode_state_topic: "zigbee/0x000d6f000b4cbce7"
    fan_mode_state_template: "{{ value_json.fan_mode }}"
```
