### ISSUE TITLE
Xiaomi curtain position

### ISSUE THREAD

**Issue by trdb33** [Koenkk/zigbee2mqtt#3511]
Hello I'm using zigbee2mqtt with a lot with Xiaomi products, and noticed that the Xiaomi Curtain is reporting his position only when it's triggered, the state of the curtain is unknown after each Hass reboot and curtain automation can't be triggered since I'm using curtain position in automations conditions
I don't think the Zigbee2mqtt and hass versions are important because I have the probleme for more than four months with a lot of updates
To sum : Hass don't know curtain position after each reboot

I hope the issue is clear, thank you ;)

**Comment by Koenkk** [comment]
Make sure to correctly setup according to https://www.zigbee2mqtt.io/integration/home_assistant.html#mqtt-discovery

**Comment by trdb33** [comment]
Hey I added 
```
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
to mqtt section and now the issue is resolved, thank you ;)
