### ISSUE TITLE
[feature request] Binary sensors invert option

### ISSUE THREAD

**Issue by to4ko** [Koenkk/zigbee2mqtt#3569]
# Feature request
## What happened
Would be handful to be able to have option to invert logic of binary sensors logic (like door\window ones) thru devices.yaml

Will help to avoid creation of unnecessary entities in software like HA.

## What did you expect to happen
Be able to invert binary logic
## Debug Info
Zigbee2mqtt version: 1.13
Adapter hardware: CC2538

**Comment by Koenkk** [comment]
Similar to #3541 this can be done with:

```yaml
device_options:
  homeassistant:
    occupancy:
      payload_on: false
      payload_off: true
```
