### ISSUE TITLE
Turning group off sets brightness to 1

### ISSUE THREAD

**Issue by olemagnp** [Koenkk/zigbee2mqtt#3857]
# Bug Report
## What happened
I have set up five IKEA Trådri bulbs in a group, and bound the group to a Trådfri remote. However, when I turn the group off using Zigbee2mqtt (either by manually publishing the command or through home assistant), all bulbs gets their brightness set to 0 in addition to setting "state": "OFF", before all of them update to "brightness": 1.

Turning the group back on using Z2M works as expected (the previous brightness is returned), however if I try turning them on using the bound remote, the lights turn on at the lowest brightness. This only happens when turning the group off using Z2M, turning each bulb off separately and then turning them on using the remote works as expected.

## What did you expect to happen
Turning the group off using Z2M then on using bound remote should set the lights to their previous brightness

## How to reproduce it (minimal and precise)
1. Create a group consisting of lights
2. Bind remote to group
3. Turn group off using Z2M
4. Turn group on using bound remote

## Debug Info
Zigbee2mqtt version: 1.14.1-dev (Docker, latest-dev)
Adapter hardware: CC26X2R1
Adapter firmware version: zStack3x0, majorrel: 2, minorrel: 7, maintrel: 1

Debug log: https://hastebin.com/uhokebubun.sql

Group config:
```yaml
groups:
  '1':
    friendly_name: Living Room
    retain: false
    optimistic: true
    devices:
      - '0x000d6ffffe016f8e'
      - '0x14b457fffe42bcf5'
      - '0x14b457fffe44431e'
      - '0x14b457fffe444a7c'
      - '0x14b457fffe4aa34d'
```
