### ISSUE TITLE
Tradfri LED1624G9 doesn't report color

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee2mqtt#3923]
# Bug Report
## What happened
When changing color on the bulb via a bound E1524 remote (5-button puck), the colors are not getting reported back to homeassistant. According to [the docs](https://www.zigbee2mqtt.io/information/report.html) this should work, the relevant portion of my configuration.yaml is as follows
```yaml
advanced:
  report: true
devices:
  '0x000b57fffe39eb73':
    friendly_name: Remote
  '0xd0cf5efffe2357cd':
    friendly_name: Couch_1
    transition: 0.5
  '0xd0cf5efffe2d3b55':
    friendly_name: Couch_2
    transition: 0.5
  '0xd0cf5efffe292755':
    friendly_name: Couch_3
    transition: 0.5
groups:
  '901':
    friendly_name: Couch
    retain: false
    optimistic: true
    transition: 0.5
    devices:
      - 0xd0cf5efffe2357cd/1
      - 0xd0cf5efffe2d3b55/1
      - 0xd0cf5efffe292755/1
```
## What did you expect to happen
The bulb state would reflect x/y color coords. The bulb state updates power state, brightness, but not x/y color coords
## How to reproduce it (minimal and precise)
Press left or right on the puck to change group color
## Debug Info
Zigbee2mqtt version: 1.14.1 (tried 1.14.1-dev, no difference)
Adapter hardware: CC2531
Adapter firmware version: 20190608
