### ISSUE TITLE
Using state: toggle to turn on doesn't set brightness

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee2mqtt#3948]
# Bug Report
## What happened
When using 
```json
{ "state" : "toggle" }
```
on a bulb (an Ikea TRADFRI bulb E27 WS opal 980lm on fw 2.3.050 in this case), z2mqtt sets the brightness to 0 regardless if the new state is off or on. Also, after turning it off with toggle, setting the state via "state": "on" does nothing, because zigbee2mqtt" remembers the brightness is set to 0, which effectively means the bulb should be off. This now applies to "toggle" as well. Because of this, one needs to first set the brightness > 0 to effectively turn the bulb back on, and restore normal operation
## What did you expect to happen
Using toggle to turn back on the bulb should restore brightness

## How to reproduce it (minimal and precise)
Turn the bulb off using "state": "toggle", then back on.
## Debug Info
Zigbee2mqtt version: 1.14.1
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
- Do you have a default `transition` specified? 
- Can you share your `configuration.yaml`?
- Can you provide the herdsman debug logging of this issue?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by elfhack** [comment]
@Koenkk 
transition - indeed I do, 0.5 for lights
configuration.yaml:
```
advanced:
  report: true
  log_output:
    - console
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto.homeassistant'
permit_join: false
serial:
  port: /dev/zigbee
  disable_led: true
devices:
  '0x000b57fffe396706':
    friendly_name: Kitchen_Remote
  '0x000b57fffe39eb73':
    friendly_name: Couch_Remote
  '0x000b57fffe368edd':
    friendly_name: Bedroom_Remote
  '0x00124b001e728db4':
    friendly_name: Kitchentop
    retain: true
  '0x000b57fffedbd90c':
    friendly_name: Kitchen
    retain: true
    transition: 0.5
groups: {}
```
herdsman logs attached, as there's too much of it. The moment you're looking for is when there's a toggle, then an off, then an on.
[z2m.txt](https://github.com/Koenkk/zigbee2mqtt/files/4955548/z2m.txt)
