### ISSUE TITLE
Zigbee2mqtt stops responding randomly on CC26X2R1 stick 

### ISSUE THREAD

**Issue by cvhoang** [Koenkk/zigbee2mqtt#4060]
# Bug Report

Zigbee2mqtt randomly stops every few days. Log file shows `SRSP - AF - dataRequest after 6000ms` error message.
The only way to get it working again is pressing the reset button new USB adapter and restart Z2M container.

## What did you expect to happen
No random crashes.

## How to reproduce it (minimal and precise)
Runs Z2M on CC26X2R1 with a large number of devices (~100) for a period of time.

## Debug Info
Zigbee2mqtt version: 1.14.1 
Adapter hardware: CC26X2R1
Adapter firmware version: 20200417

## More information

I'm currently running Z2M in Docker on Intel NUC with around 90 devices.

My devices are mostly Hue lights, sensors, Samsung Smart Plugs and Xiaomi sensors. I previously ran Conbee II stick. It was really stable but I migrated because I think Z2M is the future.

configuration.yaml:
```
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.13__Embed_with_CMSIS-DAP_L11008CR-if00
```

docker-compose.yaml:

```
  zigbee2mqtt:
    container_name: z2m
    volumes:
      - /opt/docker/zigbee2mqtt:/app/data
      - /opt/zigbee2mqtt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
      - /opt/zigbee2mqtt/homeassistant.js:/app/lib/extension/homeassistant.js
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.13__Embed_with_CMSIS-DAP_L11008CR-if00
    environment:
      - TZ
    image: koenkk/zigbee2mqtt
    restart: always
```
