### ISSUE TITLE
Support for Develco KEPZB-110 alarm keypad

### ISSUE THREAD

**Issue by alekslyse** [Koenkk/zigbee2mqtt#4106]
I got a Develco KEPZB-110 keypad (alarm keypad) and was hoping to fully support a proper alarm keypad in z2m. I got the regular arm to work, but the buttons (1234567890 and code 1234) all report as unknown. Is it an easy method to implement an alarm panel as I cant see many examples of code and keypad entry in other devices.

I made the device with the standard alarm and that works fine, and attached the pcap. 0x4383 is the alarm panel. Default z2m network code

`{ zigbeeModel: ['KEPZB-110'],
        model: 'KEPZB-110',
        vendor: 'Develco',
        description: 'Alarm Panel',
        supports: '',
        fromZigbee: [fz.ias_sos_alarm_2, fz.battery, fz.command_arm, fz.command_emergency],
        toZigbee: [],
    }`

[alarmpanel.pcapng.zip](https://github.com/Koenkk/zigbee2mqtt/files/5075948/alarmpanel.pcapng.zip)

**Comment by alekslyse** [comment]
Also full specs here. Can this help? https://www.elektroimportoren.no/docs/lib/4514807-Manual-18.pdf

**Comment by Koenkk** [comment]
You can probably use https://github.com/Koenkk/zigbee-herdsman-converters/pull/1301 as a starting point

**Comment by ioull** [comment]
I do my first integration of the alarm panel / keypad KEPZB-110 from Develco/Frient :
Here is the code :
https://gist.github.com/ioull/25334cfcc78b920ecc1c8f8828cd3c90
Key and LEDs are working fine ! The only knowing 'bug' I have is that when there is a tamper detection, I'm not able to clear it ... Any Idea ?
As it is my first z2m integration, keep free to make remarks, I'm interrested to progress !!!
The last things not tested is the battery level ! I'm waiting the message from the device 😉

**Comment by heinekmadsen** [comment]
@ioull I've got my hands on one of these keypads... i see using a code is working and i can see it in the Home Assistant events... but when scanning a rfid card it beeps, but i can't really see any unique code/identifier of which card was beeped in the events... Do you have it working when swiping a card?

**Comment by ioull** [comment]
Very strange that it works with the code and not with rfid ... Indead it takes the same way, the only difference is that an rfid tag start with a '+' ... Are you sure you use a suppoorted RFID TAG ?
Just to be sure, you have to swipe the card (or enter a code), then push an action button in order to generate the event.

**Comment by heinekmadsen** [comment]
@ioull sorry... guess it was just me and my eyes :)

How do you handle the events with HA? Do you use node red to catch the state_changed events? and how do you check which card is read/or code is read?

**Comment by ioull** [comment]
I handle it throw a workflow in NodeRed. Here is how I manage it in order to set the led status 
```
[
    {
        "id": "6814538862850eec",
        "type": "tab",
        "label": "Flow 1",
        "disabled": true,
        "info": "",
        "env": []
    },
    {
        "id": "adde1e9caf7b8d23",
        "type": "mqtt in",
        "z": "6814538862850eec",
        "name": "ENT_TEL_keypad",
        "topic": "zigbee2mqtt/ENT_TEL_keypad",
        "qos": "1",
        "datatype": "json",
        "broker": "9b372184.f0e1a",
        "nl": false,
        "rap": false,
        "inputs": 0,
        "x": 130,
        "y": 200,
        "wires": [
            [
                "79919fbee76170db"
            ]
        ]
    },
    {
        "id": "68f2d041a7a0c77b",
        "type": "mqtt out",
        "z": "6814538862850eec",
        "name": "ENT_TEL_keypad",
        "topic": "zigbee2mqtt/ENT_TEL_keypad/set",
        "qos": "1",
        "retain": "false",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "9b372184.f0e1a",
        "x": 690,
        "y": 160,
        "wires": []
    },
    {
        "id": "c93878364358f080",
        "type": "function",
        "z": "6814538862850eec",
        "name": "Parse topic",
        "func": "const codes = [\n    '1234',\n    '+1122AABB'\n];\n\naction = msg.payload.action;\naction_code = msg.payload.action_code;\naction_transaction = msg.payload.action_transaction;\nif(action == 'disarm' && !codes.includes(action_code))\n{\n   action = 'invalid_code';\n}\nmsg.payload = '{\"arm_mode\":{\"mode\":\"'+action+'\",\"transaction\":'+action_transaction+'}}';\nmsg.alarmAction = action;\nmsg.code = action_code;\n\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 200,
        "wires": [
            [
                "68f2d041a7a0c77b",
                "8e18454d16948f05"
            ]
        ]
    },
    {
        "id": "79919fbee76170db",
        "type": "switch",
        "z": "6814538862850eec",
        "name": "action ?",
        "property": "payload.action",
        "propertyType": "msg",
        "rules": [
            {
                "t": "nempty"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 320,
        "y": 200,
        "wires": [
            [
                "c93878364358f080"
            ]
        ]
    },
    {
        "id": "8e18454d16948f05",
        "type": "switch",
        "z": "6814538862850eec",
        "name": "",
        "property": "alarmAction",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "disarm",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "invalid_code",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "emergency",
                "vt": "str"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 4,
        "x": 650,
        "y": 260,
        "wires": [
            [],
            [],
            [],
            []
        ]
    },
    {
        "id": "9b372184.f0e1a",
        "type": "mqtt-broker",
        "name": "mqttIoull",
        "broker": "192.168.10.9",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": true,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": ""
    }
]
```

**Comment by heinekmadsen** [comment]
So you use this to set the LED status’ on the keypad? How do you control them? Mine just stay turned off

**Comment by ioull** [comment]
Did you try my flow ? It manage the keypad LEDs. The code 1234 will activate the alarm

**Comment by heinekmadsen** [comment]
Well… I do see the yellow led flashing when using an invalid code…
Is it possible to also flash the green and red leds as pr. Technical manual?

According to the technical manual
***@***.***

**Comment by ioull** [comment]
Oh sorry I forgot the part I update the status after alarm is armed. Here is the updated flow :

``` yaml
[
    {
        "id": "6814538862850eec",
        "type": "tab",
        "label": "Flow 1",
        "disabled": true,
        "info": "",
        "env": []
    },
    {
        "id": "adde1e9caf7b8d23",
        "type": "mqtt in",
        "z": "6814538862850eec",
        "name": "ENT_TEL_keypad",
        "topic": "zigbee2mqtt/ENT_TEL_keypad",
        "qos": "1",
        "datatype": "json",
        "broker": "9b372184.f0e1a",
        "nl": false,
        "rap": false,
        "inputs": 0,
        "x": 130,
        "y": 200,
        "wires": [
            [
                "79919fbee76170db"
            ]
        ]
    },
    {
        "id": "68f2d041a7a0c77b",
        "type": "mqtt out",
        "z": "6814538862850eec",
        "name": "ENT_TEL_keypad",
        "topic": "zigbee2mqtt/ENT_TEL_keypad/set",
        "qos": "1",
        "retain": "false",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "9b372184.f0e1a",
        "x": 690,
        "y": 160,
        "wires": []
    },
    {
        "id": "c93878364358f080",
        "type": "function",
        "z": "6814538862850eec",
        "name": "Parse topic",
        "func": "const codes = [\n    '1234',\n    '+1122AABB'\n];\n\naction = msg.payload.action;\naction_code = msg.payload.action_code;\naction_transaction = msg.payload.action_transaction;\nif(action == 'disarm' && !codes.includes(action_code))\n{\n   action = 'invalid_code';\n}\nmsg.payload = '{\"arm_mode\":{\"mode\":\"'+action+'\",\"transaction\":'+action_transaction+'}}';\nmsg.alarmAction = action;\nmsg.code = action_code;\n\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 200,
        "wires": [
            [
                "68f2d041a7a0c77b",
                "8e18454d16948f05"
            ]
        ]
    },
    {
        "id": "79919fbee76170db",
        "type": "switch",
        "z": "6814538862850eec",
        "name": "action ?",
        "property": "payload.action",
        "propertyType": "msg",
        "rules": [
            {
                "t": "nempty"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 320,
        "y": 200,
        "wires": [
            [
                "c93878364358f080"
            ]
        ]
    },
    {
        "id": "8e18454d16948f05",
        "type": "switch",
        "z": "6814538862850eec",
        "name": "",
        "property": "alarmAction",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "disarm",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "invalid_code",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "emergency",
                "vt": "str"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 4,
        "x": 650,
        "y": 260,
        "wires": [
            [],
            [],
            [],
            []
        ]
    },
    {
        "id": "01888fd1d3c7149c",
        "type": "change",
        "z": "6814538862850eec",
        "name": "not_ready",
        "rules": [
            {
                "t": "set",
                "p": "arm_mode",
                "pt": "msg",
                "to": "exit_delay",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 320,
        "y": 340,
        "wires": [
            [
                "68a39496e722f436"
            ]
        ]
    },
    {
        "id": "921e5006341e690e",
        "type": "change",
        "z": "6814538862850eec",
        "name": "disarm",
        "rules": [
            {
                "t": "set",
                "p": "arm_mode",
                "pt": "msg",
                "to": "disarm",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 310,
        "y": 380,
        "wires": [
            [
                "68a39496e722f436"
            ]
        ]
    },
    {
        "id": "d057ea8e019f0847",
        "type": "change",
        "z": "6814538862850eec",
        "name": "arm_all_zones",
        "rules": [
            {
                "t": "set",
                "p": "arm_mode",
                "pt": "msg",
                "to": "arm_all_zones",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 300,
        "y": 420,
        "wires": [
            [
                "68a39496e722f436"
            ]
        ]
    },
    {
        "id": "4333706fb86e1fe4",
        "type": "change",
        "z": "6814538862850eec",
        "name": "in_alarm",
        "rules": [
            {
                "t": "set",
                "p": "arm_mode",
                "pt": "msg",
                "to": "in_alarm",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 320,
        "y": 500,
        "wires": [
            [
                "68a39496e722f436"
            ]
        ]
    },
    {
        "id": "68a39496e722f436",
        "type": "function",
        "z": "6814538862850eec",
        "name": "Parse topic",
        "func": "\nmsg.payload = '{\"arm_mode\":{\"mode\":\"'+msg.arm_mode+'\"}}';\n\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 420,
        "wires": [
            [
                "2cca0ba3313b813b"
            ]
        ]
    },
    {
        "id": "2cca0ba3313b813b",
        "type": "mqtt out",
        "z": "6814538862850eec",
        "name": "ENT_TEL_keypad",
        "topic": "zigbee2mqtt/ENT_TEL_keypad/set",
        "qos": "1",
        "retain": "true",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "9b372184.f0e1a",
        "x": 670,
        "y": 420,
        "wires": []
    },
    {
        "id": "9b372184.f0e1a",
        "type": "mqtt-broker",
        "name": "mqttIoull",
        "broker": "192.168.10.9",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": true,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": ""
    }
]
```
