### ISSUE TITLE
Device specific settings?

### ISSUE THREAD

**Issue by sirs2k** [Koenkk/zigbee2mqtt#4298]
Hi,

I'm a little confused, where do I put the config for hue_power_on_behavior so it recovers the hue settings before power loss?

I'm using hass.io plugin and I've tried putting the settings in devices.yaml like so
```
'0x0017880102d9e6ef':
  friendly_name: office_hue_3
  retain: true
  retrieve_state: true
  hue_power_on_behavior: recover
  hue_power_on_brightness: 125
```

I've also tried it like this:
```
'0x0017880102d9e6ef':
  friendly_name: office_hue_3
  retain: true
  device_options:
    brightness: 255
    kelvin: 6000
```

But no luck, apologies if I've completely missed any instructions
Thank you
