### ISSUE TITLE
Define a max and min in opening or closing in roller blind

### ISSUE THREAD

**Issue by alcar21** [Koenkk/zigbee2mqtt#4611]
## Is your feature request related to a problem? Please describe
When I raise the Ikea Fyrtur blinds they go all the way up and when they go down the catch on the window handles.
When low it is frustrating to be aware that it does not latch anywhere.

## Describe the solution you'd like
Define a maximum or/and a minimum when you open or close the blinds fully

## Describe alternatives you've considered
Define a new parameter that allows a blind to open or close at a certain percentage.
example:
```yaml
devices:
  '0x00158d0001d82999':
    friendly_name: 'livin_room_cover'
    max_percent: 90
    min_percent: 20
```

## Additional context
Does not apply

**Comment by alcar21** [comment]
it can be implemented?

**Comment by Koenkk** [comment]
It can if there is enough interest for it. I currently do not see any thumbs up on the OP, if someone else is interested please do this.

**Comment by alcar21** [comment]
I understand. Thank you @Koenkk

**Comment by edubox** [comment]
I think is an interesting feature

**Comment by Jaguaza** [comment]
interesting

**Comment by Davide1313** [comment]
I think it's a good feature, it could be very useful.

**Comment by Jaguaza** [comment]
Please @Koenkk I've been behind this thread for a long time and I'm very interested. Please implant it, it would make us happy and it would be good news.

Sure there are non-participatory people who would see this integration great.
If I knew about programming it would help to do it, but I'm a chump.

I can only ask and trust that you can help us to do this.

Thanks for everything.

**Comment by divemasterjm** [comment]
+1

**Comment by hoggerz** [comment]
Hi,

The IKEA Fyrtur blinds do have a configurable maximum drop that can be set using the buttons on the blind itself. I have one and it works fine with zigbee2mqtt, here’s the instructions from the manual:

Set maximum level of extension

Move the blinds to the desired position using the Open/Close remote or the buttons on blind. When blind is at the desired position, you can double press the up or down button on the blind to save this position as the new maximum level of extension.
If you would like to clear the maximum level of extension setting, first move the blind to the top position. Afterwards, double press either up or down button on the blind .
You cannot perform this setting using the Open/Close remote.

I know this doesn't solve the minimum opening issue but it’s a start.

hoggerz

**Comment by alcar21** [comment]
I didn't know this. It's valid for me but i don't know if it is valid for the rest people.

**Comment by mambers** [comment]
It would be interesting for me if this function could be implemented, without it it is much more limited by creating automation for this blind.

**Comment by Koenkk** [comment]
I will implement this once I'm finished with current zigbee-herdsman-converters refactoring (almost done)

**Comment by Koenkk** [comment]
@alcar21 reading https://github.com/Koenkk/zigbee2mqtt/issues/4611#issuecomment-744065796 now, does this fix your issue? (this sounds better than limiting the position from the z2m side).

**Comment by Koenkk** [comment]
I've started to implement this but I don't think this can be (correctly) implemented. The problem is that when you send state: OPEN, a Zigbee command "OPEN" will be send to the cover (so there is no position to min/max out here). I think that in fact the correct way to limit the max/min position is in the blind itself (like described in: https://github.com/Koenkk/zigbee2mqtt/issues/4611#issuecomment-744065796).

**Comment by mambers** [comment]
@Koenkk There is no method to natively put the minimum, you can only the maximum.

**Comment by Koenkk** [comment]
@mambers I see, but neither can we limit the min position from z2m

**Comment by alcar21** [comment]
> I've started to implement this but I don't think this can be (correctly) implemented. The problem is that when you send state: OPEN, a Zigbee command "OPEN" will be send to the cover (so there is no position to min/max out here). I think that in fact the correct way to limit the max/min position is in the blind itself (like described in: [#4611 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/4611#issuecomment-744065796)).

The native method not working with zigbee2mqtt. 

Ok ok, i understand the problem.

**Comment by alcar21** [comment]
> @mambers I see, but neither can we limit the min position from z2m

@Koenkk this feature is useful because when I said to Google or Alexa, "open the cover or close the cover" you can check the command and set max or min position. I believe that if you set position above or below the configured limit (min and max), it's difficult to control this case.

Now, when I push the remote button, I control max with home assistant. This is my action:
```
 action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.cover_salon_derecha_cover
        position: 90
```

**Comment by Koenkk** [comment]
@alcar21 that would involve translating commands, e.g. when OPEN command is set use position. In my opinion this look like a big workaround/hack.

**Comment by alcar21** [comment]
yes, it's botched. I understand because I'm a Java programmer.

I think that comment #4611 only works with the button [Ikea E1766](https://www.zigbee2mqtt.io/devices/E1766.htm)

@mambers do you have home assistant? Do the Ikea limits of comment #4611 work for you?

Thanks.

**Comment by mambers** [comment]
Once added to Z2M, the default maximum limits that ikea has have disappeared, there is no way to configure them

**Comment by hoggerz** [comment]
I found that I was able to set the hard limits following the instructions posted above. Mine is integrated with zigbee2mqtt & HA and it works fine

**Comment by alcar21** [comment]
> I found that I was able to set the hard limits following the instructions posted above. Mine is integrated with zigbee2mqtt & HA and it works fine, it’s an IKEA blind.

I try later again because now, I'm not at home. When I do the instructions of comment #461. when I made the comment instructions I couldn't define a limit.

**Comment by mambers** [comment]
I have managed to set the maximum limit by performing the steps of [#4611](https://github.com/Koenkk/zigbee2mqtt/issues/4611#issuecomment-744065796), now saying to ok google "lower bedroom blind" I don't have to say the percentage to which to go down. only missing some method for the minimum amount.

**Comment by alcar21** [comment]
Hi, I check comment 4661 and only working in the bottom limit. For the top not working, go up to the top.

**Comment by alcar21** [comment]
@Koenkk it is possible to send the configuration to home assistant such that:
```
cover:
   - platform: "mqtt"
     name: livin_room_cover
     availability_topic: "zigbee2mqtt/bridge/state"
     command_topic: "zigbee2mqtt/livin_room_cover/set"
     position_topic: "zigbee2mqtt/livin_room_cover"
     set_position_topic: "zigbee2mqtt/livin_room_cover/set"
     set_position_template: "{ \"position\": {{ position }} }"
     value_template: "{{ value_json.position }}"
     position_closed: 20
     position_open: 90
```

**Comment by Koenkk** [comment]
@alcar21 yes, add the following for your device in `configuration.yaml`.

```yaml
```yaml
devices:
  "0x12345678":
    friendly_name: my_cover
    homeassistant:
      cover:
        position_closed: 20
        position_open: 90
```

**Comment by alcar21** [comment]
Perfect, this resolve my problem.
Thanks!

**Comment by night199uk** [comment]
Hey. I'm wondering if the commit in 5cf63da reference here can be pushed to zigbee-herdsman-converters?

I have a non-Ikea blind - a Yoolax / Graywind blind from Amazon powered by the Yookee D10110. Although this blind allows you to set "min" and "max" points, they are not actually correct and act more like "stops" than limits. e.g. issuing a location: 0 will still set the blind fully open and location: 100 set the blind to full length.

I use HomeKIt via homebridge-z2m as my master, not home assistant; homebridge-z2m *always* issues location: <x> settings, and never simply issues open/close commands. Therefore; for this scenario (where the blind can't directly receive open/close) I think the commit in 5cf63da works perfectly and seems to be the only reasonable way to fix this right now. I'm running with that commit applied locally.

**Comment by alcar21** [comment]
Finally, if it's usefully, i used the following code:

```
'0x000d6ffffe2ab1e9':
  friendly_name: cover_salon_derecha
  homeassistant:
    cover:
      payload_open: '{ "position": "95" }'
      set_position_template: '{ "position": {{ 95 if position > 95 else position }} }'
      position_open: 95
      position_closed: 0
```

**Comment by dusopn** [comment]
> @alcar21 yes, add the following for your device in `configuration.yaml`.
> 
> ```yaml
> devices:
>   "0x12345678":
>     friendly_name: my_cover
>     homeassistant:
>       cover:
>         position_closed: 20
>         position_open: 90
> ```

Do I understand this correctly that this will set bottom but also the top limit of my fyrtur? also for use with Google home "open blinds"? just pasting this code into config file? thanks for info

**Comment by dusopn** [comment]
Configuration invalid

Component error: devices - Integration 'devices' not found.

**Comment by dusopn** [comment]
Also, do I have to set up anything else (templating) or just paste that code to config. So this is now added functionality of hassio? thank you

**Comment by sepodele** [comment]
`'0xasdasdasdaqwrqrwqr0':
    friendly_name: Cover
    homeassistant:
      cover:
        position_closed: 0
        position_open: 85 `

I've added that to Zigbee2mqtt configuration.yaml (and restarted mqtt addon, zigbee2mqtt addon and Home Assistant) but blinds still open all the way. What am I doing wrong?

**Comment by alcar21** [comment]
> ```
> '0xasdasdasdaqwrqrwqr0':
>     friendly_name: Cover
>     homeassistant:
>       cover:
>         position_closed: 0
>         position_open: 85 
> ```
> 
> I've added that to Zigbee2mqtt configuration.yaml (and restarted mqtt addon, zigbee2mqtt addon and Home Assistant) but blinds still open all the way. What am I doing wrong?

You need to change your code by:
```
'0xasdasdasdaqwrqrwqr0':
    friendly_name: Cover
    homeassistant:
      cover:
        position_closed: 0
        position_open: 85 
        payload_open: '{ "position": "85" }'
        set_position_template: '{ "position": {{ 85 if position > 85 else position }} }'
```
