### ISSUE TITLE
Can't find USB stick in Docker environment

### ISSUE THREAD

**Issue by vytautasgimbutas** [Koenkk/zigbee2mqtt#4707]
Hi,
I can't get zigbee2mqtt working in a docker container. If I run it directly in the VM everything works fine.

I've tried:
- got another container running home-assistant. It has `zwave` stick mapped and everything works fine there. Also, temporarily mapped zigbee stick to `home-assistant` container and when I get into container I can see that `/dev/zigbee` is there.
- tried mapping `devices: /dev/ttyUSB0:/dev/zigbee` in docker-compose.yml
- tried auto serial port detection as per documented

Logs:
```
$ docker inspect zigbee2mqtt
Zigbee2MQTT:info  2020-10-18 15:40:26: Logging to console and directory: '/app/data/log/2020-10-18.15-40-26' filename: log.txt
Zigbee2MQTT:info  2020-10-18 15:40:26: Starting Zigbee2MQTT version 1.15.0 (commit #1bccc5d)
Zigbee2MQTT:info  2020-10-18 15:40:26: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-18 15:40:26: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-18 15:40:26: Failed to start zigbee
Zigbee2MQTT:error 2020-10-18 15:40:26: Exiting...
Zigbee2MQTT:error 2020-10-18 15:40:26: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/zigbee'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
```

VM:
```
luna@luna-42:~$ ls -l /dev/zigbee
lrwxrwxrwx 1 root root 7 Oct 18 15:32 /dev/zigbee -> ttyUSB0
luna@luna-42:~$ test -w /dev/zigbee && echo success
success
luna@luna-42:~$
```

docker-compose:
```
---
version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.15.0
    volumes:
      - /home/luna/config/zigbee2mqtt/data:/app/data
    devices:
      - /dev/zigbee:/dev/zigbee
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Vilnius
```
