### ISSUE TITLE
Cannot seem to pair Xiaomi WSDCGQ11LM Sensor (temp/humid/press) -  zigbee2mqtt:warn Message without device!

### ISSUE THREAD

**Issue by deten** [Koenkk/zigbee2mqtt#474]
Hi Folks,

I cannot seem to add my third sensor.  I checked the configs and everything seems to be fine.

When I pair the device by holding down the button until the blue light blinks, I get a warning in the NPM log:

`  zigbee2mqtt:warn 2018-10-13 19:33:04 Message without device!`

I am not sure what to do, I have tried dozens of things and cant seem to get it working.  I appreciate any help!

Zigbmee2mqtt Config:

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: xxxxx
  password: xxxxx
serial:
  port: /dev/ttyACM1
devices:
  '0x00158d0002437c56':
    friendly_name: 'Stat 1'
    retain: false
  '0x00158d00023208ae':
    friendly_name: 'Stat 2'
    retain: false
```

HomeAssistant Config:

```
mqtt:
  discovery: true
  broker: 192.168.1.xx
  port: xx
  client_id: home-assistant-1
  username: xxx
  password: xxx
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
