### ISSUE TITLE
Deprecated click event - TRADFRI open/close remote

### ISSUE THREAD

**Issue by vannetta** [Koenkk/zigbee2mqtt#4815]
## What happened
I've a TRADFRI open/close remote; this is the payload:
`zigbee2mqtt:info  2020-10-29 12:48:41: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe083c73', payload '{"linkquality":26,"update_available":true,"click":"close"}'`
I've changed the automation using action instead of click; but the payload only shows the click.
I've tried to insert in the configuration.yaml 
```
devices:
  '0xccccccfffe083c73':
    friendly_name: 0xccccccfffe083c73_click
    legacy: false 
```
but when I check the configuration this is the message:
Component error: devices - Integration 'devices' not found.
## Debug info
Zigbee2MQTT version: zigbee2mqtt-edge
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II: CC2531
Adapter firmware version:
