### ISSUE TITLE
Slow network response after adding ikea trådfri lamps

### ISSUE THREAD

**Issue by taugusti** [Koenkk/zigbee2mqtt#4817]
## What happened
The problem is slow response. LED lights are really slow (or fails)
Everything worked fine while i only had sensors on zigbee2mqtt and the LEDs on the Trådfri gateway. 
Problems started when I moved the LEDs to Zigbee2mqtt.
Sensors (Ikea and Xiaomi buttons) works perfect.

** The setup **
35 zigbee devices connected:
 8x Trådfri on-off button
 18x trådfri led bulps
 2x trådfri motion sensors
 1x trådfri wireless dimmer
 1x trådfri remote control
 1x trådfri driver for led strips (10W)
 3x Xiaomi Aquara switches
 1x Xiaomi Aquara door/window sensor

**Eliminating home assistant:**
When sending a command diretcly from mqtt.fx ex:
zigbee2mqtt/0x000b57fffe121da3/set with payload {"state": "ON"}
The first command after a long silent period works fine. Maybe also the next - but after a few commands there is a delay (5-30 seconds) from command to response. Some lamps show this behavior from the very first try.
When home assistant responds to a button by turning on 2-4 lamps (both in and out via mqtt) the response is immediately very long

**Further observations**
if I try to "load map" in the home assistant zigbee2mqtt frontend, I get a lot of these errors:
zigbee2mqtt/bridge/logging: {"level":"error","message":"Failed to execute LQI for '0x000b57fffe1291e6'"}
It eventually loads the map - if it is correct or something is missing... I have no idea :-)

** What I have tried **
1. eliminate home assistant from the equation by controlling the LEDs from MQTT.fx - same result
2. replace CC2531 with conbee II (since I have >20 devices I expected that was the problem) - resulted in timeout errors:
  mqtt: zigbee2mqtt/bridge/log
  payload: {"message":"Publish 'set' 'state' to '0x000b57fffe121da3' failed: 'Error: Command 0x000b57fffe121da3/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (no response received)'","meta":{"friendly_name":"0x000b57fffe121da3"},"type":"zigbee_publish_error"}

## What did you expect to happen
no delays 👍 

## How to reproduce it (minimal and precise)
Install trådfri led lamps and the magic begins :-)

## Debug info
Zigbee2MQTT version: 1.5.0
Adapter hardware: CC2531 (tested with Conbee II also - same issue)
Adapter firmware version: 20190608
running on: Host: RPI4 with Home assistant 0.116.4 and the zigbee2mqtt plugin

** herdsman log **
https://pastebin.com/DhdHsAts

** Zigbee2mqtt home assistant config ***
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.x.y.z'
  user: abc
  password: abcd
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
