### ISSUE TITLE
zigbee2mqtt/bridge/state 'offline' after Mosquitto MQTT broker restart

### ISSUE THREAD

**Issue by coldfire84** [Koenkk/zigbee2mqtt#4854]
## What happened
I recently noticed _all_ of my zigbee2mqtt devices became ```unavailable``` in Home Assistant, and traced the trigger back to a Mosquitto MQTT broker restart.

Restarting HA did not fix the problem, but restarting zigbee2mqtt _did_ resolve the issue. On further investigation, I found that after restarting the broker ```zigbee2mqtt/bridge/state``` remains ```offline```.

Looking through the logs I can see that zigbee2mqtt reconnects, as you would expect, but state is not updated on reconnect:

```
Zigbee2MQTT:error 2020-11-02 18:28:30: Not connected to MQTT server!
Zigbee2MQTT:info  2020-11-02 18:28:35: Connected to MQTT server
```

zigbee2mqtt itself is working, I can control devices via the zigbee2mqtt web GUI/ MQTT commands, just Home Assistant thinks all of the zigbee2mqtt devices are offline due to  ```zigbee2mqtt/bridge/state``` being ```offline``` 

## What did you expect to happen
zigbee2mqtt should (imo!) reconnect when the MQTT broker is available and publish an ```zigbee2mqtt/bridge/state``` ```online``` message.

On startup/ initial connect I can see that zigbee2mqtt does publish to `zigbee2mqtt/bridge/state`:
```
Zigbee2MQTT:info  2020-11-02 20:02:42: Connecting to MQTT server at mqtt://hostname:1883
Zigbee2MQTT:debug 2020-11-02 20:02:42: Using MQTT keepalive: 30
Zigbee2MQTT:info  2020-11-02 20:02:42: Connected to MQTT server
Zigbee2MQTT:info  2020-11-02 20:02:42: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
```
However there is no such message publishing on a reconnect.

## How to reproduce it (minimal and precise)
Restart Mosquitto MQTT broker _without_ restarting zigbee2mqtt.

Cleaned config (removed device-specific/ network key) - note that MQTT version 5 in use for device-specific retention - hopefully I haven't missed anything obvious in my configuration, apologies if I have 🤞

```
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://hostname:1883'
  user: <username>
  password: <password>
  keepalive: 30
  version: 5
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8081
experimental:
  new_api: true
advanced:
  log_level: debug
  homeassistant_discovery_topic: 'homeassistant'
  homeassistant_status_topic: 'homeassistant/status'
  rtscts: false
  report: true
  last_seen: ISO_8601
```

## Debug info
Zigbee2MQTT version: 1.16.0 (I have also tested/ replicated this issue with 1.15.0, both containerised)
Adapter hardware: zzh! / CC26X2R1
Adapter firmware version: CC26X2R1_20201017.hex (from dev branch)
Mosquitto MQTT broker version: 1.6.12
