### ISSUE TITLE
debounce_ignore not working for occupancy in Aqara PIR

### ISSUE THREAD

**Issue by McGiverGim** [Koenkk/zigbee2mqtt#4859]
## What happened
I'm not too sure if I have understood the `debounce` feature correctly. I have several Aqara PIR RTCGQ11LM (https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html) that send the illuminance and the occupancy.
I have configured it to group the messages except for the occupancy one, that I don't want any delay. 
I did it with something like this:
```yaml
'0x00158d0004147c40':
  friendly_name: presencia_pasillo
  debounce: 5
  debounce_ignore:
    - occupancy
```
I have used a high `debounce` value in this test to be sure of the problem.
The result is that I don't receive the `occupancy: true` until 5 seconds later than it is detected.
 
## What did you expect to happen
Receive the `occupancy: true` message almost instantly.

## How to reproduce it (minimal and precise)
Configure as in my explanation and test it.

## Debug info
Zigbee2MQTT version: 1.16.0
Adapter hardware: CC2531
Adapter firmware version: zStack12.20190608
