### ISSUE TITLE
Ikea Tradfri LED1903C5/LED1835C6 won't pair (nothing in logs)

### ISSUE THREAD

**Issue by nielsrune** [Koenkk/zigbee2mqtt#4949]
## What happened
I'm switching from tradfri gateway to zigbee2mqtt. All other bulb has been paired but my single Tradfri LED1835C6.
Nothing at all is shown in the log of zigbee2mqtt.
I have followed the suggestions at https://www.zigbee2mqtt.io/information/FAQ.html#no-logging-is-shown-at-all
The bulbs firmware was up to date on the Tradfri Gateway.

## What did you expect to happen
Expected the bulb to start pairing.

## How to reproduce it (minimal and precise)
Try to pair new (< 1 month old) Ikea Tradfri LED1535C6.

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC26X2R1 (Electrolama zig-a-zig-ah, newly bought, latest firmware CC26X2R1_20201026.hex)
Adapter firmware version: CC26X2R1_20201026.hex

System is a new Raspberry Pi 4 model B running Rasberry Pi OS.
Home Assistant Supervised 0.117.5

Tried Touchlink scan. At first run nothing is found. Further runs fails with Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

**Comment by io53** [comment]
The trådfri e14 is very picky with the timings when resetting. Try to wait 1 full second (or a bit more) in the off state, and keep the on state very short when doing the reset procedure.

**Comment by nielsrune** [comment]
Good news and bad news:

I tried one more according to io53s suggestion waiting a little more in the off state. As before, I could get the bulb to glow, ie. paring mode. But the bulb would still not show up in zigbee2mqtt.

But then I tried - more or less in a desperate action - to switch the config to:
```
experimental:
  new_api: true
```
Then after doing the reset procedure, the bulb immediately paired.

I'm still new to the whole smart home thing, so I havn't a clue yet as to the difference in old vs new api. But it seems like a bug or at least a quirk, that maybe should be put on
https://www.zigbee2mqtt.io/devices/LED1903C5_LED1835C6.html

**Comment by hdoedens** [comment]
I am having the exact same issue. Two brand new TRADFRI lamps (bulbs). I have reset the bulbs more than ten times now. I place it very close to the coordinator but there is no logging, and no paring. 
I tried the suggestion above: disabling the `new_api` but no success. I guess @nielsrune was lucky?

I think I have tried every suggestion now but nothing is working. What could I try or how can I see what is going on? Debug logging of the zigbee2mqtt container is not showing anything.

I have many more TRADFRI devices, remotes and lamps, they all pair at first try.

**Comment by waldher** [comment]
I'm having similar issues. I'm able to pair a brand new LED1835C6 with the Tradfri Gateway, with which I've updated its firmware to 2.3.050, but I'm not able to pair it with zigbee2mqtt, despite having bulbs in the past do this without issue. I've also tried two different LED1835C6's now, so it's not isolated to one bulb.

**Comment by waldher** [comment]
An update on my previous comment: At first, setting
```
experimental:
  new_api: false
```
in the HomeAssistant plugin configuration didn't save. After setting it again, I can confirm that it does indeed pair right away after a bulb reset using firmware 2.3.050. (If you don't know what firmware you have on your bulb, you'll need to first pair the bulb with a Tradfri Gateway to update it)

**Comment by MattWestb** [comment]
I was have the same problems some time. First the bulb not being reseted but working with little tryings.
Some time its timing out after being reseted and starting one own networks as zigbee lights is doing (LL and Zigbee 3 standard). Its normal on channel 11 with default pan-ID then touchlink scanning from deCONZ. Reseting it with touchlink can helping getting it being detected.
The large problem is if not having the default LL channels in the config (11. 15. 20 and 25 is moderate for lights in LL and zigbee 3) then it can the coordinator is not scanning the channel and not finding it. Theoretically all channels should working but using one of the primary ones its making it more successful then working with lights.

**Comment by nielsrune** [comment]
I'm glad to hear @waldher got his bulbs working in the same way.

I don't recall my procedure exactly, but it may have been the same:
- Set new_api to false and restart zigbee2mqtt and wait for it to settle (the frontend is not working with this setting), so the log page in the zigbee2mqtt is the place to monitor.
- Do the reset procedure on the bulb again. I'd rather count to 7 than missing out on cycle.
- If done right and the bulb is glowing, refresh the log. My bulb started to pair right away.  

@hdoedens would you care to try again, as it seems I wasn't just lucky..

Also, I can confirm that my firmware is 2.3.050 and the bulb was previously connected to a Trådfri gateway. Also, try to remove the bulb from the gateway before resetting. 

@MattWestb My dongle is the zig-a-zig-ahh. Before getting the bulb to pair, I tried both scanning and resetting over touchlink. But it seems to not work with the dongle. The seller, Omar, wrote something like he too didn't got touchlink to work. 
But I can see that I have `channel: 11` in the configurations advance section. I didn't touch the default config but setting a custom `network_key`

**Comment by MattWestb** [comment]
What i have reading that is some problems with the firmware of all TI coordinators that is making TL not working all the time. Then its working its being very nicely implanted in the web front end.

**Comment by hdoedens** [comment]
I tried the procedure as described by @nielsrune again, several times. I completely stopped and started zigbee2mqtt to be sure sure the new settings would have effect. As soon as the log was quiet I reset the Tradfri bulb, but nothing showed up in the log and the bulb keeps glowing. When I click the a Tradfri remote a few times, that will bind to the bulb immediately and the bulb respons to the Tradfri remote. Still nothing in the log (but that makes sense as it is not paired with zigbee2mqtt).

Maybe this has something to do with my settings or the version I am running. I'm running the edge version as the binding of remote to Zigbee devices is broken in the stable version. This is my config:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: *******
  password: ***********
serial:
  port: /dev/ttyACM1
advanced:
  log_level: debug
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: false
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
Note the non-default `pan_id`. As I was having trouble to pair right from the start and I migrated some software but used the same hardware I thought it would help to change the `pan_id` to have a fresh start.
I don't know the firmware version of the bulb's that won't pair as I do not have an IKEA bridge.
The hardware I am using is a Texas Instruments CC2531.

Any help is more than appreciated...
