### ISSUE TITLE
Battery level and voltage on RTCGQ01LM

### ISSUE THREAD

**Issue by ghiglie** [Koenkk/zigbee2mqtt#495]
Hi there! I'm a Home Assistant noob user; I've started using a template in  to manage battery statuses.
I've just found that on Aqara and Mija motion / human body sensors I have this data on illumination sensor data, and only on that - so the ones that haven't it, they won't show it event there's the correct data in MQTT JSON. Is there a way to "move" it from "illumination" sensor to "presence" one?

Thanks,
Marco

**Comment by Koenkk** [comment]
Could you post the related part of your homeassistant configuration?

Offtopic: I would recommend you to use home assistant discovery: https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-Home-Assistant

**Comment by ghiglie** [comment]
Hi Koenkk! It's MQTT autodiscovery that generates that configuratio, I haven't written a single line of code. I can't catch the config messagese, but I'll add a screenshot ASAP.

**Comment by ghiglie** [comment]
![pir_ill_battery_mqtt](https://user-images.githubusercontent.com/12821495/47185508-e728cd00-d32d-11e8-9065-9e62ec0859f1.PNG)
![pir_ill_battery](https://user-images.githubusercontent.com/12821495/47185513-e98b2700-d32d-11e8-8cd6-876a47040177.PNG)

**Comment by ghiglie** [comment]
Don't give attention to the loss of data, it was my wife cleaning home... :D
That's what I have on HA with autodiscovery, but the two PIR that haven't the illuminance sensor haven't got the voltage/battery data on HA - there are instead in JSON.

**Comment by Koenkk** [comment]
Could you post your zigbee2mqtt log?

This may also be due to https://github.com/Koenkk/zigbee2mqtt/issues/485 which will be fixed in zigbee2mqtt 0.1.8.

**Comment by ghiglie** [comment]
I'm sorry, maybe I'm too late, just upgraded to 0.1.8. My "request" is different from what you mean.
For example, in HA, my AQARA sensors that have illuminance are defined like this:
![sensors_def1](https://user-images.githubusercontent.com/12821495/47261712-8e943400-d4d5-11e8-9df4-624334a716a3.PNG)
(still dunno why battery and voltage are missing on one of them!)
but "normal" mija pirs are like this:
![sensors_def2](https://user-images.githubusercontent.com/12821495/47261728-01051400-d4d6-11e8-869b-50eea3fbfa52.PNG)
same for door sensor, they are missing the Battery/Voltage data that is in MQTT message:
![sensors_def3](https://user-images.githubusercontent.com/12821495/47261734-37db2a00-d4d6-11e8-9d33-a0fc19500503.PNG)

**Comment by Koenkk** [comment]
The battery will only be visible after the sensor reported it, this can take some time (a few hours).

**Comment by ghiglie** [comment]
Ok, I'm really missing something! I've redefined the sensor in HA, as in Wiki and adding linkquality:

```
homeassistant:
  customize:
    binary_sensor:
      - platform: "mqtt"
        state_topic: "zigbee2mqtt/0x00158d00023f3532"
        availability_topic: "zigbee2mqtt/bridge/state"
        payload_on: true
        payload_off: false
        value_template: "{{ value_json.occupancy }}"
        device_class: "motion"
        json_attributes: 
          - battery
          - voltage
          - linkquality

```
So I expect to see the added attributes on the sensor, but I can only see " value_json.battery " as battery attribute value. With MQTTfx I sniffed the messages for autodiscovery, but they all look correct, and also the occupancy sensors should have the battery/voltage attributes... 
Where am I doing bad? :(

**Comment by Koenkk** [comment]
Could you provide your zigbee2mqtt log? And which HA version are you running?

**Comment by Koenkk** [comment]
Everything looks OK from the zigbee2mqtt side. Can you open an issue for this @ home assistant?

**Comment by ghiglie** [comment]
Sorry for late reply. I'll surely do, something is acting strange on my install. This works:
```
sensor:
  - platform: mqtt
    name: "Mija PIR 1"
    state_topic: "zigbee2mqtt/0x00158d00023f3532"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - voltage
    retain: false
    device_class: battery
```
And shows correctly the values.
