### ISSUE TITLE
Zigbee2Mqtt fails with conbee II 

### ISSUE THREAD

**Issue by oliviermichaelis** [Koenkk/zigbee2mqtt#5018]
## What happened
Zigbee2mqtt did not get into an operational state using the conbee II stick. The web dashboard was in a loading/initialising state. The permit_join button did not work, I was unable to pair any devices. 
## What did you expect to happen
Be able to use Zigbee2mqtt with the conbee II.
## How to reproduce it (minimal and precise)
Started docker container with the following config:
```
homeassistant: true
permit_join: false
mqtt:
  server: "mqtt://mosquitto.default.svc.cluster.local:1883"
serial:
  adapter: deconz
  port: "/dev/ttyACM0"
frontend:
   port: 8080
experimental:
  new_api: true
advanced:
  log_level: debug
```
and with the `DEBUG=zigbee-hersman*` environment variable

## Debug info
Zigbee2MQTT version:  `latest-dev` (49f37ac)
Adapter hardware: Conbee II
Adapter firmware version: `deCONZ_ConBeeII_0x26670700.bin.GCF`
Hardware: Raspberry Pi 3b+ on ARM64 with Ubuntu 20.04

Log is found at: https://pastebin.com/gXaFaBN1
I'm happy to provide any requested logs/configs/information and willing to test any preliminary fixes. Thanks!
