### ISSUE TITLE
How to force Z2M to send again the last state known after a power failure ?

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#5019]
Hi

I don't know if it's an issue or just me who don't understand how is it working but today I had a power down in my building (3 seconds) and then the power come back.

However, before the power failure, bulbs was off, after the power failure, all lights in my appartment was ON and stay like that :(. I don't want it.

I setup my NUC to POWER ON after failure power, so 3 minutes later, Z2M and HA runs again, I thought that the lights was going down because it was the last state in memory for all my lights but nothing happens and everythiung stay like that until I click on each Domotized switch.

Do you have any idea why ? is it linked to Z2M ? Home Assistant ? 

I'm lost about htis subject.

Thank you

**Comment by MiguelAngelLV** [comment]
You can configure these devices with "retain" flag

**Comment by kevincaradant** [comment]
Hi

I forgot to say every devices has already 'retain: true'

But it seems to does not work :(

**Comment by kevincaradant** [comment]
@MiguelAngelLV , do you know how is it working ? Should I write or do something else than other to write in `configuration.yaml` the attribute `retain: true` ?

This is my configuration.yaml:


```
homeassistant: true
permit_join: true
frontend:
  port: 9090
experimental:
  new_api: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://xxxxxxxxxxx'
  user: xxxxxx
  password: xxxxxxxx
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6755
  channel: 25
  baudrate: 115200
  rtscts: false
  availability_timeout: 60
devices:
  '0x00158d0002136633':
    friendly_name: switch_mini_kitchen
    retain: true
    legacy: false
  '0x00158d0002135b0b':
    friendly_name: switch_mini_table_basse_livingroom
    retain: true
    legacy: false
  '0x00158d0001e4524c':
    friendly_name: open_close_window_livingroom
    retain: true
  '0x00158d000201b485':
    friendly_name: open_close_kitchen
    retain: true
  '0x00158d0001e45264':
    friendly_name: open_close_door_livingroom
    retain: true
  '0x00158d0001e43e4c':
    friendly_name: motion_toilet
    retain: true
    occupancy_timeout: 600
  '0x00158d0001a1f256':
    friendly_name: motion_desktop
    retain: true
    occupancy_timeout: 1800
  '0x00158d000222e35e':
    friendly_name: motion_kitchen
    retain: true
    occupancy_timeout: 600
  '0x00158d0001b1448d':
    friendly_name: open_close_desktop
    retain: true
  '0x00158d0001a1f2c3':
    friendly_name: motion_bedroom
    retain: true
    occupancy_timeout: 600
  '0x00158d0001bc23c0':
    friendly_name: water_leak_bathroom
    retain: true
  '0x00124b001eadcc46':
    friendly_name: gledopto_kitchen
    retain: true
  '0x00124b001d4344fd':
    friendly_name: gledopto_1_bathroom
    retain: true
```

Is it from HA or Z2M that I should manage the auto send of the last state ? 

Thank you
