### ISSUE TITLE
LVS-SC7 & LVS-ZB500D not working with CC2652

### ISSUE THREAD

**Issue by spurgelaurels** [Koenkk/zigbee2mqtt#5091]
Ah bummer this was closed; I think it's a similar issue. 

**zigbee2mqtt add-on version (if edge, please report commit hash):**  1.16.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**  Arch linux 5.9.1-arch1-1, HASS installed manually

**Description of problem:**
Having an issue with re-pairing an LVS-SC7. It worked dandy with my CC2531, but I moved to a ZZH CC2652 for better stability, along with a move to stack 3.x.0. Initially, it paired while I was re-pairing all of the other devices, but it wasn't until a while later that I realized that my scene controllers weren't working. I checked it out and they were connected and reporting LQI, but they weren't reporting the button presses. 

Tonight I tried re-pairing one, along with pairing a new out-of-the-box LVS-ZB500D, but neither of them will connect or pair and I don't see anything in my logs. 

**Your entire configuration from the frontend (with sensitive fields redacted):**

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: <redacted>
  password: <redacted>
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
Nothing is appearing in the logs during the re-pair operation, even with debug enabled.

_Originally posted by @spurgelaurels in https://github.com/Koenkk/zigbee2mqtt/issues/3940#issuecomment-733403466_
