### ISSUE TITLE
State change of Group not being acted on by group member devices

### ISSUE THREAD

**Issue by LucidityCrash** [Koenkk/zigbee2mqtt#5225]
## What happened
Physical State of switches not changed of devices in Group

Debug Logs here : https://hastebin.com/ixokidegam.yaml

## What did you expect to happen
I expected 2 switches to turn on.  My understanding was that this is carried out using Zigbee messaging and not the actual MQTT component.

## How to reproduce it (minimal and precise)
If I send {"state":"ON"} to the groups set topic eg zigbee2mqtt/out_back/set then the value of the devices topic is updated to include "state":"ON" but the actual physical switch remains off.

## Debug info
Zigbee2MQTT version: 1.16.2 commit: 04c15f7
Adapter hardware:  CC26X2R1 (zzh)
Adapter firmware version:     zStack3x0 20201026

devices.yaml : 
```
'0x5c0272fffece4eb8':
  friendly_name: 'Back Door'
'0x5c0272fffece6d93':
  friendly_name: 'Patio Door'
```

groups.yaml
```
'1':
  friendly_name: out_back
  devices:
    - '0x5c0272fffece4eb8'
    - '0x5c0272fffece6d93'
```

configuration.yaml
```
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: XXXXXXXXXX
serial:
  port: /dev/ttyUSB0
advanced:
  pan_id: XXXXXXXXXX
  ext_pan_id: XXXXXXXXXX
  network_key: XXXXXXXXXX
  rtscts: false
  channel: 26
  cache_state: true
  cache_state_persistent: true
  last_seen: epoch
  log_level: debug
  report: true
devices: devices.yaml
groups: groups.yaml
frontend:
  port: 8880
experimental:
  new_api: true
```

I'm assuming this isn't really an issue more a case of me getting it wrong but some assistance would be great.
