### ISSUE TITLE
How to add support for an unsupported device when running the docker container?

### ISSUE THREAD

**Issue by poldim** [Koenkk/zigbee2mqtt#549]
I'm running this in a Docker.  I'm trying to figure out how to expose the `node_modules/zigbee-shepherd-converters` folder? 

I've tried both of these volume mappings but they create error in starting the container:

- `- ./appdata/home-assistant/zigbee2mqtt2/:/app/`

- `- ./appdata/home-assistant/zigbee2mqtt/zigbee-shepherd-converters/:/app/node_modules/zigbee-shepherd-converters`

This is my `docker-compose` config for running the container:

```
  homeassistant_zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: homeassistant_zigbee2mqtt
    restart: always
    network_mode: host
    volumes:
      - ./appdata/home-assistant/zigbee2mqtt/:/app/data/
    devices:
      - "/dev/ttyACM0"
    environment:
      - TZ=${TZ}
```
