### ISSUE TITLE
Xiaomi Motion Sensor Not sending occupancy:false

### ISSUE THREAD

**Issue by palitu** [Koenkk/zigbee2mqtt#55]
I have a motion sensor setup, however it rarely sends a occupancy:false.

it is a `Motion_Front_Yard (0x00158d00010e49cc): RTCGQ01LM - Xiaomi MiJia human body movement sensor`

![screenshot_20180520_103140](https://user-images.githubusercontent.com/6634784/40275149-0f19497a-5c19-11e8-964c-d4e30b32e589.png)

as you can see, it was true all over night, when we were all asleep.  Any help would be appreciated. 

```
devices:
  '0x00158d00010e49cc':
    friendly_name: 'Motion_Front_Yard'
    occupancy_timeout: 30
    retain: false
```
