### ISSUE TITLE
Moving from PI to docker

### ISSUE THREAD

**Issue by onlymejosh** [Koenkk/zigbee2mqtt#5504]
Hey there!

## What happened
I am trying to migrate from a PI to a new server as well as moving to docker.
So far I have:
- Copied the contents of the working the pis  `/opt/zigbee2mqtt/data` to a folder called `zigbee2mqtt` on the new server. 
My `docker-compose`  looks like this:

```
mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    restart: always
    ports:
        - '1883:1883'
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt:1.16.2
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    environment:
      - TZ=Europe/London
    network_mode: host
```

`zigbee2mqtt` folder looks like this:
```
log/
configuration.yaml
coordinator_backup.json
databse.db
databse.db.backup
state.json
```

`configuration.yaml`
```
homeassistant: true
permit_join: true
frontend:
  port: 8080
advanced:
  log_level: debug
  pan_id: 6760
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://haus.local:1883'
serial:
  port: /dev/ttyUSB0
devices:
```

I get errors saying the pan id is in use already. However changing the id I still result in 0 connected devices

```
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:09: zigbee-herdsman started
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:09: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200805,"transportrev":2},"type":"zStack3x0"}'
zigbee2mqtt      | Zigbee2MQTT:debug 2021-01-01 22:59:09: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6761}
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:09: Currently 0 devices are joined:
zigbee2mqtt      | Zigbee2MQTT:warn  2021-01-01 22:59:09: `permit_join` set to  `true` in configuration.yaml.
zigbee2mqtt      | Zigbee2MQTT:warn  2021-01-01 22:59:09: Allowing new devices to join.
zigbee2mqtt      | Zigbee2MQTT:warn  2021-01-01 22:59:09: Set `permit_join` to `false` once you joined all devices.
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:09: Zigbee: allowing new devices to join.
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:09: Started frontend on port 0.0.0.0:8080
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:10: Connecting to MQTT server at mqtt://haus.local:1883
zigbee2mqtt      | Zigbee2MQTT:debug 2021-01-01 22:59:10: Using MQTT anonymous login
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:10: Connected to MQTT server
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:10: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt      | Zigbee2MQTT:info  2021-01-01 22:59:10: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"04c15f7","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200805,"transportrev":2},"type":"zStack3x0"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6761},"permit_join":true,"version":"1.16.2"}'
```

DoI need to do a full repair of all of my deices?

## What did you expect to happen
Devices appear as they did before

## Debug info
Zigbee2MQTT version: 1.16.2
Adapter hardware: zig-a-zig-ah!
Adapter firmware version:

```
zigbee2mqtt      | Zigbee2MQTT:debug 2021-01-01 22:58:58: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6761},"serialPort":{"path":"/dev/ttyUSB0"}}'
```
