### ISSUE TITLE
Docker Compose Deployment with Conbee II from Dresden Elektronik

### ISSUE THREAD

**Issue by nicedevil007** [Koenkk/zigbee2mqtt#5528]
Hey guys,

I have a conbee II stick that is updated to the latest firmware from dresden elektronik since today.
Unfurtunately I can't get zigbee2mqtt to run with the provided docker compose file:

```
version: 2

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee2mqtt_data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
```

The stick is definetly on /dev/ttyACM0 because it is working with it when I'm using the phoscon webui.

Logfile of the docker container tells me this:

```
> zigbee2mqtt@1.17.0 start /app,
> node index.js,
,
Zigbee2MQTT:info  2021-01-03 14:37:33: Logging to console and directory: '/app/data/log/2021-01-03.14-37-33' filename: log.txt,
Zigbee2MQTT:info  2021-01-03 14:37:33: Starting Zigbee2MQTT version 1.17.0 (commit #07cdc9d),
Zigbee2MQTT:info  2021-01-03 14:37:33: Starting zigbee-herdsman (0.13.46),
Zigbee2MQTT:error 2021-01-03 14:37:53: Error while starting zigbee-herdsman,
Zigbee2MQTT:error 2021-01-03 14:37:53: Failed to start zigbee,
Zigbee2MQTT:error 2021-01-03 14:37:53: Exiting...,
Zigbee2MQTT:error 2021-01-03 14:37:53: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms),
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31),
    at Generator.throw (<anonymous>),
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65),
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! zigbee2mqtt@1.17.0 start: `node index.js`,
npm ERR! Exit status 1,
```

my configuration.yml looks like this:

```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://XXXXXXXXXXXXX'
  # MQTT server authentication, uncomment if required:
  user: XXXXXXXXXXXXX
  password: XXXXXXXXXXXXXXX

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
```
