### ISSUE TITLE
aqara cube automations in home assistant

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#571]
I already postet this in the HA community, but afterwards I think the better chance to get an answer 
is here. 

I wanted to get rid of the Aqara Control gateway and so I bought a cc2531 zigbee sniffer.

My doors sensors work fine already.

But I have some problems with the Cube.

First it is not autodetected like the other senors, so I had to implement this:

```
- sensor:
  - platform: "mqtt"
    name: Cube state
    state_topic: "zigbee2mqtt/0x00XXXXXXXX"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
    json_attributes: 
      - "battery"
      - "voltage"
      - "angle"
      - "side"
      - "from_side"
      - "to_side"
      - "brightness"
      - "angle_x_absolute"
      - "angle_y_absolute"
      - "angle_z"
      - "angle_y"
      - "angle_x"
      - "unknown_data"
    force_update: true
```
This is an example from here https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-Home-Assistant 1

Before I had a working automation like this:

```
- alias: Cube - flip90
  initial_state: 'on'
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_XXXXXXX
      action_type: flip90
  action:
    - service: homeassistant.toggle
      entity_id: light.flaschen
```
With the new mqtt sensor I tried this:

```
- alias: Cube - flip90
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.cube_state
    to: 'flip90'
  action:
    - service: homeassistant.toggle
      entity_id: light.flaschen
```
The problem is that toggling the light will not work, because the state does not change. So if flip90 changes to flip90 again the automation will not do anything.

How can I make this work?

The next thing that does not work is using the rotation as a dimmer function
this one worked before, but I have no clue how to change it to make it work with the mqtt sensor.

```
- alias: Cube - rotate
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_XXXXXXX
        action_type: rotate
  action:         
    - service: light.turn_on
      data:
        entity_id: light.kugellicht
        color_name: darkturquoise
    - service: light.turn_on
      data_template:
        entity_id: light.kugellicht
        brightness: >-
          {% if trigger.event.data.action_value | float > 0 %}
          {{  states.light.kugellicht.attributes.brightness | int + 30 }}
          {% else %}
          {{  states.light.kugellicht.attributes.brightness | int - 30 }}
          {% endif %}
```

**Comment by Koenkk** [comment]
You should listen to the MQTT topic like mentioned here: https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-Home-Assistant (*To respond to button clicks (e.g. WXKG01LM)*)

**Comment by h4nc** [comment]
I'm not sure how to use this with the cube
Specially I don't know how I have to change this line
`      value_template: "{{ 'single' == trigger.payload_json.click }}"`

I guess instead of `single` I have to use `action`, but I absolutly don't now what `trigger.payload_json.click` does. 
Do I have to change it to `trigger.payload_json.flip90`?

```
automation:
  - alias: Respond to button clicks
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/<FRIENDLY_NAME'
    condition:
      condition: template
      value_template: "{{ 'single' == trigger.payload_json.click }}"
    action:
      entity_id: light.bedroom
      service: light.toggle
```

**Comment by h4nc** [comment]
Thank you, it works. 

Is it also possible to use it as a dimmer? See last code in my first posting.

**Comment by h4nc** [comment]
Ok so I tried it like this now:

```
- alias: Cube - rotate
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00XXXX'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ 'rotate_left' == trigger.payload_json.action }}"
      - condition: template
        value_template: "{{ 'rotate_right' == trigger.payload_json.action }}"
  action:         
    - service: light.turn_on
      data:
        entity_id: light.kugellicht
        color_name: darkturquoise
    - service: light.turn_on
      data_template:
        entity_id: light.kugellicht
        brightness: >-
          {% if trigger.payload_json.angle | float > 0 %}
          {{  states.light.kugellicht.attributes.brightness | int + 30 }}
          {% else %}
          {{  states.light.kugellicht.attributes.brightness | int - 30 }}
          {% endif %}  
```

Altough I turn the light on before I get an error in HA:

> Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'

**Comment by lolorc** [comment]
as condition I use a simple template {{ trigger.payload_json.action in ['rotate_right', 'rotate_left'] }}
I guess you need to diag your automation my making the action simpler and adding more statements to see which one causes the issue

**Comment by h4nc** [comment]
Thanks I thing this did the trick, because it works now as before

- alias: Cube - rotate
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00XXX'
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.action in ['rotate_right', 'rotate_left'] }}"
  action:         
    - service: light.turn_on
      data:
        entity_id: light.kugellicht
        color_name: darkturquoise
    - service: light.turn_on
      data_template:
        entity_id: light.kugellicht
        brightness: >-
          {% if trigger.payload_json.angle | float > 0 %}
          {{  states.light.kugellicht.attributes.brightness | int + 30 }}
          {% else %}
          {{  states.light.kugellicht.attributes.brightness | int - 30 }}
          {% endif %}

**Comment by ebivan** [comment]
Thank you guys, I was wondering how to get this working and this works very well!
But is it also possible to use the angle value that is also provided by the cube? The solution above just applies a fixed increase or decrease by 30 based upon weather the rotation is to the left or to the right, but I would like to use the angle as well. 
Maybe one point in light level for every two degrees turned would be a good value

**Comment by h4nc** [comment]
This is how you can use the angle, next step would be to mark the cube sides (3 sides for rgb) and use the choosen side to change the colors. But I think that would be only a nice to have feature.

```
- alias: Cube - rotate
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00XXXX'
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.action in ['rotate_right', 'rotate_left'] }}"
  action:         
    - service: light.turn_on
      data:
        entity_id: light.yourlight
    - service: light.turn_on
      data_template:
        entity_id: light.yourlight
        brightness: >-
          {% if trigger.payload_json.angle | float > 0 %}
          {{  states.light.yourlight.attributes.brightness | int + (trigger.payload_json.angle | int) / 2 }}
          {% else %}
          {{  states.light.yourlight.attributes.brightness | int + (trigger.payload_json.angle | int) / 2 }}
          {% endif %}  
```

And I use this to change my color (tap funktion of the cube)

```
- alias: Cube - tap
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00XXXX'
  condition:
    condition: template
    value_template: "{{ 'tap' == trigger.payload_json.action }}"
  action:
    - service: light.turn_on
      data:
        effect: random
        entity_id: light.yourlight
```

**Comment by lolorc** [comment]
a bit sad the cube is doesn't provide its real side when rotating it.
I'm using some kind of automation to retrieve the side from the last mqtt message containing side or to_side but it's not perfect.

I also find the cube to be far from reactive enough. I guess I need to use a sniffer to see if it's an issue with the cube, the network or with zigbee2mqtt

**Comment by h4nc** [comment]
Is there a way to print a value of the trigger payload into a notification?

This does not work:

```
- alias: Aqara - Battery Cube
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00XXXXX'
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.battery | int < 10 }}"
  action:
    - service: notify.ios_mynotify
      data:
        message: "Value: {{ trigger.payload_json.battery }}"  
```

Whats the right way to do this?
