### ISSUE TITLE
Allow server to be defined in secret.yaml

### ISSUE THREAD

**Issue by claha** [Koenkk/zigbee2mqtt#5831]
## Is your feature request related to a problem? Please describe
If I want to make my configuration public (e.g. store it on github) it would be nice to not have to expose the mqtt server (as with the the mqtt user/password).

## Describe the solution you'd like
To be able to write this in my coniguration.
```yaml
mqtt:
  server: '!secret server'
  user: '!secret user'
  password: '!secret password'
```
