### ISSUE TITLE
Problem with thermostat valve Tuya GS361A-H04 after discover 

### ISSUE THREAD

**Issue by mareklac** [Koenkk/zigbee2mqtt#5897]
I have Tuya GS361A-H04  and added it tto HA via discover. I added Climate panel to dashbord and : 

1.  Can not set mode of working. These 3 buttons remains gray. On log I can see 
2021-01-24 22:28:35 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: 

2. I am able to set requested temperature and read actual one  but : 
3. I can not control from scheduler .. requested temperature.... even if trigger of scheduler occurs and requested temperature should be changed ... it is not changed at all .. only manualy I can set temperature 

So far I played with other TRVs and I had no this problem .
Here you have my discover message :

action_template: >-
  {% set values = {'idle':'off','heat':'heating','cool':'cooling','fan
  only':'fan'} %}{{ values[value_json.running_state] }}
action_topic: zigbee2mqtt/mojMar
availability:
  - topic: zigbee2mqtt/bridge/state
current_temperature_template: '{{ value_json.local_temperature }}'
current_temperature_topic: zigbee2mqtt/mojMar
device:
  identifiers:
    - zigbee2mqtt_0x5c0272fffec4d166
  manufacturer: Siterwell
  model: Radiator valve with thermostat (GS361A-H04)
  name: mojMar
  sw_version: Zigbee2MQTT 1.17.0
json_attributes_topic: zigbee2mqtt/mojMar
max_temp: '30'
min_temp: '5'
mode_command_topic: zigbee2mqtt/mojMar/set/system_mode
mode_state_template: '{{ value_json.system_mode }}'
mode_state_topic: zigbee2mqtt/mojMar
modes:
  - 'off'
  - auto
  - heat
name: mojMar
temp_step: 0.5
temperature_command_topic: zigbee2mqtt/mojMar/set/current_heating_setpoint
temperature_state_template: '{{ value_json.current_heating_setpoint }}'
temperature_state_topic: zigbee2mqtt/mojMar
temperature_unit: C
unique_id: 0x5c0272fffec4d166_climate_zigbee2mqtt
platform: mqtt

How make it working agian ( set mode and control from scheduler ) ????
UPDATE: I created manually device base on discover message. Device looks llike : 
climate mmm1:
  - platform: "mqtt"
    availability_topic: "zigbee2mqtt/bridge/state"
    temperature_unit: "C"
    temp_step: 0.5
    min_temp: "5"
    max_temp: "30"
    json_attributes_topic: "zigbee2mqtt/mojMar"
    current_temperature_topic: "zigbee2mqtt/mojMar"
    current_temperature_template: "{{ value_json.local_temperature }}"
    mode_state_topic: "zigbee2mqtt/mojMar"
    mode_state_template: "{{ value_json.system_mode }}"
    modes: 
      - "off"
      - auto
      - heat
    mode_command_topic: "zigbee2mqtt/mojMar"
    action_topic: "zigbee2mqtt/mojMar"
    action_template: "{% set values = {'idle':'off','heat':'heating','cool':'cooling','fanonly':'fan'} %}{{ values[value_json.running_state] }}"
    temperature_command_topic: "zigbee2mqtt/mojMar/set/current_heating_setpoint"
    temperature_state_template: "{{ value_json.current_heating_setpoint }}"
    temperature_state_topic: "zigbee2mqtt/mojMar"

and now those buttons are active but no effects on TRV . So if I switch from "AUTO:" to  "OFF"  , panel gets gray from green but no effect on TRV... 
In log now I can see: 
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 WARNING (MainThread) [homeassistant.components.mqtt] Erroneous JSON: off
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.local_temperature }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from off
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.child_lock }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.valve_detection }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.window_detection }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.current_heating_setpoint }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from off
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.local_temperature }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from off
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.system_mode }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.current_heating_setpoint }})
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from off
2021-01-25 13:19:52 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: off, template: {{ value_json.system_mode }})
2021-01-25 13:20:06 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: heat, template: {% set values = {'idle':'off','heat':'heating','cool':'cooling','fanonly':'fan'} %}{{ values[value_json.running_state] }})

**Comment by Flop2006** [comment]
Same Problem here.
homeassistant log shows:

```
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:469
Integration: MQTT (documentation, issues)
First occurred: 26. Februar 2021, 22:02:00 (66 occurrences)
Last logged: 08:53:02
Invalid modes mode:
```
Radiator valve with thermostat (GS361A-H04) von Siterwell 

MQTT discovery data:
`Topic: homeassistant/climate/0x14b457fffe3caa22/climate/config`
payload
```
action_template: >-
  {% set values = {'idle':'off','heat':'heating','cool':'cooling','fan
  only':'fan'} %}{{ values[value_json.running_state] }}
action_topic: zigbee2mqtt/0x14b457fffe3caa22
availability:
  - topic: zigbee2mqtt/bridge/state
current_temperature_template: '{{ value_json.local_temperature }}'
current_temperature_topic: zigbee2mqtt/0x14b457fffe3caa22
device:
  identifiers:
    - zigbee2mqtt_0x14b457fffe3caa22
  manufacturer: Siterwell
  model: Radiator valve with thermostat (GS361A-H04)
  name: '0x14b457fffe3caa22'
  sw_version: Zigbee2MQTT 1.17.1
json_attributes_topic: zigbee2mqtt/0x14b457fffe3caa22
max_temp: '30'
min_temp: '5'
mode_command_topic: zigbee2mqtt/0x14b457fffe3caa22/set/system_mode
mode_state_template: '{{ value_json.system_mode }}'
mode_state_topic: zigbee2mqtt/0x14b457fffe3caa22
modes:
  - 'off'
  - auto
  - heat
name: '0x14b457fffe3caa22'
temp_step: 0.5
temperature_command_topic: zigbee2mqtt/0x14b457fffe3caa22/set/current_heating_setpoint
temperature_state_template: '{{ value_json.current_heating_setpoint }}'
temperature_state_topic: zigbee2mqtt/0x14b457fffe3caa22
temperature_unit: C
unique_id: 0x14b457fffe3caa22_climate_zigbee2mqtt
platform: mqtt
```
