### ISSUE TITLE
Documentation error regarding MQTT permit_join switch for Home Assistant

### ISSUE THREAD

**Issue by m0wlheld** [Koenkk/zigbee2mqtt#5900]
## What happened
Tried to enable/disable permit_join using MQTT switch with Home Assistant. Used example found on page the [Home Assistant](https://www.zigbee2mqtt.io/integration/home_assistant.html) specific documentation.

```
# Switch for enabling joining
switch:
  - platform: mqtt
    name: "Zigbee2MQTT Main join"
    state_topic: "zigbee2mqtt/bridge/info"
    value_template: '{{ value_json.permit_join }}'
    command_topic: "zigbee2mqtt/bridge/request/permit_join"
    payload_on: "true"
    payload_off: "false"
```

While "switching" permit_join on does work, the switch returns to it's off position immediately after. Obviously the state is not read/interpreted correctly.

**Cause:**
The output of `value_template: '{{value_json.permit_join}}'` is `true` (boolean), while `payload_on` and `payload_off` define a string value. Those attributes will be used if `state_on` and `state_off` attributes are undefined.

**Solution:**
Documentation page needs to be updated. Either convert `value_template` outcome into a string (variant 1) or add `state_on`/`state_off` to expect boolean values (2nd proposal).

```
switch:
  - platform: mqtt
    name: "Zigbee2MQTT Main join"
    state_topic: "zigbee2mqtt/bridge/info"
    value_template: '{{ value_json.permit_join | lower }}'
    command_topic: "zigbee2mqtt/bridge/request/permit_join"
    payload_on: "true"
    payload_off: "false"
```

or

```
switch:
  - platform: mqtt
    name: "Zigbee2MQTT Main join"
    state_topic: "zigbee2mqtt/bridge/info"
    value_template: '{{ value_json.permit_join }}'
    state_on: True
    state_off: False
    command_topic: "zigbee2mqtt/bridge/request/permit_join"
    payload_on: "true"
    payload_off: "false"
```

## What did you expect to happen
Switch should represent the current "permit_join" setting.

## How to reproduce it (minimal and precise)

1. Add switch configuration from sample above to your Home Assistant configuration.yaml
2. Add switch (after restart) to HA Lovelace UI, if not automatically added
3. Click switch on. Switch will return to it's `Off` position after 1-2 seconds

## Debug info
Zigbee2MQTT version: 1.17.0-dev
Adapter hardware: Raspee II
Adapter firmware version: 0x26690700
