### ISSUE TITLE
Schneider Electric WV704R0A0902 occupied_heating_setpoint invalid value

### ISSUE THREAD

**Issue by obuchmann** [Koenkk/zigbee2mqtt#5933]
## What happened

When I try to control the heat temperature via Home Assistant it produces following error and does not set occupied_heating_setpoint.

```
ERROR: Publish 'set' 'occupied_heating_setpoint' to 'thermostat_kinderzimmer' failed: 'Error: Write 0x14b457fffea5cd4d/1 hvacThermostat({"occupiedHeatingSetpoint":2200}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 12103 - 1 - 186 - 513 - 4 after 10000ms)'
```

When I try to set the temperature to 22 degree Celsius it submits a value of 2200 for occupiedHeatingSetpoint.

The docs say following: [Device Page](https://www.zigbee2mqtt.io/devices/WV704R0A0902.html#controlling)
Get or set occupied heating setpoint to <temperature> in degrees Celsius. Possible values: 7 to 30 by default; leave empty to read.
```
  {
      "occupied_heating_setpoint": "<temperature>"
  }
```

If I submit the payload via mqtt.publish it works as expected
```
service: mqtt.publish
data:
  topic: zigbee2mqtt/thermostat_kinderzimmer/set
  payload: '{"occupied_heating_setpoint": "22"}'
```

## What did you expect to happen

The value for occupied_heating_setpoint should not be multiplied by 100 for this device when publishing the command.

## How to reproduce it (minimal and precise)

Pair this Device and submit a climate.set_temperature

test script:
```
alias: Fails on Wiser radiator thermostat
sequence:
  - service: climate.set_temperature
      data:
        entity_id: climate.kitchen
        temperature: 22
mode: single
```

## Debug info
Zigbee2MQTT version: 1.17.0.1
Adapter hardware: CC2652RB
Adapter firmware version:
