### ISSUE TITLE
RGB Bulb Brightness/Color

### ISSUE THREAD

**Issue by blawford** [Koenkk/zigbee2mqtt#616]
I am trying to get a Innr 285C RGB bulb to fully co-operate with Home Assistant. It is working but not as well as I would like!

So the main problem I am having is that when I want to change colour, brightness and power state at the same time. It does it, but in 3 distinct steps. 

The automation I have is motion sensor triggered to turn the bathroom light on red at minimum brightness. If the last time the bulb was on it was bright white at full brightness, it turns back on in this state for a split second, then turns the brightness down to minimum (still white) and then finally red at minimum brightness.

As you can imagine, a flash of white light in the middle of the night when you've got up to use the toilet isn't what you want.

If I recreate this by sending the MQTT message manually (sent to `zigbee2mqtt/lightbulbShower/set` through the MQTT option in the developer tools):
`{"state":"ON","color_temp":555,"color":{"x":0.698,"y":0.299},"brightness":2}`

I get the following messages by subscribing to `zigbee2mqtt/lightbulbShower` and `zigbee2mqtt/lightbulbShower/set` in an external program:

> zigbee2mqtt/lightbulbShower/set -> {"state":"ON","color_temp":555,"color":{"x":0.698,"y":0.299},"brightness":2}  #Red, low brightness (the message sent from HomeAssistant)
> 
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":338,"color":{"x":0.437,"y":0.404},"brightness":253} #White, full brightness
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":338,"color":{"x":0.437,"y":0.404},"brightness":253} #White, full brightness
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":338,"color":{"x":0.437,"y":0.404},"brightness":253} #White, full brightness
> 
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":338,"color":{"x":0.437,"y":0.404},"brightness":2} #White, low brightness
> 
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":555,"color":{"x":0.697,"y":0.299},"brightness":2} #Red, low brightness
> zigbee2mqtt/lightbulbShower -> {"state":"ON","color_temp":555,"color":{"x":0.697,"y":0.299},"brightness":2} #Red, low brightness

My HomeAssistant configuration for the device is the following:

```
light:
  - platform: "mqtt_json"
    name: "Shower Light"
    state_topic: "zigbee2mqtt/lightbulbShower"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    xy: true
    command_topic: "zigbee2mqtt/lightbulbShower/set"
```

Anyone any ideas how I can improve things?
