### ISSUE TITLE
Philips Lamp not working

### ISSUE THREAD

**Issue by simann** [Koenkk/zigbee2mqtt#6171]
## What happened
On last Friday(5.2.2021) i connected 4 Devices (4 Channel Switch, 2 Channel Switch, Philips Lamp and Wall Plug) and everything seemed to work "most of the time". That means the current error happened already but i wasnt sure about an error on my side or not. In the end it worked and i was able to switch the lamp every 10 seconds. Today(8.2.2021) i booted my pc and started the zigbee software and it stopped working. That means i cant switch the light anymore. Im trying to use the web interface and select a different color.

Side note:
The 4 Channel Switch is still working fine.

## What did you expect to happen
I expected that i could change the color of the lamp, because nothing in the configuration changed.

## How to reproduce it (minimal and precise)
Pair a philips lamp, then reboot pc.

Im pretty sure that this wont happen all the time but sometimes it does.

## Debug info
Zigbee2MQTT version: 1.17.1 - #99274c7
Adapter hardware: Deconz Conbee II
Adapter firmware version: 0.38.88 - rev: 0x26580700

I attached a screenshot of the error, the information of the zigbee software, the log.txt, screenshot of the lamp

## configuration
```
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: \\.\COM4
  adapter: deconz
experimental:
  output: json
  new_api: true
frontend:
  port: 8080
devices:
  '0x000d6f000fe48d1b':
    friendly_name: S1
  '0x000d6f001082b082':
    friendly_name: S2
  '0x7cb03eaa0a01920a':
    friendly_name: '0x7cb03eaa0a01920a'
  '0x0017880108383b43':
    friendly_name: L1
```
The deconz Adapter is connected via an extension cable, 2m length. I dont think that matters tho, because the switch is working.

Any help or advice would be appreciated. :)

Edit:
Attached the log of Friday (5.2.2021) aswell
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5942203/log.txt)

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5942157/log.txt)
![zigBee_Lamp](https://user-images.githubusercontent.com/28533890/107193554-42939300-69ef-11eb-84c4-50fb5fc17a5c.png)
![zigBee_startup](https://user-images.githubusercontent.com/28533890/107193557-432c2980-69ef-11eb-936d-947b48fa076d.png)
![zigBee_Logs](https://user-images.githubusercontent.com/28533890/107193555-42939300-69ef-11eb-80c9-c44d80c1d070.png)
