### ISSUE TITLE
Docker Compose instructions

### ISSUE THREAD

**Issue by 877dev** [Koenkk/zigbee2mqtt#6416]
## Is your feature request related to a problem? Please describe
I use [IOTstack ](https://sensorsiot.github.io/IOTstack/) which uses Docker compose, and find the Docker instructions don't work for me, such as here: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#docker

## Describe the solution you'd like
I would like the Docker compose commands to be shown.
Also regarding supporting new devices, how to revert back from using local devices.js

## Describe alternatives you've considered
I tried following the guide to support new devices, but always get stuck at:
`docker run -v "$PWD":/app -w /app --rm node:12 npm ci`
I don't know the Docker Compose equivalent.

## Additional context
My docker-compose.yml looks like this:
```
zigbee2mqtt:
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
    - ./volumes/zigbee2mqtt/data:/app/data
    - /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
    restart: unless-stopped
    network_mode: host
```

**Comment by ozer59** [comment]
same for me link for zigbee-herdsman-converters don't work but for /app/data is ok 
https://github.com/Koenkk/zigbee2mqtt/issues/6350#issuecomment-783558621

**Comment by 877dev** [comment]
@ozer59 are you using docker compose? As that is what I am using and raised the issue for.

**Comment by Koenkk** [comment]
Your docker compose looks OK to me (`- /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters`) Make sure that `/opt/zigbee-herdsman-converters` exists on your system (execute `ls /opt/zigbee-herdsman-converters`).

To remove local changes simply remove this line from your docker-compose.

**Comment by 877dev** [comment]
Thanks for the help, I'm afraid problems persist:

![image](https://user-images.githubusercontent.com/46575282/108895776-eeea9180-760b-11eb-9960-be3d6c9359c9.png)

docker-compose.yml:
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
      - /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
    devices:
      #- /dev/ttyAMA0:/dev/ttyACM0
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host
```

Portainer zigbee2mqtt debug output:
[zigbee.log](https://github.com/Koenkk/zigbee2mqtt/files/6031449/zigbee.log)

**Comment by m0wlheld** [comment]
> I don't know the Docker Compose equivalent.

There is none, that‘s a one-time task and the container created is removed immediately after.

**Comment by m0wlheld** [comment]
> Also regarding supporting new devices, how to revert back from using local devices.js

remove the 2nd volume bind from compose file

**Comment by 877dev** [comment]
@m0wlheld thank you! Any idea on the error's I am having only  when mapping the 2nd volume ?

` - /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters`

[zigbee.log](https://github.com/Koenkk/zigbee2mqtt/files/6031548/zigbee.log)

**Comment by ozer59** [comment]
yes i try it but same issue 
for me app/data is ok with : - /volume1/docker/zigbee2mqttstable:/app/data
but not for converters
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt:latest
      volumes:
        - /volume1/docker/zigbee2mqttstable:/app/data
        - /volume1/docker/zigbee2mqttstable/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
        - /run/udev:/run/udev:ro
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
      privileged: true
      environment:
        - TZ=Europe/Paris

**Comment by 877dev** [comment]
@ozer59 looks like the same issue after all.
Maybe something to do with this? https://github.com/Koenkk/zigbee2mqtt/issues/3291

**Comment by 877dev** [comment]
Some success, seems to be working now!

Try:
```
cd  /opt/zigbee-herdsman-converters
sudo npm ci
```

Then restart zigbee container..

**Comment by ozer59** [comment]
sorry but i don't unterstand this command : sudo docker run -v "$PWD":/app -w /app --rm node:12 npm ci
ozer@HOUSE:/volume1/docker/zigbee2mqttstable/zigbee-herdsman-converters$ sudo docker run -v "$PWD":/app -w /app --rm node:12 npm ci
npm WARN prepare removing existing node_modules/ before installation

> @serialport/bindings@9.0.4 install /app/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild


> serialport@9.0.6 postinstall /app/node_modules/zigbee-herdsman/node_modules/serialport
> node thank-you.js

Thank you for using serialport!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/serialport/donate


added 699 packages in 18.982s

**Comment by 877dev** [comment]
If you read through the comments the answer is there already...

Did you try the commands I posted?

**Comment by m0wlheld** [comment]
The docker command created the directories and files in the current directory (which - following the guide — should be /opt/zigbee-herdsman-converters), so you can bind-mount it to the Z2M container using docker-compose. 

It is only required, if you want to add unsupported devices.

**Comment by 877dev** [comment]
@Koenkk here is the solution for docker compose which I can confirm working, could it be added to the "supporting new devices" guide?


## Docker Compose

To setup a local copy of zigbee-herdsman-converters so that you can modify e.g. `devices.js` and from`Zigbee.js`; use the following instructions:

`cd /opt`
`git clone https://github.com/Koenkk/zigbee-herdsman-converters.git`
`cd zigbee-herdsman-converters`
`sudo npm ci`

Now add the volume to your `docker-compose.yml `
Example:
```
zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
      - /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
    devices:
      #- /dev/ttyAMA0:/dev/ttyACM0
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host
```

**Comment by m0wlheld** [comment]
> cd /opt
git clone https://github.com/Koenkk/zigbee-herdsman-converters.git
cd zigbee-herdsman-converters
sudo npm ci

That is basically the result of the `docker run`-call with the requirement to have npm installed locally. I don't see no benefit for an environment, if Docker is already installed.

**Comment by 877dev** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/3291
> After the clone a `npm ci` has to be done to install the dependencies. I've updated the instructions accordingly. thanks!

I'm not sure , but I do know it works. I never use `docker-run` as I am using Docker Compose.

**Comment by m0wlheld** [comment]
> I never use `docker-run` as I am using Docker Compose.

... which orchestrates docker run commands ...

**Comment by 877dev** [comment]
> That is basically the result of the `docker run`-call with the requirement to have npm installed locally. I don't see no benefit for an environment, if Docker is already installed.

I think I am understanding what you are saying. So how would you recommend getting the dependencies to be installed when up'ing the container in compose?

**Comment by Koenkk** [comment]
Does it work with:

```yaml
zigbee2mqtt:
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
    - ./volumes/zigbee2mqtt/data:/app/data
    - /opt/zigbee-herdsman-converters/index.js:/app/node_modules/zigbee-herdsman-converters/index.js
    - /opt/zigbee-herdsman-converters/devices.js:/app/node_modules/zigbee-herdsman-converters/devices.js
    - /opt/zigbee-herdsman-converters/converters:/app/node_modules/zigbee-herdsman-converters/converters
    - /opt/zigbee-herdsman-converters/lib:/app/node_modules/zigbee-herdsman-converters/lib
    restart: unless-stopped
    network_mode: host
```
