### ISSUE TITLE
Multiple lights assigned to a group don't always change their z2m-state when their group is triggered by a bounded remote

### ISSUE THREAD

**Issue by pavax** [Koenkk/zigbee2mqtt#6424]
## What happened
If I create a group with more than two lights and bind a remote to the group, the z2m-state of the lights doesn't always update, when the remote is used. (the lights physically toggle but not their z2m-state). They do however change their z2m-state, if I change the group state directly (i.e. sending a group/set mqtt command)

I've got several zigbee groups that consist of several ikea based lights. In the same group are always the same kind of lights. I've also got different remotes (5Btn / 2Btn). The very same problem can be found in various constellations. I also played around with the `retrieve_state` attribute (set to true) on the devices and/or the groups - without luck though... But maybe I'm not configuring it correctly :/

I might need to point out, that I'm using a Conbee II (aka. deconz) adapter - as due to limited stock on the Slae.sh or zzh

_PS: I just recently installed Z2M and thanks for the amazing work - I really like the project! IMHO it got the best documented features out there on zigbee and it's devices_ 

_PPS: There is also a discussion item open with regards to that, but I wasn't sure if the more proper way is an Issue: https://github.com/Koenkk/zigbee2mqtt/discussions/5998_

## How to reproduce it

- I defined a group consisting of the same type of ikea bulbs

    ```
    '4':
      friendly_name: Esstisch
      devices:
        - 0x5c0272fffe9d957d/1
        - 0x5c0272fffe9f261e/1
        - 0x5c0272fffea29e52/1
    ```

- I bound the Ikea remote (5btn) to the group (also I made sure it's not bound to the default group according to the [device page](https://www.zigbee2mqtt.io/devices/E1524_E1810.html))

    Source Ep | Destination |  Clusters
    ------------ | ------------- | -------------
    1 | Coordinator | PowerCfg 
    1 | Esstisch | OnOff/LevelCtrl
    
- when I press the toggle button on the remote the lights all toggle, but their state is often not changed as I see it in the MQTT Topic. Since at least one light might not correctly toggle the group also stays in that state (which is what I'd also expect) 

- when I change state of the group (by sending a mqtt message or using Home-assistant UI) the lights behave correct

## Current Workaround/Hack
several seconds after I press the toggle button (on the 5-Btn-Remote) or the on-off button (on the 2-Btn-Remote) I'm going to fetch the current value of every light associated with that group.  Eventually the state of the group also changes in z2m after some seconds... I guess this hack works like the concept of the `retrieve_state` attribute, but with a longer delay 

**Home-Assitant Automation:**
```
alias: '[zigbee] sync  esstisch '
description: ''
use_blueprint:
  path: custom/z2m-ikea-remote-controls.yaml
  input:
    remote: sensor.esstisch_remote_action
    toggle:
      - delay: '00:00:03'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 01/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 02/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Esstisch Spot 03/get
          payload_template: '{"state": "", "color_temp": "", "brightness": ""}'
```
Blueprint: https://gist.github.com/pavax/32581f0d4ed860264159df1d79d8c849

## Debug info
Zigbee2MQTT version: 1.17.1 
Adapter hardware:  Conbee II
Integration: Home Assistant Addon
Adapter firmware version:  0x26680700
Remotes: E1524/E1810, E1743
Lights:  LED1537R6/LED1739R5, L1529, LED1837R5 
Groups: [Tradfri_Scene (65289) ](https://www.zigbee2mqtt.io/devices/E1524_E1810.html)

Configuration:
```
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 25
```
