### ISSUE TITLE
1.18.0 won't start with Slaesh's CC2652RB: "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"

### ISSUE THREAD

**Issue by m0wlheld** [Koenkk/zigbee2mqtt#6517]
## What happened
Just switched from Zigbee2MQTT 1.17.1 (koenkk/zigbee2mqtt:1.17.1) to 1.18.0 (koenkk/zigbee2mqtt:latest) and now Zigbee2MQTT won't start any more (see below). Configuration remained unchanged.

```
Zigbee2MQTT:info  2021-03-01 22:42:12: Logging to console only'
Zigbee2MQTT:info  2021-03-01 22:42:12: Starting Zigbee2MQTT version 1.18.0 (commit #3fd6619)
Zigbee2MQTT:info  2021-03-01 22:42:12: Starting zigbee-herdsman (0.13.72)
Zigbee2MQTT:error 2021-03-01 22:42:33: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-01 22:42:33: Failed to start zigbee
Zigbee2MQTT:error 2021-03-01 22:42:33: Exiting...
Zigbee2MQTT:error 2021-03-01 22:42:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.18.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T21_42_33_282Z-debug.log
```

## What did you expect to happen
I expected Z2M to start.

## How to reproduce it (minimal and precise)

My configuration (network key changed):
```
advanced:
  channel: 11
  homeassistant_legacy_triggers: false
  legacy_api: false
  log_level: info
  log_output:
    - console
  network_key: GENERATE
  pan_id: GENERATE
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt'
  user: zigbee2mqtt
  password: *************
permit_join: false
serial:
  port: /dev/ttyACM0
devices: devices.yaml
groups: groups.yaml
```` 

Service definition in docker-compose file:

```
version: '2'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_44_12-if00-port0:/dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
    image: koenkk/zigbee2mqtt:latest
    restart: always
    volumes:
      - /srv/zigbee2mqtt/zigbee2mqtt-volume:/app/data
```` 
## Debug info
Zigbee2MQTT version: 1.18.0 (official Docker image)
Adapter hardware: CC26X2R1 (slae'sh CC2652)
Adapter firmware version: 20210120
