### ISSUE TITLE
Group turns other groups lights on

### ISSUE THREAD

**Issue by DenisLug** [Koenkk/zigbee2mqtt#6780]
## What happened
I have created two groups of lights. Group 1 with 10 and group 2 with 3 Philips Hue lights. I can turn on and off all 10 lights of group 1 independently of group 2. When I turn group 2 on or off then also the lights of group 1 are triggered.

## What did you expect to happen
Lights of group 2 should turn on/off independently to group 1.

## How to reproduce it (minimal and precise)
I added the lights in the configuration.yaml and when it did not worked I also tried it by using the MQTT messages.

This is my database.db after adding the light with MQTT:
```
{"id":33,"type":"Group","groupID":1,"members":[{"deviceIeeeAddr":"0x00178801084e87b1","endpointID":11},{"deviceIeeeAddr":"0x00178801083f63e7","endpointID":11},{"deviceIeeeAddr":"0x00178801083f6ad1","endpointID":11},{"deviceIeeeAddr":"0x0017880108461b3e","endpointID":11},{"deviceIeeeAddr":"0x0017880108461b59","endpointID":11},{"deviceIeeeAddr":"0x00178801084e9514","endpointID":11},{"deviceIeeeAddr":"0x001788010846212d","endpointID":11},{"deviceIeeeAddr":"0x00178801084e87d4","endpointID":11},{"deviceIeeeAddr":"0x0017880108462bd8","endpointID":11}],"meta":{}}
{"id":34,"type":"Group","groupID":2,"members":[{"deviceIeeeAddr":"0x00178801084905f9","endpointID":11},{"deviceIeeeAddr":"0x0017880108461b4d","endpointID":11},{"deviceIeeeAddr":"0x00178801084ede43","endpointID":11}],"meta":{}}
```

This is the resulting configuration.yaml entry for groups:
```
groups:
  '1':
    friendly_name: '{"friendly_name": Sofa, "id":1}'
    devices:
      - 0x00178801084e87b1/11
      - 0x00178801083f63e7/11
      - 0x00178801083f6ad1/11
      - 0x0017880108461b3e/11
      - 0x0017880108461b59/11
      - 0x00178801084e9514/11
      - 0x001788010846212d/11
      - 0x00178801084e87d4/11
      - 0x0017880108462bd8/11
  '2':
    friendly_name: '{"friendly_name": Esstisch, "id":2}'
    devices:
      - 0x00178801084905f9/11
      - 0x0017880108461b4d/11
      - 0x00178801084ede43/11
```

By sending "ON" or "OFF" to the topic "zigbee2mqtt/2/set" the lights of both groups turn on/off.

## Debug info
Zigbee2MQTT version: 1.18.1 (commit #a43d1f3, Docker on Synology)
Adapter hardware: Conbee II
Adapter firmware version: 0x26580700
