### ISSUE TITLE
home-assistant fails on seeing firmware update message for ikea light bulb

### ISSUE THREAD

**Issue by oivindoh** [Koenkk/zigbee2mqtt#6833]
## What happened

Configured zigbee2mqtt to publish to mosquitto. Running latest stable images as of time of writing for all three products.

Home-assistant configured:

```yaml
          mqtt:
            username: x
            password: y
            discovery: true
            broker: mosquitto
```

Zigbee2mqtt configuration:

```yaml
          homeassistant: true
          permit_join: true
          mqtt:
            base_topic: zigbee2mqtt
            server: 'mqtt://mosquitto'
            user: x
            password: y
```

Home-assistant dies on startup with the following message:

```
2021-03-26 01:17:35 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zigbee2mqtt/0x90fd9ffffed957cd': '{"linkquality":140,"update":{"state":"idle"},"update_available":false}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 225, in state_received
    if values["state"] == "ON":
KeyError: 'state'
```

I believe this is a trådfri bulb, and hass appears to barf due to the missing "state" key in the main object. Logging output from hass is sparse other than the message above.

## What did you expect to happen

Hassio successfuly started with devices from mqtt added.

## How to reproduce it (minimal and precise)

1. home-assistant -> mqtt
2. Trådfri bulb producing 'zigbee2mqtt/0xbc33acfffe2ab956': '{"linkquality":124,"update":{"state":"available"},"update_available":true}' message.

## Debug info
Zigbee2MQTT version: docker.io/koenkk/zigbee2mqtt@sha256:778e379e7839da0e2f77676beccfff5085d6ab64fd8786027a08a4c540eda614
Home assistant version: docker.io/homeassistant/home-assistant@sha256:5093966633d8274143e3fa62db0391fe365cfcf9267a649031fd1b8c7978c189
Adapter hardware: Conbee II
Adapter firmware version: deCONZ_ConBeeII_0x26680700.bin.GCF 

Semi-related issues @ home-assistant: https://github.com/home-assistant/core/issues/44969 https://github.com/home-assistant/core/issues/44057
