### ISSUE TITLE
Ewelink Zigbee Flood sensor - TS0207 variant, identifies as model FNB54-WTS08ML1.0

### ISSUE THREAD

**Issue by Plawasan** [Koenkk/zigbee2mqtt#6925]
Intentionally NOT adding this as a new device as it's already supported, only under a different model ID - hope that's OK.

## Information about the device + link
Ewelink Zigbee Flood Sensor purchased from AliExpress:
https://www.aliexpress.com/item/1005001670656851.html

Device matches description/function/look of TS0207 already supported, pairs as 'FNB54-WTS08ML1.0'. So far I have been using it simply by updating the existing device entry in devices.js

```
line 14779 in 1.18.2
- zigbeeModel: ['TS0207'] 
+ zigbeeModel: ['TS0207','FNB54-WTS08ML1.0']
```

## data/database.db entry of the device
```
id: 27
type: EndDevice
ieeeAddr: '0x00158d00058c126a'
nwkAddr: 24006
manufId: 4478
manufName: fei
powerSource: Battery
modelId: FNB54-WTS08ML1.0
epList:
  - 1
endpoints:
  '1':
    profId: 260
    epId: 1
    devId: 1026
    inClusterList:
      - 0
      - 1
      - 1280
      - 25
    outClusterList: []
    clusters:
      genBasic:
        attributes:
          modelId: FNB54-WTS08ML1.0
          manufacturerName: fei
          powerSource: 3
          zclVersion: 2
          appVersion: 1
          stackVersion: 2
          hwVersion: 1
          dateCode: '20191118'
          swBuildId: "\0\0\0\0\0\0\0\0\0"
      ssIasZone:
        attributes:
          iasCieAddr: '0x00124b0021b7771f'
          zoneState: 1
      genPowerCfg:
        attributes:
          batteryVoltage: 28
          batteryPercentageRemaining: 160
          batteryAlarmState: 0
    binds: []
    configuredReportings: []
    meta: {}
appVersion: 1
stackVersion: 2
hwVersion: 1
dateCode: '20191118'
swBuildId: "\0\0\0\0\0\0\0\0\0"
zclVersion: 2
interviewCompleted: true
meta: {}
lastSeen: 1617370410492
```

Happy to add more info if needed.
