### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by NEA1971** [Koenkk/zigbee2mqtt#695]
Followed the installation instructions - when starting zigbee2mqtt (npm start) I get an error

> TypeError: Cannot read property 'port' of null

the complete output as shown in attached "error.txt"
[error.txt](https://github.com/Koenkk/zigbee2mqtt/files/2676104/error.txt)

and additionally the "configuration.yaml"
[config_yaml.txt](https://github.com/Koenkk/zigbee2mqtt/files/2676106/config_yaml.txt)

**Comment by Koenkk** [comment]
Add 2 spaces before port:

```yaml
# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port:   /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E1A42D-if00
```
