### ISSUE TITLE
Legrand 067774 right switch not working

### ISSUE THREAD

**Issue by ytzelf** [Koenkk/zigbee2mqtt#7020]
Hi,

I'm using a ConBee 2 and the latest-dev Docker image on the latest Debian for host OS.

I've successfully adopted & operated a single switch Legrand 067773 but both my Legrand 067774 have inoperative right switches (although they are correctly adopted).

Left switch provides the expected lines in log : 
`Zigbee2MQTT:info  2021-04-09 21:27:14: MQTT publish: topic 'zigbee2mqtt/0x00047400008acca9', payload '{"action":"off_left","linkquality":41}'`

Right switch (either on or off) triggers the following sequence instead of expected behavior similar to left switch
```
zigbee2mqtt             | Zigbee2MQTT:error 2021-04-09 21:23:14: Failed to configure '0x00047400007e2d7c', attempt 1 (Error: Bind 0x00047400007e2d7c/2 genPowerCfg from '0x00212effff0619dd/1' failed (Error: status: 130)
zigbee2mqtt             |     at DeconzAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:711:23)
zigbee2mqtt             |     at Generator.next (<anonymous>)
zigbee2mqtt             |     at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
zigbee2mqtt             | Zigbee2MQTT:error 2021-04-09 21:23:20: Failed to configure '0x00047400008acca9', attempt 1 (Error: Bind 0x00047400008acca9/1 genPowerCfg from '0x00212effff0619dd/1' failed (waiting for response TIMEOUT)

```
Here's my full configuration if useful : 
```
homeassistant: false

permit_join: true

mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://vernemq'

serial:
  port: /dev/ttyACM0
  adapter: deconz

frontend:
  port: 8099

experimental:
  new_api: true

devices:
  '0x0004740000aefc54':
    friendly_name: '0x0004740000aefc54'
    retain: true
  '0x00047400008acca9':
    friendly_name: '0x00047400008acca9'
    retain: true
  '0x00047400007e2d7c':
    friendly_name: '0x00047400007e2d7c'
    retain: true
```
Thanks a lot for the already amazing work :)
