### ISSUE TITLE
use home assistant sensor for switch

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#704]
I know I can create an automation with the following example in HA:
```
automation:
  - alias: Respond to button clicks
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/<FRIENDLY_NAME'
    condition:
      condition: template
      value_template: '{{ "single" == trigger.payload_json.click }}'
    action:
      entity_id: light.bedroom
      service: light.toggle
```

Is it possible to create one based on the sensor.<myswitch>, I'd like to have as little config as possible in zigbee2mqtt and just rename entities in HA, so if I cna avoid using the GUID name in the automation and use the HA switch name which I've customised I'm thinking it should be a bit cleaner.

From what I can see the switch gets set to the state 'single' but it never goes back to 'off' or anything else.
