### ISSUE TITLE
Change state type on MQTT payload from boolean to string 

### ISSUE THREAD

**Issue by snakuzzo** [Koenkk/zigbee2mqtt#7066]
## Is your feature request related to a problem? Please describe
According to Home Assistant documentation about `MQTT Binary Sensor` entities ([HERE](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#payload_on)), Z2M publish states as boolean and not as string

This is the message published on MQTT broker...

`zigbee2mqtt/mywindow {"battery":97,"contact":true,"linkquality":72,"temperature":24,"voltage":2995}`

...and this is my `binary_sensor`...

```yaml
binary_sensor:

  - platform: "mqtt"
    name: "mywindow"
    state_topic: "zigbee2mqtt/mywindow"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.contact }}"
    payload_on: false
    payload_off: true
    device_class: "window"
```

Take a look at https://github.com/keesschollaart81/vscode-home-assistant/issues/1148

## Describe the solution you'd like
Publish states `true` and `false` as string in MQTT payload

## Describe alternatives you've considered
...apply template on HA ?
I think it is necessary to update the documentation related to manual configurations, applying the templates

```yaml
  - platform: "mqtt"
    name: "mywindow"
    state_topic: "zigbee2mqtt/mywindow"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ 'true' if value_json.contact == true else 'false' }}"
    payload_on: "false"
    payload_off: "true"
    device_class: "window"
```

## Additional context
![image](https://user-images.githubusercontent.com/7205371/114555379-eb68a380-9c67-11eb-80e5-34331513c1cd.png)
