### ISSUE TITLE
Zigbee2mqtt on Windows Host

### ISSUE THREAD

**Issue by Diddlik** [Koenkk/zigbee2mqtt#7218]
I am trying to install z2m on the Windows Hsot.
It is Node 15 installed, z2m 18.2-dev
Here is the config:

```
homeassistant: false
permit_join: true
mqtt:
    base_topic: zigbee2mqtt
    server: "mqtt://192.168.1.50:1884"
serial:
    port: \\.\COM16
advanced:
    network_key: GENERATE
    log_level: debug
    rtscts: false
devices: []
```
## Debug info
Output: ```

Zigbee2MQTT:debug 2021-04-27 09:45:42: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"L:\\z2m\\zigbee2mqtt\\data\\coordinator_backup.json","databaseBackupPath":"L:\\z2m\\zigbee2mqtt\\data\\database.db.backup","databasePath":"L:\\z2m\\zigbee2mqtt\\data\\database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"\\\\.\\COM16","rtscts":false}}'
Zigbee2MQTT:error 2021-04-27 09:45:42: Failed to start zigbee
Zigbee2MQTT:error 2021-04-27 09:45:42: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-27 09:45:42: Exiting...
Zigbee2MQTT:error 2021-04-27 09:45:42: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.join (node:path:397:7)
    at Object.joinPath (L:\z2m\zigbee2mqtt\lib\util\data.js:17:30)
    at writeDevicesOrGroups (L:\z2m\zigbee2mqtt\lib\util\settings.js:194:38)
    at write (L:\z2m\zigbee2mqtt\lib\util\settings.js:199:5)
    at Object.set (L:\z2m\zigbee2mqtt\lib\util\settings.js:403:5)
    at Zigbee.start (L:\z2m\zigbee2mqtt\lib\zigbee.js:52:22)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Controller.start (L:\z2m\zigbee2mqtt\lib\controller.js:105:13)
```


Zigbee2MQTT version: 18.2-dev
Adapter hardware: CC1352P-2 Launchpad
Adapter firmware version: CC1352P2_CC2652P_launchpad_coordinator_20210120
