### ISSUE TITLE
Problem  with hue_correction 

### ISSUE THREAD

**Issue by pterodaktil02** [Koenkk/zigbee2mqtt#7311]
## What happened
Mistake in documentation https://www.zigbee2mqtt.io/devices/GL-S-004Z.html#gledopto-gl-s-004z and other

## How to reproduce it (minimal and precise)
1. write in devices.yaml  hue correction (taken from sample)
```
'0x00xxxxxxxxx':
  friendly_name: hue_corrected
  hue_correction:
      - in: 28
          out: 45
      - in: 89
          out: 109
      - in: 184
          out: 203
      - in: 334
          out: 318
```
2. restart  z2m 
recive YAMLException: bad indentation of a mapping entry at line.... in logs
Correct  to:
```
  hue_correction:
      - in: 28
        out: 45
      - in: 89
        out: 109
      - in: 184
        out: 203
      - in: 334
        out: 318
```
The restart was successful.

But it seems  not work (lamp  with hue correction and  without it have  similar  color temp)

for  check   i set   
 this  color map 
 
   ```
hue_correction:
      - in: 150
        out: 370
      - in: 220
        out: 370        
      - in: 370 
        out: 370
      - in: 500
        out: 370  
``` 
I expected that at any set color temperature, the lamp would shine in one color.
But the color of the lamp changes     
 
## Debug info
Zigbee2MQTT version:  1.18.3
Adapter hardware:   CC2652 (zStack3x0)
Adapter firmware version: 20201113
