### ISSUE TITLE
Friendly name not working

### ISSUE THREAD

**Issue by RolluS** [Koenkk/zigbee2mqtt#740]
Hi, 

First, thanks for the nice work. I was on 0.2.0 and decide to update.

I loose friendly_name on all the sensors entity on home assistant

I can reproduce by updating from 0.2.0,  to 1.0.0, or 1.0.1
Downgrading to v0.2.0 solve the issue.

Config: 
All under docker on an UnRaid server:
- homeassistant/home-assistant
- spants/mqtt

Here is the relevant configuration for a sensor:
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.2'
serial:
  port: /dev/ttyACM0
devices:
   '0x00158d00023495a5':
      friendly_name: Mouvement_entrée
      retain: false
```
When that's working as expected:
![zigbee2mqtt 0 2 0](https://user-images.githubusercontent.com/482206/50346948-4aa0c800-0534-11e9-970d-416f8254438e.PNG)

When that's not working: You can see on the next pic the strange behavior of "Entité". Friendly_name is good for battery topic, but not for binary_sensor.

![zigbee2mqtt 1 0](https://user-images.githubusercontent.com/482206/50346953-4ffe1280-0534-11e9-8433-9e850f736b92.PNG)
