### ISSUE TITLE
unit of measurement is missing (GZCGQ01LM)

### ISSUE THREAD

**Issue by Alfagek** [Koenkk/zigbee2mqtt#7638]
## What happened
No Unit of measurement
## How to reproduce it (minimal and precise)
Unit off measurment is missing from "illuminance".
"illuminance Lux", "Battery", "Signal" are good
See also: https://github.com/home-assistant/core/issues/50674
## Debug info
Zigbee2MQTT version: 1.18.1
Adapter hardware: CC2531
Adapter firmware version:

**Comment by Koenkk** [comment]
the `illuminance` is a legacy sensor, this is a raw value and has no unit. the `illuminance_lux` is the illuminance in lux (calculated from the raw value).

**Comment by Alfagek** [comment]
Okay thanks for the explanation @Koenkk. But because the “illuminance” is more exact, I use that in Home Assistant. But because it has no unit I can’t use it in home assistant automation UI

**Comment by Alfagek** [comment]
@Koenkk , is there a other posibillity to set a unit in my own config to use the "illuminance"?

**Comment by Koenkk** [comment]
Adding this to your config should do it:

```
devices:
  "0x12345678":
    friendly_name: my_sensor
    homeassistant:
      illuminance:
        unit_of_measurement: 'lx'
```
