### ISSUE TITLE
Lights in group turn on immediately after turning off

### ISSUE THREAD

**Issue by denysdovhan** [Koenkk/zigbee2mqtt#7816]
## What happened

I have [4 Aqara Bulbs](https://www.zigbee2mqtt.io/devices/ZNLDP12LM.html) joined in a group called `main_light`. Sometimes, when I turn off lights they turn off, but immediately turn on after.

Here is a video of how this happens: https://user-images.githubusercontent.com/3459374/122544137-2b1b8500-d035-11eb-8dbf-1a1cf9bb2c4c.MOV

## What did you expect to happen

I expect the light to turn off when I turn them off, without turning on again.

## How to reproduce it (minimal and precise)

I didn't find a reliable way to reproduce this problem. It just happens from time to time, usually, after lights weren't turned on for a long time. Other bulbs that aren't joined into groups work fine. 

My group:

```yaml
'1':
  friendly_name: living_room_main_light
  transition: 2
  devices:
    - 0x00158d0002d3c856/1
    - 0x00158d000450cca4/1
    - 0x00158d00045ec07b/1
    - 0x00158d0002d71dab/1

```

## Debug info

Zigbee2MQTT version: 1.19.1 (commit #9bd4693)
Adapter hardware: CC2531
Adapter firmware version: `{"meta: 
{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}`

My setup is described here: https://denysdovhan.com/smart-home/hardware/#zigbee-network
docker-compose is here: https://github.com/denysdovhan/smart-home/blob/master/docker-compose.yaml
