### ISSUE TITLE
Color ignored when specifying brightness in automation with Hue color bulb

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#788]
When turning on my hue lights with an automation in homeassistant if I provide both brightness and color as parameters color is ignored.

Example:
```
 - alias: Adam Light Switch
   trigger:
     platform: mqtt
     topic: 'zigbee2mqtt/Adams_Switch'
   condition:
     condition: and
     conditions:
      - condition: template
        value_template: "{{ 'single' == trigger.payload_json.click}}"
      - condition: state
        entity_id: light.0x0017880110460c0f_light
        state: 'off'
   action:
     - service: homeassistant.turn_on
       entity_id: light.0x0017880110460c0f_light
       data:
         hs_color: [16.471,100]
         brightness: 255
```
See log here:
[https://pastebin.com/wMAiA8xw](url)

The only way around this I have found is to to turn on the light with the turn_on service then set the color afterwards as a secondary action.
