### ISSUE TITLE
Strange problem connexion zigbee2mqtt mosquitto broker

### ISSUE THREAD

**Issue by thierry-rhone** [Koenkk/zigbee2mqtt#7900]
## What happened
**imcomplete exposition of cover**
I installed cover switch (TS130F) on raspberry 

Expose (read from zigbee2mqtt in sidebar)

**cover_1**
state  Close ? open
position
moving
calibration
backlight_mode
motor_reversal
linkquality

in configuration entities I have
<pre>
name                      Entity ID                                Integration
cover 1                   cover.cover_1                            MQTT
cover 1 backlight.mode    sensor.cover_1backlight.mode             MQTT
cover 1 calibration       binary_sensor.cover_1_calibration        MQTT
cover 1 linkquality       sensor.cover_1_linkquality               MQTT
cover 1 motor reversal    binary_sensor.cover_1_motor_reversal     MQTT
cover 1 moving            sensor.cover_1_moving                    MQTT
</pre>
**All was correct I can move cover directly from zigbee2mqtt in sidebar or lovelace**

## What did you expect to happen
I transferred my hassio to a debian 10 nuc (ACEPC AK1) and recovered a snapshot (ha supervised  in docker)
All work fine except
My exposition in zigbee2mqtt is the same and I can move directly cover with state open close
But
in configuration entities the first line is unavailable (red circle with arrow)
<pre>
name                      Entity ID                                Integration            surface       Statut
cover 1                   cover.cover_1                            MQTT                                  (!)
cover 1 backlight.mode    sensor.cover_1backlight.mode             MQTT
cover 1 calibration       binary_sensor.cover_1_calibration        MQTT
...
</pre>

If I delete the zigbee device and join it again I don't recover the first line but recover the other 5

I tried to replace zig-a-zig-ah with CC2531 the problem remains the same 

Maybe a timer problem as my nuc is very faster

## Debug info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: Electrolama zig-a-zig-ah! (and to test CC2531)
Adapter firmware version: CC2652R_coordinator_20210120
Mosquitto broker version: 6.0.1

**Comment by thierry-rhone** [comment]
I am trying to do a manual configuration for the line 
cover 1                   cover.cover_1                            MQTT  
I write in home assistant configuration.yaml 
``` 
cover:
  - platform: mqtt                                                 #692
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/cover_1/set"
    position_template: "{{ value_json.position }}"
    set_position_template: "{ \"position\": {{ position }} }"
    set_position_topic: "zigbee2mqtt/cover_1/set"
    position_topic: "zigbee2mqtt/cover_1
#------
  - platform: template
 ...
```
Error loading /config/configuration.yaml: while parsing a block mapping
in "/config/configuration.yaml", line 692, column 5
expected <block end>, but found '<scalar>'
in "/config/configuration.yaml", line 705, column 25

can i mix discovery and manual configuration ?

Someone can help me to write corrects lines
Thanks
