### ISSUE TITLE
Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by halkeye** [Koenkk/zigbee2mqtt#819]
Just flashed the new adapter, hooked it up, and tried to pair my blinds. I have no idea what zigbee adapter the blinds has, but it actually errors out:

Added a console.log right before the error line 

```
Mon, 07 Jan 2019 02:30:05 GMT zigbee-shepherd Device: 0x00124b000bebb951 join the network.
message { type: 'devIncoming',
  endpoints: [],
  data: '0x00124b000bebb951' }
  zigbee2mqtt:error 2019-1-6 18:30:05
        {"message":"Cannot read property 'device' of undefined","stack":"TypeError: Cannot read property 'device' of undefined\n    at Controller.onZigbeeMessage (/home/pi/zigbee2mqtt/lib/controller.js:95:55)\n    at Zigbee.onMessage (/home/pi/zigbee2mqtt/lib/zigbee.js:173:18)\n    at emitOne (events.js:116:13)\n    at ZShepherd.emit (events.js:211:7)\n    at ZShepherd.<anonymous> (/home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:100:14)\n    at emitOne (events.js:116:13)\n    at ZShepherd.emit (events.js:211:7)\n    at /home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/event_handlers.js:227:18\n    at _fulfilled (/home/pi/zigbee2mqtt/node_modules/q/q.js:854:54)\n    at self.promiseDispatch.done (/home/pi/zigbee2mqtt/node_modules/q/q.js:883:30)"}
```

The entire log (`DEBUG=* node index.js 2>&1 | tee output.log`) is at https://gist.github.com/halkeye/6468a5cab7c5feb6dbec4b9557d33268

**Comment by halkeye** [comment]
Changed it to:
```
if (message.endpoints && message.endpoints.length && message.endpoints[0].device) {
             device = message.endpoints[0].device;
         }
```

Gives me:
```
  zigbee2mqtt:debug 2019-1-6 18:37:15 Received zigbee message of type 'devIncoming' with data '"0x00124b000bebb951"'
  zigbee2mqtt:info 2019-1-6 18:37:15 Device incoming...
  zigbee2mqtt:info 2019-1-6 18:37:15 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:warn 2019-1-6 18:37:15 Message without device!
message { type: 'devStatus', endpoints: [], data: 'online' }
  zigbee2mqtt:debug 2019-1-6 18:37:15 Received zigbee message of type 'devStatus' with data '"online"'
  zigbee2mqtt:warn 2019-1-6 18:37:15 Message without device!
```

**Comment by halkeye** [comment]
so is the zigbee implementation on this device faulty?

**Comment by khzd** [comment]
Hello
Not faulty, may bébés the pairing is not complete or the device is not known !
Please share your configuration and dB for help

**Comment by halkeye** [comment]
I'm not sure whats useful in the configuration:

DB (pretty printed through jq): https://gist.github.com/b7c27296c0971775b7da04896447144e

config:
```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://<server>'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
  disable_led: true

advanced:
   log_level: debug
```
