### ISSUE TITLE
last_reset not updating for some energy sensors or energy value not correct

### ISSUE THREAD

**Issue by McGiverGim** [Koenkk/zigbee2mqtt#8272]
## What happened

Home Assistant has a new Energy Dashboard. It was supported in PR https://github.com/Koenkk/zigbee2mqtt/pull/8187 
The energy sensors need to have a `last_reset` value but something seems not to be working.

This is a LLKZMK11LM Xiaomi relay. The last reset seems to be a fixed value:

![image](https://user-images.githubusercontent.com/2673520/128469546-ccbf26d1-584a-4641-bf31-b36e43606659.png)

But the sensor value is resetting itself, I don't know under which circumstances, from time to time. For example here you can see two resets in the latest 24 hours:

![image](https://user-images.githubusercontent.com/2673520/128469316-260f926e-8cda-4a1f-b0ad-85cc7152b067.png)

The result of this is that the entity appears with a "negative" value in the new dashboard:

![image](https://user-images.githubusercontent.com/2673520/128470018-4a83eb45-c606-4351-a48f-cb8c0d00f631.png)

The most strange thing is that I have other two similar relays, and they seem not to be resetting never. The three of them work perfectly (the only difference is that the other two have the interlock enabled but I doubt it matter). So I'm not sure if this is a hardware problem (despite it seems to be working ok), or some bug in the software.

## What did you expect to happen

The last reset value to be correct or the energy value of the sensor not resetting itself. 

Maybe in my case is some kind of problem in the hardware, but I suppose that at some point the energy values will reset, maybe when we reconnect the device for example and we press the reset button for 10 seconds, so I suppose we need to detect it and adjust the `last_reset` value.

## Debug info
Zigbee2MQTT version: 1.21.0-1
Adapter hardware: CC2652P (E72 by Egony)
Adapter firmware version: zStack3x0.20210708

**Comment by McGiverGim** [comment]
Another difference with the problematic device, is that I define it as light and not as a switch:
```yaml
'0x00158d00044bda5b':
  friendly_name: rele_cocina
  homeassistant:
    switch_l1:
      type: light
      object_id: light1
    switch_l2:
      type: light
      object_id: light2
'0x00158d00044adbcc':
  friendly_name: rele_comedor_mesa
'0x00158d0003f453e3':
  friendly_name: rele_comedor_centro
```
