### ISSUE TITLE
configuration variable "json_attributes" is deprecated, replace with "json_attributes_topic"

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#840]
I replaced all my json_attributes with json_attributes_topic and I still get a bunch of those errors in my ha log.
I think those errors are thrown by the autodiscovered devices which most probably still use json_attributes.

Am I right? How to fix this. Will there be an update soon?

https://community.home-assistant.io/t/json-attributes-topic-json-attributes-deprecated/90652

**Comment by Koenkk** [comment]
As I understand correctly `json_attributes_topic` is more than only a name change. What exactly did you change/

**Comment by h4nc** [comment]
You are right. I use an example to clarify that:

old:
```
- platform: "mqtt" 
  name: zigbee_cube_bat
  state_topic: "zigbee2mqtt/Zigbee Cube"
  value_template: "{{ value_json.battery | round(0) }}"
  device_class: battery 
  json_attributes: 
    - "linkquality"
```
new:
```
- platform: "mqtt" 
  name: zigbee_cube_bat
  state_topic: "zigbee2mqtt/Zigbee Cube"
  value_template: "{{ value_json.battery | round(0) }}"
  device_class: battery 
  json_attributes_topic: "zigbee2mqtt/Zigbee Cube"
```

So it looks like with this it isn't possible any more to chose which attributes you want to add, because this will add all of the attributes. Even the one that is already chosen for the value_template.
