### ISSUE TITLE
Settings to all devices

### ISSUE THREAD

**Issue by adriannowaq** [Koenkk/zigbee2mqtt#8574]
Is it possible to add debounce: true and retain:false to all devices in configuration.yaml? Including new paired?

**Comment by sjorge** [comment]
Yes! You can add them under `device_options`
e.g.

```yaml
device_options:
  retain: true
  legacy: false
  debounce: 0.5
  filtered_optimistic:
    - color
    - color_temp
    - color_mode
  qos: 2
```

This is applied to all devices. (Do note debounce takes a value in seconds not true/false)
