### ISSUE TITLE
N/A on all devices either powered or battery operated

### ISSUE THREAD

**Issue by kaczkalolo** [Koenkk/zigbee2mqtt#8609]
**Description of problem:**
Last seen: N/A on all devices either powered or battery operated
In the frontend all devices have N/A in Last seen attribute.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Zigbee2MQTT version
1.21.0 commit: unknown
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: *******
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - *
    - *
    - *
    - ***
    - ***
  availability_timeout: 60
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
```

**Running platform (details from Suypervisor > System)**
```
core-2021.8.8
supervisor-2021.06.8
Home Assistant OS 6.2
```
