### ISSUE TITLE
Xiaomi Switch automations broken

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#866]
The following automation used to work:

```
 - alias: Yolanda Light on Bright
   trigger:
     platform: mqtt
     topic: 'zigbee2mqtt/Yolandas_Switch'
   condition:
     condition: and
     conditions:
      - condition: template
        value_template: "{{ 'triple' == trigger.payload_json.click}}"
   action:
     - service: light.turn_on
       entity_id: light.yolanda_color_light_light
       data:
         brightness: 250
         xy_color: [0.442,0.378]
```

If I check the topic ('zigbee2mqtt/Yolandas_Switch') in the zigbee2mqtt log I can clearly see triple is being published the the automation doesnt work.  It appears that my other button related automations are also broken.

Could this have been caused by a change I was unaware of?
