### ISSUE TITLE
aqara temperature/humidity sensor round value for auto discovery

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#870]
The temperature and the humidty value of the aqara temperature sensor is reported with two decimal places. 

I think this sensor has an accuracy around 0.5 degrees, so it does make sense to show two decimal places. 

Sensor name: WSDCGQ11LM

`value_template: "{{ value_json.humidity | round(0) }}"`

This would round the reported data to a plausible value.

**Comment by khzd** [comment]
Hi
You can set the precision in configuration.yaml for all devices or for a specific one, see the doc

**Comment by h4nc** [comment]
I couldn't find it in the docs.

Not here 
https://koenkk.github.io/zigbee2mqtt/configuration/device_specific_configuration.html
https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html

Could you point to the right url or show an example?

**Comment by h4nc** [comment]
@Koenkk is there a way to set the precision in the configuration.yaml file of zigbee2mqtt?

**Comment by ryanbeaton** [comment]
In the dev branch only at the moment

https://github.com/Koenkk/zigbee2mqtt/issues/708#issuecomment-451907453

**Comment by Koenkk** [comment]
@khzd yes, next release will be 1.1, planned for 30 January if all firmware stability tests are OK.

**Comment by h4nc** [comment]
```
devices:
  '0xID1':
    friendly_name: Zigbee Humidity
    retain: false
    device_options: 
      humidity_precision: 0

```
Do I have to format it like this?

Also I have a motion sensor set up like this:

```
  '0xID2':
    friendly_name: Zigbee Bewegung WZ
    occupancy_timeout: 60
```
Should I change it to this?

```
  '0xID2':
    friendly_name: Zigbee Bewegung WZ
    device_options:
     occupancy_timeout: 60
```
