### ISSUE TITLE
zigbee network freezes(?) around 1-2 times a week using CC2652RB adapter.

### ISSUE THREAD

**Issue by kpcz** [Koenkk/zigbee2mqtt#8711]
Hi all. I use zigbee2Mqtt with Slaesh's CC2652RB adapter. There are cases, at least once a week when zigbee network comes unavailable (no sensors or devices are responding and reporting in logs), Zigbee2mqtt addon restart helps every time.

I  have around 52 devices in network, from which 5 are powered devices - routers. 

Slaesh's CC2652RB adapter have the firmware version as it was shipped - 20200805
zigbee2mqtt is on 1.21.1-1 version.

In standard logs, it does not show anything when zigbee network hangs. For now turned on   log_level: debug, do I need to turn on more for debbugging the issue?

Could it be that the old FW of the adapter is causing some issues, and it needs to be reflashed to a newer FW? Or as the restart of the HA addon helps, it means the adapter is working fine, but there is something wrong with addon config? As I am avoiding reflashing the FW of the adapter, as I am afraid that I will need to re-join all the end devices, that would be real pain..

For now the config looks like this, maybe something wrong in there?

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: _deleted_
  password: _deleted_
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_F2_24-if00-port0
advanced:
  ikea_ota_use_test_url: true
  log_level: debug
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: false

```

Looking forward for some ideas how I could debbug the issue, or at what direction to search, 
Side note, around 1m from zigbee dongle (what is connected via usb cord) there is also IKEA tradfri GW, with around 6 devices, if that could cause any issues.

thank you.
