### ISSUE TITLE
automation with Aqara switch don't works

### ISSUE THREAD

**Issue by vpomax** [Koenkk/zigbee2mqtt#888]
I would like to use this automation to turn on/off my Xiaomi Yeelught with a Aqara Switch button... but it do not works... why?

```
  - alias: Switch Yeelight
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/sensor.0x00158d0001593043_click'
    condition:
      condition: template
      value_template: '{{ "single" == trigger.payload_json.click }}'
    action:
      service: light.toggle
      entity_id: light.yeelightw1
```

**Comment by vpomax** [comment]
@Bojan023 
Home Assistant discover the butto as...  sensor.0x00158d0001593043_click

I tried to modify the automation calling it...

'sensor.0x00158d0001593043_click'

or

'sensor.0x00158d0001593043`

but unsuccesfull

**Comment by vpomax** [comment]
I found that automation based on template mqtt do not start.
Temporarily I solved in another way... not using template mqtt but using template: state

Since my Hassio discover Xiaom switch and call it "sensor.0x00158d0001593043_click"
I created a new automation based o template state...
```
  - alias: Turn_on_off_yeelight
    trigger:
      platform: state
      entity_id: sensor.0x00158d0001593043_click
      to: 'single'
    action:
      service: light.toggle
      entity_id: light.yeelightw1
```

and it works fine!
