### ISSUE TITLE
Temperature and Pressure Calibration do not work as expected

### ISSUE THREAD

**Issue by TheRealWaldo** [Koenkk/zigbee2mqtt#8930]
## What happened
`temperature_calibration` and `pressure_calibration` only work 'sometimes'.

## What did you expect to happen
Both should work at all times.

## How to reproduce it (minimal and precise)

```
'0x00158d0003231617':
  friendly_name: Pressure Sensor
  device_options:
    temperature_calibration: -0.4
    pressure_calibration: 120
```

After several minutes and a few updates from the device, the calibration was applied.  After a few dozen updates (approximately 40 minutes later),  calibration stopped working.

I noticed this while calibrating sensors for pressure; spikes when it was working, followed by a dip when it wasn't.  It was most evident on the pressure calibration (as you can see, it was 120hPA off).

I could find nothing in logs as to why.

Also, it would be great to be able to calibrate humidity!

## Debug info
Zigbee2MQTT version: 1.21.1-1 (hass.io addon)
Adapter hardware:  Conbee II
