### ISSUE TITLE
Zigbee2MQTT Version 1.21.2-dev & Homeassistant Generic Thermostat & Hama 00176593 & Zigbee2Mqtt do not work - need help!

### ISSUE THREAD

**Issue by zibous** [Koenkk/zigbee2mqtt#9185]
## What happened
The control takes place via Lovelace thermostat. Inital, when I restart home assistant, then the temperature is set for all thermostats via the script. 

**Ater a certain Time, however, this is always reset the `current_heating_setpoint` to 16 degrees ???**

```
init_climate_thermostat:
  alias: Heizungsthermostate einstellen
  sequence:
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-bad/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_bad') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-office/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_office') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-wc/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_wc') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-wohnzimmer1/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_wohnzimmer1') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-wohnzimmer2/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_wohnzimmer2') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-kitchen/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_kitchen') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-kindenzimmer1/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_kindenzimmer1') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-kinderzimmer2/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_kindenzimmer2') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-schlafzimmer/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_schlafzimmer') | float }}"
    - service: mqtt.publish
      data_template:
        topic: conbee2mqtt/thermostat-fitnessraum/set/current_heating_setpoint
        payload_template: "{{ states('input_number.thermostat_fitnessraum') | float }}"

```

## What did you expect to happen
**Is it due to the Zigbee2MQTT or the Homeassistant configuration?** 

```- platform: "mqtt"
  name: Thermostat Bad
  temperature_unit: "C"
  initial: 25.00
  temp_step: 0.5
  min_temp: "5"
  max_temp: "30"
  json_attributes_topic: conbee2mqtt/thermostat-bad
  temperature_command_topic: "conbee2mqtt/thermostat-bad/set/current_heating_setpoint"
  availability_topic: "conbee2mqtt/bridge/state"
  current_temperature_topic: "conbee2mqtt/thermostat-bad"
  current_temperature_template: "{{ value_json.local_temperature }}"
  temperature_state_topic: "conbee2mqtt/thermostat-bad"
  temperature_state_template: "{{ value_json.current_heating_setpoint }}"
  mode_state_topic: "conbee2mqtt/thermostat-bad"
  mode_state_template: "{{ value_json.system_mode }}"
  mode_command_topic: "conbee2mqtt/thermostat-bad/set/system_mode"
  modes:
    - "off"
    - "heat"
    - "auto"
  action_topic: "conbee2mqtt/thermostat-bad/set/system_mode"
  action_template: "{% set values = {'idle':'off','heat':'heating','auto':'auto'} %}{{ values[value_json.running_state] }}"
  away_mode_command_topic: "conbee2mqtt/thermostat-bad/set/value_json.away_mode"
  away_mode_state_topic: "conbee2mqtt/thermostat-bad"
  away_mode_state_template: "{{ value_json.away_mode }}"
  payload_on: "true"
  payload_off: "false"
  retain: true

```

## How to reproduce it (minimal and precise)
![Bildschirmfoto 2021-10-17 um 08 26 20](https://user-images.githubusercontent.com/30198737/137615062-a0a3789d-98ea-4a13-97be-4ff7d8b95de6.png)

![122682378-42a36b00-d1f9-11eb-93a9-a94ede47a3a8](https://user-images.githubusercontent.com/30198737/137615068-52a89971-b397-49c4-a975-58df770c3e8b.png)

![Bildschirmfoto 2021-10-17 um 08 39 30](https://user-images.githubusercontent.com/30198737/137615080-b91351e5-70e6-4d3f-a49c-39bba1300a33.png)

## Debug info
Zigbee2MQTT version: Version 1.21.2-dev
Adapter hardware: Conbee II
Adapter firmware version: latest

```
{"anti_scaling":"ON",
  "away_mode":"OFF",
  "battery_low":false,
  "child_lock":"UNLOCK",
  "current_heating_setpoint":16,
  "device":{
    "applicationVersion":85,
    "dateCode":"",
    "friendlyName":"thermostat-wohnzimmer2",
     "hardwareVersion":1,
     "ieeeAddr":"0x847127fffe0954af",
     "manufacturerID":4098,
      "manufacturerName":"_TZE200_yw7cahqs",
      "model":"SEA801-Zigbee/SEA802-Zigbee",
      "networkAddress":57759,
      "powerSource":"Battery",
      "stackVersion":0,
      "type":"EndDevice",
      "zclVersion":3
     },
    "elapsed":234,
    "frost_detection":"ON",
    "last_seen":"2021-10-17T08:51:28+02:00",
    "linkquality":215,
    "local_temperature":20.8,
    "local_temperature_calibration":0,
    "preset_mode":"none",
    "system_mode":"auto",
    "window_detection":"ON"
}
```
