### ISSUE TITLE
Zigbee2Mqtt gives me 502: Bad Gateway

### ISSUE THREAD

**Issue by dyarfaradj** [Koenkk/zigbee2mqtt#9277]
## What happened
I've got a CC2531 chip that I flashed with the correct firmware and it's tuning on and in the zigbee2mqtt logs I can see that it finds it.  Before I had flashed the CC2531 chip Zigbee2Mqtt gave me error so I assume the chip is working fine.

When I try to open the Zigbee2Mqtt interface I get a 502: Bad Gateway and in the supervisor log I get this message:
```
21-10-21 11:05:39 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:8099 ssl:default [Connect call failed ('172.30.33.5', 8099)]
```

Zigbee2mqtt
Current version: 1.21.2-1

![](https://community-assets.home-assistant.io/original/3X/e/f/ef4d37dae9316191c69cf6565f648850544830c1.png)

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  user: mqtt
  password: xxxxx
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```
I've also tried with:

> mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
same problem.

When I set 

> permit_join: true

I get this, but it still doesn't work:

![](https://community-assets.home-assistant.io/original/3X/5/4/5475bd9c1d311b2a20f9d066e245534f68a66fe1.png)

## What did you expect to happen
Open the GUI without any 502 error.

## How to reproduce it (minimal and precise)

Start Zigbee2MQTT, go to ingress

## Debug info
Zigbee2MQTT version: 1.21.2-1
Adapter hardware: CC2531
Adapter firmware version: https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20201127.zip

Link to community home where I've tried different stuff that doesn't work https://community.home-assistant.io/t/zigbee2mqtt-gives-me-502-bad-gateway/348856
