### ISSUE TITLE
No status change for gas (gas sensor: HEIMAN HS1CG-E)

### ISSUE THREAD

**Issue by noirrak** [Koenkk/zigbee2mqtt#9318]
Hello,
Z2M only receives "false" state for gas in all situations (look below). What could be the reason for this?
FYI: Integration with ZHA was successful - gas sensor is working properly.

**Test button result:**
```
Debug Received Zigbee message from '0x000d6f001539fdba', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":34}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f001539fdba', payload '{"battery_low":false,"gas":false,"linkquality":42,"tamper":false}'
```

**Lighter gas result:**
```
Debug Received Zigbee message from '0x000d6f001539fdba', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f001539fdba', payload '{"battery_low":false,"gas":false,"linkquality":41,"tamper":false}'
```

**Z2M config:**
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: [MY_PASS]
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
    - X
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**MQTT config:**
```
logins:
  - username: mqtt
    password: [MY_PASS]
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

**My setup:**
- RPi 3 Model B
- Zigbee adapter: CC2652P
- Zigbee2mqtt 1.21.2
- Home Assistant OS 6.5 (64-bit)
- Core: core-2021.10.5
- Supervisor: supervisor-2021.10.0
