### ISSUE TITLE
Lights go unresponsive from time to time

### ISSUE THREAD

**Issue by hmorkemo** [Koenkk/zigbee2mqtt#9554]
Many of my lights (Ikea and Philips) go unavailable from time to time (several times pr. week), and can't be contolled. After a while, sometimes, they come back online again.
Sometimes a refresh in the z2m device panel brings the light back to life. But usually that doesn't help. Often I have to delete / add it.
It seems like the lights farthest away from the controller suffer the most.
All lights are quite evenly distributed in and around the house. The farthest distance from the ConBee is 20 meters.
They are uncontrollable both from HA and from the Zigbee2mqtt UI.
The same problem occurs with my Ikea Fyrtur blinds from time to time.
Typical error message in the zigbee2mqtt log:
"Publish 'set' 'state' to 'Utebod Lys2' failed: 'Error: Command 0x5c0272fffe840e54/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'"
I have 55 mains powered devices (Ikea and Philips lights, wall plugs). 48 battery powered devices (Sensors, fyrtur blinds, switches).

What could be the reason for this behaviour, and what can I do to make it stable?

My config file:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: xxxxxx
  password: xxxxxxx
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2434862-if00
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 62369
  channel: 25
  network_key:
    - x
    - x
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

## What happened
Lights stop responding to Zigbee2Mqtt.
## What did you expect to happen
Normal lights on/off for all lights.
## How to reproduce it (minimal and precise)
This happens spontaneoulsy, it seems, with no prior action
## Debug info
Zigbee2MQTT version: 1.22.0-2, Zigbee channel 25. Far away from any local WiFi channels (1, 6 and 8).
Adapter hardware: Conbee II
Adapter firmware version: 26720700, updated 7.nov.
HA Core 2021.11.1, Supervisor 2021.10.8
