### ISSUE TITLE
Device friendly names lost on configuration change and restart - Docker environment

### ISSUE THREAD

**Issue by adams-family** [Koenkk/zigbee2mqtt#9579]
## What happened

First of all, I'm new to here and it's more than likely that I'm doing something wrong - it's just not obvious :(

All devices' friendly names are lost when `configuration.yaml` is edited and zigbee2mqtt is restarted with `docker-compose restart`

## What did you expect to happen

Devices' friendly names should be preserved.

## How to reproduce it (minimal and precise)

  1. Joined a couple of Ikea devices to zigbee2mqtt
  2. Assigned them friendly names
  3. Edited configuration.yaml
  4. Restarted zigbee2mqtt with `docker-compose restart`
  5. All friendly names are gone and all devices are reset to their original hexa-names

My `docker-compose.yml` does contain a persistent volume for `data`:

```
version: '2.1'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB1:/dev/ttyACM0
```

## Debug info
Zigbee2MQTT version: 1.22.0 (commit #0a1fccf)
Adapter hardware: CC2652RB
Adapter firmware version: zStack3x0 (20210708)
