### ISSUE TITLE
Device not responding after backup and restore

### ISSUE THREAD

**Issue by xiki808** [Koenkk/zigbee2mqtt#9808]
## What happened
I'm creating a backup of my devices, by copying the contents of configuration.yml and database.db. All devices are restored fully after a clean setup except for one device. It shows on the dash but it does not respond. When I try to switch on or off the device I get the following logs:

```
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffed5d4f3', payload '{"linkquality":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffed5d4f3', payload '{"linkquality":null,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffed5d4f3', payload '{"linkquality":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffed5d4f3', payload '{"linkquality":null,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffed5d4f3', payload '{"linkquality":null,"state":"ON"}'
```

The device works if I try to pair it.

My coordinator is a Conbee II:

```
{"id":1,"type":"Coordinator","ieeeAddr":"0x00212effff05b5e3","nwkAddr":0,"manufId":4405,"epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[0,10,25],"outClusterList":[1,32,1280],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":100,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}
```

The device not working is a wall switch light:

```
{"id":2,"type":"EndDevice","ieeeAddr":"0x60a423fffed5d4f3","nwkAddr":19999,"manufId":4098,"manufName":"_TZE200_amp6tsvy","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_amp6tsvy","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff05b5e3","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1482240604},"lastSeen":1637656247447}
```

My configuration:

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://10.0.1.7
  user: admin
  password: *******
serial:
  port: /dev/ttyACM0
  disable_led: false
  adapter: deconz
frontend:
  port: 8080
advanced:
  baudrate: 115200
  rtscts: false
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  network_key:
    - 241
    - 44
    - 75
    - 98
    - 82
    - 44
    - 208
    - 90
    - 62
    - 22
    - 247
    - 84
    - 209
    - 248
    - 1
    - 165
devices:
  "0x60a423fffed5d4f3":
    friendly_name: "0x60a423fffed5d4f3"
  "0x00158d00053f429f":
    friendly_name: "0x00158d00053f429f"
  "0x00158d00046666fb":
    friendly_name: "0x00158d00046666fb"
  "0x00158d0005074649":
    friendly_name: "0x00158d0005074649"
  "0x00158d0006af712f":
    friendly_name: "0x00158d0006af712f"
```

## What did you expect to happen
I expect for the device to work after backup is restored straight away without the need to pair it.

## How to reproduce it (minimal and precise)
1. Backup devices, by copying the contents of configuration.yml and database.db
2. Clean install of Z2M
3. Paste back the contents into the respective file

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: Conbee II
Adapter firmware version: latest
