### ISSUE TITLE
external converter not working

### ISSUE THREAD

**Issue by anton3006** [Koenkk/zigbee2mqtt#9889]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/9850

<div type='discussions-op-text'>

<sup>Originally posted by **anton3006** November 26, 2021</sup>
I*m trying to use the Xiaomi aqara door sensor. There are ones automaticly  supported with model number MCCGQ11LM. I got another version with model number MCCGQ14LM which are stated as unsupported. I looked for solutions and found [this](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/xiaomi.js) zigbee-herdsman-converter which contains exactly my model. But after adding the file in the same location as my configuration.yaml and adding the external converter, nothing changes. I restarted, reconnected the sensor but it's not working. I'm not really into this topic and I'm glad about any help.

Here is my configuration:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.21:1883
  user: mqtt
  password: mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0019386F73-if00
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  external_converters:
    - xiaomi.js
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1
```

This is the relevant part of the [xiaomi.js converter](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/xiaomi.js)(line 43 to 51) but I imported everthing: 

```
module.exports = [
    {
        zigbeeModel: ['lumi.magnet.acn001'],
        model: 'MCCGQ14LM',
        vendor: 'Xiaomi',
        description: 'Aqara E1 door & window contact sensor',
        fromZigbee: [fz.ias_contact_alarm_1, fz.aqara_opple],
        toZigbee: [],
        exposes: [e.contact(), e.battery(), e.battery_voltage()],
    }
```

And this are the relevant logs:

```
Zigbee2MQTT:info  2021-11-26 11:10:31: Successfully interviewed '0x54ef4410002598c8', device has successfully been paired
Zigbee2MQTT:warn  2021-11-26 11:10:31: Device '0x54ef4410002598c8' with Zigbee model 'lumi.magnet.acn001' and manufacturer name 'LUMI' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:info  2021-11-26 11:10:31: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x54ef4410002598c8","ieee_address":"0x54ef4410002598c8","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:info  2021-11-26 11:10:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x54ef4410002598c8","supported":false},"type":"pairing"}'
Zigbee2MQTT:debug 2021-11-26 11:10:38: Received Zigbee message from '0x54ef4410002598c8', type 'attributeReport', cluster 'genBasic', data '{"modelId":"lumi.magnet.acn001"}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2021-11-26 11:10:38: Received message from unsupported device with Zigbee model 'lumi.magnet.acn001' and manufacturer name 'LUMI'
```
And here a screenshot of the device:
![image](https://user-images.githubusercontent.com/45878290/143567435-208ba48c-0855-4418-9fa5-55aed921f248.png)

I hope someone knows a solution. 
Thank you!

</div>
