### ISSUE TITLE
Timestamps in Console and Syslog logs are shown in different timezones

### ISSUE THREAD

**Issue by IgorAga** [Koenkk/zigbee2mqtt#9905]
Timestamp in Console log output is shown in local timezone (UTC+3):

> Zigbee2MQTT:info  2021-11-29 09:40:40: Logging to console only'
> Zigbee2MQTT:info  2021-11-29 09:40:41: Starting Zigbee2MQTT version 1.22.0 (commit #df0543d4)
> Zigbee2MQTT:info  2021-11-29 09:40:41: Starting zigbee-herdsman (0.13.164)

while the same log entries in Syslog are shown in UTC:

> Nov 29 06:40:40 192.168.0.2 zigbee2mqtt Logging to console only'
> Nov 29 06:40:41 192.168.0.2 zigbee2mqtt Starting Zigbee2MQTT version 1.22.0 (commit #df0543d4)
> Nov 29 06:40:41 192.168.0.2 zigbee2mqtt Starting zigbee-herdsman (0.13.164)

Log config is as following:

```
  log_level: debug
  log_output: ['console', 'syslog']
  log_syslog:
    app_name: zigbee2mqtt
    host: 192.168.0.6
    localhost: 192.168.0.2
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
```
