### ISSUE TITLE
Lights turn on after restart of zigbee2mqtt - workaround?

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#992]
I have a xiaomi double switch that turns on my lights. 

After a restart zigbee2mqqt publishes all the states again and so my automation in homeassistant gets triggered and turns on my lights. 

Is there a way to bypass this? May turning of publishing the events at restart for certain devices?

My automation looks like this:

```
- alias: Zigbee Doppelschalter - left
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.zigbee_doppelschalter_click
  condition:
    - condition: state
      entity_id: sensor.zigbee_doppelschalter_click
      state: 'left'          
  action:
    - service: light.turn_on
      entity_id: light.licht
```

My config in zigbee looks like this:

```
  '0xXXX':
    friendly_name: Zigbee Doppelschalter
    retain: false
```
